- chain/chain-primitives/src/error.rs
- chain/chain/src/validate.rs
- chain/client/src/client.rs
- chain/client/src/stateless_validation/chunk_validator/mod.rs
- chain/client/src/tests/process_blocks.rs
- core/primitives/src/congestion_info.rs
- integration-tests/src/tests/client/features/congestion_control.rs
Added the validation of the congestion info fields. As far as I can tell this should cover both stateful and stateless validation transition. I added a unit test for the relevant method as well but I am not actually convinced that this is sufficient. I will see if I can add a simple nayduck end to end test as well. I also checked that the test will pass after cc stabilization.
>  feat(congestion_control) - congestion info validation 

- chain/client/src/client.rs
- chain/client/src/stateless_validation/chunk_validator/mod.rs
- integration-tests/src/tests/client/features/adversarial_behaviors.rs
This is an attempt to create a submittable version of [this commit](https://github.com/near/nearcore/commit/0c6c82266302c3b115d73c4df66cdc545ba37d37).
After this change chunk-witness validation errors will lead to panic for non-production chains (eg. mocknet and localnet). mainnet and testnet will continue to log error and continue on validation errors.
We also add a method to enable/disable this for tests, especially for adversarial behavior where the chunk validation errors are intended as part of the test scenario.
> Panic in debug mode or non-prod chain when there is a chunk-witness validation error

- chain/client/src/stateless_validation/chunk_validator/mod.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/test_utils/setup.rs
- integration-tests/src/tests/client/features/multinode_test_loop_example.rs
- integration-tests/src/tests/network/runner.rs
- nearcore/src/lib.rs
This adds logic to
`PartialWitnessActor::validate_partial_encoded_state_witness()` that checks that the height is greater than the current final head height (as is done in `Client::process_chunk_state_witness()`), and not more than five ahead of the current head height, similar to what's done in `EncodedChunksCache::height_within_horizon()`
For now we read the head and final head heights directlly from the database, but in the future this should be changed so that we make a request to the client for this info
Related issue: #11301
> [stateless_validation] validate incoming partial witness heights

- .github/workflows/neard_release.yml
In https://github.com/near/nearcore/pull/10521 I made checkout process to fetch all nearcore branches.
This instead messed with master branch builds version because these are fetching latest annotated tag:
```
➜  nearcore git:(master) git "describe" "--always" "--dirty=-modified" "--tags" "--match=[0-9]*"  
1.36.1-653-g2b01868d4
```
To avoid this, we will be fetching with depth 1(default fetch-depth) when workflow is triggered by master branch push events.
```
➜  nearcore git:(master) git "describe" "--always" "--dirty=-modified" "--tags" "--match=[0-9]*"  
dfa392b
```
> GHA workflow: Master build neard version

- benchmarks/continous/db/ft_transfer_schema.sql
Related to #11405.
Not sure if this directory makes sense, but I couldn't find another place where this should obviously be. I'd like to push more files with code/commands related to db setup and admin, so I think having a dedicated directory can be useful.
Proposing this table as a starting point, probably we'll have multiple iterations anyway as benchmarks are fleshed out.
> bench/ft_transfer: add db table

- pytest/tests/mocknet/mirror.py
Allow targeted commands from mirror.py. Every command can be issued only for a subset of nodes by using the following filters:
`mirror --help`
```
Control a mocknet instance
options:
...
--type {all,nodes,traffic}
Type of hosts to select
--filter FILTER       Filter through the selected nodes using regex.
...
```
`mirror --filter="-dumper" run-cmd --cmd "ls" `
```
[2024-05-29 11:43:25] INFO: created configured logger, name test, level 20
[2024-05-29 11:43:26] INFO: created configured logger, name serializer, level 20
[2024-05-29 11:43:32] INFO: Running cmd on mocknet-*******-dumper
[2024-05-29 11:43:33] INFO: mocknet-*******-dumper:
stdout:
data
logs
neard-logs
stderr:
```
`mirror --type="nodes" run-cmd --cmd "ls" ` # will target all nodes
`mirror --type="traffic" run-cmd --cmd "ls" ` # …
> feat(forknet): Add targeted commands to mirror.py

- pytest/tests/loadtest/locust/common/congestion.py
It looks like in the refactor #11410 the congestion load was not updated and  still returned  bytes instead of SignedTransaction. This leads to key errors during serialization when running the congestion load.
> fix(loadtest): bug fix in congestion load

- pytest/tests/loadtest/locust/common/base.py
- pytest/tests/loadtest/locust/locustfiles/ft.py
This PR aims to make it easier to achieve a constant TPS load with FT transfer workload.
We achieve this with two changes:
1. Transactions are now sent without waiting for their completion
2. We use `constant_throughput(1.0)` which means that each Locust user tries to send one transaction per second.
> locust: Send FT transfers asynchronously

- nightly/pytest-sanity.txt
- pytest/tests/sanity/congestion_control.py
- runtime/near-test-contracts/test-contract-rs/src/lib.rs
- runtime/near-vm-runner/src/imports.rs
- runtime/near-vm-runner/src/logic/logic.rs
Implemented a nayduck test for congestion control. It's more complex than I was hoping for and it still only check a simple scenario all to one, one hop transactions. Still it's a good starting point.
> test(congestion_control) - Implemented nayduck tests for congestion control

- core/store/src/db.rs
- core/store/src/db/testdb.rs
- core/store/src/opener.rs
- integration-tests/src/tests/client/features/multinode_test_loop_example.rs
Somewhat hacky but very simple and very effective speedup of the multinode test. When grabbing a state snapshot, instead of having to use rocksdb, we can now use create_test_store(). The reason why it didn't work earlier was because the TestDB didn't support snapshotting. But that's just doing a copy of the data so with one conditional, we're able to make this happen.
This shortens the test from needing >100s to only 5s.
> [Testing] Speed up multinode_test_loop_example by 20x.

- pytest/tests/loadtest/locust/README.md
This is a more convenient way to scale Locust on a single machine.
> docs: Add documentation about Locust processes

- chain/client/src/stateless_validation/chunk_validator/orphan_witness_handling.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
This is mostly to prevent malicious chunk producer from sending a witness with a valid height and old epoch id.
Part of #11301.
> feat: add partial witness epoch check

- chain/client/src/info.rs
- core/primitives/src/telemetry.rs
Adding protocol version information and chain_id to telemetry data.
Chain_id is required as currently we have no way of knowing what chain telemetry data source running.
https://github.com/near/nearcore/issues/4355
Tested with a http server to make sure data is correct. From debug logs:
`2024-05-31T15:13:30.356984Z DEBUG handle{handler="TelemetryEvent" actor="TelemetryActor>"}: telemetry: msg=TelemetryEvent { content: Object({"agent": Object({"build": String("1.36.1-666-g1fec7a712"), "name": String("near-rs"), "protocol_version": Number(67), "version": String("trunk")}), "chain": Object({"account_id": String("test.near"), "block_production_tracking_delay": Number(0.1), "chain_id": String("mycustomnetwork"), "is_validator": Bool(true), "latest_block_hash": …
> Add protocol and chain id to telemetry data

- pytest/tests/mocknet/helpers/neard_runner.py
- pytest/tests/mocknet/mirror.py
- pytest/tests/mocknet/node_handle.py
Add two parameters to update-binaries to allow url update for an epoch.
Usage:
`mirror update-binaries ` # will redownload all binaries in `config.json`
`mirror amend-binaries --neard-binary-url <some url> --epoch-height 0` # will update the url for epoch height 0 in `config.json` and then download all binaries. 
`mirror amend-binaries --neard-binary-url <some url> --binary-idx 0` # will update the url for the first binary which is at epoch height 0 in `config.json` and then download all binaries. 
`mirror amend-binaries --neard-binary-url <some url> --epoch-height 10` # will insert the url for epoch height 10 in `config.json` and then download all binaries. 
`mirror amend-binaries --neard-binary-url <some url> --binary-idx 1` # will update the url for the second binary which is at epoch …
> feat(forknet): allow url update when using update-binaries cmd

- chain/chain/src/chain.rs
- chain/client/src/client_actor.rs
- chain/client/src/stateless_validation/chunk_validator/mod.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
- chain/client/src/test_utils/test_env.rs
- core/primitives/src/stateless_validation.rs
- integration-tests/src/tests/client/features/orphan_chunk_state_witness.rs
- integration-tests/src/tests/client/features/stateless_validation.rs
This PR implements check for partial state witness metadata fields (`epoch_id`, `shard_id`, `height_created`) after decoding complete state witness. This is needed to protect against malicious chunk producer providing incorrect metadata in the partial witness.
Large part of this PR is about moving state witness decoding (decompression + borsh-deserialization) from client to partial witness actor. This is required to implement the check, but also a nice change on its own since wintess decompression can take several dozens of milliseconds, so it is better to avoid blocking client actor.
Closes #11303.
> feat: check partial witness metadata

- chain/chain/src/test_utils/validator_schedule.rs
- chain/client/src/info.rs
- chain/client/src/sync/block.rs
- chain/jsonrpc-primitives/src/errors.rs
- chain/network/src/store/mod.rs
- core/primitives/src/trie_key.rs
- core/primitives/src/types.rs
- pytest/lib/utils.py
- runtime/near-vm-runner/src/logic/logic.rs
- runtime/near-vm-runner/src/logic/tests/gas_counter.rs
- runtime/runtime-params-estimator/src/lib.rs
- runtime/runtime/src/balance_checker.rs
- runtime/runtime/src/state_viewer/mod.rs
- utils/near-cache/src/cell.rs
- utils/near-cache/src/sync.rs
remove duplicated words in comments to improve readability.
> chore: remove duplicated words in comments

- chain/client-primitives/src/debug.rs
- chain/client/src/chunk_inclusion_tracker.rs
- chain/client/src/debug.rs
- chain/jsonrpc/res/last_blocks.js
Adds a new metric in the `last_blocks` debug page: `endorsement(stake)`. This indicates what percentage of the 'validators stake' has endorsed a given chunk in a block. 
The addition works only if the stateless validation feature is enabled.
> feat(debug): add chunk endorsement ratio to last_blocks debug page

- chain/client/src/stateless_validation/chunk_endorsement_tracker.rs
Fixes: https://github.com/near/nearcore/issues/11445
In the new version all operations are done by `ChunkEndorsementTrackerInner` which has `&mut self` on all methods, which prevents most races. Apart from that when adding a pending endorsement we check whether the header for this chunk has already been seen and if so we treat this endorsement as non-pending.
> Fix race condition in ChunkEndorsementTracker

- chain/chain/src/stateless_validation/chunk_validation.rs
- chain/chain/src/validate.rs
The header protocol version was not set correctly in the stateless validation context. It caused a mismatch between the congestion info in the header and congestion control not being enabled (in the wrong protocol version).
> fix(congestion_control) - set correct header protocol version

- chain/client/src/test_utils/test_env.rs
- integration-tests/src/tests/client/features/stateless_validation.rs
This test performs a protocol upgrade from the version before StatelessValidationV0 to the binary's PROTOCOL_VERSION. This test would have caught the issue fixed in #11469. As is, in nightly, the test checks protocol upgrade from 79 to 143. 
Note that we also have protocol upgrade tests for congestion control. I think this test didn't catch the mentioned issue because it's configured with only one client and (I think) it automatically accepts its own chunks. It was much easier to reuse the stateless validation test configuration than to reimplement it in congestion control tests. Also this test seems generally useful.
> test(stateless_validation) - Implemented a protocol upgrade integration test

- integration-tests/src/tests/client/chunks_management.rs
Hooray.
https://nayduck.nearone.org/#/run/130
> test: reenable chunk management tests

- core/parameters/res/runtime_configs/87.yaml
- core/parameters/src/config.rs
- core/primitives/src/congestion_info.rs
- integration-tests/src/tests/client/cold_storage.rs
- nearcore/src/test_utils.rs
Setting the max_congestion_missed_chunks to 2. This means that at most 2 (+/-1) chunks worth of outgoing receipts can accumulate before all shards will stop forwarding any receipts to the shard with missing chunks. This is a relatively conservative limit to minimize the impact of incoming receipts on source_receipt_proofs size in the state witness. I expect it to have minimal impact on the total throughput of the chain since it's quite rare to see more than one missed chunk in a row. 
It's also worth noting that just having one missed chunk is a special case that will not increase the congestion level:
https://github.com/near/nearcore/blob/dd1e2786bac3622020f6e684e986eb426751600a/core/primitives/src/congestion_info.rs#L65-L68
> config(congestion_control) - set max_congestion_missed_chunks to 2

- runtime/runtime/src/lib.rs
This is to avoid triggering bootstrapping multiple times in the case of missed chunks.
> fix(congestion): Don't bootstrap congestion info on old chunks

- .config/nextest.toml
When I run `cargo nextest run --cargo-profile dev-release` I often get timeouts because some tests can run for more than 120 seconds:
```
PASS [  45.690s] estimator-warehouse::bin/estimator-warehouse tests::test_full_estimator
PASS [  48.150s] integration-tests tests::client::process_blocks::contract_precompilation_tests::test_two_deployments
PASS [  40.543s] near-client tests::query_client::test_state_request
PASS [  68.920s] integration-tests tests::client::sync_state_nodes::test_dump_epoch_missing_chunk_in_last_block
PASS [ 131.637s] integration-tests tests::client::state_dump::test_state_sync_w_dumped_parts
```
This is annoying, when a test timeouts the test run is considered "failed" and it spams the whole console with test logs.
Let's increase the timeout duration to 3s so that the …
> Increase timeout for tests

- nearcore/res/example-config-gc.json
- nearcore/res/example-config-no-gc.json
- nearcore/src/config.rs
Since #11444 the telemetry data contains the `chain-id`, we can now use the multichain endpoint to send telemetry. 
With this change we gain resiliency to misconfiguration: for instance `testnet` nodes with config partially copied from `mainnet` will report their telemetry correctly labeled as `testnet`.
> chore: use the new multi-chain endpoint for N1 telemetry

- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
- core/primitives/src/reed_solomon.rs
- core/primitives/src/stateless_validation.rs
This PR adds check a single witness part size based on max witness size. For now the limit is the same as max network message size, that will be adjusted in a separate PR.
Closes #11304.
> feat: add size check for state witness part

- chain/client-primitives/src/debug.rs
- chain/client/src/debug.rs
- tools/debug-ui/src/RecentEpochsView.tsx
- tools/debug-ui/src/SnapshotHostsView.tsx
- tools/debug-ui/src/api.tsx
Couple of minor improvements which help to understand the state of decentralized state sync.
> debug-ui: show epoch heights and sort snapshot hosts

- runtime/runtime/src/lib.rs
To better distribute the load when multiple shards are fully congested, we can use the block height + shard id as the seed for selecting which of the other shards can forward receipts in the next block height.
> congestion: seed round-robin by shard id

- chain/chain/src/runtime/mod.rs
- core/parameters/src/config.rs
- integration-tests/src/tests/client/features/multinode_stateless_validators.rs
- integration-tests/src/tests/client/features/multinode_test_loop_example.rs
- nearcore/src/test_utils.rs
The `test_in_memory_trie_node_consistency` was failing occasionally because the config with disabled congestion control wasn't properly passed into the nightshade runtime. Also setting the threshold for rejecting transactions from 1 to 2 because otherwise some could still get rejected under full congestion.
> fix(test) - fix flaky test 

- chain/client/src/stateless_validation/partial_witness/encoding.rs
- chain/client/src/stateless_validation/partial_witness/mod.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
This PR includes the following:
* Move everything related to partial witness reed solomon encoding to a separate module
* Introduce wrapper around `Option<ReedSolomon>` to encapsulate logic around handling a single part which is currently spread around the codebase.
> refactor: introduce partial witness encoding mod

- core/primitives/src/upgrade_schedule.rs
- core/primitives/src/version.rs
- integration-tests/src/tests/client/process_blocks.rs
A rather trivial solution to a potential inconvenience introduced by #11368: due to a human error or a very long epoch multiple protocol upgrades could end up being applied together at an epoch's boundary.
This PR change the protocol upgrade voting to select at most one upgrade per epoch.
> feat(protocol_upgrade): nodes won't vote multiple protocol upgrades together 

- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
- core/primitives/src/stateless_validation.rs
This PR includes the following:
* Set size limit for compressed witness to 32MiB. This is at least twice as big as the witness we expected to handle, so it give us quite some safety margin.
* Set size limit for the compressed witness to 64MiB. Same as above, this values give us pretty big margin on top of witness sizes we expect.
* Reduce partial witness cache size to 40 entries to limit memory usage at ~1.3GiB. 40 entries should be more than enough to handle all kinds of crazy chain forks 🙃
> feat: adjust witness size limits

- chain/chain/src/runtime/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/epoch-manager/src/shard_tracker.rs
- chain/epoch-manager/src/test_utils.rs
- chain/epoch-manager/src/tests/mod.rs
- chain/epoch-manager/src/validator_selection.rs
- chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
- core/chain-configs/src/genesis_config.rs
- core/chain-configs/src/test_genesis.rs
- core/primitives/src/epoch_manager.rs
- core/primitives/src/shard_layout.rs
- tools/fork-network/src/cli.rs
- utils/mainnet-res/res/mainnet_genesis.json
It would be very convenient to set this value to 1 in tests to ensure that most of validators are assigned to validate only one chunk, so we have better control to test rewards and kickouts. Adding this field to genesis until it's not too late.
> chore: make target_validator_mandates_per_shard configurable

- scripts/ft-benchmark.sh
Without running locust in nohup, shell script waits until locust finish and only after this run data sender
> [ft-benchmark] run locust in nohup

- chain/client/src/client_actor.rs
- chain/client/src/sync/state.rs
- chain/client/src/test_utils/test_env.rs
- core/parameters/src/config.rs
- core/parameters/src/view.rs
- core/primitives-core/src/version.rs
- core/primitives/src/action/delegate.rs
- core/primitives/src/state.rs
- runtime/near-test-contracts/src/lib.rs
- runtime/near-vm/test-generator/src/lib.rs
- runtime/near-vm/vm/src/vmoffsets.rs
- tools/congestion-model/src/lib.rs
Fixes the errors I got while running `cargo doc`. Also fixes some (not all 😄) warnings. 
I checked that the changes look fine in the rendered documentation.
> fix(doc): fix errors encountered during cargo doc and a few warnings

- pytest/lib/cluster.py
- pytest/tests/sanity/slow_chunk.py
At the beginning of the test there are a few missing blocks leading to congestion control kicking in and rejecting the transactions. I added a few blocks wait to allow the chain to warm up before starting the actual test.
> fix(nayduck) - fix slow_chunk test - bypass congestion control

- chain/jsonrpc/src/lib.rs
- pytest/lib/cluster.py
- pytest/tests/sanity/congestion_control.py
The default timeouts introduced in #11397 mean that a failing requests will take about 1 minute to complete including the timeouts. In the congestion control test we intentionally overload the chain and expect that some transactions will be rejected. Combined this means that the test would take 20 minutes to complete. The fix is to better configure the timeouts and retries in the nayduck infra.
>  fix(nayduck) - fix congestion control test - configure timeouts 

- Makefile
- scripts/binary_release.sh
Adding near-sandbox which was removed in https://github.com/near/nearcore/pull/10223.
near-sandbox is used by near-workspaces which is an SDK for end-to-end contracts testing that automatically spins up localnet using near-sandbox (neard with extra features useful for testing - state patching, time travel). There are JS and Rust SDKs and it wouldn’t be efficient to build nearcore from scratch on the user machine and CI, so it relies on the prebuilt binaries. 
store-validator and genesis-populate are not added back.
> Add near-sandbox back to S3

- benchmarks/continous/db/README.md
- benchmarks/continous/db/tool/orm/migrations/2024-06-12-094545_simplify_permissions/down.sql
- benchmarks/continous/db/tool/orm/migrations/2024-06-12-094545_simplify_permissions/up.sql
As the db does not contain sensitive data, permission management can be simplified by granting `pg_read_all_data` and `pg_write_all_data` instead of more fine grained permissions.
> bench: simplify db permissions

- chain/chain/src/stateless_validation/chunk_validation.rs
- chain/chain/src/validate.rs
- core/primitives-core/src/version.rs
- core/primitives/src/congestion_info.rs
The stateless validation was released without the allowed shard validation. Now that I want to add it back by adding #11526 it's going to be a protocol upgrade and should be handled as such. When stabilizing we can remove it to keep the code cleaner.
> chore(congestion_control) - Added a dedicated protocol feature for allowed shard validation

- core/primitives-core/src/version.rs
- core/primitives/src/epoch_manager.rs
We had this code change that forced 20 block producers on chain ids that are not mainnet. However, it makes no sense in stateless validation where there is no chunk-only producers. Fixed this by introducing a new protocol version.
> fix: no chunk-only producer in stateless validation

- chain/client/src/stateless_validation/partial_witness/encoding.rs
Short term fix for the current stuck statelessnet.
We have a bunch of validator nodes offline due to which we are not able to gather the 80% parts required for reconstructing the state witness.
This PR changes this to 60% as a short term fix. We would have to reason about a more long term solution for partial witness distribution.
> [stateless_validation] Change ratio of data parts needed for partial witness distribution from 0.8 to 0.6

- tools/debug-ui/src/entity_debug/keys.tsx
Currently debug ui doesn't allow cryptohash-keys of length 43, though they are completely valid. For example, epoch id `nzPSmXu6KDoyamTLyK4j8s6eYw9jUfX2MVuC9zW8A6p` does exist in testnet.
This probably wasn't caught before because these keys are more rare than ones of length 43.
> fix(debug-ui): CryptoHash key validity

- chain/client/src/stateless_validation/partial_witness/encoding.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
- core/primitives-core/src/version.rs
Follow up from PR https://github.com/near/nearcore/pull/11571 where we need to have the change in ratio under a protocol upgrade.
> [stateless_validation] Partial witness RATIO_DATA_PARTS under protocol config

- Cargo.toml
- chain/chain/Cargo.toml
- chain/client/Cargo.toml
- chain/client/src/client.rs
- chain/client/src/view_client_actor.rs
- chain/jsonrpc/Cargo.toml
- chain/jsonrpc/jsonrpc-tests/Cargo.toml
- core/o11y/Cargo.toml
- integration-tests/Cargo.toml
- nearcore/Cargo.toml
- neard/Cargo.toml
- runtime/near-vm-runner/Cargo.toml
- runtime/near-vm-runner/src/wasmtime_runner.rs
- runtime/near-vm/compiler/src/translator/environ.rs
- runtime/near-vm/engine/src/universal/engine.rs
- runtime/near-vm/engine/src/universal/executable.rs
- runtime/near-vm/test-api/src/sys/externals/function.rs
- runtime/near-vm/test-api/src/sys/native.rs
- runtime/near-vm/vm/src/lib.rs
- runtime/near-vm/vm/src/trap/traphandlers.rs
- runtime/runtime-params-estimator/Cargo.toml
- runtime/runtime-params-estimator/emu-cost/Dockerfile
- runtime/runtime/Cargo.toml
- rust-toolchain.toml
- tools/epoch-sync/src/cli.rs
- tools/state-viewer/Cargo.toml
- tracing/Cargo.toml
- tracing/Dockerfile
- utils/stdx/src/lib.rs
Release notes: https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html
Compiler found some dead code.  Clippy complained about bunch of new
stuff¹.  Inline const expressions got stabilised which allowed to
simplify static checks in stdx.
Apart from that I’ve not found any other code that could be improved
though places where the new stabilised features could be used are
non-trivial to look for.
¹ I’m not sure if I like the new clippy::missing_transmute_annotations
check.  At least in nearcore it feels very noisy without actually
doing anything good.  I’ve added annotation in a few places but
where the annotation would be too long I just disabled that check.
Perhaps it should be disabled globally?
> rust: 1.79.0

- scripts/ft-benchmark.sh
Before I logged it using redirecting outputs of whole script in the cron job, but it leaded to mix of outputs of several instances of script in one file
> [ft-benchmark] debug logging

- chain/chain/Cargo.toml
- chain/indexer/Cargo.toml
- core/primitives/src/types.rs
- core/store/Cargo.toml
- core/store/src/metadata.rs
- core/store/src/migrations.rs
- nearcore/src/migrations.rs
Properly migrate to new ValidatorKickoutReason enum because order of variants matter for borsh serialization.
Statelessnet was started already from new enum so migration must be skipped for it.
Needs merge to unblock testnet canaries https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/Testnet.20canaries.20all.20crashed/near/444467227
> fix: make new ValidatorKickoutReason backwards compatible

- runtime/runtime/src/lib.rs
- runtime/runtime/src/metrics.rs
The metric counts the number of chunks where the number of processed receipts was limited by a certain factor.
Here's an example visualisation from a localnet node with ft.py loadtest at ~500 TPS:
We can see that for ~20% of chunks on shard 0 the number of processed receipts was limited by the `compute_limit`.
This will allow us to see what's the bottleneck for receipt processing - is it the compute limit, storage proof limit, or something else.
> Add a metric showing what limited number of processed receipts in a chunk

- docs/architecture/how/resharding.md
remove TODO to use the master link of NEP-0508
> chore: use the master link of NEP-0508

- benchmarks/continous/db/tool/README.md
Provide more detailed instructions to set up a machine to use the CLI tool on it.
> bench/db: extend docs on setup for cli

- scripts/ft-benchmark.sh
- scripts/run-ft-benchmark.py
- scripts/start-benchmark.sh
This is a step to manual triggering of `ft-benchmark`.
Note: I think this lock file don't provide 100% protection, but IMO probability of two actors triggering this script within time of creating lock file is small enough.
> [ft-benchmark] manual benchmark triggering

- .github/workflows/near_crates_publish.yml
- Cargo.toml
Run the publish crates WF on release.
> fix(release) publish crates on nearcore release

- pytest/tests/loadtest/locust/common/base.py
This makes it possible to understand which transactions are actually failing.
> locust: Improve error messages

- pytest/lib/mocknet.py
This allows scripts that use this file to specify which project they want to use without forcing the user to set environment variable.
> mocknet: Add ability to customize project

- core/store/src/trie/accounting_cache.rs
- core/store/src/trie/mem/loading.rs
- core/store/src/trie/trie_recording.rs
- core/store/src/trie/trie_tests.rs
- core/store/src/trie/update.rs
- runtime/near-vm-runner/fuzz/fuzz_targets/diffrunner.rs
- runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
- runtime/near-vm-runner/src/code.rs
- runtime/near-vm-runner/src/logic/dependencies.rs
- runtime/near-vm-runner/src/logic/errors.rs
- runtime/near-vm-runner/src/logic/mocks/mock_external.rs
- runtime/near-vm-runner/src/logic/mod.rs
- runtime/near-vm-runner/src/near_vm_runner/runner.rs
- runtime/near-vm-runner/src/runner.rs
- runtime/near-vm-runner/src/tests/cache.rs
- runtime/near-vm-runner/src/tests/fuzzers.rs
- runtime/near-vm-runner/src/tests/rs_contract.rs
- runtime/near-vm-runner/src/tests/test_builder.rs
- runtime/near-vm-runner/src/tests/ts_contract.rs
- runtime/near-vm-runner/src/wasmer2_runner.rs
- runtime/near-vm-runner/src/wasmer_runner.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
- runtime/runtime-params-estimator/src/function_call.rs
- runtime/runtime-params-estimator/src/gas_metering.rs
- runtime/runtime-params-estimator/src/lib.rs
- runtime/runtime-params-estimator/src/trie.rs
- runtime/runtime/src/actions.rs
- runtime/runtime/src/ext.rs
- runtime/runtime/src/state_viewer/mod.rs
This simplifies the interface to the contract runtime and makes it
easier to split up the loading vs. instantiation vs. execution as it
gets exposed as an API from the contract runtime.
Thematically `VMContext` is probably more appropriate place for storing
some of this functionality, however Externals is quite a bit more of a
straightforward home for this functionality by the virtue of it already
having access to the storage where the contracts live in.
The downside of this being stored in `Externals` is precisely that until
this point `Externals` has been entirely focused on providing an interface
for host functions to interact with. And now the trait is gaining methods
that are slightly outside of that area of responsibility.
> runtime: implement loading the contract through Externals

- tools/state-viewer/src/cli.rs
- tools/state-viewer/src/commands.rs
- tools/state-viewer/src/congestion_control.rs
- tools/state-viewer/src/lib.rs
- tools/state-viewer/src/util.rs
Adding a tool for printing and re-calculating the congestion info. 
I also did a small refactoring - I moved some utility methods to an utils file. 
I'm going to use it to perform bootstrapping benchmarking. The plan is:
* Spin up a mainnet RPC node - this is in order to have a real-life db. 
* Load the delayed receipts queue with predefined number/ size/ gas of receipts. What receipts exactly is yet to be decided. This would likely lead to inconsistent db state but that is fine. 
* Run the `bootstrap` command introduced in this PR and measure the time it takes.
> tool(congestion) - Adding neard subcommand for debugging congestion control

- scripts/ft-benchmark-data-sender.py
- scripts/run-ft-benchmark.py
- scripts/start-benchmark.sh
With this PR we will be finally able to run benchmark and send data to DB fully automatically
> [ft-benchmark] some fixes for benchmark infra

- runtime/near-vm-runner/src/logic/errors.rs
- runtime/near-vm-runner/src/near_vm_runner/runner.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
- runtime/runtime/src/conversions.rs
This largely mirrors the code in near_vm_runner module. I heard some
people pondering what it would be like to use a higher quality backend.
Outside LLVM, Cranelift is by far the next in line in produced code
quality. Since we already have wasmtime in place, might as well wire it
up completely for a full experience.
Based on top of #11529
Part of #11319
> wasmtime: add caching of executables and artifacts

- runtime/near-vm-runner/src/logic/logic.rs
- runtime/near-vm-runner/src/logic/mocks/mock_memory.rs
- runtime/near-vm-runner/src/logic/tests/vm_logic_builder.rs
- runtime/near-vm-runner/src/logic/vmstate.rs
- runtime/near-vm-runner/src/near_vm_runner/runner.rs
- runtime/near-vm-runner/src/wasmer2_runner.rs
- runtime/near-vm-runner/src/wasmer_runner.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
This is a part of an effort to drop the lifetime from the `VMLogic` structure in order to make it more straightforward to have it live for a longer duration alongside the instance and not force our hand in pretty much "create-execute contract-drop" flow.
Part of #11319
> vmlogic: maintain memory by a Box

- chain/chain/src/stateless_validation/chunk_validation.rs
- chain/chain/src/validate.rs
- core/primitives-core/src/version.rs
- core/primitives/src/congestion_info.rs
This feature was only needed for the protocol upgrade in statelessnet. Now that statelessnet is past this feature we can get rid of it and simplify the code. The simplification is not needing to pass the protocol version around.
> cleanup(congestion_control) - remove CongestionControlAllowedShardValidation

- core/primitives/src/epoch_manager.rs
Make `TestnetFewerBlockProducers` only apply to testnet to avoid breaking other testing network due to the hardcoded change of block producers. Specifically, increasing the number of block producers will make things break due to `num_total_parts` computation that only looks at what is in genesis and if genesis protocol version is between the protocol version of `TestnetFewerBlockProducers` and `NoChunkOnlyProducers`, it will forcefully set the number of block producer seats to 20, regardless of what is set in genesis. Even worse, any attempt to increase that later in the code won't work.
> fix: make TestnetFewerBlockProducers only apply to testnet

- pytest/tests/loadtest/locust/common/base.py
This allows parallelism across requests issued through the same NearNodeProxy. Alternative would be to use different proxies, but this can be tricky in calls like `on_locust_init` and `ft_contract.create_passive_users`.
> locust: Use a new session for each request

- pytest/tests/loadtest/locust/common/base.py
As they ran out of funds when creating 10M accounts.
> locust: Increase initial worker balance

- Cargo.lock
- genesis-tools/genesis-populate/Cargo.toml
- genesis-tools/genesis-populate/src/lib.rs
In forknet the genesis may contains some delayed / buffered receipts. It's important to initialize the congestion info correctly otherwise integer overflow may happen when updating the congestion info. 
This is untested since I don't know how, looking for hints here :)
> feat(congestion) - Initialize congestion info in the genesis-populate tool

- chain/network/src/config_json.rs
- chain/network/src/peer_manager/network_state/tier1.rs
- chain/network/src/peer_manager/tests/tier1.rs
- chain/network/src/stun/mod.rs
- chain/network/src/stun/testonly.rs
- chain/network/src/stun/tests.rs
- chain/network/src/tcp.rs
When nodes query an address such as `stun.l.google.com:19302` for which there exist both IPv4 and IPv6 records, `tokio::net::UdpSocket::connect` chooses one arbitrarily.
We should make sure to query the appropriate server based on the IP version of the node's TCP listener address.
> network: pick STUN server to match node_addr IP version

- core/primitives/src/types.rs
- core/store/src/metadata.rs
- core/store/src/migrations.rs
- nearcore/src/migrations.rs
I tried #11569 to solve validator kickout enum issue to get mainnet and statelessnet aligned. But because we reset statelessnet, we can get all ValidatorKickoutReasons in line. This is the easiest solution.
DB version for latest release is 38, so removing 40 is not an issue. 39 must stay.
> fix: revert db version 40

- Cargo.toml
Something about this spelling no longer working starting with 2024 edition.
> chore: resolve a warning from cargo

- scripts/ft-benchmark.sh
Here I switch script I'm using in cron job for regular runs to using new scripts. We can't just schedule `python3 new-script.py` on cron, because cron have a bit different environment compared to just running python file on the machine and it requires updating `PATH`. 
With current updates I agree that this script should be renamed, but soon will send PR with massive renamings and relocatings of ft-benchmark related files.
> [ft-benchmark] switch cron job to new scripts

- chain/client/src/stateless_validation/chunk_validator/orphan_witness_handling.rs
See https://github.com/near/nearcore/pull/11400#issuecomment-2182650051
It seems non-validator nodes still call `process_ready_orphan_witnesses_and_clean_old` and logging an error in such case is spammy.
> fix: spammy log - not a validator

- chain/chain/src/tests/simple_chain.rs
- chain/client/src/client.rs
- chain/client/src/sync/header.rs
- chain/client/src/test_utils/client.rs
- chain/client/src/tests/query_client.rs
- chain/network/src/network_protocol/testonly.rs
- core/primitives/benches/serialization.rs
- core/primitives/src/block.rs
- core/primitives/src/block_header.rs
- core/primitives/src/test_utils.rs
- core/primitives/src/version.rs
- integration-tests/src/tests/client/challenges.rs
- integration-tests/src/tests/client/process_blocks.rs
- integration-tests/src/tests/nearcore_utils.rs
This change is needed to make setting protocol version in block compatible with test loop that uses fake clock.
> [test] Use clock in get_protocol_version with upgrade schedule

- chain/chain/src/chain.rs
- chain/client/src/client.rs
Currently we remove obsolete memtries only when we start state sync for a new shard: https://github.com/near/nearcore/blob/master/chain/client/src/client.rs#L2507-L2519
However, it does not unload obsolete memtries in all cases.
For example, if we tracked shards [0, 1, 2], and then we track shards [0, 1] only, shard 2 won't be unloaded, because we did not start a new state sync.
Although it is not critical, trie for shard 2 could occupy memory forever.
This PR calls the routine to unload obsolete memtries as a block post-processing step too.
> Unload obsolete memtries post block processing

- pytest/tests/loadtest/locust/common/base.py
- pytest/tests/loadtest/locust/common/ft.py
This addresses two problems:
- The initial balance of master funding account was not enough for 16 workers, so decreasing it 10x (still 10x higher than the previous value)
- Decrease the starting balance of individual user accounts - this is possible now as in FT benchmark, we disable gas price changes during congestion
> [locust] Adjust worker and contract balances

- runtime/near-vm-runner/src/logic/logic.rs
- runtime/near-vm-runner/src/logic/mod.rs
- runtime/near-vm-runner/src/logic/tests/vm_logic_builder.rs
- runtime/near-vm-runner/src/near_vm_runner/runner.rs
- runtime/near-vm-runner/src/wasmer2_runner.rs
- runtime/near-vm-runner/src/wasmer_runner.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
The split boundary has been chosen to be what's necessary to compute a VMOutcome, which now in turn allows us to load a contract without constructing a VMLogic, or contract memory quite yet.
This might very well resolve issues I've been working through by attempting to remove lifetimes and such from `VMLogic`...? As previous changes this makes quite some sense in isolation regardless of the ongoing projects. While I imagine there are more lines, they will mostly be due to the fact that in many places the previous code now needs to go through an additional field projection to get to types it needs to operate.
@Ekleog-NEAR I think you'll appreciate these as I recall you've struggled with the VMLogic nonsense as well in the past.
Part of #11319
> vmlogic: split up into two

- scripts/ft-benchmark-data-sender.py
- scripts/run-ft-benchmark.py
- scripts/start-benchmark.sh
Before this changes `initiator` and `context` db fields was filled by hardcoded constants. Now they switched to command line arguments. Probably it makes sense to do this arguments required and not default them to "unknown", but don't think it is very important
> [ft-benchmark] fill actor and context db fields properly

- runtime/near-test-contracts/build.rs
Another attempt at fixing slow_chunk and congestion_control nayduck tests. Those were failing because the test contract was not being built correctly with the test_features enabled. Here I'm making the build script rerun the build if the relevant feature is changed. 
The first attempt and some relevant discussion is here - #11619. I know this new approach is not the best way to fix this issue but it is much quicker and seems to be getting the job done. 
https://nayduck.nearone.org/#/run/160
> fix(nayduck) - Recompile the test contracts when test_features is enabled. 

- chain/chain/Cargo.toml
- chain/chain/src/block_processing_utils.rs
- chain/chain/src/chain.rs
- integration-tests/Cargo.toml
- integration-tests/src/test_loop/tests/multinode_test_loop_example.rs
As discussed in [#11447](https://github.com/near/nearcore/issues/11447), if there is a panic (due to assertion failure) when running testloop locally, the test freezes instead of reporting the failure. This makes it difficult to run testloop in cases where we want to debug an assertion failure.
The reason for the freezing test failures is that the panic causes the objects be dropped and the drop handler for Chain blocks, waiting apply-chunks be finished: https://github.com/near/nearcore/blob/71d35d9921603d8dea60fcc41c0d5478202fc574/chain/chain/src/chain.rs#L295
However that wait does not end, since setter runs after apply-blocks is finished: https://github.com/near/nearcore/blob/71d35d9921603d8dea60fcc41c0d5478202fc574/chain/chain/src/chain.rs#L1831
And it does not get a chance to notify …
> Change apply-chunk tracker implementation

- tools/debug-ui/src/EpochValidatorsView.scss
- tools/debug-ui/src/EpochValidatorsView.tsx
- tools/debug-ui/src/SnapshotHostsView.tsx
- tools/debug-ui/src/api.tsx
Quick change to improve the debug experience of statelessnet. 
Changes are scoped to the EpochInfo/Validators page.
- Validators can now have multiple roles: chunk validator, chunk producer, block producer. **Note**: I haven't included the role `Block validator` from [NEP-509](https://github.com/near/NEPs/pull/509/files) because I don't fully understand if it's useful nor how to compute this role
- Chunks column renamed -> Produced Chunks
- New column -> Endorsed Chunks
> debug: add new validator roles in debug page and endorsement info

- chain/client/src/client_actor.rs
Subtracting 1 from the smallest chunk height included crashes when it's zero, which can actually happen in many tests, and is currently causing the skip_epoch.py test to fail
> fix(client): fix overflow in get_extra_sync_block_hashes()

- chain/chain/src/test_utils/kv_runtime.rs
- chain/client/src/info.rs
- chain/epoch-manager/src/adapter.rs
The number of validators displayed in the `INFO stats` logging currently does not include chunk validators, which could be misleading post stateless validation launch. This fix works for both before stateless validation and post stateless validation. I verified a fix on a statelessnet node.
> fix: display correct number of validators in stats logging

- tools/debug-ui/src/EpochValidatorsView.scss
- tools/debug-ui/src/EpochValidatorsView.tsx
Following up on the ideas shared by @Longarithm, I removed the `shards` column and merged the `shards` information into the role of `CP` (chunk producer), recovering some space in the page.
Also fix to display the role CP in the next epoch.
> feat(debug): small improvements to validator debug page

- runtime/runtime/src/lib.rs
- runtime/runtime/src/metrics.rs
Add a `shard_id` label to the metrics describing storage proof size. Without this label we have to aggregate over all shards, which often doesn't tell much about what's going on on a specific shard.
When I originally added these metrics I heard that runtime is shard-independent and I thought I can't have a shard id, but it turns out that I can.
> Add shard_id to storage proof size metrics

- CHANGELOG.md
- Cargo.lock
- chain/network/Cargo.toml
- chain/network/src/config.rs
- chain/network/src/config_json.rs
- chain/network/src/lib.rs
- chain/network/src/peer/peer_actor.rs
- chain/network/src/peer/tests/mod.rs
- chain/network/src/peer/tests/rate_limits.rs
- chain/network/src/rate_limits/messages_limits.rs
- chain/network/src/rate_limits/mod.rs
- chain/network/src/rate_limits/token_bucket.rs
- chain/network/src/stats/metrics.rs
- nearcore/src/config_duration_test.rs
Implementation for rate limits of incoming network messages. 
Original issue: #11617. Also supersedes #11618.
**Note:** rate limits are implemented but not defined with this PR; in practice, nothing should change  for a node.
This PR adds:
- A module to arbitrate rate limits using a token bucket algorithm (see `token_bucket.rs`)
- Convenience class to handle all rate limits of a network connection (see `messages_limits.rs`)
- Changes to `peer_actor.rs` to implement the rate limits on received messages
- Changes to the network configuration
- A new metric to count messages dropped due to rate limits
- Unit tests
- ~Make rate limits configurable, likely through config files with overrides~ _done_
- ~Use more accurate token allocation for some network messages, in particular the ones …
> feat: rate limit for network messages

- tools/debug-ui/src/EpochValidatorsView.scss
Fixes a little display error of the table bottom border, in the validators debug page.
> fix: fix CSS border display at the end of the page

- core/parameters/res/runtime_configs/82.yaml
- core/parameters/src/config_store.rs
- core/parameters/src/snapshots/near_parameters__config_store__tests__138.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__82.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_129.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_138.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_82.json.snap
- core/primitives-core/src/version.rs
- integration-tests/src/tests/runtime/sanity_checks.rs
- integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
- integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
- integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_statelessnet_protocol.snap
The gas cost of sending receipts between shards is currently too low - it doesn't reflect the limitations caused by network bandwidth. Let's increase the cost of sending a receipt to another account to 50 Tgas / MiB.
The increase is low enough so that it shouldn't break any contracts, while still being a big improvement over the previous situation.
Refs: https://github.com/near/nearcore-private/issues/107
> Increase gas cost of sending non-sir receipts to 50 TGas / MiB

- pytest/tests/loadtest/locust/common/ft.py
This PR allow to generate multiple large FT contracts that can be reused in the future benchmark runs.
I ran this with 10M users per contract and was able to generate 4 contracts (one per worker), each with 10M users and 1.25GB of state in 24 hours (with gas_limit set to 10 PGas):
```sh
locust -H 127.0.0.1:3030 \
-f locustfiles/ft.py \
--funding-key=$KEY \
--fixed-contract-names --num-ft-contracts=1 \
--num-passive-users=10000000 \
-u 4000 -r 500 --headless --processes 4
```
> Locust: Pre-generate users in FT benchmark

- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
- core/primitives/src/stateless_validation.rs
The `MAX_COMPRESSED_STATE_WITNESS_SIZE` has been set to 32 MiB in https://github.com/near/nearcore/pull/11511. Back then it was a reasonable choice, but since then we increased some of the runtime parameters, which increased the worst case witness size by ~17MiB. (https://github.com/near/nearcore/pull/11582, https://github.com/near/nearcore/pull/11629). I'd feel safer with a larger limit on the compressed witness size.
> Increase MAX_COMPRESSED_STATE_WITNESS_SIZE to 48 MiB

- runtime/near-vm-runner/fuzz/fuzz_targets/diffrunner.rs
- runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
- runtime/near-vm-runner/fuzz/src/lib.rs
- runtime/near-vm-runner/src/lib.rs
- runtime/near-vm-runner/src/logic/context.rs
- runtime/near-vm-runner/src/logic/logic.rs
- runtime/near-vm-runner/src/logic/tests/promises.rs
- runtime/near-vm-runner/src/logic/tests/vm_logic_builder.rs
- runtime/near-vm-runner/src/near_vm_runner/runner.rs
- runtime/near-vm-runner/src/runner.rs
- runtime/near-vm-runner/src/tests.rs
- runtime/near-vm-runner/src/tests/cache.rs
- runtime/near-vm-runner/src/tests/fuzzers.rs
- runtime/near-vm-runner/src/tests/rs_contract.rs
- runtime/near-vm-runner/src/tests/test_builder.rs
- runtime/near-vm-runner/src/tests/ts_contract.rs
- runtime/near-vm-runner/src/wasmer2_runner.rs
- runtime/near-vm-runner/src/wasmer_runner.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
- runtime/runtime-params-estimator/src/function_call.rs
- runtime/runtime-params-estimator/src/gas_metering.rs
- runtime/runtime-params-estimator/src/lib.rs
- runtime/runtime-params-estimator/src/vm_estimator.rs
- runtime/runtime/src/actions.rs
This is a very exciting step forward! Finally we got up to the point where we can do some work in preparing the contract to run separately from actual running of the contract. And all of this is encapsulated in a very neat API that gives out `Send + 'static` types for users to pass around between threads or whatever so that they can pipeline these processes.
It will remain to see whether the requirement to have `&External` and `&VMContext` in both calls is a problem, and how much of a problem it is, but that might be very well solvable with some scoped threads or smart use of channels, or even just `Arc<Mutex>`, especially since both of these structures generally tend to be unique to a contract execution...
Part of https://github.com/near/nearcore/issues/11319
> vm: split preparation and running of a contract

- chain/client/src/info.rs
- integration-tests/Cargo.toml
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/env.rs
- integration-tests/src/test_loop/tests/chunk_validator_kickout.rs
- integration-tests/src/test_loop/tests/congestion_control_adv_chunk_produce.rs
- integration-tests/src/test_loop/tests/in_memory_tries.rs
- integration-tests/src/test_loop/tests/mod.rs
- integration-tests/src/test_loop/tests/multinode_stateless_validators.rs
- integration-tests/src/test_loop/tests/multinode_test_loop_example.rs
- integration-tests/src/test_loop/utils.rs
- runtime/near-vm-runner/src/logic/errors.rs
* Added the capability to have RPC nodes that track all shards. 
* Added storing the tempdir for the whole duration of testloop so that the test can do something meaningful in the db e.g. store a contract in the cache
* Added a draft for the congestion control test - for now only deploying and calling some contracts. I'm intentionally separating the test loop specific stuff and the real logic for congestion control test will be added later.
> feat(testloop) - new testloop features and cc test draft

- Cargo.toml
My local build fails with the following error:
```
> cargo test -p near-chain --no-run 
Compiling near-chain-configs v0.0.0 (/Users/pugachag/Projects/near/nearcore/core/chain-configs)
Compiling near-vm-runner v0.0.0 (/Users/pugachag/Projects/near/nearcore/runtime/near-vm-runner)
error[E0599]: no function or associated item named `now` found for struct `Utc` in the current scope
--> core/chain-configs/src/test_genesis.rs:282:40
|
282 |             let default = chrono::Utc::now();
|                                        ^^^ function or associated item not found in `Utc`
```
`Utc::now()` is only available with `clock` feature.
> fix: add missing chrono feature

- scripts/mac-release.sh
we don't build store validator on neard release anymore and wf upload is failing https://github.com/near/nearcore/actions/runs/9765365593/job/26955860213
> Mac OS release workflow: no store validator

- pytest/tests/loadtest/locust/common/base.py
- pytest/tests/loadtest/locust/common/sweat.py
We switch to sequential account preparation which has much better error messages. For these specific places, the speed is less important than good error messages.
> [locust] Improve errors during account preparation

- chain/chain/src/chain_update.rs
Since #11381 the congestion info from the current block, not the previous block, should be used when applying chunks. The same logic change needs to be applied in state sync / catchup. 
I found this issue while working on a unrelated test loop test for congestion control. I will follow up with the test separately because I would like to get this merged ASAP and the test still requires some work. 
Sadly the existing test - `state_sync_missing_chunks.py` - does not catch this issue despite covering the relevant lines. This is because in this test there is no congestion so it doesn't matter what block is used.
> fix(congestion_control) - fix congestion info from wrong block used in catchup

- runtime/runtime-params-estimator/estimator-warehouse/src/main.rs
- runtime/runtime-params-estimator/src/estimator_context.rs
resolves #11705
Two things needed to be changed.
1. Copy previous congestion info output over to the next chunk as input.
2. Disable congestion info to not mess with existing estimations. In particular, `DataReceiptCreationPerByte` requires large amounts of data to be processed and forwarded every round.
> fix: reenable test_full_estimator

- .cargo/config.toml
We rely on this extension to accelerate computation of SHA2 hashes quickly. This extension not being present will slow down node beyond what's reasonable and the node will not be able to keep up with others. Enabling this extension unconditionally and having the node fail early on machines where the extension is not available seems like a reasonable option here.
> Unconditionally enable SHA-NI extensions

- pytest/tests/loadtest/locust/common/base.py
- pytest/tests/loadtest/locust/common/ft.py
As attaching 300 TGAS leads to a lower network throughput due to recently enabled congestion control. See https://near.zulipchat.com/#narrow/stream/295306-contract-runtime/topic/ft_transfer.20benchmark/near/448814523 for more details.
> [locust] Attach less gas to FT transfers

- Cargo.lock
Using borsh 1.2 for nearcore workspace allows to use the [ordered-float](https://crates.io/crates/ordered-float) crate.
Note that I didn't update the Cargo.toml requirements, hence it won't require dependency updates on published crates from this repo.
The new features changes in borsh in 1.1 and 1.2 don't affect us and are backwards compatible changes according to semver rules.
- 1.1.0 https://github.com/near/borsh-rs/releases/tag/borsh-v1.1.0
- 1.2.0 https://github.com/near/borsh-rs/releases/tag/borsh-v1.2.0
> chore: bump borsh from 1.0 to 1.2 in lockfile

- Cargo.lock
- Cargo.toml
- chain/chain/src/runtime/mod.rs
- chain/jsonrpc/res/rpc_errors_schema.json
- core/primitives/Cargo.toml
- core/primitives/src/congestion_info.rs
- core/primitives/src/errors.rs
- integration-tests/src/tests/client/features/congestion_control.rs
- pytest/tests/loadtest/locust/common/base.py
With the congestion level already included in the response, we clients
don't have to query the congestion info afterwards if they want to use
it to determine a fitting timeout for a retry.
We could also provide more detailed information, like which specific limit
of congestion was hit but I don't think it's appropriate for the RPC API. I would
say this is implementation detail and we want to be able to change it without
worrying about what is exposed on the API.
However, since "missed chunk congestion" is fundamentally different, I think
we should provide a separate error for it. I've added `ShardStuck` error for it,
which includes the number of missed chunks in the error message rather than
the congestion level.
> feat(congestion): More info on shard congested RPC error

- core/primitives/src/epoch_manager.rs
We have `TestnetFewerBlockProducers` feature responsible for limiting number of beefy nodes on testnet.
As in stateless validation we introduce `num_chunk_producer_seats` which defines beefy nodes now, let's retroactively change the feature to limit this number as well.
Note that `num_chunk_only_producer_seats` will be no-op for stateless validation.
> fix: lower testnet seat number

- integration-tests/src/tests/nearcore/stake_nodes.rs
Fix for the failing nayduck test: `test_inflation`.
The issue was that, since stateless validation has been introduced, the validator reward computation has changed to include produced chunk endorsements.
Tested locally by running the test several times in both `nightly` and `stable`
> fix: rewards expectation in test_inflation

- chain/chain/Cargo.toml
- chain/chain/src/runtime/tests.rs
- core/primitives/src/stateless_validation.rs
- core/store/src/trie/mod.rs
- core/store/src/trie/trie_recording.rs
- runtime/runtime/Cargo.toml
- runtime/runtime/src/actions.rs
This PR introduces a way to generate arbitrary large chunk state witness as a result of processing a single receipt. This is needed to test what happens with the blockchain if we missed something in the witness size checks.
Part of #11656.
Large witness generation is triggered by a function call action with a method name `internal_record_storage_garbage_<GARBAGE_SIZE>` with `<GARBAGE_SIZE>` corresponding to a number of megabytes of random data to be added to the storage proof. For example `internal_record_storage_garbage_20` would result in 20MB of garbage data in the witness. Having size as part of the method name (and not as an argument) makes it easier to send a transaction using near cli (`args` needs to be base64 encoded).  Note that we don't need to deploy any contracts, failed …
> feat: generate large state witness

- core/primitives-core/src/version.rs
- runtime/runtime/src/lib.rs
Removes the only storage key in testnet which violates key length restriction.
I verified locally that protocol upgrade works: https://github.com/Longarithm/nearcore/compare/a3828e8738...fecdca4237
I need some time to polish the test, but this PR can be merged anytime.
> fix: remove long storage key on testnet

- pytest/lib/peer.py
Before #11321, the nonce `1` never expired. Now it is no longer usable to establish a connection:
```
network: bad nonce, disconnecting: nonce timestamp too distant in the future/past: got = 1970-01-01 0:00:01.0 +00:00:00, now_timestamp = 2024-07-05 10:23:19.959609591 +00:00:00, max_delta = 20m nonce=1 
```
Instead we should replicate the correct behavior to assign a nonce:
https://github.com/near/nearcore/blob/03a8b5d4a0e6df057a9531f5452c2dbc95ffa89c/chain/network/src/network_protocol/edge.rs#L130-L138
Fixes spec/network/peers_request.py.
> fix: pytest network/peers_request

- runtime/near-test-contracts/build.rs
The slow chunk test in nayduck is still failing due to the test contract being built without the test_features. In my previous attempt it worked once, likely only because I made changes to the build.rs file. My current debug plan is to 
* Add logs to the build script
* ssh to the nayduck builder and see what's going on in there
This PR is the first part. Here is a sample output:
```
~/near/nearcore $ cargo clean && cargo build -p near-test-contracts --features test_features
~/near/nearcore $ cat target/debug/build/near-test-contracts-c89ce330453445c7/output
cargo:rerun-if-env-changed=CARGO_FEATURE_TEST_FEATURES
debug: test_features = Ok("1")
debug: running command: cd "./test-contract-rs" && env -u CARGO_BUILD_RUSTFLAGS -u CARGO_ENCODED_RUSTFLAGS -u RUSTC_WORKSPACE_WRAPPER …
```
> debug(nayduck) - adding debug logs to the near test contracts build.rs

- tools/database/src/commands.rs
> chore: fix typo in command help message

- core/primitives/src/epoch_manager.rs
This value is only introduced with `NoChunkOnlyProducers` feature, so I will guard it behind it.
> fix(chunk-producers): guard the chunk producers change

- Cargo.lock
Run `cargo update` for couple crates, allowing syn to bump to `2.0.70`. Not sure if it is necessary, but cargo did it automatically for #11749.
> chore: update syn deps

- nightly/pytest-sanity.txt
- pytest/tests/sanity/large_witness.py
This PR introduces a nayduck test with large chunk state witness, see test description for more details.
Remote run: https://nayduck.nearone.org/#/run/179
Part of #11656.
> feat: add nayduck test for distributing large state witness 

- core/store/src/trie/mod.rs
- core/store/src/trie/trie_recording.rs
- runtime/runtime/src/metrics.rs
Follow up on https://github.com/near/nearcore/pull/11567
Trie is made up of nodes and values referenced by the leaf nodes. Let's add a metric which shows how much space is taken up by the nodes and the values in the recorded trie. It'll help us estimate how much overhead there is from using Merkle trees.
To get the total size I summed the sizes of subtrees for all trie columns. This is a little bit inaccurate, because it doesn't include the root node, but it should be good enough, the root node is small so it doesn't change the results much.
Here's how the trie metrics look like on the current mainnet traffic:
You can see a preview here:
https://grafana.nearone.org/d/ddrc1ewgllb0gf/witness-size?var-query0=&var-chain_id=mainnet&var-query0-2=&var-role=dev&var-query0-3=&var-node_type=$__all&v …
> Add a metric showing how much space nodes and values take up in the recorded Trie

- pytest/tests/mocknet/helpers/neard_runner.py
- pytest/tests/mocknet/mirror.py
binaries can be replaced. In this PR, we are saving the binary used to make the backup to avoid corrupting the backup when restoring with a higher db version.
> feat(mocknet): save binary used for backup

- chain/chain/src/runtime/mod.rs
- chain/chain/src/types.rs
- core/store/src/trie/mod.rs
- tools/state-viewer/src/apply_chain_range.rs
- tools/state-viewer/src/apply_chunk.rs
- tools/state-viewer/src/cli.rs
- tools/state-viewer/src/commands.rs
This PR fixes commands such as `neard view-state apply` and `neard view-state apply-range` when used on a block height that doesn't have flat storage built for it. 
It works by re enabling the feature of accessing trie nodes without paying gas costs (removed in #10490).
Probably it also fixes #8741.
> fix: block apply in the past 

- pytest/tests/mocknet/helpers/neard_runner.py
`shutil.copyfile` does not preserve permissions
> fix(mocknet) add x permissions on the backup binary

- chain/chain/src/runtime/mod.rs
in `NightshadeRuntime::get_gc_stop_height_impl()`, we check if the db kind is Hot *and* cold_head is set to Some(), and if so we modify the stopping point of garbage collection to not be higher than the cold head epoch's first block. The problem is that the cold storage migration loop can run before the genesis block has been built and stored on disk, in which case updating the cold storage head in cold_store_migration() [here](https://github.com/near/nearcore/blob/42a0c224d6777f65c0d3d0b6010842ae774f93d6/nearcore/src/cold_storage.rs#L294) fails [here](https://github.com/near/nearcore/blob/42a0c224d6777f65c0d3d0b6010842ae774f93d6/core/store/src/cold_storage.rs#L274), because the genesis block height has not yet been written to the BlockHeight column.
This is not a problem for the cold …
> fix(gc): don't garbage collect before cold storage is set up

- Makefile
This pr adds target `help` to display commonly used targets in this project `Makefile`. This is useful for new developers begin to contribute and get a helpful tool for building
> chore: add `help` target to Makefile to display the usage of all targets

- pytest/tests/sanity/gc_sync_after_sync.py
Attempt to fix the failing test `gc_sync_after_sync.py`. Example: https://nayduck.nearone.org/#/test/62087
The reasoning here is to disable database storage checks in both instances when node is restarted; previously it was done only in one of the two restarts.
> fix: fix test gc_sync_after_sync

- pytest/tests/sanity/block_sync_archival.py
At the end of block_sync_archival.py we check that the `near_partial_encoded_chunk_request_processing_time` metric reports that a node that got restarted served partial encoded chunks both by looking them up in `DBCol::PartialChunks`, and also by reconstructing them from chunks for the ones that were garbage collected. But now that archival nodes started from scratch are split storage nodes, `DBCol::PartialChunks` is no longer garbage collected, since that only happens in `ChainStore::clear_archive_data()`, which is only called for legacy archival nodes
> fix(pytests): remove check that applies to legacy archivals in test

- chain/client/src/info.rs
The catchups log line is currently using new line separators which is against the structured logging recommendations and it is messing up my `grep`s and `sed`s. I'm putting it all in a single log line. I would also be happy to make it into a line per shard or something similar, please just let me know.
> logs(state-sync) - put the catchups log in a single line

- pytest/tests/mocknet/mirror.py
- pytest/tests/mocknet/remote_node.py
This is necessary for mocknet instances of FT benchmark that don't follow the previous naming pattern of "{chain_id}-{height}-{unique_id}".
> [mocknet] Add ability to specify mocknet-id

- pytest/requirements.txt
As it is needed for the mocknet neard-runner: https://github.com/near/nearcore/blob/00fbeec47e686c90814264af6b9e603bdd6cf523/pytest/tests/mocknet/helpers/neard_runner.py#L9
> [pytest] Add json-rpc dependency

- chain/chain/src/types.rs
Adding instrumentation on outcome proof computation, which may take a non-negligible amount of time if there are thousands of outcomes.
> tracing: instrument outcome proof computation

- chain/client/src/client_actor.rs
When stateless validation kicks in, we no longer want validators to track all shards - 
the `tracked_shards` field in `config.json` should be set to an empty-list.
It is not critical that they stop tracking all shards immediately after the upgrade to protocol v69,
but at least we add this check so that validators are enforced to set `tracked_shards=[]` during the next restart (e.g. while downgrading the machine to lower RAM).
Tested on a testnet node:
* For non-validator it started normally regardless of `tracked_shards` value.
* For validator node:
* It started normally when `tracked_shards=[]`.
* If panicked when `tracked_shards=[0]`.
> [stateless_validation] Prohibit all-shards-tracking post-stateless-validation

- chain/client/src/view_client_actor.rs
- pytest/tests/sanity/single_shard_tracking.py
The `ViewClientRequestManager` is meant to remember what tx status requests we've sent to other nodes so we can serve future view client requests after receiving it. But before this change, each view client has its own cache. This means that tx status responses are only available to the same view client thread, which might not have been the one that made the request. So if we share it across threads, we fix this issue
Also in this change we wait a bit in single_shard_tracking.py before sending transactions because otherwise the first block after the localnet is started often has no new chunks and the transaction is rejected by congestion control because the computed current height - height included (which is the genesis height) is too high
> fix(view client): remember tx status requests across view client threads

- chain/client/src/view_client_actor.rs
In the ViewClientActor we log this whole message, but it can really be very giant with all the outomes and merkle paths and transaction data (especially for deploy contract transactions, where the entire contract code will be logged). So just log a few parts of the message instead. This kind of change is probably necessry in a few other places here where we log entire messages in these handlers.
> fix(logs): Don't log whole TxStatusResponse message

- README.md
- runtime/runtime-params-estimator/README.md
This simple PR replaces the breaking URLs from the Lychee CI test with working URLs.
> chore(lychee): replaced near examples URL and gnuplot url with working urls

- pytest/tests/loadtest/locust/common/ft.py
If the users are already created, we can skip the expensive part of checking each one of them, and instead just populate the array with known accounts.
> [locust] Register FT users faster

- pytest/tests/mocknet/remote_node.py
As on CRT benchmark, we don't mirror the traffic and don't have this directory.
> [mocknet] Don't require traffic_target_home

- core/parameters/res/runtime_configs/143.yaml
- core/parameters/res/runtime_configs/70.yaml
- core/parameters/res/runtime_configs/parameters.snap
- core/parameters/src/config_store.rs
- core/parameters/src/snapshots/near_parameters__config_store__tests__129.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__141.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__70.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_129.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_141.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_70.json.snap
- core/parameters/src/snapshots/near_parameters__view__tests__runtime_config_view.snap
- core/primitives/src/snapshots/near_primitives__views__tests__runtime_config_view.snap
This stabilizes the recently implemented #11721. As the protocol version for 2.0 has already been bumped to 69, this is now 70 for the release that comes after 2.0.
> proto ver 70 & stabilize discard_custom_sections

- pytest/tests/mocknet/helpers/neard_runner.py
My goal is to figure out how to set the log level in forknet. Please consider this PR only as an RFC for what would be the best approach to solve this problem. I think in the perfect world the initial setup would happen only once e.g. in `new_test` or in `reset`. It may also be nice to add a command to adjust the log config but this can always be done with `run-cmd` so it's low pri. 
I also refactored things a bit, sorry for mixing it with the real change. The real change is moving `configure_log_config` from `start_neard` to `new_test`, the rest should be a noop.
> feat(forknet) - configure log config only in new_test

- chain/jsonrpc/src/lib.rs
This PR updates the RPC handler to return appropriate HTTP errors for specific RPC issues, improving error visibility for operators
closes #11792
> feat: improved RPC's response error handling with HTTP status codes

- chain/client/src/client_actor.rs
See https://github.com/near/nearcore/issues/11821 for context.
Check if this is a current validator using current epoch info, not merely the fact that validator key exists.
Pre-requirements for the check to kick-in:
* `tracked_shards=[]` in `config.json`
* `validator_key.json` exists
Tested with different validator IDs:
* `node` - dummy validator ID, it **did not** crash
* `gritsly.poolv1.near` - existing validator with the lowest stake, not marked as `CP` in the debug page, it **did not** crash
* `solidstate.poolv1.near` - existing validator with the lowest stake that was marked as `CP` in the debug page, it **crashed**
Pre-requirements for the check to kick-in:
* `tracked_shards=[0]` in `config.json`
* `validator_key.json` exists
Tested with different validator IDs:
* `node` - dummy …
> fix: Use current validator for tracked shards check

- runtime/near-vm-runner/fuzz/fuzz_targets/diffrunner.rs
- runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
- runtime/near-vm-runner/fuzz/src/lib.rs
- runtime/near-vm-runner/src/lib.rs
- runtime/near-vm-runner/src/logic/context.rs
- runtime/near-vm-runner/src/logic/dependencies.rs
- runtime/near-vm-runner/src/logic/gas_counter.rs
- runtime/near-vm-runner/src/logic/logic.rs
- runtime/near-vm-runner/src/logic/mocks/mock_external.rs
- runtime/near-vm-runner/src/logic/mod.rs
- runtime/near-vm-runner/src/logic/tests/vm_logic_builder.rs
- runtime/near-vm-runner/src/near_vm_runner/runner.rs
- runtime/near-vm-runner/src/runner.rs
- runtime/near-vm-runner/src/tests.rs
- runtime/near-vm-runner/src/tests/cache.rs
- runtime/near-vm-runner/src/tests/fuzzers.rs
- runtime/near-vm-runner/src/tests/rs_contract.rs
- runtime/near-vm-runner/src/tests/test_builder.rs
- runtime/near-vm-runner/src/tests/ts_contract.rs
- runtime/near-vm-runner/src/wasmer2_runner.rs
- runtime/near-vm-runner/src/wasmer_runner.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
- runtime/runtime-params-estimator/src/function_call.rs
- runtime/runtime-params-estimator/src/gas_metering.rs
- runtime/runtime-params-estimator/src/lib.rs
- runtime/runtime-params-estimator/src/vm_estimator.rs
- runtime/runtime/src/actions.rs
- runtime/runtime/src/ext.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/state_viewer/mod.rs
Best reviewed commit-by-commit.
This ultimately lifts the contract preparation up through a several function call layers in the transaction runtime up to the layer where all the currently necessary data are available.
This PR also establishes in broad strokes where the pipelining decisions will be made (`ApplyProcessingReceiptState`) and makes some minor changes to the type to have it contain local receipts (in addition to the previously contained delayed receipts etc) in a queue of sorts which would allow the pipelining code to look-ahead of the ongoing processing work and queue-up preparation of the upcoming contracts there.
This work so far is intended to have no functional changes.
Part of #11319
> runtime: start lifting contract preparation up through tx runtime layers 

- pytest/lib/cluster.py
- pytest/tests/sanity/split_storage.py
- tools/cold-store/src/cli.rs
This is not a final fix to `split_storage.py`, because there is still some nondeterminism that makes the test fail. But the changes below are needed since without them the test consistently fails.
This PR fixes the following:
1) Change `init_cluster` to add a flag to prevent it from initializing cold-storage for archival node, since the test initializes the cold-storage after initializing the cluster. The test checks the state of the archival node before and after it has cold-storage.
2) Update the `DBKind` checks for the hot db, since the hot DB seems to be using `DBKind::Hot` only, not `DBKind::Archive` anymore.
3) Replace `time.sleep` calls with waiting for a number of blocks to be more deterministic on the chain progress.
> fix: Fix issues with nayduck test split_storage.py

- scripts/run-ft-benchmark.py
Of course we want remove lock after a successful run, not only after fails during benchmark execution
> [ft-benchmark] remove lock file after successful run

- pytest/tests/mocknet/helpers/neard_runner.py
- pytest/tests/mocknet/mirror.py
- pytest/tests/mocknet/node_handle.py
- tools/fork-network/src/cli.rs
Forknet V2 restricts the chain_id by only allowing us to append a suffix. 
This PR introduces a new parameter that will let us change the chain id to anything.
> feat(forknet): Add chain_id parameter to fork-network tool

- chain/client-primitives/src/types.rs
- chain/client/src/lib.rs
- chain/client/src/view_client_actor.rs
- pytest/tools/mirror/online_test.py
- tools/mirror/src/lib.rs
- tools/mirror/src/offline.rs
- tools/mirror/src/online.rs
Before this change, the only way to get a chunk from the view client actor is to send a `GetChunk` message which returns a `ChunkView`. This is what we do when running `neard mirror run` with the `--online-source` flag, which is used to start a source chain node that applies mainnet blocks so that we don't run out of transactions. This is normally completely fine, but there is a problem with Deploy Contract actions, where the deploy contract action in the `ChunkView` type actually only contains the hash of the contract code instead of the whole thing, which means that we can't mirror any deploy contract transactions.
To fix it, we can add a new `GetShardChunk` view client type that is the same as the existing `GetChunk` except that it returns the full shard chunk. It's a much smaller …
> feat(mirror): add a GetShardChunk view client type and call it in mirror subcommand

- core/parameters/src/config_store.rs
As this is limiting the throughput of FT benchmark.
> [bench] Disable tx pool state size limit

- chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
- chain/jsonrpc/src/lib.rs
- pytest/lib/cluster.py
This PR fixes a small issue that was introduced in #11806
Internal error - 500 status code
Handler error - 408 if it's a `TIMEOUT_ERROR`, otherwise 200
Request validation error - 400 status code
closes #11792
> feat: handle `RpcError` properly

- pytest/tests/mocknet/node_handle.py
This is useful to identify faulty node when `mirror start-traffic` hangs in `waiting for validators to be up` mode for a long time.
> feat: add mirror tool logging when node is not ready yet

- chain/chain/src/stateless_validation/state_transition_data.rs
We noticed that the first block of the epoch where stateless validation gets enabled takes a lot of time (~30 seconds). @robin-near  [pinpointed](https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/Slow.20first.20block.20in.20protocol.20v69/near/454062961) `garbage_collect_state_transition_data` to be the cause. In particular it is caused by `compute_start_heights`. The expectation was that it will read only a few entries from `StateTransitionData` column on the first run to initialise `StateTransitionStartHeights`. The issue is that currently it is only triggered when stateless validation is already enabled with `checked_feature!("stable", StatelessValidation, protocol_version)` check. But we start saving state transition data one epoch before that, see …
> fix: always garbage collect state transition data

- pytest/tests/sanity/transactions.py
The test is affected by the congestion control. The test starts sending transactions immediately after starting the nodes. There are some chunk misses at the beginning (while the nodes are starting), which makes the congestion control reject the transaction due to chunk misses.
To fix it, we wait for height 5 instead of 1 to start sending the transaction.
Related [zulip thread](https://near.zulipchat.com/#narrow/stream/295302-general/topic/nayduck/near/452544235).
> fix: Fix nayduck test transactions.py

- integration-tests/src/test_loop/tests/max_receipt_size.rs
- integration-tests/src/test_loop/tests/mod.rs
- integration-tests/src/test_loop/utils/mod.rs
- integration-tests/src/test_loop/utils/setups.rs
- integration-tests/src/test_loop/utils/transactions.rs
- integration-tests/src/tests/client/features/congestion_control.rs
- integration-tests/src/tests/runtime/test_evil_contracts.rs
- runtime/near-test-contracts/test-contract-rs/src/lib.rs
Test the `max_receipt_size` limit added in 8f8a73b6e5184e2e8773c9b6ac641d85e0fd5f8c using TestLoop.
Receipts larger than `4_194_304` bytes should be rejected.
We can't easily generate a 4MB receipt because the transaction size limit is 1.5MB. To deal with this I generate the receipt from within a contract. The contract creates a single receipt with multiple `FunctionCall` actions, each of which has a lot of data in the `args`. All those actions sum up to more than 4MB and the receipt size limit is hit.
The transaction fails properly and the runtime doesn't die when it encounters an invalid receipt.
I had to add the functionality to execute a transaction and wait for the result. I implemented something similar to the old `TestEnv::execute_tx` function.
I also added a "default setup" …
> test: test max receipt size using TestLoop

- integration-tests/src/tests/client/features/delegate_action.rs
As comment above suggests, we need to use exec gas in calculation instead of send. This didn't cause the test to fail because all of the costs are zero, but I've tested that increasing them fails before and passes with this change.
This fixes some of the failures in https://github.com/near/nearcore/pull/11864
> [tests] Fix gas cost calculation in delegation tests

- chain/chain/src/runtime/tests.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/epoch-manager/src/tests/mod.rs
- integration-tests/src/test_loop/tests/chunk_validator_kickout.rs
- integration-tests/src/test_loop/tests/multinode_stateless_validators.rs
- integration-tests/src/tests/client/benchmarks.rs
- integration-tests/src/tests/client/features/stateless_validation.rs
- integration-tests/src/tests/client/features/storage_proof_size_limit.rs
- nearcore/tests/economics.rs
Now that stateless validation is in prod, we no longer need to check the protocol version for stateless validation specific tests.
> [cleanup] Remove check for stateless validation protocol version in tests

- pytest/requirements.txt
- pytest/tests/mocknet/mirror.py
The mirror.py script uses the `datetime` library, but it wasn't included in the `requirements.txt` file.
Let's add it to `requirements.txt`.
Apart from that, the script used an older version of the dependency, let's update it to work with the new version where `datetime.UTC` has been deprecated.
> fix(mirror.py): Fix datetime dependency

- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/tests/simple_chain.rs
- chain/client/src/stateless_validation/chunk_endorsement_tracker.rs
- chain/client/src/stateless_validation/chunk_validator/mod.rs
- chain/client/src/test_utils/client.rs
- chain/client/src/test_utils/test_env.rs
- chain/epoch-manager/src/adapter.rs
- chain/epoch-manager/src/tests/mod.rs
- chain/network/src/network_protocol/mod.rs
- chain/network/src/peer/peer_actor.rs
- chain/network/src/peer_manager/peer_manager_actor.rs
- chain/network/src/rate_limits/messages_limits.rs
- core/primitives-core/src/version.rs
- core/primitives/src/stateless_validation/chunk_endorsement.rs
- core/primitives/src/validator_signer.rs
- integration-tests/src/tests/client/challenges.rs
- integration-tests/src/tests/client/features/orphan_chunk_state_witness.rs
- integration-tests/src/tests/client/process_blocks.rs
This PR is a pre-step for the work around merging validation of chunk endorsement and partial witness.
This PR has the following changes
- New protocol feature ChunkEndorsementV2 which would introduce a new network message and versioning of ChunkEndorsement.
- ChunkEndorsement is changed from struct to a versioned enum. The original/old chunk endorsement message would work with ChunkEndorsementV1 till deprecated.
- The outgoing network stack would use the original RoutedMessageBody::ChunkEndorsement for V1 while we would use RoutedMessageBody::VersionedChunkEndorsement for futue versions.
No functional change in this PR.
> [stateless_validation] Versioned chunk endorsement

- integration-tests/src/node/runtime_node.rs
- integration-tests/src/tests/client/features/nonrefundable_transfer.rs
- integration-tests/src/tests/runtime/test_evil_contracts.rs
- integration-tests/src/tests/standard_cases/mod.rs
There was a discrepancy between the costs used by the started nodes and the ones used by the fee_helper which was exposed when gas costs changed.
There were a number of places where we select which RuntimeConfig to use:
1. Multiple NEAR nodes started in separate threads with random chain_id `test-chain-*`
2. `RuntimeNode` class
3. `fee_helper()` function
4. `TestEnv` builder
All these places must use the same config for the gas calculations to match.
I've decided to align all of these cases with the configs used in 1, which matches the current mainnet config.
I think that's generally a good choice if available as we want the test environment to catch the problems that we will see on mainnet.
There could be some tests that still rely on the values from `free` or `test` configs, but I argue …
> [tests] Use consistent runtime config across tests

- docs/practices/style.md
`rust-analyzer.imports.granularity.group` is used instead of `rust-analyzer.assist.importGranularity` these days.
> doc: fix Import Granularity rust analyser settings

- pytest/tests/sanity/db_migration.py
Related discussion: https://near.zulipchat.com/#narrow/stream/295302-general/topic/Database.20migration.20CI.20check.20is.20consistently.20failing/near/457036240
We fix it by increasing the GC window for the old binary (which does not have the mechanism to compute and save the congestion info in disk, this we lose the genesis block if GC is enabled).
See the comment in the test file for more context.
> fix: Fix db_migration.py test

- core/store/src/contract.rs
- core/store/src/lib.rs
- core/store/src/trie/update.rs
- integration-tests/src/tests/runtime/sanity_checks.rs
- integration-tests/src/tests/runtime/state_viewer.rs
- runtime/runtime/src/actions.rs
- runtime/runtime/src/ext.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/pipelining.rs
- runtime/runtime/src/state_viewer/mod.rs
This PR implements a very basic form of pipelining of the contract preparation. In particular with this PR only actions from one upcoming "interesting" local receipt is handled, with other receipt kinds (incoming, delayed) being left for a future change. I don't anticipate any trouble integrating them as they largely have similar data and structure as the local receipts seen here.
The primary reason I want this reviewed separately, however, is due to the changes to storage. You will notice that I have largely changed the code to read contracts without going through The State (i.e. it now reads the contract code directly via the code hash.) However at the same time writing of the contract continues involving The State; largely because I don't want to deal with migrations and similar such …
> runtime: implement a receipt preparation pipeline

- chain/telemetry/src/lib.rs
We observed that nodes on `2.1.0-rc.2` were printing a panic after receiving a signal to stop. [zulip conversation](https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/2.2E1.2E0-rc2.20panic.20on.20shutdown).
We looked into the problem and found out that it's caused by the destructor of `awc::Client`.
The logic went like this:
* Node operator enables uploading telemetry in `config.json`
* `neard` is started and `TelemetryActor` is spawned to upload telemetry data to the specified endpoints
* `TelemetryActor` creates an instance of `awc::Client` to perform HTTP POST requests with telemetry data.
* `awc::Client` maintains a connection pool with open connections that can be reused for making requests to the same host
* After making a request, the connection is kept alive …
> fix(telemetry): Fix panic when stopping node with telemetry

- tools/state-viewer/src/apply_chain_range.rs
Small change to print DB stats before a panic during the `apply-block` command.
This makes possible to know if the command has written any data into the DB before the panic.
> debug: print DB stats before panic while applying block

- runtime/runtime/src/congestion_control.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/metrics.rs
- runtime/runtime/src/pipelining.rs
Part of #11319 and the final change in integration with the transaction runtime as all interesting receipt types are handled now. There are also receipt types like yield timeouts which only result in generation of new (delayed) receipts, so they don't need to be handled by this mechanism.
> runtime: pipelined preparation for incoming and delayed receipts

- pytest/lib/cluster.py
We used to with BUILDKITE but that relied on BUILDKITE-specific environment variable.
> ci: output node logs to stdout on pytest nodes

- core/primitives/src/views.rs
**_SignedTransactionView_**
Default value used when deserializing SignedTransactionView which are missing the `priority_fee` field.
Data which is missing this field was serialized before the introduction of `priority_fee`.
`priority_fee` for `Transaction::V0 => None`, `SignedTransactionView => 0`
**_ReceiptView_**
Default value used when deserializing ReceiptView which are missing the `priority` field.
Data which is missing this field was serialized before the introduction of `priority`.
For `ReceiptV0` `ReceiptPriority::NoPriority => 0`
> add `serde(default)` when deserializing views which are missing new fields.

- pytest/tests/sanity/validator_switch.py
Non validator node was not tracking any shard and needs to state sync when it becomes a validator. This test does not test state sync so we made the non validator node track all shards to be ready to become a validator.
> fix(nayduck): validator_switch

- runtime/runtime/src/congestion_control.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/metrics.rs
- runtime/runtime/src/pipelining.rs
This reverts commit 781805d5075c7e8fffb1cbe3512df90c2d461a97
The commit above is causing issues in processing chunks both in testnet and mainnet. The issue can be reproduced on an healthy node by applying the commit and then running:
```
/home/ubuntu/neard view-state -t hot apply-range --start-index 125812312 --end-index 125812312 --shard-id 2 --storage trie-free sequential
```
Note: block 125812312 will sooner or later be GC'd so the repro steps will need an archival node and cold storage.
Fix tested locally on a mainnet canary.
> fix: Revert changes to pipelined runtime implementation

- chain/epoch-manager/src/lib.rs
- chain/epoch-manager/src/tests/mod.rs
In this function, we compute and collect ratios of expected blocks and chunks for all validators in the epoch, and we exempt the top validators from being kicked based on the `validator_max_kickout_stake_perc` epoch config field. We build this list from a hashmap, which has nondeterministic iteration order, and then sort by this ratio. But if there are many with the same ratio, then the ones we pick are not deterministic because we don't also sort by account ID. Fix it by also sorting by account ID
> fix(epoch-manager): fix nondeterminism in EpochManager::compute_exempted_kickout()

- pytest/tests/sanity/concurrent_function_calls.py
The test fails because the HTTP requests for `call_function` get stuck when invoked from `multiprocessing` object, even if number of processes is set to one. 
The node was working as expected.
I solved the issue by using the native python `Session` object to do the requests.
> fix: Fix concurrent fn calls test

- pytest/tests/sanity/rpc_tx_forwarding.py
The problem in rpc_tx_forwarding is that it attempts to run `send_tx_and_wait` function (which both sends the tx and fetches its result) on a node tracking no shards. Forwarding transaction in `send_tx_and_wait` works, but fetching the result does not work for a node tracking no shard. Splitting it into two parts, sending tx with the same node but fetching the tx result from another node makes the test pass.
We also replace sleep functions with waiting for few blocks.
> fix: Fix test rpc_tx_forwarding nayduck test

- .cargo/config.toml
- core/store/src/trie/mem/arena/mod.rs
- core/store/src/trie/mem/flexible_data/children.rs
- core/store/src/trie/mem/node/encoding.rs
- core/store/src/trie/mem/node/mod.rs
This set of changes applies a set of small changes which all ultimately end up in a some appreciable wins to the performance of memtrie_lookup function.
Although the two profiles I'm about to reference come from distinct workloads (they are 60 seconds of recording of a node tracking mainnet 2 days across, on different machines) the contextual information suggests that these two profiles are roughly comparable still (in particular the duration of `node_hash` and `decode` between the two profiles is pretty similar.) Here's the [old run](https://share.firefox.dev/3YO6es2) where you can see that `view_impl` is taking a relatively obscene amount of time in relation to what it is doing. In particular samples were showing that reading the one header byte was accounting for ~70% of the total …
> memtrie: improve the performance of memtrie_lookup

- chain/chain-primitives/Cargo.toml
- core/primitives/Cargo.toml
- nearcore/src/lib.rs
- runtime/near-vm-runner/fuzz/Cargo.toml
- tools/storage-usage-delta-calculator/Cargo.toml
Fix the crates publishing process.
tested with:
```
cargo ws exec -- cargo check --all-features                 
cargo ws exec -- cargo check --no-default-features
cargo ws exec -- cargo check      # This is the one that we needs to be pass. Others are nice to have for now.
```
> chore fix cargo dependencies

- .cargo/config.toml
That said, development currently happens on machines with this
instruction enabled and our fee structure will assume use of this
instruction in the long run, meaning that this instruction will become
required to keep up with the network in due time anyway.
This also fixes other feature names. I had looked at the LLVM names,
rather than Rust ones in the list 🤦
> Do not mandate use of SHA-NI instruction

- .github/workflows/neard_assertion_binary_n1.yml
- .github/workflows/neard_release_n1.yml
- scripts/binary_release_n1.sh
- scripts/mac-release-n1.sh
These workflows will build binaries and push them into n1 build bucket:
n1.build.nearprotocol.com
> Preparing N1 S3 build bucket and OIDC

- .github/workflows/mac_m1_binary.yml
after switching to OIDC forgot to add token write permissions and deploy environment
> GHA: mac os binary release fix

- core/store/src/trie/shard_tries.rs
Part of #11912.
See [zulip thread](https://near.zulipchat.com/#narrow/stream/313099-storage/topic/Disabling.20prefetcher.20when.20memtrie.20is.20enabled/near/462370532) for more context around removing prefetcher.
Shard cache is removed since it doesn't provide any additional caching on top of memtrie since `TRIE_LIMIT_CACHED_VALUE_SIZE` value is lower than `INLINE_DISK_VALUE_THRESHOLD`. This was confirmed by `near_shard_cache_hits` metric.
> feat: disable prefetch and shard cache when memtrie is enabled

- chain/chain/src/test_utils/kv_runtime.rs
- chain/client/src/chunk_inclusion_tracker.rs
- chain/client/src/client.rs
- chain/client/src/stateless_validation/chunk_endorsement/mod.rs
- chain/client/src/stateless_validation/chunk_endorsement/tracker_v1.rs
- chain/client/src/stateless_validation/chunk_endorsement/tracker_v2.rs
- chain/client/src/stateless_validation/mod.rs
- chain/client/src/stateless_validation/partial_witness/mod.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
- chain/client/src/stateless_validation/validate.rs
- chain/client/src/test_utils/test_env.rs
- chain/epoch-manager/src/adapter.rs
- core/primitives/src/stateless_validation/chunk_endorsement.rs
- core/primitives/src/stateless_validation/partial_witness.rs
This PR has the following
- Add a new ChunkEndorsementTracker that tracks ChunkEndorsementV2
- Add logic to separate between the two trackers
- Merge validation logic for ChunkEndorsementV2 and partial witness
Follow up on https://github.com/near/nearcore/pull/11856 and https://github.com/near/nearcore/pull/11860
> [stateless_validation] Introduce ChunkEndorsementTracker V2

- integration-tests/src/test_loop/tests/mod.rs
- tools/debug-ui/src/log_visualizer/events.ts
logviz used to display all network messages as `NetworkRequest`, this isn't very useful, it'd be better to show what type of message it is. Let's parse the network event and set the subtitle to message type. There's still a `Network` prefix to indicate that this is a network message.
> feat(debug-ui): Show type of network message in logviz

- chain/client/src/client.rs
- chain/client/src/client_actor.rs
- chain/client/src/config_updater.rs
- core/chain-configs/src/lib.rs
- core/chain-configs/src/updateable_config.rs
- core/dyn-configs/src/lib.rs
- nearcore/src/dyn_config.rs
- nightly/pytest-sanity.txt
- pytest/lib/cluster.py
- pytest/tests/sanity/validator_remove_key_quick.py
Issue: https://github.com/near/nearcore/issues/11995
Adds support to dynamically remove validator key.
> Dynamically remove validator key

- scripts/recover_missing_archival_data.sh
This script contains the minimal set of commands to restore missing data from archival nodes.
The data loss appeared in three time periods:
- early January
- after first resharding
- after second resharding
Due to the nature of how trie nodes are stored in the database, one missing node in the past may cause errors when querying accounts at very distant future heights.
Recovery takes many days and required an SSD backed cold storage. 
I've tested the procedure's outcome with manual queries and by iterating tries from different state roots.
> feat: add script to recover missing data in archival nodes

- nightly/pytest-sanity.txt
After https://github.com/Near-One/nayduck/pull/58, 3 consecutive runs against master shows that slow_chunk and congestion_control pass now. So it is safe to uncomment congestion_control.py.
> chore: uncomment congestion_control.py

- core/primitives-core/src/version.rs
Move ChunkEndorsementV2 to stable protocol version.
With the next release, we should be able to get rid of tracker_v1 code.
> [stateless_validation] Stabilize ChunkEndorsementV2

- integration-tests/src/tests/client/features/wallet_contract.rs
- runtime/near-wallet-contract/src/lib.rs
- runtime/runtime/src/actions.rs
- runtime/runtime/src/ext.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/state_viewer/mod.rs
Hash is stored in the `Account` and the rest of the codebase largely expects the hash to uniquely identify the specific contract code. For the time being just return exactly what's stored in the `Account` and think about updating the accounts later...
> `wallet_contract` now returns contract based on the hash

- runtime/near-vm-runner/src/near_vm_runner/runner.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
This makes sure that changes to the configuration correctly take effect for provided contract. Otherwise the repeat executions of a contract that's already in the cache might "stick" to the old behaviour across e.g. a VM configuration change.
> vm: use contract_cache_key for memory cache

- chain/chain/src/runtime/metrics.rs
- chain/chain/src/runtime/mod.rs
This can be helpful when we need to distinguish between applications from chunk producer and chunk validator. One example is to compare memtrie vs recorded storage perf.
> feat: add apply_reason label for apply chunk metric

- Cargo.toml
- chain/network/src/network_protocol/mod.rs
- chain/network/src/store/schema/mod.rs
- core/store/src/trie/shard_tries.rs
- runtime/near-vm/tests/compilers/traps.rs
- runtime/near-wallet-contract/implementation/rust-toolchain.toml
- runtime/runtime-params-estimator/emu-cost/Dockerfile
- rust-toolchain.toml
- tools/state-viewer/src/state_dump.rs
- tracing/Cargo.toml
- utils/near-performance-metrics/src/stats_enabled.rs
Release notes: https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html
Addresses the following Clippy warnings:
warning: lint `box_pointers` has been removed: it does not detect
other kinds of allocations, and existed only for historical reasons
warning: struct `PeerComponent` is never constructed
warning: struct `ComponentEdges` is never constructed
warning: struct `LastComponentNonce` is never constructed
warning: this function depends on never type fallback being `()`
--> core/store/src/trie/shard_tries.rs:468:5
warning: this function depends on never type fallback being `()`
--> tools/state-viewer/src/state_dump.rs:132:1
> rust: 1.81.0

- chain/chain/src/metrics.rs
- chain/chain/src/resharding/resharding_v2.rs
- chain/chain/src/store/mod.rs
- tools/database/src/resharding_v2.rs
Clean up resharding V2 code, more specifically:
- Resharding metrics
- Reassigning of outgoing receipt in `chain/src/store/mod.rs`
TODO next:
- `StateSnapshotType::ForReshardingOnly`
- `ShardSyncStatus::{ReshardingScheduling, ReshardingApplying}` 
- `State_sync::resharding_state_roots`
- Resharding handle
- Pytests
> feat: clean up resharding v2 part 3

- pytest/tests/sanity/shadow_tracking.py
Reproduced the flakiness very easily locally.
With these changes, I could not.
Gave some more time to catch up and added `stop_checking_store`.
> Fix shadow tracking test flakiness

- chain/network/Cargo.toml
In #11597 some new feature flags were introduced in the near-primitives package.
near-network depends on some of the gated features. Currently running `cargo test -p near-network` results in compile errors. This PR restores the ability to build and run the tests of the near-network package independently.
> fix(network): include correct features from near-primitives

- chain/jsonrpc-primitives/src/types/entity_debug.rs
- core/store/src/trie/raw_node.rs
- nearcore/src/entity_debug.rs
- tools/debug-ui/scripts/compare_tries.py
- tools/debug-ui/src/entity_debug/BottomBarView.scss
- tools/debug-ui/src/entity_debug/BottomBarView.tsx
- tools/debug-ui/src/entity_debug/EntityDataValueView.tsx
- tools/debug-ui/src/entity_debug/EntityDebugView.tsx
- tools/debug-ui/src/entity_debug/fields.tsx
- tools/debug-ui/src/entity_debug/keys.tsx
- tools/debug-ui/src/entity_debug/types.tsx
- tools/debug-ui/src/entity_debug/view_options.tsx
Example:
It's similar to the existing trie queries, but this one is by hash, not by path. It allows more low-level trie access that can be used by a script.
Also:
* Add a script for diffing tries given disagreeing state roots.
* Add an option to display ascii in hex vs not.
[Screencast from 09-12-2024 10:36:48 AM.webm](https://github.com/user-attachments/assets/0c9a1937-1f19-489d-9825-2b11f98ed7dd)
> [Debug UI] Allow querying raw trie nodes by hash in entity debug UI

- runtime/near-vm-runner/src/wasmtime_runner.rs
Resolves: #12062 
This PR resolves the issue with the wasmtime function type incompatibility.
To understand the issue, I highly recommend my investigation comments on the issue itself: https://github.com/near/nearcore/issues/12062
To be honest, I'm not sure it's a proper fix as I guess the root cause of the issue is somewhere outside of the file that leads to running under different engines/settings, leading to instantiating failures. It's a bit weird that the WasmtimeVM instance and Module instance could be different somehow as wasmtime::Engine is an arc wrapper. And module seems to clone it inside which should be still the same instance.
I could reproduce the issue only by tweaking the code manually by recreating an engine before the linking. It means that something more complex happens …
> bugfix: wasmtime: instantiating function type incompatibility

- chain/jsonrpc-primitives/src/types/blocks.rs
- chain/jsonrpc-primitives/src/types/changes.rs
- chain/jsonrpc-primitives/src/types/chunks.rs
- chain/jsonrpc-primitives/src/types/client_config.rs
- chain/jsonrpc-primitives/src/types/config.rs
- chain/jsonrpc-primitives/src/types/gas_price.rs
- chain/jsonrpc-primitives/src/types/light_client.rs
- chain/jsonrpc-primitives/src/types/maintenance.rs
- chain/jsonrpc-primitives/src/types/network_info.rs
- chain/jsonrpc-primitives/src/types/query.rs
- chain/jsonrpc-primitives/src/types/receipts.rs
- chain/jsonrpc-primitives/src/types/sandbox.rs
- chain/jsonrpc-primitives/src/types/split_storage.rs
- chain/jsonrpc-primitives/src/types/status.rs
- chain/jsonrpc-primitives/src/types/transactions.rs
- chain/jsonrpc-primitives/src/types/validator.rs
This pull request introduces the `Clone` trait for the RpcErrors structs. Implementing this trait is essential for ensuring that the RPC service can properly handle error instances, particularly for scenarios involving reading and matching errors.
- The RpcError structs now derive the `Clone` trait, allowing for instances of RpcErrors to be duplicated easily.
- The primary reason for this change is to facilitate the error handling process in the read RPC service. By enabling cloning, we ensure that error values can be reused or matched without ownership issues.
- This enhancement will improve the flexibility of error handling in the read RPC service, especially in scenarios where errors need to be logged, sent, or processed in multiple contexts.
> Add Clone derive for RPC errors structs

- core/store/src/config.rs
In preparation for decentralizing state sync and deprecating cloud storage, we want to have all nodes produce snapshots so that they can share state parts with each other.
> feat(state-sync): enable EveryEpoch snapshot generation by default

- core/primitives/src/sharding.rs
- core/schema-checker/schema-checker-macro/src/lib.rs
- tools/protocol-schema-check/res/protocol_schema.toml
Remove lifetimes from types generated by ProtocolSchema tooling.
Needed for #12031.
> feat: lifetimes in ProtocolSchema types

- chain/chain/src/garbage_collection.rs
- chain/client/src/sync/epoch.rs
- core/async/src/test_loop.rs
- core/store/src/columns.rs
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/epoch_sync.rs
* Store EpochSyncProof locally after as part of bootstrapping the node.
* Use the stored EpochSyncProof to derive a new EpochSyncProof in order to handle EpochSyncRequests.
* Add a new testloop test to check that one can bootstrap a new node via epoch sync from a node that was bootstrapped with epoch sync itself
* Add new testloop tests to check that the EpochSyncProof derived based on an older EpochSyncProof is exactly equal to an EpochSync derived from genesis.
> [Epoch Sync] Support bootstrapping a node from another epoch-synced node.

- core/store/src/contract.rs
- core/store/src/lib.rs
- core/store/src/trie/mem/loading.rs
- core/store/src/trie/mod.rs
- core/store/src/trie/receipts_column_helper.rs
- core/store/src/trie/resharding_v2.rs
- core/store/src/trie/update.rs
- integration-tests/src/tests/client/features/fix_storage_usage.rs
- integration-tests/src/tests/client/features/nearvm.rs
- integration-tests/src/tests/runtime/state_viewer.rs
- runtime/near-vm-runner/src/near_vm_runner/runner.rs
- runtime/near-vm-runner/src/wasmer2_runner.rs
- runtime/near-vm-runner/src/wasmer_runner.rs
- runtime/runtime/src/actions.rs
- runtime/runtime/src/balance_checker.rs
- runtime/runtime/src/congestion_control.rs
- runtime/runtime/src/ext.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/metrics.rs
- runtime/runtime/src/pipelining.rs
- runtime/runtime/src/state_viewer/mod.rs
This reverts commit 4e93e4680bfcc8e8e445d30bd3106188e18eb234.
This reverts commit 86cd45b1a6f58a190fb7ac518eb7ee309f7874a4.
To address the issues seen that led to the functionality being reverted in the first place I had to add some mechanisms to query The State in a side-effect-free (pure) manner and to also revert some changes from the original change-set where we the new code would *not* produce the side-effects that were expected by the other nodes.
> Pipelining

- chain/chain/src/stateless_validation/chunk_endorsement.rs
- chain/client/src/chunk_inclusion_tracker.rs
- chain/client/src/debug.rs
- chain/client/src/stateless_validation/chunk_endorsement/mod.rs
- chain/client/src/stateless_validation/chunk_endorsement/tracker_v1.rs
- chain/client/src/stateless_validation/chunk_endorsement/tracker_v2.rs
- core/primitives/src/stateless_validation/validator_assignment.rs
I noticed in endorsement tracker, we were first checking if we have enough endorsement stake and then using that information to generate the signature vector. 
It's simpler and more efficient to generate this while calculating enough stake.
ChunkEndorsementsState doesn't have to be an enum, we can include the signatures in EndorsementStats (and rename it to ChunkEndorsementsState).
> [stateless_validation] Refactor ChunkEndorsementsState

- core/store/src/trie/mem/arena/concurrent.rs
- core/store/src/trie/mem/arena/frozen.rs
- core/store/src/trie/mem/arena/hybrid.rs
- core/store/src/trie/mem/arena/mod.rs
- core/store/src/trie/mem/arena/single_thread.rs
- core/store/src/trie/mem/mem_tries.rs
- core/store/src/trie/mem/node/encoding.rs
- core/store/src/trie/mem/updating.rs
On converting existing arena memory to shared memory, we lose the ability to refcount the shared memory part.
However, while adding new nodes and new entries in the owned memory part, we could potentially be referring to the shared memory.
In such cases, while adding or removing nodes, we would like to ignore all increments and decrements to refcounts in the shared part of memory.
Added a unit test for expected scenario.
> [memtrie] Fix refcount for HybridArena

- nightly/pytest-sanity.txt
- pytest/lib/cluster.py
- pytest/tests/sanity/state_sync_decentralized.py
Pytest to check decentralised state sync of nodes tracking one shard.
Keep shard shuffling off until the implementation is done.
This test sets a dumper node only for the state sync headers.
Sets 4 validator nodes, each tracking 1 shard.
Sets an RPC node to handle the random traffic that changes the state.
Only allow validator nodes to share parts by enabling the state snapshot. 
Check if the network can got for 6 epochs while shard shuffling is on. 
Validator nodes are expected to download parts from each other.
Check http://127.0.0.1:3040/debug/pages/epoch_info for the validator assignment rotation.
> test(state-sync): shard swap in single shard tracking

- tools/fork-network/src/cli.rs
There is a corner case where the last batch of changes is smaller than the batch threshold and it may not get flushed before the seconds pass. This will recreate the keys for the accounts that were deleted in the uncommitted batch.
To test this, we created a network with a validator and an RPC node. Created an account (`A` with key `Ka`) by sending some `$N` to it.  Add another key to that account (`Kb`). Now `A` has `Ka` and `Kb` as full access keys. 
Delete `Ka`. Now `A` has just `Kb` as full access key.
On this state, we run `fork-network`.
 In the first pass, we change account `A` to `rA` and delete `A`. 
Change key `Kb` to `rKb` and delete `Kb`.
 Without this fix, the default batch size is too large to flush the changes from the first pass of `prepare_shard_state`. 
Moving to the …
> fix(fork-network): flush the first pass changes before starting the second pass

- debug_scripts/estimate_epoch_start_time.py
Usage:
```
python3 estimate_epoch_start_time.py --chain_id mainnet --num_future_epochs 10 --num_past_epochs 20
```
<details><summary>Example output</summary>
```
Epoch -1: 14 hours, 59 minutes                                                                                                                                                                                        
Epoch -2: 14 hours, 58 minutes                                                                                                                                                                                        
Epoch -3: 13 hours, 22 minutes …
```
> feat(release): Add epoch start estimator script

- core/store/src/flat/manager.rs
- core/store/src/trie/state_snapshot.rs
The StateSnapshot class provides a function called `get_shard_uids`, which is intended to return the UIDs of the shards included in the snapshot.
However, this function was incorrectly returning the entire set of flat storage keys from the flat storage manager. As a result, if a flat storage exists but the snapshot process fails to update the flat storage head, the snapshot would incorrectly report that the shard was successfully included.
> fix(state-snapshot): correctly return included shard uids

- integration-tests/src/tests/client/process_blocks.rs
Uncovered a weird issue by setting "no_cache" feature.
Another reason why the store layer cache should be removed.
Please take a look at issue https://github.com/near/nearcore/issues/12160
> [fix] Fix inconsistent block hash

- chain/jsonrpc/src/api/mod.rs
- chain/jsonrpc/src/lib.rs
This PR makes the `RpcRequest` trait public to allow for broader usage in external crates. Additionally, it re-imports `near_jsonrpc_primitives` as `primitives` to simplify references and improve code readability. This change is aimed at improving modularity and maintainability in the codebase.
> (jsonrpc): Make trait `RpcRequest` a public and reimport `near_jsonrpc_primitives` as `primitives`

- .github/workflows/nayduck_ci_dev.yml
- core/primitives/src/shard_layout.rs
- core/store/src/adapter/flat_store.rs
- nightly/ci_dev.txt
Run more tests in Nayduck. 
Need this workflow to identify and fix flaky tests before making them blocking.
Added handler for workflow cancel, test in https://github.com/near/nearcore/actions/runs/11107751344/job/30859091936
> Nayduck dev tests workflow

- docs/architecture/how/receipt-congestion.md
since `NEP-539` was merged, it's time to use master link of `NEP-539` in the docs to render better reading experience. :)
> chore(docs): use master link of `NEP-539`

- tools/mirror/src/chain_tracker.rs
- tools/mirror/src/lib.rs
In queue_block(), we lock the TxTracker struct and add some data to it related to the current block's worth of transactions we're queuing. This includes references to transactions that will be queued to the tx_block_queue passed to that function. But we actually add these to the tx_block_queue only after we release the lock on the TxTracker, so another thread that's waiting for that lock might start looking through it and trying to find the transactions whose references were added to the TxTracker in queue_block(), but before these blocks get added to the tx_block_queue. This leads to a possible crash in get_tx() if we try to look up one of these transactions:
```
thread 'actix-rt|system:0|arbiter:0' panicked at tools/mirror/src/chain_tracker.rs:366:14:
called `Result::unwrap()` on an …
```
> fix(mirror): fix a crash in the mirror traffic generator

- core/parameters/res/runtime_configs/67.yaml
- core/parameters/res/runtime_configs/69.yaml
- core/parameters/res/runtime_configs/73.yaml
- core/parameters/res/runtime_configs/parameters.snap
- core/parameters/src/config_store.rs
- core/parameters/src/cost.rs
- core/parameters/src/snapshots/near_parameters__config_store__tests__73.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_129.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_73.json.snap
This was intended to match the cost of the per-byte of function call payloads, but an unfortunate two-letter typo led to it becoming the same as the base cost instead.
This change requires a protocol version bump (to 73) but otherwise is fairly straightforward in that I just set the cost of the fee to the incorrect value back in 67 and corrected it in code and protocol version 73.
> yield_resume: fix resume per-byte cost

- chain/chain/src/chain.rs
- core/primitives/src/epoch_manager.rs
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
Do minimal changes to the code allowing to check that number of shards in the new epoch increased.
This code can be reused to test each separate component for resharding v3:
* non-contiguous shard ids
* state sync
* memtries resharding
* ...
To make the test pass, nodes must track all shards for now, because state sync is not implemented yet. So every node must think that it has enough state to skip state sync.
Note that it doesn't mean at all that resharding works already. State is also not properly constructed yet, so tx processing will either be incorrect or crash the node.
> test: enable simple resharding v3 test

- chain/chain/src/chain.rs
- chain/client/src/view_client_actor.rs
- core/primitives/src/state_sync.rs
- integration-tests/src/tests/client/sync_state_nodes.rs
In testnet we observed `get_cached_state_parts` consistently taking ~58 seconds to run. 
Returning the list of cached state parts is a relic of the old decentralized state sync design. We no longer need this at all.
> fix(state sync): delete get_cached_state_parts

- chain/client/src/client_actor.rs
- chain/client/src/sync/state.rs
Before this PR, when a state part arrived via a network message from a peer, it was validated and stored by the client actor. As a result, the client actor could become slow to apply blocks causing the node to fall behind the chain.
Instead, the state parts should be handled async on `state_parts_future_spawner` the same way they are when downloaded from external storage.
> fix(state sync): handle StateResponse on state_parts_future_spawner

- chain/chain/src/chain.rs
According to this line in the storage checker, the chunk tail should always be less or equal than the tail:
https://github.com/near/nearcore/blob/99ecfa4e8b97eda5e369d82ef00cfc06e5291552/chain/chain/src/store_validator/validate.rs#L146
This invariant is broken, I'm guessing since #12025 as shown by nayduck gc test failing at this check:
https://nayduck.nearone.org/#/test/108874 - test1 stderr last line
This is a simple mitigation but I'm not 100% sure if correct - please let me know if it makes sense or not. 
Even if not entirely correct it should not cause any problems. At worst gc will attempt to clean a little bit more data that isn't there. I hope. 
The only real change here is the added `saturating_sub(1)` to the line where we set the tail.
> fix(gc) - fix the chunk_tail <= tail invariant

- chain/chain/src/runtime/mod.rs
- chain/chain/src/runtime/tests.rs
- chain/chunks/src/client.rs
- chain/client/src/stateless_validation/chunk_validator/orphan_witness_pool.rs
- chain/client/src/tests/bug_repros.rs
- chain/client/src/tests/cross_shard_tx.rs
- chain/network/src/peer_manager/tests/snapshot_hosts.rs
- core/primitives-core/Cargo.toml
- core/primitives-core/src/types.rs
- core/primitives/benches/serialization.rs
- core/primitives/src/congestion_info.rs
- core/primitives/src/shard_layout.rs
- core/primitives/src/test_utils.rs
- core/primitives/src/trie_key.rs
- core/store/src/trie/state_parts.rs
- core/store/src/trie/trie_storage.rs
- runtime/runtime/src/congestion_control.rs
- runtime/runtime/src/tests/apply.rs
- runtime/runtime/tests/runtime_group_tools/mod.rs
More of the same. I added a rust feature to quickly switch between the old and new shard ids to speed up work. 
No interesting changes here, just syntax everywhere. I hope.
> feat(resharding) - Make shard ids non-contiguous - part 2

- chain/client/src/test_utils/setup.rs
- chain/network/src/peer_manager/testonly.rs
- chain/network/src/test_utils.rs
- core/async/src/actix.rs
- core/async/src/actix_wrapper.rs
- core/async/src/functional.rs
- core/async/src/messaging.rs
- core/async/src/test_loop/sender.rs
- integration-tests/src/test_loop/tests/view_requests_to_archival_node.rs
- integration-tests/src/test_loop/utils/transactions.rs
Previously, `MessageWithCallback<T, R>` contains `T` as well as a callback that is a function that accepts an `Result<R, AsyncSendError>`. And then, `AsyncSender<T, R>` is simply `Sender<MessageWithCallback<T, R>>`.
The problem was that in the actix implementation of `Sender<MessageWithCallback<T, R>>`, because on the actix side when we call `.send(msg)` it gives us a future of `R`, we cannot call the callback right away. The solution was to `actix::spawn` a future that awaits this future of `R` and then we call the callback.
This was a bad design, because it is actually the *sender* (code that calls `.send_async(...)`) who ends up calling `actix::spawn`, and that panics if the sender was not on an actix thread.
This PR changes that so that `MessageWithCallback<T, R>` contains a callback …
> [TestLoop] Make MessageWithCallback accept future as a result.

- pytest/tests/sanity/rpc_state_changes.py
https://nayduck.nearone.org/#/test/117339 was flaky on some run.
The failure happens because of ShardStuck error for the single shard we have.
Looks like it is specific to the height 3, where there is a high probability that no chunks can be produced which triggers ShardStuck.
But if we wait for height 5, everything is fine.
Another finding: sometimes `load_test_contract` seems to serve as an unintended delay to ensure warmup. In some of the cases we do `time.sleep` or `wait_for_blocks` as well.
> test: warmup before tx execution

- chain/chain/src/chain.rs
- integration-tests/src/tests/client/state_dump.rs
- o
The current gc logic cleans state part column along with the blocks. By default 5 epochs. State parts older than an epoch are not needed. This introduces a change to drop the state sync files at the end of the epoch.
> feat(state-sync): drop old state parts at the end of epoch

- chain/client/src/metrics.rs
- chain/client/src/sync/epoch.rs
- integration-tests/src/test_loop/tests/epoch_sync.rs
It's a very simple cache. We only cache the most recent epoch sync proof, in compressed format. The key of the cache is the EpochId. So whenever the EpochId changes, we recompute it.
Why don't we just store this on disk instead? It's unnecessary, and introduces more state to keep. Deriving the proof is not very expensive anyway (maybe a couple of seconds).
> [EpochSync] Cache epoch sync proof in memory for multiple requests.

- tracing/Dockerfile
It seems the rust buster image tags don't exist anymore, so this bumps it up one to bullseye. Also bumps the rust version to 1.81 to match up with what's in Cargo.toml, because otherwise that part will fail, too.
> fix(tracing-server): fix Dockerfile

- chain/client/src/info.rs
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/network.rs
Enhance the test by dropping certain ranges of chunks, based on **height relative to protocol upgrade height**. For example, if upgrade height is 100 and range is `-3..2`, then chunks at heights `97, 98, 99, 100, 101` should be dropped.
This allowed to catch a bug in `InfoHelper`: because inside `cares_about_shard_from_prev_block` is called, previous block should be passed instead of current one. Otherwise shard layout is incorrect.
For now I add a test to skip two chunks just after upgrade. I wanted to add more, but **surprisingly the test starts to fail for various reasons**. I added TODOs and resolve them later.
The main piece of logic is `should_drop_chunk_for_protocol_upgrade`. It is a bit complex because if protocol upgrade didn't happen yet, its height is hard to retrieve. …
> test(resharding): skipped chunks on protocol upgrade

- chain/chain/src/flat_storage_resharder.rs
Adding log entries telling the time spent on the longer operations happening during flat storage resharding.
Part of flat storage resharding issue (#12174).
> feat(resharding): log time spent in resharder operations

- tools/ping/src/metrics.rs
The ping tool currently crashes when initializing these metrics because the names starting with "near_" is now enforced with a panic
> fix(ping): prepend "near_" to metric names

- Cargo.lock
- chain/chain/Cargo.toml
- chain/chain/src/block_processing_utils.rs
- chain/chain/src/chain.rs
- core/async/src/test_loop.rs
- integration-tests/Cargo.toml
- integration-tests/src/tests/client/state_dump.rs
Previously, https://github.com/near/nearcore/pull/11653 introduced a mechanism where a maximum timeout was used in `impl Drop for Chain`, but that only works if the testloop feature is enabled, which most likely is not the case when someone just runs a test.
This PR switches to an alternative implementation; not only is it simpler, but it also automatically works. If the TestLoop panics, it will be dropped first. When it is dropped, it ensures that all pending events are dropped, thereby dropping the ApplyChunksStillApplying struct, making the subsequent waiter.wait() call go through when we're recursively dropping the Chain.
Confirmed that this fixes #11840 as well.
> [TestLoop] Properly fix the TestLoop hang-on-panic issue.

- chain/chain/src/store_validator.rs
- chain/chain/src/store_validator/validate.rs
- chain/client/src/sync/epoch.rs
- nightly/pytest-sanity.txt
- pytest/lib/cluster.py
- pytest/tests/sanity/epoch_sync.py
Most of the complexity here is changes to the StoreValidator:
* Do not check that previous block exists, if it's older than the epoch sync boundary.
* Do not check that if BlockInfo exists the header also exists, because this is also not true for some blocks before the epoch sync boundary.
* (This one was pre-existing before epoch sync) Be lenient when checking chunk body's existence, because we don't seem to download these for the extra blocks needed by state sync. I couldn't figure out a good way to check this rigorously, so I included a heuristic to skip checking if the block in question is <= tail height. I don't think it's correct, but it works for now.
* The reason why this does not trigger state sync nayduck test failures is because the utils.poll_blocks function doesn't trigger …
> [Epoch Sync] Add a Nayduck test for Epoch Sync.

- chain/client/src/sync/state.rs
Reverts state sync to the old behavior: if an external parts source is available, it will be used without making any p2p requests. 
Alternative would be to set the default `peer_attempts_threshold` to 0, but I'd rather hard disable this since we do not intend to officially release it pending further testing and tuning.
Not sure why CI is showing a bunch of unrelated failures; maybe some issue with basing this PR on a non-master branch.
> state sync: prefer external if available

- .github/workflows/ci.yml
- .github/workflows/lychee_lints.yml
Separate workflow for Lychee lints.
Removing the check from CI workflow.
> Periodic lychee lints

- chain/chain-primitives/src/error.rs
- chain/chain/src/chain.rs
- chain/chain/src/lib.rs
- chain/chain/src/store/merkle_proof.rs
- chain/chain/src/store/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/client/src/sync/epoch.rs
- chain/client/src/view_client_actor.rs
- chain/epoch-manager/src/adapter.rs
- core/primitives/src/epoch_sync.rs
- integration-tests/src/test_loop/tests/epoch_sync.rs
- integration-tests/src/tests/client/process_blocks.rs
Issue: https://github.com/near/nearcore/issues/11932
Implements EpochSyncProof validation, according to:
- [design doc](https://docs.google.com/document/d/14Itc9Hs7ewTRmcGANid9UCaYcJzaLzzM7FsvYYIFKDY/edit#heading=h.p2oiicluwd6o)
- [`epoch_sync.rs`](https://github.com/near/nearcore/blob/d6d6e4782f7d57a7b7acc2894e1668355012ff74/core/primitives/src/epoch_sync.rs)
Summary:
- Move block merkle proof retrieval logic from `Chain` to a separate trait (`MerkleProofAccess`). Make `Store` implements this trait so that we can `get_block_proof` while serving `EpochSyncRequest` from a separate thread and having no access to `Chain`.
- Refactor `verify_approval` and `compute_bp_hash` so that we can use it for proof validation.
- Derive `first_block_info_in_epoch` from block header.
- Implement the …
> [Epoch Sync] EpochSyncProof validation

- chain/chain/src/flat_storage_resharder.rs
- chain/chain/src/resharding/manager.rs
- core/primitives/src/state.rs
This PR improves the way batches are handled in the background task that splits a shard. In particular, I'm re-using the good old `batch_size` and `batch_delay` to throttle processing.
Part of #12174
> feat(resharding): use resharding config in flat storage resharder

- core/store/src/adapter/trie_store.rs
- core/store/src/cold_storage.rs
- core/store/src/lib.rs
- nearcore/src/entity_debug.rs
The [previous PR](https://github.com/near/nearcore/pull/12084) introduced mapping for read operations.
This PR extends that functionality to write operations and adds some testing for State mapping.
Following the [Zulip discussion](https://near.zulipchat.com/#narrow/stream/407288-core.2Fresharding/topic/State.20mapping/near/476959235), we decided to implement a panic inside the `TrieStoreUpdateAdapter` methods. Other strategies considered were:
1. Propagating the error instead of panicking: This was rejected because the error would need to be propagated through multiple layers that currently don't expect errors. Additionally, an error here would indicate a misconfiguration in the database, justifying the use of panic.
2. Performing the mapping later in `TrieStoreUpdateAdapter::commit()`: …
> feat(resharding) - Resharding mapping state update

- core/primitives/src/stateless_validation/chunk_endorsement.rs
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/mod.rs
- integration-tests/src/test_loop/tests/protocol_upgrade.rs
- integration-tests/src/test_loop/utils/network.rs
I tried to use the feature added in https://github.com/near/nearcore/pull/12235 to simulate a protocol upgrade with missing chunks (to test bandwidth scheduler upgrade), but I couldn't get it to work.
I spent some time debugging, and I think that we should drop chunk endorsements instead of partial chunks.
From what I saw, dropping partial chunks without dropping chunk endorsements causes the nodes to end up in a state where they have a block with some non-missing  chunks, but they don't have the parts for these chunks. 
The node can't process a block, prints out `Error::ChunksMissing`, and gets stuck.
I replaced the function that drops partial chunks with a function that drops endorsements and now it works as expected.
I added a basic test which does a protocol upgrade between two …
> fix(test_loop) - drop chunk endorsements instead of partial chunks to simulate missing chunks

- chain/client/src/sync/state/network.rs
If the expected sender is not specified, we should accept a response from any peer. We don't specify an expected sender for state parts, so this bug meant that state sync was ignoring all parts received from peers. 
#12247 adds tests which cover this code and detect this problem.
> fix(state sync): handle expected_peer_id correctly

- chain/chain/src/types.rs
- chain/chunks/src/client.rs
- chain/client/src/test_utils/setup.rs
- chain/epoch-manager/src/shard_tracker.rs
- chain/network/src/network_protocol/testonly.rs
- chain/network/src/peer_manager/tests/snapshot_hosts.rs
- core/primitives-core/src/types.rs
- core/primitives/src/congestion_info.rs
- core/primitives/src/shard_layout.rs
- genesis-tools/genesis-populate/src/lib.rs
- nearcore/src/config.rs
Removing the remaining usages of new_shard_id_tmp and replacing it with ShardId::new. Removed the new_shard_id_tmp too.
> cleanup(resharding) - remove new_shard_id_tmp

- chain/network/src/peer_manager/connection/mod.rs
Witness contracts distribution messages are as latency sensitive as `PartialEncodedStateWitness` and `PartialEncodedStateWitnessForward`, so we want to use T1 for those as well.
> feat: use T1 for when distribution chunk witness contracts messages

- chain/chain/src/stateless_validation/metrics.rs
- chain/client/src/metrics.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
Added metrics should help identify if accessed contracts causing delays in witness processing for chunk validators.
> feat: add metrics around witness contracts distribution

- core/store/src/metrics.rs
- core/store/src/trie/trie_storage.rs
This should help us to identify missing contracts codes as a result of failed/delayed distribution of the accessed contracts.
> feat: add metric for missing TrieMemoryPartialStorage values

- chain/chain/src/runtime/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/types.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/test_utils/setup.rs
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/tests/network/runner.rs
- nearcore/src/lib.rs
- runtime/near-vm-runner/src/cache.rs
This PR adds compiled contracts cache check for contract hashes for witness accessed contracts. We only request contract code for the missing contracts.
Tested in forknet: number of `ContractCodeRequest` and `ContractCodeResponse` became significantly lower than `ChunkContractAccesses`.
Before:
After:
> feat: request only missing witness contracts

- nightly/pytest-sanity.txt
The test workload looks heavy enough to exceed default 3m timeout sometimes, as we can see in the test history. https://nayduck.nearone.org/#/run/454
> chore: pytest single_shard_tracking timeout

- chain/chain/src/resharding/event_type.rs
- chain/chain/src/runtime/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chunks/src/client.rs
- chain/client/src/stateless_validation/chunk_validator/orphan_witness_pool.rs
- chain/client/src/tests/bug_repros.rs
- chain/client/src/tests/cross_shard_tx.rs
- chain/network/src/peer_manager/tests/snapshot_hosts.rs
- core/primitives-core/src/types.rs
- core/primitives/src/congestion_info.rs
- core/primitives/src/shard_layout.rs
- core/primitives/src/trie_key.rs
- core/store/src/trie/state_parts.rs
- core/store/src/trie/trie_storage.rs
- genesis-tools/genesis-populate/src/lib.rs
- integration-tests/src/test_loop/tests/protocol_upgrade.rs
- integration-tests/src/tests/client/flat_storage.rs
- integration-tests/src/tests/client/process_blocks.rs
- runtime/runtime/src/bandwidth_scheduler/mod.rs
- runtime/runtime/src/congestion_control.rs
- runtime/runtime/src/tests/apply.rs
- tools/flat-storage/src/commands.rs
Removed a bunch of temporary methods that were used as a glue between the old and new ShardId. 
The parts worth reviewing are:
* core/primitives-core/src/types.rs
* ShardUId::new - it's safe now to make it into a method as ShardId is strongly typed and shard id and version won't get mixed up. I am also very tempted to refactor the `from_shard_id_and_layout` function to a method in the shard layout but I'll leave that for later.
> cleanup(resharding) - remove temporary methods after the ShardId transition

- chain/chain/src/chain.rs
- chain/client/src/sync/epoch.rs
- core/primitives/src/epoch_sync.rs
- core/primitives/src/types.rs
- integration-tests/src/test_loop/tests/epoch_sync.rs
Fix several issues:
* The endorsements for last final block of each epoch actually contain signatures from both that and the next epoch's block producers. While we only need the verify the signatures of this epoch's block producers, the list of approvals included in the next block needs to be trimmed down to exactly these block producers. So when producing the epoch sync proof, we trim down these approvals.
* The endorsements for the last final blocks were verified, but the total stake was not verified to be more than 2/3. This PR fixes that by calling `Doomslug::can_approved_block_be_produced`.
* The block producers list was incorrectly derived from the `EpochInfo`. The `EpochInfo::block_producers_settlement()` returns a list with repeated validator indexes. This PR introduces a …
> [Epoch Sync] Fix some epoch sync proof verification problems.

- chain/chain/src/chain.rs
- chain/chain/src/garbage_collection.rs
* GC prints error because the head is at genesis. Return early in that case. Otherwise while we're doing epoch sync because head remains at genesis, this keeps spamming the logs.
* See #11930 for a header sync problem; a recently received block is marked as invalid because its height is too far ahead of where our head is (genesis). We fix this by not marking blocks as invalid if it's just because of height. The reason why we mark a block as invalid is because we think that the block can never be valid (e.g. due to some state disagreement) so we should not bother trying it again, but if invalid height is the issue, this is counterproductive.
Closes #11930 
Closes #11936
> [Epoch Sync] Fix GC error spam and invalid height problem

- pytest/tests/sanity/congestion_control.py
Added a fail fast check at the beginning to the test and a nice comment explaining the most common reason - the test contract built without the test_features enabled. 
This addresses the first part of #12305
> feat: improve congestion control nayduck test

- chain/chain/src/store/merkle_proof.rs
- core/primitives/src/merkle.rs
This serves as the foundation for solving https://github.com/near/nearcore/issues/12255
For Epoch Sync, we need to be able to generate block merkle proofs despite not having older blocks.
Luckily, after much [banging my head against the wall](https://github.com/user-attachments/assets/74954ab8-a80e-409a-85d1-0a48655274d3) on the merkle tree proof algorithm mostly without much luck, I eventually found a way to modify the algorithm (without changing the result it generates) to guarantee that proving block X against block Y will never access anything older than X or newer than Y (the latter is not important and also already true, but we may as well say it neatly like this).
Added a test to assert that this guarantee is met for all pairs 0 <= X < Y < 100.
The rigorous proof of this guarantee …
> [Epoch Sync] Strengthen the storage access guarantees of block merkle proof.

- chain/client/src/client_actor.rs
This function gets called repeatedly every `sync_step_period` (default 10 ms). Printing "request_sync_blocks: done" every time produces unhelpful log spam.
> fix(state sync): downgrade request_sync_blocks log level

- chain/client/src/metrics.rs
- chain/client/src/sync/state/network.rs
Analogous to STATE_SYNC_EXTERNAL_PARTS_REQUEST_DELAY metric for centralized state sync.
> feat(state sync): record latency of p2p state requests

- pytest/tests/sanity/epoch_switches.py
- pytest/tests/sanity/validator_switch.py
Checked locally that it makes impacted tests not flaky. Example reason is that for near genesis heights, not all chunks are created, so some txs, like staking, may not go through due to congestion control.
> test(nayduck): more warmup for flaky tests

- pytest/tests/sanity/congestion_control.py
The test became flaky since relaxing the congestion control parameters made it harder to congest the chain. 
It turns out that the test was really inefficient in sending transactions because it was querying for the current head block for every transaction. The fix is to store the block hash at the beginning of the test and reuse it for all transactions. 
Sped up the test by breaking early when the expected conditions are met (some transactions are rejected, the chain finishes processing all of the load.)
Added some cosmetic changes to make it easier to tweak the load. The load can be adjusted by changing the number of accounts or the sleep time in the load method.
> fix(nayduck) - fix congestion control test flakiness

- chain/chain-primitives/src/error.rs
- chain/chain/src/stateless_validation/chunk_validation.rs
- chain/chunks/src/shards_manager_actor.rs
- core/primitives/src/sharding.rs
- core/primitives/src/sharding/shard_chunk_header_inner.rs
Add one more check in `pre_validate_chunk_state_witness` - make sure that the chunk header is valid in this protocol version. We already have a `valid_for` function, but it looks like it's only used in shards manager actor.
AFAIU not having this check is not a problem at the moment - only the newest chunk header will match the chunk extra with congestion control info, so other versions of chunk headers won't be endorsed.
But there's the concern that there could be a new version of chunk header which can match older chunk extra. For example for bandwidth scheduler I added a new version of `ShardChunkHeaderInner` and accepted cases where `ChunkExtra` had `None` while the list of requests in `ShardChunkHeaderInner` was empty. It was needed to handle protocol upgrades. Chunk validators would …
> Check that header version is valid for the current protocol version in witness validation

- chain/client/src/stateless_validation/partial_witness/encoding.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
- core/primitives/src/reed_solomon.rs
- core/primitives/src/stateless_validation/state_witness.rs
This PR makes code related to witness parts tracking generic so it can be reused for deployed contracts distribution.
We need to merge it ASAP, tests will be added in a separate PR.
> refactor: make witness reed solomon parts reusable 

- .github/workflows/master_fuzzer_binaries.yml
- .github/workflows/ondemand_fuzzer_binaries.yml
- Cargo.lock
- Cargo.toml
- core/crypto/Cargo.toml
- core/primitives/src/version.rs
2.3.0
Set the voting date for mainnet protocol 72 to November 5th.
Cherry pick two changes to fixing fuzzing infrastructure issues:
https://github.com/near/nearcore/pull/12184
https://github.com/near/nearcore/pull/12274
> 2.3.0 release updates

- chain/client/src/sync/epoch.rs
- core/chain-configs/src/client_config.rs
- integration-tests/src/test_loop/tests/epoch_sync.rs
The previous config defaulted to false, which is not good, because we want all nodes to default it to true. This change renames the fields to "disable_..." because (1) we need a field name change to apply new defaults because some nodes may already have reinitialized the config; (2) defaulting a field to false is more natural and less error-prone, so using "disable" rather than "enable" will more naturally default to enabling.
Also document the config fields.
Closes #12347
> [Epoch Sync] Enable epoch sync by default in configs.

- chain/client/src/metrics.rs
- chain/client/src/stateless_validation/partial_witness/partial_deploys_tracker.rs
Similar to the metric we have for partial witness. It allows us to track both the distribution latency as well as number of successful decodings (via `_count`)
> feat: add contract deploys time-to-last-part metric

- chain/client/src/client.rs
- chain/client/src/stateless_validation/chunk_validator/mod.rs
- integration-tests/src/tests/client/features/adversarial_behaviors.rs
With async witness code distribution occasional chunk validation failures are expected due to network delays or message loss.
> feat: remove stateless validation panic in test environment

- chain/client/src/sync/epoch.rs
- core/primitives/src/epoch_sync.rs
- core/primitives/src/merkle.rs
* Verify the first block of the current epoch against the last final block of the current epoch, using the merkle proof.
* Verify the last and second last headers before the first header.
* Verify the partial merkle tree (note: this is NOT the merkle *proof*!) of the first block; add `is_well_formed()` to facilitate that validation.
* Clearly document what every field of EpochSyncProof is validated against.
> [Epoch Sync] Verify merkle proofs for the first block in current epoch.

- docs/practices/workflows/profiling.md
It should be `kptr_restrict` as [documented here](https://www.kernel.org/doc/html/latest/admin-guide/sysctl/kernel.html#kptr-restrict). The command with `restrict_kptr` fails on a GCP node running Ubuntu.
> fix: typo in profiling instructions

- core/store/src/trie/mem/updating.rs
Issue: #12361
After #12359, we can take memory usages from `updated_nodes` instead of recomputing them again.
The original plan was to remove reading child nodes completely, where it is not necessary. However, we still need to read hash, and hash is still a part of child' `MemTrieNodeId`... Moreover, it doesn't make sense to store hashes of children in the node for memory savings.
I think we just need to live with it then. At least the usecase is very clear now. If we ever want to make memtrie recording cleaner (make it a side effect of `MemTrieNodePtr::view`?), we need to skip recording node only if its hash is needed.
> fix: remove recomputing memtrie node memory usages

- runtime/near-test-contracts/README.md
- runtime/near-test-contracts/build.rs
- runtime/near-test-contracts/src/lib.rs
Placing build artifacts into source directories has a nasty property of readily doing the wrong thing in situations where there's parallel compilation of different feature combinations, for example.
In my case, I would locally never be able to run integration tests as R-A would quickly rebuild the test contracts crate with its own feature set during a run of the tests.
There has historically been problems with this in the context of nayduck too.
This PR does the right thing wherein it places the build-time artifacts exactly where they belong: $OUT_DIR.
> chore: keep build artifacts for test contracts out of source

- Cargo.lock
- chain/indexer/src/lib.rs
- core/primitives/Cargo.toml
- core/primitives/src/epoch_manager.rs
- nearcore/src/config.rs
- neard/src/cli.rs
- runtime/runtime-params-estimator/src/main.rs
Added a new parameter to `init`. 
Dump all the epoch configs between the given version and the latest known protocol version.
> feat(epoch config): dump epoch configs in neard init for tests

- nearcore/src/lib.rs
This one was overlooked from the previous PR. 
Pass the `home_dir` so it can load the epoch config files when necessary.
> fix(epoch config): load config files on neard run

- core/primitives/src/shard_layout.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
Replace the custom `create_new_shard_layout` in the test with the proper `derive_shard_layout`.
> feat(resharding) - use derive_shard_layout in the testloop test

- integration-tests/src/test_loop/tests/contract_distribution_cross_shard.rs
- integration-tests/src/test_loop/tests/contract_distribution_simple.rs
- integration-tests/src/test_loop/utils/contract_distribution.rs
- integration-tests/src/test_loop/utils/mod.rs
Noticed that some simple tests succeed even if we remove the code distributing the code. Thus, adding more observability to the tests.
- Add `run_until_caches_contain_contract` to wait until the nodes contain the deployed code in their compiled-contracts cache. This is to make sure we clear the cache and call the contract, after the deploy action takes effect. We run additional tests with this option.
- Add `assert_all_chunk_endorsements_received` which checks if there is any missing chunk or chunk endorsements. This is to make sure that while the test was running there is no validation errors due to a problem in chunk distribution.
- Also move some shared functions to `utils/contract_distribution.rs`.
> feat(contract-distribution): Improve testloop tests for contract distribution for more observability

- chain/chain/src/test_utils/kv_runtime.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/epoch-manager/src/adapter.rs
- chain/epoch-manager/src/lib.rs
Replaced with the implementation on the client side using `get_epoch_chunk_producers_for_shard`
> refactor: remove get_random_chunk_producer_for_shard from EpochManager interface

- chain/chain/src/state_sync.rs
This was a TODO added during development that was forgotten about, but it's not relevant. We do delete old ones right there in that store update.
> nit(state-sync): remove TODO

- chain/chain/src/chain.rs
Currently we only call start_resharding() in postprocess_ready_block() if the node either tracks the parent shard currently, or will track it (meaning it will produce chunks for a child in the next epoch) *and* is caught up (meaning it has downloaded state for the parent and applied parent chunks from the sync_hash until the HEAD).  If it doesn't currently track it but will in the future and catchup is not done, we will not initiate the resharding and will get stuck at the beginning of the next epoch.
We can fix it by just calling start_resharding() in the same place where update_flat_storage_and_memtrie() is called during catchup, because in that case (in block_catch_up_postprocess()), we call update_flat_storage_and_memtrie() if the shard is not currently tracked but will be tracked, …
> fix(resharding): call start_resharding() when catching up blocks

- chain/chain/src/test_utils/kv_runtime.rs
- chain/client/src/stateless_validation/validate.rs
- chain/epoch-manager/src/adapter.rs
Includes replacing `get_chunk_producer` with `get_chunk_producer_info` to expose validator's public key as part of the return value.
> refactor: remove epoch manager verify_partial_deploys_signature

- Cargo.lock
- Cargo.toml
- chain/network/src/network_protocol/state_sync.rs
- deny.toml
While at the moment this is strictly a change that introduces extra dependencies and shuffling, over time we expect the ecosystem to start moving towards 2.0 bit by bit, and any new improvements to the crate to only go to the 2.0 series.
Changelog: https://github.com/dtolnay/thiserror/releases/tag/2.0.0
> chore: update thiserror to 2.0

- chain/chain/src/blocks_delay_tracker.rs
- chain/chain/src/test_utils.rs
- chain/chain/src/validate.rs
- chain/chunks/src/shards_manager_actor.rs
- chain/chunks/src/test_utils.rs
- chain/client/src/client.rs
- chain/client/src/debug.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/test_utils/test_env.rs
- chain/client/src/view_client_actor.rs
- chain/epoch-manager/src/adapter.rs
- integration-tests/src/tests/client/features/adversarial_behaviors.rs
- integration-tests/src/tests/client/process_blocks.rs
- integration-tests/src/tests/client/resharding_v2.rs
- nearcore/src/entity_debug.rs
- tools/state-viewer/src/commands.rs
Replace all usages with `get_chunk_producer_info`, follow-up to #12409.
> refactor: remove EpochManager get_chunk_producer

- chain/client/src/test_utils/peer_manager_mock.rs
- chain/network/src/peer/peer_actor.rs
- chain/network/src/peer/testonly.rs
- chain/network/src/peer_manager/network_state/mod.rs
- chain/network/src/peer_manager/peer_manager_actor.rs
- chain/network/src/peer_manager/testonly.rs
- chain/network/src/stats/metrics.rs
- chain/network/src/test_loop.rs
- chain/network/src/test_utils.rs
- chain/network/src/types.rs
- integration-tests/src/tests/network/peer_handshake.rs
- integration-tests/src/tests/network/runner.rs
- integration-tests/src/tests/network/stress_network.rs
- nearcore/src/lib.rs
- tools/chainsync-loadtest/src/main.rs
Incoming state part requests are [throttled by the view client actor](https://github.com/near/nearcore/blob/8e30ccdd425ecbbeeec8d96bfc9a7e02bc35c2d3/chain/client/src/view_client_actor.rs#L1346-L1349), which drops excess requests to avoid overloading the resources of the node. This PR removes the additional layer of queueing on the network side of things. There is little benefit from queueing:
- State part requests are made at a regular rate over a long period of time and distributed well across nodes; there is no need for serving nodes to modulate spikes in demand
- If the steady flow of incoming requests is too high for the view client's throttling rate, queueing will change _which_ requests are served but does not increase _how many_ requests are served; there is no benefit in that
and …
> network: remove tier3_request_queue

- nightly/pytest-sanity.txt
This test was disabled because it was flaky, but it was fixed in #12366
> test(nayduck): re-enable state_sync_routed

- chain/network/src/network_protocol/mod.rs
- core/primitives/src/stateless_validation/contract_distribution.rs
- core/primitives/src/validator_signer.rs
Currently we add a method to `ValidatorSigner` for every data type we want to sign. I'm not sure what exactly is a benefit of doing that, but such approach results in quite a few annoying issues:
* Overly verbose code: need to add 3 methods for every data type to be signed.
* Not consistent with signature verification: we just call `verify` method on public key passing signature and bytes, why should signing be any different?
* It blows up `ValidatorSigner` public API making it awkward to work with.
This PR repurposes `sign_chunk_contract_accesses` to be a generic `sign_bytes` method and replaces usage for witness contract code distribution related types. The rest will be addressed in a separate PR.
> refactor: move serialisation out of ValidatorSigner

- integration-tests/src/test_loop/tests/contract_distribution_cross_shard.rs
- integration-tests/src/test_loop/tests/contract_distribution_simple.rs
- integration-tests/src/test_loop/utils/contract_distribution.rs
- integration-tests/src/test_loop/utils/mod.rs
- integration-tests/src/test_loop/utils/transactions.rs
Add new testloop tests for deleting the account after deploying and calling contracts on them. For this, we use accounts separate from the validator accounts.
Also update the tests to reuse the new utils added in other PRs to share code.
Extracted from #12416.
> feat(contract-distribution): Update testloop test to use new utils and add delete-account test

- .cargo/audit.toml
instant & derivative are breaking audit in CI:
https://github.com/near/nearcore/actions/runs/11779066830/job/32806748238
This is a poor fix. Please let me know if we should find a proper one.
> chore: ignore RUSTSEC-2024-0384

- core/parameters/res/runtime_configs/73.yaml
- core/parameters/res/runtime_configs/parameters.snap
- core/parameters/src/config_store.rs
- core/parameters/src/snapshots/near_parameters__config_store__tests__129.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__73.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_129.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_73.json.snap
- core/parameters/src/snapshots/near_parameters__view__tests__runtime_config_view.snap
- core/primitives-core/src/chains.rs
- core/primitives/src/snapshots/near_primitives__views__tests__runtime_config_view.snap
- integration-tests/src/tests/client/features/congestion_control.rs
- pytest/tests/sanity/congestion_control.py
- runtime/runtime/src/tests/apply.rs
relaxing the congestion control to allow more gas (receipts) in the delayed receipts queue.
Please note I'm adding it directly to protocol version 73 because it wasn't released yet. @staffik Will it be possible to get it into 2.4?
> feat(congestion_control) - relax congestion control - part 2

- core/store/src/trie/update.rs
- runtime/runtime/src/actions.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/state_viewer/mod.rs
Extracted from #12416 since it is an unrelated change and preparation for future changes to use `ContractStorage` to set and get contract code.
> Small refactor to hide contract_storage in TrieUpdate

- chain/jsonrpc/CHANGELOG.md
- chain/jsonrpc/src/lib.rs
- nightly/pytest-sanity.txt
- pytest/tests/sanity/replay_chain_from_archive.py
- pytest/tests/sanity/rpc_missing_block.py
As requested from our partner, custom status code for a missing block was added. I decided to go with 422 Unprocessable Content which seems pretty logical to me, but let me know if this is a bad choice
closes #12399
> feat: added custom status code for a missed block

- chain/chain/src/stateless_validation/chunk_validation.rs
- core/primitives/src/stateless_validation/state_witness.rs
Currently we use epoch_id from the last block with non-missing chunk for that shard which is incorrect.
> fix: use epoch id from the witness when determining protocol version

- chain/chain/src/chain.rs
- chain/network/src/peer_manager/tests/snapshot_hosts.rs
- core/primitives-core/src/types.rs
- core/primitives/src/shard_layout.rs
- core/primitives/src/trie_key.rs
The non-contiguous ShardIds should be treated as abritrary identifiers. In particular they should not be comparable. Removing the Ord implementation from this type. 
This is a follow up to #12419 where I found a bug caused by sorting receipts by shard id instead of shard index.
> refactor(resharding) - Removing ShardId Ord

- chain/chain/src/stateless_validation/chunk_validation.rs
The same check as we already have for the `transactions` field.
See [zulip thread](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/Missing.20.60tx_root.60.20check.20for.20state.20witness.20.60new_transactions.60) for more context.
> feat: add `tx_root` check for state witness `new_transactions`

- chain/chain/src/runtime/mod.rs
- chain/epoch-manager/src/adapter.rs
- chain/epoch-manager/src/lib.rs
- tools/state-viewer/src/commands.rs
There are two versions of this function, one that looks up the `protocol_version` and can fail and the other that gets the `protocol_version` and does not fail.  This PR removes the first version and moves all uses to the second version.  This allows us to simplify some of the code and remove some error paths in the code.
> refactor: Simplify `get_epoch_config`

- chain/chain/src/test_utils/kv_runtime.rs
- chain/client/src/client.rs
- chain/epoch-manager/src/adapter.rs
The MR removes `get_epoch_sync_data` and `get_epoch_sync_data_hash` form the epoch manager trait inlines the code
> refactor: remove get_epoch_sync_data and get_epoch_sync_data_hash from epoch manager

- Cargo.lock
- deny.toml
Somewhat of a spring cleaning thing to save a build of an entire borsh deptree. We don't use borsh serialization for wasmer0 purposes in nearcore, so there is no risk that something would change behaviourally.
> chore: deduplicate borsh dependency

- tools/fork-network/src/cli.rs
When setting up a forknet, the `neard fork-network set-validators` command is run after `neard init`. If `init` was executed with `--dump-epoch-config`, the `epoch_configs` directory is populated with the `mainnet` epoch configs.
Additionally, the mirror tool now includes an option to provide overrides to the epoch configurations.
If epoch config files are present, they will be utilized to create the genesis configuration for the fork network.
> feat(fork-network): use the epoch config files to setup the nodes

- chain/client/src/client_actor.rs
- chain/network/src/test_loop.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
PR to add simple chain fork and block double signing tests to the existing resharding_v3 test loop.
The implementation is a bit hacky, but I couldn't find a better way.
- Refactored adversarial block production to extrapolate a method in `Client` with additional functionality.
- Ignoring `Challenge`s in test loop.
- Refactored `resharding_v3` test structure to pass more parameters to the base test scenario.
- Added an "hook" to execute arbitrary test code inside test loop iteration of `resharding_v3`.
Both tests fail at the moment. They seems to do trigger the behavior we want to test.
For forks consecutive resharding starts:
```
{block_hash=F5zmejS8RxnGwnJhtfH5JK4V5VbciBDrfJMwKuxpio1L block_height=13 parent_shard_uid=s1.v3}: memtrie: Freezing parent memtrie, creating children memtries... …
```
> feat(tests): add resharding chain fork tests

- chain/chain/src/resharding/manager.rs
- core/store/src/trie/mem/loading.rs
- core/store/src/trie/mem/mem_trie_update.rs
- core/store/src/trie/mem/mem_tries.rs
- core/store/src/trie/mem/resharding.rs
- core/store/src/trie/mod.rs
Generate proof for resharding (retain_multi_range) and check that it is valid against existing retain tests, already including memtrie and disktrie.
Surprisingly, #12390 allows to make the change almost invisible. The actual work here is to move `&mut TrieRecorder` inside `TrieChangesTracker` which is inside `MemTrieUpdate`.
Reasoning: when we work with `MemTrieUpdate`, it is in fact unique owner of the logic to record proof (what I called "2nd stage" in the previous PR, after "1st stage" of trie lookups). And now, if we are sure that proof doesn't need values, `MemTrieUpdate` can fully hold the `&mut`, because memtrie has all the necessary information, and we can record nodes directly on node access instead of doing it retroactively (which was really bad).
`TrieRecorder` now is passed as …
> feat: resharding proof

- chain/chain/src/runtime/mod.rs
- runtime/near-test-contracts/build.rs
- Removes some unnecessary `map_err`
- Replaces some functional code with a simple `match` statement to improve readability.
> refactor: remove unnecessary code and clarify some small code

- pytest/tests/mocknet/mirror.py
The dumper node is an RPC and tracks all shards, it does not need to load memtries
> fix(forknet): do not load the memtries on dumper node

- nearcore/src/state_sync.rs
Looks like state sync dump doesn't work at genesis, because latest final block is non-existent 111...111. State sync at genesis doesn't make sense; however, it leads to very spammy logs all the time at startup:
```
0.146s ERROR state_sync_dump: Failed to get the latest epoch shard_id=ShardId(1) err=DBNotFoundErr("BLOCK HEADER: 11111111111111111111111111111111")
0.146s ERROR state_sync_dump: Failed to get the current state err=DBNotFoundErr("BLOCK HEADER: 11111111111111111111111111111111") shard_id=ShardId(1)
...
```
So I just return None if final block sync is 111... or sync hash doesn't exist. Later, the "next state sync state" is set to None anyway, so there are no changes in behaviour.
> chore: don't log error on genesis state sync dump

- runtime/runtime/src/lib.rs
Slight glitch, `processing_state.local_receipts` will be empty after `take()`, so `local_receipt_count` is always 0, obviously not the intent.
> Fix processing metrics

- tools/indexer/example/src/configs.rs
Needed to avoid this fatal error:
```
thread 'main' panicked at /Users/saketh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.2.4/src/builder/debug_asserts.rs:115:17:
Command indexer-example: Short option names must be unique for each argument, but '-h' is in use by both 'home_dir' and 'help' (call `cmd.disable_help_flag(true)` to remove the auto-generated `--help`)
```
> indexer-example: change short option for --home-dir

- core/primitives/src/shard_layout.rs
- tools/fork-network/src/cli.rs
When the `init` command is run, the fork-network command writes state roots to the DB by key "FORK_TOOL_SHARD_ID:{shard_id}", and later reads them back by iterating over that prefix. But there is inconsistent treatment of these ShardIds sometimes as ShardIds and sometimes as ShardIndexes. Firstly, the name of the key itself indicates we should expect ShardIds to be there. But when we write them, we collect the state roots in a Vec in order of ShardLayout::shard_ids(), and then iter().enumerate() over that to write the (shard_id, state_root), which is really a shard index. Then when we read them back, we index into that array with `shard_uid.shard_id as usize`, which doesn't work when the ShardIds are shuffled.
When running this on a localnet where shard IDs are shuffled, this gives us …
> fix(fork-network): fix handling of shard IDs

- core/primitives/src/version.rs
TestNet release: Nov 19th (Tue)
TestNet voting: Nov 24th (Sun)
TestNet protocol upgrade: Nov 25th (Mon)
> voting date

- chain/chain/src/runtime/tests.rs
- chain/client/src/test_utils/client.rs
- chain/client/src/test_utils/test_env.rs
- core/primitives/src/shard_layout.rs
- genesis-tools/genesis-populate/src/lib.rs
- integration-tests/src/test_loop/tests/protocol_upgrade.rs
- integration-tests/src/tests/client/features/orphan_chunk_state_witness.rs
- integration-tests/src/tests/client/process_blocks.rs
- tools/state-viewer/src/state_dump.rs
Making more tests compatible with arbitrary ShardIds. There are still some left but making progress. The ultimate goal is to make the default shard layout to contain random shard ids.
>  refactor(resharding) - Make some tests compatible with arbitrary ShardIds part 2

- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/transactions.rs
Adding a basic test-loop test for resharding v3 and delayed receipts splitting.
During the test I'm burning more gas than the chain capacity at every block height before resharding and one block after. Thus, in the resharding block height there are delayed receipts to be split.
A couple of blocks later I verify the transaction outcomes.
The test passes if the target account is not in the parent shard. It fails if the account belongs to either future child.
> test: resharding V3 and delayed receipts

- chain/chain/src/test_utils/kv_runtime.rs
- chain/epoch-manager/src/adapter.rs
- nearcore/src/state_sync.rs
Currently, the state dumper starts one thread for each ShardId in the current epoch, and each of those is responsible for dumping headers and parts just for that ShardId. But after a resharding, there's no thread that's aware that it should dump state for any of the new ShardIds. Here we fix it by iterating not just over the ShardIds in the current epoch when we start the threads, but also over any future ShardIds that might belong to post-protocol upgrade epochs.
This is not great because we're starting threads that won't be doing anything useful (but still doing work in a loop which in tests can be nontrivial since we set the "iteration_delay" config value to 100ms) for quite some time, and we don't stop old threads after the shard ID they correspond to is no longer a valid shard ID in …
> fix(state-dumper): dump state for post-resharding shards

- chain/rosetta-rpc/src/errors.rs
- chain/rosetta-rpc/src/models.rs
- chain/rosetta-rpc/src/utils.rs
Implemented similar logic to #12402 for Rosetta RPC
> feat(rosetta-rpc): added custom status code for a missed block

- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
New test loop test for buffered receipts during resharding.
- Added a new static shard in the starting shard layout to make facilitate cross shard testing
New state before resharding:
```
accounts for shard s2.v3: ["account0"]
accounts for shard s1.v3: ["account1", "account2"]
accounts for shard s0.v3: ["account3", "account4", "account5", "account6", "account7", "near"]
```
- `test_resharding_v3_split_parent_buffered_receipts` fails when buffered receipts are present in resharded shard, it works when target shard is not changing at epoch boundary
- Changed `loop_action` to execute multiple functions, not just one
> test: reshardingV3 test loop for buffered receipts

- chain/chain/src/chain.rs
- chain/chain/src/stateless_validation/chunk_validation.rs
- chain/chain/src/update_shard.rs
- chain/client/src/stateless_validation/chunk_validator/mod.rs
- nearcore/src/state_sync.rs
- tools/replay-archive/src/cli.rs
Completes the resharding validation flow on the chunk validator side.
The code replaces `MainTransition::ShardLayoutChange` with actual logic. The whole preparation is needed to call `let new_root = trie.retain_split_shard(&boundary_account, retain_mode)?;`, to verify it against state root provided in transition.
The main complexity is to introduce implicit transition for resharding to the right place - after applying last chunk in old shard layout, potentially missing, and before applying first chunk in the new layout. To do that, I needed to modify `get_state_witness_block_range` once again, and to make it readable, I rewrote it using `TraversalPosition`. The point of that is to change all parameters of the loop at once, instead of changing them one-by-one in the loop. Then, I generate …
> resharding: verify proof

- chain/chain/src/garbage_collection.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
GC was failing after resharding because of duplications in the list of shard uids to gc.
It worked with previous resharding because all shard uids had version bumped, which is not the case since resharding v3.
Note that does this not handle delayed receipts etc.
> fix(resharding) Deduplicate shard uids for gc

- core/async/src/test_loop.rs
- core/async/src/test_loop/futures.rs
- integration-tests/src/test_loop/tests/bandwidth_scheduler.rs
- integration-tests/src/test_loop/utils/transactions.rs
Should be `Future`, not `Futute`
> fix(testloop) - Fix typo in TestLoopFutureSpawner

- core/store/src/trie/mem/mem_trie_update.rs
- core/store/src/trie/mod.rs
- core/store/src/trie/ops/insert_delete.rs
- core/store/src/trie/ops/interface.rs
- core/store/src/trie/ops/resharding.rs
- core/store/src/trie/ops/squash.rs
- core/store/src/trie/trie_storage_update.rs
This PR introduces the GenericTrieNode which is a generalization on top of GenericUpdatedTrieNode where the nodes need not be an update type node.
This is useful in scenarios where we are not dealing with just updates, for example generalizing iterators over tries etc.
Along with this change this PR renames `GenericUpdatedNodeId` to `UpdatedNodeId` which is more appropriate as for both memtries and store tries we have UpdatedNodeId as usize.
> [trie] Introduce GenericTrieNode as replacement of GenericUpdatedTrieNode

- runtime/runtime/src/lib.rs
It was decided offline that `check_balance` should not be called in release builds anymore. This PR implements this change by gating `check_balance(...)` behind `cfg!(debug_assertions)`.
> Move balance check into debug assertion

- core/store/src/trie/ops/resharding.rs
We were not handling creating the intervals for keys like delayed receipts or buffered receipts.
This PR handles creating intervals for these other-category keys based on the resharding design.
These changes were originally a part of #12518 but shifted the core logic to a separate PR.
> [resharding] Generate intervals for non account_id prefix trie keys

- chain/chain/src/tests/simple_chain.rs
- chain/client/src/client.rs
- chain/client/src/client_actor.rs
- chain/client/src/sync/header.rs
- chain/client/src/test_utils/client.rs
- chain/client/src/test_utils/setup.rs
- chain/client/src/tests/query_client.rs
- chain/network/src/network_protocol/testonly.rs
- core/primitives/benches/serialization.rs
- core/primitives/src/block.rs
- core/primitives/src/block_header.rs
- core/primitives/src/lib.rs
- core/primitives/src/test_utils.rs
- core/primitives/src/upgrade_schedule.rs
- core/primitives/src/version.rs
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/protocol_upgrade.rs
- integration-tests/src/test_loop/tests/simple_test_loop_example.rs
- integration-tests/src/tests/client/challenges.rs
- integration-tests/src/tests/client/process_blocks.rs
`test_protocol_upgrade` (added in https://github.com/near/nearcore/pull/12253) is supposed to upgrade from `old_protocol` to `new_protocol`, but it actually did an upgrade from `old_protocol` to `PROTOCOL_VERSION` (latest protocol). It just so happened that all uses of the test were with `new_protocol` equal to `PROTOCOL_VERSION` and the bug wasn't noticed when the test was written.
I did some debugging and it looks like the problem is that clients are voting for the latest protocol instead of the one specified in `new_protocol`, and switch to the latest one instead of the one that they were supposed to.
The protocol version that nodes vote for is controlled by `PROTOCOL_UPGRADE_SCHEDULE`, which is a global constant. It being a global constant makes it awkward to overwrite in tests.
I …
> fix(tests) - fix test_protocol_upgrade always upgrading to the latest version

- integration-tests/src/test_loop/tests/resharding_v3.rs
Un-ignored the buffered receipts test and added an extra check that the buffered receipts are present after resharding. 
There is a bit of refactoring here, mostly moving most of the logic of `check_receipts_presence_at_resharding_block` to a new method `check_receipts_at_block` that is now used for both before and after resharding checks.
> test(resharding) - un-ignore buffered receipts test

- chain/chain/src/chain.rs
- chain/chain/src/flat_storage_resharder.rs
- chain/chain/src/runtime/mod.rs
- chain/chain/src/runtime/tests.rs
- chain/chain/src/store/mod.rs
- chain/chain/src/test_utils.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/epoch-manager/src/adapter.rs
- chain/epoch-manager/src/shard_tracker.rs
- core/primitives/src/shard_layout.rs
- core/store/src/genesis/initialization.rs
- genesis-tools/genesis-populate/src/lib.rs
- integration-tests/src/test_loop/tests/bandwidth_scheduler.rs
- integration-tests/src/tests/client/features/congestion_control.rs
- integration-tests/src/tests/client/features/stateless_validation.rs
- integration-tests/src/tests/client/features/yield_resume.rs
- integration-tests/src/tests/client/features/yield_timeouts.rs
- integration-tests/src/tests/client/process_blocks.rs
- nearcore/src/config.rs
- tools/database/src/analyse_gas_usage.rs
- tools/flat-storage/src/commands.rs
- tools/state-viewer/src/apply_chunk.rs
This refactor simplifies the API and aligns with the ShardLayout abstraction (#12480). It implements account_id_to_shard_id as a method within ShardLayout.
The standalone function is deprecated. Usages updated
> refactor: move account_id_to_shard_id to ShardLayout

- core/primitives/src/shard_layout.rs
This is a continuation of [the previous refactor pull request](https://github.com/near/nearcore/pull/12526).
Deprecated `account_id_to_shard_id` function is removed
> refactor: remove deprecated account_id_to_shard_id

- .github/workflows/neard_release.yml
This WF will update metadata on release events:
https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/testnet/latest_release
https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/mainnet/latest_release
> Chores: trigger metadata wf on GH release events

- chain/chain/src/flat_storage_resharder.rs
- core/chain-configs/src/client_config.rs
- Small addition to the existing resharding config: added an entry to configure how many blocks of delta are applied in a batch during shard catchup
- Small fix to make use of batch_delay config also during shard catchup
> feat(config): add configuration for resharding catch up blocks

- Cargo.lock
- Cargo.toml
- core/store/src/trie/mem/loading.rs
- deny.toml
- genesis-tools/genesis-populate/src/lib.rs
- nearcore/src/download_file.rs
- tools/flat-storage/src/commands.rs
- tools/replay-archive/Cargo.toml
- tools/replay-archive/src/cli.rs
- tools/state-viewer/Cargo.toml
- tools/state-viewer/src/apply_chain_range.rs
- tools/state-viewer/src/cli.rs
- tools/state-viewer/src/progress_reporter.rs
With this PR the original `benchmarking` functionality has been subsumed by the `sequential` mode which has been extended to operate on flat and memtrie storage modes.
`benchmark` is then changed to not commit any results to the storage, effectively leading to the same starting block being applied over and over again, thus ideally demonstrating the time spent inside `Runtime::apply`.
I've seen this to sometimes handle a huge number of blocks per second which would make the output somewhat difficult keep track of, so I went ahead and integrated indicatif-based progress bar (which then also comes with a built-in mechanism to estimate duration and rate of blocks per second.)
> apply-range: add ability to operate with memtries & a new benchmark mode

- pytest/tests/mocknet/mirror.py
* `nodes.find` doesn't work because `'list' object has no attribute 'find'`. The closest working code is `next(filter)`.
* `gsutil rm` can fail if there are no state parts which crashes mirror. Allowing `return_on_fail` then.
> fix(forknet): clearing state parts

- chain/chain/src/flat_storage_resharder.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
In this PR there're two main changes:
- Introduction of an adversarial parameter in `FlatStorageResharder` to allow the addition of an arbitrary block delay to the scheduling of the split shard task. This can be useful to emulate long running tasks in test loop.
- New test to check resharding works if splitting flat storage finishes later into the epoch.
> test(resharding): add adversarial method to delay flat store resharding 

- integration-tests/src/tests/client/sync_state_nodes.rs
https://nayduck.nearone.org/#/run/833
Apparently the current failure is triggered regularly for 9s epochs and not triggered for 21s epochs. While this is not proper fix, it unblocks the pipeline.
> fix: increase epoch time in sync_state_dump

- chain/client/src/sync/epoch.rs
I think if I understand correctly, the way the AwaitingPeers state works is simply a marker for the starting state. The mechanism by which we transition away from the AwaitingPeers state is by header sync replacing it with HeaderSync when there are enough peers to run the header sync code at all.
So, before this PR, what would happen is that we start with AwaitingPeers, and epoch sync will see that and say "oh we don't have enough peers, so let's skip", but then header sync takes the stage and starts syncing headers. This ruins the header_head by moving it away from genesis, making epoch sync no longer eligible. In fact, this happens pretty reliably because at startup we would always perform header sync first before performing epoch sync, and since epoch sync is most likely slower than …
> [Epoch Sync] Make epoch sync happen before header sync on AwaitingPeers.

- chain/client/src/sync/epoch.rs
[Epoch Sync] Make epoch sync happen before header sync on AwaitingPeers. (#12563)
I think if I understand correctly, the way the AwaitingPeers state works is simply a marker for the starting state. The mechanism by which we transition away from the AwaitingPeers state is by header sync replacing it with HeaderSync when there are enough peers to run the header sync code at all.
So, before this PR, what would happen is that we start with AwaitingPeers, and epoch sync will see that and say "oh we don't have enough peers, so let's skip", but then header sync takes the stage and starts syncing headers. This ruins the header_head by moving it away from genesis, making epoch sync no longer eligible. In fact, this happens pretty reliably because at startup we would always perform header sync …
> 2.4.0-rc2 Epoch sync fix

- pytest/tests/mocknet/helpers/neard_runner.py
- tools/mirror/src/lib.rs
The reason this was done originally was to make sure we apply all chunks so that in `on_target_block()` we can look through all the outcomes and keep track of how many of our txs made it on chain, and so that we can figure out what unstake actions need to be sent to undo stakes that came from staking pool contract calls. The first one is just best effort anyway, and the second one won't even be that relevant in the case where the traffic generator is offline for several epochs and state syncs, since by that time it will be too late to unstake them. So just remove this check and don't make the traffic generator an archival node
> mirror: don't require an archival dir for the traffic generator

- integration-tests/src/test_loop/tests/resharding_v3.rs
* Added base_shard_layout_version to the resharding test loop params. 
* Refactored the buffered receipts tests to have one test for each base shard layout
* Refactored the load memtrie tests to have one test for each base shard layout
* ~Removed what seems to be an old copy of some tests - we have tests for both `buffered` and `outgoing` receipts that look like old and new versions of the same test. Please let me know if that's not the case and those were actually testing different things.~
Let me know if any other tests deserve to cover both cases. For now the default is set to V2 because that's what we'll use in the long term. 
I'm curious if there is any rust library for automatically creating tests for various test parameters combinations. Thoughts on whether that would be useful?
> test(resharding) - Test resharding with both V1 and V2 base shard layout

- Cargo.lock
Should fix the audit error. The updates seem like they should be risk free.
(Holy hot dog, whole ICU??? For urls??????)
> chore: update smallvec, url, idna

- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
Since `SimpleNightshadeV4` stopped being the latest nightly feature, the dropper stopped dropping chunks **after** protocol upgrade, because the protocol version became too high.
> test(resharding): chunk dropper fix

- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/mod.rs
- integration-tests/src/test_loop/utils/receipts.rs
- integration-tests/src/test_loop/utils/sharding.rs
- integration-tests/src/test_loop/utils/transactions.rs
- integration-tests/src/test_loop/utils/trie_sanity.rs
The resharding V3 test loop became a beast of a file rather quickly.
This PR simply moves some utility functions outside of the test into three other files, grouped by theme:
- `receipts.rs` for all things about checking receipts existence
- `sharding.rs` for everything related to shards and shard layout
- `trie_sanity.rs` for the new TrieChecker implemented by @marcelo-gonzalez 
Hopefully this will make the method more reusable.
`TestReshardingParameters` is not touched. It still needs improvements though.
> refactor: Move out utilities from resharding_v3 test loop

- core/store/src/db.rs
- core/store/src/db/testdb.rs
- core/store/src/test_utils.rs
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
With reshardingV3, parent's delayed receipts are copied (shared) to both children and irrelevant receipts are ignored by children. However, it causes the same delayed receipt to be removed twice (by both children) during garbage collection, which causes `TestDB` to panic in resharding testloop tests. But it works in real setting, where apparently rocksdb allow negative refcounts.
After [discussion](https://near.zulipchat.com/#narrow/channel/407288-core.2Fresharding/topic/Delayed.20Receipts), we decided to ignore negative refcounts in `TestDB` for resharding only, and may think about proper solution later.
> test(resharding): allow negative refc in testdb for resharding

- chain/chunks/src/chunk_cache.rs
- chain/client/src/tests/doomslug.rs
- chain/network/src/accounts_data/tests.rs
- chain/network/src/network_protocol/testonly.rs
- core/crypto/src/signer.rs
- core/primitives/benches/serialization.rs
- core/primitives/src/test_utils.rs
- core/primitives/src/validator_signer.rs
- core/store/benches/finalize_bench.rs
- integration-tests/src/tests/client/block_corruption.rs
- integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
- integration-tests/src/tests/client/runtimes.rs
- integration-tests/src/tests/client/state_dump.rs
- nearcore/src/config.rs
- tools/state-viewer/src/state_dump.rs
Following #11531  InMemorySigner's and InMemoryValidatorSigner's factory methods should return Signer and ValidatorSigner interfaces respectively. The PR provides such implementation for:
- InMemorySigner::from_secret_key
- InMemoryValidatorSigner::from_random
- InMemoryValidatorSigner::from_seed
- InMemoryValidatorSigner::from_signer
- InMemoryValidatorSigner::from_file
> refactor(InMemorySigner, InMemoryValidatorSigner) factory methods 

- chain/chain/src/chain_update.rs
- chain/chain/src/garbage_collection.rs
- chain/chain/src/store/mod.rs
- chain/chain/src/store_validator.rs
- chain/chain/src/store_validator/validate.rs
- tools/state-viewer/src/apply_chunk.rs
Detailed discussion here https://near.zulipchat.com/#narrow/channel/295558-core/topic/DBCol.3A.3AReceipts.20.2B.20single.20shard.20tracking
The way we choose the receipts to write to DBCol::Receipts is incorrect if the node does not track all shards. The prev_outgoing_receipts of a chunk do not represent the receipts executed by the chunk, but rather the outgoing receipts from the execution of the previous chunk, which target arbitrary shards. In other words, if a node tracks only some shards, a receipt may be executed by the node but not actually in the Receipts column.
To fix this, we change the DBCol::Receipts column to be an exact reindexing of the DBCol::IncomingReceipts column, which accurately reflects the receipts that this node would actually execute.
Even though this changes the …
> Fix persistence of the Receipts column if we don't track all shards.

- core/primitives/Cargo.toml
- core/primitives/src/shard_layout.rs
Simple PR with a motivation to avoid loading extra dependencies when using `test-utils`.
`near-json-rpc-client` uses `test-utils` feature for transaction.sign() API, but it doesn't really need random in the scope
@race-of-sloths
> chore: separated rand and test_utils features in the near-primitives

- chain/client/src/chunk_inclusion_tracker.rs
- chain/client/src/client_actor.rs
- chain/client/src/metrics.rs
This PR extends `near_block_producer_insufficient_endorsement_chunk_count` metric to `near_block_producer_excluded_chunks_count` with `reason` label.
> feat: add metric for excluded chunks on the block producer side

- core/primitives/src/epoch_manager.rs
- core/store/src/config.rs
- core/store/src/trie/trie_storage.rs
- nearcore/src/config.rs
Address https://github.com/near/nearcore/blob/649743f6cb94474644b0cd5d0693b4fe5b277a0f/core/store/src/config.rs#L214-L215
by deriving shard cache limit from known access pattern (per contract account) such that the limits can stay relevant after resharding
> feat: auto per-shard cache size limit across resharding

- chain/chain/src/garbage_collection.rs
- chain/chain/src/store/mod.rs
- chain/chain/src/store_validator.rs
- chain/chain/src/store_validator/validate.rs
- chain/chunks/src/logic.rs
- chain/client/src/client.rs
IncomingReceipts double counts when we do catchup state sync because we persist the state sync boundary's IncomingReceipts again. So.. switch to using PartialEncodedChunk to make the DBCol::Receipts column. It's equivalent, really.
> Revise #12613 by using PartialEncodedChunk instead of IncomingReceipts

- chain/chain/src/resharding/resharding_v2.rs
- chain/chunks/src/client.rs
- chain/epoch-manager/src/tests/mod.rs
- core/primitives/src/shard_layout.rs
- core/store/src/config.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/tests/client/resharding_v2.rs
`account_id_to_shard_uid` belongs to ShardLayout and not as a stand alone function.
> [cleanup] Push account_id_to_shard_uid function in shard_layout

- Cargo.lock
- Cargo.toml
Using simd will speed up the reed solomon encoding and decoding
> chore: enable simd-accel feature for reed solomon crate

- chain/network/src/peer_manager/connection/mod.rs
We missed that when refactoring chunk endorsement logic. The old `ChunkEndorsement` message was removed in #12131, but we forgot to add the new message introduced in #11091.
I've noticed that by looking at mainnet metrics where `VersionedChunkEndorsement` message is only sent via T2.
> fix: use T1 for sending chunk endorsements

- chain/network/src/peer_manager/connection/mod.rs
This is a follow-up to [this comment](https://github.com/near/nearcore/pull/12632#pullrequestreview-2507529710).
> refactor: explicitly list all message types when specifying tier

- chain/network/src/peer_manager/connection/mod.rs
See [this comment](https://github.com/near/nearcore/pull/12634#pullrequestreview-2508723983).
> refactor: explicitly list all message types in tcp::Tier::is_allowed

- docs/SUMMARY.md
- docs/architecture/storage/flat_storage.md
With PR #12381 the name of `trie.md` was changed to [trie_storage.md](https://github.com/near/nearcore/pull/12381/files#diff-241b373494cf811201567825847b904ff1e29134525b86d5f6f5c1e35d0e0e83)
> docs: wrong path for trie.md

- core/parameters/src/config.rs
Such config that disables limits is useful for tests/benchmarks. An equivalent `test_disabled` already exists for `CongestionControlConfig`:
https://github.com/near/nearcore/blob/e692d204ed97add40f6fa5baea4477f9b28f9c49/core/parameters/src/config.rs#L217-L221
I plan to use `WitnessConfig::test_disabled` in a follow up PR to make `benchmarknet` config adjustments.
> test: create a `WitnessConfig` that removes limits

- core/parameters/src/config_store.rs
Previously, for benchmarknet some fields of `CongestionControlConfig` and `WitnessConfig` had been modified. As these structs evolved, the modifications became outdated.
This PR uses `test_disabled()` to generate entire `CongestionControlConfig` and `WitnessConfig` structs with all limits disabled. With this approach, fewer updates to benchmarknet adjustments should be required in the future.
Note that this config is effective only when `chain_id: "benchmarknet"`, which should happen only in tests or benchmarks.
> test: update config adjustments for `benchmarknet`

- chain/epoch-manager/src/tests/mod.rs
- chain/epoch-manager/src/validator_selection.rs
- core/chain-configs/src/test_genesis.rs
- core/primitives-core/src/version.rs
- integration-tests/src/test_loop/tests/fix_chunk_producer_stake_threshold.rs
- integration-tests/src/test_loop/tests/fix_stake_threshold.rs
- integration-tests/src/test_loop/tests/mod.rs
In case of **empty seats**, the seat price of cp used to depend on the number of existing shards (approximately `block_producer_threshold / num_shard`), but it is no longer the case. Hence the fix.
cc @Longarithm @wacban
> feat: fix chunk producer staking threshold

- chain/chain/src/chain.rs
- `chain/chain/src/chain.rs:3918`: "preprocesing" corrected to "preprocessing".
- Improved code accuracy and ensured professionalism by fixing the typo.
> typo-Update chain.rs

- tools/state-viewer/src/trie_iteration_benchmark.rs
- tools/themis/src/rules.rs
- tools/undo-block/src/lib.rs
- Fixed typo: "`accound `" → "Creates a new `account `"
- Fixed typo: "`superfluouos `" → "Creates a new `superfluous `"
- Fixed typo: "`alreay `" → "Creates a new `already `"
> chore: docs fix spelling issues

- core/store/src/metadata.rs
- docs/practices/workflows/benchmarking_synthetic_workloads.md
- integration-tests/src/test_loop/utils/trie_sanity.rs
- integration-tests/src/tests/runtime/test_yield_resume.rs
- pytest/tests/replay/README.md
- pytest/tests/sanity/split_storage.py
This PR focuses on correcting typos and improving clarity in documentation files.
Thank you very much.
> chore: fix some typos in comment

- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/loop_action.rs
- integration-tests/src/test_loop/utils/mod.rs
- integration-tests/src/test_loop/utils/receipts.rs
Some resharding tests were failing with single shard tracking enabled because of epoch length was sligthly too short.
Under the hood, if we are close to epoch length (4 blocks or less), we forward transactions to chunk producer for the next epoch too. But if the epoch length is 6, it means the chunk producer has only 2 blocks to catchup before it is supposed to start accepting transactions for the new shard. In such case, `TX_CHECK_BLOCKS_AFTER_RESHARDING` needs also be increased.
**Changes:**
This PR sets `INCREASED_EPOCH_LENGTH: 8` for these tests.
For remaining tests, I keep the old `DEFAULT_EPOCH_LENGTH: 6`, to test potentially more corner cases, and some tests seem to be designed with this specific epoch length in mind.
`TX_CHECK_BLOCKS_AFTER_RESHARDING ` is increased to almost max …
> fix(resharding): Increase epoch length for shard shuffling

- chain/chain/src/orphan.rs
- core/async/README.md
- core/primitives/src/stateless_validation/stored_chunk_state_transition_data.rs
- runtime/near-vm-runner/src/instrument/stack_height/thunk.rs
- runtime/near-vm/test-api/src/sys/externals/global.rs
- runtime/runtime-params-estimator/src/trie.rs
- tools/congestion-model/src/main.rs
This pull request addresses several typographical errors across multiple files in the repository. Specifically, it corrects the usage of indefinite articles ("a" vs. "an") and other minor grammatical issues for improved readability and accuracy. Below are the key changes:
1. **File:** `chain/chain/src/orphan.rs`
- Fixed: "a orphan block" → "an orphan block"
2. **File:** `core/async/README.md`
- Fixed: "a event-loop-based" → "an event-loop-based"
3. **File:** `core/primitives/src/stateless_validation/stored_chunk_state_transition_data.rs`
- Fixed: "a implicit missing chunk" → "an implicit missing chunk"
4. **File:** `runtime/near-vm-runner/src/instrument/stack_height/thunk.rs`
- Fixed: "a index of a thunk" → "an index of a thunk"
5. **File:** …
> Fix typographical errors

- integration-tests/src/test_loop/tests/congestion_control.rs
- integration-tests/src/test_loop/tests/contract_distribution_cross_shard.rs
- integration-tests/src/test_loop/tests/create_delete_account.rs
- integration-tests/src/test_loop/tests/max_receipt_size.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/mod.rs
- integration-tests/src/test_loop/utils/resharding.rs
- integration-tests/src/test_loop/utils/transactions.rs
- integration-tests/src/test_loop/utils/trie_sanity.rs
Partially applies the patch: https://github.com/near/nearcore/pull/12597
It was failing for delayed receipt tests with `MissingTrieValue(TrieStorage)` inside
`check_state_shard_uid_mapping_after_resharding`.
The reason is that trie access interface returns `None` for a key with an empty value (which is the case for delayed receipts and negative refcounts).
That was not caught up before the patch, because the `check_state_shard_uid_mapping_after_resharding` was called after resharding, but not in the end of the test (after gc kicked in).
**Changes**
This PR modifies the `check_state_shard_uid_mapping_after_resharding` to not check entries with negative refcount.
The test is refactored so that the main loop does not finish an epoch after resharding, but keeps running until gc kicks in.
For …
> fix(resharding): MissingTrieValue in tests

- chain/chain/src/flat_storage_resharder.rs
If `account_id` of a key does not map to any child (and thus does not belong to the parent in the first place), just log a warning and avoid failing the entire operation.
> fix(resharding): do not fail flat storage resharding if account id does not belong to parent

- chain/chain/src/flat_storage_resharder.rs
Adding a TODO to remember to put in place a debug assertion inside the `shard_uid` sanity check.
> docs: add a TODO to flat storage resharder

- chain/chain/src/runtime/test_utils.rs
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/resharding.rs
- nearcore/src/test_utils.rs
A test for cleanup after resharding.
Adds an extra client without a role, that initially tracks the parent shard, then a child shard, and then an unrelated shard.
After a few epochs, only the last tracked shard should reside in State, while currently the test fails because it has entries from the first tracked shard too.
**Changes**
- Fix a bug in test infra: pass `gc_num_epochs_to_keep` to the runtime.
- Add `tracked_shard_schedule` option to resharding testloop, in order to test the cleanup.
- Add the cleanup test itself (ignored for now).
> test(resharding): base resharding scenario state cleanup

- Cargo.lock
- chain/indexer/src/lib.rs
- chain/indexer/src/streamer/fetchers.rs
- chain/indexer/src/streamer/mod.rs
- tools/indexer/example/Cargo.toml
- tools/indexer/example/src/main.rs
- tools/mirror/src/lib.rs
Tested this out by using Finality::None in mpc node indexers. Observed reduction of latency.
> indexer: make block finality configurable

- chain/chain/src/chain.rs
- chain/client/src/sync/state/shard.rs
- core/store/src/trie/shard_tries.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
This PR contains a small code change to fix a failure in the tests `test_resharding_v3_load_mem_trie_`.
In the test a client that doesn't track the parent shard is assigned to track one of the children in the next epoch after resharding. However, in order to track the children shard, the client must state sync the state of the parent and perform the shard split.
This fix allows the catchup routine to build the memtrie even with `load_mem_tries_for_tracked_shards=false`, only if the shard is "pending resharding in the future".
The first two commits are updates of code comments.
> fix: allow loading of memtrie during catchup, for shards pending resharding

- chain/chain/src/resharding/manager.rs
- integration-tests/src/test_loop/utils/trie_sanity.rs
Introduce the fix from https://github.com/near/nearcore/pull/12635 now, will add test later as it requires one of two:
- memtrie support for double resharding without restart
- testloop support for restarting a node
> fix(resharding): double resharding state mapping

- runtime/runtime/src/bandwidth_scheduler/mod.rs
Creating a tracing span doesn't do anything by itself, you have to enter it as well.
> fix(bandwidth_scheduler) - enter tracing span

- runtime/runtime/src/bandwidth_scheduler/distribute_remaining.rs
- runtime/runtime/src/bandwidth_scheduler/mod.rs
- runtime/runtime/src/bandwidth_scheduler/scheduler.rs
- runtime/runtime/src/bandwidth_scheduler/simulator.rs
- test-utils/testlib/src/bandwidth_scheduler.rs
After bandwidth scheduler processes bandwidth requests, there's usually some leftover budget for sending and receiving.
Let's grant more bandwidth to use up this remaining budgets, it's wasteful to not use them.
The algorithm for distributing remaining bandwidth is a bit magical, I don't have an easy way to explain why it works well, it was developed by intuition and trying different things. I can prove that it's safe and fast, but proving fairness and high utilization is much harder.
The intuition is that when a shard can send out X bytes of data and there are Y links on which things could be send, the shard should send about X/Y bytes of data on each link. But it can't just send out X/Y, it has to make sure that everything stays withing the receiver's budget. The sender and receiver …
> feat(bandwidth_scheduler) - distribute remaining bandwidth

- README.md
"become validator": Should be "become a validator" (missing the article "a").
Corrected.
> docs: fix typo Update README.md

- chain/chain/src/flat_storage_resharder.rs
this was fixed in https://github.com/near/nearcore/pull/12589 but this TODO was left around
> chore(resharding): remove outdated TODO

- chain/chain/src/flat_storage_resharder.rs
- Refactoring `shard_catchup_apply_deltas` to return an enum which is more explicit than previous return type
- Now `shard_catchup_apply_deltas` gets cancelled correctly if resharding is aborted
- Added a small simple test
> feat(resharding): make flat storage shard catchup cancellable

- runtime/runtime/src/congestion_control.rs
Previously the assert was:
```rust
assert_eq!(all_buffers_empty, self.own_congestion_info.buffered_receipts_gas() == 0);
```
But this is wrong. It could happen that buffers are not empty, but `buffered_receipts_gas` is zero. Data receipts have zero gas, so having only Data receipts in the outgoing buffer would trigger the assert.
Let's instead assert that gas is zero when there are no receipts, that should always be true.
> fix(congestion_control) - don't assume that gas is nonzero when buffers are not empty

- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/sharding.rs
- integration-tests/src/test_loop/utils/trie_sanity.rs
Unblocks https://github.com/near/nearcore/pull/12691
**Changes**
* Adjust `check_state_shard_uid_mapping_after_resharding` so that it can be run for a client that does not track all shards.
* Run `check_state_shard_uid_mapping_after_resharding` for each client.
* Slightly refactor (simplify) resharding test loop.
> test(resharding): Adjust State mapping check for single shard tracking

- runtime/near-vm/test-api/src/sys/externals/global.rs
- runtime/near-vm/test-generator/src/processors.rs
- Fixed "a incompatible type" → "an incompatible type" in `global.rs`.
- Corrected "is a Emscripten" → "is an Emscripten" in `processors.rs`.
> Fix spelling

- chain/network/src/peer/peer_actor.rs
- chain/network/src/peer_manager/network_state/mod.rs
The detailed description of the problem is available at #12364
> Mismatched handshake

- core/primitives/src/bandwidth_scheduler.rs
Bandwidth scheduler always grants `base_bandwidth` on all links. `base_bandwidth` has to be low enough to allow granting enough bandwidth to send a max size receipt on one link without going over the `max_shard_bandwidth` limit.
Previously I described this requirement as:
```rust
num_shards * base_bandwidth + max_receipt_size <= max_shard_bandwidth
```
But this is actually incorrect. The inequality assumed that `base_bandwidth` is granted on every link, and then `max_receipt_size` of bandwidth is granted on top of that. This is not what actually happens, the bandwidth scheduler is smarter than that. It'll notice that one link already has `base_bandwidth` granted on it and increase the grant by `max_receipt_size - base_bandwidth`, not `max_receipt_size`.
This means that the proper …
> fix(bandwidth_scheduler) - slightly increase base_bandwidth

- runtime/runtime/src/congestion_control.rs
This PR builds on top of https://github.com/near/nearcore/pull/12710 and is related to issue https://github.com/near/nearcore/issues/12701
After resharding, we copy the set of delayed receipts from parent to both children. While handling delayed receipts in the new shard, we iterated over all the delayed receipts and ignored/removed the ones that did not belong to our shard.
Due to the implementation however, we bypassed checks to the state witness size limit in the specific case of when the receipt did not belong to our shard.
Now that we are doing the checks for the state witness size within the trie recorder, it's much simper to go back and check the proof size limit after reaching EVERY delayed receipt.
> [resharding] Check proof size limit while reading delayed receipts

- pytest/tests/mocknet/mirror.py
Allow `reset` command to run without `--gcs...` parameter.
```
mirror reset --backup-id start --yes        
Traceback (most recent call last):                                                                                                                                                                                  
File "/Users/razvan/repos/nearcore/pytest/tests/mocknet/mirror.py", line 772, in <module>                                                                                                                         
args.func(args, traffic_generator, wanted_nodes)                                                      
File "/Users/razvan/repos/nearcore/pytest/tests/mocknet/mirror.py", line 381, in reset_cmd
_clear_state_parts_if_exists(_get_state_parts_location(args), nodes) …
```
> fix(forknet): Fix the state parts bucket cleanup logic

- docs/README.md
While reviewing the Introduction section of the guide, I noticed a minor grammatical error in the sentence:  
**Current:**  
> The target audience of this guide are developers of nearcore itself.  
The issue lies in the use of "are" instead of "is." The subject "audience" is singular, so the correct verb form should be "is."  
**Fixed:**  
> The target audience of this guide is developers of nearcore itself.  
This update ensures grammatical accuracy and improves the readability of the text.
> docs: Fix grammatical error Update README.md

- Cargo.lock
- Cargo.toml
- core/store/src/db/rocksdb.rs
Updating rocksdb to 0.22 allows us to remove the run-time CStr → str conversion when collecting statistics.
rocksdb is at 0.23 however I got dependency resolution failure when trying to update to that version (included below).  Since 0.22 is enough to resolve one of my TODOs, my job here is done.  ;)
error: failed to select a version for `tikv-jemalloc-sys`.
... required by package `tikv-jemallocator v0.5.4`
... which satisfies dependency `tikv-jemallocator = "^0.5.0"` of package `neard v0.0.0 (…)`
> chore: update rocksdb dependency to 0.22

- pytest/tests/replay/README.md
- runtime/near-vm/engine/src/universal/link.rs
> docs: Spelling error.

- .github/workflows/neard_test_features_binary.yml
This can be useful for forknet testing.
> config: add github action to build neard binary with test_features enabled

- chain/chain/src/stateless_validation/chunk_validation.rs
Based on top of https://github.com/near/nearcore/pull/12627.
> chain: require that new_transactions are empty

- chain/chain/src/runtime/mod.rs
- runtime/runtime-params-estimator/src/estimator_context.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/verifier.rs
In the old flow, validation (including signature checks) happened inside `verify_and_charge_transaction()`. In the new flow, we first run `parallel_validate_transactions()` to validate and compute the transaction cost (including signature checks) in parallel. Only after a transaction passes validation do we call `verify_and_charge_transaction()` with the known `cost`.
```mermaid
graph TD;
subgraph Old_Flow
A[Runtime::apply]
A-->B[self.process_transactions]
B-->C[process_transaction]
C-->D[verify_and_charge_transaction]
D-->E[validate_transaction incl. signature]
E-->|Valid|F[charge fees & finalize]
E-->|Invalid|G[reject tx]
end
subgraph New_Flow
A2[Runtime::apply]
A2-->H[self.process_transactions]
H-->|parallel|I[parallel_validate_transactions incl. signature]
I-->|Valid, get …
```
> runtime: validate transactions in parallel

- chain/chain/src/flat_storage_resharder.rs
This PR fixes a rather old misconception in flat storage resharding.
When the slit parent task gets cancelled (because the node gets stopped) the resharding status of parent and children should not be reverted back to what it was previously. 
In this way resharding can resume when the node starts again.
> fix(reshading): cancelling the resharding task should not cancel the entire resharding

- core/primitives/src/bandwidth_scheduler.rs
- core/store/src/trie/outgoing_metadata.rs
- runtime/runtime/src/bandwidth_scheduler/scheduler.rs
- runtime/runtime/src/bandwidth_scheduler/simulator.rs
As @matejpavlovic pointed out in his NEP review, the last few `BandwidthRequestValues` can never be granted because granting them along with base bandwidth would always cause the shard to exceed `max_shard_bandwidth`.
In the current configuration with 6 shards the `base_bandwidth` is set to `61139` and the last few values are `4194304, 4278056, 4389028, 4500000`.
But `4278056` can never be granted on a link because `4278056 + 5 * 61139 = 4583751`, which is more than `max_shard_bandwidth` (4_500_000). That makes the last three values useless, they just take up space that could be used for more precise bandwidth requests.
Let's solve it by adding a new parameter to `BandwidthSchedulerParams`: `max_single_grant`
`max_single_grant` describes the maximum amount of bandwidth that can be granted …
> fix(bandwidth_scheduler) - Remove BandwidthRequestValues which can never be granted

- chain/chain/src/chain.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
Follow up to [zulip discussion](https://near.zulipchat.com/#narrow/channel/407288-core.2Fresharding/topic/forknet/near/494153325).
Hot fix to unblock resharding testing, until we have the proper fix in place.
> fix(resharding): catchup shard even if not tracked for 1 epoch

- tools/speedy_sync/README.md
Fix Typo in `README.md`
This pull request corrects a minor typo in the `README.md` file located in the `tools/speedy_sync/` directory of the `nearcore` repository.
- Fixed the typo:
- **Before**: `sync from scrach`
- **After**: `sync from scratch`
> typo fix README.md

- pytest/tests/mocknet/node_config.py
Archival nodes should not be considered for the validator pool
> feat(forknet): treat archival ndoes as RPC

- chain/chain/src/flat_storage_resharder.rs
Copy out of boundaries accounts into the closes child, during flat storage resharding. With a test to validate.
Summary of the new behavior:
```
| shard0 | shard1 | shard2 |
|--------|--------|--------|
|        | c,z    |        |  <- accounts
|--------|--------|--------|
d        m           <- boundaries
```
If we split `shard1` at a new boundary `g`, the account `c` will go into the first child and the account `z` into the second.
> fix(resharding): copy out of boundary accounts to the closer shard

- runtime/near-vm/compiler-singlepass/src/codegen_x64.rs
- runtime/near-vm/engine/src/error.rs
- runtime/near-vm/engine/src/universal/link.rs
- runtime/near-vm/test-generator/src/processors.rs
- runtime/runtime-params-estimator/src/trie.rs
- runtime/runtime/src/actions.rs
- Fixed spelling in `codegen_x64.rs`, correcting "alignement" to "alignment."
- Corrected "ocurred" to "occurred" in error messages in `error.rs` and `link.rs`.
- Fixed "writen" to "written" in `link.rs`.
- Corrected "genrator" to "generator" in `processors.rs`.
- Fixed "extention" to "extension" in `trie.rs`.
- Corrected "contrct" to "contract" in `actions.rs`.
> Fixed spelling

- chain/chain/src/chain.rs
`height_created` shouldn't be used to check that chunk is new, because in the case of block skip block height will be strictly greater. `height_included` must be used and that's what method `is_new_chunk` does.
Also using `is_genesis` for genesis case check (`self.prev_block_hash() == &CryptoHash::default()`) because it's equivalent and a little more neat.
> fix: is_new_chunk condition on block validation

- chain/chain/src/chain.rs
- chain/chain/src/sharding.rs
- chain/chain/src/stateless_validation/chunk_validation.rs
- tools/replay-archive/src/cli.rs
#10584
There is another unexpected dependency on block hash during chunk application - it is used in `shuffle_receipt_proofs` to shuffle new receipts targeting our shard. As block hash is unknown in optimistic block, I replace it with prev block hash with a protocol upgrade.
Additionally, use `Chunks` instead of `Block` in `collect_incoming_receipts_from_chunks` - it will be useful for optimistic block execution flow later.
Some block producer can brute force hashes to get salt which gives more desirable order. But block hash is prone to that as well, prev hash has equivalent safety.
I use `BlockHeightForReceiptId` feature because it has similar goal and it is going to be released soon. Adding separate feature makes code harder to read I think.
IMO it makes sense only to check consistency …
> feat(optimistic_block): shuffle incoming receipts based on prev hash

- core/primitives/src/shard_layout.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/setups.rs
- integration-tests/src/test_loop/utils/sharding.rs
* `test_resharding_v3_two_independent_splits` - tests basic scenario where we split two independent shards.
* `test_resharding_v3_two_splits_one_after_another_at_single_node` - tries to reproduce the scenario that we have in recent forknet test, where one node tracks (first_parent) -> (first_parent_child, second_parent) -> (second_parent_child). (Un)fortunatelly, it passes too.
Double resharding (split child after first resharding) actually needs restarts and is not supported yet in testloop.
> test(resharding): two independent splits

- core/store/src/db.rs
- core/store/src/db/refcount.rs
- core/store/src/db/testdb.rs
- core/store/src/test_utils.rs
- integration-tests/src/test_loop/builder.rs
- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/trie_sanity.rs
In ReshardingV3 we shallow copy some subtries to both children, but there is just a single copy on disk.
That results in these trie nodes having negative refcounts. As a quick mitigation, we decided to clamp these negative refcounts to 0.
> fix(resharding): Clamp negative refcounts to 0

- runtime/runtime/src/verifier.rs
Add `validate_verify_and_charge_transaction` function for verifier tests which combines `validate_transaction` and
`verify_and_charge_transaction` functions. This reduces complexity of current and future tests.
> refactor: add helper function for verifier tests

- Cargo.lock
- chain/chain/src/flat_storage_resharder.rs
- core/store/src/flat/storage.rs
- runtime/runtime/src/verifier.rs
- tools/flat-storage/Cargo.toml
- tools/flat-storage/src/commands.rs
- tools/flat-storage/src/lib.rs
- tools/flat-storage/src/resume_resharding.rs
This PR adds a new tool for flat storage, to resume resharding if the node is stopped or crashes before an ongoing resharding can terminate.
Tested in this way:
- Grab a forknet
- Schedule resharding
- Stop the node while resharding is in progress
- Start the node, verify it fails
- Run the tool `.near/neard-runner/binaries/neard0 flat-storage resume-resharding --shard-id 0`
- Verify flat state for parent and children is correct on disk
- Restart the node and verify it can rejoin the network
> feat: implement resume-resharding tool

- chain/chain/src/resharding/manager.rs
The "prev block has the same shard layout" log was printed every block. Changed it to only be logged at the epoch boundary.
> logs(resharding) - Make logs less spammy

- chain/epoch-manager/src/adapter.rs
- chain/epoch-manager/src/tests/mod.rs
The issue was that since `STABLE_PROTOCOL_VERSION` was higher than what's in mainnet the implementation was including the current shard layout in the calculation. Additionally the current shard layout is V1 and it has non-unique shard ids which made it seem like there is a resharding pending. 
The fix is to exclude the head shard layout from the calculation.
> fix(resharding) - fix loading shards when no resharding is scheduled

- nearcore/src/lib.rs
- nearcore/src/metrics.rs
This function creates its own epoch manager with new_from_genesis_config(), but this is not how the main epoch manager is created at startup, which is done with new_arc_handle(). These result in epoch managers that return different EpochConfigs for a given protocol version, since only the second one initializes an epoch config store from the genesis config, and the first one generates epoch configs with generate_epoch_config(). In this case it leads to a crash if the shard layouts are different because the call to `ShardUId::from_shard_id_and_layout()` will see the wrong shard IDs and crash at `assert!(shard_layout.shard_ids().any(|i| i == shard_id));`
> fix(metrics): pass the epoch manager to spawn_trie_metrics_loop

- chain/client/src/sync/header.rs
- cspell.json
- nightly/README.md
- nightly/pytest-sanity.txt
- pytest/lib/cluster.py
- pytest/lib/utils.py
- pytest/tests/sanity/state_sync_routed.py
The test was failing when the node was slow to catch up and was still at height 0 when entering this loop: 
https://github.com/near/nearcore/blob/ba1ed9f7b26cd6bc20115a9d5350bef4cfbb18bb/pytest/tests/sanity/state_sync_routed.py#L106-L107 
In this case the `hash_` here would be the genesis block hash:
https://github.com/near/nearcore/blob/ba1ed9f7b26cd6bc20115a9d5350bef4cfbb18bb/pytest/tests/sanity/state_sync_routed.py#L118-L120
The `ctx.send_moar_txs` would send it to a node that is fully caught it and has already garbage collected the genesis block. In this case the transaction would be invalid and the balance check would fail. This would in turn lead to the test being stuck forever in the final loop:
https://github.com/near/nearcore/blob/ba1ed9f7b26cd6bc20115a9d5350bef4cfbb18bb/pytest/te …
> fix(nayduck) - fix flaky state_sync_routed test

- integration-tests/src/test_loop/tests/resharding_v3.rs
- integration-tests/src/test_loop/utils/resharding.rs
- Rephrased the description of the original double signing fork test `slow_test_resharding_v3_double_sign_resharding_block_last_fork`, to make it clearer and more accurate
- Added another test to check the code path where, in the presence of multiple resharding points (because of forks), the chain ends up 'picking' the first resharding point, ignoring the following ones.
> feat(test): implement missing resharding double signing fork test

- cspell.json
- utils/fmt/src/lib.rs
- utils/near-performance-metrics/src/stats_enabled.rs
- utils/stdx/src/lib.rs
Fix the spellchecker errors in `nearcore/utils`
> spellcheck: utils directory

- chain/jsonrpc-primitives/src/types/chunks.rs
Trivial change to use the correct `ShardId` type
> chore: use correct shard_id type

- core/primitives/src/epoch_info.rs
Cleaning up the unused function `EpochInfo::v1_test`.
> refactoring: remove unused function

- nightly/pytest-sanity.txt
This test is failing with insuficient prepaid gas errors, and it seems to have started failing after the contracts were updated on the nayduck workers: https://nayduck.nearone.org/#/test/414086. This should be investigated, but it shouldn't block PRs for now
> nayduck: ignore slow_chunk.py

- chain/chain/src/chain.rs
- chain/chain/src/runtime/tests.rs
- chain/chain/src/stateless_validation/chunk_endorsement.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/validate.rs
- chain/client/src/client.rs
- chain/client/src/client_actor.rs
- chain/client/src/debug.rs
- chain/client/src/info.rs
- chain/client/src/stateless_validation/validate.rs
- chain/client/src/view_client_actor.rs
- chain/epoch-manager/src/adapter.rs
- chain/epoch-manager/src/lib.rs
- chain/epoch-manager/src/tests/mod.rs
- integration-tests/src/tests/client/challenges.rs
* `get_validator_by_account_id` no longer returns slashing info and `get_fisherman_by_account` is removed
* all functions for signature verification (except `verify_validator_signature`) are moved out of EpochManager as free functions
* bunch of slashing tests are disabled
> refactor: remove slashing info and signature verification from epoch manager

- chain/chain/src/chain.rs
- chain/chain/src/state_snapshot_actor.rs
- chain/client/src/test_utils/test_env_builder.rs
Remove one unnecessary parameter from the function type `MakeSnapshotCallback`.
> refactor: simplify MakeSnapshotCallback

- tracing/Cargo.toml
- tracing/Dockerfile
Building the tracing collector `Dockerfile` failed with:
```console
3.198 error: rustc 1.81.0 is not supported by the following package:
3.198   near-tracing@0.0.0 requires rustc 1.84.0
3.198 
```
Because the dockerfile uses older version than the crate.
Let's bump dockerfile version to match the crate version.
> fix: Update tracing collector image

- chain/chain/src/runtime/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/epoch-manager/src/adapter.rs
- chain/epoch-manager/src/lib.rs
- chain/epoch-manager/src/tests/mod.rs
The PR makes some functions as default implementation in the `EpochManagerAdapter` trait and deletes unused functions like `copy_epoch_info_as_of_block` and `get_all_block_approvers_ordered`
> refactor: move fns as default implementation in EpochManagerAdapter trait

- integration-tests/src/tests/client/block_corruption.rs
This PR makes the test `ultra_slow_test_check_process_flipped_block_fails` more efficient by re-using the same test loop environment, instead of initializing a new `TestEnv` at every iteration.
Locally the test runs 40% faster.
> refactoring: Speed up flipped block test

- chain/chain/src/store/merkle_proof.rs
- chain/chain/src/store/mod.rs
- chain/client/src/sync/epoch.rs
- chain/epoch-manager/src/lib.rs
- core/store/src/adapter/chain_store.rs
- core/store/src/adapter/epoch_store.rs
- core/store/src/adapter/mod.rs
Follow up on all the store adapter work.
In future I'll add update adapter as well
> [store] Introduce Epoch store adapter

- chain/chain/src/approval_verification.rs
- chain/chain/src/chain.rs
- chain/chain/src/doomslug.rs
- chain/chain/src/lightclient.rs
- chain/chain/src/runtime/tests.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/tests/doomslug.rs
- chain/chain/src/tests/garbage_collection.rs
- chain/chunks/src/shards_manager_actor.rs
- chain/chunks/src/test_utils.rs
- chain/client/src/client.rs
- chain/client/src/client_actor.rs
- chain/client/src/debug.rs
- chain/client/src/info.rs
- chain/client/src/view_client_actor.rs
- chain/epoch-manager/src/adapter.rs
- chain/epoch-manager/src/lib.rs
- chain/epoch-manager/src/test_utils.rs
- chain/epoch-manager/src/tests/mod.rs
- genesis-tools/genesis-populate/src/lib.rs
- integration-tests/src/tests/client/features/adversarial_behaviors.rs
- integration-tests/src/tests/client/features/in_memory_tries.rs
- tools/state-viewer/src/commands.rs
- tools/state-viewer/src/state_dump.rs
This PR moves implementation for a bunch of functions from `EpochManager` to be the default implementation in `EpochManagerAdapter` trait.
Also `is_slashed` is removed from the API since we do not properly support slashing.
> refactor: move EpochManager functions as default impl for EpochManagerAdapter

- chain/client/src/sync/epoch.rs
- chain/epoch-manager/src/lib.rs
- core/store/src/adapter/mod.rs
> [cleanup] Rename epoch() to epoch_store() in store adapters

- chain/client/src/client.rs
- integration-tests/src/tests/client/process_blocks.rs
Issue #12564. Epoch sync is restricted to nodes at genesis. At the moment node will not initialize Block Header sync but it can handle BlockHeadersResponse anyway.
The commit provides addtional check on processig BlockHeadersResponse to ensure that receiver node is not at EpochSync state.
> fix(epoch_sync) Prevent Block Header sync during Epoch sync

- tools/mirror/src/cli.rs
The from-rpc help text should explain that the URL should be for a node running on the chain the state was forked from, e.g. mainnet
> nit(mirror): improve show-keys help text

- chain/network/src/raw/connection.rs
- chain/network/src/raw/tests.rs
- tools/mock-node/src/lib.rs
- tools/mock-node/src/main.rs
- tools/mock-node/src/setup.rs
When using mock-node to test older versions of neard, they might not be able to connect to each other if the protocol versions are different. But they probably are actually compatible since the mock-node program is doing nothing but providing serialized blocks and chunks. So just respond with whatever protocol version the client specified in its handshake, and add a --handshake-protocol-version flag to set it explicitly if desired.
> mock-node: use the client's protocol version in the handshake

- benchmarks/synth-bm/justfile
- benchmarks/synth-bm/src/account.rs
- benchmarks/synth-bm/src/contract.rs
- benchmarks/synth-bm/src/native_transfer.rs
Issue [12835](https://github.com/near/nearcore/issues/12835). 
Using "requests-per-second" instead of suggested "transactions_per_second" as this value can be used to limit the rate of the other requests to the network as well (client data sync for example). 
Renamed the corresponding parameter in the `bencmark_mpc_sign` as well.
> replace interval_duration_micros by requests_per_second as an argument to benchmark_native_transfers

- chain/network/src/raw/connection.rs
- tools/mock-node/src/lib.rs
If an error occurs during this part we don't want to exit with an error, since everything is probably fine and we can continue serving requests.
One way for this to happen is a ^C on neard while the handshake is in progress, which of course shouldn't cause us to exit. But a more likely cause of the mock-node program exiting because of an accept() error that actually has happened is that under certain conditions, if the mock node closes the connection, the peer manager might open a TCP connection to it while trying to reconnect but then [close it right after](https://github.com/near/nearcore/blob/f527efeafe915514137099f16db9acef9a172999/chain/network/src/peer_manager/network_state/mod.rs#L479) with `outbound not allowed: already connected to this peer`.
So add a ConnectError::Accept …
> mock-node: don't exit on errors during the handdshake phase

- benchmarks/synth-bm/Cargo.lock
- benchmarks/synth-bm/Cargo.toml
- benchmarks/synth-bm/justfile
- benchmarks/synth-bm/src/account.rs
- benchmarks/synth-bm/src/contract.rs
- benchmarks/synth-bm/src/native_transfer.rs
[issue 12805](https://github.com/near/nearcore/issues/12805)
The flag (default=false) triggers the update of the account nonces from the network before generating the transactions.
impl details:
- extract the `update_account_nonces()` function
- add a corresponding flag to benhmark_native_transfers and benchmark_mpc binaries
+ apply the `update_account_nonces()` depending on the flag value
tested:
- run the benchmark from the clean state
- edit the `a_user_0.test.near.json`, set "nonce" to 7000001
- update the log level to "trace" in the justfile
- re-run the benchmark
- find the `[2025-01-29T13:06:56Z TRACE near_synth_bm::account] updating nonce for a user a_user_0.test.near (7000001->7000020)` in the log
> bench(synth-bench):  Add `read_nonces_from_network` flag to benchmark binaries

- chain/jsonrpc/src/lib.rs
There was a complaint that the `/metrics` endpoint doesn't set `content-type` in the HTTP response.
Let's set it to `text/plain`, as described in the prometheus docs: https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md
Refs: https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/.E2.9C.94.20Reported.20issue.20with.20telemetry.3F
I manually confirmed that the change sets content-type:
```rust
$ curl -vvv 127.0.0.1:3030/metrics 2>&1 | grep -i content
< content-length: 276846
< content-type: text/plain
```
> Set Content-Type: text/plain for /metrics endpoint

- chain/chain/src/chain.rs
The info logs are reserved for rare and important events, processing a chunk does not meet that criteria.
> fix(logs) - Reduce log level for spammy logs

- chain/chain/src/chain.rs
We want the protocol version of the block after the head block, because if we check the current head's protocol version, then we'll take a snapshot the old way when we see the last block in the epoch before we switch to the current epoch state sync. This did not cause any tests to fail because by itself it is not strictly a bug (although suboptimal) since we'll take another snapshot later when we see the new sync hash in the next epoch. But it triggers a long-standing bug when multiple state snapshot requests are made within a short time, where the state snapshot actor might unlock flat storage updates after the first one is created even though there's another one still to go.
> state-snapshot: fix protocol version calculation when creating snapshot

- chain/epoch-manager/src/adapter.rs
The fact that `EpochManagerHandle` is just a wrapper over `Arc<RwLock<EpochManager>>` became a footgun. It is tempting to call its own methods, like we did in `get_epoch_config` and `get_shard_config` for a long time. But this leads to grabbing lock twice in read mode. That's obvious thing to fix but I'll also tell how I discovered it.
We didn't hit it before, as RwLock allows multiple readers. However, the deadlock may occur if we grab write lock exactly between 2 read calls. This is an example from official docs: https://doc.rust-lang.org/std/sync/struct.RwLock.html
When I reduced block time to 0.6s and further, it did happen to me - between subsequent calls inside `get_epoch_config`, `add_validator_proposals` was also called.
> fix: epoch manager deadlock

- chain/chain/src/flat_storage_resharder.rs
- chain/chain/src/state_snapshot_actor.rs
- core/store/src/flat/manager.rs
- core/store/src/flat/storage.rs
- integration-tests/src/test_loop/builder.rs
- nearcore/src/lib.rs
The state snapshot actor's logic does not work if several requests come in quick succession. There are a couple problems that this PR fixes.
One is that we first handle a `DeleteAndMaybeCreateSnapshotRequest` message and delete the state snapshot, and then send a `CreateSnapshotRequest` to `Self` that will be handled later. But this means that if several requests come in a period of time shorter than the amount of time it takes to create the state snapshot, several deletions might all run in a row before the corresponding creations run, and the extra state snapshots will not get cleaned up
The second more important problem is that we call `snapshot_taken()` to allow flat storage updates after the snapshot has been created, but this is done even if there have been other snapshot requests …
> fix(state-snapshots): handle multiple incoming requests correctly

- chain/chain/src/chain.rs
- chain/chain/src/state_sync/adapter.rs
- chain/chain/src/state_sync/mod.rs
- chain/chain/src/state_sync/utils.rs
We decide whether to take a snapshot based on the return value of is_sync_prev_hash(), which looks at the StateSyncNewChunks column to tell whether the given hash will be the prev_hash of the sync_hash. But the current logic assumes that this will be called only before the sync hash is actually found, because we clear that column after it is found since the contents are not needed anymore.
This means that if we processed the sync header during header sync instead of during normal block processing, then is_sync_prev_hash() will not return true when it should. We can fix it by just checking if the sync hash is already set before looking at the values in StateSyncNewChunks.
> fix(state-snapshots): fix skipped state snapshot after header sync

- core/store/src/db/rocksdb.rs
- core/store/src/lib.rs
- core/store/src/opener.rs
- tools/fork-network/src/cli.rs
`fork-network finalize` deletes data in every column except the ones we need to start the network, but it does it with a delete DB transaction. This only logically deletes the values, but does not free up the disk space, which will only happen after a compaction. So here we remove the columns by calling `drop_cf()` on the unnecessary columns, which actually removes the sst files and frees up the space. This will reduce the size of images used for forknet by quite a bit.
> forknet: Drop unneeded columns in the fork-network command

- tools/mirror/src/offline.rs
I recall we discussed some assumption that `initialize_genesis_state` must be called before `ChainStore` is created. This is the case generally but not for the mirror tool.
It fixes the issue of genesis height not set for mirror traffic node launched for the current images.
> fix: set genesis height for mirror

- tools/fork-network/src/delayed_receipts.rs
I forgot to "git add" this when applying suggestions from https://github.com/near/nearcore/pull/12837
> nit(forknet): add comment about delayed receipts

- benchmarks/synth-bm/src/account.rs
- benchmarks/synth-bm/src/rpc.rs
During benchmarking I wanted to spawn txs between different shards, and for that it was convenient to use prefixes in the form `2,c,h,m,x`. Would it make sense in general? I retain `sub_account_prefix` as alias.
Also I had an issue with RPC node crashing: `[2025-02-13T21:19:04Z WARN  near_synth_bm::rpc] RPC call failed: error while sending payload: [error sending request for url (http://34.132.32.11:3030/)]`
However, `response_check_severity` states that we can afford such errors, and it makes sense because they are very rare. So I suggest to use `warn_or_panic` for it as well.
> feat(synth-bm): allow multiple account prefixes

- chain/client/src/info.rs
This was missed previously because the shard id here doesn't need to be converted to ShardId.
> fix(metrics) - fix shard id / shard index mixup

- pytest/lib/key.py
- pytest/tools/mirror/fork_network.py
- pytest/tools/mirror/mirror_utils.py
It's kind of hard to test changes to the fork-network commands at the moment, so this adds at least a quick check that the forked network can start and produce some blocks. It would be good to add a check that we can send mirrored transactions, but that is prob not a huge deal to cover for now.
This also makes a change to `Key.from_keypair()`, because creating a key with `Key.from_random()` and then saving it to a file with `Key.to_json()` does not work because it only writes the bytes of the private key to the "secret_key" field, but neard expects the key to be the private and public keys concatenated. This should be fine to change because `Key.sign_bytes()` does make sure to take the first 32 bytes
> forknet: add test for forknet v2 setup

- tools/fork-network/src/cli.rs
- tools/fork-network/src/delayed_receipts.rs
- tools/fork-network/src/storage_mutator.rs
We'd like to use forknet with more shards than we have currently on mainnet, or just any arbitrary shard layout. But it won't work to just change the shard layout in the genesis file, since we need to rewrite everything in the tries. So this PR implements support for an optional custom shard layout when generating the state.
To do this, we use the existing `StorageMutator` that keeps a list of updates per shard, and we change it to be aware of which shards belong to the source shard layout and which belong to the target. We still have one thread per source shard, but now it writes state to shards that possibly don't exist in the shard layout.
This also requires writing a new bandwidth scheduler state in each target shard that doesn't exist in the source shard layout
> forknet: support arbitrary shard layouts

- benchmarks/transactions-generator/justfile
- benchmarks/transactions-generator/readme.md
- benchmarks/transactions-generator/src/lib.rs
Replaces the tokio::select picking the events from the transaction generation, block hash updates  and reporting sources to all those running in a dedicated tasks to avoid the interference.
> bench-synth: Fix the (mis)usage of tokio::select in transactions generator

- core/parameters/src/config.rs
- core/parameters/src/config_store.rs
`BandwithScheduler` was added quite recently and its config has not yet been unlimited for benchmarknet. Follows the approach to unlimit other configs, e.g. `WitnessConfig`.
> bench: unlimit BandwithSchedulerConfig in BENCHMARKNET

- pytest/tests/mocknet/local_test_node.py
- tools/fork-network/src/cli.rs
https://github.com/near/nearcore/pull/12938 changed the format of the data we write to the `FORK_TOOL` Misc column keys in the `init` command, but didn't keep backward compatibility. But this should have been done because we need to run `fork-network` again when starting a forknet so we can run the `set-validators` and `finalize` commands. So this PR reads the values the old way if there's nothing in the `FORK_TOOL_FLAT_HEAD` key
> fix(forknet): Fix fork-network tool backward compatibility

- core/parameters/src/config.rs
See [this Zulip thread](https://near.zulipchat.com/#narrow/channel/295306-contract-runtime/topic/master.20broken.20for.20me.20if.20the.20chainid.20is.20set.20to.20.22benchmarknet.22) for reference.
> fix: reduce benchmarknet config values

- pytest/tests/mocknet/helpers/neard_runner.py
The hostnames can be quite long, which is inconvenient for creating subaccounts. So here we just take the last unique part of the hostname and use `node-$name.near` as the validator ID
> forknet: reduce validator name length

- integration-tests/src/tests/client/bug_repro.rs
These tests have been causing a bit of a headache, very recently I've hit them being flaky a couple of time. One example is [this](https://github.com/near/nearcore/actions/runs/13521612958/job/37781967085) CI merge queue run.
Ignoring the tests while we figure out a solution.
> [test] Ignore flaky tests causing CI failures

- chain/chain/src/runtime/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/types.rs
- chain/client/src/client.rs
If we pass in the `ShardLayout` to `validate_tx` instead of the `EpochId`, we can simplify what it returns and then remove a panic from `process_tx_internal`.
> refactor: remove a panic in `process_tx_internal` by refactoring `validate_tx`

- core/chain-configs/src/test_genesis.rs
- core/primitives/src/epoch_manager.rs
- test-loop-tests/src/builder.rs
- test-loop-tests/src/tests/global_contracts.rs
This PR introduces alternative way to configure genesis and epoch configs for test loop.
Currently the most common way to do that is `build_genesis_and_epoch_config_store`. I have the following issues with it:
* `GenesisAndEpochConfigParams` forces you to set values for parameters even if you are perfectly happy with `TestEpochConfigBuilder` defaults. This pollutes test setup because it is unclear which parameter values actually matter for the tests.
* Callbacks to customise genesis and epoch config builders results in weird inversion of control. Also it just looks cumbersome for simple test setup.
The alternative way is to derive epoch config builder from genesis state and use it directly.
```
let genesis = TestLoopBuilder::new_genesis_builder()
.validators_spec(validators_spec.clone()) …
```
> test: improve test loop builders

- core/chain-configs/src/test_genesis.rs
- integration-tests/src/tests/features/in_memory_tries.rs
- test-loop-tests/src/tests/bandwidth_scheduler.rs
- test-loop-tests/src/tests/chunk_validator_kickout.rs
- test-loop-tests/src/tests/congestion_control.rs
- test-loop-tests/src/tests/congestion_control_genesis_bootstrap.rs
- test-loop-tests/src/tests/contract_distribution_cross_shard.rs
- test-loop-tests/src/tests/contract_distribution_simple.rs
- test-loop-tests/src/tests/create_delete_account.rs
- test-loop-tests/src/tests/epoch_sync.rs
- test-loop-tests/src/tests/fix_chunk_producer_stake_threshold.rs
- test-loop-tests/src/tests/in_memory_tries.rs
- test-loop-tests/src/tests/malicious_chunk_producer.rs
- test-loop-tests/src/tests/multinode_stateless_validators.rs
- test-loop-tests/src/tests/multinode_test_loop_example.rs
- test-loop-tests/src/tests/optimistic_block.rs
- test-loop-tests/src/tests/syncing.rs
- test-loop-tests/src/tests/view_requests_to_archival_node.rs
- test-loop-tests/src/utils/setups.rs
This PR replaces `build_genesis_and_epoch_config_store` with direct usage of builders introduced in #12995.
> test: remove build_genesis_and_epoch_config_store 

- chain/client/src/client.rs
when forwarding the tx, we can just pull the hash once.  Not sure if the compiler would already optimise this away but doesn't hurt to clean up the code.
> nit: do not keep copying the hash

- chain/chain/src/runtime/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/types.rs
- chain/client/src/client.rs
Depending on the args passed to `validate_tx`, it does two different types of checks.  This PR splits them into separate calls so that the code becomes easier to follow.  This will also introduce the new type: `SignatureVerifiedTransaction` that we are aiming to do.
> refactor: split `validate_tx` into two functions

- pytest/tests/mocknet/helpers/neard_runner.py
- pytest/tests/mocknet/mirror.py
1. Now, if you call init like `mirror init-neard-runner --neard-binary-url $NODE_BINARY_URL --neard-upgrade-binary-url ""`, it won't ask you for upgrade binary url, as it always do.
2. Update config can simply accept many arg changes separated by comma, if you want to update many of them instantly. Calling it multiple times is a waste. 
Example: `mirror update-config --set 'consensus.min_block_production_delay.secs=0,consensus.min_block_production_delay.nanos=600000000,consensus.max_block_production_delay.secs=1,consensus.max_block_production_delay.nanos=800000000,consensus.max_block_wait_delay.secs=6,consensus.max_block_wait_delay.nanos=0`
> chore(mirror): minor user improvements

- core/async/src/test_loop.rs
- core/async/src/test_loop/data.rs
- core/async/src/test_loop/pending_events_sender.rs
- test-loop-tests/src/builder.rs
- test-loop-tests/src/tests/bandwidth_scheduler.rs
- test-loop-tests/src/tests/simple_test_loop_example.rs
- test-loop-tests/src/utils/transactions.rs
Within TestLoop framework, we keep a priority queue of events to be executed. As of today there's no way to distinguish events of one client from another.
This PR introduces a new `identifier` field within the event. This is set to be the string representation of `account_id` of the client.
In the future this would be useful to implement node shutdown and restart functionality within TestLoop where we would potentially be able to filter events based on the identifier.
Couple of other cosmetic changes to test loop.
> [testloop] Introduce identifier in testloop callback event

- chain/network/src/test_loop.rs
- test-loop-tests/src/builder.rs
- test-loop-tests/src/env.rs
Setting up network stack in TestLoop environment is not trivial.
We have a singleton instance of `TestLoopNetworkSharedState` that holds data about the senders for all clients. Additionally, for each client we have a `TestLoopPeerManagerActor` that holds a reference to `TestLoopNetworkSharedState`.
Originally while building the network sender stack in TestLoop, we required to first initialize all senders/actors for all clients before we could go ahead and create `TestLoopNetworkSharedState` and therefore setup network adapter.
This unfortunately creates an issue where we may need to make modifications to the network stack later, example in cases of implementing restarting a node.
This PR changes the design language for setting up network where now it's possible to incrementally add …
> [testloop] Sequentially setup network in TestLoopBuilder

- core/chain-configs/src/test_genesis.rs
- integration-tests/src/tests/features/in_memory_tries.rs
- test-loop-tests/src/tests/chunk_validator_kickout.rs
- test-loop-tests/src/tests/congestion_control.rs
- test-loop-tests/src/tests/congestion_control_genesis_bootstrap.rs
- test-loop-tests/src/tests/contract_distribution_cross_shard.rs
- test-loop-tests/src/tests/contract_distribution_simple.rs
- test-loop-tests/src/tests/epoch_sync.rs
- test-loop-tests/src/tests/multinode_stateless_validators.rs
- test-loop-tests/src/tests/multinode_test_loop_example.rs
- test-loop-tests/src/tests/syncing.rs
- test-loop-tests/src/utils/setups.rs
A followup to [this comment](https://github.com/near/nearcore/pull/13004#discussion_r1972728146).
> refactor: avoid specifying genesis version for TestEpochConfigBuilder::build_store_for_single_version

- benchmarks/synth-bm/src/contract.rs
- benchmarks/synth-bm/src/rpc.rs
Before this change, the synthetic benchmark script exited immediately upon encountering an RPC error. It meant that the nonces tracked in memory did not get written to disk, leading to nonce conflicts when running the script again.
This PR fixes that issue by gracefully handling errors and always updating the nonces on disk.
> benchmark_mpc_sign: write nonces even if some txs error

- chain/chain/src/chain.rs
- chain/client/src/client.rs
- chain/client/src/client_actor.rs
- chain/client/src/metrics.rs
- test-loop-tests/src/tests/optimistic_block.rs
It is incorrect to compare `peer_id.public_key() != validator.public_key()` - it rejects all blocks, in fact. Instead, we just check the signature.
Also, add block height check to prevent overflow.
There is still a potential issue that optimistic block can be received and verified many times, but well, it's malicious block producer behaviour which is unlikely.
> fix: some fixes to check optimistic block

- chain/chain/src/runtime/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/types.rs
- chain/client/src/client.rs
- runtime/runtime-params-estimator/src/estimator_context.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/verifier.rs
This change allows for a number of simplifications.
- `validate_tx_metadata`: does not need to compute the tx cost unnecessarily just to drop it.  It also needs fewer arguments.
- `validate_tx_against_state` does not need to call `validate_transaction` anymore removing duplicate checks and it can just call `tx_cost`.
- `validate_transaction` now always verifies signatures so it needs one fewer argument.
- rename `validate_tx_against_state` to `can_verify_and_charge_tx` to make it clear what the function is actually doing.
- rename `validate_tx_metadata` to just `validate_tx` as that is what this function is now doing.
> refactor: move `tx_cost` out of `validate_transaction`

- Cargo.lock
- tools/state-parts-dump-check/Cargo.toml
- tools/state-parts-dump-check/src/cli.rs
After the current epoch state sync feature is enabled, getting the state roots from the last block of the previous epoch no longer works. So in this PR we find the right sync hash if that protocol feature is enabled by iterating over the chunks in the new epoch until we find the right point.
> fix(state-parts-dump-check): check the right sync hash (#12975)

- Dockerfile
Because of changes in rustup, we need to explicitly specify toolchain version
https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html
> Docker build toolchain version

- Dockerfile
Because of changes in rustup, we need to explicitly specify toolchain version
https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html
> Docker build toolchain version (#13034)

- chain/chain/src/runtime/mod.rs
- runtime/runtime-params-estimator/src/estimator_context.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/verifier.rs
This will make usage of `TrieUpdate` inside `process_tx_internal` non `mut` and then allow us to more easily parallelise.
> make `TrieUpdate` non `mut` in `verify_and_charge_transaction`

- chain/network/src/peer_manager/connection/mod.rs
- chain/network/src/peer_manager/network_state/mod.rs
With release 2.5 we had changed VersionedChunkEndorsement to be allowed on T1. This lead to a compatibility issue with 2.4 nodes, which were expecting VersionedChunkEndorsement to be allowed only on T2.
To fix this problem, with release 2.5 we allow to receive VersionedChunkEndorsement on T1 but send on VersionedChunkEndorsement T2.
With next release 2.6, we can start sending VersionedChunkEndorsement on T1.
Zulip discussion:
https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/2.2E5.2E0.20release.20mainnet.20-.20missing.20chunks/near/503332447
> [network] Send VersionedChunkEndorsement on T2 (#13039)

- benchmarks/synth-bm/src/rpc.rs
The line "received x responses.." is a little spammy for my use case, I propose to change the log level to debug.
> chore: change log level in synth-bm

- core/primitives-core/src/version.rs
- runtime/runtime/src/lib.rs
`check_balance` was converted to a debug assert in PR https://github.com/near/nearcore/pull/12516
Unfortunately, this was a protocol change and meant old and new nodes were not in coordination any more.
This PR puts `check_ balance` behind a protocol feature flag
> [fix] `check_balance` removal under protocol feature flag

- chain/network/src/peer_manager/connection/mod.rs
- chain/network/src/peer_manager/network_state/mod.rs
Reverts near/nearcore#13039
This fix was required for 2.5 release but we do not want to include these changes into 2.6 release
> Revert "[network] Send VersionedChunkEndorsement on T2"

- core/primitives-core/src/version.rs
- runtime/runtime/src/lib.rs
`check_balance` was converted to a debug assert in PR https://github.com/near/nearcore/pull/12516
Unfortunately, this was a protocol change and meant old and new nodes were not in coordination any more.
This PR puts `check_ balance` behind a protocol feature flag
> [fix] `check_balance` removal under protocol feature flag (#13053)

- core/async/src/test_loop.rs
- test-loop-tests/src/env.rs
- test-loop-tests/src/tests/mod.rs
- test-loop-tests/src/tests/restart_node.rs
- tools/debug-ui/src/log_visualizer/LogVisualizer.scss
- tools/debug-ui/src/log_visualizer/LogVisualizer.tsx
- tools/debug-ui/src/log_visualizer/events.ts
This is the first step for adding support to restart nodes in testloop.
Here we begin by providing the support to kill a node.
TestLoop visualizer is updated appropriately to show events to a killed node in red.
Next step would be to add support to start/restart a node
> [testloop] Support to kill a node

- core/primitives/src/lib.rs
Fixes a CI job that runs on master branch only
> chore: fix compilation of fuzz targets

- chain/client/src/stateless_validation/chunk_validator/mod.rs
Add more information to the error message that's printed when chunk validation fails. Will make it easier to pinpoint which chunk producer created the invalid chunk witness.
> Add more info in chunk validation error

- chain/chain/src/chain.rs
- chain/chain/src/metrics.rs
- chain/chain/src/orphan.rs
- chain/client/src/client.rs
- chain/client/src/client_actor.rs
- chain/client/src/metrics.rs
- chain/epoch-manager/src/lib.rs
- chain/epoch-manager/src/validate.rs
I discovered that with small block delays, we often may not even have previous block when we receive OB.
So we need to put OB into the orphan pool until prev block is postprocessed and we can fully process it again.
In such case, we also cannot fully verify OB, so I reuse heuristic from the state witness validation - we check which epoch ids it may correspond to and try to verify signature for each such potential epoch. This limits malicious behaviour to the block producers.
We are in a bit of a rush before 2.6.0, so I've just checked manually that the new code path is indeed used.
I also had to move `maybe_process_optimistic_block` to Chain because orphans are part of Chain.
(1)
(2)
> fix: orphaned optimistic blocks

- chain/chain/src/runtime/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/types.rs
- chain/client/src/client.rs
- chain/indexer/src/streamer/utils.rs
- core/primitives/src/transaction.rs
- runtime/runtime-params-estimator/src/action_costs.rs
- runtime/runtime-params-estimator/src/estimator_context.rs
- runtime/runtime/src/config.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/verifier.rs
This PR introduces the `ValidatedTransaction` type and starts to use it in `process_tx_internal` i.e. when a transaction is received from the rpc nodes.  In order to keep the scope small enough, this PR does not store validated transactions in the tx pool yet so we still have to do validation when we produce chunks.
> Introduce `ValidatedTransaction`

- Cargo.lock
- integration-tests/src/tests/features/chunk_nodes_cache.rs
- nearcore/Cargo.toml
- runtime/near-vm-runner/Cargo.toml
- runtime/near-vm-runner/src/logic/dependencies.rs
- runtime/near-vm-runner/src/logic/gas_counter.rs
- runtime/near-vm-runner/src/logic/logic.rs
- runtime/near-vm-runner/src/logic/mocks/mock_external.rs
- runtime/near-vm-runner/src/logic/mod.rs
- runtime/near-vm-runner/src/logic/tests/storage_read_write.rs
- runtime/near-vm-runner/src/tests/ts_contract.rs
- runtime/runtime-params-estimator/Cargo.toml
- runtime/runtime/Cargo.toml
- runtime/runtime/src/conversions.rs
- runtime/runtime/src/ext.rs
Contract runtime has no business knowing anything about the storage implementation details outside of the specifics around particular gas fees.
This change reflects this reality by moving the concerns about how TTNs are counted into the glue layer that's the implementation of `Externals` in the transaction runtime.
In principle I would say that the transaction runtime has no business knowing much about TTNs and such *either* so I anticipate that e.g. the newly added `dyn AccessTracker` would get passed deeper into the storage calls wherein the TrieAccountingCache would be able to call `trie_node_touched` and similar methods almost on an individual node basis. But this seemed like a lovely intermediate point and a great improvement already.
Part of #13008
> store: move concerns about TTN and storage types outta contract runtime

- runtime/near-vm-runner/Cargo.toml
- runtime/near-vm-runner/src/cache.rs
use of tempfile was a stretch anyway and only really used for generating random file names. Well, now that a new release of tempfile has broken this use-case we'll have to implement this logic ourselves.
> rewrite cache put to not use tempfile

- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
When a node is syncing and receives a partial encoded state witness, `validate_partial_encoded_state_witness` returns `Ok(false)`, which means that the witness is valid, but not relevant for this validator.
Currently when this happens we print a warning saying:
```
Received invalid partial encoded state witness
```
But this not really true, the witness isn't "invalid", it's just "irrelevant", which is normal during sync. The warning also scares node operators, who think that there's something wrong with their node.
Let's downgrade this log message to debug level and only print warnings when the witness is actually invalid, not just irrelevant. Normal node operations, like syncing, shouldn't be producing warnings.
> fix: better log messages for irrelevant partial encoded state witness

- integration-tests/src/env/test_env.rs
- integration-tests/src/env/test_env_builder.rs
- integration-tests/src/tests/client/block_sync.rs
The eventual goal is to try to get rid of mock epoch manager.
Part of https://github.com/near/nearcore/issues/10634
> refactor: stop using mock epoch manager in block_sync tests.

- Cargo.lock
- Cargo.toml
- deny.toml
This updates the versions of `tempfile` and with it `rustix` & `wasmtime` in order to keep crate duplication lower.
Requires #13085
Based on #13085
> chore: update crate versions

- chain/chain/src/chain.rs
- chain/chain/src/runtime/mod.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/types.rs
- runtime/runtime/src/state_viewer/mod.rs
We were cloning then passing around references.
> refactor: reduce cloning when passing RuntimeConfig around

- test-loop-tests/src/setup/builder.rs
- test-loop-tests/src/setup/env.rs
- test-loop-tests/src/tests/restart_node.rs
We need to add `NodeStateBuilder` as now we need the ability to build the node startup state (i.e. mainly client_config) outside of the test_loop_env build function.
See test-loop-tests/src/tests/restart_node.rs for example use.
> [testloop] Add support to add new node

- integration-tests/src/env/test_env_builder.rs
- integration-tests/src/tests/client/process_blocks2.rs
Part of #10634
I have also removed num_shards from test env builder, since it's no longer used. (Note also that it's only usage is with mock epoch manager.)
> refactor: remove mock epoch manager usage from process_blocks2.

- chain/chain/src/garbage_collection.rs
This PR makes deduplicates common logic for each gc mode and makes block hash reassignment to previous block hash easier to spot in case of canonical gc mode.
> refactor: in gc clear_block_data improve TrieChanges gc.

- chain/chain/src/runtime/tests.rs
- chain/chain/src/stateless_validation/chunk_validation.rs
- chain/client/src/stateless_validation/shadow_validate.rs
- chain/pool/src/lib.rs
Helps address this issue: https://github.com/near/nearcore/pull/13075#discussion_r1991405889.
> refactor: expose an internal cloning to the callers

- chain/chunks/src/logic.rs
`StoreUpdate` allows us to query the state of the `ChainStore` so we can remove all the pre checks.
> refactor: simplify logic in `persist_chunk`

- Cargo.lock
This is mostly for testing changes in our merge queue.
> chore: update openssl in the root repostory

- core/primitives-core/src/version.rs
- core/primitives/src/version.rs
- neard/src/main.rs
Confirmed that the protocol version in mainnet genesis is 29.
> [protocol] Introduce MIN_SUPPORTED_PROTOCOL_VERSION

- chain/chain/src/runtime/mod.rs
With epoch and state sync implemented, gc is spamming logs when nodes are just bootstrapped.
Fixing by implementing a 10 seconds throttle for get_gc_stop_height logs.
```
$ journalctl -fu neard  |grep Error
Mar 16 01:24:35 neard[586239]: 2025-03-16T01:24:35.232735Z  INFO runtime: Error when getting the gc stop height. This error may naturally occur after the gc_num_epochs_to_keep config is increased. It should disappear as soon as the node builds up all epochs it wants. Error: DB Not Found Error: epoch block: BDbsSDd7aP5qbrFubk4kM57xpn8zWa1X9MWvyJ1DkK75
Mar 16 01:24:45 neard[586239]: 2025-03-16T01:24:45.135321Z  INFO runtime: Error when getting the gc stop height. This error may naturally occur after the gc_num_epochs_to_keep config is increased. It should disappear as soon as the node …
```
> Chore: throttle gc error logs

- pytest/tests/mocknet/helpers/neard_runner.py
I realised that `,` doesn't work if we ever want to set value to a list, say, `[0, 1]`. Sorry. `;` shouldn't have collisions.
> nit: use semicolon in do_update_config 

- test-loop-tests/src/examples/missing_chunk.rs
- test-loop-tests/src/examples/mod.rs
- test-loop-tests/src/tests/contract_distribution_cross_shard.rs
- test-loop-tests/src/tests/contract_distribution_simple.rs
- test-loop-tests/src/utils/mod.rs
This PR adds a test loop example test for triggering missing chunk at a certain height using adversarial behaviour.
It also includes a bit of refactoring around common utils.
> test: add test loop example for triggering missing chunk

- test-loop-tests/src/examples/missing_chunk.rs
- test-loop-tests/src/examples/mod.rs
- test-loop-tests/src/utils/mod.rs
With #13161 test-loop-tests build fails when `test_features` is not enabled:
```
% cargo test -p test-loop-tests -- global_contracts
error[E0432]: unresolved import `near_client::NetworkAdversarialMessage`
--> test-loop-tests/src/examples/missing_chunk.rs:4:5
|
4  | use near_client::NetworkAdversarialMessage;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `NetworkAdversarialMessage` in the root
|
```
> test: fix test loop missing chunk example compilation

- chain/chain/src/chain.rs
- chain/chain/src/genesis.rs
- chain/chain/src/types.rs
- chain/client/src/sync/epoch.rs
- chain/network/src/network_protocol/testonly.rs
- core/primitives/benches/serialization.rs
- core/primitives/src/block_header.rs
- core/primitives/src/epoch_sync.rs
- core/primitives/src/genesis/block.rs
- core/primitives/src/version.rs
- genesis-tools/genesis-populate/src/lib.rs
Along with genesis, epoch_sync also relies on old protocol version to generate the proof chain. In particular, we changed the way we calculate next block producer hash based on BLOCK_HEADER_V3_PROTOCOL_VERSION.
Specifically, `use_versioned_bp_hash_format`, is set as `ProtocolFeature::BlockHeaderV3.enabled(protocol_version)`
This PR isolates the code to use versioned bp_hash for epoch sync and prod genesis.
> [limited replayability] Isolate bp_hash computation for genesis & epoch_sync

- chain/chain/src/runtime/mod.rs
- chain/indexer/src/streamer/utils.rs
- runtime/runtime-params-estimator/src/estimator_context.rs
- runtime/runtime/src/config.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/verifier.rs
This code caused the indexer to crash on forknet:
```rust
let signer = InMemorySigner::test_signer(&indexer_tx.transaction.signer_id);
let signed_tx = tx.sign(&signer);
let validated_tx = ValidatedTransaction::new(runtime_config, signed_tx).unwrap();
```
The transaction is signed using a dummy signer, but then in `ValidatedTransaction::new` the signature is verified against the real public key from the transaction, which fails and the `unwrap()` panics, which crashes the indexer.
To fix the problem I made `tx_cost` take a normal `Transaction` and pass the `tx` there without having to create a `ValidatedTransaction`.
> fix(indexer): Don't create ValidatedTransaction in indexer

- pytest/tests/mocknet/mirror.py
This tool can be used with older binaries that are not aware fo the new config values.
> fix(forknet): use old snapshot config values for backward compatibility

- core/primitives/src/optimistic_block.rs
- test-loop-tests/src/setup/env.rs
- test-loop-tests/src/tests/optimistic_block.rs
Test that optimistic block production is not disrupted by block miss.
Test that optimistic chunk aplication outcome is discarded if block is built with different data than what was included in the OB.
> test(optimistic block): tests

- Cargo.lock
(Reality show narrator voice) Previously on enum-map:
test   %rdi,%rdi
je     0x38011ee
cmp    $0x1,%rdi
jne    0x38011f1
mov    $0x1,%al
ret
xor    %eax,%eax
ret
mov    $0x2,%al
cmp    $0x3,%rdi
jb     0x3801415
mov    $0x3,%al
je     0x3801415
mov    $0x4,%al
cmp    $0x5,%rdi
jb     0x3801415
mov    $0x5,%al
je     0x3801415
mov    $0x6,%al
cmp    $0x7,%rdi
jb     0x3801415
mov    $0x7,%al
je     0x3801415
<narration continues on for ~30 minutes of airtime>
(Reality show narrator voice) Next up:
cmp    $0x54,%rdi
ja     0x31db9d9
mov    %edi,%eax
ret
sub    $0x38,%rsp
lea    0x1d121a4(%rip),%rax
mov    %rax,0x8(%rsp)
movq   $0x1,0x10(%rsp)
movq   $0x8,0x18(%rsp)
xorps  %xmm0,%xmm0
movups %xmm0,0x20(%rsp)
lea    0x1d1218e(%rip),%rsi
lea    0x8(%rsp),%rdi
call   *0x1e8db0b(%rip)
---
This …
> perf: update enum-map for perf gains

- Justfile
I recall we fixed some issues with integration tests and they work on macs as well.
I just want to run `just nextest-all nightly --color=always` and have all integration tests launched as well. Locally it worked for me, except like `ultra_slow_test_cross_shard_tx_8_iterations` which are disabled anyway. We don't have macos in CI anymore, so there is no impact on others, right?
> chore: reenable integration tests on macos

- benchmarks/sharded-bm/README.md
- benchmarks/sharded-bm/bench.sh
Very small change to add a `mirror` command to the bench script, that just calls `mirror.py` on the forknet cluster in use.
> benchmark: add shortcut to mirror.py

- chain/jsonrpc-primitives/src/types/entity_debug.rs
- nearcore/src/entity_debug.rs
- tools/debug-ui/src/entity_debug/fields.tsx
- tools/debug-ui/src/entity_debug/types.tsx
Add the ability to fetch `EpochConfig` by `EpochId` in debug ui.
It's hard to get this information from some other source, so it'd be useful to have it in entity debug.
Tested on my mainnet node, seems to be working fine:
> Add EpochConfigByEpochId to entity debug

- .github/workflows/benchmarks.yml
Changing ubuntu version as we need jq 1.7.1 and ubuntu 22 comes with 1.6.2
https://packages.ubuntu.com/search?keywords=jq
> Chore: Benchmark workflow fix

- chain/chain/src/runtime/tests.rs
- chain/epoch-manager/src/lib.rs
- chain/epoch-manager/src/shard_tracker.rs
- chain/epoch-manager/src/test_utils.rs
- chain/epoch-manager/src/tests/mod.rs
- core/primitives/src/epoch_manager.rs
- core/primitives/src/shard_layout.rs
- tools/database/src/analyze_contract_sizes.rs
- tools/database/src/analyze_delayed_receipt.rs
- tools/database/src/analyze_gas_usage.rs
- tools/state-viewer/src/commands.rs
- tools/state-viewer/src/trie_iteration_benchmark.rs
Follow up on issue #11265 
We've had both epoch config in files and epoch config generated. At this point it seems like it's fine to stabilize reading config from config files.
Simplify the AllEpochConfig and EpochManager constructors and remove some tests that were too specific to be useful.
> [epoch config] Make config files source of truth

- core/store/src/lib.rs
- core/store/src/opener.rs
- tools/database/src/commands.rs
- tools/database/src/lib.rs
- tools/database/src/rollback_to_25.rs
Add a command which allows to roll back the database from version 44 (used by 2.6) to version 43 (used by 2.5).
This will allows node operators to roll back their nodes from 2.6 to 2.5 in case something is wrong with 2.6.
We already have `database drop-column` and `database set-version`, and the hope was that these could be used to perform the roll back by first removing the column and the setting the version, but sadly it doesn't work.
`set-version` recreates the `ChunkApplyStats` column, and `drop-column` doesn't work with db version 43, so we can't use both of them in any order.
This command is also safer than the previous to, it's almost impossible to break a node with it.
Running it on database with version 44 will correctly roll it back to 43.
Running it on database with version 43 …
> Add database rollback-to25 command

- chain/chain/src/chain_update.rs
- chain/chain/src/runtime/mod.rs
- chain/chain/src/runtime/tests.rs
- chain/chain/src/test_utils/kv_runtime.rs
- chain/chain/src/types.rs
- chain/chain/src/update_shard.rs
- integration-tests/src/user/runtime_user.rs
- runtime/runtime-params-estimator/src/estimator_context.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/prefetch.rs
- runtime/runtime/src/tests/apply.rs
- runtime/runtime/src/types.rs
- runtime/runtime/tests/runtime_group_tools/mod.rs
- tools/state-viewer/src/apply_chain_range.rs
- tools/state-viewer/src/apply_chunk.rs
- tools/state-viewer/src/commands.rs
Part of https://github.com/near/nearcore/issues/13140. 
Similar to https://github.com/near/nearcore/pull/13122 which can be closed in favour of landing this.
- `SignedValidPeriodTransactions` take ownership of `SignedTransactions`
- Rework `ApplyProcessingReceiptState` and `ApplyProcessingState` to not store `SignedValidPeriodTransactions`
- This allows us from avoiding a clone in `process_transactions`.  We need to do a clone in `set_state_finalize` instead now.  However that is not part of chunk application but instead part of state sync.  And still, in this case we are not introducing a new clone just moving it to the top of the stack.
CC: @miloserdow.  As discussed in our chat, this should help with your PR and hopefully we will not have any clones in your work.
> refactor: remove a clone for `SignedTransactions`

- chain/chunks/src/shards_manager_actor.rs
- chain/chunks/src/test_utils.rs
- chain/client/src/chunk_producer.rs
- chain/client/src/test_utils.rs
- chain/network/src/network_protocol/testonly.rs
- core/primitives/src/genesis/chunk.rs
- core/primitives/src/reed_solomon.rs
- core/primitives/src/sharding.rs
- core/store/benches/finalize_bench.rs
- It doesn't need to return a `Result`
- It can call encoding with a reference to the data
These changes will help in a future PR where I hope to be able to remove the cloning of receipts.
Part of https://github.com/near/nearcore/issues/13140
> refactor: cleanups around `EncodedShardChunk::new()`

- chain/chain/src/chain.rs
- chain/chain/src/garbage_collection.rs
- chain/chain/src/state_sync/utils.rs
- chain/client/src/client_actor.rs
- chain/client/src/sync/handler.rs
- chain/epoch-manager/src/shard_tracker.rs
- core/primitives-core/src/version.rs
- core/primitives/src/block.rs
- core/primitives/src/sharding.rs
- integration-tests/src/tests/client/process_blocks.rs
- integration-tests/src/tests/client/sync_state_nodes.rs
- test-loop-tests/src/tests/state_sync.rs
- tools/state-parts-dump-check/src/cli.rs
This PR addresses issues related to the `CurrentEpochStateSync` change. Several functions are updated to correctly handle these scenarios:
-  Heights of blocks leading up to the sync hash block may not be contiguous due to missing blocks.
- The last final block before the sync block might not be present in storage after state sync (and may even belong to the previous epoch).
Test loop state sync tests are expanded to cover:
- Starting a new node from genesis state and having it state sync to nodes far ahead.
- Cases with missing chunks in the blocks leading up to the sync hash block.
Old code gated by `!ProtocolFeature::CurrentEpochStateSync.enabled(protocol_version)` is removed.
Apart from adding tests, I checked all references to last final block (`git grep last_final_block`) to catch …
> state sync: correctly handle missing blocks

- chain/epoch-manager/src/adapter.rs
- chain/epoch-manager/src/genesis.rs
- chain/epoch-manager/src/lib.rs
- chain/epoch-manager/src/reward_calculator.rs
- chain/epoch-manager/src/test_utils.rs
- chain/epoch-manager/src/tests/mod.rs
In EpochManager initialization, we had a code path setting up the genesis EpochInfo that relied on the genesis protocol version.
In this PR, we separate out the initialization of genesis EpochInfo for mainnet/testnet from the rest of the codebase making it easier to remove old code.
This is similar to what we did in #13158
> [limited replayability] Isolate genesis epoch config initialization code

- benchmarks/sharded-bm/bench.sh
After this PR it should be possible to use a `near-synth-bm` executable with a different name.
Tested by exporting `SYNTH_BM_BIN=<some path>/synth-bm`  before running the benchmark.
> benchmark: remove hardcoded usage of near-synth-bm

- benchmarks/sharded-bm/bench.sh
Fix genesis timestamp to a known value to avoid invalidating genesis when tweaking the nodes configuration.
> benchmark: fix genesis timestamp

- chain/epoch-manager/src/lib.rs
- core/primitives/src/test_utils.rs
- core/primitives/src/types.rs
- runtime/runtime/src/actions.rs
- runtime/runtime/src/ext.rs
- runtime/runtime/src/state_viewer/mod.rs
Part of https://github.com/near/nearcore/issues/13231.  I am intentionally creating a small PR here as I am experiencing some test failures with larger scopes and using smaller PRs to isolate the test failures.
> cleanup: no need to look up `BlockInfo::slashed()`

- Cargo.lock
- Cargo.toml
- core/primitives/src/version.rs
Prepare 2.6.0-rc.1 release
* Set neard version to `2.6.0-rc.1`
* Set crates version to `0.30.0`
* Set voting date to Monday 2025-04-14 19:00 UTC - protocol upgrade will happen 12-24 hours later, on 2025-04-15 between 7:00 and 19:00 UTC.
According to our estimation tool the upgrade will happen at 2025-04-15 10:48:15 UTC
```
$ python3 estimate_epoch_start_time.py --chain_id testnet --num_future_epochs 30 --voting_date "2025-04-14 19:00:00"
Epoch -1: 11 hours, 38 minutes
Epoch -2: 11 hours, 40 minutes
Epoch -3: 11 hours, 41 minutes
Epoch -4: 12 hours, 14 minutes
Exponential weighted average epoch length: 11 hours, 47 minutes
Predicted start of epoch 1: 2025-04-03 15:46:07 UTC+0000 Thursday
Predicted start of epoch 2: 2025-04-04 03:33:42 UTC+0000 Friday
Predicted start of epoch 3: 2025-04-04 …
```
> Prepare 2.6.0-rc.1

- test-loop-tests/src/tests/create_delete_account.rs
The small epoch lengh leads to some flaky behavior with `do_create_account` leading to unrelated failures. Those include producing one block with missing chunks due to `ChunkHeaderReadyForInclusion` never called for that particular block in the https://github.com/near/nearcore/pull/13259 . It has been verified that the stress tested network does not produce more blocks with missing chunks if the above PR is included. Together with the failures being only observable with only small epoch lengths (5,6) and for only a single block we have a strong evidence the failure is a noise. Increasing the epoch length for the tests makes the test stable against the changes.
> increase the epoch-length in create-delete-account test

- integration-tests/src/env/test_env.rs
- integration-tests/src/tests/client/chunks_management.rs
- integration-tests/src/tests/client/process_blocks.rs
- integration-tests/src/tests/client/process_blocks2.rs
Part of #10634
Changing runtime of the test to the real runtime made it pass. This was the last use site of TestEnv::default_builder so I renamed default_builder_with_genesis to be the new default_builder.
default_builder_with_genesis would always work and make sure that the real epoch manager and runtime are used.
> test: unignore test_request_chunk_restart

- chain/chunks/src/shards_manager_actor.rs
- chain/client/src/chunk_producer.rs
- chain/client/src/test_utils.rs
- core/primitives/src/sharding.rs
- core/store/benches/finalize_bench.rs
- integration-tests/src/tests/client/invalid_txs.rs
- integration-tests/src/tests/features/access_key_nonce_for_implicit_accounts.rs
`TransactionReceipt` only ever stores `ValidatedTransactions`.  This PR updates one call paths to pass in validated txs instead of signed txs.  
Ultimately, if we can refactor the other call site to use validated txs as well, then it will become quite straightforward for a chunk producer to skip a number of duplicate steps when it later applies the chunk.
Part of: https://github.com/near/nearcore/issues/13140
> refactor: one step closer to storing `ValidatedTransactions` in `TransactionReceipt` 

- chain/chain/src/runtime/mod.rs
- core/store/src/trie/shard_tries.rs
- core/store/src/trie/state_snapshot.rs
We identified a race condition in state sync part generation. Node would start processing a state part request without holding the snapshot lock. To allow the state part to finish, we will hold the lock while the state part is generated.
> fix(state_sync): make sure that snapshot is not used when deleted

- chain/chunks/src/logic.rs
- chain/chunks/src/shards_manager_actor.rs
- chain/client/src/test_utils.rs
- core/primitives/src/genesis/chunk.rs
- core/primitives/src/sharding.rs
- integration-tests/src/tests/client/benchmarks.rs
- `decode_chunk()` doesn't need to know how many data parts.
- reorganise the code a bit in `decode_encoded_chunk` to make it more straightforward to understand.
Helps with https://github.com/near/nearcore/issues/13140
> refactor: improvements to `decode_encoded_chunk`

- benchmarks/sharded-bm/cases/base_config_patch.json
- benchmarks/sharded-bm/cases/forknet/realistic_20_cp_1_rpc_20_shard/config_patch.json
- benchmarks/sharded-bm/cases/forknet/realistic_20_cp_1_rpc_20_shard/epoch_configs/template.json
- benchmarks/sharded-bm/cases/forknet/realistic_20_cp_1_rpc_20_shard/params.json
Updating the realistic scenario with current top TPS
Also setting `max_block_production_delay` and `max_block_wait_delay` to 30s because they make analyzing results easier (IMO). In this way, I can increase TPS gradually, and stop once average block time increases significantly.
> chore: update realistic 20 shard benchmark config

- chain/chunks/src/logic.rs
- chain/chunks/src/shards_manager_actor.rs
- tools/replay-archive/src/cli.rs
Moves some clones happening inside functions to the callers and manages to eliminate some clones.
> refactor: eliminate some more unnecessary cloning

- chain/chain/src/store/mod.rs
- chain/chunks/src/logic.rs
- chain/chunks/src/shards_manager_actor.rs
- chain/client/src/chunk_distribution_network.rs
- chain/client/src/client.rs
Puts `PartialEncodedChunk` in an `Arc` earlier and allows us to save a couple of `clone`s.
> refactor: By creating an `Arc` earlier, save some `clone`ing

- chain/client/src/chunk_producer.rs
- chain/client/src/client.rs
- chain/client/src/test_utils.rs
- core/primitives/src/sharding.rs
- integration-tests/src/tests/client/benchmarks.rs
- integration-tests/src/tests/client/invalid_txs.rs
- integration-tests/src/tests/client/process_blocks.rs
- integration-tests/src/tests/features/access_key_nonce_for_implicit_accounts.rs
- integration-tests/src/utils/process_blocks.rs
Completely non-functional changes.  Just reorganising code a bit.
- `EncodedShardChunk::new` is tidied up a bit
- `ProduceChunkResult::chunk` is renamed to `ProduceChunk::Result::encoded_chunk` to better suit the type
I needed these changes to prevent another PR from blowing up in complexity.
> refactor: reorganise code a bit

- benchmarks/sharded-bm/bench.sh
Fixes a few issues when tracing node is not present:
- neard not able to start
- log spam about missing tracing endpoint
> fix: correctly disable tracing if not needed

- core/primitives/src/upgrade_schedule.rs
- core/primitives/src/version.rs
- test-loop-tests/src/utils/setups.rs
This PR introduces a new field for `NEAR_TESTS_PROTOCOL_UPGRADE_OVERRIDE`.
`one_by_one` will set the voting schedule for all protocol versions in the past
to avoid upgrading multiple versions at the same time.
Tested with `cargo test --package near-primitives --lib upgrade_schedule::tests -- --show-output --test-threads=1` to avoid interference from `test_env_override`.
> feat(voting): one_by_one upgrade for protocol upgrade schedule override

- test-loop-tests/src/tests/chunks_management.rs
These tests run for more than 5 seconds and sometimes for more than 15 seconds.
> test: fix slow test prefixes in chunks_management.

- tools/debug-ui/package-lock.json
- tools/debug-ui/package.json
- tools/debug-ui/src/EpochValidatorsView.scss
- tools/debug-ui/src/EpochValidatorsView.tsx
for every chunk producers, new shards will be highlighted in red.
> feat(debug-ui): make shard transitions visible

- chain/chunks/src/shards_manager_actor.rs
The `ProcessPartialEncodedChunk` was returning OK while dropping the chunk in case there was not enough information to validate it.
This lead to some test-loop tests being prone to have missing chunks and failing with low probability or for unrelated changes.
In particular this fixes the slow tests for the https://github.com/near/nearcore/pull/13259.
The condition for this failure to occur seem also relevant for the prod.
[failing logs](https://drive.google.com/file/d/1Qs22FmLl4joeLQM5xd5aXsxGfKSPIlvo)
```
2.642s  INFO test: Observed new block at height 10021, chunk_mask: [true, true, false, true]
...
thread 'tests::protocol_upgrade::slow_test_protocol_upgrade_not_latest' panicked at test-loop-tests/src/tests/protocol_upgrade.rs:194:5:
assertion `left == right` failed
left: {0: [10021]} …
```
> fix chunk being dropped if the previous block is not ready

- benchmarks/sharded-bm/bench.sh
The bench.sh script contains uppercase "MIRROR.py", but the actual file is "mirror.py" (lowercase).
I think this works on Mac, but it doesn't work on Linux where it complains that it can't find the MIRROR.py file.
Let's make it lowercase to fix the script on Linux.
> fix(bench.sh): use lowercase mirror.py

- chain/jsonrpc/client/src/lib.rs
- integration-tests/src/user/rpc_user.rs
The RPC user used in our integration test used the (deprecated) broadcast_tx_commit method, plus a manual wait-another-block loop to ensure the transaction is actually committed.
This works most of the time but not always. Specifically, I ran into issues while removing refund receipts in #13370. This means that sometimes we see the last receipt but it has not been applied yet.
Using the newer replacement "send_tx" lets us specify to wait for finality, solving the problem cleanly.
Docs on deprecated method:
https://docs.near.org/api/rpc/transactions#send-transaction-await
Docs on new method:
https://docs.near.org/api/rpc/transactions#send-tx
> fix(rpc_user): wait for finality in commit_transaction

- chain/chain/src/runtime/mod.rs
- chain/indexer/src/streamer/mod.rs
- chain/indexer/src/streamer/utils.rs
- core/parameters/res/runtime_configs/149.yaml
- core/parameters/src/config_store.rs
- core/parameters/src/snapshots/near_parameters__config_store__tests__149.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_149.json.snap
- core/primitives-core/src/version.rs
- integration-tests/src/node/runtime_node.rs
- integration-tests/src/tests/nearcore/rpc_nodes.rs
- integration-tests/src/tests/runtime/deployment.rs
- integration-tests/src/tests/runtime/sanity_checks.rs
- integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
- integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status_nightly.snap
- integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status_nondeterministic_nightly.snap
- integration-tests/src/tests/runtime/test_evil_contracts.rs
- integration-tests/src/tests/runtime/test_yield_resume.rs
- integration-tests/src/tests/standard_cases/mod.rs
- integration-tests/src/user/runtime_user.rs
- pytest/tests/sanity/meta_tx.py
- pytest/tests/sanity/rosetta.py
- runtime/runtime-params-estimator/src/estimator_context.rs
- runtime/runtime/src/config.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/verifier.rs
- runtime/runtime/tests/test_async_calls.rs
With `ProtocolFeature::ReducedGasRefunds` enabled, we remove the pessimistic gas price increase. This PR makes this change for nightly only.
This is the first part for NEP-536, which aims to reduce the number of gas refund receipts that are generated in the system. Pessimistic gas pricing is one major cause for such refunds, as it forces all non-local receipts to pay more gas than it likely needs.
There is already a number of integration tests that had to be updated, since the number of receipts has changed. (The refunding receipts is missing with the feature enabled.) This should be enough to test the basic functionality.
The other features for NEP-536, which adds a fee for all remaining gas refunds, will require new integration tests which will also indirectly test that pessimistic gas …
> feat: remove pessimistic gas pricing

- chain/chain/src/chain.rs
- chain/chain/src/missing_chunks.rs
These two optimistic block logs are spamming output. Let's reduce their log-level to debug.
refs: [zulip](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/2.2E6.2E0-rc.2E2/near/513021767)
> fix(optimistic-block) - reduce log level to debug to reduce spam

- Cargo.lock
- Cargo.toml
- chain/chain/src/chain.rs
- chain/chain/src/garbage_collection.rs
- chain/chain/src/missing_chunks.rs
- chain/chain/src/runtime/mod.rs
- chain/chain/src/state_sync/utils.rs
- chain/client/src/client_actor.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
- chain/client/src/sync/handler.rs
- chain/epoch-manager/src/shard_tracker.rs
- chain/indexer/src/streamer/fetchers.rs
- chain/indexer/src/streamer/mod.rs
- core/primitives-core/src/version.rs
- core/primitives/src/block.rs
- core/primitives/src/sharding.rs
- core/store/src/trie/shard_tries.rs
- core/store/src/trie/state_snapshot.rs
- core/store/src/trie/update.rs
- integration-tests/src/tests/client/process_blocks.rs
- integration-tests/src/tests/client/sync_state_nodes.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/state_viewer/mod.rs
- test-loop-tests/src/tests/global_contracts.rs
- test-loop-tests/src/tests/state_sync.rs
- tools/state-parts-dump-check/src/cli.rs
Changes needed for the 2.6.0-rc.2 release. Includes cherry-picks discussed on zulip and removal of some spammy logs.
* af300c15acc779c6dd1cb58d983ac2dc9d74ddd1 is cherry-picked from https://github.com/near/nearcore/pull/13410, I couldn't directly cherry-pick #13258 because of merge conflicts.
* 93ec1c6f5d303f0d5449c4519c976b648bbec5a2 is cherry-picked from https://github.com/near/nearcore/pull/13411
> Prepare 2.6.0-rc.2 release

- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
Healthy nodes often emit the `Evicted unprocessed partial state witness` warning, which confuses node operators who think that there's something wrong with their node. AFAIU this happens when the node is syncing and it doesn't have the latest blocks to validate the witness.
Let's reduce the log-level to DEBUG to reduce spam and confusion.
Refs:
https://t.me/near_validators/18753
https://t.me/near_validators/18782
[#nearone/private > 2.6.0-rc.2 @ 💬](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/2.2E6.2E0-rc.2E2/near/513021767)
> fix(partial_witness): lower log-level to debug to reduce spam

- runtime/runtime/src/lib.rs
likely leftover from older code.
> tidy(runtime): remove unused var timeout_receipts

- tools/debug-ui/src/LatestBlocksView.tsx
Disclaimer: I have absolutely zero knowledge about typescript. 
Fixing the bad ui for showing shard ids in debug ui. 
Before:
After:
Resharding:
> fix(debug_ui) - fix shard id in latest blocks

- benchmarks/sharded-bm/bench.sh
I didn't notice it in #13384, because I didn't wipe my "localnet" folder. Forknet boot nodes are set by mirror and neard-runner, so we should remove the localnet way to setup it.
> fix(sharded-bm): remove getting boot nodes

- chain/client/src/view_client_actor.rs
- core/primitives/src/state_sync.rs
- core/store/src/trie/state_snapshot.rs
- integration-tests/src/tests/client/sync_state_nodes.rs
`can_generate` is not used in the current implementation. This PR removes the overhead of filling that field.
> fix(state_sync): deprecate unused can_generate field from state sync

- benchmarks/sharded-bm/README.md
Adding a brief section with recommended steps to measure max TPS in a sharded benchmark on forknet.
> docs: add simple instructions about how to measure max TPS

- pytest/tests/mocknet/helpers/neard_runner.py
Because neard < 2.7.0 won't know about the state source.
> fix(forknet): backwards compatibility with neard < 2.7.0

- runtime/runtime/tests/runtime_group_tools/mod.rs
- runtime/runtime/tests/test_async_calls.rs
With slice destructuring, this macro used inside the `assert_receipts!` macro is no longer needed.
Removing it makes it much easier to adapt tests to have a different refund receipts count based on version, which is necessary to implement NEP-536.
> test refactor: remove tuplet! macro

- .github/workflows/ci.yml
CodeCov UI at complains that uploads are invalid due to multiple flags being specified for each upload. As seen e.g. in
https://app.codecov.io/gh/near/nearcore/commit/3d620e7cc9b6be1d1a225d55ec643b8339e1bc34
There's also some documentation on this here:
https://docs.codecov.com/docs/flags#one-to-one-relationship-of-flags-to-uploads
Address this by always specifying one flag for each of the uploads only...
> codecov: fix flags

- .github/workflows/ci.yml
Unfortunately codecov appears to be relying on master coverage to be uploaded for each commit to correctly track the coverage of the base branch. It can't reuse coverage results from PR runs because we use squash merges and those change the commit hashes, so there is never a match.
Fixes master ci failures introduced in #13430
> ci: restore uploading coverage for master branch

- chain/chunks/src/shards_manager_actor.rs
When a node transitions from CV -> CP for a shard, it starts to track the shard in the epoch before it becomes a chunk producer. When tracking the shard, it needs to receive the chunks for the shard as well as outgoing receipt proofs from other shards.
If they are not distributed eagerly the node will have to use the ChunkRequest/ChunkResponse pattern and incur significant additional latency during block processing. This in turn delays endorsement of chunks for the following block, causing the node's performance as a chunk validator to suffer.
> distribute receipts and chunks to BPs of the next epoch

- Cargo.lock
- Cargo.toml
The new version in particular removes depending on `rc` in `borsh`.
> update `near-account-id` dependency

- chain/chain/src/stateless_validation/metrics.rs
- core/primitives/src/utils/compression.rs
- integration-tests/src/env/test_env.rs
- integration-tests/src/tests/features/orphan_chunk_state_witness.rs
- integration-tests/src/tests/features/stateless_validation.rs
- runtime/runtime/src/verifier.rs
This PR replaces usage of `borsh::to_vec` with `borsh::object_length` to determine the size of serialized data. This is much faster as it avoid memory allocation.
> fix: use borsh `object_length` instead of `to_vec(..).len()`

- runtime/runtime/src/lib.rs
- runtime/runtime/src/types.rs
This reverts commit 10f236066f276475143b5174e06eedcb673d6c49.
The reason is that #13369 has a negative impact on multi-node network performance, reducing maximum TPS by 10-15%
> Revert "runtime: parallel transaction processing (#13369)"

- chain/chain/src/chain.rs
- chain/chain/src/garbage_collection.rs
- chain/chain/src/store/mod.rs
- chain/chunks/src/logic.rs
- core/store/src/adapter/chain_store.rs
- core/store/src/adapter/chunk_store.rs
- integration-tests/src/tests/client/invalid_txs.rs
- integration-tests/src/tests/features/access_key_nonce_for_implicit_accounts.rs
- integration-tests/src/tests/features/congestion_control.rs
- tools/replay-archive/src/cli.rs
- tools/state-viewer/src/commands.rs
- tools/state-viewer/src/tx_dump.rs
We have many different functions called `get_chunk`.  Most of them are looking up the chunk from the DB so do not need to unnecessarily wrap the returned chunk inside an `Arc`.  This PR tidies this up.  The benefit of not unwrapping a struct in Arc is that it makes it possible to consume it without having to actually copy the data out of it.
> refactor: remove unnecessary `Arc` in various `get_chunk` 

- chain/client/src/chunk_inclusion_tracker.rs
- chain/client/src/client.rs
- chain/client/src/client_actor.rs
- chain/client/src/rpc_handler.rs
- chain/client/src/stateless_validation/chunk_endorsement.rs
- chain/client/src/stateless_validation/state_witness_producer.rs
- core/chain-configs/src/client_config.rs
- integration-tests/src/env/test_env.rs
- integration-tests/src/tests/client/process_blocks.rs
Removes a lock from endorsement tracker, and replaces it with a more granular lock to protect only the cache operations.
This enables to run the (expensive) endorsement validation outside the locked scope, so it can be processed in parallel.
tested: [sharded-bm](https://grafana.nearone.org/d/deg7e0doxn30gf/blockchain-performance?orgId=1&from=2025-05-07T13:30:00.000Z&to=2025-05-07T13:45:00.000Z&timezone=browser&var-chain_id=$__all&var-role=$__all&var-node_type=$__all&var-node_id=.%2Aslavas.%2A&var-shard_id=$__all&var-node_id-2=.%2Atps.%2A&refresh=10s)
> enable parallel endorsement validation

- chain/chain/src/chain.rs
- chain/client/src/view_client_actor.rs
just discovered this function and thought I'd give it a try.
> refactor: Use `Arc::unwrap_or_clone` to get to the inner object

- chain/chain-primitives/src/error.rs
- chain/chain/src/chain.rs
- chain/chain/src/pending.rs
- chain/chain/src/tests/simple_chain.rs
There is a tricky case of multiple blocks at the same height. Initially I solved it in the way - if there is already some pending block, just process all other blocks directly, as it is malicious case and we should treat it as simple as possible.
However, there is a case when a node receives the same block multiple times. Then the second copy of the block got always executed right away, negating the optimisation. Moreover, it always happened for the block producer of the block itself, because it redirected the block to itself from the network layer. Some reference: https://grafana.nearone.org/goto/FfChEuxHR?orgId=1
To solve this "multiple copy" issue, I also expose block hash from the pending block pool. If it is already there, every copy should be pending as well (and it won't be …
> fix: make proper check before moving block to pending pool

- chain/network/src/tcp.rs
Make the code more resilient - don't crash if set_nodelay returns an error
> 2.6.2: Don't crash when nodelay is not supported

- chain/chain/src/chain.rs
- chain/chain/src/chain_update.rs
- chain/chain/src/runtime/mod.rs
- chain/chain/src/runtime/tests.rs
- chain/chain/src/types.rs
- tools/state-viewer/src/apply_chunk.rs
Currently we record "chunk result cache" hits and misses whenever we call `get_update_shard_job`, regardless of block type.
But it makes hits/misses metric harder to use. We care only whether chunk application was successfully skipped while processing full block, for optimistic block it will be miss anyway.
For that I introduce block type into the application block context. That's a bit excessive but solves the issue with minimal change, I think it's worth it.
As a result, for benchmark runs misses stay completely at 0, if all OBs are distributed and created perfectly. https://grafana.nearone.org/goto/LYjlJXxNR?orgId=1
> chore: record OB hits/misses only on processing Block

- chain/chain/src/pending.rs
It is too spammy and it is unfortunately standard behaviour because block producer seems to attempt processing its own block many times while waiting for optimistic block to be produced. I don't see performance issues with it, but log level must be reduced at least.
Some more context #13509
Actually, that's how it looks like for every node in forknet. It doesn't bring immediate issues, but it is also not something I expected. Every attempt to process block took 60ms here (I have 3s blocks here though) and they don't stop. For sequential chain client doesn't have any meaningful work to do anyway, but what about forks...
> chore: reduce log level of pending pool

- chain/network/src/tcp.rs
- cspell.json
Enable TCP_NODELAY to reduce the latency of sending network messages to other peers.
Helps deliver endorsements faster and increases validator's endorsement rate.
> fix(network): Enable TCP_NODELAY on all peer connections

- core/o11y/benches/metrics.rs
- core/primitives/benches/serialization.rs
- core/store/benches/finalize_bench.rs
- core/store/benches/store_bench.rs
- core/store/benches/trie_bench.rs
- core/store/src/lib.rs
- nearcore/benches/store.rs
- utils/near-cache/benches/cache.rs
- utils/near-performance-metrics-macros/src/lib.rs
replaces with `use ...`.
Just bugged me every time I saw the outdated `extern crate` being used.
> nit: refactor: remove a bunch of `extern crate`

- core/primitives/src/shard_layout.rs
- integration-tests/src/tests/features/in_memory_tries.rs
- test-loop-tests/src/examples/multinode.rs
- test-loop-tests/src/examples/simple.rs
- test-loop-tests/src/tests/chunk_validator_kickout.rs
- test-loop-tests/src/tests/congestion_control.rs
- test-loop-tests/src/tests/congestion_control_genesis_bootstrap.rs
- test-loop-tests/src/tests/contract_distribution_cross_shard.rs
- test-loop-tests/src/tests/epoch_sync.rs
- test-loop-tests/src/tests/global_contracts.rs
- test-loop-tests/src/tests/in_memory_tries.rs
- test-loop-tests/src/tests/malicious_chunk_producer.rs
- test-loop-tests/src/tests/multinode_stateless_validators.rs
- test-loop-tests/src/tests/state_sync.rs
- test-loop-tests/src/tests/view_requests_to_archival_node.rs
- test-loop-tests/src/utils/setups.rs
Removing `simple_v1` in favor of `multi_shard_custom`
> [cleanup] Remove reference of simple_v1 ShardLayout

- Cargo.lock
- chain/chain/src/chain.rs
- chain/chain/src/stateless_validation/chunk_validation.rs
- chain/chain/src/update_shard.rs
- tools/replay-archive/Cargo.toml
- tools/replay-archive/src/cli.rs
> refactor: `NewChunkData` can use `SignedValidPeriodTransactions` instead of passing components

- chain/chain/src/chain.rs
- chain/chain/src/chain_update.rs
- chain/chain/src/genesis.rs
- chain/chunks/src/logic.rs
- chain/chunks/src/shards_manager_actor.rs
- chain/client/src/chunk_executor_actor.rs
- chain/client/src/client_actor.rs
- chain/client/src/lib.rs
- chain/client/src/test_utils.rs
- chain/epoch-manager/src/tests/mod.rs
- chain/network/src/peer_manager/peer_manager_actor.rs
- chain/network/src/types.rs
- core/primitives/src/block.rs
- core/primitives/src/genesis/block.rs
- core/primitives/src/genesis/chunk.rs
- core/primitives/src/sharding.rs
- core/primitives/src/sharding/shard_chunk_header_inner.rs
- core/primitives/src/views.rs
- core/store/benches/finalize_bench.rs
- core/store/src/adapter/chain_store.rs
- integration-tests/src/tests/client/process_blocks2.rs
- nearcore/src/state_sync.rs
- test-loop-tests/src/examples/simple.rs
- test-loop-tests/src/setup/setup.rs
- test-loop-tests/src/setup/state.rs
- test-loop-tests/src/tests/spice.rs
- test-loop-tests/src/utils/peer_manager_actor.rs
Tracking issue: [#13385](https://github.com/near/nearcore/issues/13387)
In the test I check that chunks are being applied by changing balances,
querying status via view_client and making sure that balances are
updated correctly.
Right now for simplicity all chunks are applied synchronously in the actor which may be something we would want to improve later on.
There is intentionally no core statement handling yet and data
availability layer is mocked - peer manager's actor request is used to
share receipts.
This will be rewritten better to allow it being merged to master (after
consensus changes are merged in) later, but wanted to get some initial
feedback in case I am missing some big parts or taking completely wrong
approach.
One particular thing I am not sure about is how expensive are …
> spice mvp: chunk executor initial implementation. (#13404)

- chain/network/src/network_protocol/testonly.rs
- chain/network/src/peer/peer_actor.rs
- chain/network/src/peer/tests/communication.rs
- chain/network/src/peer_manager/tests/nonce.rs
- core/primitives-core/src/version.rs
- core/primitives/src/version.rs
We now use `MIN_SUPPORTED_PROTOCOL_VERSION` in favor of `PEER_MIN_ALLOWED_PROTOCOL_VERSION`.
Technically `PEER_MIN_ALLOWED_PROTOCOL_VERSION` is no longer correct if it is below `MIN_SUPPORTED_PROTOCOL_VERSION`
> [limited replayability] Remove PEER_MIN_ALLOWED_PROTOCOL_VERSION

- .github/workflows/ci.yml
I've noticed the [Cargo check publishable packages separately (Windows, win, windows-latest)](https://github.com/near/nearcore/actions/runs/15063554183/job/42343254085#logs) takes upwards of 15 min to complete. To improve upon efficiency and time to merge queue it makes sense to only run this CI in the merge queue.
> [ci] run Cargo check publishable packages only in merge queue

- chain/chain/src/tests/garbage_collection.rs
- nightly/expensive.txt
Follow-up to
https://github.com/near/nearcore/pull/13549#discussion_r2091565286c
The test was broken for 15 months and is now failing for a reason unrelated to the reason for which it was disabled.
> refactor: Remove ultra_slow_test_clear_old_data_too_many_heights

- pytest/tests/mocknet/cmd_utils.py
- pytest/tests/mocknet/helpers/neard_runner.py
- pytest/tests/mocknet/local_test_node.py
- pytest/tests/mocknet/mirror.py
- pytest/tests/mocknet/node_config.py
- pytest/tests/mocknet/node_handle.py
- pytest/tests/mocknet/remote_node.py
- pytest/tests/mocknet/utils.py
This PR introduces new commands to the mirror tool.
```
mirror schedule cmd
mirror schedule list
mirror schedule clear
```
`schedule cmd` can be applied to a subset of mirror commands to make them execute at a later time on the targeted host.
some example of usage:
```
(pytest_env) ➜  pytest git:(forknet/scheduled_commands_systemd) ✗ mirror --host-filter cf7c schedule cmd --schedule-in 20h --schedule-id act1 env --key-value "EEEEE=debug,network=info"
[2025-05-14 18:30:17] INFO: created configured logger, name test, level 20
[2025-05-14 18:30:18] INFO: created configured logger, name serializer, level 20
[2025-05-14 18:30:26] INFO: mocknet-mainnet-142274930-release26-cf7c:
stdout:
stderr:
Running timer as unit: mocknet-act1.timer
Will run service as unit: mocknet-act1.service
(pytest_env) …
```
> feat(forknet): add support for scheduled commands in forknet

- chain/chain-primitives/src/error.rs
- chain/chain/src/runtime/errors.rs
- chain/chain/src/runtime/mod.rs
- chain/client-primitives/src/types.rs
- chain/client/src/view_client_actor.rs
- chain/jsonrpc-primitives/src/types/query.rs
- chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
- chain/jsonrpc/src/api/query.rs
- chain/jsonrpc/src/lib.rs
- core/primitives/src/views.rs
- core/store/src/trie/update.rs
- integration-tests/src/user/runtime_user.rs
- runtime/runtime/src/adapter.rs
- runtime/runtime/src/state_viewer/errors.rs
- runtime/runtime/src/state_viewer/mod.rs
- test-loop-tests/src/tests/global_contracts.rs
This PR adds `QueryRequest` for retrieving global contract code. This is needed because `ViewCode` query only allows retrieving contracted used as part of the specified accounts. Global contracts deployed separately, so we need to have a dedicated view query.
2 separate enum variants are introduced for queries by hash (`ViewGlobalContractCode`) and by account id (`ViewGlobalContractCodeByAccountId`) to have simple API and keep it consistent with `DeployGlobalContract`/`UseGlobalContract` actions.
`QueryResponseKind::ViewCode` is reused for the response.
Also `QueryError::NoGlobalContractCode` error is introduced, similar to `NoContractCode`.
Closes #13531.
> feat: add rpc query for viewing global contract code

- cspell.json
- docs/SUMMARY.md
- docs/practices/workflows/futex_contention.md
This PR adds a new page in the book that explains how to gather lock contention data using `futexctn` .
> docs: add instruction on how to gather lock contention data

- nightly/pytest-sanity.txt
- pytest/tests/sanity/chunk_validator_failover.py
Attempt to reproduce: [#community-support > Failover node confusion @ 💬](https://near.zulipchat.com/#narrow/channel/469556-community-support/topic/Failover.20node.20confusion/near/516922703).
Reproduction unsuccessful - the test passes.
Also tested this on top of release 2.5 (in case the recent changes to use T1 connections helped) - but it passes there as well.
This test uses the failover procedure that restarts the backup node:
```
failover_node.kill()
failover_node.reset_validator_key(chunk_validator_node.validator_key)
chunk_validator_node.kill()
failover_node.start()
```
To try the hot-swap variant (no restart), replace that block with:
```
failover_node.reset_validator_key(chunk_validator_node.validator_key)
chunk_validator_node.kill()
failover_node.reload_updatable_config()
```
To …
> test: Chunk-only validator starts endorsing immediately after failover

- core/store/src/db/refcount.rs
Claping refcounts to 0 was originally introduced in PR https://github.com/near/nearcore/pull/12784/ as a solution to a potential issue with GC of parent shard_uid state when accessed from both children after resharding.
With the new TrieStateResharder as a proper fix where we are replicating the state from parent to both children, we no longer need this fix.
> [resharding] Allow negative refcount

- chain/chain/src/garbage_collection.rs
- core/primitives/src/shard_layout.rs
- integration-tests/src/tests/client/process_blocks.rs
- test-loop-tests/src/tests/resharding_v3.rs
- test-loop-tests/src/utils/resharding.rs
Update the state garbage collection code to take into account the new solution for refcount issue in resharding.
I don't completely understand what the old solution was doing, but the new solution divides gc into two parts, one specific to resharding, where we are simply deleting the parent shard_uid state, and second, deleting untracked shard_uids.
The logic to find untracked shard_uids is updated and simplified.
Don't worry if the old code and new code don't make 100% sense. I took several days to figure out what exactly is going on :)
> [resharding] Rewrite state column gc

- chain/chain/src/stateless_validation/mod.rs
- chain/chain/src/stateless_validation/state_witness.rs
- chain/client/src/stateless_validation/shadow_validate.rs
- chain/client/src/stateless_validation/state_witness_producer.rs
Prerequisite for debug tool to recreate state witness. It will be located in state-viewer, and we don't want to create Client and even Chain for debug purposes. It is more than enough to have ChainStore and EpochManager. 
GitHub doesn't recognise `git mv` is the original file is still present, so here https://github.com/near/nearcore/commit/4904c596d7081ed48af91c06e9bd98035345eb39 you can make sure that the logic is simply moved with minimal changes.
> refactor: move state witness creation from Client to ChainStore

- core/store/src/adapter/trie_store.rs
Previous implementation would allocate a whole `Arc<[u8]>` thingy to immediately deallocate it shortly afterwards
> store: improve `TrieStoreAdapter::get_ser`

- chain/epoch-manager/src/adapter.rs
~Based on the code & the comment it seems is_next_block_epoch_start expects the hash of the block itself, not the parent hash. Renaming the param to avoid confusion.~
^ This was incorrect but probably can still update the comment as it confused me.
> nit(epoch-manager): update comment for is_next_block_epoch_start

- core/store/src/archive/cold_storage.rs
- core/store/src/db/database_tests.rs
- core/store/src/db/rocksdb.rs
- core/store/src/node_storage/mod.rs
- core/store/src/node_storage/opener.rs
- core/store/src/store.rs
No reason to leak implementation details all over the place. In particular the newly added `database` method ensures that users don't clone the `storage`'s `Arc` behind `Store`'s back and create new ad-hoc stuff with it.
> store: make `storage` field private

- chain/chain/src/metrics.rs
- chain/chain/src/store/utils.rs
This can inform the size of the caches we should have in ChainStore from which validity period check later reads.
This metric is intended to be quick to compute and in no way 100% accurate (due to not necessarily handling multiple chains and such.)
Part of #12997
> chain_store: track how long is the delay for tx validity check

- chain/chain/src/runtime/mod.rs
- chain/chain/src/update_shard.rs
When reasoning about block production it's useful to know when the node is applying chunks, let's add those spans to the block production mode.
@Trisfald if you think it's too noisy we could make it _ext? or filter out in traviz.
> feat(tracing): add chunk application spans to block production mode

- chain/jsonrpc/openapi/openapi.json
- core/primitives/src/views.rs
This pull request introduces a minor change to the `CurrentEpochValidatorInfo` struct in `core/primitives/src/views.rs`. The change adds a `#[serde(default)]` attribute to the `shards_endorsed` field to ensure it is initialized with a default value during deserialization.
> fix validators_info deserialization

- pytest/lib/mocknet.py
- pytest/tests/mocknet/helpers/neard_runner.py
- pytest/tests/mocknet/mirror.py
The new shard tracking config is not known by 2.6 release. We will keep using the old config until the next release.
> fix(mirror): keep tracked shards backwards compatible

- benchmarks/sharded-bm/cases/forknet/10_cp_1_rpc_10_shard/params.json
- benchmarks/sharded-bm/cases/forknet/20_cp_1_rpc_20_shard/params.json
- benchmarks/sharded-bm/cases/forknet/50_cp_1_rpc_50_shard/params.json
- benchmarks/sharded-bm/cases/forknet/5_cp_1_rpc_5_shard/params.json
- benchmarks/sharded-bm/cases/forknet/70_cp_1_rpc_70_shard/params.json
- benchmarks/sharded-bm/cases/forknet/realistic_20_cp_1_rpc_20_shard/params.json
- benchmarks/sharded-bm/cases/local/1_node_10_shard/params.json
- benchmarks/sharded-bm/cases/local/1_node_1_shard/params.json
- benchmarks/sharded-bm/cases/local/1_node_50_shard/params.json
- benchmarks/sharded-bm/cases/local/1_node_5_shard/params.json
- benchmarks/sharded-bm/cases/local/3_cp_1_rpc_10_shard/params.json
- pytest/tests/mocknet/docs/sharded_bm.md
- pytest/tests/mocknet/sharded_bm.py
I misunderstood before why we needed tweak_config, but that seems like a nice usecase. https://github.com/near/nearcore/pull/13645#discussion_r2123197381
Now, if you want to make a slight change, like reduce block production time, you can run `tweak-config`, it will update configs on all nodes, and you will not have to reinit cluster again.
`apply-json-patches` didn't make sense because it didn't upload updated files.
Testing: the different profiles here https://grafana.nearone.org/goto/Xl6ljWYNg?orgId=1 were resulting only from calling start, stop and tweak-config.
> feat: tweak sharded-bm config in non-invasive way

- chain/chain/src/garbage_collection.rs
Relevant thread: [#nearone/private > mainnet node running out of disk space @ 💬](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/mainnet.20node.20running.20out.20of.20disk.20space/near/522805869)
High level, we can't call `will_shard_layout_change` and `get_shard_layout_from_prev_block` as these functions rely on getting block info for `block_info.epoch_first_block()` which has already been GC'd
> [resharding] Fix GC of parent state

- pytest/tests/mocknet/helpers/neard_runner.py
If the binary creates the new `tracked_shards_config`, wipe it. `mirror` only works with old `tracked_shard` config for compatibility with 2.6.3.
> fix(forknet): fix tracked shard config compatibility

- benchmarks/synth-bm/README.md
- This PR fixes an incorrect path reference in the benchmarks/synth-bm/README.md file. 
- The link to the locust workloads directory was using a tilde path (`~/pytest/tests/loadtest/locust/`) which doesn't correctly resolve in the repository context. 
- Changed to use the proper relative path (`../../pytest/tests/loadtest/locust/`) instead, ensuring the link correctly points to the locust workload examples.
> docs: Fix incorrect path

- docs/practices/testing/README.md
Replaced the outdated link to process_blocks.rs in the testing practices documentation with the correct path: integration-tests/src/tests/client/process_blocks.rs. This ensures that readers are directed to the current location of the example test file.
> Fix broken link to process_blocks.rs in testing documentation

- integration-tests/src/tests/nearcore/rpc_nodes.rs
- integration-tests/src/tests/nearcore/stake_nodes.rs
- nightly/expensive.txt
Based on flakiness seen [here](https://github.com/near/nearcore/actions/runs/15537333892/attempts/1?pr=13685), I'm moving `slow_test_get_execution_outcome_tx_failure` back to nayduck.
Also marking a couple of tests as slow.
> [test] Move test_get_execution_outcome_tx_failure back to nayduck

- chain/chain/src/chain.rs
- chain/chain/src/resharding/manager.rs
- chain/chain/src/resharding/trie_state_resharder.rs
- tools/database/src/memtrie.rs
Related to the thread here: [#nearone/private > mainnet node crash during garbage collection @ 💬](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/mainnet.20node.20crash.20during.20garbage.20collection/near/523304892)
High level, during resharding, in the TrieStateResharder, we were copying the state from parent shard_uid to the child shard_uid even for shards that the client was not tracking.
This had the unfortunate consequence that the memtrie was removed for these untracked shards and we were indirectly relying directly on the state column to iterate through state, which is super slow.
This PR fixes this issue where we are now only copying state in TrieStateResharder for tracked shards.
For testing, simply adding a debug assert in TrieStateResharder to check …
> [resharding] Do not split state of untracked child shard

- tools/flat-storage/src/resume_resharding.rs
In resharding tool we must manually create the entry for the parent flat storage in the FlatStorageManager, because it is needed to perform the flat store split operation.
> fix - Flat Storage resharding tool

- docs/practices/workflows/run_a_node.md
The latest version of `near` install via `npm` as directed by the docs I get
```console
❯ near --version
4.0.13
❯ NEAR_ENV=local near state test.near
near state <accountId>
View account's state (balance, storage_usage, code_hash, etc...)
Options:
--help       Show help  [boolean]
--version    Show version number  [boolean]
-v, --verbose    Prints out verbose output  [boolean] [default: false]
--networkId  Which network to use. Supports: mainnet, testnet, custom  [string] [default: "local"]
Error: Unconfigured environment 'local'. Can be configured in src/config.js.
at getConfig (/opt/homebrew/lib/node_modules/near-cli/config.js:40:15)
at connect (/opt/homebrew/lib/node_modules/near-cli/utils/connect.js:17:20)
at Object.viewAccount [as handler] …
```
> doc: clarify near-cli version

- Cargo.lock
- runtime/near-vm-runner/Cargo.toml
This feature flag, [which is enabled by default in Wasmtime](https://github.com/bytecodealliance/wasmtime/blob/ef7a29619789b2a43fd04a0aff81438696e5c8be/Cargo.toml#L443), turns on parallel compilation using [rayon](https://docs.rs/rayon/latest/rayon/)
Running a synthetic benchmark from https://github.com/cosmonic-labs/nearcore/commit/e9b038b9a68e87b61056337fc758e5891a96a81f on GCP `n2d-standard-8`.
Before:
```
test wasmtime_ft_transfer  ... bench: 301,324,308 ns/iter (+/- 5,026,087)
```
After:
```
test wasmtime_ft_transfer  ... bench: 133,858,110 ns/iter (+/- 7,693,557)
```
This seems to be a pretty-straightfoward change, but I am happy to run more comprehensive/time-consuming set of benchmarks to support it if desired
> feat: enable Wasmtime parallel compilation

- chain/chain/src/stateless_validation/chunk_validation.rs
- chain/chain/src/stateless_validation/state_witness.rs
- chain/client/src/stateless_validation/chunk_validator/mod.rs
- chain/client/src/stateless_validation/partial_witness/partial_deploys_tracker.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
- chain/client/src/stateless_validation/state_witness_producer.rs
- chain/client/src/stateless_validation/validate.rs
- chain/network/src/peer_manager/peer_manager_actor.rs
- core/primitives/src/reed_solomon.rs
Add tracing spans to track witness distribution
New spans for:
* Creating the witness, compressing it, preparing parts, sending parts
* Receiving and forwarding the parts
* Decoding the witness and processing it in ClientActor
A new tag is added for witness distribution spans: `tag_witness_distribution`
It's possible to export both block production and witness distribution spans by using:
```json
"opentelemetry": "[{tag_block_production=\"true\"}]=debug,[{tag_witness_distribution=\"true\"}]=debug"
```
> feat(tracing): witness distribution spans

- chain/chain/src/resharding/resharding_actor.rs
- chain/chain/src/resharding/trie_state_resharder.rs
Related to issue in 2.7 release related to resuming trie resharding
[#nearone/private > resume trie resharding issue (2.7 release)](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/resume.20trie.20resharding.20issue.20.282.2E7.20release.29/with/524478858)
More context on the thread, but high level, we want to set the trie_state_resharding_status at the beginning of resharding so that a future call to resume resharding can read it.
> [resharding] Set trie_state_resharding_status before flat storage resharding

- pytest/tests/mocknet/helpers/neard_runner.py
- Use all but 50G of the root disk for neard logs
- Add compation for logs
- Make logfiles 200M from 100M
- Add gzip compaction. This reduces the size from 100M to 10M
- Rotate the logfile when enard is restarted
From compaction alone we should get 10x more log retention.
> feat(forknet) add compaction for logs

- Cargo.lock
- Cargo.toml
- deny.toml
~This PR exists mostly to pull in https://github.com/bytecodealliance/wasmtime/pull/11068 (see profiles linked in that PR). If it lands in the upcoming Wasmtime 34.0.0 release (https://github.com/bytecodealliance/wasmtime/pull/11074), then this PR will be updated to just pull in the latest version. If it does not, then there will be two options:~
- ~use a git rev of Wasmtime until the commit linked lands in a release (current approach in this PR)~
- ~enable `gc`, and at least one of `gc-drc` or `gc-null` features to avoid collecting the backtrace, that is a fix that can be applied already today, but it pulls in `winch`-related Wasmtime crates into the dependency graph for some reason, which seems to be undesired for this project~
~Keeping this as draft until it's clear if the fix can …
> chore: update Wasmtime to 34

- runtime/near-vm-runner/src/tests/runtime_errors.rs
- runtime/near-vm-runner/src/tests/test_builder.rs
Tests now pass under x86_64 linux on wasmtime VM as well, so reenable said tests with the command
```console
cargo test --features wasmtime_vm,near_vm
```
With both the `dev-release` and `release` profiles.
Removing the comment in `test_builders.rs` on contentious signal handling since after more than 50 test runs we weren't able to reproduce.
> chore: remove `.skip_wasmtime()` logic from near-vm-runner tests

- docs/practices/workflows/profiling.md
Possibly this flag was renamed, but `readwrite` is not a valid flag in recent `neard` versions:
```
error: unexpected argument '--readwrite' found
tip: a similar argument exists: '--read-write'
Usage: neard view-state <--read-write|--store-temperature <STORE_TEMPERATURE>> <COMMAND>
```
> doc(profiling): use correct `read-write` flag

- chain/chain/src/chain.rs
- chain/chain/src/tests/simple_chain.rs
- chain/client/src/debug.rs
- core/primitives/src/block.rs
- test-loop-tests/src/tests/bandwidth_scheduler.rs
- test-loop-tests/src/tests/global_contracts_distribution.rs
- test-loop-tests/src/tests/max_receipt_size.rs
- tools/state-viewer/src/apply_chain_range.rs
- tools/state-viewer/src/apply_chunk.rs
This PR is the first step in trying to simplify the chunk iterators. We currently have iter_raw and iter_deprecated that are not too user friendly.
With this PR we make some major improvements to the iteration
- Now there are two new functions `iter_new` and `iter_old` to iterate over new and old chunks
- `ChunkType` now stores a new/old chunk but can dereference to the chunk header for easy access
- `Chunks` that is the container for the chunk headers can seamlessly dereference to `[ShardChunkHeader]` so that we can easily use methods like `len` and `index` on it.
Next PR in the series https://github.com/near/nearcore/pull/13784
> [refactor] 1/n Introduce chunk iter_new, iter_old

- chain/chain/Cargo.toml
- chain/chain/src/garbage_collection.rs
- chain/client/Cargo.toml
- chain/client/src/chunk_executor_actor.rs
- chain/epoch-manager/Cargo.toml
- core/primitives/src/utils.rs
- core/store/Cargo.toml
- core/store/src/adapter/chain_store.rs
- core/store/src/columns.rs
- nearcore/Cargo.toml
- test-loop-tests/Cargo.toml
- test-loop-tests/src/setup/setup.rs
This PR adds `DBCol::ReceiptProofs` database column to store incoming receipts in SPICE.
Conditional compilation with `#[cfg(feature = "protocol_feature_spice")]` is needed here to prevent database changes in the stable protocol version.
Note that in SPICE we don't use `IncomingReceipts` column since it is only needed when handling missing chunks (see `get_incoming_receipts` fn usage).
`cargo test -p test-loop-tests --features=protocol_feature_spice -- spice` still passes.
> feat: add db column for receipt proofs for SPICE

- chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
We must check `processed_witnesses` under lock, to avoid some race condition that can lead to process twice the same SW.
Note that the race conditions happen only if SW parts distribution is changed in a way that multiple parts are delivered by multiple nodes at very low latencies.
> fix - prevent race condition in reconstructing witness

- runtime/near-vm-runner/src/lib.rs
- runtime/near-vm-runner/src/near_vm_2_runner/runner.rs
- runtime/near-vm-runner/src/near_vm_runner/runner.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
- promote `lazy_drop` already used for NearVM(s) to a crate-level function and use in `wasmtime_runner` as well
- slightly reorganize the code to reduce nesting
- switch from `String` to `Box<str>` - this probably has negligible impact, but since we're starting off with `&str`, might as well avoid allocating the redundant capacity field
refs #13791 
Before this PR: 153/153 blocks applied in 60s at a rate of 2.577/s
After this PR: 277/277 blocks applied in 2m at a rate of 2.7627/s
To be fair, the results are somewhat inconsistent, however this PR seems to be faster in most cases or at least provide more consistent performance.
heads benchmarked:
```
* b33a95afa - feat(wasmtime): lazy drop, reorganize slightly [Roman Volosatovs] (2 hours ago) (tag: measurement-wasmtime-34-lazy-drop)
* …
```
> feat(wasmtime): lazy drop, reorganize slightly

- runtime/near-vm-runner/src/tests/runtime_errors.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
The Wasmer implementation canonicalizes NaNs, so we're matching that behaviour on the Wasmtime side.
> fix: canonicalize wasmtime NaNs

- runtime/near-vm-runner/src/tests/cache.rs
- runtime/near-vm-runner/src/tests/fuzzers.rs
- runtime/near-vm-runner/src/wasmtime_runner.rs
Closes #13790 
The fuzzer test is effectively a duplicate of `slow_test_near_vm_is_reproducible_fuzzer`: https://github.com/near/nearcore/blob/3e3b52c7f57b5cdd01256c4d9e27a5b51ef16f3b/runtime/near-vm-runner/src/tests/fuzzers.rs#L119-L143
> test: run cache determinism tests on Wasmtime

- chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
- core/primitives/src/reed_solomon.rs
Contract deploys message is split into the number of parts equals to the total number of validators in the epoch excluding validators for the current shard. We use `reed_solomon_erasure::galois_8` which only supports max 256 parts.
This PR limits the number of part owners to not exceed the max number of parts. Technically this should be a protocol upgrade, but attempting to reed solomon encode data into more than 256 parts crashes the node. So even though during the transition period old binary won't be able to decode contract deploys from the new one, it is still better than crashing the chunk producer. The only downside is that the old binary will log `Failed to reed solomon decode deployed contracts`.
> fix: limit contract deploys part owners

- pytest/tests/mocknet/docs/release_forknet.md
- pytest/tests/mocknet/mirror.py
- pytest/tests/mocknet/release_forknet.py
- pytest/tests/mocknet/release_scenarios/__init__.py
- pytest/tests/mocknet/release_scenarios/base.py
- pytest/tests/mocknet/release_scenarios/test27.py
This pull request adds a framework for running release tests in a Forknet environment. It includes new scripts, test definitions, and updates to existing infrastructure to simplify setting up and managing release test scenarios.
- Added `release_forknet.py` to manage Forknet release test lifecycles — create infra, run tests, and clean up. Supports commands like `create`, `start_test`, and `destroy`.
- Introduced a `TestSetup` base class in `release_scenarios/base.py` to standardize how test cases initialize environments, update configs, and check network readiness.
- Added `Test27` and `Test27Small` in `release_scenarios/test27.py` to test upgrades from 2.6.3 to 2.7 with configurable validator and epoch settings.
- Created a test registry in `release_scenarios/__init__.py` to map test …
> feat(forknet): Add forknet release scenarios

- chain/client/src/sync/external.rs
- chain/client/src/sync/state/mod.rs
- nearcore/src/state_sync.rs
- tools/state-parts-dump-check/src/cli.rs
- tools/state-viewer/src/state_parts.rs
Backport of 7257689e69fee63bb6973cd6b98f85440657985e.
> 2.7.0: ask object_storage to grab creds from environment

- core/store/src/adapter/trie_store.rs
- core/store/src/deserialized_column.rs
- core/store/src/store.rs
While this is likely not enough to make a measurable impact on the total TPS by itself, IMO the 10-20ms savings in `postprocess_ready_block` is too much to ignore.
[Before](https://share.firefox.dev/3TmaZFg), [After](https://share.firefox.dev/4epPLja) The call path is: 
```
trie_store::maybe_get_shard_uid_mapping 
ShardTries::apply_insertions_inner 
ShardTries::apply_insertions 
ChainStoreUpdate::finalize
ChainStoreUpdate::commit
Chain::postprocess_ready_block 
```
Additionally I think caching this is better than hoisting it out of `trie_store` methods, as it seems along the lines of breaking the resharding mapping abstraction (which is already complex).
>  feat(store): cache None values (for StateShardUIdMapping) 

- core/schema-checker/schema-checker-macro/src/lib.rs
This does not actually change the way tuple type IDs are calculated (`TypeId::of` will properly consider changes to all of the fields.) All this does is get rid of a warning that can look pretty scary at first.
> feat(protocol-schema): add support for tuples

- chain/client/src/chunk_executor_actor.rs
- test-loop-tests/src/setup/setup.rs
- test-loop-tests/src/tests/spice.rs
The main goal of this PR is to move expensive chunk application outside of actor thread, just like we currently do as part of block processing and stateless validation.
Implementation notes:
- We send `ExecutorApplyChunksDone` message back to chunk executor actor so that database changes are happen as part of the actor thread. This is needed because `ChainStore` is not thread safe. As an alternative we could create a new instance of `ChainStore` for every chunk application.
- We keep track of blocks that are currently applied with `blocks_in_execution`. Also we check database for existence of the corresponding chunk extras to verify if the block was already processed.
- A requirement for previous block to be executed is added in order to start applying chunks for the current block. …
> feat(spice): apply chunk asynchronously

- core/store/src/adapter/trie_store.rs
This PR fixes a resharding related bug that we have for archival nodes cold storage reads.
Read [#nearone/private > 2.7 testnet upgrade @ 💬](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/2.2E7.20testnet.20upgrade/near/527995852) for more context.
High level we want to change the logic of fetching nodes from using shard_uid_mapping directly to first trying without shard_uid_mapping and then with.
> [fix] Fix cold storage shard_uid mapping based reads

- core/store/src/trie/mod.rs
- core/store/src/trie/ops/tests.rs
- core/store/src/trie/state_parts.rs
- core/store/src/trie/trie_storage.rs
Visited nodes are only really interesting for only a couple callsites.
Everything else does not care in the least. So its a wasted work in many
cases, including pretty hot uses such as applying a chunk (during SW
validation.)
With the goal of making absolutely sure there is nothing else to squeeze
out of this sponge lets statically at compile time compile out most of
this logic.
Co-authored-by: Darioush Jalali <darioush.jalali@nearone.org>
> perf: statically avoid recording partial storage coverage

- tools/debug-ui/src/LatestBlocksView.tsx
- Change `Processing Time (ms)` header to `Proc. Time (ms)` with a tooltip
- Display block delay with exactly exactly 3 digits digits after the decimal point
Before:
After:
> feat: make debug ui latest blocks page slightly more compact

- tools/debug-ui/src/LatestBlocksView.scss
- tools/debug-ui/src/LatestBlocksView.tsx
Currently Latest Blocks page contains quite a few block and chunk fields that we are no always interested in.
This PR adds toggle buttons on top of the table to allow showing/hiding corresponding fields:
The goal here is to make the table more compact and enabled adding more fields in the future without overloading user with unnecessary information.
By default only Block Delay and Chunk Gas Used is enabled.
Before:
After:
> feat(debug-ui): make it possible to show/hide block and chunk fields 

- core/store/src/trie/trie_recording.rs
*Usually* unstable sort is going to be faster than a stable sort. It of course depends on data and making comparisons is difficult due to how different the stable and unstable sorting algorithms implemented in `libstd` are. In terms of requirements to the data ordering since the collection sorted is randomized, stable sorting is not providing any guarantees.
> perf: use `sort_unstable` in `TrieRecorder`

- chain/client/src/sync/state/downloader.rs
- chain/client/src/sync/state/external.rs
- chain/client/src/sync/state/network.rs
- chain/client/src/view_client_actor.rs
- core/chain-configs/src/client_config.rs
- core/chain-configs/src/lib.rs
- nearcore/src/config.rs
- pytest/lib/state_sync_lib.py
- pytest/tests/sanity/state_sync_decentralized.py
Similar to #13464, which fixed this logic for headers.
The old code carries the assumption that the fallback source will work eventually. Rather we should continue making attempts to both sources until the needed part is obtained.
The fix should be included to the 2.7 release.
---
As a follow up, it should be possible to test this by adding a fake bucket in the state_sync_decentralized.py pytest. We can also introduce some random failures of the p2p requests to make sure the bucket gets hit (unsuccessfully).
> state_sync: fix attempt logic for parts (#13891)

- runtime/runtime/src/congestion_control.rs
- runtime/runtime/src/global_contracts.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/metrics.rs
ShardLayout will not change during an application of a single shard and fetching the shard layout for every single forwarded receipt gets pretty expensive pretty fast: internally it involves walking a `BTreeMap` and some allocations as well.
Newly added asserts mitigate potential misuse where `epoch_id` would indeed change.
cc @darioush
> perf: memoize `ShardLayout` for the lifetime of a `ReceiptSink`

- chain/chain/src/runtime/mod.rs
- core/store/src/trie/state_parts.rs
- core/store/src/trie/state_snapshot.rs
`get_state_part_boundaries` can easily be inside the `get_trie_nodes_for_part_with_flat_storage` function here. No need to call it externally and pass in the parameters.
> [state_part] Simplify get_trie_nodes_for_part_with_flat_storage

- cspell.json
- pytest/tests/mocknet/helpers/get-profile.sh
- pytest/tests/mocknet/mirror.py
- pytest/tests/mocknet/sharded_bm.py
Adds the "off-cpu" perf tracing and `perf stat` for the aggregate report.
This is mostly targeted for use in the CI benchmark runs.
> add option to download extended perf data in mocknet pytest

- chain/epoch-manager/src/shard_assignment.rs
Fix `index out of bounds` panic in shard assignment when number of shards increases between epochs.
> fix - shard assignment out of bounds

- runtime/runtime/src/lib.rs
- runtime/runtime/src/types.rs
Since we're taking the values… by value, there is no reason to create a new vector for those values when we can "simply" use the original vector.
> perf: avoid re-allocating the transactions for validation

- benchmarks/transactions-generator/justfile
hardcoding bash path is not portable.
> chore: use /usr/bin/env bash in tx gen justfile

- chain/client/src/chunk_producer.rs
- chain/client/src/client.rs
- chain/jsonrpc/src/lib.rs
- test-loop-tests/src/examples/missing_chunk.rs
This PR implements #13912 as part of adversarial behavior so we can have it in master.
New `AdvProduceChunksMode::SkipWindow` is added to allow skipping a sequence of `skip_length` chunks in a row deterministically randomly chosen in a window of size `window_size`. 
This allows us to test that network can recover after a long sequence of missing chunks.
> feat: add adversarial feature to skip chunk production window

- chain/chain/src/genesis.rs
- test-loop-tests/src/tests/congestion_control_genesis_bootstrap.rs
This PR reproduced the issue experienced in 2.7 release testing:
- Have a network of nodes
- Node A will become CP in the next epoch
- Node A database is cleaned and the node performs epoch sync
- Epoch sync fails with `MissingTrieValue` when fetching genesis congestion info
The repro here is more narrow scoped than a full pytest test. Here we are simply asserting that `get_genesis_congestion_infos` works as expected when the chain is not a production chain, and the node is doing epoch synch from a clean DB.
Included:
- Unit test
- Fix
The fix is simply to return default congestion info if we can't retrieve it for the genesis block from the DB.
> fix - Missing congestion info in mocknet epoch sync

- core/store/src/trie/mem/memtrie_update.rs
- core/store/src/trie/mem/memtries.rs
- core/store/src/trie/shard_tries.rs
This PR introduces the concept of a snapshot for memtries. This is useful if we want to save the state at a specific height, for example in the case of state_sync.
Conceptually it's very simple, where we are simply increasing the refcount of the state_root of the snapshot height so that it doesn't get garbage collected.
Caveats: Saving a snapshot for an extended period of time can lead to extra memory consumption as the nodes corresponding to the snapshot height are not cleaned up. This is something that the user of the snapshot should be careful with.
> [memtrie] Introduce snapshot in memtrie

- Cargo.lock
- Cargo.toml
- core/primitives/src/version.rs
Prepare `2.7.0-rc.4` release
* Set neard version to `2.7.0-rc.4`
* Set crates version to `0.31.0-rc.4`
* Set voting date to Wednesday 2025-07-30 02:00 UTC - protocol upgrade will happen 7-14 hours later, on 2025-07-30 between 9:00 and 16:00 UTC.
According to our estimation tool the upgrade will happen around 2025-07-30 12:00 UTC
```
$ python3 debug_scripts/estimate_epoch_start_time.py  --url http://34.13.153.53:3030 --num_past_epochs 10 --num_future_epochs 20
Epoch -1: 06 hours, 52 minutes
Epoch -2: 06 hours, 50 minutes
Epoch -3: 06 hours, 55 minutes
Epoch -4: 06 hours, 54 minutes
Epoch -5: 06 hours, 53 minutes
Epoch -6: 06 hours, 50 minutes
Epoch -7: 06 hours, 54 minutes
Epoch -8: 06 hours, 51 minutes
Epoch -9: 06 hours, 52 minutes
Epoch -10: 06 hours, 52 minutes
Exponential weighted …
```
> Prepare 2.7.0-rc.4

- chain/client/src/chunk_producer.rs
- chain/client/src/client.rs
- chain/client/src/client_actor.rs
- integration-tests/src/tests/features/adversarial_behaviors.rs
- test-loop-tests/src/examples/missing_chunk.rs
- remove log fields that are already added by spans
- shorter log messages
- remove check if current validator is a chunk producer from client since we already check in chunk producer
- move `should_skip_chunk_production` check to `produce_chunk`
- remove `on_block_accepted` span, it looks like some kind of copy&paste fail, it doesn't belong there
- change `produce_chunk` handling in client to use `continue` instead of `return` since validator can be chunk producer for multiple shards
- group adversarial controls together into struct
example log:
`0.058s DEBUG check_triggers:try_process_unfinished_blocks:postprocess_ready_blocks{should_produce_chunk=true}:on_block_accepted_with_optional_chunk_produce{block_hash=EJRT7j3BjMgtBNqsd3QzAaLEKjapcSa6mNsTymLRwBDb status=Next provenance=PRODUCED …
> refactor: various improvements around chunk production code

- chain/chain/src/validate.rs
- chain/client/src/stateless_validation/chunk_validation_actor.rs
- integration-tests/src/tests/client/process_blocks2.rs
The PR adds further chunk consistency checks. Validators will now reassemble the full payload from incoming data and derive a compact fingerprint over the segments, cross-checking the fingerprint for validity.
Discrepancies trigger an early exit and will be registered by a lightweight metric that has been added to track the cost per shard.
> chore: extra chunk checks

- pytest/tests/sanity/slow_chunk.py
1. Ensure the test actually causes missing chunks and recovers after that. (Currently it exits before the chunks are missing)
2. Submit the transaction without waiting for it, allowing for execution to take longer than 10s
Example output from running this:
```
...
[2025-07-29 15:11:02] INFO: #10 6EiCP3KKTLLf8FC7TodN3MFmxaaNVPqs9gcCYKZFYVVm  (waiting for #10)
[2025-07-29 15:11:02] INFO: Deploying contract.
[2025-07-29 15:11:02] INFO: Loading test contract rs_contract.wasm
2025-07-29T13:11:02.866469Z  INFO neard: version="trunk" build="1.36.1-2361-g157e53a9d7-modified" commit="157e53a9d71fede76c6f6ac7555b98b5457c9d09" latest_protocol=79
2025-07-29T13:11:02.866500Z ERROR neard::cli: THIS IS A NODE COMPILED WITH ADVERSARIAL BEHAVIORS. DO NOT USE IN PRODUCTION.
[2025-07-29 15:11:02] INFO: …
```
> test: fixes to slow_chunk.py

- benchmarks/sharded-bm/cases/log_patch.json
- chain/chain/src/chain.rs
- chain/client/src/client.rs
- chain/client/src/client_actor.rs
Updates optimistic traces to use consistent attributes. Also adds a new tag `tag_optimistic` to be used now for OB and in the future for optimistic witness.
> observability - update optimistic traces

- core/store/src/trie/mem/iter.rs
- core/store/src/trie/mem/memtrie_update.rs
- core/store/src/trie/mem/mod.rs
- core/store/src/trie/trie_recording.rs
Follow up on https://github.com/near/nearcore/pull/13988
There are two more places where we can use `record_with` to do less serialization.
Speeds up chunk application by another ~10%
Before: application time: 108.4ms, applications per second: 9.22
After: application time: 95.1ms, applications per second: 10.51
> feat(recording): use record_with in more places

- runtime/runtime/src/ext.rs
Seems it is always set to true, maybe leftover from another feature.
> nit(runtime): remove unused allow_insert

- chain/chain/src/validate.rs
- chain/client/src/stateless_validation/chunk_validator/mod.rs
- integration-tests/src/tests/client/process_blocks2.rs
The PR adds further chunk consistency checks. Validators will now reassemble the full payload from incoming data and derive a compact fingerprint over the segments, cross-checking the fingerprint for validity.
Discrepancies trigger an early exit and will be registered by a lightweight metric that has been added to track the cost per shard.
> chore: extra chunk checks (#13984)

- pytest/tests/sanity/slow_chunk.py
1. Ensure the test actually causes missing chunks and recovers after that. (Currently it exits before the chunks are missing)
2. Submit the transaction without waiting for it, allowing for execution to take longer than 10s
Example output from running this:
```
...
[2025-07-29 15:11:02] INFO: #10 6EiCP3KKTLLf8FC7TodN3MFmxaaNVPqs9gcCYKZFYVVm  (waiting for #10)
[2025-07-29 15:11:02] INFO: Deploying contract.
[2025-07-29 15:11:02] INFO: Loading test contract rs_contract.wasm
2025-07-29T13:11:02.866469Z  INFO neard: version="trunk" build="1.36.1-2361-g157e53a9d7-modified" commit="157e53a9d71fede76c6f6ac7555b98b5457c9d09" latest_protocol=79
2025-07-29T13:11:02.866500Z ERROR neard::cli: THIS IS A NODE COMPILED WITH ADVERSARIAL BEHAVIORS. DO NOT USE IN PRODUCTION.
[2025-07-29 15:11:02] INFO: …
```
> test: fixes to slow_chunk.py (#13983)

- core/primitives/src/version.rs
Prepare `2.7.0-rc.4` release
https://github.com/near/nearcore/pull/13969 already:
* Set neard version to `2.7.0-rc.4`
* Set crates version to `0.31.0-rc.4`
In this PR, we:
* Set voting date to Tuesday 2025-08-05 02:00 UTC - protocol upgrade will happen 7-14 hours later, on 2025-08-05 between 9:00 and 16:00 UTC.
According to our estimation tool the upgrade will happen around 2025-08-05 12:20 UTC
```
$ python3 debug_scripts/estimate_epoch_start_time.py  --url http://34.13.150.28:3030 --num_past_epochs 10 --num_future_epochs 20
Epoch -1: 06 hours, 51 minutes
Epoch -2: 06 hours, 52 minutes
Epoch -3: 06 hours, 55 minutes
Epoch -4: 06 hours, 53 minutes
Epoch -5: 06 hours, 51 minutes
Epoch -6: 06 hours, 52 minutes
Epoch -7: 06 hours, 53 minutes
Epoch -8: 06 hours, 50 minutes
Epoch -9: 06 hours, …
```
> Prepare `2.7.0-rc.4`

- chain/client/src/chunk_producer.rs
Adding a new span `produce_chunk_internal` with the following properties:
- contains attribute `height` in order to be linked to other spans in traviz
- emit only when chunk is actually produced
I also removed the old "produce_chunk" span because I don't see anymore use case for that.
> observability: add produce_chunk_internal span

- chain/chain/src/chain.rs
- chain/chain/src/store/mod.rs
- chain/chunks/src/logic.rs
- core/store/src/adapter/chain_store.rs
Maybe helpful with this (starting OB processing earlier), by avoiding de-serializing the partial chunk
> nit: add partial_chunk_exists

- core/store/src/trie/mem/memtrie_update.rs
- core/store/src/trie/mem/node/encoding.rs
- core/store/src/trie/mem/node/mod.rs
Even when the node hash is computed (ie. we already serialized it once), during computing the new root, we end up calling `to_raw_trie_node_with_size_non_leaf` in apply_memtries with `new_with_hash`.
Since we already know the memory usage & hashes for the nodes as well we can pass it in and avoid the call to `to_raw_trie_node_with_size_non_leaf`. This could shorten the time of applying memtries.
> perf(memtries): Avoid re-serializing nodes when size/hash is known

- pytest/tests/mocknet/helpers/neard_runner.py
- pytest/tests/mocknet/mirror.py
`amend-genesis` (Forknet v1) is very slow to build state. On top of this it has not been used in more than a year in favor of the `fork-network` approach.
This PR removes it from forknet setup.
> chore(forknet): deprecate legacy_records

- pytest/lib/cluster.py
- pytest/lib/mocknet.py
- pytest/requirements.txt
- pytest/tests/mocknet/local_test_node.py
- pytest/tests/mocknet/mirror.py
- pytest/tests/mocknet/node_config.py
- pytest/tests/mocknet/node_handle.py
- pytest/tests/mocknet/remote_node.py
Previously the host clasification was done by hostname. 
This PR proposes a more reliable clasification using GCloud host labels.
This will remove the need to assign long names to hosts in forknet and fix the bug preventing overlapping mockent_ids such as: `test` and  `testing-something`.
This feature is required to enable chunk only validator hardware in mocknet.
> feat(forknet): label based selection

- chain/chain/src/tests/simple_chain.rs
- chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
- core/primitives-core/src/version.rs
- core/primitives/res/epoch_configs/mainnet/80.json
- core/primitives/res/epoch_configs/testnet/143.json
- core/primitives/res/epoch_configs/testnet/80.json
- core/primitives/src/epoch_manager.rs
And increase number of validator mandates per shard to 105, as discussed here [#nearone/private > 2.8 release - more partial seats @ 💬](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/2.2E8.20release.20-.20more.20partial.20seats/near/532980422)
Next step is to cherry-pick this on 2.8.0.
@VanBarbascu could you remind why we wanted to create protocol version 81? No one seems to use 80 so far.
> feat: increase validators number to 500

- pytest/tests/mocknet/helpers/neard_runner.py
- pytest/tests/mocknet/release_scenarios/base.py
This pull request makes improvements to error handling and logging in the mocknet testing helpers, specifically around binary updates and environment initialization. The changes enhance the clarity of error messages and log outputs, making debugging easier.
> fix(forknet): fix neard-runner error handling

- pytest/tests/mocknet/sharded_bm.py
Detection of which node is an RPC and which node is a CP is broken. However, we don't need an RPC node at all, so we can simply remove it from the equation.
> fix - remove RPC node from benchmarks

- chain/chunks/src/shards_manager_actor.rs
- chain/client/src/client_actor.rs
- chain/client/src/sync_jobs_actor.rs
- core/async/src/actix/wrapper.rs
- integration-tests/src/env/setup.rs
- integration-tests/src/tests/network/runner.rs
- nearcore/src/lib.rs
The following actors now use tokio-based runtime:
* ShardsManagerActor
* SyncJobsActor
* PartialWitnessActor
* ReshardingActor
* GCActor
* StateRequestActor
Actors still on Actix:
* All sync actors, such as ViewClientActor and RpcHandlerActor - requires replacement sync runtime implementation
* Network actors (PeerManagerActor and PeerActor) - requires partial migration to near-async framework as well as runtime cancellation implementation
* TelemetryActor - requires making the actor Send.
> Migrate all `spawn_actix_actor` to `spawn_tokio_actor`.

- chain/chain/src/tests/simple_chain.rs
- chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
- core/parameters/res/runtime_configs/81.yaml
- core/parameters/res/runtime_configs/parameters.snap
- core/parameters/src/config_store.rs
- core/parameters/src/snapshots/near_parameters__config_store__tests__149.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__81.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_129.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_149.json.snap
- core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_81.json.snap
- core/parameters/src/snapshots/near_parameters__view__tests__runtime_config_view.snap
- core/primitives-core/src/version.rs
- core/primitives/src/snapshots/near_primitives__views__tests__runtime_config_view.snap
- integration-tests/src/tests/features/chunk_nodes_cache.rs
- integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
- integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
- runtime/runtime-params-estimator/src/cost.rs
- runtime/runtime-params-estimator/src/estimator_context.rs
- runtime/runtime-params-estimator/src/gas_cost.rs
- runtime/runtime-params-estimator/src/lib.rs
- runtime/runtime-params-estimator/src/trie.rs
- runtime/runtime/src/ext.rs
This change reduces the gas cost for `wasm_touching_trie_node` and increases the compute cost of  `wasm_read_cached_trie_node`, so they can be interchangeable in the future.
I also added a test to ensure they would not unintentionally diverge to different values in the future.
> feat(parameters): Equalize cost of touching and reading trie nodes

- pytest/tests/mocknet/helpers/neard_runner.py
- pytest/tests/mocknet/mirror.py
- pytest/tests/mocknet/node_handle.py
- pytest/tests/mocknet/release_scenarios/base.py
- pytest/tests/mocknet/remote_node.py
During the init, mirror.py sends configs to the host that can be inferred locally. Let the host decide the default configs to reduce the number of requests done to the hosts.
The possibility to update the configs is not hindered by this change. Use `mirror update-config`
> chore(forknet): move default configs from mirror init to host

- core/crypto/ed25519-batch/benches/ed25519_benchmarks.rs
- core/crypto/ed25519-batch/src/lib.rs
- core/crypto/ed25519-batch/tests/ed25519.rs
- Use same message for single signature benchmark as batch benchmark (for a more similar comparison across batch & single signature verification)
- Use same message as benchmarks in tests (some of the language included may be unnecessarily distracting eg https://github.com/near/nearcore/commit/45f4e859f21594cc6f8affdc6ad909db43c5a466#r164289156)
fyi @SimonRastikian
> chore(ed25519-batch): use same messages for test / bench

- chain/chain/src/update_shard.rs
- chain/client/src/chunk_producer.rs
Show number of transactions and receipts in the chunk production/application spans. Helps figure out what load is running on the network.
> feat(tracing) - number of transactions in chunk application spans

- runtime/near-vm-runner/src/wasmtime_runner/mod.rs
Enable inlining. Note that the feature is still very fresh and just introduced in Wasmtime 36
https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.compiler_inlining
> feat(wasmtime): enable inlining

- .github/workflows/ci.yml
- .github/workflows/mac_m1_binary.yml
Intel Mac OS 15 [fails](https://github.com/near/nearcore/actions/runs/17203730514/job/48799599736) to build.
Reverting to Mac OS 14 and setting the ARM Mac OS to latest.
Tested by manual run https://github.com/near/nearcore/actions/runs/17204329496/job/48801494739
> Chore: revert Intel Mac OS to 14

- chain/chain/src/chain.rs
- chain/chain/src/lib.rs
- chain/client/src/sync/block.rs
- add `#[instrument]` for `block_sync` function extracting common fields
- directly send request as part of `for _ in 0..max_block_requests` instead of accumulating `requests`
- log when next block hash is not found
- log when block is known
- the following functions are renamed and moved as member functions to `Chain`: `check_header_known`, `check_known`, `check_known_store` 
- `BlockKnowledge` enum is introduced to replace `Result<(), BlockKnownError>`
> refactor: improve block_sync logging

- Cargo.lock
- Cargo.toml
- chain/rosetta-rpc/Cargo.toml
- chain/rosetta-rpc/src/lib.rs
- chain/rosetta-rpc/src/models.rs
- chain/rosetta-rpc/src/types.rs
- chain/rosetta-rpc/src/utils.rs
- cspell.json
- deny.toml
This is required as part of the effort to migrate from actix_web to axum.
We use paperclip for openapi spec but paperclip doesn't support axum. This PR changes from using paperclip to utoipa libraty.
> [actix_migration] Use utoipa instead of paperclip for OpenApi Spec

- test-loop-tests/src/tests/global_contracts.rs
- test-loop-tests/src/tests/global_contracts_distribution.rs
- test-loop-tests/src/tests/resharding_v3.rs
- test-loop-tests/src/utils/mod.rs
Followup to #14017 cleaning old utils usage in global contracts tests.
Also removes `#[cfg_attr(not(feature = "nightly"), ignore)]` as it is no longer needed.
> refactor: update global contracts test loop tests to use TestLoopNode

- Cargo.lock
- Cargo.toml
- chain/network/src/store/mod.rs
- chain/network/src/store/schema/mod.rs
This fixes failing cargo audit CI:
```
Crate:     tracing-subscriber
Version:   0.3.18
Title:     Logging user input may result in poisoning logs with ANSI escape sequences
Date:      2025-08-29
ID:        RUSTSEC-2025-0055
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0055
Solution:  Upgrade to >=0.3.20
Dependency tree:
tracing-subscriber 0.3.18
```
> chore(deps): bump tracing-subscriber

- chain/epoch-manager/src/reward_calculator.rs
There is some annoying part of code where for all reasonable protocol versions inflation rate is always set to 5%, even though we have `max_inflation_rate` parameter in genesis.
If forknet depends on the exact order of validators, non-zero rewards may break it.
Based on #3294, `use_hardcoded_value` is just a hack to override inflation. This hack was introduced because we didn't have epoch config store yet. `max_inflation_rate` should be moved to epoch config, especially if we decide to change inflation.
For now, let's change condition for `use_hardcoded_value` to checking whether we are on mainnet or testnet. Due to limited replayability, it is equivalent.
For forknets though, `max_inflation_rate` will be taken from their genesis, as forknet engineers should expect.
> fix: take inflation rate from genesis for forknets

- benchmarks/sharded-bm/cases/base_config_patch.json
- core/store/src/config.rs
- core/store/src/db/rocksdb.rs
- cspell.json
This is the next iteration of rocksDB tuning based on benchmark data.
- Optimize store config for benchmarks
- Increase effective rocksDB parallelism through subcompaction jobs
- Shift more resource allocation to write heavy columns and reduce it for less used columns
> perf: further tune rocksdb with per column config 

- Cargo.lock
This addresses the failing audit CI
> chore: update flate2

- integration-tests/src/tests/client/sync_state_nodes.rs
- Disable flaky `slow_test_state_sync_headers_no_tracked_shards` test by adding `#[ignore]` attribute
This has caused headaches in simple runs. I've seen this enough time to disable the test.
https://github.com/near/nearcore/actions/runs/17504038433/job/49724754482?pr=14162
> [test] Disable flaky slow_test_state_sync_headers_no_tracked_shards test

- core/primitives/src/trie_key.rs
- core/store/src/trie/update.rs
- runtime/runtime/src/global_contracts.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/state_viewer/mod.rs
`TrieUpdate` is a relatively weird place to put common logic such as this, as it does not really have anything to do with account contracts and its API surface should be somewhat agnostic of the data it is working with.
But for the most part this is informed by the want to reuse this code with the new `StateUpdate` and this logic living inside `TrieUpdate` was bothering me quite some.
In fact this interface probably should take `&dyn TrieAccess` as an argument or something of that sort, but this is not easily achievable for `AccountContract::hash` due to `TrieAccess` not exposing accessors for `OptimizedValueRef`s. Left the argument as `TrieUpdate` for now, but in the future this will change (in a less involving way.)
> refactor: move `AccountContract` utilities off `TrieUpdate`

- core/primitives/src/action/mod.rs
- core/primitives/src/trie_key.rs
- core/store/src/trie/update.rs
- runtime/runtime/src/actions.rs
- runtime/runtime/src/global_contracts.rs
- runtime/runtime/src/lib.rs
- runtime/runtime/src/state_viewer/mod.rs
These utility functions seem weird to have on a `TrieUpdate`. Usually I
would've considered adding an extension trait similar as for #14192, but
in this case these functions are only used once and adding an extension
trait seemed excessive. Especially when one of the uses is going away
shortly and the other is straightforward to replace with code that
already exists (that same `AccountContract` extension trait.)
> refactor: move single-use utilities away from `TrieUpdate`

- chain/chunks/src/chunk_cache.rs
- chain/chunks/src/metrics.rs
previous buckets were too large for small average values of close to 1ms
> chore: smaller buckets for chunk reconstructibility

- chain/chain/src/runtime/mod.rs
- chain/client/src/chunk_producer.rs
- core/store/src/trie/shard_tries.rs
- core/store/src/trie/update.rs
- runtime/runtime/src/lib.rs
More spans for viewing things in traviz.
Tx preparation:
* `prepare_transactions`
Chunk application stages:
* apply
* `TrieUpdate::finalize`
* process_transactions
* validate_apply_state_update
Also `apply_memtrie_changes`
I might be abusing the `block_production` tag a bit. I'm using it as a marker for "I want this to be collected in benchmark spans". Maybe we could consider `tag_traviz` for spans that should be exported for traviz analysis?
> feat(tracing): more spans

- nearcore/src/config.rs
> fix: Get rid of `NETWORK_LEGACY_TELEMETRY_URL`

- chain/chain/src/resharding/manager.rs
- core/store/src/archive/cold_storage.rs
- core/store/src/trie/mod.rs
- tools/database/src/commands.rs
- tools/database/src/memtrie.rs
Cherry-Pick #14185
This is a recovery tool for the data loss that happened during the recent reshardings. As the resharding implementation does not store any TrieChanges, the trie nodes inserted during resharding are never moved to the cold storage. Once the garbage collection removes those nodes they are lost and the archival node cannot serve some queries for some range of blocks after resharding.
This tool replays the resharding, extracts the TrieChanges and stores them directly into the cold db.
The check-only option allows checking if the trie is whole. 
This is not a fix to the original problem that caused the data loss, that will follow separately.
> fix(resharding) - recovery tool for resharding archival data loss (#14185)

- core/store/src/config.rs
- core/store/src/db/rocksdb.rs
This PR add the possibility to override RocksDB settings.
There are a few key requirements I wanted to enforce:
- the config is totally optional
- operators can override a single parameter (like `{ "cf_medium_load_overrides": { "max_write_buffer_number": 12 } }`
- the default config is the same as what we use in master
- columns config can be customized per category (all columns are split into high, medium, low "heaviness")
- adding a new config option in the code and forgetting to use it must trigger a compiler warning
Common RocksDB settings are defined through constants, while column presets (and overrides) are defined with a macro.
> config: expose option to override rocksdb configuration

- chain/chain/src/garbage_collection.rs
- chain/client/src/sync/state/shard.rs
- core/store/src/columns.rs
Prior to this change it's possible for state parts to be re-applied if state sync is interrupted at that stage.
This PR introduces a new DB column to track which state parts are applied to avoid this issue.
Additionally, it will avoid deleting the flat storage if any parts are applied and avoid recreating the flat storage if it was already completed.
https://github.com/near/nearcore/issues/14032
> feat(sync): avoid reapplying state parts

- chain/chain/src/runtime/mod.rs
- runtime/runtime/src/verifier.rs
Unfortunately the throughput (with or without rayon) turned out to be within the error margin, so I chose to only keep mild refactors that are obviously reducing the work done:
* Only load access key and account once per group (which is grouped by account + access key);
* This isn't particularly useful in the benchmark where most groups have just one transaction each, but should help other workloads;
* Don't bother committing or rolling back the `TrieUpdate`;
* This was necessary in the past, but now `verify_and_charge_tx_ephemeral` only modifies the passed in account and access key if the transaction verifies (these TrieUpdate operations were relatively prominent in the profiles.)
> perf: optimize storage accesses during tx preparation

- chain/client/src/archive/cold_store_actor.rs
- chain/client/src/gc_actor.rs
- chain/epoch-manager/src/shard_tracker.rs
- chain/jsonrpc/openapi/openapi.json
- core/chain-configs/src/client_config.rs
- core/chain-configs/src/lib.rs
- core/store/src/archive/cloud_storage.rs
- core/store/src/config.rs
- core/store/src/node_storage/mod.rs
- core/store/src/node_storage/opener.rs
- genesis-tools/genesis-populate/src/main.rs
- nearcore/benches/store.rs
- nearcore/src/config.rs
- nearcore/src/config_validate.rs
- nearcore/src/lib.rs
- runtime/runtime-params-estimator/src/main.rs
- test-utils/store-validator/src/main.rs
- tools/cold-store/src/cli.rs
- tools/database/src/adjust_database.rs
- tools/database/src/analyze_high_load.rs
- tools/database/src/set_version.rs
- tools/database/src/write_to_db.rs
- tools/flat-storage/src/commands.rs
- tools/mirror/src/lib.rs
- tools/mock-node/src/setup.rs
- tools/replay-archive/src/replaydb.rs
- tools/speedy_sync/src/main.rs
- tools/state-viewer/src/cli.rs
- tools/state-viewer/src/replay_headers.rs
- tools/undo-block/src/cli.rs
Changes:
- Introduce `CloudArchivalReaderConfig` and `CloudArchivalWriterConfig` configs with validation.
- Minor refactor and cleanup.
This PR prepares the ground for introducing the cloud archival loop, which will save blobs to a bucket.
**Note**: Config validation tests will come in a separate PR.
> feat(cloud_archival): `CloudArchivalConfig`

- benchmarks/sharded-bm/cases/base_config_patch.json
- chain/client/src/client.rs
- core/chain-configs/src/client_config.rs
- core/primitives/src/sharding.rs
- nearcore/src/config.rs
We don't strictly need to store `PartialChunks` parts if we don't track a shard in benchmarks. 
- Parts are in the memory cache anyway (for a while); CP keeps them for 3 epochs
- This reduces write pressure by a good 20%
- Leaked `PartialChunks` are less "impactful"
- Add config option to disable persisting chunk parts, active only in benchmarks
It turns out we still need receipts and `PartialChunks` header .. so the workaround is to avoid storing the parts which are the biggest contributor to size.
This makes the GC+compaction combo work as expected. Also less write pressure in general on the disk
> perf: config to disable saving untracked partial chunks parts

- core/async/src/test_loop/mod.rs
When tests fail it results in panic and it's expected that in that case test loop wouldn't be shutdown properly. Extra panic creates noise and makes it harder to see the actual test failure so this PR avoids panic on testloop drop when we are already panicking which makes failed test output much easier to read.
> fix: test-loop: panic less on failed tests.

- chain/jsonrpc/openapi/openapi.json
Adds the new optional configuration option to OpenAPI spec to keep CI green.
> openapi: adds save_untracked_partial_chunks_parts (nonbreaking)

- chain/jsonrpc/openapi/openapi.json
- core/primitives/src/views.rs
This pull request makes improvements to the handling of deprecated fields `rent_paid` and `validator_reward` in both the Rust data structures and the OpenAPI specification. The main goal is to ensure these fields default to zero when not present, improving backward compatibility and API clarity.
**Rust struct improvements:**
* Added `default` attribute to the `rent_paid` and `validator_reward` fields in both `BlockHeaderView` and `ChunkHeaderView`, ensuring they default to zero if missing during deserialization. [[1]](diffhunk://#diff-1e4fc99d32e48420a9bd37050fa1412758cba37825851edea40cbdfcab406944L911-R915) [[2]](diffhunk://#diff-1e4fc99d32e48420a9bd37050fa1412758cba37825851edea40cbdfcab406944L1094-R1098)
**OpenAPI specification updates:**
* Added `"default": "0"` to the `rent_paid` and …
> add serde(default) for deprecated  fields

- pytest/tests/mocknet/locust.py
replaced `args.funding_key` with the `filename` argument inside `upload_key`.
`args` isn’t available in this scope, so it would raise a `NameError`.
since the function is already called with the proper path, referencing `filename` directly fixes the issue.
> fix: NameError in `upload_key` by using correct parameter

- Cargo.lock
- Cargo.toml
- chain/chain/src/tests/simple_chain.rs
- chain/jsonrpc/openapi/openapi.json
- core/primitives-core/src/version.rs
- core/primitives/src/transaction.rs
- integration-tests/src/tests/standard_cases/mod.rs
- runtime/runtime/Cargo.toml
- runtime/runtime/src/lib.rs
- runtime/runtime/src/tests/apply.rs
- runtime/runtime/src/types.rs
Transactions that fail validation were dropped previously and now the outcome will be registered in the `state_change` with the `Failed` status.
- Extracted the single transaction processing into a function making sure that every transaction generates an outcome (apart from `RuntimeError` cases that result in chunk being dropped)
- added the Protocol feature to include every outcome into the `state_change` instead of quietly dropping the transactions that failed validation.
- added new error to signal the overflow when calculating the total gas burnt by the chunk. This one I am not really sure about. This may not be actionable by the party generating the transaction and the case may be better handled by throwing `RuntimeError` and dropping the chunk as the transaction gas usage alone has …
> create outcome for each transaction in the processed chunk

- core/primitives/src/receipt.rs
- pytest/lib/cluster.py
- pytest/tests/contracts/deploy_call_global_smart_contract.py
- pytest/tests/contracts/deploy_call_smart_contract.py
Sleeping an arbitrary amount is prone to fail due to small timing changes.
This change also picks up some assorted improvements that reduce log spam or make configuration patches not explode pytest when given dicts for initially non-dict values.
> refactor: use send_tx_and_wait in `deploy_call_*_contract` tests

- chain/network/src/peer_manager/tests/accounts_data.rs
We observed this test failing in CI with the following error:
```
thread 'tokio-runtime-worker' panicked at chain/network/src/peer_manager/peer_manager_actor.rs:272:29:
failed to start listening on server_addr=[::1]:31971 e=Os { code: 98, kind: AddrInUse, message: "Address already in use" }
```
During the test a node is stopped by dropping the PeerManagerActor, after which it is started again:
https://github.com/near/nearcore/blob/6d64f5e99181fd263d7bf9f6ccb5fdb8b7b63fda/chain/network/src/peer_manager/tests/accounts_data.rs#L311-L316
In a local environment I could reproduce the `AddrInUse` error by binding a TcpListener to the node's addr immediately after `drop(pm0)`. This happens because the TcpListener created by the peer manager is owned by a background task and it takes time to …
> fix: flaky validator_node_restart

- pytest/tests/mocknet/helpers/load_test_utils.py
`self.function_call_state = [[]] * len(self.test_accounts)` was causing all test accounts to share the same list, which led to unexpected side effects. now each account gets its own independent list, so updates to one won’t affect the others.
> chore: fix shared reference issue in test account initialization

- chain/network/Cargo.toml
Restores ability to `cargo build` or `cargo nextest run` on just the network crate.
> fix: network crate test_util dependency

- runtime/runtime/src/actions.rs
- runtime/runtime/src/deterministic_account_id.rs
- test-loop-tests/src/tests/deterministic_account_id.rs
It's an explicit feature in NEP-616  to allow sending a Transfer to a deterministic account id first, already creating the account but not allowing it to be called, yet.
This fixes a crucial bug in the pre-initialization creation, where the deposit was not deposit and just vanished instead.
`test_deterministic_state_init_prepay_for_storage` checks that the described feature works as expected and that the sent funds arrive at the receiver.
> fix(det-accounts): store deposit in pre-initialization

- runtime/near-vm-runner/src/logic/logic.rs
- runtime/near-vm-runner/src/logic/tests/promises.rs
We can't use key_len and value_len because they can be u64::MAX to reference a register instead of a memory pointer.
> fix(det-accounts): set_state_init_data_entry bytes calculation

- chain/chain/src/chain.rs
- chain/chain/src/sharding.rs
- chain/chain/src/stateless_validation/chunk_validation.rs
- chain/chain/src/stateless_validation/spice_chunk_validation.rs
- chain/client/src/chunk_executor_actor.rs
- chain/client/src/client_actor.rs
- core/primitives-core/src/version.rs
- runtime/runtime/src/verifier.rs
- tools/replay-archive/src/cli.rs
Mainnet is at protocol version 80, which means we can deprecate features before this.
> [limited_replayability] Deprecate features GlobalContracts, BlockHeightForReceiptId, ProduceOptimisticBlock

- runtime/near-vm-runner/src/wasmtime_runner/logic.rs
Silly me forgot to apply the fix from #14386 to the wasmtime host function implementation.
> fix(det-accounts): wasmtime_runner logic.rs

- benchmarks/sharded-bm/cases/forknet/20-shards/tx-generator-settings.json
- benchmarks/sharded-bm/cases/forknet/4-shards/tx-generator-settings.json
- benchmarks/transactions-generator/src/lib.rs
- core/primitives/src/views.rs
- use block time to measure BPS. Previously the block request time was used, which resulted in the noisy rate
- if we do not get new blocks for longer than 3s stop updating the rate and pause pushing new transactions
- adjust the averaging window and p-gain for 4- and 20- shards runs. The BPS is rock-solid. TPS still fluctuates quite a lot in the second half of the run.
+ [4-shards](https://grafana.nearone.org/d/deg7e0doxn30gf/blockchain-performance?orgId=1&from=2025-10-06T16:00:40.000Z&to=2025-10-06T17:32:12.000Z&timezone=utc&var-chain_id=$__all&var-role=$__all&var-node_type=$__all&var-node_id=.%2Abenchmark-.%2A&var-shard_id=$__all&refresh=10s)
+ [20-shards](https://grafana.nearone.org/d/deg7e0doxn30gf/blockchain-performance?orgId=1&from=2025-10-06T14:44:11.000Z&to=2025-10-06T15:54:44.000 …
> [benchmark] use the block time to measure bps
