near/nearcore

core/primitives/Cargo.toml

cargo t -p near-vm-runner currently fails because we don't properly
specify the feature we use.

chore: unbreak builds on master

---

Makefile

We used to use near-vm-runner-standalone as a way to run contracts
locally, but that never worked properly, as the standalone runner can't
perfectly recreate proper blockchain environment. Today, the task of
running a contract "locally" is solved by a sandbox node
https://github.com/near/sandbox
We still keep the code in the repo, as it is sometimes useful for ad-hoc
investigations by contract runtime team. We just forgot to remove it
from releases, which we should have done ages ago.

chore: don't include near-vm-runner-standalone in release artifacts

---

chain/network/benches/routing_table_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/edge.rs
chain/network/src/routing/edge_verifier_actor.rs
chain/network/src/routing/ibf_peer_set.rs
chain/network/src/routing/routing.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/tests/cache_edges.rs

`EdgeInfo` is used in a lot of places in our code. We should remove `pub` modifier from all it's attributes.
Splitting https://github.com/near/nearcore/pull/5267 due to some unknown bug.

REFACTOR Make all attributes in `EdgeInfo` private

---

integration-tests/tests/network/routing.rs

Due to recent changes bin `near-networking`, where we moves Routing Table calculation to another thread. This action is no longer synchronous.
I added extra checks to make sure that the routing table is correct.
I saw in the output logs that the routing failed. I want to figure out whenever that was due to routing table not being updated properly on all nodes, or for some other reason.
I caused failing CI, and therefore we were unable to do a merge.
For example: https://buildkite.com/nearprotocol/nearcore/builds/6774#c2582722-b8ab-49e0-8ee1-0c98fdca9b85

FEATURE: Add extra checks to ping_jump test

---

chain/network/src/lib.rs
chain/network/src/peer_manager/mod.rs
chain/network/src/peer_manager/peer_store.rs
test-utils/state-viewer/src/commands.rs

`peer_store.rs` is right now public. It will be cleaner to make it `pub(crate)` instead.

REFACTOR Make PeerStore package private

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/edge.rs
chain/network/src/routing/routing_table_actor.rs

`key` and `nonce` attributes of `Edge` have `pub` modifier. We are going to remove `pub` modifier to make internal structure of `Edge` private. This will be used in the future, to change `Edge` internal representation to make `PeerManager`, `RoutingTableActor` more efficient.
For example, we could make Edge use `Arc<PeerId>` to remove duplicates of signatures, thus reducing size of `Edge` and improving efficiency.
Or change key to use `Arc<PeerId, PeerId>`, etc. This would remove having to store duplicates of key, in a few hashmaps like `edges_info`, and ones used for `IBF` algorithm.

REFACTOR Remove unused method from Edge struct

---

CODEOWNERS

Make @mm-near code owners of 
```
/core
/neard
/nearcore
```
I noticed that Marcin is not a code owner in a few places. Changes like https://github.com/near/nearcore/pull/5237 require approval from  @bowenwang1996 and @mm-near

Make @mm-near code owners of  /core /neard /nearcore

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/mod.rs

peer_manager.rs is not used from outside. It should be marked with `pub(crate)` instead of `pub`.

REFACTOR Make peer_manager.rs pub(crate) instead of pub

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/codec.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/stats/metrics.rs
integration-tests/tests/network/peer_handshake.rs

Current implementation of metrics in `chain/network/src/stats/metrics.rs` can be done better.
As discussed in https://github.com/near/nearcore/pull/5240
I replaced usage of `Lazy<near_metrics::Result<IntCounter>> ` with simply `Lazy<IntCounter>`.
This will make code much cleaner, and we will notice whenever there is an issue with name conflict between two different metrics in Prometheus while running CI, rather than finding out later that something doesn't work as it should.

refactor: Stop using near_metrics::Result<IntCounter>

---

chain/network/benches/routing_table_actor.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/peer_store.rs
chain/network/src/routing/codec.rs
chain/network/src/routing/route_back_cache.rs
chain/network/src/routing/routing.rs
chain/network/src/types.rs
rustfmt.toml
utils/near-performance-metrics/src/actix_enabled.rs
utils/near-performance-metrics/src/stats_enabled.rs
utils/near-rate-limiter/src/lib.rs

Let's group imports together in `near-network`. This was done with running rustfmt with 'imports_granuality = "Module"' in `rustfmt.toml`.
Command used:
`rustfmt +nightly *.rs`

refactor: Reorganize imports in near-network

---

integration-tests/tests/network/runner.rs

In `PeerActor` we have a logic which is used to drop duplicated messages if they happen within `50`ms. That constant used to be higher while the change was originally implemented.
```
/// Duplicated messages will be dropped if routed through the same peer multiple times.
pub const DROP_DUPLICATED_MESSAGES_PERIOD: Duration = Duration::from_millis(50);
```
In `network/routing.rs` tests we use structs `StateMachine` to test PR. The check coincidentally runs every `50ms`, which is sometimes too fast, sometimes too slow for the logic to drop duplicated messages to work.
The fix is to change constant inside testes from `50ms` to `1ms`.
Closes #5322

bug: fix `network/routing.rs` tests

---

chain/network/src/routing/route_back_cache.rs
chain/network/src/routing/routing.rs
core/store/src/db.rs

We should make core more readable by moving `RouteBackCache` related constants inside `route_back_cache.rs`.

refactor: Add Default and move constants to route_back_cache.rs

---

tools/indexer/example/src/configs.rs

Current `neard` binary implement `--help` option, while `tools/inder/example` doesn't.
Let's add `--help` to `tools/indexer/example`.

Add help to `tools/indexer/example`

---

tools/indexer/example/src/configs.rs

Logging to stdout for `info!` doesn't work for indexer.
`indexer-example=info,` is missing from `pub(crate) fn init_logging() {`

feature: Add logging in indexer to stdout

---

chain/network/src/peer/codec.rs
chain/network/src/peer/mod.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/mod.rs

`codes.rs` doesn't make much sense to be in `near-network/src/routing`. `Codec` is used to create `PeerActor` by `PeerActorManager`. Therefore it's only used by those two places.

refactor: Move codes.rs in the same module as peer_actor.rs

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/edge.rs
chain/network/src/routing/mod.rs
chain/network/src/routing/routing.rs
chain/network/src/routing/routing_table_actor.rs
t_shard_layout_upgrade_cross_contract_call

After looking through the code, It will make more sense for `EdgeType` to be together with `Edge` and `SimpleEdge` rather than in `routing.rs`.

refactor: Move EdgeType to edges.rs

---

runtime/near-vm-runner/src/wasmer2_runner.rs

With the change of the gas measurement implementation we want to also
evict all the old cached contracts. Bumping the version here does so.

Bump Wasmer2 VM configuration version

---

Cargo.lock
utils/near-rate-limiter/Cargo.toml

Let's remove unused  `slab`  dependency for `near-rate-limiter`

refactor: Remove slab from near-rate-limiter dependencies

---

Cargo.lock
chain/network/Cargo.toml

Remove unused dependency:
- `near-chain-configs = { path = "../../core/chain-configs" }`

Remove unused dependencies for near-network

---

integration-tests/tests/network/runner.rs

Currently it's hard to debug why tests in `runner.rs` are failing. Let's print the command, so we see which one failed.

refactor: Add debug logs to runner.rs

---

core/primitives/src/network.rs

There is a compile error when trying to compile our code using Fuzz.
Anyway, we can remove `AnnounceAccountRouteHeader` and make our code cleaner. That structure was only created, so that we can use `BorshSerializer` on it to get hash, it's not longer anyder. 
Closes #5386
Tested fix locally with 
```
cd test-utils/runtime-tester/fuzz/
env RUSTC_BOOTSTRAP=1 'cargo' 'fuzz' 'run' 'runtime-fuzzer' '--' '-len_control=0' '-prefer_small=0' '-max_len=4000000' '-rss_limit_mb=10240'
```
TODO:

bug: Fix for `fuzz` not compiling `core/primitives/src/network.rs`

---

chain/jsonrpc/jsonrpc-tests/src/lib.rs
chain/network/src/test_utils.rs

`test_utils.rs` currently has code code that's under `test_features` feature. It's better to split the code into two parts.

refactor: Split `test_utils.rs` to avoid having code with `test_features` and without in one file.

---

utils/near-rate-limiter/Cargo.toml

`near-rate-limiter`, introduced in https://github.com/near/nearcore/pull/4927, should be a private crate.

chore: mark near-rate-limiter unpublishable

---

utils/near-rate-limiter/Cargo.toml

`near-rate-limiter`, while compilable as a dependency of `near-network`, is not compilable in isolation due to missing features.
```console
$ cargo check -p near-rate-limiter
Compiling near-rate-limiter v0.0.0 (/git/near/nearcore/utils/near-rate-limiter)
error[E0432]: unresolved import `tokio_util::codec`
--> utils/near-rate-limiter/src/framed_read.rs:13:17
|
13 | use tokio_util::codec::Decoder;
|                 ^^^^^ could not find `codec` in `tokio_util`
```

fix: near-rate-limter build

---

Cargo.lock
core/primitives-core/Cargo.toml
core/primitives/Cargo.toml

Remove unused dependencies
`primitives-core`:
- `hex = "0.4"`
- `lazy_static = "1.4"`
`primitives-core`:
- `regex = "1"`
- `validator = "0.12"`

Remove unused dependencies from core

---

Cargo.lock
core/account-id/Cargo.toml
core/account-id/src/lib.rs
core/crypto/Cargo.toml
core/crypto/src/signature.rs
core/crypto/src/vrf.rs
core/primitives-core/Cargo.toml
core/primitives-core/src/account.rs
core/primitives-core/src/hash.rs
core/primitives/Cargo.toml
core/primitives/src/block.rs
core/primitives/src/block_header.rs
core/primitives/src/challenge.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/errors.rs
core/primitives/src/merkle.rs
core/primitives/src/network.rs
core/primitives/src/rand.rs
core/primitives/src/receipt.rs
core/primitives/src/sharding.rs
core/primitives/src/sharding/shard_chunk_header_inner.rs
core/primitives/src/syncing.rs
core/primitives/src/transaction.rs
core/primitives/src/types.rs
core/primitives/src/version.rs
core/primitives/src/views.rs
runtime/near-vm-errors/Cargo.toml
runtime/near-vm-errors/src/lib.rs

We would like to use `deepsize` crate and `DeepSizeof` derive in our code. In discussed that it's better not to add extra dependencies to our code base if possible. That's useful for external projects using `core/primitives`.
Here is a proposal on how to include `deepsize`/`DeepSizeOf` inside our repo as optional dependency.
We could do it this the same way for other dependencies like, for example:
```
use serde::{Deserialize, Serialize};
use borsh::{BorshDeserialize, BorshSerialize};
```
@frol I hope this solves your concerns. @matklad Can you take a look?

feat: Make `deepsize` import and `DeepSizeOf` derive optional 

---

chain/network/src/peer/codec.rs
chain/network/src/peer/peer_actor.rs

We can make code cleaner, by inlining two methods in `codes.rs`
```
pub(crate) fn peer_message_to_bytes(peer_message: &PeerMessage) -> Result<Vec<u8>, std::io::Error> {
peer_message.try_to_vec()
}
pub(crate) fn bytes_to_peer_message(bytes: &[u8]) -> Result<PeerMessage, std::io::Error> {
PeerMessage::try_from_slice(bytes)
}
```

re: inline methods in codes.rs

---

docs/style.md

Document whether we should do
```rust
use near_store::{ColPeers, Store};
use std::collections::HashMap;
use std::net::SocketAddr;
```
or 
```rust
use std::collections::HashMap;
use std::net::SocketAddr;
use near_store::{ColPeers, Store};
```
This PR currently documents both suggested guidelines, and we'll use this PR to decide which one we pick. 
Decision procedure: if you don't care about the style, ignore this PR, and just note the final decision :) Otherwise, react with :+1: for proposal A or proposal B (do read the actual proposals in the changset). Feel free to leave a comment explaining your choice.
If there's a clear consensus around one option, we'll just pick it. Otherwise, @bowenwang1996 makes the final call or delegates the decision to make the final call.

docs: document consistent import style

---

chain/network/src/lib.rs

Let's write `lib.rs`, in us a way, that internal crates are addressed with `crate::` prefix.
This should make it easier to see, which exports are internal, and which are external.

re: Refactor `near-network/lib.rs`

---

chain/network/src/peer/codec.rs
chain/network/src/peer_manager/peer_manager_actor.rs

In an ongoing effort to improve code readability, I propose we
- Use `default` rather than `new` for `Coded`
- remove `max_length` from attribute list of `Codec`.  We don't use/plan to modify it through constructor. If we ever do, well, we will refactor the code, but that's unlikely.
- switch constant `MAX_CAPACITY` to proper type. It defines used to define capacity of a buffer, which is returned as `usize` - we avoid extra casting from u64 to usize.
- Add comments to constants.

Document `near-network::peer::code::Codec`  and make it's constr default

---

nightly/pytest-sanity.txt
pytest/lib/cluster.py
pytest/tests/sanity/restart.py
pytest/tests/sanity/rpc_finality.py
pytest/tests/sanity/sync_chunks_from_archival.py

- restart.py -- had a flaky assumption that after startup, the current head is <= 2 (probably used to work when our node creation a lot faster)
- rpc_finality - inside the code, it started 3 nodes, killed one of them and tried making the transaction, that didn't succeed. AFAIK you need now to have more than 2/3 of the stake for the chain to approve it. So I've changed number of nodes to 4.
- sync_chunks_from_archival - was checking that the data was read from the hardcoded archival node id (for example, that first 10 blocks would be read from 2, next 10 blocks from 3 etc) - AFAIK we don't enforce this in the code - so I've updated the test to verify that each block is requested from either node.

test: fixing 3 nayduck tests

---

pytest/lib/cluster.py

We are tests timeout often in `get_status`. Let's increase timeout from `2s` to `4s`.
This is blocking CI in production.

Increase timeout for `get_status` to `4s` from `2s`

---

chain/network/src/peer/codec.rs

`peer_id_type_field_len` is a method that gets size of binary presentation of `PeerId`, by looking at it's first byte.

Figure out what `peer_id_type_field_len` method in `near-network`...`codec.rs` does

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/types.rs
chain/network/tests/cache_edges.rs

Currently, `PeerManager` is responsible to sending edges to check their signatures `EdgeVerifierActor`.
Then `PeerManager` runs `broadcast_edges_trigger` trigger, which is time consuming.
And then `PeerManager` sends edges to `RoutingTableActor`.
This has a few issues:
- `PeerManager` is spends a bit of time running  `broadcast_edges_trigger`.
- There is an extra structure in `EdgeVerifierActor` which leaks memory and can be removed
- `PeerManager` doesn't care about the edges by itself. This adds extra complexity in the logic.
In the current design:
We create `RoutingTableActor` first then `PeerManagerActor` We pass `Addr<RoutingTableActor>` to `PeerManagerActor`, and we keep references to for both.
- `RoutingTableActor` create `EdgeVerifierActor` and also talks to ` RoutingTableActor`. …

feat: Move `EdgeVerifierActor` inside `RoutingTableActor`

---

nightly/pytest-sanity.txt

state_sync2 and state_sync_late tests are consistently failing.
Remove them from nightly run while working on a fix.

nightly: disable consistently failing tests

---

runtime/near-vm-runner/src/prepare.rs
runtime/near-vm-runner/src/tests/compile_errors.rs

We've noticed that if we validate functions number just after initialization, it speeds up the contract processing.
Also we want to do this before release, because number of functions computed **before** and **after** the change is actually different. I'm working on the repro.
- existing tests,
- adjust `test_limit_contract_functions_number` so that it checks precise limit now.

fix: validate functions number after initialization

---

chain/jsonrpc/fuzz/Cargo.lock
chain/jsonrpc/fuzz/Cargo.toml
chain/jsonrpc/fuzz/fuzz_targets/fuzz_target_1.rs

‘static ref’ is not a valid Rust syntax instead used by `lazy_static`
crate.  Replace the syntax by use of the `once_cell` crate.  This
fixes the following build failure:
$ cd ./chain/jsonrpc/fuzz
$ RUSTC_BOOTSTRAP=1 cargo fuzz run fuzz_target_1
⋮
Compiling near-jsonrpc-fuzz v0.0.0 (/home/mpn/code/near/nearcore/chain/jsonrpc/fuzz)
error: expected identifier, found keyword `ref`
--> fuzz_targets/fuzz_target_1.rs:140:12
|
140 |     static ref RUNTIME: std::sync::Mutex<tokio::runtime::Runtime> = {
|            ^^^ expected identifier, found keyword

chain: fix build of `chain/jsonrpc/fuzz`

---

chain/network-primitives/src/types.rs
chain/network/src/peer/codec.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/edge.rs
chain/network/src/routing/routing.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/types.rs
docs/style.md

We should improve code quality by removing conditional imports.
There are a few issues with conditional imports:
-  high maintenance  cost - modifying code under conditional flags, requires manually adding #[cfg(feature=)] for each import. Rust plugin for Intellij doesn't support them well.
- readability - this makes code more readable, it's good to see what's being imported when to feature flags are used. 
- fragility CI - I've seen a lot cases, where I submit PR, only to find out, something didn't compile with some subset of features.

re: Stop using conditional imports in `near-network`

---

chain/network/src/peer/codec.rs
chain/network/src/peer/peer_actor.rs
docs/style.md

There is a 500 lines `handle` method in `PeerActor`. We should add comments to it and try to split it.
Reasons:
- Currently too much is going on in this method. It will be much easier to read the code, by splitting parts of it into independent functions. This has to be done in parts. Analyzing what each part does it time consuming.
- As a good rule of thumb: method names alone should be descriptive of what the method does.
`handle` is too generic.
- We have a lot of weird logic here. It needs to be double checked at documented.

re: First part of splitting 500 lines long method in `near-network::PeerActor`

---

chain/chain/src/tests/gc.rs
chain/chain/src/tests/mod.rs
nightly/expensive.txt

First of all, add ‘gc’ to the ‘tests’ module since it was omitted and
thus completely ignored.
Second of all, since now all the tests are compiled into a single
binary, update executable name in the nightly configuration file.
Issue: https://github.com/near/nearcore/issues/5371

chain: fix nightly expensive tests after tests move to /src/tests

---

nearcore/Cargo.toml
nearcore/src/config.rs

We are already using tempfile crate in other parts of the code so
use it in download_file as well rather than having an arguably less
safe way of creating temporary files (i.e. blindly using predefined
extension).
Issue: https://github.com/near/nearcore/issues/4951

nearcore: use tempfile to create temporary files when downloading

---

chain/chain/src/tests/doomslug.rs
chain/chain/src/tests/gc.rs
chain/chain/src/tests/mod.rs
chain/client/src/tests/catching_up.rs
chain/client/src/tests/consensus.rs
chain/client/src/tests/cross_shard_tx.rs
chain/client/src/tests/mod.rs
nightly/expensive.txt

After moving tests from `/tests` to `/src/tests` and thus bringing
them all into a single executable with a single namespace we ended up
with aesthetically unpleasing nested paths such as:
tests::catching_up::tests::test_chunk_grieving
Flatten the structure by removing the inner `tests` module.
Issue: https://github.com/near/nearcore/issues/5371

chain: remove nested `tests` modules

---

pytest/lib/branches.py
pytest/tests/sanity/backward_compatible.py
pytest/tests/sanity/db_migration.py
pytest/tests/sanity/state_migration.py
pytest/tests/sanity/upgradable.py

Use latest_release and latest_deploy data stored on S3 rather than
relying on GitHub releases to figure out what is the latest binary run
on mainnet for performing A/B tests.
This fixes issues around release time when our CI suddenly breaks when
a new rc is made without it yet being released on either testnet or
mainnet.
For example, once 1.42.0-rc1 is release on GitHub, the code expects to
download a 1.42.0 binary from S3 regardless of whether such release
has been deployed or not.  With this change, the code will look at the
actual executable that is running in production on mainnet.
This also makes sure that all our tests are performed against what is
running on mainnet so that we can confirm that upgrading from mainnet
to current HEAD is possible.
Fixes: …

pytest: make A/B tests against latest deployed mainnet binary

---

chain/network/src/peer_manager/peer_manager_actor.rs

Adding a value to `active_peer.full_peer_info.chain_info.height`  could potentially cause an overflow error. It's better to use saturating add.
Refactor afterwards: https://github.com/near/nearcore/pull/5524

fix: `PeerActorManager`: Remove hidden overflows

---

Cargo.lock
runtime/near-vm-runner/Cargo.toml

This contains the `VecAssembler` changes which should improve the
performance of compiling a contract significantly.

Update wasmer-near to 2.1.0

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/types.rs

In the current design. `PeerManagerActor`` is responsible for maintaining list of all connected peers.
Whenever `PeerActor` receives `Handshake` from other node. It notifies `PeerManagerActor` to add given `PeerActor` to list of all active connections.
Currently, that message is called `Consolidate`. `Consolidate` can have multiple meanings. Let's change it's name to `RegisterPeer` message. 
And also response that `PeerManagerActor` sends to `PeerActor`, about whenever registration was successful from `ConsolidateResponse` to `RegisterPeerResponse`.
This should make it easier to explain the process of `Handshake` negotiation inside https://github.com/near/nearcore/issues/5156.

re: `near-network` Rename `Consolidate` to `RegisterPeer`

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/types.rs

`ValidateEdgeList` doesn't have documentation. It will be easier to explain what it does once we add it.
That's useful for https://github.com/near/nearcore/issues/5156

re: Add documentation to `near-network::ValidateEdgeList`

---

pytest/lib/proxy.py

The behaviour of `proxy.bridge` has been changed in recent commit such
that reading header always reads four bytes making it such that empty
read was never possible.  Previously, the loop in `bridge` function
would stop if empty read happened.
This change broke `sanity/proxy_restart.py` and `stress/stress.py 3 3
3 0 staking transactions node_restart packets_drop` tests.
Make empty reads when reading header possible again to fix the tests.

pytest: allow empty header reads in `proxy.bridge`

---

Cargo.lock
core/primitives/Cargo.toml

We are not using the following dependencies in `near-primitives`:
```
bs58 = "0.4"
base64 = "0.13"
```

re: Remove unused dependencies from `near-primitives`

---

chain/network/src/common/message_wrapper.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/types.rs
utils/near-rate-limiter/src/framed_read.rs

We want to track count and sizes of messages arriving from `PeerActor`, while they  travel to `PeerManagerActor`, and then to `RoutingTableActor`.
This PR extends message tracking per peer, while they travel through `actix` `InBox` system.
Continuation of https://github.com/near/nearcore/pull/5198
TODO:

feat: Propagate `ActixMessageWrapper` between `PeerManagerActor` and `RoutingTableActor`

---

core/account-id/Cargo.toml
core/account-id/README.md
core/account-id/fuzz/Cargo.lock
core/account-id/fuzz/README.md
core/account-id/src/error.rs
core/account-id/src/errors.rs
core/account-id/src/lib.rs
runtime/near-vm-logic/src/logic.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/config.rs

Exhaustively documents `near-account-id` including fuzz tests and refactors the API a bit.
What's different on the API?:
- `AccountId::is_implicit` is now a method on an already validated `AccountId`, no longer an associated method.
```rust
// before
AccountId::is_implicit("6bf3a4a59f8a23edc2fb96a94fc14be697353f49f3ec49b02a4764a5648fa4a5");
// after
"6bf3a4a59f8a23edc2fb96a94fc14be697353f49f3ec49b02a4764a5648fa4a5"
.parse::<AccountId>()?
.is_implicit();
```
cc @mm-near

re+doc(account-id): refactor and fully document near-account-id

---

core/crypto/src/signature.rs

Copy trait is not needed by `Secp256K1PublicKey` nor `ED25519PublicKey`.

feat: Remove `Copy` traits from `core/crypto/src/signature.rs`.

---

pytest/lib/cluster.py

This fixes the following warning when trying to run tests with
unittest fixture:
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/mpn/.near/test0/stdout' mode='a' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/mpn/.near/test0/stderr' mode='a' encoding='UTF-8'>
Issue: https://github.com/near/nearcore/issues/3186

pytest: close stdout and stderr when local node is cleaned up

---

chain/jsonrpc/src/lib.rs

We are in the middle of trying to figure out where `near-network` type belong, whenever they should be in `near-network` or `near-network-primitives` crate.
First, we should cleanup imports mess inside `jsonrpc::lib`, which is related to `near-network`, before proceeding further.

re: Use qualified imports in `jsonrpc::lib`

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/edge.rs

Let's change `Edge::partial_verify` signature, to pass arguments as reference.

re: `near-network`: Remove `clone()` from `Edge::partial_verify`

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/edge.rs
chain/network/src/routing/mod.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/tests/cache_edges.rs

Add documentation to `EdgeType`/`EdgeState`. I'm proposing to rename `EdgeType` to `EdgeState` in order to make code more understandable.
It's easier to think about edges, by saying that each edge is in one of the two states. Starts in `Active` state, and it's state can change from `Removed` to `Active`, and vice-versa, each type increasing `nonce` by exactly 1.
Also, it's worth renaming `Added` to `Active`. Term "active state` is more self descriptive.

re: Rename `EdgeType` to `EdgeState` in `near-network`

---

pytest/lib/cluster.py

Commit ‘close stdout and stderr when local node is cleaned up’ removed
`stdout_name` and `stderr_name` fields from the LocalNode object but
as it turns out utils.LogTracker uses the latter.  In effect, that
change caused tests which use LogTracker to start failing at the
following:
File "/datadrive/nearcore/pytest/lib/utils.py", line 77, in __init__
self.fname = node.stderr_name
AttributeError: 'LocalNode' object has no attribute 'stderr_name'
Fix the issue by bringing the two fields back to LocalNode class.

pytest: fix failure with tests that use LogTracker

---

Cargo.lock
utils/near-cache/Cargo.toml

`near-cache`, introduced in #5259, should be a private crate.
Context: this fixes CI on master - https://buildkite.com/nearprotocol/nearcore-release/builds/1381#b7c93adf-148e-4fa3-970d-8043a58a81a7

chore: mark near-cache unpublishable

---

chain/rosetta-rpc/src/adapters/mod.rs
chain/rosetta-rpc/src/lib.rs
chain/rosetta-rpc/src/models.rs

Currently /construction/hash and /construction/submit APIs return
transaction identifiers where hash is simply the hash of the
transaction.  This does not match identifier returned by Data API
which prefixes the hashes with a ‘tx:’ (to distinguish them from
Rosetta transaction created as a result of other NEAR changes).
Introduce constructors for models::TransactionIdentifier and use them
throughout the code to make sure all places agree how the identifiers
are formatted.
Issue: https://github.com/near/nearcore/issues/5173

chain: rosetta: fix make Construction and Data APIs ids match

---

integration-tests/tests/nearcore/stake_nodes.rs

New version of Rust `1.57.0` improved checking for unused code. (see https://github.com/near/nearcore/pull/5659). This causes a warnings in tests code. Let's remove the warnings from `tests/nearcore/state_nodes.rs`.
```
warning: field is never read: `arbiters`
--> integration-tests/tests/nearcore/stake_nodes.rs:37:5
|
37 |     arbiters: Vec<ArbiterHandle>,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```

re: Remove unused code from `tests/nearcore/state_nodes.rs`

---

chain/rosetta-rpc/src/adapters/mod.rs
chain/rosetta-rpc/src/adapters/validated_operations/mod.rs
chain/rosetta-rpc/src/errors.rs
chain/rosetta-rpc/src/utils.rs

This saves a few kestrokes and I hear defining one’s own Result is
quite rustic.

chain: rosetta: introduce errors::Result type alias

---

chain/chain/src/chain.rs
chain/chunks/src/lib.rs
nearcore/src/runtime/mod.rs

We can improve code quality by  replacing `or_insert_with(|| vec![])` with `or_default()`
See https://github.com/near/nearcore/pull/5571

Re: Replace `or_insert_with(|| vec![])` with `or_default()`

---

chain/rosetta-rpc/src/adapters/mod.rs

Move code that maps state change cause into Rosetta transaction
identifier into a separate function.  This causes no observable
behaviour change.  The `convert_block_changes_to_transactions`
function is long as is and this attempts to mitigate it a little.

chain: rosetta: small refactor; add `convert_cause_to_transaction_id`

---

core/account-id/src/errors.rs
core/account-id/src/lib.rs

Merges into https://github.com/near/nearcore/pull/5660
Context: https://github.com/near/nearcore/pull/5660#discussion_r762553344
Wonder if it's useful to highlight which character and at what index was responsible for the error.. Something like;
`InvalidChar(2, 'ƒ')` from `tiƒƒany..near`
`RedundantSeparator(0, '_')` from `_root.near`
But, of course, when matching, you can discard that data with `RedundantSeparator(..)`.
- `fmt::Display` + `borsh`:
- `invalid value: "alice.", the Account ID has a redundant separator '.' at index 5`
- `serde`:
- `invalid value: "alice.", the Account ID has a redundant separator '.' at index 5 at line 4 column 9`

feat: hint the position of invalidation for an Account ID

---

docs/network.md

-  Routing table computation
See https://github.com/near/nearcore/issues/5156

doc: Add `near-network` reference level documentation `Routing table computation`

---

chain/network/src/peer_manager/peer_manager_actor.rs

While debugging test failures I noticed that `let listener = listener.unwrap();` can sometimes panic.
Let's improve error handling in `PeerManagerActor`.

re: PeerManagerActor Make exceptions readable when TcpSocket::bind unwrap panics

---

docs/network.md

-  Message routing
See https://github.com/near/nearcore/issues/5156

doc: Add `near-network` reference level documentation `Message routing`

---

chain/chain/src/chain.rs
chain/chain/src/doomslug.rs
chain/chain/src/store.rs
chain/chain/src/store_validator.rs
chain/chain/src/tests/challenges.rs
chain/chain/src/tests/gc.rs

Fix 'clippy::redundant-clone' clippy warnings in `near-chain`.
See https://github.com/near/nearcore/pull/5571

`near-chain`: Fix `clippy::redundant-clone` issues.

---

core/crypto/src/signature.rs

`use Trait as _` is a standard Rust idiom -- it allows calling trait's
methods without bringing the trait itself in scope. This is useful to
avoid naming conflicts, which is exactly what happens in this case
(there's a `Signature` struct defined in this file).
We *could* `as _` the other two crates as well, but we don't as:
a) we don't have an active name conflict for them
b) more than one `_` confuses CLion: https://github.com/intellij-rust/intellij-rust/issues/8143
Notes:
Rust naming convention suggests using verbs as trait names, which helps
with dodging similar conflicts.

refactor: minimize work-around

---

test-utils/state-viewer/README.md
test-utils/state-viewer/src/apply_chain_range.rs
test-utils/state-viewer/src/cli.rs
test-utils/state-viewer/src/commands.rs

Add improved logging of history playback and switch allowing to ignore all transactions but ones related to contracts with
--only-contracts CLI switch.
Also allow playback for cases where database was migrated and so outcome varies in versions.
This way we hope to have improved playback performance, although still to playback the whole mainnet history of 40M blocks with current performance of 7-10 blocks per second would take ~2 months.

Improve history playback functionalty

---

core/store/src/trie/trie_storage.rs

Increase trie cache size to mitigate receipts undercharging issue.
We can increase cache size to 50_000, so the theoretical occupied size is 50_000 * 4 (num_shards) * 4_000 = 800 MB.
In reality, `/usr/bin/time -v ` shows **520 -> 1070 MB** RAM growth which seem to be caused by https://github.com/near/nearcore/pull/5212. This change have an impact like 30 MB.
I've additionally checked that cache is full on my runs.
On the sample of 30 receipts we considered, we have the following characteristics:
```
default settings: summary time = 3.3s, avg undercharging = 101
increase state cache size: summary time = 0.67s, avg undercharging = 21
increase state cache size + trie cache size = 50k: summary time = 0.5s, avg undercharging = 11.5
increase state cache size + trie cache size = 100k + reduce …
```

fix: increase trie cache size

---

integration-tests/tests/network/routing.rs

Let's ignore failing `archival_node` test for now.

bug: Ignore `archival_node` test

---

Cargo.lock
chain/network/src/common/mod.rs
chain/network/src/lib.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_actor.rs
utils/near-rate-limiter/Cargo.toml
utils/near-rate-limiter/src/framed_read.rs
utils/near-rate-limiter/src/lib.rs
utils/near-rate-limiter/src/message_wrapper.rs

We want to use `near-rate-limiter` across multiple crates. That implies, that we would have to use `ActixMessageWrapper` across mujltiple crates. However, `ActixMessageWrapper` currently is located in `near-network`. And we don't want other crates, to be directly importing from `near-network`.
I propose, we move `ActixMessageWrapper` to the same crate as `ThrottledFramedReader`, that is inside ` near-rate-limiter`.
Both `ActixMessageWrapper`, `ThrottledFramedReader` are meant to be used together, and it makes sense for them to be together.
Later, we may consider moving `near-rate-limiter`, to a new place. However, it's hard to say exactly where. 
Anyway, moving those two structs together, is definitely a good change. Let's do it now.
This is required for the next step. The plan will be …

fe: Move `ActixMessageWrapper` from `near-network` to `near-rate-limiter`

---

.buildkite/pipeline.yml

There are a few ways to specify logging level to `cargo test`.
We are currently using `RUSTFLAGS='-D warnings' cargo test`, which passes flags directly to rustc.
Let's switch to using `RUST_LOG=WARN` instead.
See https://docs.rs/env_logger/latest/env_logger/

re: Use `RUST_LOG=WARN` inside `pipeline.yml`

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing.rs

We can make a few code simplifications in `RoutingTableView`.
We currently only keep local edges in `local_edges_info`, once of peers is `my_peer_id`, so there is no need to store a pair anymore.
We can change signature of `local_edges_info`
```
pub local_edges_info: HashMap<(PeerId, PeerId), Edge>,
```
to
```
pub local_edges_info: HashMap<PeerId, Edge>,
```

re: `near-network`: Rewrite `local_edge_info` in `RoutingTableView`

---

docs/network.md

-  Adding new edges to routing tables.
See https://github.com/near/nearcore/issues/5156

doc: Add `near-network` reference level documentation `Adding new edges to routing tables`

---

chain/network/src/lib.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/test_utils.rs
integration-tests/tests/network/peer_handshake.rs
integration-tests/tests/network/runner.rs

We can further isolate `near-network` by:
- making `crate::routing` available only for `test_features` only
- making `crate::stats` only available pub(crate) only
- making `PeerActorMessages` pub(crate) only
`near-network` still exports the following to outside world:
- `PeerManaagerActor`
- `PeerManagerActor` related messages
- some borsh serializable messages (split between `near-network`, `near-network-primitives`)
Doesn't for
- `PeerActor`
- `RoutingTableActor`
- `EdgeValidatorActor`
`near-network-primitives`
- `ClientActor`related messages
- `ViewClientActor`related messages
- some borsh serializable messages (split between `near-network`, `near-network-primitives`)

re: `near-network` Limit visibility of types outside of crate

---

chain/client-primitives/src/types.rs
chain/client/src/client_actor.rs
chain/client/src/info.rs
chain/client/src/test_utils.rs
chain/jsonrpc-primitives/src/types/network_info.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/types.rs
chain/rosetta-rpc/src/lib.rs
integration-tests/tests/client/process_blocks.rs
integration-tests/tests/network/infinite_loop.rs
integration-tests/tests/network/peer_handshake.rs
integration-tests/tests/network/runner.rs
integration-tests/tests/network/stress_network.rs

Change terminology used in `near-network` to be more accurate.
Currently we use `active peer` terminology to mean `connected peer`.
Unfortunately, that term is not self explanatory and leads to some confussion.
See #5424
Blocked by #5515

re: Rename active peer to connected peer terminology in `near-network`

---

chain/chain/src/chain.rs
chain/chain/src/store_validator.rs
chain/chain/src/test_utils.rs
chain/chain/src/tests/simple_chain.rs
chain/chunks/src/lib.rs

Fix `KeyValueRuntime` to take epoch length as parameter. It caused some bugs with epochs with different length then 5
Replace direct call of Utc::now with Clock::utc() so it can be mocked in tests

Pass epoch length in tests setup

---

core/account-id/src/errors.rs
core/account-id/src/lib.rs

Based on https://github.com/near/nearcore/pull/5581. 
Previously, `ParseErrorKind::Invalid` was returned as the error kind for four parsing cases:
- either the ID started with a separator (`.a`)
- ended with one (`b.`)
- had separators following each other in quick succession (`a..b`)
- or had invalid characters (caps, symbols, or spaces).
We can and should split those up. Context: https://github.com/near/nearcore/pull/5575#discussion_r762530320
This resolves to having these two variants:
- `RedundantSeparator`: for IDs starting or ending with separators, as well as for separators following each other consecutively.
- `InvalidChar`: for non-lowercase, non-alphanumeric characters. (caps, symbols, or spaces).

feat: more descriptive `AccountId` error kinds

---

chain/client/src/client_actor.rs
chain/jsonrpc/src/lib.rs
chain/network-primitives/src/types.rs
chain/network/src/types.rs

Move `SandboxResonse` from `near-network` to `near-network-primivites`.
Current `NetworkSandboxMessage` is inside `near-network-primitives`, while `NetworkSandboxResponse` is in `near-network`.
Let's put those two together.
```
#[cfg(feature = "sandbox")]
#[derive(Debug)]
pub enum NetworkSandboxMessage {
SandboxPatchState(Vec<near_primitives::state_record::StateRecord>),
SandboxPatchStateStatus,
}
```

re: Move `SandboxResponse` from `near-network` to `near-network-primivites`

---

core/store/src/trie/trie_storage.rs
runtime/near-vm-logic/src/dependencies.rs
runtime/near-vm-logic/src/logic.rs
runtime/near-vm-logic/src/mocks/mock_external.rs
runtime/runtime/src/ext.rs
runtime/runtime/src/lib.rs

We need to track touched nodes quite frequently, this should simplify debugging.
Also disable `ext.reset_touched_nodes_counter()` on `VMLogic` creation. It should not affect the result because only counter differences matter, but it made counter harder to debug.
Existing tests.

feat: trace node counter on receipt processing

---

scripts/test_nearlib.sh

Yarn test keeps failing.
Let's disable it for now. This has been happening for a while.
Here is another failure.
https://buildkite.com/nearprotocol/nearcore/builds/9750#834c14d9-c161-45c7-b4e1-4acae3b92a13
My proposal is to move "yarn test" to nayduck.

re: Disable yarn test

---

chain/network/src/peer_manager/peer_manager_actor.rs
utils/near-rate-limiter/src/framed_read.rs

Continuation of https://github.com/near/nearcore/pull/5455
We are in progress of determining, what are the safe ranges of limit thresholds to set for `ThrottleController`.
`num_messages_in_progress` is part of `ThrottleController`. It's associated with given `PeerActor`. I tracks the number of messages which are currently in progress of being processed.
I added stats, which help us track, what was the maximum value of `num_messages_in_progress` across all peers over period of 1m. This will help us setup the liimits.

feat: Add bandwidth stats to `PeerManagerActor` pt2

---

Cargo.lock
chain/jsonrpc-primitives/src/types/network_info.rs
chain/network-primitives/Cargo.toml
chain/network-primitives/src/types.rs
chain/network/src/routing/routing.rs

We are planning to separate `jsonrpc` types from rest of the code base. We can start by separating types from `near-network-primitives` from `jsonrpc` by removing direct usage of `serde` from that crate.
See https://github.com/near/nearcore/issues/5516
TODO: (next PR)
- Fix database memory leak.

re: Remove usage of `serde` from `near-network-primitives`

---

docs/network.md

- Code flow - finding first peer to connect to.
- Edges & network - in code representation
-  Code flow - connecting to a peer - handshake
See https://github.com/near/NEPs/pull/274 for full PR

doc: Add `near-network` reference level documentation `Handshake`

---

utils/near-cache/Cargo.toml

Tracking issue: https://github.com/near/nearcore/issues/5763
All crates must explicitly specify a Minimum Supported Rust Version.
Resolves:
```console
(i) These packages should specify a Minimum Supported Rust Version (MSRV):
• near-cache v0.0.0 (utils/near-cache/Cargo.toml)
```

chore(compliance): specify a MSRV for all crates

---

scripts/waitonserver.sh

We are missing a check whenever `NEAR_PID` is defined in `scripts/test_nearlib.sh`.
It's better to add those checks ahead of the time, that will make debugging easier in case an issue happens.

re: Improve handling errors in `scripts/test_nearlib.sh`.

---

chain/network/src/types.rs
runtime/near-vm-runner-standalone/src/main.rs
rust-toolchain.toml

Rust `1.57.0` has been announced https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html
Perhaps. we should consider upgrading at some point.
Related PR's:
- #5663 
- #5674 
- #5675 
`1.57.0` introduces `panic! in const contexts`.
```
panic! in const contexts
With previous versions of Rust, the panic! macro was not usable in const fn and other compile-time contexts. Now, this has been stabilized. Together with the stabilization of panic!, several other standard library APIs are now usable in const, such as assert!.
This stabilization does not yet include the full formatting infrastructure, so the panic! macro must be called with either a static string (panic!("...")), or with a single &str interpolated value (panic!("{}", a)) which must be used with {} (no format specifiers or other …
```

feat: upgrade rust `1.57.0`

---

runtime/near-vm-errors/src/lib.rs

I am looking into finally untangling vm errors and removing all
serialization concerns from the VM layer. While doing that, I've noticed
that we can easily drop the two serializes.
Test Plan
---------
Drops unused code, so `cargo check`

refactor: drop unused serializes from some errors

---

.buildkite/pipeline.yml
runtime/near-vm-runner/src/imports.rs

After giving it some thought, I think https://github.com/near/nearcore/pull/5723 should be reverted.

Revert #5723

---

runtime/runtime-params-estimator/test-contract/build.sh

The scripts runs a couple of dangerous commands (such as `rm -rf`) with
relative directory arguments. This can result in an unintended data
loss. Make sure the script has $PWD set to an expected location before
doing anything else.

refactor: test contract build script $PWD agnostic

---

test-utils/state-viewer/src/cli.rs

Show a help message if `neard view_state` is called withouta subcommand.

---

chain/network/src/routing/network_protocol.rs

Add `debug_assert` to `Edge::build_hash`.
We make an assumption when calling `build_hash`, it's safe to add an assert.

Add `debug_assert` to `Edge::build_hash`

---

chain/network/src/types.rs

Let's remove currently unused  `GetRoutingTable` from `near-network::types`.
TODO:

re: `near-network` Remove unused `GetRoutingTable ` type

---

chain/jsonrpc-adversarial-primitives/src/lib.rs
chain/jsonrpc/src/lib.rs
chain/network/benches/routing_table_actor.rs
chain/network/src/lib.rs
chain/network/src/network_protocol.rs
chain/network/src/peer/codec.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/peer_store.rs
chain/network/src/private_actix.rs
chain/network/src/routing/edge_validator_actor.rs
chain/network/src/routing/ibf_peer_set.rs
chain/network/src/routing/ibf_set.rs
chain/network/src/routing/mod.rs
chain/network/src/routing/routing.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/test_utils.rs
chain/network/src/types.rs

In order to more clearly define the public interface of `near-network`. 
We should move all actix messages, that are meat to be used only within the `near-network` to a separate `private_actix.rs` file.

re: `near-network` Split private actix types of out `types.rs`

---

chain/network/src/network_protocol.rs
chain/network/src/peer/codec.rs
chain/network/src/peer/peer_actor.rs
core/primitives/src/version.rs

We haven't bumped minimum required version for more than a year, since 2020/10/01.
Let's upgrade minimum protocol version from `34` to `39`. This will allow us to drop deprecated code in `HandshakeV2`.
The current stable version used is '49`.
Follow up:

feat: increase `OLDEST_PROTOCOL_VERSION`  from `34` to `LATEST - 1`

---

chain/jsonrpc-adversarial-primitives/src/lib.rs
chain/network-primitives/src/types.rs
chain/network/src/routing/network_protocol.rs
core/account-id/src/lib.rs
core/crypto/src/signature.rs
core/primitives-core/src/account.rs
core/primitives-core/src/hash.rs
core/primitives/src/block.rs
core/primitives/src/block_header.rs
core/primitives/src/challenge.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/errors.rs
core/primitives/src/merkle.rs
core/primitives/src/network.rs
core/primitives/src/rand.rs
core/primitives/src/receipt.rs
core/primitives/src/sharding.rs
core/primitives/src/sharding/shard_chunk_header_inner.rs
core/primitives/src/syncing.rs
core/primitives/src/transaction.rs
core/primitives/src/types.rs
core/primitives/src/version.rs
core/primitives/src/views.rs
runtime/near-vm-errors/src/lib.rs

Let's make deepsize imports qualified.
This will avoid adding following the following header:
```
#[cfg(feature = "deepsize_feature")]
use deepsize::DeepSizeOf;
```

re: Make `deepsize` a qualified import

---

chain/network/benches/routing_table_actor.rs

Due to recent changes. `chain/network/benches/routing_table_actor.rs` started crashing while `RoutingTableActor` due to the fact, that now it starts `EdgeValidatorActor` and `actix` System has not been running.

Fix crash in `near-network` benches

---

chain/network-primitives/src/types.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing.rs

`neard` binary reads a `client config` which contains `max_num_peers` peers parameter.
Internally `near-network` disallows having higher number of peers than `128`. 
It's a good idea to add this error to `CLI` directly in `verify()` method of `NetworkConfig`.

feat: `near` Print an error if the number of `peers` specified in config is higher than allowed.

---

chain/network-primitives/src/types.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/peer_store.rs

`find_peers` is used to sample connected peers. It can be written in a more efficient way:
- avoiding cloning whole array, when less elements than max are requested
- splitting `filter_map` to `filter` and `map`.

re: `PeerManager`: Refactor`find_peers` 

---

chain/network/benches/graph.rs
chain/network/src/routing/routing.rs

We can rewrite `compute_result` to be written in a more functional style.
This will improve performance by 50%.

re: Rewrite `compute_result` in `near-network::Graph`

---

utils/near-rate-limiter/src/framed_read.rs

`ReadFrame`'s `poll_next` method can be written in a shorter, cleaner way.
There is no reason why not to do it.
This is a response to https://github.com/near/nearcore/pull/5758#discussion_r768648859

Write `poll_next` in a cleaner way

---

Cargo.lock
deny.toml
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/wasmer2_runner.rs

This includes a merge of upstream 2.1.0 version, which among other
benefits now checks the required CPU features by itself, has support for
Windows, and other assorted fixes.

Wasmer upgrade (to fork's 2.1.2)

---

pytest/lib/cluster.py
pytest/tests/sanity/rosetta.py

We've been experiencing random test failures of `upgradable.py` see https://github.com/near/nearcore/pull/5524
'query' jsonrpc return an 'account' information, or an error json response, in case account is not found.
Let's start by printing the full response, this will allow us to see what the issue is.

fix: Add debug logs to `upgradable.py` in case of failure.

---

chain/network/src/peer_manager/peer_manager_actor.rs
docs/architecture.md
integration-tests/tests/network/runner.rs

We stater using structured (key/value) logging that tracing provides, but there's more than one way to use it. Let's document our preferred style (the simplest one, and the one advertised by the upstream docs).

docs: document structural logging style

---

chain/network/src/peer_manager/peer_manager_actor.rs

It looks like we were not using `unwrap_or_error` correctly.
If an error within `monitor_peers_trigger` where to happen, the node would stop connecting to new peers. That issues was obfuscated by usage of   `unwrap_or_error` macro.

bug: Remove `unwrap_or_error!` from `near-network`

---

nightly/expensive.txt

Commit d3efd9942: ‘Move testbs for `integration-tests` from `/tests`
to `/src/test`’ moved tests around affecting their path but did not
correctly update nightly list with the correct test paths.  Fix that.

nightly: fix expensive integration tests after test move

---

chain/indexer/src/streamer/mod.rs

Micro-optimisation creating a vector using `collect` iterator method
rather than pushing in a loop.  The former can use size hints to
figure out size of the vector.

chain: indexer: avoid vector reallocation

---

chain/indexer/src/streamer/mod.rs

Rather than storing base58 hashes of problematic blocks store
`CryptoHash` objects.  This avoids base58→string conversion each time
the `PROBLEMATIC_BLOKS` array is read.

chain: indexer: avoid base58→string conversion

---

chain/indexer/src/streamer/fetchers.rs
chain/indexer/src/streamer/mod.rs

In the two places where `fetch_chunks` function is called, it is used
to fetch chunks for a block.  By moving code which extracts list of
chunk hashes from a block view into the `fetch_chunks` function we
reduce code duplication and eliminate an allocation of a temporary
vector object.
To better describe what the function does, rename it to
`fetch_block_chunks`.

chain: indexer: avoid allocation of temporary vector

---

pytest/lib/utils.py
pytest/tests/stress/stress.py

The tests use logging which writes to standard error so making
standard output unbuffered doesn’t do anything.  Furthermore, there is
no reason to make test’s output unbuffered.

pytest: remove `utils.Unbuffered`

---

core/primitives/src/version.rs

Recently we changed `PEER_MIN_ALLOWED_PROTOCOL_VERSION` to `MAIN_NET_PROTOCOL_VERSION - 1`.
However, that can lead to situation, where the version on the master branch is 2 versions behind the version running on the mainnet. 
This PR resolved the issue by changing  `PEER_MIN_ALLOWED_PROTOCOL_VERSION` to `MAIN_NET_PROTOCOL_VERSION - 2`.
Closes #5853

Change `PEER_MIN_ALLOWED_PROTOCOL_VERSION` to `MAIN_NET_PROTOCOL_VERSION - 2`

---

integration-tests/src/node/mod.rs
integration-tests/src/node/process_node.rs
integration-tests/src/node/thread_node.rs
integration-tests/src/test_helpers.rs
integration-tests/src/user/mod.rs
integration-tests/src/user/rpc_user.rs
integration-tests/src/user/runtime_user.rs
test-utils/store-validator/src/main.rs
tools/restaked/src/main.rs
tools/restored-receipts-verifier/src/main.rs

There are still a few `clippy` warnings that need to be fixed in `integration-tests`.

re: Fix remaining `clippy` warnings in `intergration-tests`

---

runtime/near-vm-runner/src/lib.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests/rs_contract.rs
runtime/near-vm-runner/src/wasmer_runner.rs

Let's group imports properly in `near-vm-runner`.

re: Group imports in `near-vm-runner`

---

CODEOWNERS
tools/themis/Cargo.toml
tools/themis/src/main.rs
tools/themis/src/rules.rs
tools/themis/src/style.rs
tools/themis/src/types.rs
tools/themis/src/utils.rs

Context: https://github.com/near/nearcore/pull/5724#discussion_r766659405
cc. @matklad
Thanks for the cleanup hints @matklad
```console
(i) These packages have an incompatible `rust-version`: [expected: <=1.57.0, as defined in the `rust-toolchain`]
• near-cache v0.0.0 (utils/near-cache/Cargo.toml) [found: 1.58.0]
```
```console
(i) These packages have an incompatible `rust-version`: [expected: <=1.57.0, as defined in the `rust-toolchain`]
↳ utils/near-cache/Cargo.toml (found: 1.58.0)
```

refactor(themis): dyn error handling case analysis

---

chain/chain/src/tests/simple_chain.rs
chain/epoch_manager/src/validator_selection.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/version.rs
integration-tests/tests/client/challenges.rs
nearcore/res/genesis_config.json

Hotfix to address #5688
While all chunk producers are block producers we should use same validator to produce chunks that would later produce block out of them, to avoid network delays

Synchronize block and chunk production

---

chain/network-primitives/src/types.rs
chain/network/src/network_protocol.rs
chain/network/src/peer_manager/peer_store.rs

We can replace `match` with `matches!` in `near-network`
Why is this bad?
- Readability and needless complexity.
See https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro

re: Improve `near-network` code quality with `matches!`

---

CODEOWNERS

I added `/utils` a while back. We have code there that's used in production, and it's better to make sure I review all changes to it.

Update code owners for `/utils`

---

chain/network-primitives/README.md
chain/network-primitives/src/lib.rs
chain/network-primitives/src/network_protocol.rs
chain/network-primitives/src/types.rs

Our goal is to make `near-network` more readable.
We have a network protocol, which defines how nodes communicate between each other. However, the types which belong to the protocol and mixed up with types that do not.
By moving types related to network protocol from `near-network-primitives::types.rs`, to `network_protocol.rs`  gives us a few advantages:
-  Easier for anyone not familiar with `near-network`, which code belongs to network protocol.
-  Whenever, anyone makes changes to network protocol file, we need to review, whenever they don't break the network protocol, and whenever migration is needed.
- By splitting types into groups, that form logical connection to each other, we can make sure our network protocol doesn't change, as long as there are no changes to network protocol …

`near-network-primitives`: Move network protocol files to `network_protocol.rs`

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/peer_store.rs
chain/network/src/routing/edge_validator_actor.rs
chain/network/src/routing/mod.rs
chain/network/src/routing/routing.rs
chain/network/src/routing/routing_table_actor.rs

Fixed:
- Use slice instead of `Vec`, as a function argument
- `compute_result` doesn't need mutable reference.
- use of `or_insert` followed by a function call

re: Fix clippy warnings in near-network

---

chain/network/src/peer_manager/peer_manager_actor.rs

We should improve readability of messages printed by `PeerManagerActor` in order to make debugging easier.
This will require more changes, but using `tracings` format of messages is a good start.

re: Change formatting of messages in `PeerManager` to use `tracing`

---

pytest/lib/utils.py

The existing code for handling Google Cloud nodes in `LogTracker` is
obviously wrong (uses `logger` which is not imported and does not quote
`pattern`) so just get rid of it.  We are not using remote nodes and
the feature is bitrotting.  No point in keeping obviously-wrong code
around.

pytest: remove `GCloudNode` support from `utils.LogTracker`

---

genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs
integration-tests/src/tests/nearcore/node_cluster.rs
nearcore/src/config.rs
nearcore/src/migrations.rs
test-utils/runtime-tester/src/fuzzing.rs
tools/restored-receipts-verifier/src/main.rs

Taking `&String` argument limits how function can be used without
providing any additional features.  Specifically, when caller has
a string slice they have to make unnecessary conversion to String
before passing it to the function.
Similarly, returning `&String` doesn’t offer benefits over returning
`&str` since there’s nothing that can be done with the former that
cannot be done with the latter as well.
As such, prefer using `&str` instead of `&String`.

Prefer `&str` to `&String`

---

runtime/near-vm-runner/src/imports.rs

We received feedback that near_vm_runner produces too much output couple
of times. At the same time, there was once instance where having a log
line for something as trivial `read_register` was useful.
So, let's downgrade the logging here to trace for now, and maybe revisit
in the future when we have a clearer understanding of which amount of
logs is acceptable.

fix: don't log host functions by default

---

core/primitives/src/errors.rs
runtime/near-vm-errors/src/lib.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmer_runner.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/ext.rs

vm-logic is "generic" over External implementation. We don't want
however to literally add a type parameter to it, so we use `dyn
External`. This creates a problem that, when a particular external
fails, we need to report the error, but we don't know error's concrete
types. So let's use `Box<dyn Any>` for that, and a bit of down-casting.
The previous impl did roughly equivalent thing, but via
serialize/deserialize route, which is more complicated than what we need
here.
As a result, we eliminate a couple of BorshSerializes and clones.

refactor: don't abuse serialization for type erasure

---

chain/rosetta-rpc/src/adapters/mod.rs
core/primitives-core/src/hash.rs
core/primitives/src/shard_layout.rs
core/primitives/src/utils.rs
core/store/src/trie/mod.rs
test-utils/state-viewer/src/commands.rs

We can remove `impl TryFrom<Vec<u8>>` for `CryptoHash`
This will remove extra memory allocations and make code shorter.

Remove `From<Vec<u8>>` for `CryptoHash`

---

scripts/test_nearlib.sh

`scripts/test_nearlib.sh` currently doesn't work on localhost.
Before, we fix `yarn test`, let's make this script work from any directory.
See #5757

re: Make `test_nearlib.sh` work from any directory

---

pytest/lib/utils.py

Commit 24667dbd4: ‘remove GCloudNode support from utils.LogTracker’
introduced an unconditional `raise NotImplementedError` statement to
LogTracker.__init__ method which causes all tests using LogTracker to
fail.  While fixing that also fix variable names in check and count
methods.

pytest: fix LogTracker implementation broken after cleanup

---

chain/epoch_manager/src/shard_assignment.rs

Commit 15c648c4c2: ‘remove unnecessary ShardId redefinition’
introduced `shard_pos` variable in `assign_with_possible_repeats`
function but failed to properly update it when necessary.  This lead
to incorrect vector index being used when accessing result vector
elements.  Fix that.

chain: fix ‘remove unnecessary ShardId redefinition’ commit

---

chain/epoch_manager/src/shard_assignment.rs

Introduce a test case which demonstrates a failure in the code.
Upcoming changes will fix the issue.
Issue: https://github.com/near/nearcore/issues/5932

chain: demonstrate failure in `assign_shards` function

---

chain/network-primitives/src/types.rs
chain/network/src/peer/peer_actor.rs

`PeerStatus`, which is currently in `near-network-primitives`, is only used by `PeerActor`. 
For that reason, we should move it to `near-network`, in the same file as `PeerActor`.

re: `near-network` Move `PeerStatus` near `PeerActor`

---

core/crypto/src/signature.rs
test-utils/runtime-tester/src/scenario_builder.rs

Fix clippy::redundant_closure'   issue

re: Fix clippy::redundant_closure'   

---

Cargo.lock
runtime/runtime-params-estimator/Cargo.toml
runtime/runtime-params-estimator/src/config.rs
runtime/runtime-params-estimator/src/cost.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/estimator_params.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_cost.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/main.rs
runtime/runtime-params-estimator/src/qemu.rs
runtime/runtime-params-estimator/src/transaction_builder.rs
runtime/runtime-params-estimator/src/vm_estimator.rs

- Change function interfaces to use Gas as a common unit
- Integrate CPU benchmark used to estimate x86 op cost
- Integrate gas metering estimation
- Preparation for more general estimation cases to be added
- Remove unused code

refactor: Generalize parameter estimator 

---

CODEOWNERS

Test contracts is something transaction runtime might want to use as
well, so it makes sense to make ownership more cross-team.

chore: add Longarithm to test-contract owners

---

chain/chain/src/store.rs

First of all, the `mut_store()` call is not necessary and instead
`store()` is sufficient.
Secend of all, `store_update().store()` is just a convoluted way to
get to the `Store` from a `ChainStore`.  The same can be achieved by
calling `store()` directly on `ChainStore` object.

chain: simplify `.mut_store().store_update().store().store_update()`

---

chain/chain/src/store.rs

Commit 3179d756: ‘fix block ordinal computation’ broke the tests which
wasn’t caught immediately by CI because it’s an expensive test and
those are only run nightly.
Fix the test the same way `test_clear_old_data_fixed_height` was fixed
in the aforementioned commit.

fix(chain): fix `test_clear_old_data_too_many_heights` test

---

test-utils/logger/src/lib.rs

Change logger to print output of `cargo test` correctly.
https://github.com/near/nearcore/issues/4490#issuecomment-1007554120

feat: Print cargo test output only on error.

---

nearcore/src/config.rs

This was missed, but https://github.com/near/nearcore/pull/5967 did
not interact very well with `enum FileDownloadError`, so this is an
attempt to fix that, and present better error messages.
The reason for getting rid of the #[from] in the HttpError variant is
that it doesn't really play nicely with the anyhow {:#} formatter and
gives us ugliness like:
ERROR neard::cli: Failed to initialize configs: Failed to download the config file from http://localhost:8002/config.json: error trying to connect: tcp connect error: Connection refused (os error 111): tcp connect error: Connection refused (os error 111): Connection refused (os error 111)
Test Plan:
Of course check that downloading the file still works, but also inject
errors and make sure the error messages look ok. For reviewer …

fix(error messages): fix error messages when downloading the config

---

integration-tests/Cargo.toml
integration-tests/src/tests/nearcore/sync_state_nodes.rs
integration-tests/src/tests/test_catchup.rs
integration-tests/src/tests/test_tps_regression.rs
nightly/expensive.txt

Firstly, the proper way to denote a test as expensive is to use
`#[cfg]` directive before its definition rather than adding a return
inside of the function.  The latter will cause the test to show up in
list of tests and always pass giving people false sense that running
the test without `expensive_tests` feature actually does something.
After fixing `sync_state_nodes_multishard` also add it to nightly run.
Secondly, the `check_nightly.py` script is rather crude and the order
in which `#[cfg]` and `#[test]` attributes are applied do matter.
With `#[test]` being first, the script failed to recognise
`test_catchup` as an expensive test.
Thirdly, the `check_nightly.py` script also doesn’t understand
`#[cfg]` matching multiple features.  Because of that it does not
detect `test_highload` as …

integration-tests: fix some expensive tests marking

---

Cargo.lock
runtime/near-vm-runner-standalone/src/script.rs
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
runtime/near-vm-runner/src/cache.rs
runtime/near-vm-runner/src/imports.rs
runtime/near-vm-runner/src/preload.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/tests/contract_preload.rs
runtime/near-vm-runner/src/tests/rs_contract.rs
runtime/near-vm-runner/src/tests/ts_contract.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/vm_estimator.rs

This is intended to be a non-functional change.
Here we replace the use of the `wasmer` crate and the wrappers it
provides with the lower level APIs exposed by various wasmer subcrates
such as `wasmer-engine`, `wasmer-vm`, etc.
These changes are primarily intended to reduce the burden of maintaining
and publishing the `wasmer-near` crate. Since our requirements for a
runtime are scoped to very narrow portion of what the `wasmer` crate
provides, the complexity of the code in `nearcore` didn't
change as much as I feared it would, while also making certain portions
of the codebase significantly more straightforward.
The `imports`-related code is perhaps the highest gain in complexity of
the code, as it has become necessary to take care of ensuring a matching
ABI. On the other hand, the …

refactor: use the lower level wasmer APIs

---

runtime/near-vm-runner-standalone/src/script.rs
runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/tests/contract_preload.rs
runtime/near-vm-runner/src/tests/rs_contract.rs
runtime/near-vm-runner/src/tests/ts_contract.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmer_runner.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/vm_estimator.rs

Conceptually this matches what is happening somewhat better – VM is
constructed as configured in some specific way and then can be used to
run multiple contracts or somesuch, as long as the configuration
matches.
This kind of construction can help, in the future, to reuse more state
between contract invocations. Since `VMConfig` doesn't change within the
same run of `neard` typically, we could reuse the same memory map to
hold the contract code and cache the allocation of the working memory as
well (so long as we clear it between contract invocations), thus saving
on page faults and similar cost centres.

refactor: Runtime structure now contains VMConfig

---

Cargo.lock
runtime/near-vm-runner-standalone/src/script.rs
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
runtime/near-vm-runner/src/cache.rs
runtime/near-vm-runner/src/imports.rs
runtime/near-vm-runner/src/preload.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/tests/contract_preload.rs
runtime/near-vm-runner/src/tests/rs_contract.rs
runtime/near-vm-runner/src/tests/ts_contract.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmer_runner.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/vm_estimator.rs

It broke betanet. The breakage is related to the memory sizes, wherein we trigger the first assert in [this section of code](https://github.com/near/wasmer/blob/68da83cfb903ae14093b84cc041048cd0f21e48b/lib/engine/src/resolver.rs#L242-L275)
Looks like there is a contract that is attempting to import 65536 pages worth of memory whereas our limits config specifies a 2048 maximum. Presumably the preparation code should standardize these sizes, so not sure how the larger numbers end up reaching wasmer.
Reverting to give us time to investigate.

Revert the changes to use low level wasmer2 implementation

---

core/store/Cargo.toml

This has been temporarily removed from Cargo.toml to wait for
a rocksdb release (see #3835)
Test plan
---------
Running existing store tests but with --features single_thread_rocksdb

feat: Reintroduce single_thread_rocksdb

---

Cargo.lock
runtime/near-vm-runner-standalone/src/script.rs
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
runtime/near-vm-runner/src/cache.rs
runtime/near-vm-runner/src/imports.rs
runtime/near-vm-runner/src/preload.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/tests/contract_preload.rs
runtime/near-vm-runner/src/tests/rs_contract.rs
runtime/near-vm-runner/src/tests/ts_contract.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmer_runner.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/vm_estimator.rs

This reverts commit 353b4b4aa3c5955460e89d8ab7c654d61d29201d.

re: restore the low level wasmer2 refactor

---

runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/vm_estimator.rs

No estimations should be run as tests in CI.
The binary module in runtime-params-estimator is used to run estimations

test: Remove params-estimator tests

---

Cargo.lock
core/primitives-core/src/config.rs
core/primitives/res/runtime_configs/50.json
core/primitives/src/runtime/config_store.rs
core/primitives/src/version.rs
deny.toml
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/prepare.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/compile_errors.rs
runtime/near-vm-runner/src/tests/runtime_errors.rs

This forward-ports the change from 1.23.1
We upgrade our version of pwasm-utils -- the old one severely
undercounted stack usage in some cases. As this is a protocol change, we
keep the old implementation around
Test Plan
=========
* added test for stack overflow behavior for the bad case
* added test for protocol upgrade related to stack overflow
* fuzzed new pwasm utils implementation locally, confirmed that it only
differs for calls which stack overflow

fix: use pwasm-utils 0.18 for more correct stack accounting

---

chain/network/src/peer_manager/peer_manager_actor.rs
utils/near-rate-limiter/README.md
utils/near-rate-limiter/src/framed_read.rs
utils/near-rate-limiter/src/lib.rs

I noticed some code quality issues with `ThrottledFramedRead`
Done:
- renamed `ThrottledFrameRead` to `ThrottledFramedRead` for consistency
- removed `semaphore` field from `ThrottledFramedRead`

re: Refactor `ThrottledFramedRead`

---

Cargo.lock
core/primitives-core/Cargo.toml
core/primitives/Cargo.toml
core/store/Cargo.toml
runtime/near-vm-errors/Cargo.toml
tools/rpctypegen/core/Cargo.toml
tools/rpctypegen/macro/Cargo.toml
utils/near-rate-limiter/Cargo.toml

Remove recursive unused dependencies, which may slow down compilation of  `near-network`
```shell
L .~/r/nearcore master NO_REMOTE r cargo unused-deps --packages near-network
INFO cargo:191          package.name="near-primitives" package_path="core/primitives"
INFO cargo:194          unused dependency x.name="sha2"
INFO cargo:191          package.name="near-store" package_path="core/store"
INFO cargo:194          unused dependency x.name="lazy_static"
INFO cargo:194          unused dependency x.name="serde"
INFO cargo:194          unused dependency x.name="smart-default"
INFO cargo:191          package.name="near-vm-errors" package_path="runtime/near-vm-errors"
INFO cargo:194          unused dependency x.name="hex"
INFO cargo:191          package.name="near-rpc-error-core" …
```

re: Remove unused dependencies for `near-network`

---

chain/network/src/routing/routing_table_actor.rs

Document buggy behavior of `fetch_edges_for_peer_from_disk`  in response to https://github.com/near/nearcore/pull/5566
Based on https://github.com/near/nearcore/pull/5566, meant to be shipped afterwards.

re: Document buggy behavior of `fetch_edges_for_peer_from_disk` 

---

Cargo.lock
runtime/runtime-params-estimator/Cargo.toml

There are a few unused dependencies in `runtime-params-estimator` that can be safely removed.

re: Remove unused dependencies from `runtime-params-estimator`

---

Dockerfile
scripts/run_docker.sh

Hello, I'd like to propose some fixes to the docker run script:
1. `if [[ -z {INIT} ]]`
I suppose this was a typo and the `$` was missing, otherwise bash interpret {INIT} has string and `-z` is always false. In this case the correct test should be `-n` (= check variable is NOT empty VS `-z` = the variable is empty)
2. `if [[ -z {NODE_KEY} ]]`
Same as above, missing `$`
3. `exec neard $NEARD_FLAGS ...`
I'm adding `exec` in order to not let bash as PID 1 in the docker container, which is a best practice for signal handling and potential zombie processes (example [here](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint)) 
4. `$@`
This allows passing additional arguments to the main process (along with the next point)
5. `CMD => ENTRYPOINT`
Using the image …

Fix docker run script

---

chain/network/src/routing/edge_validator_actor.rs

Doc string for `EdgeValidatorActor` was not rendered properly, because it was placed before `impl`, rather than before `struct`.
Also fixes ticks.

re: chore: Fix doc string in `edge_validator_actor`

---

chain/network/src/routing/routing_table_actor.rs

Documentation for `RoutingTableMessages` is  using regular comments instead of doc strings. This PR changes those comments to doc strings, and fixes ticks.

re: chore: Change `comments` to doc strings for `RoutingTableMessages`

---

chain/network/src/peer_manager/peer_store.rs

`find_peers` function in `PeerStore` can be written in a cleaner way.

re: chore: Rewrite `find_peers` in `peer_store.rs`

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/routing/routing_table_view.rs
chain/network/src/tests/cache.rs

Code related to removing local edges can be written in a much simpler way. There is no need to pass list of edges.

re: chore: Refactor code in `PeerManager` related to removing local edges

---

chain/network/src/test_utils.rs

`Message` trait from `actix` can be derived instead of implementing it directly. We can do it for `test_utils` to improve code quality.
See https://github.com/near/nearcore/issues/6075

re: Cleanup usage of `actix::Message` in `near-network::test_utils`

---

chain/network/src/network_protocol.rs

Clion Rust plugin for Intellij gives a false error. Let's fix it. Maybe we should inform the rust clion plugin team?
```
mismatches types [E308]
expected `&HandshakeAutoDes`, for `&mut &[u8]`.
```
This issue is not too important to fix. I reported the issue to `intelij-rust`, and this PR can be helpful in fixing the issue in the plugin.

re: Fix Clion false error in `near_network.rs`

---

chain/network-primitives/Cargo.toml
chain/network/Cargo.toml
utils/near-cache/Cargo.toml
utils/near-performance-metrics-macros/Cargo.toml
utils/near-performance-metrics-macros/src/lib.rs
utils/near-performance-metrics/Cargo.toml
utils/near-rate-limiter/Cargo.toml
utils/near-stable-hasher/Cargo.toml

Let's format `Cargo.toml` files properly with order following https://doc.rust-lang.org/cargo/reference/manifest.html

re: Reformat `Cargo.toml` for `near-network` related packages

---

pytest/tests/sanity/rosetta.py

Commit 3444b8ed: ‘Avoid reading the genesis json file twice upon
startup’ changed how genesis file is loaded and as a result operations
of genesis block are now populated in Rosetta.  Update rosetta.py test
file.

pytest: fix Rosetta test after genesis records started being loaded

---

Cargo.lock
chain/indexer/src/lib.rs
chain/network-primitives/Cargo.toml
chain/network-primitives/src/config.rs
integration-tests/src/node/thread_node.rs
integration-tests/src/tests/nearcore/node_cluster.rs
integration-tests/src/tests/nearcore/stake_nodes.rs
integration-tests/src/tests/nearcore/sync_nodes.rs
integration-tests/src/tests/nearcore/sync_state_nodes.rs
nearcore/Cargo.toml
nearcore/src/lib.rs
neard/src/cli.rs
tools/indexer/example/src/main.rs

`client config` contains a sections for `near-network` called `NearNetworkConfig`.
In function `validate()` of `NearNetworkConfig` we verify all argument. However, if any argument is invalid, we will print an error an continue running an normal. 
The proper solution is to, throw an error, and make let the caller know, that the `network_config` is invalid. Btw, we don't check whenever the number of peers allowed is to high. See https://github.com/near/nearcore/pull/5703

feat: Don't hide errors with parsing `network config`.

---

chain/network/src/peer_manager/peer_manager_actor.rs

In order to improve readability of `PeerManagerActor`, we should remove the methods that don't really need `self`.
This can be done by either in-lining the code, or changing `self` method to be `Self` method.

re: Refactor `PeerManagerActor` pt 1

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_actor.rs

`send_message` function can be simplified in `PeerManagerActor` by changing it's signature from `self` to `Self`.
This is important step for adding tests to `PeerManagerActor` .

re: `PeerManagerActor` Simplify `send_message`

---

chain/client/src/client_actor.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
utils/near-performance-metrics-macros/src/lib.rs

By making improvements to `near-performance-metrics-macros`, we can change the logic of `perf` derive not to use `msg` argument.
This will allow us to use `perf` for any function, even ones that don't contain `msg` argument.
Also, we will be able to fix warnings about unused `msg` agument.

re: chore: Fix unused `msg` paramater warnings in `near-network`

---

Makefile

Commit adf23731: ‘Use make targets when building docker images’
changed sandbox and sandbox-release rules from assigning the
CARGO_TARGET_DIR environment variable within the shell command to
using a Makefile variable.  However, the commit did not export that
variable which means that the setting was never picked up by cargo.
As a result, running ‘make sandbox’ would build within ‘target’
directory overriding anything there and in the end fail (because it
expects to be able to link files from ‘sandbox’ directory to ‘target’
directory).
Fix by exporting the variable.
Note: It would be better to use rule-level export directive (as in
`sandbox: export CARGE_TARGET_DIRE=sandbox`) but, as far as
I gathered, that syntax isn’t supported by macOS make.
Issue: …

Makefile: fix sandbox target not building in sandbox directory

---

integration-tests/src/tests/test_download_file.rs
nearcore/src/config.rs

the download_file() test might fail if download_file() runs before
the HTTP server gets a chance to start. Fix it by waiting until the server
is already listening to call download_file(). This requires moving the
tokio runtime block_on() call to a wrapper function so we don't have problems
starting a runtime inside a runtime in the test code

tests: fix flaky integration test

---

chain/network/src/network_protocol.rs

Visibility of `HandshakeAutoDes` can be decreased to private. It's better not to expose this structure outside.

re: chore: Reduce visibility of HandshakeAutoDes in `near-network-primitives`

---

chain/network/src/peer_manager/peer_manager_actor.rs

Code inside `get_total_bytes_per_sec`/`sample_random_peer` can be inline for better readability.

re: `near-network` Inline one line methods to improve readability.

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/test_utils.rs

`broadcast_validated_edges_trigger` in `PeerManagerActor` should be rewritten in such a way, that the amount of work done my `PeerManagerActor` is constant.
The plan is to move the work inside `routing_table_actor`. More PRs are needed, this is a refactor, which will make the next change easier.

re: chore: Refactor `PeerManagerActor` before big changes

---

chain/network/src/peer_manager/peer_manager_actor.rs

There is still some code left in `PeerManagerActor` where we use `active_peer` terminology, but `connected_peer` terminology should be used. Let's fix those remaining places.

re: Rename `active_peer` to `connected_peer`

---

pytest/tests/sanity/skip_epoch.py

if get_validators() doesn't give what is expected, it's best to print
out the bad output itself. Subsequent calls might give different info

pytest: skip_epoch.py: don't refetch status when printing error msg

---

Cargo.lock
chain/chunks/Cargo.toml
chain/chunks/src/chunk_cache.rs
chain/chunks/src/lib.rs
chain/client/Cargo.toml
chain/client/src/client.rs
chain/client/src/sync.rs
chain/client/src/view_client.rs
chain/epoch_manager/Cargo.toml
chain/epoch_manager/src/lib.rs
integration-tests/Cargo.toml
integration-tests/src/test_helpers.rs
integration-tests/src/tests/client/runtimes.rs

We are in the process of removing `cached`, see https://github.com/near/nearcore/issues/5527
This is the final step towards removing `cached`.
- `/chain/chunk`
- `/chain/client`
- `/chain/epoch-manager`
- `/itegration-tests`

feat: Finish replacing `cached` with `lru`

---

CODEOWNERS

I replaced myself in the CODEOWNERS file with Robert, so he can be tagged in PRs and get more context on parts I was involved with.

chore: remove chefsale from codeowners and replace rtsai123

---

runtime/near-test-contracts/build.rs

This will fix the nightly build which in turn will let `nearup` download binaries again.
Tested by running `make nightly-release` with and without `CARGO_TARGET_DIR` environment variable.

Fix near-test-contracts build script to work if CARGO_TARGET_DIR is set.

---

Cargo.lock
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/wasmer2_runner.rs

This pulls in a fair amount of development that has occurred in the fork
over the past couple weeks.
Most notably it has a fix for a crash, functionality to simplify
profiling of the code generated by JIT, a stack limiting safeguard, and
a removal of baked in CPU capability checks at instantiation time, 
thus allowing cost estimation work again.
cc @jakmeier @olonho

Update to wasmer-near 2.2.0

---

chain/jsonrpc-primitives/src/types/chunks.rs
chain/jsonrpc-primitives/src/types/config.rs
chain/jsonrpc-primitives/src/types/gas_price.rs
chain/jsonrpc-primitives/src/types/query.rs
chain/jsonrpc-primitives/src/types/receipts.rs
chain/jsonrpc-primitives/src/types/sandbox.rs

This PR just adds `Debug` derivations to all jsonrpc-primitives types as we need them to be able to print RPC debug logs in [workspaces-rs](https://github.com/near/workspaces-rs).

feat: Make jsonrpc-primitives types derive `Debug`

---

Cargo.lock
chain/network/Cargo.toml
chain/network/src/routing/routing_table_view.rs

`find_route_from_peer_id` can be written without doing extra `clone`, memory allocations `Vec` nor `unwraps`.

feat: Optimize `find_route_from_peer_id` in `near-network`

---

chain/network-primitives/src/types.rs
chain/network/src/private_actix.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/types.rs
utils/near-rate-limiter/src/message_wrapper.rs

We can refactor code related to `MessageResponse`. We don't need to implement the trait, we can simply derive it.

re: Derive `MessageResponse` instead of implementing it

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_view.rs
chain/network/src/tests/cache.rs

I'm trying to improve `pub fn get_accounts_keys(&mut self)`.
Is there a way to avoid doing memory allocation here?

feat: Optimize `RoutingTableView` iterators

---

chain/network/src/peer/codec.rs
chain/network/src/peer_manager/peer_store.rs

`near-network::Codec::decode` method can be written in a cleaner way, by reducing the number of casts to `usize`.
And also writing code which gets length in a cleaner way as:
```rust
let len = u32::from_le_bytes(buf[..4].try_into().unwrap()) as usize;
```
We also change `fn gen_peer_info(port: u16)` api from `fn gen_peer_info(port: u8)`.
Ports are represented by `u16` in operating systems, and let's use correct type for consistency.

re: chore: Refactor decode in `near-network::Codec`

---

chain/network/src/peer_manager/peer_manager_actor.rs
nightly/pytest-sanity.txt

There was a crash, which only happens for this unit test. I fixed the issue by removing the unwrap.
Closes #6021

bug: Fix `routing_table_sync.py` test

---

Cargo.lock
chain/chain/Cargo.toml
chain/chunks/Cargo.toml
chain/client/Cargo.toml
chain/epoch_manager/Cargo.toml
chain/network/Cargo.toml
core/store/Cargo.toml
deny.toml
runtime/near-vm-logic/Cargo.toml
utils/near-cache/Cargo.toml

This upgrades:
* borsh
* bn
* lru
which together ensures that we have only one version of hashbrown -- a
sizable crate we don't want to have duplicates of.

chore: update crates to use single hashbrown version

---

chain/network-primitives/src/types.rs
chain/network/src/network_protocol.rs
chain/network/src/peer/codec.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer/utils.rs
chain/network/src/peer_manager/peer_manager_actor.rs

We should reduce size of `PeerMessage` enum to 64 bytes or less.
We can start by doing this for `PeerMessage::Routed` variant.
See #1313 
TODO

feat: Move `RoutedMessage` inside `Box` to reduce `PeerMessage` enum size

---

Cargo.lock
chain/network/Cargo.toml
chain/network/benches/graph.rs
chain/network/benches/routing_table_actor.rs

We are currently using `bencher` for bench-marking. We should switch to `criterion`.
In this PR we will switch `near-network` to use `criterion`.
Reasoning:
- `bencher` hasn't been updated since Jan 2018.
- `criterion` provides a statistically correct data on samples
- `criterion` provides various profiling tools, etc:
https://nickb.dev/blog/guidelines-on-benchmarking-and-rust

feat: Use `criterion` instead of `bencher`

---

Cargo.lock
chain/network/Cargo.toml
chain/network/src/peer/codec.rs
chain/network/src/peer/peer_actor.rs
nearcore/Cargo.toml
nearcore/src/lib.rs
neard/Cargo.toml
neard/src/main.rs
utils/near-performance-metrics/Cargo.toml
utils/near-performance-metrics/src/actix_enabled.rs
utils/near-performance-metrics/src/stats_enabled.rs

Upgrade `near-rust-allocator-proxy` to `0.4.0`, this version is can be used with `rust-memory-analyzer` (https://crates.io/crates/rust-memory-analyzer)
```shell
cargo build -p neard --features memory_stats
... // start neard 
cargo install rust-memory-analyzer
sudo $(which rust-memory-analyzer) analyze --pid `pidof neard`
```
Same, thing for `indexer-example`.

Update `near-rust-allocator-proxy ` to 0.4.0

---

chain/chain/src/chain.rs
integration-tests/src/tests/client/process_blocks.rs

Disable it for now. Fetching chunks for even two blocks at a time may cause OOM

Disable fetching chunks for multiple blocks

---

core/store/src/trie/trie_storage.rs

While working with https://github.com/near/nearcore/pull/5871, because of a typo (?) we replaced some `cache_get` with `pop`, so we remove each entry from `TrieCachingStorage` on read: https://github.com/near/nearcore/pull/5871/files#diff-e073548a40d97af14f75cf143fab41a1cffe61d159e0b9a6297daeab0b2a5d45L171
Here we restore the original behaviour.
Existing tests.

fix: replace pop with get in `TrieCachingStorage`

---

pytest/lib/utils.py

in utils.poll_blocks(), start_height will never be set, and
blocks_count is never referred to, so we'll never get the more
helpful error message on timeout with this logic

pytest: fix small bug

---

chain/chain/src/chain.rs
chain/chain/src/tests/challenges.rs
chain/chain/src/tests/mod.rs
chain/chain/src/tests/sync_chain.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/sync.rs
integration-tests/src/tests/client/process_blocks.rs

This mechanically substitutes `dyn FnMut` for `F where F: FnMut`. The benefits would be: 
* net reduction in lines of code
* significantly simplified call-sites -- no more weird `Arc<RwLock>` shenanigans
* improved compile times -- now we don't need to monomorphize this stuff, so it is compiled once, in the definition crate
I think there might be further benefits to bunching up the callbacks into some kind of callback struct, but that'd be a slightly more invasive refactor.

refactor: simplify callback handling in chain

---

Cargo.toml

Tagged: https://github.com/near/nearcore/releases/tag/crates-0.12.0
Notable changes:
- https://github.com/near/nearcore/pull/6179
- https://github.com/near/nearcore/pull/6158
Check here for a full changelog: https://github.com/near/nearcore/compare/crates-0.11.0...crates-0.12.0

chore: bump version to 0.12.0

---

Cargo.toml

`neard` marked "independent" since https://github.com/near/nearcore/pull/6202 resulted in `cargo-workspaces` falling back to interactive mode for it to be versioned.
Context: https://buildkite.com/nearprotocol/nearcore-release/builds/1784#260c2987-b154-4d5b-acb5-85a9ca1259b9
This excludes `neard` entirely from the versioning process.

fix(CI): exclude neard from being versioned by cargo-workspaces

---

chain/network/src/network_protocol.rs

The bound is too tight for aarch64 for now. Given that we don't run
aarch64 in production yet and would have to audit all the code before we
do anyway, let's just disable this check for aarch64.
Fixes #6222

aarch64: fix compilation issue

---

chain/client/src/client_actor.rs

The first three already imply ToEnvelope because of a blanket impl:
https://github.com/actix/actix/blob/v0.11.0-beta.2/actix/src/address/envelope.rs#L22-L31
So this allows a bit of simplification and avoids having to refer to a sort of less
public part of actix

cleanup: remove ToEnvelope trait bound on create_sync_job_scheduler()

---

Cargo.lock
chain/network-primitives/Cargo.toml

Context: https://buildkite.com/nearprotocol/nearcore-release/builds/1802#48b4d213-9613-462b-bb5d-350a3ad87d3a/106-1194
```console
$ cargo package -p near-network-primitives
Compiling near-network-primitives v0.12.0 (/var/lib/buildkite-agent/builds/buildkite-i-08e77618f4765ff4c-1/nearprotocol/nearcore-release/target/package/near-network-primitives-0.12.0)
error[E0412]: cannot find type `OneshotSender` in module `actix::dev`
--> src/types.rs:322:17
|
322 | #[derive(Debug, actix::MessageResponse)]
|                 ^^^^^^^^^^^^^^^^^^^^^^ not found in `actix::dev`
|
= note: this error originates in the derive macro `actix::MessageResponse` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0049]: method `handle` has 0 type parameters but its trait declaration has 1 type …
```

fix(network-primitives): pin actix-derive to fix isolated compilation issues

---

chain/chain/src/chain.rs
chain/client-primitives/src/types.rs
chain/client/src/lib.rs
chain/client/src/view_client.rs
chain/rosetta-rpc/src/lib.rs

The `/network/status` Rosetta RPC returns, among other things, height
and hash of the genesis block.  Currently, it does it by fetching the
genesis block.  Sadly, in non-archival nodes, genesis block is usually
unavailable which leads to failures in serving the RPC.  To address
this issue, introduce a `GetBlockHash` request which returns only the
hash of a block.  Since height→hash mapping is not garbage collected,
this request will always work even for garbage collected blocks.

client: add GetBlockHash request and use it in Rosetta RPC

---

chain/client/src/client_actor.rs
chain/client/src/info.rs
chain/client/src/metrics.rs

The metrics added look like this on a localnet node without transactions:
```
near_chunk_tgas_used_hist_bucket{shard="0",le="50"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="100"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="300"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="500"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="700"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="800"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="900"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="950"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="1000"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="1050"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="1100"} 12
near_chunk_tgas_used_hist_bucket{shard="0",le="1150"} 12 …
```

feat: add metrics about chunk fullness

---

Dockerfile

Address ‘When using COPY with more than one source file, the destination
must be a directory and end with a /’ warning showing up when building
Docker image.

Fix copy path in Dockerfile

---

chain/client/src/info.rs

Remove some overly verbose information from status line and at the
same time make the status more descriptive.
Before: `-/4 7/7/40 peers`
After: `4 validators 7 peers`
Information that this commit removes:
* the ‘-’ indicating whether node was validator or not,
* second ‘7’ indicating the number of peers that have highest height
close to the node and
* ‘40’ indicating maximum number of peers.
Fixes: https://github.com/near/nearcore/issues/2454

chain: make status line more descriptive

---

chain/chain/Cargo.toml
chain/client/Cargo.toml
chain/epoch_manager/Cargo.toml
chain/jsonrpc/Cargo.toml
chain/network-primitives/Cargo.toml
chain/network/Cargo.toml
chain/rosetta-rpc/Cargo.toml
core/crypto/Cargo.toml
core/primitives-core/Cargo.toml
core/primitives/Cargo.toml
core/store/Cargo.toml
integration-tests/Cargo.toml
nearcore/Cargo.toml
neard/Cargo.toml
runtime/near-vm-errors/Cargo.toml
runtime/near-vm-logic/Cargo.toml
runtime/near-vm-runner-standalone/Cargo.toml
runtime/near-vm-runner/Cargo.toml
runtime/runtime-params-estimator/Cargo.toml
runtime/runtime/Cargo.toml
test-utils/state-viewer/Cargo.toml
test-utils/testlib/Cargo.toml

this will make them easier to edit and the git diffs will be nicer.
Done with a python script that basically says:
if len(list) > 1:
reformat(list)
Issue: https://github.com/near/nearcore/issues/5328

chore: reformat Cargo.toml lists with many elements in one line

---

runtime/runtime-params-estimator/src/cost.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/utils.rs

The new deployment cost estimation now also treats data bytes and code
bytes differently  in the fromulas.
The new cost `DeployBytes` is there to assert the assumption that
compilation cost is the dominant factor.

feat: Differentiate code and data bytes

---

chain/client/src/info.rs

The status line has recently been simplified with many unnecessary
pieces of information being removed.  Among those was flag denoting
whether node was a validator.  Turns out that that particular piece of
information is desired to be kept.  Add it back.
Right now the status line will be:
- `42 validators 24 peers` if node is not a validator and
- `Validator | 42 validators 24 peers` if it is.
Fixes: https://github.com/near/nearcore/issues/2454

chain: include information whether node is a validator in status line

---

Cargo.lock
chain/indexer/Cargo.toml
core/store/Cargo.toml
core/store/src/db.rs
core/store/src/db/refcount.rs
core/store/src/db/v6_to_v7.rs
runtime/runtime-params-estimator/Cargo.toml

This reverts commit 6a0349f31a6b681e825ae98015d0d842d54fd21c.

Revert "chore: Upgrade rust-rocksdb 0.16 to 0.18 (#6289)"

---

chain/client/src/info.rs

This changes status like:
… 6Z3gNeGdPyvjcBYRu15yBHxZJukePjBiKBuBXYj2KoW8Validator | 1 validator …
^^^^ notice lack of space
into:
… 6Z3gNeGdPyvjcBYRu15yBHxZJukePjBiKBuBXYj2KoW8 Validator | 1 validator …
^^^^ notice space
Sorry about this silly mistake.
Issue: https://github.com/near/nearcore/issues/2454

chain: add space between block hash and validator status

---

Dockerfile
scripts/run_docker.sh

Commit [c46de252: ‘run_docker.sh improvements and fixes’] changed
Dockerfile to use ENTRYPOINT rather than CMD.  The idea was to make
it simple to pass arguments to the `run_docker.sh` script (i.e. they
would just need to be passed to the docker invocation).
Unfortunately, this was a backwards incompatible change and this
wasn’t realised back then.  As a result, previously working commands
such as:
docker run nearprotocol/nearcore:latest \
sh -c 'neard --verbose --home=/home/ubuntu/.near run'
stopped working.
Change the Dockerfile back from ENTRYPOINT to CMD to bring back the
old behaviour.
Other changes in the run_docker.sh script can be left as is since they
are still compatible.  One fix though is to use a POSIX-compliant export
command since the script now uses /bin/sh.

Dockerfile: change back from ENTRYPOINT to CMD

---

nightly/fuzz.toml

1.25.0-rc.1 was cut recently and 1.24.0 is currently on mainnet, so we no longer need to fuzz 1.23.1 but we do need to fuzz 1.25.0

fuzz: adjust branches with the latest release

---

core/store/benches/trie_bench.rs
core/store/src/trie/iterator.rs
core/store/src/trie/mod.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_storage.rs
core/store/src/trie/trie_tests.rs
core/store/src/trie/update.rs

https://github.com/near/nearcore/issues/6270
Currently, `retrieve_raw_bytes` returns `Vec<u8>`, but in fact we don't need it, and sometimes it leads to unnecessary clones. Here we replace it with `Arc<[u8]>`. We can't use `&[u8]` at least for now, because trie cache may be used by different clients (i.e. view clients).
I tried two approaches to benchmark this:
I couldn't see significant performance improvement here.
The difference is still negligible, though the version in PR always gave smaller time.
However, in current bench implementation
* keys are random `Vec<u8>`s, so the number of intermediate visited nodes should be small relatively to the number of values;
* perhaps on the long distance, running bench with the same set of kv pairs gives the same results.
So I modified benchmark …

feat: replace `Vec<u8>` with `Arc<[u8]>` in trie cache

---

pytest/requirements.txt
pytest/tests/fuzz.py

`subprocess.call(..., timeout=...)` will send KILL signal to the
process that has been spawned once the timeout passes but that may
leave its descendants still running.  To cover that case, handle
timeout ourselves by waiting and then killing the entire process tree.

pytest: fuzz: fix test not killing fuzz processes correctly

---

neard/build.rs

The build.rs script for neard package assumes that git direcotry is
located in ../.git (relative to the package directory) which usually
is the case except whet git worktrees are used.  In that case .git is
a file rather than a directory and resolving paths relative to it
acuses an error.  Fix the isuse by using `git rev-parse --show-git-dir`
as the code should from the start.

neard: make build.rs work with git worktree

---

tools/state-viewer/src/commands.rs

view_state chain will now print information about each shard/chunk (including gas used)
10718 H44octV |  test.near | parent: 10717 Br9X8Vg | . 0: 2WdPmD9   0 Tgas
10719 AjuJw2P |  test.near | parent: 10718 H44octV | . 0: 6f92HEW   0 Tgas
10720 BdwPWrj |  test.near | parent: 10719 AjuJw2P | . 0: 3vHDAFR   0 Tgas

Added chunk info to state viewer's print chain

---

runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_cost.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/vm_estimator.rs

Gas metering estimation now also respects CLI parameters
(`--iters` and --`warmups-iters`)
Also avoid runtime panic in case of unstable measurements

refactor: Align gas metering estimation

---

core/store/src/db.rs
runtime/runtime-params-estimator/src/config.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/main.rs
runtime/runtime-params-estimator/src/rocksdb.rs
runtime/runtime-params-estimator/src/testbed.rs
runtime/runtime-params-estimator/src/utils.rs

Setting up state for estimating benchmarks leads to warm chaches.
But the goal is to measure the times used when caches are cold.
Flushing write buffers and clearing the OS cache helps here.

feat(params-estimator): Clear IO caches

---

chain/chain/Cargo.toml
chain/chain/src/chain.rs
chain/client/Cargo.toml
chain/client/src/client_actor.rs
chain/network/Cargo.toml
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_actor.rs
nearcore/Cargo.toml
tools/delay_detector/Cargo.toml
tools/delay_detector/src/lib.rs

We can get rid of conditional imports from our code by making `delay-detected` a required dependency. However, it's functionality will be put under `delay_detector` flag.

Make `delay-detector` required, and make it's functionality flag dependent.

---

core/primitives/src/sharding.rs

core: preallocate known vector capacity in encode_transaction_receipts

---

chain/chunks/src/lib.rs

Extract two more methods from `process_partial_encoded_chunk_request`
which correspond to `if` bodies that used to be in it.  This makes each
function shorter and thus easier to read especially as in the future
more branches will be added to the method.
Furthermore, move sending of the message to the method changing
`maybe_send_partial_encoded_chunk_response` into method which prepares
the response only.
This is a pure refactoring with no changes to the behaviour.

chain: refactor `process_partial_encoded_chunk_request` method

---

Cargo.lock
chain/chain-primitives/Cargo.toml
chain/chain-primitives/src/error.rs
chain/chain/Cargo.toml

Closes #6207 
Switch from `failure` crate to `thiserror` and `anyhow`.

refactor: migrate from failure crate to thiserror & anyhow

---

pytest/lib/cluster.py
pytest/tests/sanity/block_sync_archival.py

Extend sanity/block_sync_archival.py test documentation describing in
more detail what it’s doing and mentioning that both nodes are
archival.  Furthermore, avoid starting the observer node at the
beginning just to kill it immediately; it’s now started only once the
validator generates the blocks.  Finally, add explicit comparison of
all the blocks in the validator and observer nodes.

pytest: explicitly check synced blocks in block_sync_archival.py test

---

Cargo.lock
chain/chain/src/chain.rs
chain/chunks/src/lib.rs
chain/chunks/src/test_utils.rs
chain/client/src/client.rs
chain/client/src/view_client.rs
chain/network/src/types.rs
integration-tests/Cargo.toml
integration-tests/src/bin/start_mock_network.rs
integration-tests/src/lib.rs
integration-tests/src/mock_network/README.md
integration-tests/src/mock_network/mod.rs
integration-tests/src/mock_network/setup.rs
integration-tests/src/tests/client/challenges.rs
tools/restaked/Cargo.toml

First iteration of mock network (different from Nikolay's mocknet, better name suggestion welcomed)
A mock network simulates a test environment for ClientActor by replacing PeerManagerActor, instead of sending network messages out to other peers, it simulates a network and reads the needed block and chunk content from storage.
In this first iteration, the mock network only simulates one peer and all messages get instant response from the mock network. I will add more complicated peer logic in future iteration.

mock network first iteration

---

core/primitives/src/errors.rs

Saw that we were missing a couple impls for `std::error::Error` for some of the errors in near-primitives. Would be useful if we could convert them into `&dyn Error` or `anyhow` errors to be used in libraries such as `workspaces`

chore: impl `Error` on near-primitives errors that missed them

---

chain/client/src/client_actor.rs

Currently log_summary was executed periodically via 'run_later'. Unfortunately, Actix can sometimes 'starve' these threads when system is overloaded.
Moved the code to run from check_triggers, which will not starve.
Tested:
Run loadtest to verify the behaviour under load.

Moving log_summary into check_triggers

---

core/primitives-core/src/account.rs

Fixes #6293 
Note I'm not sure why we were panicking upon invalid buffer length before: it looks to me like something that was left over from an experiment of adding a second version of account serialization and no longer makes sense, but I'm keeping it for now until @EgorKulikov comments about its use.
I tried building and running the two neard command lines listed in #6293 on both arm64 and amd64 and they succeeded properly.
cc @frol @EgorKulikov @bowenwang1996 @mm-near

fix: fix account deserialization on arm64 while keeping the behavior of panicking if deserializing too big a slice

---

Cargo.lock
test-utils/runtime-tester/Cargo.toml
test-utils/runtime-tester/fuzz/fuzz_targets/runtime_fuzzer.rs
test-utils/runtime-tester/src/run_test.rs

System time is a high-variability metric. CPU time consumed by the
process should be much less volatile, and so hopefully will lead to both
fewer false positives, but also to a lesser need for safety margins,
thus allowing the lowering of 3 seconds to 2 seconds when fuzzing.

fuzz: avoid runtime-tester false positives

---

chain/client-primitives/src/types.rs
chain/client/src/tests/query_client.rs
chain/client/src/view_client.rs
chain/jsonrpc-primitives/src/types/query.rs

Querying garbage collected historical data from a non-archival node yields `RpcQueryError::UnavailableShard`, see #4340.
Before returning `RpcQueryError::UnavailableShard`, `ViewClientActor` checks in `handle_query` if the block might have been garbage collected. If yes, it returns `QueryError::GarbageCollectedBlock` (new error variant).
- Start two validator nodes: one non-archival, one archival.
- Let them produce blocks until garbage collection kicks in.
- Query data that might have been garbage collected and verify:
- The non-archival node returns `QueryError::GarbageCollectedBlock`.
- The archival node returns the data.

chain: add RpcQueryError::GarbageCollectedBlock

---

nightly/fuzz.toml

Context: grafana for at least two of the last spurious crashes since switching to measuring CPU time shows a memory peak of ~4G just around the time of the crash report.
I'm thinking if one iteration of one of these fuzzers takes more than 1G there's probably something wrong, so might as well lower the limit.
I'm also seeing to integrate the cAdvisor exporter in order to get cgroup-specific metrics, which should help identify the root cause of the memory peak in case it was not actually one fuzzer causing the issues.

fuzz: fight fuzzer false positives by attempting to reduce the allowed memory

---

chain/network-primitives/src/types.rs
chain/network/src/peer_manager/peer_store.rs

`PeerStore::new` can be written in a functional style; it will be much easier to read it.

re: Rewrite `PeerStore::new` in a functional way

---

Makefile

We’re running canary nodes with executable build using perf-release
target.  Since that target does not set NEAR_RELEASE_BUILD environment
variable when canary starts it prints warning about unsupported node
being run:
neard: Running a neard executable which wasn’t built with `make release` command isn’t supported on mainnet.
neard: Note that `cargo build --release` builds lack optimisations which may be needed to run properly on mainnet
Fix that by setting the environment variable in perf-release target
(just like it’s done in release target) so that neard executable
knows it’s a supported build.

Makefile: classify perf-release as release build

---

runtime/runtime-params-estimator/src/cost.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/transaction_builder.rs
runtime/runtime-params-estimator/test-contract/src/lib.rs

Replace old placeholder estimation for touching_trie_node
with an actual estimation.

feat(params-estimator): Touching trie node est.

---

pytest/endtoend/endtoend.py

Most notably, wrap body of the pinger loop in a try-except block which
logs exception information if any exception happens.  This way, even if
something goes wrong during one iteration, the test will continue trying.
And while editing the file, replace `for _ in range(len(_))` loops by
iterating over elements of lists.  This is more idiomatic and removes the
need to explicitly index the lists.
Lastly, initialise Prometheus client only after all arguments are validated.

endtoend: make more resilient to exceptions and other minor improvements

---

nightly/fuzz.toml

Spurious OOMs, maybe related to
https://github.com/rust-fuzz/cargo-fuzz/issues/270, seem to have started
appearing — they are very hard to reproduce locally, so let's increase a
bit the memory limit

fuzz: go back to the default 2G of ram for each fuzzer

---

Cargo.lock
chain/client/src/client_actor.rs
test-utils/actix-test-utils/Cargo.toml
test-utils/actix-test-utils/src/lib.rs

This reverts commit f2bba0841ecc8c9917babe57757f14fed838fa3b.
The commit casuse ~30 timeouts in NayDuck tests.

Revert "start client actor in a separate thread"

---

runtime/runtime-params-estimator/emu-cost/ci.sh

The old way of initializing a neard home does not install the test
contract on all accounts, which leads to estimations failing.
Giving an empty directory to the estimator as home will cause it to
initialize it properly.

fix(script): Fix params-estimator init in CI

---

runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/test-contract/src/lib.rs

Some estimations took >1h to finish in qemu.
This change speeds them up by reducing unreasonable repetitions per
iteration.
(Total repetitions = iters_per_block * block_size * inner_repetitions)
- Deployment per byte: 100 -> 5 block size
- UTF8 / UTF16 decoding per byte: 10k -> 1k inner repetitions
The new time is around 5min per block for all 3 collectively.

Estimator speed

---

pytest/lib/utils.py
pytest/tests/adversarial/malicious_chain.py
pytest/tests/adversarial/start_from_genesis.py
pytest/tests/sanity/backward_compatible.py
pytest/tests/sanity/block_sync.py
pytest/tests/sanity/block_sync_archival.py
pytest/tests/sanity/garbage_collection.py
pytest/tests/sanity/garbage_collection1.py
pytest/tests/sanity/gc_after_sync1.py
pytest/tests/sanity/gc_sync_after_sync.py
pytest/tests/sanity/handshake_tie_resolution.py
pytest/tests/sanity/proxy_restart.py
pytest/tests/sanity/repro_2916.py
pytest/tests/sanity/spin_up_cluster.py
pytest/tests/sanity/state_sync2.py
pytest/tests/sanity/state_sync3.py
pytest/tests/sanity/state_sync_fail.py
pytest/tests/sanity/switch_node_key.py
pytest/tests/sanity/sync_ban.py
pytest/tests/sanity/sync_chunks_from_archival.py
pytest/tests/sanity/transactions.py

Calculate default timeout to the utils.wait_for_blocks function.  The
timeout is based on number of blocks the function waits for.  Having
the default allows us to simplify tests which no longer need to
specify explicit timeout.

pytest: add default timeout to utils.wait_for_blocks

---

nightly/fuzz.toml

This way we can scale up the fuzzing infrastructure for the other fuzz targets without getting overwhelmed by this fuzzer's intermittent failures that look mostly independent from its inputs.

fuzz: disable runtime-tester for now as it's got lots of intermittent failures anyway

---

pytest/tests/sanity/block_sync_archival.py

By mistake archive_gc_partial_chunks setting has been added to the
test in previous commit changing it.  The option is meant for future
commits and currently causes test failures.  Fix that.

pytest: fix block_sync_archival.py

---

pytest/tests/sanity/block_sync_archival.py

Add code for observing the partial chunks request processing time metrics
to make sure that the expected code paths are executed when handling the
request.

pytest: observe metrics in block_sync_archival.py test

---

scripts/formatting

Due to a typo, the scripts/formatting script did not look at Python
files located in scripts directory when checking or fixing the
formatting.  Fix that issue.

scripts: actually look at ‘scripts’ directory when ‘formatting’

---

runtime/runtime-params-estimator/emu-cost/ci.sh

Do not copy runtime_config.json after estimation.
The CI script wants to prepare runtime_configs.json as buildkite
artifact but this is no longer generated by default. Generating it
in an extra step also does not work right now as some estimations are
missing.
We do not need this artifact and this script is deprecated anyway.

fix(script): Estimator CI

---

nearcore/src/lib.rs

Issue: https://github.com/near/nearcore/issues/6119

neard: use u64 counters in recompress-storage to avoid overflows

---

chain/client/src/client_actor.rs
chain/jsonrpc/res/debug.html
chain/jsonrpc/res/sync_info.html
chain/jsonrpc/src/lib.rs
chain/network/src/types.rs
core/primitives/src/views.rs

This PR is to add a debugging page that reflects the sync status in a browser window.
JIRA Issue: [CP-10](https://nearinc.atlassian.net/browse/CP-10)
Test plan
- Build with `make neard`
- Launch using command `nearup stop && nearup run localnet --binary-path ./target/release`
- Open your browser and go to http://[host_address[:3030/debug/
- Expect to see the link "Sync Info"
- Click the link "Sync Info"
Screenshot
(on localnet)
(on testnet)
First-round Reviewers
- @mm-near 
- @mzhangmzz

add a debug page with sync and network info

---

runtime/runtime-params-estimator/src/main.rs

I realized that if building test contract fails, we don't notice it, because it just results in non-zero status.
The PR should fix it.

feat: return error if building test contract fails

---

nearcore/src/config.rs

Now that nearcore can download a compressed genesis.json file and we
are offering one for betanet and testnet start downloading that file.
Fixes: https://github.com/near/nearcore/issues/4951

nearcore: download compressed betanet and testnet genesis.json file

---

Cargo.lock
Cargo.toml
core/o11y/Cargo.toml
core/o11y/README.md
core/o11y/src/lib.rs
deny.toml
neard/Cargo.toml
neard/src/cli.rs
test-utils/logger/Cargo.toml
test-utils/logger/src/lib.rs
tools/chainsync-loadtest/Cargo.toml
tools/chainsync-loadtest/src/main.rs
tools/indexer/example/Cargo.toml
tools/indexer/example/src/configs.rs
tools/indexer/example/src/main.rs
tools/restaked/Cargo.toml
tools/restaked/src/main.rs
tools/storage-usage-delta-calculator/Cargo.toml
tools/storage-usage-delta-calculator/src/main.rs

This will utilize a separate thread to write out the spans and events
without while letting the main computation to proceed with its business.
Additionally, we are buffering the output by lines, thus reducing the
frequency of syscalls that can occur when the subscriber is writing out
parts of the message.
This should mitigate concerns of enabling debug logging as its impact on
performance should now be minimal (putting an event structure onto a
MPSC queue.) There are still costs associated with logging everything
however. Most notably formatting and construction of the
`tracing_core::ValueSet`s still occur on the caller side, so if
constructing those is expensive, the logging might remain expensive.
An example of code sketchy like that (although silly) could be:
```
debug!(message = { …
```

Use non-blocking log writer

---

runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/testbed.rs
runtime/runtime-params-estimator/src/utils.rs

Most estimations execute transactions. The measurment includes
as many blocks as necessary to execute all receipts.
This change does two things.
1. Mark as uncertain if overhead of applying blocks is significant.
2. Force estimation function to define over how many blocks it executes.

feat(params-estimator): Block overhead consistency

---

chain/client/src/client_actor.rs
chain/client/src/info.rs

This PR adds more detailed info of sync on the debug page, utilizing the existing `display_sync_status` method.
[CP-19](https://nearinc.atlassian.net/browse/CP-19?atlOrigin=eyJpIjoiZTlhZDkyZWJkZmNkNDJjMTgyOWI4MTdmMTFjZTNkNDQiLCJwIjoiaiJ9)
- Under nearcore directory, launch localnet using command `nearup stop && nearup run localnet --binary-path./target/release`
- Open your browser and go to `http://[host_address]:3030/debug/`
- Click the link "Sync Info"
- Expect to see a webpage that displays detailed sync info, similar to the one below, with contents in the parentheses
(on localnet)
- @mzhangmzz
- @mm-near

add detailed sync info on debug sync page

---

core/o11y/src/lib.rs
neard/src/cli.rs
tools/chainsync-loadtest/src/main.rs
tools/indexer/example/src/main.rs
tools/restaked/src/main.rs
tools/storage-usage-delta-calculator/src/main.rs

When the subscriber is registered globally, it transparently also
applies to any thread, unlike the subscribers that are registered using
`set_default`, which only apply to the current thread.
This is somewhat incompatible with the non-blocking writer, because now
it is possible that we drop the writer guard in the main thread, flush
the `stderr` and then threads log additional messages before the program
exits. This would then lead to some messages being lost.
I feel like we can afford this, though. The alternative would be to
somehow ensure we register the subscriber for every thread, but thread
creation is not necessarily have a full control over. Libraries could
spawn their own, etc.

Register the subscriber globally

---

chain/client/src/client_actor.rs
chain/client/src/metrics.rs
chain/network-primitives/src/network_protocol/mod.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/stats/metrics.rs

Added metrics to track how much time client actor spends on each check_trigger and add more detailed network messages counting by type.
Metrics:

Add more debug metrics

---

tools/state-viewer/src/commands.rs

the apply command prints out the ChunkExtra that results from applying
the block, but it uses the genesis config's gas limit instead of the
gas limit actually specified in the chunk it applied. This is just a
cosmetic change since it only affects what info the command prints,
not how it applies the chunk

nit(state-viewer): print out current gas limit in apply command

---

CODEOWNERS
CONTRIBUTING.md

Today the nearcore code review process is substandard. When a PR is submitted, code owners’ reviews are automatically requested. Given that some components have a few code owners, often a PR automatically requests review from many people. At the same time, a PR needs approvals from at least one code owner of every component. As a result, the code review process may take several days and sometimes people ignore those review requests thinking that other code owners would review them instead.
After some discussion with @mm-near and @matklad, we decide to experiment with the following solution: there will be a single team of codeowners and once a pull request is submitted, one of the codeowners' review will be requested. The chosen codeowner can re-assign to another person for review if they …

chore: remove per component code owners

---

chain/client/src/client_actor.rs
chain/jsonrpc/res/chain_info.html
chain/jsonrpc/res/debug.html
chain/jsonrpc/res/last_blocks.html
chain/jsonrpc/res/sync_info.html
chain/jsonrpc/src/lib.rs
core/primitives/src/views.rs

This PR adds the skeleton of the chain info debug page , and fills in the heights & hashes of the current head & header head.
[CP-18](https://nearinc.atlassian.net/browse/CP-18)
- Under `nearcore` directory, launch localnet using command `nearup stop && nearup run localnet --binary-path ./target/release`
- Open your browser and go to http://[host_address]:3030/debug/
- Expect to see the link "Chain Info"
- Click the link "Chain Info"
- Go back to http://[host_address]:3030/debug/
- Make sure other links aren't broken, either
- @mzhangmzz 
- @mm-near

Chain debug page: head & header head info

---

chain/chain/src/store.rs
core/primitives/src/trie_key.rs
core/store/src/trie/shard_tries.rs

Firstly, rename KeyForStateChanges constructor methods.  Maybe it’s
just me, but get_prefix just doesn’t sound like a good name for
a constructer,  Use for_block, from_raw_key and from_trie_key names
instead which are shorter and at the same time more descriptive.
Secondly, add TrieKey::append_into method which rather than
allocating a new vector appends the data into existing vector.
Lastly, use that in KeyForStateChanges::from_trie_key method to
get rid of vector allocation.

core: small KeyForStateChanges refactor

---

runtime/near-vm-logic/src/logic.rs
runtime/near-vm-logic/src/tests/gas_counter.rs
runtime/near-vm-logic/src/tests/helpers.rs
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/imports.rs
runtime/runtime/Cargo.toml

This contains two fixes:
* We didn't actually add the relevat feature flag to Cargo.toml,
so near-vm-runner side of implementation was effectively dead
* In the signature of the logic function, only u64/u32 are allowed (this
is a signature directly exported into WASM)
Test Plan
---------
Run `cargo test --package near-vm-runner --lib --all-features` locally and check that it indeed adds the required host fn.

fix: protocol_feature handling for FunctionCallWeight

---

runtime/near-vm-logic/src/receipt_manager.rs
runtime/near-vm-logic/src/tests/gas_counter.rs

Adjusting formula based on @matklad suggestion. It more closely represents distributing gas based on weights if the sum of weights is greater than the amount of gas remaining at the cost of performing slightly more arithmetic.
I think this makes more sense, but hard to think about the exact implications without some benchmark of the two.

fix!: adjust gas distribution formula for NEP264

---

nearcore/src/runtime/mod.rs

This reduces the amount of boilerplate, and also makes it easy to see
all the places where we take a write lock.

refactor: compress locking of EpochManager

---

chain/client/src/client_actor.rs
chain/jsonrpc/res/debug.html
chain/jsonrpc/res/epoch_info.html
chain/jsonrpc/src/lib.rs
core/primitives/src/views.rs

This PR adds the skeleton of the epoch info debug page , and fills in the information of account IDs of the validators, as the first step.
[CP-20](https://nearinc.atlassian.net/browse/CP-20)
- Under `nearcore` directory, launch localnet using command `nearup stop && nearup run localnet --binary-path ./target/release`
- Open your browser and go to http://[host_address]:3030/debug/
- Expect to see the link "Epoch Info"
- Click the link "Epoch Info"
- Go back to http://[host_address]:3030/debug/
- Make sure other links aren't broken, either
- @mzhangmzz 
- @mm-near

create epoch info debug page to show validators

---

core/primitives/src/runtime/config_store.rs
core/primitives/src/version.rs
integration-tests/src/tests/client/process_blocks.rs

When updating #6397 to protocol v53 right before merging,
I forgot to add the configuration JSON file to the config store.
Test plan
---------
Added a test to verify that cost indeed increases.

fix: Add v53 to config store

---

nearcore/src/lib.rs

Store::iter strips reference count from reference counted columns and
writing returned value to a new database leads to corrupted data since
the count is no longer present.  The correct way to deal with raw
values saved in the database is to use Store::iter_without_rc_logic.
Switch recompress_storage to do that.
Issue: https://github.com/near/nearcore/issues/6119

recompress_storage: fix handling of rc columns

---

chain/chain/src/blocks_delay_tracker.rs

The asserts have been introduced in commit ed1a1b600bb4: ‘add metrics
for how long a block stay in the orphan pool and the missing chunks
pool’ and at least the one in mark_block_unorphaned have been failing
in some of the tests.  Remove the asserts to make the tests pass.

chain: remove failing debug asserts

---

Cargo.lock
chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/epoch_manager/Cargo.toml
chain/epoch_manager/src/lib.rs
chain/epoch_manager/src/tests/random_epochs.rs
nearcore/src/runtime/mod.rs
nearcore/src/shard_tracker.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/epoch_info.rs
utils/near-cache/src/lib.rs

This replaces `lru::LruCache` with `near_cache::SyncLruCache` in the implementation of the EpochManager, which in turn allows to make all the getters to use `&self`, which in turns allows the callers of EpochManager to actually take advantage of RwLock.

perf: avoid locks in epoch manager

---

core/o11y/src/lib.rs

The target is used by recompress_storage.  Initially the command used
no target but then target was added which caused the log lines to be
ignored by default.
Issue: https://github.com/near/nearcore/issues/6119

neard: enable target:"recompress" info logs by default

---

Cargo.lock
chain/chain/Cargo.toml
chain/chunks/Cargo.toml
chain/client-primitives/Cargo.toml
chain/client/Cargo.toml
chain/indexer/Cargo.toml
chain/jsonrpc-primitives/Cargo.toml
chain/jsonrpc/Cargo.toml
chain/jsonrpc/fuzz/Cargo.toml
chain/jsonrpc/jsonrpc-tests/Cargo.toml
chain/network-primitives/Cargo.toml
chain/network/Cargo.toml
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/routing_table_actor.rs
chain/rosetta-rpc/Cargo.toml
chain/telemetry/Cargo.toml
integration-tests/Cargo.toml
nearcore/Cargo.toml
neard/Cargo.toml
tools/chainsync-loadtest/Cargo.toml
tools/indexer/example/Cargo.toml
utils/near-performance-metrics/Cargo.toml
utils/near-performance-metrics/src/framed_write.rs
utils/near-rate-limiter/Cargo.toml

Closes https://github.com/near/nearcore/issues/5537
Updates `actix` to `v0.12.0`, resolving the compilation issue that required us to manually pin `actix_derive` in our dependency tree. Or downstream dependents of nearcore, having to copy the `Cargo.lock` into their projects.
Related: https://github.com/near/nearcore/pull/6246

chore: bump `actix` to `v0.12.0` stable

---

runtime/near-vm-runner-standalone/src/main.rs
runtime/near-vm-runner-standalone/src/script.rs
runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
runtime/near-vm-runner/src/lib.rs
runtime/near-vm-runner/src/preload.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/tests/contract_preload.rs
runtime/near-vm-runner/src/tests/rs_contract.rs
runtime/near-vm-runner/src/tests/ts_contract.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmer_runner.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/state_viewer/mod.rs

This refactor primarily tries to make the `VM::run` signature clearer.
It is also a preparation step towards changing where contract loading
gas costs are charged.

refactor: VM::run returns an enum instead of tuple

---

core/primitives/src/types.rs
core/store/src/trie/mod.rs
core/store/src/trie/trie_storage.rs
core/store/src/trie/trie_tests.rs
runtime/near-vm-logic/src/dependencies.rs
runtime/near-vm-logic/src/logic.rs
runtime/near-vm-logic/src/mocks/mock_external.rs
runtime/runtime/src/ext.rs
runtime/runtime/src/lib.rs

Recent experiments show that cost for reading kv pair from the chunk cache should be somewhere between 37 and 200 Mgas. Given that we use a safety multiplier 3 and that we could build an example where ~1M nodes are read from the chunk cache, we have to add the new cost to the runtime config.
The first step is adding a separate counter for that, and updating trie storage tests appropriately. This PR shouldn't affect the protocol in any way.
Next steps will be:
* add new cost to runtime config with an estimation function
* return to https://github.com/near/nearcore/pull/6450 and charge this cost there
* Updating trie storage tests.

feat: separate counter for chunk nodes cache

---

core/primitives-core/src/config.rs
core/primitives/res/runtime_configs/53.json
core/primitives/src/runtime/config_store.rs
runtime/near-vm-runner/src/wasmer2_runner.rs

200*1024 is still just under 2MiB, which we can definitely afford, given a default stack size on glibc systems is 8MiB.

Increase the secondary stack cleck limit

---

core/store/src/db.rs
core/store/src/lib.rs
core/store/src/trie/shard_tries.rs
integration-tests/src/mock_network/setup.rs
tools/chainsync-loadtest/src/main.rs

Two related tangentially-related changes here:
* Remove extra clones from DBTrasaction by make its API more natural in terms of ownership
* And then make it and related things private to near_store, and not world-visible

refactor: DBTransaction

---

chain/chain/src/missing_chunks.rs
chain/client/src/client_actor.rs
chain/jsonrpc/res/chain_info.html
core/primitives/src/views.rs

This PR adds a section for blocks with missing chunks to the chain info debug page that displays hash and height info of those blocks.
[CP-24](https://nearinc.atlassian.net/browse/CP-24)
- Under `nearcore` directory, launch localnet using command `nearup stop && nearup run localnet --binary-path ./target/release`
- Open your browser and go to http://[host_address]:3030/debug/chain_info
(Positive case TBD)
- @mm-near

add blocks with missing chunks on chain page

---

pytest/lib/cluster.py

The filed has been removed ages ago and currently results in warnings:
WARN nearcore::config: .../config.json: encountered unrecognised fields: ["rpc.?.metrics_addr"]
Stop setting the value in tests.

pytest: don’t set rpc.metrics_addr

---

nightly/pytest-contracts.txt

The cuts close to five minutes run time it’s allotted which sometimes
makes it miss the deadline and fail making the test flaky.  Increase
the timeout.

nightly: increase timeout for contracts/gibberish.py test

---

nearcore/src/lib.rs

So far recompress_storage assumed that a single database will use 512
file descriptors at the most and thus set NOFILE limit to three times
that (so it can open two databases simultaneously and have whole bunch
of descriptors to spare).  However, this number is now configurable
and may be larger.  Change the command to take into consideration what
is the actual configured max_open_files number.

nearcore: take max_open_files into consideration in recompress_storage

---

Cargo.lock
chain/network/src/routing/edge_validator_actor.rs
chain/network/src/routing/routing_table_actor.rs
chain/network/src/test_utils.rs
integration-tests/Cargo.toml
integration-tests/src/tests/network/ban_peers.rs
integration-tests/src/tests/network/churn_attack.rs
integration-tests/src/tests/network/full_network.rs
integration-tests/src/tests/network/peer_handshake.rs
integration-tests/src/tests/network/routing.rs
integration-tests/src/tests/network/runner.rs

Replaced System::stop with Context::stop.
Fixed the testing framework by making sure that all actions were completed.
Removed flakiness by retrying the AddEdge action until success.
After this refactor:
1. each node is spawned in a separate actix runtime (so that one node cannot stop another)
2. the framework is now executed as a tokio future, rather than an actor (to simplify the flow and isolate it from the nodes).

Fixed network integration tests which were succeeding even though nodes were crashing in the middle.

---

core/store/src/db.rs

rocksdb::Error is just an opaque wrapper around a string error
message.  Peeling off the rocksdb::Error wrapper doesn’t really
loose any information.  As such, simplify DBError so that rather
than storing rocksdb::Error it stores the message directly.
Apart from simplifying the types it will make it possible to use
DBError for errors which come from our code as opposed to be limited
to only carry errors from RocksDB.

db: store error message directly in DBError

---

CHANGELOG.md
Cargo.lock
core/store/Cargo.toml
core/store/src/db.rs
core/store/src/lib.rs

Increase the default max_open_files from 512 up to 10k;
Set ulimit for the number of files from neard to 11025.

Increase max open files parameters in rocksdb up to 10K

---

pytest/tests/sanity/state_sync_fail.py

this started failing after https://github.com/near/nearcore/pull/6326 because
that PR made it so that the process actually dies when the client actor panics.
Before that change, the node stays up but gives HTTP errors when trying to ask
for stuff that the client actor has to provide. Now that the node will actually exit,
we'll get a ConnectionError instead of an HTTPError

pytest: fix state_sync_fail.py

---

core/primitives-core/src/config.rs
core/primitives-core/src/profile.rs
runtime/near-test-contracts/test-contract-rs/src/lib.rs
runtime/near-vm-errors/src/lib.rs
runtime/near-vm-logic/src/alt_bn128.rs
runtime/near-vm-logic/src/array_utils.rs
runtime/near-vm-logic/src/lib.rs
runtime/near-vm-logic/src/logic.rs
runtime/near-vm-logic/src/tests/alt_bn128.rs
runtime/near-vm-logic/src/tests/mod.rs
runtime/near-vm-runner/src/tests/rs_contract.rs
runtime/runtime-params-estimator/src/lib.rs

Semantic changes:
* The input now is a raw slice (no length in front)
* Costs are now computed in terms of number of elements to operate on,
not in terms of number of bytes
* Sublinear component of the multiexp_cost is removed. Manual sanity checking shows that this is indeed can be upper-bounded by a linear function, in terms of time and memory usage. Our estimator should give us upper-bound. That is, we should calculate sublinear component if we want to make the cost *lower*, it's efficiency, not safety, concern.
* We no longer have a limit of 5_000 elements for multiexp. I believe that the reasoning that there's a potential memory exhaustion is flawed. The size of the internal buffer is exponential in the *logarithm* of input, that is, it is linear (sublinear, actually, it's 2^log_10 …

refactor: cleanup nightly alt_bn128 API 

---

CHANGELOG.md
neard/src/cli.rs
tools/state-viewer/src/cli.rs

We’re using kebab-case for command line options (e.g. --chain-id,
--num-shards, --csv-file etc) but for whatever reason use snake_case
for commands (e.g. view_state, check_block etc.).  This leads to user
confusion as one needs to use both types of naming.
Fix this inconsistency by using kebab-case for subcommands and, for
backwards compatibility, leaving snake_case names as aliases so they
continue to be valid.
Alias for recompress-storage is not kept because it’s a new command
and as such there is no backwards compatibility issues with dropping
recompress_storage.
While at it, remove a few redundant clap(name) directive.  Clap
automatically derives name of the subcommand from the variant name
usually there is no need to explicitly specify it.
The diff in help between the old and the …

neard: prefer kebab-case for subcommand names

---

Cargo.lock
integration-tests/Cargo.toml
integration-tests/src/mock_network/setup.rs

setup_mock_network() can start up a very large number of threads if
get_num_state_parts() returns a big number, which makes it difficult
to run the tool successfully with mainnet data. Fix it by using rayon
to split the work among threads in a pool.

start-mock-network: limit the number of worker threads

---

runtime/runtime-params-estimator/src/config.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/main.rs

Use a single debug flag rather than a list of debug options.

refactor: Simplify estimator debug flags

---

Cargo.lock
runtime/near-vm-runner/Cargo.toml

Since 2.2.0 this includes a reproducibility fix to generated machine code as well as a performance improvement achieved by disabling functionality we don't utilize.

Upgrade wasmer-near to 2.2.2

---

integration-tests/src/tests/client/process_blocks.rs

The `rs_contract()` uses all the latest protocol features (ie, it
changes over time). This is something you want most of the time, (as we
test against the latest protocol), *but* for upgradability tests
specifically this is wrong -- for those tests, we want to guarantee that
only the base protocol is being used.

test: use base contract for upgradability tests

---

chain/client-primitives/src/types.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs

For an unknown reason the test requests a block before any blocks are produced.

Fix a flaky test by adding a retry for requesting blocks

---

chain/chain/src/chain.rs
chain/chain/src/test_utils.rs
chain/chain/src/tests/gc.rs
chain/client/src/tests/query_client.rs
core/chain-configs/src/client_config.rs
core/chain-configs/src/lib.rs
genesis-tools/genesis-populate/src/lib.rs
integration-tests/src/tests/client/process_blocks.rs
nearcore/src/config.rs
nearcore/src/runtime/mod.rs
test-utils/runtime-tester/src/run_test.rs
test-utils/store-validator/src/main.rs
testdata/example-config-gc.json
tools/restored-receipts-verifier/src/main.rs
tools/state-viewer/src/apply_chunk.rs

Adds `num_epochs_to_store_data` option to `config.json` file.  This
configures how many epochs back from the current epoch a non-archival
node will keep.  This used to be hard coded to five but can now be
configured.  Note that values below three are mapped to three, that
is, node will always keep data for at least three last epochs.

add num_epoch_to_store to gc_config

---

integration-tests/src/tests/client/process_blocks.rs

See https://github.com/near/nearcore/pull/6649, as the changes here
are basically copy-pasted from there. This test does the same protocol
upgrading, and also currently fails when the new upgrade schedule is
set to a time in the future.

integration-tests: fix verify_contract_limits_upgrade() protocol upgrading

---

Cargo.lock
chain/network/src/stats/metrics.rs
core/metrics/Cargo.toml
core/metrics/src/lib.rs

If creating a counter fails don’t store it in the peer_messages hash
in NetworkMetrics.  There is no point in keeping a None entry in the
hash.  This simplifies inc and inc_by methods which no longer have to
handle the case of None being stored in the hash map (only the case of
value missing from the hash which they were handling already).
With that, inc_counter_opt and inc_counter_by_opt functions are no
longer used.  Just like a whole slew of other functions which
manipulate metrics defined in near_metrics crate.  Delete all of them.

metrics: refactor NetworkMetrics and remove bunch of dead functions

---

nearcore/src/lib.rs

Rather than panicking or aborting the process, return errors which
happen when applying database migration to propagate them up the call
stack.
While at it, prefer `anyhow::Result<T>` to `Result<T, anyhow::Error>`.
Issue: https://github.com/near/nearcore/issues/6622

nearcore: propagate errors when applying migrations

---

core/store/src/db.rs

Rather than asserting and unwrapping results in ensure_max_open_files_limit
function, report the failures as errors which are propagated up through the
RocksDBOptions::open method.
Issue: https://github.com/near/nearcore/issues/6622

store: propagate error from ensure_max_open_files_limit i/o panicking

---

pytest/lib/utils.py

utils.wait_for_blocks function would log each time a new block was
encountered.  However, if a test used utils.poll_blocks instead that
log would not be generated.  Move the logging to the latter so that
tests using it are more verbose.

pytest: move logging from wait_for_blocks to poll_blocks

---

nightly/fuzz.toml

Before that, the fuzzer would OOM in a way that could be reproduced
only with the sanitizers enabled.

fuzz: bump near-vm-runner fuzzer to 3G max RAM

---

CHANGELOG.md
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/stats/metrics.rs

Remove `near_<msg-type>_total` metrics.  Data in those metrics are
available in a `near_peer_message_received_by_type_total` metric with
a `type` label which is easier to deal with.
Similarly, `replace near_<msg-type>_bytes` metrics with a single new
`near_peer_message_received_by_type_bytes` metric using `type` label.
The `near_<msg-type>_dropped` metric is left as is for now but will be
dealt with in another change.

network: remove near_<msg-type>_{total,bytes} metrics

---

core/store/src/db.rs
core/store/src/migrations.rs
nearcore/src/lib.rs

All places which used RocksDB::get_version were already able to return
an error which makes propagating an error when reading the version
trivial.
Issue: https://github.com/near/nearcore/issues/6622

store: propagate errors when reading db version rather than panicking

---

Cargo.lock
core/o11y/src/lib.rs
core/store/Cargo.toml
core/store/src/lib.rs

debug_assert is for cases where assert condition is too costly to evaluate.
If the reason for using debug_assert is to avoid the node crashing in prod, than
log_assert is strinctly better: it crashes the node in debug, but logs in
release.

refactor: introduce log_assert to be used instead of missused debug_asserts

---

Cargo.lock
core/o11y/Cargo.toml
core/o11y/src/lib.rs

This little utility is quite useful during ad-hoc debugging sessions.
Having it accessible in the ubiquitious o11y crate would be convenient.

feat: add print_backtrace function for easier debugging

---

Cargo.lock
deny.toml
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/cache.rs
runtime/near-vm-runner/src/imports.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/wasmer2_runner.rs

This makes the changes necessary on the nearcore side to start
experimenting with – and testing – the branch of runtime implementing
0-copy deserialization.
@Ekleog I wonder how difficult would it be to throw this at the fuzzing infrastructure?

Redirect to the 0-copy wasmer branch

---

runtime/near-vm-runner-standalone/src/main.rs
runtime/near-vm-runner-standalone/src/script.rs
runtime/near-vm-runner/src/preload.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/tests/compile_errors.rs
runtime/near-vm-runner/src/tests/contract_preload.rs
runtime/near-vm-runner/src/tests/rs_contract.rs
runtime/near-vm-runner/src/tests/runtime_errors.rs
runtime/near-vm-runner/src/tests/ts_contract.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmer_runner.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/state_viewer/mod.rs

Replace results without outcome with no-op outcome results.
Note that `VMOutcome` itself cannot be no-op, it needs to be considered
in conjunction with the error. Therefore, the constructor is on the
`VMResult` and requires an error.
If we move the error to a field inside `VMOutcome`, this will also
become clearer.

refactor: Clean up VMResult::NotRun

---

chain/chain/src/store_validator.rs
core/store/src/db.rs
core/store/src/lib.rs
nearcore/src/lib.rs

This method is an deliberate escape hatch, and shouldn't be used outside of auxilary code like migrations which wants to hack on the database directly.
Note: this also tightens some asserts a bit, it *should* be fine but I wouldn't be surprised if some tests fail...

feat: introduce StoreUpdate::set_raw escape hatch

---

CHANGELOG.md
Cargo.lock
chain/client/Cargo.toml
chain/client/src/info.rs
chain/client/src/metrics.rs

Introduce near_build_info with a constant value 1 which exports
node’s build information as labels.  Specifically, release, build and
rust version are exported.  See [1] for description how this metric
can be used.
[1] https://www.robustperception.io/exposing-the-software-version-to-prometheus
While at it, set near_node_protocol_version and near_node_db_version
only once (since they are always set to the same value) rather than
doing so each time statistics are printed.  Added bonus of this is
that those metrics are now set immediately when node starts rather
than the first time the stats info line is printed in the log.
Issue: https://github.com/near/nearcore/issues/5979

client: introduce `near_build_info` metric with node’s release info

---

chain/client/src/metrics.rs

I’ve changed implementation of the function during developement and
forgotten to update the docstring resulting in wrong description
getting commited.  Fix that.

client: fix docstring of metrics::export_version

---

integration-tests/src/tests/nearcore/rpc_nodes.rs

by retrying the request is the finality cannot be resolved to a block due to no blocks being produced.

Fix a flaky test `test_query_rpc_account_view_account_doesnt_exist_must_return_error`

---

runtime/runtime-params-estimator/estimator-warehouse/src/db.rs

SQL condition to select data from icount comparison also checked for
time metric condition, which lead to an empty set to be compared.

fix(contiunous estimation): Icount comparison

---

debug_scripts/request_chain_info.py

small fix: resolve undefined variable `chunk_id` by referencing `args`

fix: 'chunk_id' is not defined in request_chain_info.py

---

core/chain-configs/src/client_config.rs
nearcore/src/config.rs

this was inadvertently changed to 5 in https://github.com/near/nearcore/pull/6604

fix(chain): revert the gc_blocks_limit default to 2

---

core/store/src/db.rs
core/store/src/lib.rs
nearcore/src/lib.rs

The setters in RocksDBOptions are never used and the object is only
ever created with it’s default values.  As such, the structure
provides no value.  Get rid of it.

store: get rid of RocksDBOptions

---

integration-tests/src/tests/client/process_blocks.rs
runtime/near-test-contracts/src/lib.rs
runtime/near-vm-runner/src/prepare.rs
runtime/near-vm-runner/src/tests/compile_errors.rs

Fixes a regression introduced in
7f1672f89f1700eb3601f742759ac2742f7007aa
This is a backport of #6698 to the 1.26.0 release.

1.26.0: Count function imports towards the function limit

---

chain/client-primitives/src/types.rs
chain/network-primitives/src/network_protocol/mod.rs
chain/network-primitives/src/types.rs
chain/network/src/network_protocol.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/types.rs
utils/near-performance-metrics-macros/src/lib.rs
utils/near-performance-metrics/src/stats_disabled.rs

strum::AsStaticStr derive and trait are deprecated.  Replace most uses
of them by strum::AsRefStr derive which serves very similar purpose.
Unfortunately there is a difference where the latter returns a reference
with lifetime same as ‘self’.  utils/near-performance-metrics currently
depends on NetworkClientMessages and NetworkViewClientMessages implementing
the former and being convertible to `&'static str`.  Because of that, those
two still use strum::AsStatirStr.

strum: reduce usage of deprecated strum::AsStaticStr

---

chain/epoch_manager/src/lib.rs
core/store/src/columns.rs
core/store/src/db.rs
core/store/src/lib.rs
core/store/src/trie/shard_tries.rs

We have three classes of columns in the DB:
* read-write columns which are modified arbitrary
* insert only columns, where each value is written once and exists
unchanged until GCed. You can call such columns immutable.
* RC columns, which are also immutable, but allow repated writes which
bump rc.
Today, we use the same operations for working with both read-write
and write-once columns. In this PR, I want to seprate that into two
semantically distinct operations (which would allow us to have better
runtime and compile-time checks):
* `set` for read-write columns
* `insert` for insert-only columns
The main motivation is to make reasoning about the code easier -- if a
bit of code only does inserts and no sets, it can be reorderd relatively
easily.

feat: add runtime checks for "immutable" columns

---

chain/client/src/client_actor.rs
chain/jsonrpc/res/epoch_info.html
core/primitives/src/views.rs

In `HeaderSync`, there is no block available. Debug page actually crashes in this mode by trying to access block 0. This PR fixes this issue.
[CP-60](https://nearinc.atlassian.net/browse/CP-60)
- Build with `make neard`
- Under `nearcore` directory, launch testnet using command `nearup stop && nearup run testnet --binary-path ./target/release`
- Open your browser and go to http://[host_address]:3030/debug/epoch_info
- Verify that the page works in `HeaderSync` mode, too (You can clear all files under `~/.near/testnet` to force `HeaderSync`, but remember to set`"enable_debug_rpc": true`, under `rpc`, in `~/.near/testnet/config.json`)
- Build with `make neard`
- Under `nearcore` directory, launch localnet using command `nearup …

fix debug page crash when there is no block available

---

runtime/runtime-params-estimator/src/main.rs

Add nightly feature flags to build inside docker, to allow icount
estimates of nightly features without hackery.

feat(params-estimator): nightly feature estimation

---

integration-tests/src/tests/runtime/sanity_checks.rs
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status.snap

Issue: https://github.com/near/nearcore/issues/4961

runtime: make test_cost_sanity independent of receipt hash

---

README.md

The original urls of the tutorials and api docs will all redirect to [getting started](https://docs.near.org/docs/develop/basics/getting-started), this pr corrects them.

doc: update some urls in readme

---

chain/network-primitives/src/network_protocol/mod.rs
chain/network/src/network_protocol/mod.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/stats/metrics.rs

The advantage of strum::IntoStaticStr derive is that provided into
method returns a static reference rather than a one with self’s
lifetime which also creates a borrow on self.
Issue: https://github.com/near/nearcore/issues/6704

network: replace strum::AsStrRef derives with strum::IntoStaticStr

---

chain/network/src/tests/peer_actor.rs
chain/network/src/types.rs

The latter is deprecated so use the former which has equivalent
behaviour.

network: prefer strum::IntoStatiStr than strum::AsStaticStr

---

chain/client/src/client_actor.rs
core/chain-configs/src/client_config.rs
core/store/src/lib.rs
nearcore/src/config.rs

This PR lets us verify whether the performance impact is caused by RocksDB statistics or by nearcore re-exporting those metrics. If the latter, we can optimize the code to reduce the performance impact.

Separate collecting rocksdb statistics and re-exporting them to prometheus

---

chain/network-primitives/src/types.rs
chain/network/src/network_protocol/mod.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/stats/metrics.rs
chain/network/src/types.rs

We will disable borsh encoding once node all versions >= PEER_MIN_ALLOWED_PROTOCOL_VERSION support protobuf decoding. Nevertheless, this metric will allow us to observe whether protobuf is actually used (as borsh is still enabled as a fallback).

added a metric monitoring Proto/Borsh encoding for peer connections

---

chain/chain/src/chain.rs
integration-tests/src/tests/client/process_blocks.rs

Refactoring ChainUpdate::process_block to move the processing before apply_chunks to a new function preprocess_block. Later, the preprocess_block function will be moved to Chain, because there should be no chain update in this function.

Add function preprocess_block

---

chain/client/src/client_actor.rs

EpochManager::get_validator_info call querying information by block
hash turns out to be quite expensive while node is synchronising.
Normally, EpochManager maintains validator information up to the
latest final block.  With that, calling get_validator_info with
a block hash usually needs to iterate over only a handful of blocks
until it hits the latest final block and then can read the already
aggregated data.
However, while node is syncing, the aggregated data is not maintained.
This means that getting validator info for a given block requires
iteration over all blocks until start of the epoch.  This is an
expensive operation.
EpochManager::get_validator_info is called each time stats line is
generated.  When synchronising this ends up taking a up all of the
processing time to the point …

client: don’t update validators produced counters when syncing

---

pytest/lib/peer.py
pytest/lib/proxy.py

This fixes the python tests which were broken by https://github.com/near/nearcore/commit/0d879ac
nayduck run: https://nayduck.near.org/#/run/2491
There are 8 tests that are still failing, but they started failing even before my PR was merged.

added ignoring unparseable messages

---

chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/jsonrpc/res/chunk_info.html
chain/jsonrpc/res/debug.html
chain/jsonrpc/src/lib.rs
core/primitives/src/views.rs

This PR adds the skeleton of the chunk info debug page.
[CP-83](https://nearinc.atlassian.net/browse/CP-83)
- Under `nearcore` directory, launch localnet using command `nearup stop && nearup run localnet --binary-path ./target/release`
- Open your browser and go to http://[host_address]:3030/debug/
- Expect to see the link "Chunk Info"
- Click the link "Chunk Info"
- @mzhangmzz 
- @mm-near

add chunk info debug page

---

Cargo.lock
core/o11y/Cargo.toml
core/o11y/src/lib.rs
neard/src/cli.rs
tools/chainsync-loadtest/src/main.rs
tools/indexer/example/src/main.rs
tools/restaked/src/main.rs
tools/storage-usage-delta-calculator/src/main.rs

Tested by running a betanet node for 5 minutes. Both runs generated ~3.6M log lines, but file sizes differ 1.5x.
--color=always - 1.5GB
--color=never - 1.0GB
Fix #6548

Option to disable colored log output.

---

integration-tests/src/tests/standard_cases/mod.rs

This essentially enshrines the current buggy behavior to fix
non-deterministic test failures. Proper fix is tracked at
https://github.com/near/nearcore/issues/6724

test: work-around flaky tests

---

Cargo.lock
chain/chain/Cargo.toml
chain/chain/src/tests/simple_chain.rs

With insta it’s much simpler to update the hashes when they change.
Furthermore, observe that empty_chain test doesn’t actually test
anything that build_chain doesn’t test already so remove it.

chain: update build_chain test to use insta

---

Cargo.toml

Given that our storage-related code is crash-safe, we should be able to set panic=abort so that no panic goes unnoticed.
AFAICT the test targets are ignoring this setting:
https://github.com/alexcrichton/cargo/blob/master/src/cargo/core/profiles.rs#L114
therefore our "should_panic" tests still work (at least on my workstation).

added panic=abort to the whole workspace

---

chain/network/src/peer_manager/peer_store.rs

`PeerStore` maintains its internal cache in two maps:
https://github.com/near/nearcore/blob/dddbb6a9691d0be59bef59cf50bbf096e1b617c8/chain/network/src/peer_manager/peer_store.rs#L47-L51
In [`remove_expired`](https://github.com/near/nearcore/blob/dddbb6a9691d0be59bef59cf50bbf096e1b617c8/chain/network/src/peer_manager/peer_store.rs#L282-L299) peers are deleted (via `delete_peers`) *only* from `peer_states`
but not from `addr_peers`.
Assume a peer with address `x` was deleted via `remove_expired`. When learning
about a new indirect peer which has the same address `x`, that information is
not stored due to `x` still being in `addr_peers`:
https://github.com/near/nearcore/blob/dddbb6a9691d0be59bef59cf50bbf096e1b617c8/chain/network/src/peer_manager/peer_store.rs#L381-L389
This PR updates …

fix(network): PeerStore's cache gets out of sync

---

test-utils/actix-test-utils/src/lib.rs

I am not sure why we were catching ctrl+c in the first place. This was
introduced in #4229 I think. But messing up with signal handlers in
tests doesn't feel right and, indeed, prevents tests from being killed.
Test Plan
---------
Manual testing: running `cargo t -p integration-tests` and then killing
it in the middle with ctrl+c leaves the test running in the background
before this PR, and properly kills the process after.

fix: make sure that `cargo test` can be killed with ctrl+c

---

Cargo.lock
chain/chain-primitives/src/error.rs
chain/chain/Cargo.toml
chain/chain/src/tests/challenges.rs
chain/chain/src/tests/simple_chain.rs
chain/client-primitives/src/types.rs
chain/client/src/client.rs
chain/client/src/view_client.rs
integration-tests/src/tests/client/challenges.rs
integration-tests/src/tests/client/process_blocks.rs

This changes from `IOErr(String)` to `IOErr(io::Error)`, so we don't
lose specific error. The consequence here is that Error is no longer Eq,
so the tests are adjusted accordingly.
In general, errors should be neither Eq nor Clone, they are not values.
Often times, when an error feels like a value, it means that the error
type wants to be split in two, from `Result<T, Error>` into
`Result<Result<T, InvalidTx>, io::Error>` where the outer Error captures
real errors/exceptions (such as the database having a bad day), and
internal error is just a normal outcome of a request processing.

refactor: don't type-erase IO errors

---

chain/client/src/adversarial.rs
chain/client/src/client_actor.rs
chain/client/src/lib.rs
chain/client/src/test_utils.rs
chain/client/src/view_client.rs
integration-tests/src/tests/network/runner.rs
nearcore/src/lib.rs
tools/mock_node/src/setup.rs

Provide an ‘empty’ definition of AdversarialControls which is used
when test_features compilation feature is not enabled.  This empty
definition provides accessors to all adversarial controls always
returning non-adversarial values.
Based on the test_features flag either the empty definition (if it’s
missing) or definitinons where adversarial behaviour can be enabled
(if it’s present) is used.
With this refactoring most `#[cfg(feature = "test_features")]` guards
can be removed.  This simplifies the code by removing some of the
syntax noise.
While at it, also change the controls such that rather than using
RwLock all the options are stored in atomic values.  This further
simplifies the code slightly.

chain: refactor AdversarialControls to reduce conditional compilation

---

runtime/runtime-params-estimator/estimator-warehouse/src/check.rs
runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-4.snap

Simple division seems to do the trick:
* if both numerator and denominator are zero, we get a NaN, which isn't
larger then threshold.
* if only deom is zero, we get +inf

fix: don't show 0 -> 0 changes in continuous estimation

---

core/store/src/config.rs

The ‘pub’ is not necessary any longer.

store: remove ‘pub’ from StoreConfig constants

---

runtime/runtime-params-estimator/test-contract/Cargo.toml
runtime/runtime-params-estimator/test-contract/build.sh
runtime/runtime-params-estimator/test-contract/src/lib.rs

docs: https://doc.rust-lang.org/cargo/reference/profiles.html#strip

refactor: use built-in option to strip compiled WASM

---

runtime/near-vm-logic/src/logic.rs

Needed to retain functionality for unit testing within the SDK
https://github.com/near/near-sdk-rs/pull/820 is the matching PR to the SDK (and other changes needed when updating for reference)

feat: expose logs and receipt metadata from VMLogic

---

Cargo.toml

Tagged: https://github.com/near/nearcore/releases/tag/crates-0.13.0
Check here for a full changelog: https://github.com/near/nearcore/compare/crates-0.12.0...crates-0.13.0
Tested `cargo package` on each public crate locally, they all compile independently of the workspace. We should be good to go.

chore: bump version to 0.13.0

---

Cargo.lock
chain/jsonrpc/client/Cargo.toml
chain/jsonrpc/fuzz/Cargo.toml
chain/jsonrpc/jsonrpc-tests/Cargo.toml
chain/rosetta-rpc/Cargo.toml
chain/telemetry/Cargo.toml
nearcore/Cargo.toml

Following https://github.com/near/nearcore/issues/6694

chore: update `awc` to stable

---

core/store/src/db.rs

Introduce RocksDB::cf_handle method which encapsulates unsafe access
to the vector of column family pointers.  This eliminates bunch of
unsafe blocks consolidating them into that method.  This makes it
easier to reason about the code and its safety.

store: introduce RocksDB::cf_handle method

---

core/primitives-core/src/config.rs

I forgot to update the test config when merging #6787.
Functionally, it makes no difference. But to make code less confusing,
let's still use the stabilized cost values that reflect elements instead
of bytes.

test: use new alt_bn costs in test config

---

core/o11y/src/lib.rs
neard/src/cli.rs

`--verbose` flag is a bit confusing in that it does requires an
argument.  This isn’t contrary to many other Linux utilities which
expect `--verbose` to take no value.
Change the flag such that it accepts an *optional* argument so it can
be passed as plain `--verbose` without any target.
By the way, note that `neard --verbose=<target>` is roughtly equivalent
to `RUST_LOG=info,<target>=debug`.  We might consider deprecating
usage of the flag with argument in favour of RUST_LOG.

neard: support no-value --verbose flag

---

Cargo.lock
core/store/Cargo.toml
core/store/src/columns.rs
core/store/src/db.rs

RocksDB and TestDB both create vectors which are meant to map from
column to some value.  The issue is that the way they are created
assumes that variants in DBCol are all listed in order of their
values, the values are all unique and there are no holes.  In other
words, removing or rearranging variants of DBCol causes things to
break.
Solve that by using enum_map::EnumMap which creates fixed-size
constant-access arrays (same as a Vec approach) but allow the map to
be indexed by the enum value itself which avoids all of the above
issues.
Furthermore, introduce RocksDB::cf_handle method which consolidates
all bunch of unsafe blocks into a single unsafe block in that method.
Having a single unsafe block makes it easier to reason about the
safety guarantees.

store: prefer enum_map::EnumMap to strum’s count and iterator

---

chain/rosetta-rpc/src/lib.rs

Adding web data with `Data::from(genesis.clone())` makes the type of
the data to be `Data<Genesis>` while handler functions expect
`Data<Arc<Genesis>>`.  Since the two types differ, actix-web cannot
find a match which results in a 500 error.  Changing argument type
fixes the issue.
Issue: https://github.com/near/nearcore/issues/6599

rosetta: fix after actix update

---

integration-tests/src/tests/runtime/sanity_checks.rs
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap

The test might pass or fail depending on whether you `cargo t` or `cargo
t -p integration-tests`.
The reason for that is that `preserve_order` feature of serde_json
differs depending on which cargo command you invoke. That in turn leads
to different input to the contract.
There's two ways we can fix this:
* enableing preserve_order feature for integration tests crate
* formatting the JSON manually
I went with the second option as it seems simpler and more robust.

test: fix non-determinisit tests

---

chain/jsonrpc-adversarial-primitives/Cargo.toml
chain/jsonrpc-adversarial-primitives/src/lib.rs
chain/jsonrpc/Cargo.toml

Tracking issue: https://github.com/near/nearcore/issues/6850
Cleanup feature flags in `near-jsonrpc-adversarial-primitives`.

chore(jsonrpc): cleanup adversarial-primitives

---

chain/chain/src/chain.rs

I *think* the old code caused the following flaky failure for me from
time to time:
thread 'tests::client::process_blocks::access_key_nonce_range_tests::test_chunk_transaction_validity' panicked at \
'assertion failed: `Other("Invalid Transactions")` does not match `Error::InvalidTransactions`', \
integration-tests/src/tests/client/process_blocks.rs:3811:9
failures:
tests::client::process_blocks::access_key_nonce_range_tests::test_chunk_transaction_validity
Note that this might be a behavior-changing change. I don't know the
surrounding code well enough to judge whether this is problematic. But
the current code does look very much like a bug.

fix: don't type convert errors to strings unnecessary

---

integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/runtimes.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs

assert_matches! should print the miss-matched variant on failure.
Specifically, I'd love to see why `test_chunk_transaction_validity`
fails for me locally from time to time.

test: more helpful assertion messages

---

core/primitives/src/block.rs
core/primitives/src/block_header.rs
core/primitives/src/test_utils.rs
core/primitives/src/views.rs
integration-tests/src/tests/client/challenges.rs
integration-tests/src/tests/client/process_blocks.rs
test-utils/testlib/src/process_blocks.rs

Prep work for #6811
This is a somewhat large change of the internal model, as now this types
are mostly immutable. This seems reasonable -- I can imagine us doing
things like fetching a block on the database thread, putting it into the
cache and handling a reference to it to HTTP server.
It seems that blocks are immutable in practice -- the only exception are
some testing utilities, but `Arc::make_mut` deals with those cases.

refactor: make blocks and headers cheaply clonable

---

Cargo.lock
chain/indexer/Cargo.toml
chain/indexer/src/streamer/mod.rs
chain/network/src/peer_manager/peer_store.rs
core/store/benches/store_bench.rs
core/store/src/config.rs
core/store/src/db.rs
core/store/src/lib.rs
core/store/src/migrations.rs
genesis-tools/genesis-populate/src/lib.rs
genesis-tools/genesis-populate/src/main.rs
genesis-tools/genesis-populate/src/state_dump.rs
nearcore/benches/store.rs
nearcore/src/config.rs
nearcore/src/lib.rs
nearcore/src/migrations.rs
nearcore/src/runtime/mod.rs
neard/src/cli.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/main.rs
runtime/runtime-params-estimator/src/testbed.rs
runtime/runtime-params-estimator/src/vm_estimator.rs
test-utils/runtime-tester/src/run_test.rs
test-utils/store-validator/src/main.rs
tools/mock_node/src/setup.rs
tools/restored-receipts-verifier/src/main.rs
tools/state-viewer/src/cli.rs
tools/state-viewer/src/rocksdb_stats.rs

Introduce near_store::StoreOpener as a new interface for opening
storage.  This gets rid of create_store and create_store_with_config
functions and converts all users of those into users of StoreOpener.
While doing that, convert a few uses of create_store (i.e. calls which
ignore StoreConfig) into ones where the configuration is taken into
consideration.
Issue: https://github.com/near/nearcore/issues/6857

store: introduce StoreOpener; get rid of StoreConfig::read_only

---

runtime/near-vm-runner/src/prepare.rs

With this figuring out why a deserialization error is triggered should be as easy as setting `RUST_LOG="info,near_vm_runner=debug" neard run`

feat: log information when hitting a deserialization error

---

chain/chain/src/chain.rs
chain/chain/src/validate.rs
chain/chunks/src/chunk_cache.rs
chain/chunks/src/lib.rs
chain/client/src/test_utils.rs
chain/client/src/tests/catching_up.rs
chain/network-primitives/src/network_protocol/mod.rs
core/primitives/src/sharding.rs

Change SharedChunkHeader::prev_block_hash method to return a reference
(rather than cloning the hash) so that prev_block_hash_ref method
becomes unnecessary and can be deleted.
Convert all users of all those methods as required.  In a few plasecs
that allowed us to avoid cloning but in others we had to clone either
because we wanted a clone or to satisfy borrow checker.

core: get rid of SharedChunkHeader::prev_block_hash_ref

---

pytest/lib/mocknet.py

Mocknet scripts assume the nodes run on port 3030, for example here https://github.com/near/nearcore/blob/master/pytest/lib/mocknet_helpers.py#L10, but it's not the only reference to port 3030.
After a recent infrastructure change the nodes run on port 4040 by default.
This PR sets a port that works well with mocknet. An alternative would be to update mocknet scripts to use a different port, but that requires more maintenance.

Run mocknet nodes on port 3030

---

core/crypto/src/key_file.rs

mode_t is u16 not u32 on apple os https://github.com/rust-lang/libc/blob/master/src/unix/bsd/apple/mod.rs#L11

Fix local build on mac

---

Cargo.lock
chain/network/Cargo.toml
chain/network/src/test_utils.rs

closes https://github.com/near/nearcore/issues/6826
We have circular depedencies between PeerManager and Client, which we
break via `dyn PeerManagerAdapter`. As this is a real cycle, we close it
at runtime by calling `set_recipient`. But today nothing prevents client
from sending message to network before that, and indeed that happens if
we are unlucky with timing.
This commit fixes the issue by making `PeerManagerAdapter` APIs block
until the loop is closed.
<hr/>
After finishing the implementation, I realized that this might not be the ideal solution. It seems that actix has the API ([Actor::create](https://docs.rs/actix/latest/actix/prelude/trait.Actor.html#method.create)) for tying such loop nicely, where you can get actor's address before creating the actor. We use it, for example, …

fix: race in NetworkRecepient 

---

Cargo.lock
core/crypto/Cargo.toml
core/crypto/src/key_file.rs

Permissions::from_mode is portable across unixes and requires u32. But
libc::mode_t isn't guaranteed to be u32, so the current code might break
on non-Linux Unix.
Instead of relying on platform-specific libc, just specify mode directly
using traditional octals.

fix: platform-compatibility bug in key_file

---

pytest/lib/cluster.py
pytest/tests/sanity/gc_after_sync.py

e.g.: https://nayduck.near.org/#/test/322670
After waiting for the node that's been restarted to sync, the block at
height HEAD-10 might not be stored since state sync will start at the
beginning of the epoch, which may be after that point. So start checking
blocks at max(HEAD-10, epoch_start) instead

fix(pytests): fix gc_after_sync.py failure

---

integration-tests/src/tests/runtime/sanity_checks.rs

Adds `contract_sanity_check_used_gas`, which calls host function `used_gas`
multiple times (within a metered block, in different metered blocks) and returns
the values returned by `used_gas`.
This new test contract is then called by `test_sanity_used_gas`, which
compares the differences between `used_gas` return values to the `base` cost
of `ExtCostConfig` (i.e. the cost of executing `used_gas`).
(ref. [gas instrumentation](https://nomicon.io/RuntimeSpec/Preparation#gas-instrumentation))
Issue #6422

test: verify operation of host function `used_gas`

---

core/o11y/src/lib.rs
neard/src/cli.rs
tools/chainsync-loadtest/src/main.rs
tools/indexer/example/src/main.rs
tools/restaked/src/main.rs
tools/storage-usage-delta-calculator/src/main.rs

o11y is responsible for setting up console output and its options, so it
makes sense to keep that flag in `o11y` too.
cc @nikurt
cc @mina86 (this is very mildly related to the discussion in https://github.com/near/nearcore/issues/6888; basically, I feel like we could do pretty much the same thing to the EnvFilter and then users only ever need to think about dealing with including an `o11y::Options` in their structopt definition)

Move `--color` into `o11y::Options`

---

Cargo.lock
tools/mock_node/Cargo.toml
tools/mock_node/README.md
tools/mock_node/benches/README.md
tools/mock_node/benches/sync.rs
tools/mock_node/src/lib.rs
tools/mock_node/src/main.rs
tools/mock_node/src/setup.rs

- use kebab-case rather than snake-case
- replace mode argument with custom syntax with a pair of
* --client-height
* --network-height
- use convention-over-configuration for the binary name
These are mostly inconsequential cleanups which I am not feeling particularly strongly about specifically. I do feel moderately strongly about the overall point of sticking to conventions, defaults, and trying to leverage existing functionality instead of implementing custom logic :)

feat: more idiomatic CLI interface for mock network

---

Cargo.lock
runtime/runtime-params-estimator/Cargo.toml
runtime/runtime-params-estimator/src/main.rs

Allow to select tracing levels and targets with the `RUST_LOG` environment variable when the estimator is running without the `--tracing-span-tree` flag.

feat: tracing logs in estimator

---

chain/network/src/peer_manager/peer_store.rs
core/store/benches/store_bench.rs
core/store/src/config.rs
core/store/src/db.rs
genesis-tools/genesis-populate/src/main.rs
genesis-tools/genesis-populate/src/state_dump.rs
nearcore/benches/store.rs
nearcore/src/lib.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/main.rs
runtime/runtime-params-estimator/src/vm_estimator.rs
test-utils/runtime-tester/src/run_test.rs
test-utils/store-validator/src/main.rs
tools/mock_node/src/setup.rs
tools/state-viewer/src/cli.rs

Add home_dir as argument to StoreOpener::new and with_default_config
methods.  All call sites allready pass the home directory so this is
a purely refactoring change.  With that the home method is no longer
necessary.
Issue: https://github.com/near/nearcore/issues/6857

store: make home directory required when constructing StoreOpener

---

integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/runtime/deployment.rs
runtime/near-test-contracts/src/lib.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/utils.rs

Contracts with a controlled data section size are generated ad-hoc for
tests and estimations. But they never actually worked, they hit
`PrepareError::Deserialization` instead.
Test plan
-----------------
Validate the generated wat codes using `prepare_contract`.

fix: data sections in test wat codes

---

chain/network-primitives/src/config_json.rs
chain/network-primitives/src/network_protocol/mod.rs

We use kuberenetes for spinning up networks now with custom genesis using DNs instead of IPs and we have a problem that nodes can't resolve DNS records which are assigned to services. This fixes the issue.

feat(network): Added ability to resolve DNS records for peers instead of only IP addresses

---

core/store/src/db.rs
core/store/src/lib.rs
runtime/runtime-params-estimator/src/testbed.rs

Store::get_rocksdb method turns Store into a leaky abstraction as it
exposes the wrapped RocksDB to the clients.  At the same time, it’s
used in RuntimeTestbed only to flush the database.  Therefore, it can
be trivially replaced by a flush method which leaves the abstraction
intact.

store: replace Store::get_rocksdb with Store::flush

---

runtime/runtime-params-estimator/src/cost.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/utils.rs

Various changes around function call estimation.
1. Estimation for function call cost related to loading contract code from storage.
2. Change fn call estimations to use CLI arguments for iteration counts and reduce inner iterations to something that runs faster.
3. Add some documentation to estimations and rename a few things to make the code clearer.

feat(params-estimator): Cleanup fn call estimation

---

runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/vm_estimator.rs

Rather than creating a temporary directory with a RocksDB database,
use a test store which is a simple in-memory store.

runtime-params-estimator: use in-memory store

---

pytest/tests/loadtest/README.md

`neard` lives really under `release` but not `debug`.

Fix wrong command in README of pytest

---

Cargo.lock
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/compile_errors.rs
runtime/near-vm-runner/src/tests/runtime_errors.rs
runtime/near-vm-runner/src/tests/test_builder.rs
runtime/near-vm-runner/src/tests/wasm_validation.rs
runtime/near-vm-runner/src/vm_kind.rs

RFC solution for https://github.com/near/nearcore/issues/6921
Vision:
* remove `make_simple_call` family of functions completely in favor of unified `test_builde()`
* use snapshot/expect testing rather than relying on `Error: Eq`. I'd love to use `insta` as that's what we are using elsewhere, but I don't think insta can do what I want here (packaging "snapshot" as a value), so I plugged my `expect_test`. 
* pull the `with_vm_kinds` loop inside

RFC: introduce unified testing infrastructure for contract runtime

---

core/primitives-core/src/account.rs

This panic both never triggered and broke the API constraints of
BorshDeserialize. See the discussion at [1]
[1] https://github.com/near/nearcore/issues/6186
fixes #6186

chore: remove impossible-to-trigger panic

---

tools/mock_node/benches/sync.rs
tools/mock_node/src/lib.rs
tools/mock_node/src/main.rs
tools/mock_node/src/setup.rs

we don't have to wait for the peer manager to start to find out what
the the target height is, so getting rid of this simplifies the code a
bit. But more importantly, it removes an explicit dependency on actix
stuff in the mock main.rs file, which will make it easier to refactor
the mock code to not talk to the client via actix

refactor(mock-node): remove GetChainTargetBlockHeight

---

chain/network-primitives/src/network_protocol/edge.rs
chain/network/src/lib.rs
chain/network/src/store/mod.rs
chain/network/src/store/schema/mod.rs
chain/network/src/store/schema/tests.rs
chain/network/src/store/testonly.rs
chain/network/src/tests/mod.rs

It consists of 2 layers:
1. schema definition layer - enforcing type-safe access to the DB columns
2. atomic access layer - defining all DB transactions, which are the high level operations that business logic can execute.

Implemented store module for near-network

---

chain/indexer/src/streamer/mod.rs
chain/network/src/peer_manager/peer_store_test.rs
core/store/Cargo.toml
core/store/benches/store_bench.rs
core/store/src/config.rs
core/store/src/db.rs
core/store/src/lib.rs
genesis-tools/genesis-populate/src/main.rs
genesis-tools/genesis-populate/src/state_dump.rs
nearcore/benches/store.rs
nearcore/src/lib.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/src/main.rs
test-utils/runtime-tester/src/run_test.rs
test-utils/store-validator/src/main.rs
tools/mock_node/src/setup.rs
tools/state-viewer/src/cli.rs

Firstly, replace StoreOpener constructors with static methods on
the Store struct.  Specifically, add Store::opener (which acts just
like StoreOpener::new which is now private) and Store::tmp_opener
(which replaces StoreOpener::with_default_config).
Secondly, incorporate creation of the temporary directory into
the Store::tmp_opener method.  Previously, test code would create
a temporary directory and use StoreOpener::with_default_config.
Now, this is all rolled into single Store::tmp_opener method.
The motivation for that is to make it painfully obvious that
Store::tmp_opener is meant for tests only.  Anything that operates
on a non-temporary storage will have to use Store::opener and
provide it with a StoreConfig.
Lastly, change StoreOpener to resolve the path to the storage during …

store: refactor StoreOpener; add Store::opener and related changes

---

tools/state-viewer/src/apply_chain_range.rs

Fix typo leading to big value in the first progress report:
```
Printing results including outcomes of applying receipts
Processed 50 blocks, 1653136875922 ms passed, 0.0000 blocks per second (0 skipped), 4992473365.28 secs remaining 3 empty blocks 204.21 avg gas per non-empty block
Processed 100 blocks, 97978 ms passed, 0.5103 blocks per second (0 skipped), 197.92 secs remaining 4 empty blocks 199.30 avg gas per non-empty block
```
Manual run

fix: state-viewer starting timestamp

---

Cargo.toml

Fixes: https://github.com/near/nearcore/issues/4541

Add missing ‘chain/telemetry’ to workspace

---

core/store/src/db.rs
core/store/src/lib.rs

Fixes: #7024
Test plan
---------
I did not find a test that could be updated/enhanced to validate that the iteration would remain deterministic.
Not sure whether this extra step is needed. But if it is, I'd appreciate some guidance.
Edit:
Added two tests: `rocksdb_iter_order` and `testdb_iter_order`. These two tests that there is determinism
when calling the `iter` functions.

fix: make TestDB iterator deterministic

---

chain/network/src/peer_manager/peer_store_test.rs
core/store/benches/store_bench.rs
core/store/src/config.rs
core/store/src/db.rs
core/store/src/lib.rs
genesis-tools/genesis-populate/src/state_dump.rs
nearcore/src/runtime/mod.rs
test-utils/runtime-tester/src/run_test.rs

The problem some users encountered was that they were running tests in
an environment where resource limits (most notably hard NOFILE limit)
were too low for the default store configuration to work.  This lead
to the tests failing even though they could easily run without ever
approaching the limits.
This change introduces StoreConfig::test_config method which returns
test store configuration with max_open_files lowered to the old 512
default.
With that also rename Store::tmp_opener to test_opener (to indicate
it uses non-default configuration) and perform minor refactoring on
StoreConfig associated constants.

store: introduce StoreConfig::test_config constructor

---

CHANGELOG.md
Cargo.lock
core/crypto/Cargo.toml
core/crypto/src/key_file.rs

To make it easier to use credential files that near cli tool works
with, introduce ‘private_key’ alias for the ‘secret_key’ field in
KeyFile struct.  This way, the JSON file can have either of those
fields set and it’ll be read correctly.
Fixes: https://github.com/near/nearcore/issues/7030

crypto: add ‘private_key’ alias for ‘secret_key’ field

---

core/primitives/src/transaction.rs
tools/state-viewer/README.md
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/lib.rs
tools/state-viewer/src/tx_dump.rs

This PR adds a new command `dump_tx` to allow transactions in a certain block (specified by its height) to be dumped into a json file, while receiver accounts can be specified in the process, too.
- Spin up a mainnet node (go/own-mainnet)
- Clone this repo & branch and compile to get the binary
- `./target/release/neard --home [YOUR_MAINNET_DIR, e.g.: /x/y/z] view_state dump_tx --height [YOUR_HEIGHT, e.g.: 33043] --account-ids [ACCOUNTS_OF_INTEREST]`
- @mzhangmzz 
- @mm-near

dump block transactions into a file

---

runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/main.rs
runtime/runtime-params-estimator/test-contract/Cargo.toml
runtime/runtime-params-estimator/test-contract/build.sh
runtime/runtime-params-estimator/test-contract/src/lib.rs

The test cotract used in the estimator does no longer have a good reason
to have a fixed size. Instead, let's use the contract's natural size.
Closes #6822

chore: Remove estimator contract size padding

---

core/chain-configs/src/genesis_config.rs

this try_into converts T into Result<T, Infalliable>, we don't need it.

refactor: remove no-op into

---

Cargo.lock
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/wasmtime_runner.rs

- Upgrade wasmtime to 0.37, which should fix the build issue
- Increase the max stack size as seen by wasmtime, as our fuzzer
detected a behavior change with the upgrade without this
Fixes #6281

feat: add support for aarch64-linux

---

chain/chain/src/types.rs
core/chain-configs/src/genesis_config.rs
integration-tests/src/genesis_helpers.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/runtimes.rs
integration-tests/src/tests/client/sharding_upgrade.rs
nearcore/src/lib.rs
nearcore/tests/economics.rs
test-utils/runtime-tester/src/run_test.rs
tools/mock_node/src/lib.rs
tools/mock_node/src/setup.rs

We never actually use this stuff generically, cutting this out removes
indirection and makes it clear what's going on.
Can be reviewed per-commit

refactor: remove needless generics form GenesisConfig API 

---

core/primitives/src/merkle.rs
core/primitives/src/sharding.rs

* CryptoHash::hash_borsh computes the hash in the streaming fashion,
without allocating an intermediary vec
* EncodedShardChunkBody, we avoid cloning boxes, taking references
instead.

perf: avoid unnecessary allocations when merklizing stuff

---

chain/chain/src/test_utils.rs
chain/chain/src/tests/simple_chain.rs
chain/epoch_manager/src/test_utils.rs
chain/epoch_manager/src/validator_selection.rs
core/chain-configs/src/genesis_config.rs
core/primitives/src/types.rs
core/primitives/src/views.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/nearcore/sync_nodes.rs
nearcore/src/runtime/mod.rs
nearcore/src/shard_tracker.rs
runtime/runtime/src/actions.rs

We figured out that we don't actually need it. And, indeed, today the
code is unused.
The code still preserves versions for stakes, just in case we need it
later.
closes https://nearinc.atlassian.net/browse/CPR-83

refactor: remove `is_chunk_only` field from ValidatorStake

---

.buildkite/pipeline.yml

"git merge-base --fork-point master" is unreliable and sometimes returns no response (I don't know why).
"git merge-base master HEAD" works in the case we discovered, so switching to that.

[fix] protobuf backward compatibility test

---

core/store/src/config.rs
core/store/src/db.rs
core/store/src/lib.rs

Currently, Store converts errors from Databases into std::io::Error.
This means that calls to RocksDB go through rocksdb::Error → DBError →
std::io::Error conversion.  DBError is pretty much never used directly
and it does not include any programmatic information about the error.
Just like rocksdb::Error it’s just a wrapper around a string message.
Simplify the code by getting rid of DBError and changing Database
interface to convert rocksdb::Error into std::io::Error.  This makes
Store methods simpler and removes one step from the conversion chain.
Note that Store methods need to return std::io::Error because that’s
the error that Borsh deserialisation returns.  Returning something
else would require converting that error which would lead to excessive
wrapping of errors.

store: get rid of DBError type

---

core/store/src/db.rs
core/store/src/db/refcount.rs

Also, add more documentation and move get_with_rc_logic and
iter_with_rc_logic functions outside of impl RocksDB since
they aren’t RocksDB-specific and are used in TestDB as well.
Note that at the moment some of the tests give inocrrect results
(i.e. results which do not match documentation).  Those will be
fixed in subsequent commit.  This commit is meant not to introduce
any changes in behaviour.

store: add unit tests for near_store::db::refcount functions

---

chain/chain/src/store.rs
chain/chain/src/store_validator.rs
chain/chain/src/store_validator/validate.rs
core/store/src/columns.rs
core/store/src/db.rs
core/store/src/db/refcount.rs
core/store/src/lib.rs
core/store/src/trie/shard_tries.rs

Every time StoreUpdate::update_refcount is used it’s called with
a positive or a negative value.  I.e. each caller knows whether they
are increasing or decreasing the value.  This makes it trivial to
split the method into increase_refcount and decrease_refcount methods.
The two methods are now simpler since they don’t have to check sign of
the delta argument.

store: separate StoreUpdate::update_refcount into increase and decrease

---

core/store/src/config.rs

Revert default value (to 50K) because after https://github.com/near/nearcore/pull/7022 we got more evidence that it doesn't help to speed up storage ops.
Existing tests.

fix: revert default value for trie cache capacity

---

core/store/src/db.rs
core/store/src/lib.rs

Firstly, remove transaction function from the Database trait in favour
of callers simply creating DBTransaction object themselves.
Secondly, replace Database::get by get_raw_bytes method which,
similarly to iter_raw_bytes, doesn’t perform refcount decoding.  RC
handling is now done at Store::get level which means that it’s now
common code regardless of Database implementation.  This new method
can be further used in tests which so far were using their own code.
And lastly, while doing all that, add more documentation to functions
within Database trait.

store: add documentation to Database trait and refactor it a little

---

core/store/src/columns.rs
core/store/src/db.rs
core/store/src/db/refcount.rs

Firstly, change decode_value_with_rc so that it returns (None, 0) if
reference count is zero.  This is what the documentation claims it
should do but in reality the function returned (Some(...), 0).
Secondly, change get_with_rc_logic such that it no longer creates
a new Vec.  Instead, Vec which is passed to it is truncated when
necessary.  This reduces amount of times allocator is called.
Thirdly, change refcount_merge so that it first goes through all the
values and only at the end performs single Vec allocation.  This makes
merge_refcounted_records function unnecessary and simplifies code
a bunch.

store: various small near_store::db::refcount changes

---

chain/chain/src/doomslug.rs
chain/client/src/client.rs

The previous code was removing the witness at the moment of block creation - which makes debugging/reviewing history a lot harder (as the data is gone).
Now, the data is persisted, and it is removed when we GC all the trackers for a given height..

Changing remove_witness to get_witness in Doomslug

---

chain/client/Cargo.toml
nearcore/src/config.rs

The indexer doesn't depend on `neard` but depends on `near-client`

shardnet compilation feature for near-indexer-for-explorer

---

.cargo/config.toml

For various tests, we compile a bunch of code in this repo to WASM, and
that emits a tone of warnings about sse not making sense here. Let's
scope it to just x86_64 cpu arch

fix: don't set rustflags for WASM

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/peer_store.rs

When reading peers from the database, some of them may be banned.
Knowing how many peers were read does not give complete information.
Include number of banned peers so that it’s clear from logs how many
usable known peers there are.

peer_manager: include information about number of banned known peers

---

chain/chain/src/tests/simple_chain.rs
core/primitives-core/src/config.rs
core/primitives-core/src/parameter.rs
core/primitives/Cargo.toml
core/primitives/res/runtime_configs/130.txt
core/primitives/res/runtime_configs/parameters.txt
core/primitives/src/errors.rs
core/primitives/src/runtime/config_store.rs
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__0.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__42.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__48.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__49.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__50.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__52.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__53.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_0.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_42.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_48.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_49.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_50.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_52.json.snap
core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_53.json.snap
core/primitives/src/version.rs
integration-tests/Cargo.toml
integration-tests/src/tests/client/process_blocks.rs
runtime/runtime/src/verifier.rs

closes https://nearinc.atlassian.net/browse/CPR-135

feat: enforce that account_ids are valid in FunctionCallPermission

---

pytest/tests/shardnet/restake.py

when running create_account.sh fails, we'll continue with the staking
part but it will silently fail because the account doesn't exist. This
actually happens for transient reasons in practice, so retry the
command a few times and dont continue if it fails.

fix(shardnet): don't ignore errors in restake.py

---

Cargo.lock
chain/epoch_manager/Cargo.toml
core/crypto/Cargo.toml
core/primitives/Cargo.toml
integration-tests/Cargo.toml
nearcore/Cargo.toml

This disables default features for the `primitives` crate, which
inadvertedly also enabled a bunch of optional deps there.

chore: remove a bunch of unused dependencies

---

Cargo.lock
chain/client/Cargo.toml
chain/client/src/info.rs

We no longer need to use the fork it seems

chore: upgrade sysinfo

---

core/store/src/lib.rs
core/store/src/trie/shard_tries.rs

Convert static methods of ShardTries which effectively take self as
argument into regular non-static methods.  This makes code more
idiomatic.

store: change static ShardTries methods into regular ones

---

Cargo.lock

Primarily to silence a warning about https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-2097
I don't think we are affected, but openssl is probably something we
should keep up-to-date anyways!

chore: update openssl

---

runtime/runtime-params-estimator/src/estimator_params.rs

regression from #7154
Previously, the string was converted to hex, while the `CryptoHash`
uses bs58 encoding. Let's just go with bs58 to keep it simple.
This changes the output of the function. Which is completely irrelevant.
We only care that the hash gets computed and no compiler can remove it.

fix: CpuBenchmarkSha256 encoding in assertion

---

tools/state-viewer/README.md
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/tx_dump.rs

This PR enables transactions to be dumped from a range of blocks on `dump_tx` command.
See changes in README on how to use the new tx dumper with the new parameters.
- Prepare a home directory that contains transactions in the db
- Compile the code using `make neard`
- Run `./target/release/neard --home $HOME_PATH view_state dump_tx --start-height XXX --end-height YYY` (replace XXX and YYY with heights, and `$HOME_PATH` with the actual home directory location)
- @mzhangmzz 
- @mm-near

support state_viewer:tx_dump for a range of blocks

---

genesis-tools/genesis-populate/src/lib.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/transaction_builder.rs
runtime/runtime-params-estimator/src/utils.rs

1. Use account ids without a shared prefix.
2. Subtract block overhead instead of just checking it is insignificant.
resolves #7003

feat: reduce block overhead effect on estimations

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/routing/actor.rs
chain/network/src/routing/graph_with_cache.rs
chain/network/src/routing/mod.rs
chain/network/src/routing/routing_table_view.rs
chain/network/src/routing/tests/cache.rs
chain/network/src/routing/tests/mod.rs
chain/network/src/routing/tests/routing_table_view.rs
integration-tests/src/tests/network/runner.rs

also hidden some implementation details, which were exposed to PeerManagerActor.
The previous implementation of next hop selection was slightly favoring sending messages to newly connected peers for unknown reasons. The current one aims at uniform utilization of all connected peers and is way simpler. The expected impact on the actual performance is negligible.

simplified the round robin in RoutingTableView

---

pytest/tests/sanity/docker.py

‘docker stop’ stops a container but leaves it still accessible.  Use
‘docker rm -f’ to stop and remove any data regarding the container.

pytest: remove Docker container once sanity/docker.py test finishes

---

runtime/runtime-params-estimator/src/cost.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/trie.rs
runtime/runtime-params-estimator/src/utils.rs

`action_function_call_*` costs are currently used to also cover contract
loading. But we want to give `wasm_contract_loading_*` costs meaningful
values and consequently reduce `action_function_call_*`.
This adjusts the `ActionFunctionCallBase` estimation to not include
contract loading costs. The difference is rather singificant since the
test contract used before was almost 100kB in size.
This change also introduces an approach of subtracting receipt overhead
completely, by executing multiple actions into one receipt.

feat: estimate fn call action without loading cost

---

Cargo.lock
chain/chain/Cargo.toml
chain/chain/src/chain.rs
integration-tests/src/tests/client/process_blocks.rs

It was temporarilty ignored to ship async block processing.
The reason why this test fails after the change is because, in the test,
we inspect the logs, and, now that the work happens in a different
threads, tracing loses its thread-local context and we fail to capture
the span.
In the ideal world, tracing&rayon would just magically work this out
between themselves, but today it seems that the best option is for us to
help them.
See also discussion at
https://discord.com/channels/500028886025895936/627649734592561152

test: unignore wasmer2 upgrade test

---

Cargo.lock
chain/network/src/peer_manager/peer_manager_actor.rs

Follow up to 03f99956ee93959a83bf3473ef310559e67beae1
This case was missed during the cherry-picking

fix: fix span leakage

---

chain/client/src/test_utils.rs

It probably takes the crown as the scariest function in our codebase,
and it'd be great to simplify this significantly. Let's start somewhere.

test: tiny simplification in setup_mock_all_validators

---

chain/client/src/test_utils.rs

Got this one spuriously(?) firing in some test with nightly features.
Let's make the failure a bit more helpful here!

test: more useful assert

---

chain/chain/src/test_utils.rs
chain/chunks/src/test_utils.rs
chain/client/src/test_utils.rs

* eagarly compute assignemt of validators to blocks & chunks, which I find a bit easier to wrap my head around (you can print `EpochValidatorSet`s and just see the result)
* compress the code by centralizing cfg handling

test: simplify cops support in KeyValue runtime

---

core/primitives-core/src/serialize.rs
runtime/near-vm-logic/src/mocks/mock_external.rs
runtime/near-vm-logic/src/types.rs

Closes #7203 
There are a few structs that do not need to derive `Serialize` and `Deserialize`.  Remove the derives highlights that there are some structs that we do not need at all and that we do not need to define custom deserializer: `bytes_as_string`.
Tests
-------
- `cargo check --tests --benches` does not complain.
- Other existing tests

Refactor: remove some dead code

---

chain/client/src/test_utils.rs
integration-tests/src/tests/client/process_blocks.rs

We have been copying the same code multiple times, this refactor
pulls out the functionality the `TestEnv`.

refactor: `call_main` utility for integration test

---

core/store/src/config.rs
core/store/src/db/rocksdb.rs

In our case it's the number of file descriptors that is not respected.

also respect storage config when checking rocksdb version

---

tools/state-viewer/src/commands.rs

This PR adds a line of output at the end of `dump_state`, for convenience. 
- `make neard`
- `/target/release/neard --home $NEAR_HOME_PATH view-state dump_tx --start-height $X --end-height $Y`
- expect to see a line of output in the end that shows 
- @mzhangmzz 
- @mm-near

show output file path after dumping tx

---

runtime/runtime-params-estimator/src/gas_cost.rs
runtime/runtime-params-estimator/src/qemu.rs

Estimations such as `GasMeteringBase` can return a zero value, which has
no metric attached. The least-squares method should not panic in such
cases and instead treat the value as 0 for every metric.
regression introduced in #7215

fix: graceful zero least-squares estimations

---

chain/chain/src/chain.rs
chain/chain/src/metrics.rs

This will be used to calculate number of skipped blocks. The current calculation of this metrics is problematic.

add metrics for block ordinal for current chain head

---

runtime/runtime-params-estimator/src/function_call.rs

--debug flag on estimator is used to show intermediate results and other
useful information. The contract loading estimation did not respect this
flag so far because the code predates the debug flag.

debug: forward debug flag to loading estimation

---

CHANGELOG.md
chain/chain/src/tests/simple_chain.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
core/primitives/Cargo.toml
core/primitives/src/version.rs
integration-tests/Cargo.toml
integration-tests/src/tests/client/process_blocks.rs
nearcore/Cargo.toml
runtime/near-vm-logic/Cargo.toml
runtime/near-vm-logic/src/logic.rs
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/compile_errors.rs
runtime/near-vm-runner/src/tests/runtime_errors.rs

This reverts commit f7aca03262bdbc58a8b1cedeb4deb82a5c565d01.
Reverting based on discussion at https://github.com/near/nearcore/issues/7227
The TL;DR is while the current impl of the feature charges correct cost for contract loading at *logically* correct place, we'd want to move the charging a little bit earlier physically, even before we load the contract from the database, so that the cost can be lower without adding an extra protocol feature here.

Revert "feat: stabilize precharged contract loading gas (#7177)"

---

core/store/src/trie/insert_delete.rs
core/store/src/trie/mod.rs

`encode_into()` is using the `Cursor` API to write bytes to a vector.  This API can return errors which we have to handle.  Instead, the standard vector API does not return errors so we do not have handle errors in our code that are "impossible" to happen.

refactor: Use std API to avoid throwing errors that should not be possible

---

core/chain-configs/src/genesis_config.rs
core/primitives-core/src/account.rs
core/primitives-core/src/runtime/fees.rs
core/primitives-core/src/serialize.rs
core/primitives/src/errors.rs
core/primitives/src/receipt.rs
core/primitives/src/runtime/config.rs
core/primitives/src/transaction.rs
core/primitives/src/types.rs
core/primitives/src/views.rs
runtime/near-vm-logic/src/context.rs

Replace all `{option_,}{u64,u128}_dec_format{,_compatible}` formats
with a single `dec_format` which automatically figures out the type
it’s serialising/deserialising.  This makes it somewhat easier to use
the formats since a simple `#[serde(with = "dec_format")]` now just
works without user having to think about the actual type of the field.
This brings one change in behaviour though.  Previously only some of
the fields used ‘compatible’ variant.  I.e. they would allow the field
to be either string or a number.  Most always expected a string.  With
this change, when deserialising u128 and u64 fields they can all be
gives as strings (the canonical format) or numbers.
Finally, remove one remaining unused instance of u128_dec_format which
was overlooked in previous commit.
Fixes: …

core: harmonise dec_format serialisation formats

---

Cargo.lock
chain/network-primitives/src/types.rs
chain/network/Cargo.toml
chain/network/src/accounts_data/mod.rs
chain/network/src/accounts_data/tests.rs
chain/network/src/lib.rs
chain/network/src/network_protocol/testonly.rs
chain/network/src/testonly/mod.rs
core/primitives/src/types.rs

https://nearinc.atlassian.net/browse/CPR-94
accounts_data::Cache is the central component collecting the SignedAccountData (data about validator nodes broadcasted by the the validators themselves). It takes care of preventing DDOS attacks of various types: minimizes the amount of signature verifications (which is computationally expensive) and detects malicious data as early as possible. It will be plugged into the PeerManager logic in the next PR.

implemented accounts data cache

---

chain/jsonrpc-primitives/Cargo.toml
chain/jsonrpc-primitives/src/types/status.rs
chain/jsonrpc/Cargo.toml

This cuts the number of dependencies pulled in by `near-jsonrpc-primitives` from 211 down to 145. I am especially happy to see `actix` and `tokio` gone! This will help `near-jsonrpc-client` to be a bit slimmer.

refactor: Make the near-client-primitives optional dependency in near-jsonrpc-primitives

---

chain/client/src/test_utils.rs
chain/network/src/test_utils.rs
chain/network/src/types.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/network/runner.rs
nearcore/src/lib.rs
tools/chainsync-loadtest/src/main.rs
tools/mock_node/src/setup.rs

Refactored NetworkRecipient interface so that it supports multiple message types and easy mocking. Currently we have an enum for all-messages and an enum for all-responses, which requires an unwrap of right response variant at every call site.

refactored NetworkRecipient interface

---

core/primitives/src/types.rs
core/store/src/lib.rs
integration-tests/src/tests/client/process_blocks.rs
nearcore/src/runtime/mod.rs
runtime/near-vm-runner/src/cache.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/testbed.rs
runtime/runtime-params-estimator/src/vm_estimator.rs
runtime/runtime/src/lib.rs

The main motivation here isn’t obvious.  It’s to decouple the cache
from Store struct similarly how peer store is now talking to Database
directly.  Long-term plan is to have hot and cold storage;  it’s
beneficial if part of the code which only ever talk to hot storage
don’t need to go through Store interface.
As a side benefit, this reduces the number of clones when storing
contracts in the cache.

store: use Database directly in StoreCompiledContractCache

---

nearcore/src/runtime/mod.rs

This computation takes several minutes if there are many records, like
in testnet, or a network with state forked from mainnet. And then if
the hash was already stored, the result is promptly discarded.  If the
TODO here around re-enabling the hash check gets done then we will
have to revisit this.

refactor: don't compute the genesis json hash if it's already stored

---

chain/chain/src/store.rs
chain/chain/src/test_utils.rs
chain/chain/src/test_utils/validator_schedule.rs
chain/chain/src/tests/gc.rs
chain/chunks/src/lib.rs
chain/chunks/src/test_utils.rs
chain/client/src/info.rs
chain/client/src/sync.rs
chain/client/src/test_utils.rs
chain/client/src/tests/query_client.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/network/runner.rs

With cops, we now need to somehow configure `setup_mock_all_validators` to also specify cops. It *could* be done by adding just another argument, but I'd rather avoid that. Instead, what I suggest is bunching up all related configs into a single builder object, `ValidatorSchedule`, and use that as a universal tool to configure validators for KeyValueRuntime. 
Note that this PR doesn't change `setup_mock_all_validators` -- that's going to be a bigger diff, so I want to land that separately.
I might also merge this with `EpochValidatorSet`, the structs handle similar data, but, at this stage, `EpochValidatorSet` is implementation detail, while `ValidatorSchedule` is the API for authors of tests. 
Can be reviewed per commit.

test: introduce ValidatorSchedule to specify COPs for KeyValue runtime conveniently

---

chain/client/src/client.rs

The get_validator_info function doesn't work with the current epoch id, see comments in ValidatorIdentifier.

fix a bug in send_network_chain_info

---

pytest/tests/sanity/backward_compatible.py
pytest/tests/sanity/upgradable.py

Issue: https://github.com/near/nearcore/issues/4372

pytest: update tests to no longer used deleted ‘testnet’ command

---

chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
core/primitives/src/test_utils.rs
core/primitives/src/views.rs
integration-tests/src/tests/client/sandbox.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs
integration-tests/src/tests/runtime/deployment.rs
integration-tests/src/tests/runtime/sanity_checks.rs
integration-tests/src/tests/runtime/state_viewer.rs
integration-tests/src/tests/runtime/test_evil_contracts.rs
integration-tests/src/tests/standard_cases/mod.rs
runtime/runtime/src/state_viewer/mod.rs

Rather than declaring a field String and having all the users do
base64 conversion manually, declare it Vec<u8> with base64_format
serialisation scheme.  This way, only the serialisation code needs to
worry how the data looks on the wire.  This also means that users
reading the data don’t need to worry about decoding errors.
Fixes: https://github.com/near/nearcore/issues/7232

core: views: prefer base64_format to manual base64 conversions

---

core/chain-configs/src/genesis_config.rs
core/chain-configs/src/lib.rs
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/state_dump.rs

Adding option to state dump to kick non-whitelisted validators. This is needed for shardnet hardforks. 
As there are some other things we do with genesis file for shardnet after dumping, introducing change_state_record and change_genesis_config to accumulate the code for future possible alterations. 
Also introducing GenesisChangeConfig, which includes previously separate individual field select_account_ids along with new field whitelist_validators. 
Unit test:
- setup with one validator test0
- staking test1
- waiting 2 epochs
- dumping state with test1 and non_validator_account whitelisted
- checking that only test1 is in validators list in genesis config
- checking that test0 has 0 stake
- checking that genesis is valid

add include validators option to state dump

---

Cargo.lock
chain/chain/Cargo.toml
chain/chain/src/block_processing_utils.rs
chain/chain/src/blocks_delay_tracker.rs
chain/chain/src/chain.rs
chain/chain/src/metrics.rs
chain/chain/src/missing_chunks.rs
chain/chain/src/tests/simple_chain.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/jsonrpc/res/chain_n_chunk_info.html
core/primitives/src/views.rs

This PR refactors BlockInProgress to keep information of recent blocks, not just blocks that are in progress and updates the debug page and debug stats print. 
The new implementation also fixed some small issues: 
- Implemented GC in BlockInProgress correctly. Previously, a block is only removed if it finished processing. This could leave blocks permanently left in the pool if it never finished processing, which could happen for blocks on some old forks.
- Now missing chunks are reflected with character "X"
In a following PR, I will add more detailed information regarding chunk processing (which parts/receipts are received/missing).
New debug page: 
New debug stats:
```
2022-07-29T19:00:06.422803Z DEBUG stats: EpochId(`AcpLCWttsHYuh7HNMoKaQxU63enpEJC31TXDZnFXDqVS`) Orphans: 0 With missing …
```

Refactor BlockInProgress to print more information of processed blocks and chunks

---

chain/network/src/accounts_data/mod.rs
chain/network/src/peer_manager/testonly.rs
chain/network/src/peer_manager/tests.rs
chain/network/src/testonly/actix.rs

actix::stop causes all the futures from the actix runtime to be dropped. Until we replace actix with structured concurrency we cannot enforce driving futures to completion :/.
Fixed a race condition introduced in https://github.com/near/nearcore/pull/7182
I've executed the test suite locally 50 times to confirm that deflaking took effect.

deflaked network tests

---

chain/rosetta-rpc/src/adapters/mod.rs
chain/rosetta-rpc/src/adapters/transactions.rs
chain/rosetta-rpc/src/adapters/validated_operations/transfer.rs
chain/rosetta-rpc/src/models.rs

That commit broke sanity/rosetta.py pytest.
This reverts commit add1390034763834648e7f3180c90f6b58f55ecf.

Revert "Fix/rosetta rpc predecessor"

---

chain/client/src/client.rs
chain/network/src/accounts_data/mod.rs

as discussed offline, the computation cost is negligible wrt block processing.

removed unnecessary caching of TIER1 account keys in the near_client

---

pytest/requirements.txt

We had some issues with scipy 1.7.2 on buildkite (which I can no
longer recall if I’m to be honest) but now requiring 1.7.1 poses its
own problems.  It is incompatible with Python 3.10 and also causes
issues on M1.  Both of those are solved by unpinning the version and
allowing latest scipy release.

pytest: remove requirement of specific scipy version

---

Cargo.lock
chain/indexer/Cargo.toml
core/store/Cargo.toml
core/store/src/db/rocksdb.rs
deny.toml
runtime/runtime-params-estimator/Cargo.toml

This brings a few changes which allow our code to be simplified:
* Iterators now return Result<Item, Error> rather than forcing users
to check for errors with separate status method call.  We can remove
our wrapping code;
* rocksdb::PrefixRange allows setting a prefix range which is what we
used to do ourselves.  This lets us get rid of next_prefix function;
* property_value method et al. accept CStr arguments and properties
defined in rocksdb::properties are now defined as CStrs.  This is
an optimisation as previously each call to property_int_value_cf
resulted in str→CStr conversion which requires memory allocation.
Notably, with this update Cargo (after issuing a build command) also
decided that updating actix-http from 3.0.4 to 3.2.1 is in order.

Update rocksdb to 0.19

---

chain/client/src/view_client.rs

In all instances where ViewClientActor::maybe_block_id_to_block_hash
is called, the caller takes the hash and fetches block’s header.
However, in two out of three cases the method already fetches the
header of the block (to determine the hash) making it trivially
available to the caller.
Replace the method with one which returns the header directly.  This
means that in one case where the fetching did not occur inside of the
method, it is now happening there.

chain: maybe_block_id_to_block_hash → maybe_block_id_to_block_header

---

chain/chain/src/store_validator/validate.rs
chain/chain/src/test_utils.rs
chain/chain/src/tests/gc.rs
chain/chain/src/types.rs
core/store/benches/trie_bench.rs
core/store/src/test_utils.rs
core/store/src/trie/iterator.rs
core/store/src/trie/mod.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/split_state.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_tests.rs
core/store/src/trie/update.rs
integration-tests/src/tests/client/features/fix_storage_usage.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/user/runtime_user.rs
nearcore/benches/store.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/src/testbed.rs
runtime/runtime/src/ext.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/state_viewer/mod.rs
runtime/runtime/tests/runtime_group_tools/mod.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/state_dump.rs

Introduce a new `root: StateRoot` field into Trie structure.  With that,
methods reading the state no longer need a state root argument (so remove
it).  This also makes state root redundant in TrieUpdate struct (so remove
it as well).
The overarching goal here is to make Trie and TrieUpdate interface the
same.  With that, it’s going to be possible to create a common trait
for accessing state from Trie and TrieUpdate.
Issue: https://github.com/near/nearcore/issues/6308
Fixes: https://github.com/near/nearcore/issues/7362

store: add StateRoot into Trie struct

---

core/store/benches/trie_bench.rs
core/store/src/trie/mod.rs
core/store/src/trie/split_state.rs

Change Trie::update to accept IntoIterator rather than Iterator.  This
simplifies a few call sites (by making explicit into_iter calls
unnecessary).  While at this, clean up some other uses of the update
method.

store: accept IntoIterator by Trie::update

---

chain/rosetta-rpc/src/lib.rs
chain/rosetta-rpc/src/models.rs

Firstly, replace From<BlockHeaderView> with From<BlockView>
implementation for BlockIdentifier.  The former is somewhat more
flexible but in practice we only ever used it when we had the full
block view at hand.
Secondly, introduce BlockIdentifier::new constructor to better
encapsulate creating the identifier from height and hash.  It reduces
code duplication.
Lastly, replace use of to_base method with use of to_string method.
They are equivalent for CryptoHash but the latter produces less syntax
noise since we don’t need to use our home grown BaseEncode trait.

rosetta: refactor BlockIdentifier construction

---

chain/epoch_manager/src/lib.rs
chain/epoch_manager/src/test_utils.rs
chain/epoch_manager/src/tests/mod.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
core/chain-configs/src/genesis_config.rs
core/primitives/src/epoch_manager.rs
nearcore/src/runtime/mod.rs
nearcore/src/shard_tracker.rs
tools/state-viewer/src/commands.rs

This sets a few changes for ChunkOnlyProducers:
- set number of block producers to 100 (for testnet)
- change number of chunk only producers to 200
- decrease the kick off limit for both block and chunk producers to 80
Test plan:
- start a localnet with use_production_config set to true and test that it runs and check from the debug log that the epoch config is set correctly 
- thinking about other ways to test it programmatically

Add protocol config changes for chunk only producers

---

chain/network/src/concurrency/demux.rs
chain/network/src/concurrency/tests.rs
chain/network/src/peer_manager/connected_peers.rs

Spawning tasks on runtime of unknown lifecycle is scary :/. I need to think this through again.

fix: a quickfix to make demux tolerant to stopping tokio::Runtime

---

chain/client-primitives/src/types.rs
chain/client/src/lib.rs
chain/client/src/view_client.rs
chain/rosetta-rpc/src/adapters/mod.rs
chain/rosetta-rpc/src/lib.rs
nearcore/src/lib.rs

Rosetta RPC is the only user of GetBlockHash message.  It uses it to
get the hash of the genesis block.  Instead, pass the hash of the
genesis block to Rosetta RPC server when it’s starting so that there
is no need to query the view client for it.  With that, GetBlockHash
becomes unused and can be deleted completely.

chain: pass genesis hash to Rosetta and get rid of GetBlockHash request

---

core/store/src/lib.rs

This `.insert` was causing some test failures on CI, like the following one: 
https://buildkite.com/nearprotocol/nearcore/builds/18816#01828244-167b-42e9-aae2-2884f8daa9f1/94-831

fix: remove mistaken write-once assert from CompiledContractCache

---

core/store/src/db.rs

Not really certain what exactly we want here, but this seems like an incremental improvement. Notably, it would've caught https://github.com/near/nearcore/pull/7395

refactor: add some assertions about column types to DBTransaction

---

chain/client/src/client_actor.rs
chain/indexer/src/streamer/fetchers.rs
chain/indexer/src/streamer/mod.rs
chain/indexer/src/streamer/utils.rs
integration-tests/src/tests/standard_cases/mod.rs
integration-tests/src/tests/test_tps_regression.rs
integration-tests/src/user/mod.rs
integration-tests/src/user/rpc_user.rs
integration-tests/src/user/runtime_user.rs

The code base isn’t fully consistent in how functions getting data by
their hash or height are named.  For example, in different strucs and
traits we have examples of ‘get_block’ (some taking hash while others
taking height argument), ‘get_block_by_hash’ and ‘get_block_by_height’
methods.
Normalise the naming such that functions fetching data by hash don’t
have a suffix (e.g. ‘get_block’ or ‘get_chunk’) while functions
fetching data by height have it (e.g. ‘get_block_by_height’).
This was made with just a little bit of grepping and sedding.
It’s possible that there still remain functions which don’t follow
convention suggested here.

chain: normalise ‘_by_hash’ and ‘_by_height’ naming

---

chain/client/src/view_client.rs

`chain.head_header()?.hash()` translates roughly into
`chain.get_block_header(chain.head()?.last_block_hash)?.hash()`
and that’s of course just a convoluted way of writing
`chain.head()?.last_block_hash`.
Change the Finality::None case so that fetching of the block header
does not happen.

chain: avoid fetching header in ViewClientActor::get_block_hash_by_finality

---

chain/chain/src/chain.rs
chain/chain/src/store.rs
chain/chain/src/store_validator.rs
chain/chain/src/tests/challenges.rs
chain/chain/src/tests/simple_chain.rs
chain/client/src/client.rs
chain/client/src/debug.rs
chain/client/src/sync.rs
chain/client/src/view_client.rs
integration-tests/src/tests/client/process_blocks.rs

Some of the functions returning BlockHeader are named get_header while
others are called get_block_header.  Remove that inconsistency by
renaming the former function to follow the format of the latter.
While I would honestly prefer ‘get_header’, doing the renaming in the
other direction results in a larger diff so I’ve settled on more
verbose ‘get_block_header’:
14 files changed, 139 insertions(+), 155 deletions(-)
This was done with:
sed -i s/get_header/get_block_header/g -- $(git grep -l get_header)

chain: standardise on ‘get_block_header’ naming

---

chain/chain/src/store.rs
chain/chain/src/store_validator.rs
core/store/src/columns.rs
core/store/src/db.rs
core/store/src/lib.rs
nearcore/src/lib.rs

I’d argue that the current DBCol’s Display implementation offers no
value.  I cannot think of a situation in which we’d rather see the
description of the column provided by the implementation rather than
the variant name.
If one sees the name of the column in logs or some other places, it’s
trivial to start grepping the source code for uses of that column.
When the description is shown it first need to be transformed back
into the variant name to actually be useful.
And it’s not like the description explains anything.  For example,
‘epoch information’ is no more clear than EpochInfo.  In a few cases,
things like ‘hash of chunk per height and shard_id’ are easier to read
than ChunkPerHeightShard but I’d still question if this is enough to
justify existence of this custom implementation.
In …

Simplify DBCol’s Display implementation and prefer it over Debug

---

core/primitives-core/src/hash.rs

In some cases, CryptoHash is converted into a String which gets passed
as &str to other parts of the code only for the String to be discarded
later.  Avoid that by doing the encoding onto the stack and using &str
pointing at the on-stack buffer.

core: avoid allocations when formatting crypto hash as base58

---

chain/client/src/client_actor.rs

Otherwise, syncing will be slow because log_summary will take a long time.
Proper fix of get_validator_info in another PR.

fix log_sumary to use header_head instead of head for get_valiator_info

---

chain/client/src/client.rs
chain/client/src/client_actor.rs

We should send ChainInfo to net whenever it changes, but we've missed
one case: at the startup, theres' a change due to us getting the initial
info. If we don't do that, we can't start block processing, so the info
is never updated. So, let's just send the info on startup.
There's a python tests which uncovered this bug:
$ python3 tests/sanity/block_sync_archival.py
While fixing this, I've also noticed a bug in the epoch manager, which failed to report validators for genesis block, so that is fixed as well. 
best reviewed per commit.

fix: fix logical deadlock in the network 

---

chain/network-primitives/src/network_protocol/mod.rs
chain/network/src/peer/peer_actor.rs

We keep adding more and more unused variants to RoutedMessageBody
enum making name the name Unused overburdened.  Rename existing
Unused variant to _UnusedReceiptOutcomeResponse so that it stays
consistent with other two unused variants.  With three of them now
hopefully this will establish the pattern.
While at it, harmonise how all three of the variants are handled.

chain: rename RoutedMessageBody::Unused to _UnusedReceiptOutcomeResponse

---

core/store/src/lib.rs
core/store/src/trie/mod.rs
core/store/src/trie/split_state.rs
core/store/src/trie/update.rs
integration-tests/src/tests/client/process_blocks.rs
runtime/runtime/src/balance_checker.rs
runtime/runtime/src/lib.rs
tools/state-viewer/src/apply_chain_range.rs

Define a TrieAccess trait with a single get method whose purpose is
reading data from given trie.  That is, a trie rooted at one specific
root.
Implement this for Trie and TrieUpdate and with that, change helper
getter functions which previously require `state_update: &TrieUpdate`.
This allows runtime’s check_balance function to work without the need
for explicit `initial_state: &TrieUpdate` to be specified.  The
function can assume that initial state is the one in the Trie
underlying the final state and then read data directly from that
Trie when fetching initial balances etc.
There may be other places where use of &TrieUpdate to read data is now
not necessary.  This commit doesn’t go into changing all of them.  In
fact, I haven’t looked for other such places.
Issue: …

store: introduce TrieAccess and make getter functions use it

---

chain/client/src/client_actor.rs
chain/client/src/sync.rs

Notably, use `&Chain` rather than `&mut Chain` where we can.
Backstory: debugging https://github.com/near/nearcore/issues/7371

refactor: minor sync cleanups

---

chain/client-primitives/src/types.rs

Query::query_id field is never used.  Get rid of it.

chain: get rid of Query’s query_id

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/private_actix.rs
chain/network/src/routing/actor.rs
chain/network/src/stats/metrics.rs

Adds debug metrics for the time that PeerManagerActor spends on processing different triggers and messages and for routing table actor too. These metrics are useful for debugging why PeerManagerActor or routing table actor are busy

Add some debug metrics for PeerManager performance

---

chain/client/src/test_utils.rs
chain/client/src/view_client.rs
chain/network-primitives/src/network_protocol/mod.rs
chain/network-primitives/src/types.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/types.rs
tools/chainsync-loadtest/src/network.rs

As far as I can tell, ReceiptOutcomeRequest does nothing useful.
- There’s ViewClientActor::request_receipt_outcome which generates
NetworkRequests::ReceiptOutComeRequest messages.
- Those end up in PeerManagerActor::handle_msg_network_requests which
sends it over network as RoutedMessageBody::ReceiptOutcomeRequest.
- That is handled by PeerActor::receive_view_client_message which
repackages it into NetworkViewClientMessages::ReceiptOutcomeRequest
and sends it to ViewClientActor.
- ViewClientActor gets the outcome and in response sends
a NetworkViewClientResponses::ReceiptOutcomeResponse.
- This ends up back in PeerActor where the response is caught by
a catch-all `_ => {}` case which ignores it.
Seems like, we can get rid of pretty much everything in that chain
starting from …

chain: cleanup ReceiptOutcomeRequest et al.

---

nearcore/src/config.rs
pytest/lib/cluster.py

The commit breaks ‘sanity/repro_2916.py’ and ‘sanity/gc_sync_after_sync.py
swap_nodes’ python tests.
This reverts commit 9d71da60266dd90667ef15ad035250f5dde73814.

Revert "add config check that validators track all shards (#7383)"

---

chain/client/src/adversarial.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/view_client.rs
chain/jsonrpc/src/lib.rs

We accidentally made the whole `SetSyncInfo` infra dead code in
https://github.com/near/nearcore/pull/7171
The main change in that PR was the switch from "network pulls data from
client" to "client pushes data to network" model, so we effectively move
this adv control over to client here.
Perhaps it would be cleaner to scope this to just `PeerManager`,
without going through client, but perhaps not -- client has much more
extensive infra for adversarial patching.

test: fix wrong_sync_info.py

---

core/chain-configs/src/genesis_config.rs
core/chain-configs/src/genesis_validate.rs
integration-tests/src/node/mod.rs
integration-tests/src/tests/standard_cases/runtime.rs
nearcore/src/runtime/mod.rs
runtime/runtime/src/lib.rs
test-utils/testlib/src/runtime_utils.rs
tools/state-viewer/src/state_dump.rs
tools/storage-usage-delta-calculator/src/main.rs

Genesis::records are not guaranteed to be set since the records may
reside in records file instead.  Code accessing that field directly
(without taking records_file field into consideration as well) is
technically incorrect and violates Genesis’ encapsulation.
Make the records an records_file private to force all users of the
class to uses provided methods rather than accessing the fields
directly.  To accommodate all usage, introduce records_len and
force_read_records methods.
Note that this isn’t the state we’d like the struct to be in.
Ideally, we’d have an enum which either holds the records in a vector
or path to the file with the records.  This commit is a step into that
direction.

core: make Genesis::records and records_file private

---

chain/epoch_manager/src/lib.rs
nearcore/src/runtime/mod.rs
nearcore/src/shard_tracker.rs

The mechanical change here is rather small: rename SafeEpochManager to
EpochManagerHandle, and move it from nearcore to epoch_manager crate.
The architectural implications are rather large in contrast. What I aim
to do eventually is to remove EpochManager from RuntimeAdapter trait and
instead force everyone who needs em to hold EpochManagerHandle, rather
than dyn RuntimeAdapter. That way, the RuntimeAdapter would become
essentially stateless, and the shared mutable state of epoch manager
would be explicitly accounted for.
work towards #6910

refactor: introduce EpochManagerHandle

---

runtime/runtime-params-estimator/src/transaction_builder.rs

When all accounts have been used and an estimation requests
an unsued account, the estimator panics instead of hanging in an
infinite loop.
Example error:
```
thread 'main' panicked at 'All accounts used. Try running with a higher value for the parameter `--accounts-num <NUM>`.', runtime/runtime-params-estimator/src/transaction_builder.rs:99:13
```
resolves #7448

fix: avoid infinite loop in estimator

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer/testonly.rs
chain/network/src/peer_manager/peer_manager_actor.rs

Removed a wrapper which was supposed to be used for fancy throttling based on the amount of memory used by the inflight requests (it was abandoned though). Instead, we will eventually do some standard throttling based on the incoming QPS and the inflight request count.

removed wrapper of PeerManagerActor actix address

---

chain/chain/src/store_validator.rs
core/store/src/columns.rs
core/store/src/db/rocksdb.rs

DBCol::variant_name method is redundant considering it can be easily
replaced by the features of the Display trait in all places where it
is currently used.

store: remove DBCol::variant_name

---

chain/indexer/src/streamer/mod.rs
chain/network/src/peer_manager/peer_store_test.rs
core/store/benches/store_bench.rs
core/store/src/config.rs
core/store/src/db/rocksdb.rs
core/store/src/lib.rs
core/store/src/migrations.rs
genesis-tools/genesis-populate/src/main.rs
genesis-tools/genesis-populate/src/state_dump.rs
nearcore/benches/store.rs
nearcore/src/lib.rs
nearcore/src/migrations.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/src/main.rs
test-utils/runtime-tester/src/run_test.rs
test-utils/store-validator/src/main.rs
tools/mock-node/src/setup.rs
tools/state-viewer/src/cli.rs

Having a Result allows for the error to be propagated to the user in
nicer form than in a panic message.  This will also help in the future
expansion of the StoreOpener::open method to return different kinds of
failures which may be handled by the caller in different ways.

store: make StoreOpener::open return Result rather than panicking

---

core/store/src/config.rs
core/store/src/db/rocksdb.rs

Introduce Mode::ReadWriteExisting for opening a database.  It’s like
Mode::ReadWrite except it requires that the database exists and will
not create it if it doesn’t.
This is currently unused, but it’s going to be used in future commits.

store: add Mode::ReadWriteExisting

---

core/store/src/config.rs
core/store/src/db.rs
core/store/src/db/rocksdb.rs
core/store/src/db/rocksdb/snapshot.rs
core/store/src/lib.rs
nearcore/src/lib.rs

Move code which creates and deletes database migration snapshot to
near-store crate from nearcore.  This is done by introducing
a near_store::Snapshot struct which creates the snapshot and allows
to delete it once the migration finishes.
While at it, implement Drop for Snapshot which logs the location of
the snapshot.  With it, if migration is interrupted and the snapshot
is not removed, the location will be printed near the end of the log
pointing user at it.
My overall goal here is to move use_db_migration_snapshot and
db_migration_snapshot_path options from node Config into StoreConfig.
In the future, once we have cold storage, this will allow configuring
different locations for snapshots of hot and cold databases.

store: move database migration snapshot handling to near-store

---

Cargo.lock
chain/chain-primitives/src/error.rs
core/store/Cargo.toml
core/store/src/migrations.rs
nearcore/src/lib.rs
nearcore/src/migrations.rs

Rather than panicking which gives a somewhat dry and very technical
error message to the user, propagate errors when migrating up the
stack.

store: propagate errors from migration functions

---

chain/chain/src/types.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
nearcore/src/config.rs

Update the default value for `min_gas_price` when creating a new chain
to the effective value we use in mainnet today. (10e9 ->10e8)
This changes the gas price for new chains, localnet and sandbox.
Also add some comments to `fn min_gas_price` to improve clarity.
Resolves #7466

fix: default genesis minimum gas price

---

core/primitives/src/version.rs

also set the PEER_MIN_ALLOWED_PROTOCOL_VERSION to PROTOCOL_VERSION-1, so that we can reject old binaries from the network in 2 releases.

bumped PROTOCOL_VERSION for shardnet

---

chain/network/src/peer_manager/peer_manager_actor.rs

Every other log message does specify `target`, and this inconsistency messes with logs ingestion into Grafana.

fix(o11y): Add a missing `target` to a log message

---

integration-tests/src/tests/client/chunks_management.rs

#7385 made chunk forward messages sent to all chunk producers irrespective of shard assignment. This test suite was assuming the previous behavior that forward messages only went to the chunk producers that care about the specific shard. It's still a useful test suite though because it was testing the chunk fetching timeout behavior. So this PR conditionally drops all chunk forward messages so we can focus on testing the chunk fetching behavior.

test: Fix chunks_recovered_from_full_timeout_too_short.

---

core/store/src/db.rs
core/store/src/db/refcount.rs
core/store/src/lib.rs

Add get_with_rc_stripped method to the Database trait which strips the
reference count from the returned value.
Previously, Store::get method called get_raw_bytes and then (for
reference counted columns) refcount::get_with_rc_logic to strip the
reference count.  With this change, it now calls either get_raw_bytes
or get_with_rc_stripped as needed.
The reason for this addition is to help with cold storage.  We don’t
want to keep refcounts in cold storage which means that we would need
to append dummy refcount to get_raw_bytes calls against cold storage.
By having a separate method which returns values without refcount, we
won’t need to worry about this dummy count.
As a side benefit, this removes a memory allocation when reading
a reference counted column.  Previosly get_payload method was …

store: introduce Database::get_with_rc_stripped method

---

Cargo.lock
chain/network/Cargo.toml
chain/network/src/testonly/mod.rs
deny.toml

Firstly, update rand dependency to 0.7 to put the crate more in line
with the rest of the repository.
Furthermore, switch from rand_pcg to rand_xorshift.  The latter is
already used in a couple places while near-network was the only user
of the former so it’s best to converge on a single crate.

network: update to rand 0.7 and switch from PCG to xorshift

---

pytest/tests/sanity/rosetta.py

Commit 028fa7c9: ‘default genesis minimum gas price’ changed the
localnet gas price and broke Rosetta test.  Fix it.
Issues: https://github.com/near/nearcore/issues/7466

pytest: fix sanity/rosetta.py test

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer/testonly.rs
chain/network/src/peer_manager/connection.rs
chain/network/src/peer_manager/peer_manager_actor.rs

outgoing_peers is an additional piece of state which prevents a race condition when 2 peers are trying to connect to each other at the same time. We will need that duplicated for the TIER1 connection pool, so I moved this functionality inside of connection::Pool. Also, I applied RAII pattern to make sure that the elements of outgoing_peers (aka outbound_handshakes) are eventually removed.

moved outgoing_peers inside connection::Pool

---

Cargo.lock
core/crypto/Cargo.toml
core/crypto/src/randomness.rs
core/crypto/src/signature.rs
core/crypto/src/vrf.rs

Everything we need from rand_core is re-exported by rand crate which
we’re already depending on.  There’s no need to depend on rand_core
directly.

crypto: remove direct dependency on rand_core

---

core/primitives/src/challenge.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_storage.rs
core/store/src/trie/trie_tests.rs

Replace all caching and recording fields in trie storage to keep the
raw node’s bytes as `Arc<[u8]>` rather than `Vec<u8>`.  This forced
changing of the challanges::PartialState to use an Arc as well.

core: avoid Vec↔Arc conversions when reading trie nodes

---

chain/chain/src/test_utils.rs
core/primitives/src/types.rs
core/store/src/trie/mod.rs
core/store/src/trie/state_parts.rs
nearcore/src/runtime/mod.rs

When a node is retrieved its raw bytes end up in an `Arc<[u8]>`.  This
is because it’s how the value is stored in cache.  StateRootNode, on
the other hand, keeps the data as a vector which means that a new
object needs to be allocated from the shared slice.
Replace the `data` in StateRootNode to keep an Arc such that this
conversion is no longer necessary.

primitives: keep data as Arc<[u8]> in StateRootNode

---

core/store/src/trie/trie_storage.rs

Finding the counter of a metric is a relatively expensive operation,
when compared to just updating its value. A performance regression
of about 20% on read perfromance has been observed due to additional
metrics added in #7429.
This commit stores the counters in `TrieCacheInne` and
`TrieCachingStorag` to avoid the lookup in hot paths like when
we hit the shard or chunk cache.

perf: avoid expensive lookup of storage metrics

---

runtime/runtime-params-estimator/src/transaction_builder.rs

Improve the performance of selecting random unused account in https://github.com/near/nearcore/blob/master/runtime/runtime-params-estimator/src/transaction_builder.rs. See #7450 for more details.

refactor: imporve performance of random unused account selection

---

core/store/src/config.rs
core/store/src/db/rocksdb/snapshot.rs
core/store/src/lib.rs
nearcore/src/config.rs
nearcore/src/lib.rs

Deprecated use_db_migration_snapshot and db_migration_snapshot_path
fields in Config by migration_snapshot field in StoreConfig.  The main
motivation for doing it is being able to configure the path separately
for hot and cold storage (once cold storage is implemented).

store: add StoreConfig::migration_snapshot option; deprecated options in Config

---

integration-tests/src/tests/nearcore/rpc_nodes.rs

Commit 028fa7c9: ‘default genesis minimum gas price’ changed default
minimum gas price in localnet which affected actual values in the
test.  Adjust the expected values to match thus fixing the test.
While at it, refactor the code slightly to reduce all the indentation.
Issues: https://github.com/near/nearcore/issues/7466

integration-tests: fix test_tx_not_enough_balance_must_return_error

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/private_actix.rs

Now that propose_edge is a method of NetworkState, PeerActor is able to call it directly.

removed UpdateEdge from PeerManagerActor

---

core/store/src/db.rs
core/store/src/db/rocksdb.rs
core/store/src/db/testdb.rs
core/store/src/lib.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/testbed.rs

Run compaction on the DB after inserting all records from the state
dump. This brings the layout of SST files to a more stable and optimal
layout. See #4771 for more details.
This is an estimator only change.

feat(estimator): compact RocksDB in testbed setup

---

runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/runtime/src/actions.rs

Just minor cleanups:
* remove needles `&mut`
* flatten the entry point a bit
* collapse two unwraps into one

refactor: cleanup contract runtime entry point

---

core/store/src/flat_state.rs
core/store/src/trie/shard_tries.rs

Add flat_state::maybe_new function which creates FlatState object when
requested and the feature is enabled.  This removes bunch of
annotations and noise from shard_tries.rs.
Furthermore, split definition of FlateState to one when the feature is
enabled and another when it’s disabled.  This further removes bunch of
annotations this time at definition place.
Furthermore, by making the latter impossible to instantiate (by using
an enum with no variants) this encodes in the type system that the
flat state won’t be created if the feature is not enabled and its
method won’t be called.  This also makes `Option<FlatState>` a ZST.

store: refactor flat_state.rs to reduce amount of annotations

---

pytest/tests/sanity/one_val.py

The test broke after recent changes to tracked shards configuration
options.  Fix it.

pytest: fix one_val.py test

---

chain/chunks/src/chunk_cache.rs
chain/chunks/src/lib.rs

A validator may receive the same part multiple times for various reasons such as retries. Don't forward the same part twice.

Do not forward the same chunk part twice.

---

core/store/src/trie/iterator.rs

This avoids an `expect` present in the second invocation.

core: avoid double Vec::last call in TrieItorator::iter_step

---

chain/network/src/peer/codec.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/stats/metrics.rs

When profiling memory usage, I've noticed non-trivial amount of space is occupied by net IO buffers. So, let's add metrics to track their size!
We use SockAddr, rather than `PeerId`, as a label here, as we don't know peer ids for outgoing connections. 
I don't worry much about perf hit here -- we more or less do a syscall here, that should dominate metric bump. 
The implementation is a bit hacky, but the "proper" fix would probably require unforking the FramedRead/Write infrastructure.

feat: track current sizes of network buffers

---

CHANGELOG.md
chain/network/src/stats/metrics.rs

Deprecate near_peer_message_received_total Prometheus metric in favour
of aggregating near_peer_message_received_by_type_total metric instead.

network: deprecate near_peer_message_received_total

---

core/metrics/src/lib.rs

This ... is somewhat questionable API, let's remove it if we are not
using it.
Was added and removed in
* 061161bd7b8566bea541537d6d98177ee6246827
* 1198ec789abcdf71fecbe37b3be81ad00417146d

chore: remove dead code

---

core/store/src/trie/mod.rs

Extend test_iterator_seek by adding verification of known existing
keys.

store: extend test_iterator_seek test

---

core/store/src/opener.rs
nearcore/src/lib.rs

This does three relate things:
1. When opening the database in read-only mode, StoreOpener now checks
whether database version is the one node is built for.  If it
isn’t, opening fails.  This is because we cannot perform migrations
in read-only mode so there’s nothing we can do with the database.
2. When creating the database, initialise it by setting its version to
the one node was built for.  This moves the code from nearcore.
3. Introduce StoreOpener::create which refuses to open already
existing database.  Motivation here is mostly to remove database
existence check from recompress_storage and thus get rid of the
check_if_exists method to shrink StoreOpener API.

store: introduce StoreOpener::create; deal with version in StoreOpener

---

core/store/src/config.rs
core/store/src/db/rocksdb.rs
core/store/src/db/rocksdb/snapshot.rs
core/store/src/opener.rs
nearcore/benches/store.rs
nearcore/src/lib.rs
tools/state-viewer/src/cli.rs

Introduce new mode for opening the storage, Mode::Create, and use it
instead of StoreOpener::create method.  This is removes some
nonsensical combinations where one might set mode to ReadOnly or
ReadWriteExisting and then call create method.
Furthermore, get rid of StoreOpener::mode method and instead add
StoreOpener::open_in_mode which takes the mode at the moment when
database is opened.  I’d say it ends up being more readable as the
mode is always specified at the exact same location where function to
open the storage is called.

store: replace StoreOpener::create with Mode::Create

---

core/store/src/db/rocksdb/snapshot.rs
nearcore/src/lib.rs

If Snapshot::remove failed to delete the snapshot it would log the
error but wouldn’t propagate it letting the node continue to work. The
reasoning was that the database has migrated so there’s no harm just
going on.
However, it’s possible that operator won’t notice errors in the log
and leave the snapshot around.  This will waste space but also cause
next migration to fail.  What’s worse, that failure will recommend
rolling back to the existing snapshot.  This may result in database
being rolled back to state from weeks or months ago.
Change this behaviour by making Snapshot::remove propagate the error
and opening of the database failing if the removal fails.

store: propagate error when deleting the snapshot

---

chain/chunks/src/lib.rs

See https://github.com/near/nearcore/pull/7595 for context. The tests were failing because of this assert.
This assert should actually be a return; see the code comments.
Stress-ran the sync_state_nodes_multishard test 50 times; used to be flaky, now passes.

Fix failing tests by removing an assert that was actually possible

---

.buildkite/pipeline.yml

We used to have a Redis test which required running instance of Redis
running on the machine.  However, the test has been removed in commit
83a08f5b02f090363dd21f8601f6b0165f651875 so it’s no longer necessary
to set the instance up on CI.

buildkite: don’t start Redis when running tests

---

CHANGELOG.md
chain/jsonrpc/client/src/lib.rs
chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
chain/jsonrpc/src/api/query.rs
core/primitives-core/src/serialize.rs
integration-tests/src/user/rpc_user.rs

This has been deprecated at least since August 2020 (see #3237), isn’t
documented and it’s probably fair to say that anyone who cared
migrated to JSON RPC requests.
As a side effect, this allows us to get rid of from_base58 function.

json: remove deprecated old style path+data request format

---

pytest/tests/sanity/db_migration.py

Since db_migration.py uses the stable neard to initialise the node, it
results with config.json with use_db_migration_snapshot field
set. This makes the new binary complain when it tries to run
migration.
Note that this shouldn’t be a major issue in production since config
files offered on S3 don’t have that field set.

pytest: fix db_migration.py after changes to migration config options

---

chain/network-primitives/src/network_protocol/mod.rs

PartialEncodedChunk is deprecated and effectively unused. It is VersionedPartialEncodedChunk which is sent by chunk producer to approvers and should be reliably delivered.

VersionedPartialEncodedChunk is important

---

chain/network-primitives/src/network_protocol/mod.rs
chain/network/src/network_protocol/mod.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs

PartialEncodedChunk was deprecated in favor of VersionedPartialEncodedChunk for 2 years now: https://github.com/near/nearcore/pull/3463
It is confusing, in particular we have configured PartialEncodedChunk to be sent out 3x (to make it delivered reliably) while
we should have done that for VersionedPartialEncodedChunk (which is still sent out just 1x).
There is a codepath which encodes V1 PartialEncodedChunk into this specific RoutedMessagebody variant, however while decoding this distinction is lost. Technically this PR should be split into 2 separate rollouts (first: stop using the deprecated variant to send messages; second: stop accepting the deprecated variant). The situation gets even more complicated, because network protocol is supposed to be backward compatible for 2 versions …

removed deprecated RoutedMessageBody::PartialEncodedChunk

---

Cargo.lock
runtime/near-vm-errors/Cargo.toml
runtime/near-vm-errors/src/lib.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/metrics.rs

Provides visibility into the success rate of processing function call actions.
In case of errors, this PR also counts the error types and sub-types where it makes sense.
Would be useful to have `shard_id` in these metrics, but the runtime is not supposed to know anything about epochs, shard layouts, etc.
```
near_function_call_processed{result="FunctionCallError"} 17
near_function_call_processed{result="ok"} 1088
near_function_call_processed_function_call_errors{error_type="HostError"} 17
near_function_call_processed_host_errors{error_type="GasLimitExceeded"} 5
near_function_call_processed_host_errors{error_type="GuestPanic"} 12
```

Function call success and error metrics

---

chain/chain/src/chain.rs
chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/chunks/src/lib.rs
core/primitives/src/challenge.rs
core/primitives/src/merkle.rs
core/primitives/src/validator_signer.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs
integration-tests/src/tests/nearcore/sync_nodes.rs
integration-tests/src/tests/standard_cases/mod.rs
runtime/near-vm-runner/src/cache.rs

CryptoHash::hash_borsh doesn’t allocate a vector where the object is
serialised into instead calculating the hash directly as the data is
serialised.  This reduces amount of memory allocations and thus
optimises the code.
It is worth noting however that while try_to_vec may fail, hash_borsh
panics on failures.  In most cases we were unwrapping the result of
serialisation anyway, but it does change behaviour in chain which used
to propagate the error and now it’s panicking on failure.  However,
that code operates on values which in practice cannot fail
serialisation so the change should be fine.

Prefer CryptoHash::hash_borsh to try_to_vec+hash combo

---

chain/network/src/peer_manager/network_state.rs
chain/network/src/peer_manager/peer_manager_actor.rs

spawn_outbound takes self as `Arc<Self>` but then calls
spawn_peer_actor passing it as `&Arc<Self>`.  The latter then clones
the Arc.  Meanwhile, Arc owned by spawn_outbound gets dropped.  Fix by
changing all the methods to take an Arc and moving cloning to the call
sites.

network: avoid double Arc::clone in NetworkState

---

chain/chain/src/store.rs
chain/chain/src/store_validator.rs
chain/chain/src/store_validator/validate.rs
core/primitives-core/src/types.rs
core/store/src/columns.rs
core/store/src/db/rocksdb.rs
test-utils/store-validator/src/main.rs

We’re writing to the GCCount column but never read from it in
production. It’s only ever used in store validator but even there zero
values in garbage-collected columns results in the column being
printed at the end of the validation rather than any kind of failure.
So really, I’d argue the column doesn’t serve any purpose.
Removing the column not only simplifies the code but also allows us to
get rid of borsh serialisation of the DBCol enum.  This in turn means
that now the variants in the enum can be rearranged or deleted without
breaking things.
Note that I’m not clearing out this column in this commit.  I’m
planning to introduce an unrelated database migration soon and will do
the clearing then.

store: deprecate GCCount column

---

chain/chunks/src/lib.rs
core/primitives/src/sharding.rs
core/primitives/src/version.rs

Replace ShardChunkHeader::version_range and
PartialEncodedChunk::version_range methods with valid_for method which
is simpler interface for the call site and which allows us to get rid
of custom ProtocolVersionRange type.
Note that, yes, PartialEncodedChunk::valid_for is actually unused.
I’m leaving it in though.  Perhaps it’s worth keeping the record of
when each version of the PartialEncodedChunk was introduced?

core: replace ShardChunkHeader::version_range by valid_for

---

.cargo/config.toml

Cargo's bug repro: https://github.com/rust-lang/cargo/pull/11114
This has caused the flag not to be passed into rocksdb -- therefore impacting node performance.

Rollback of #7130 - due to cargo issue

---

runtime/near-test-contracts/estimator-contract/Cargo.toml
runtime/near-test-contracts/estimator-contract/src/lib.rs

Makes estimations run again (with and) without `--features=nightly`.
#7165 introduced new methods in the estimator contract but we forgot to hide them behind cfg.

fix: estimator contract and feature_ed25519_verify

---

core/store/src/db/testdb.rs
genesis-tools/genesis-populate/src/state_dump.rs
runtime/runtime-params-estimator/src/config.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/main.rs
runtime/runtime-params-estimator/src/testbed.rs

Do not use RocksDB for qemu based estimations, it is very slow and has
very high variance. It also doesn't measure anything useful, the IO
bytes that we count are not a good approximation for IO costs at all.
See #6445 for a detailed explanation why this is the case.
Resolves #7526.

feat: icount estimations without RocksDB

---

.buildkite/pipeline.yml
tools/mock-node/src/setup.rs

This test actually requires `mock_node` feature to be enabled to work.
I am not sure what's the best way to run this test. The ideal solution
would be to add an extra CI job just for mock-node, but I would loath
to combinatorially inflate CI for every feature we have. Not that it
would be particularly problematic for mock-node, but it would seem
like a bad precedent. So instead I tacked mock_node to our nightly
tests. This is roughly how it worked anyway, while mock_node was
a default feature.
Of corse, in the ideal world we'd perhaps not use conditional
compilation here (or anywhere at all, really), but this isn't the
battle I am ready to fight yet.
closes https://github.com/near/nearcore/issues/7631

fix: flaky test

---

core/primitives-core/src/hash.rs
integration-tests/src/tests/nearcore/sync_nodes.rs

Turns out `CryptoHash::hash_borsh(&[foo])` doesn’t quite do what one
might expect.  Rather than hashing one-element slice (which is
serialised as length of one plus serialisation of the element) it
hashes one-element array (which is serialised as just the element).
Introduce `CryptoHash::hash_borsh_slice` to provide less error-prone
method and fix tests which fell victim of the confusion.  The tests
were broken by commit d5f650ab: ‘Prefer CryptoHash::hash_borsh to
try_to_vec+hash combo’.

integration-tests: fix hashing of a list of elements

---

Cargo.lock
chain/chain/Cargo.toml
chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/lib.rs
nearcore/src/runtime/mod.rs

Part of https://github.com/near/nearcore/issues/6910
The grand plan is to separate EpochManager out of NightshadeRuntime. As
a first step, I want to separate the *types* of runtime and epoch
manager, while keeping them in the same object. I want to do this via
the following series of steps:
```
trait RuntimeAdapter {}
```
```
trait EpochManagerAdapter {}
trait RuntimeAdapter: EpochManagerAdapter {}
```
```
trait EpochManagerAdapter {}
trait RuntimeAdapter {}
```
This PR introduces the EpochManagerAdapter infra.
You can see the rough idea of the plan in https://github.com/near/nearcore/pull/7606

refactor: add EpochManagerAdapter infra 

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/epoch-manager/src/adapter.rs
nearcore/src/runtime/mod.rs

Part of https://github.com/near/nearcore/issues/6910, depends on #7655
Must be reviewed per commit.

refactor: move signature verification functions to EpochManagerAdapter 

---

integration-tests/src/tests/client/chunks_management.rs

Adding an explicit "test fixture" struct makes call-sites more readable (named args!) and makes making further changes easier.
No particular grand plan here, just figured this small change to be a marginal improvement!

refactor: prettify chunk management test

---

chain/chain/src/chain.rs
chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/epoch-manager/src/adapter.rs
nearcore/src/runtime/mod.rs

Part of https://github.com/near/nearcore/issues/6910, depends on https://github.com/near/nearcore/pull/7656
This is slighly less trivial than pure move -- the API is adjusted to
remove direct dependency on doomslug which lives in a different crate

refactor: move verify_approvals_and_threshold_orphan to EMA 

---

chain/chain/src/test_utils.rs
chain/epoch-manager/src/adapter.rs
nearcore/src/runtime/mod.rs

Part of https://github.com/near/nearcore/issues/6910, depends on https://github.com/near/nearcore/pull/7665
Previously, this was only available on NightshadeRuntime, but seems fine
to expose everywhere.

refactor: expose get_epoch_id as a method of EpochManagerAdapter 

---

CHANGELOG.md
core/store/src/config.rs
runtime/runtime-params-estimator/src/testbed.rs

Prefetch receipt meta data (account and access keys) ahead of time.
This recent performance optimization has been disabled by default.
In lab settings, performance improvement is confirmed. Using the
estimator to measure the time it takes to process empty receipts,
on a DB with 2 million accounts, on a local SSD, with enabled shard
caches. The result is as follows.
- sender = receiver:  737us -> 386 us
- sender != receiver: 1014us -> 644us
- overhead per block: 6.9us -> 7.4us
Note that this is with 100 empty receipts in the same block, with all
different accounts. In real traffic it usually does not happen that so
many different accounts are accessed in the same block. But it is
allowed and we must be able process this case in reasonable time.
So even if it might not help in the average …

feat: enable receipt prefetching by default

---

chain/chain-primitives/src/error.rs

Make it clear what kind of thing is missing from the DB. Ideally, we'd
add a db_col field to the error, but that's going to be a much larger
change.

refactor: more useful error message

---

chain/chunks/src/client.rs
chain/chunks/src/lib.rs
chain/chunks/src/test_utils.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/test_utils.rs
chain/client/src/tests/chunks_management.rs
integration-tests/src/tests/client/challenges.rs
integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/runtimes.rs
integration-tests/src/tests/client/shards_manager.rs

* Move handling of chunk completion to a ClientActor message (ShardsManagerResponse), because this will eventually be async. So no more passing DoneApplyingChunksCallback. Add support of this message to TestEnv; tests that rely on chunk part messaging now need to manually handle such messages (because the TestEnv doesn't have real actors). Fixed tests that need this.
* Move ReedSolomonWrapper inside ShardsManager. However Client still has a copy because it actually needs to encode the parts to produce a chunk - at least the merkle root is needed.
* Does not touch ChainStore yet. Leaving that till later.
* Minor refactoring to push chunk part processing logic from Client into ShardsManager (otherwise Client needs to fetch header and stuff).

[chunks] Move chunk completion out of ShardsManager

---

runtime/runtime-params-estimator/estimator-warehouse/src/check.rs
runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-2.snap
runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-3.snap
runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-4.snap
runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command.snap
runtime/runtime-params-estimator/estimator-warehouse/src/zulip.rs

resolves #7004, see that issue for reasoning behind the change

feat: always display uncertain estimation warnings

---

chain/chain/src/store.rs
chain/chunks/src/chunk_cache.rs
chain/chunks/src/lib.rs
core/store/src/columns.rs
core/store/src/db/colddb.rs
core/store/src/db/rocksdb.rs
core/store/src/migrations.rs
core/store/src/version.rs
nearcore/src/lib.rs
tools/mock-node/src/lib.rs

This column is only used by ShardsManager to reject an incoming partial chunk. Previously, the column is written in two ways:
1. When a partial encoded chunk's header is validated by ShardsManager, it will write this column. As long as the header is valid, this column will map the (height, shard ID) to the chunk's hash.
2. When a block is processed by the Client, we will write each chunk in that block to this column.
This PR moves the mapping into memory. That means that upon a restart we will have an empty mapping. This should be OK: consider two nodes, one running the old version and one running the in-memory version; since the old version's mapping is a superset of the new version's in-memory mapping, there are two possible cases when the two nodes obtain different lookup results:
1. …

Remove DBCol::ChunkPerHeightShard

---

core/store/src/trie/prefetching_trie_storage.rs

The bounded queue was intended to drop new requests on the sender side
instead of blocking the main thread.
The prefetching requests we send today are at least 100 times fewer
than what fits in the channel, and only white listed accounts can even
trigger it. So this is not a concern in practice, yet.

fix: do not block on prefetcher

---

chain/chain/src/chain.rs
chain/chain/src/test_utils.rs
chain/chain/src/types.rs
core/store/src/flat_state.rs
nearcore/src/runtime/mod.rs

We create FlatStorageState on Chain creation, but it currently happens for any RuntimeAdapter impl. Because KeyValueRuntime doesn't and shouldn't support flat storage, it leads to tests failures.
Here we move FSS creation inside RuntimeAdapter impl.
https://buildkite.com/nearprotocol/nearcore-flat-state/builds/60#018383c5-7838-4e5b-86f1-da2baa381789 - number of failing tests drops from 77 to 4 - which are failing due to other reasons

fix: create FlatStorageState inside RuntimeAdapter

---

chain/chain/src/chunks_store.rs
chain/chain/src/lib.rs
chain/chain/src/store.rs
chain/chunks/src/client.rs
chain/chunks/src/lib.rs
chain/chunks/src/logic.rs
chain/chunks/src/test_utils.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/test_utils.rs
chain/client/src/tests/chunks_management.rs
integration-tests/src/tests/client/challenges.rs
integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/runtimes.rs
integration-tests/src/tests/client/sharding_upgrade.rs

ShardsManager currently needs mutable access to ChainStore for persisting PartialEncodedChunk (for parts and receipts that the node tracks), ShardChunk (if the chunk is Reed-Solomon reconstructible), and EncodedShardChunk for chunks that were invalid. This PR moves all these writes out from the ShardsManager, into the Client. They are persisted in three ways:
When on_chunk_completed(partial_chunk: PartialEncodedChunk, shard_chunk: Option<ShardChunk>) is called (which is invoked by the ClientActor upon receiving a ChunkCompleted message sent by ShardsManager), we persist the partial chunk and optionally the shard chunk.
Similar case as above, but for on_invalid_chunk(encoded_chunk: EncodedShardChunk).
When we are a chunk producer and produces a chunk; we immediately persist the …

[chunks] Move ChainStore use out of ShardsManager and into the Client

---

pytest/tests/sanity/rosetta.py

The transfer_fee_type metadata field has been introduced in 7a663fce2
without updating the test.  Do it now.
Issue: https://github.com/near/nearcore/issues/7654

pytest: fix Rosetta test after addition of transfer_fee_type

---

CONTRIBUTING.md
docs/architecture/README.md

This pulls mode useful bits from
https://wiki.near.org/contribute/contribute-nearcore and in general makes this more hands on, urging the prospective contributor to get the hands dirty as soon as possible :)
I want to dissolve "Build Process" section as well and move it to a dedicated doc, but that's for a different PR.

docs: refresh CONTRIBUTING.md

---

CONTRIBUTING.md
docs/SUMMARY.md
docs/practices/fast_builds.md

Mostly moves content from
https://wiki.near.org/contribute/contribute-nearcore#how-to-speed-up-rust-compilation-time.
I also trimmed it a bit to be shorter and more to the point.

doc: move build optimization content from wiki into internal docs

---

Cargo.lock
tools/rpctypegen/macro/Cargo.toml
tools/rpctypegen/macro/src/lib.rs

The macro can be invoked by several processes, so we need some kind of
IPC lock here to avoid reading garbage data.
File locks are a sketchy technology, but what we are doing here is
already quite gross :-)
closes https://github.com/near/nearcore/issues/7757

fix: race condition in rpctypegen macro

---

nearcore/src/config.rs

I’m planning to deprecate `archive` configuration option.  Removing it
from `config.json` when it’s false (its default value) will help with
that.

nearcore: don’t serialise `archive` if false

---

Cargo.toml
pytest/tests/loadtest/contract/Cargo.toml

loadest isn't part of our top-level workspace. We also shouldn't be
using `near-sdk` here ideally, but that's a different story.
https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/pytest.2Floadtest.20broken.3F

fix: broken pytest

---

CHANGELOG.md
nearcore/src/config.rs

Validators are already adding their public IPs to the configs (some correctly, some incorrectly) and this PR enables broadcasting this information to the network. It will allow us to monitor whether broadcasting works and check whether validators have correctly configured their public IPs. So far TIER1 peer discovery has been enabled in shardnet (while it still existed) and no regression has been observed.
The TIER1 connections are still not established, the relevant code will be merged in another PR (possibly protected with a separate feature flag, and this flag will be renamed accordingly).

enabled TIER1 peer discovery in all envs

---

core/primitives/src/types.rs
core/store/src/lib.rs
runtime/near-vm-runner/src/cache.rs

precompile_contract_vm function is not interested in the actual
compiled contract code, it only cares whether the cache contains it.
However, at the moment it uses CompiledContractCache::get method which
clones the data read from the database.  Introduce a has method which
only checks whether the value exists or not.

store: introduce CompiledContractCache::has to avoid data cloning

---

core/store/src/flat_state.rs

If we move flat storage head, all deltas with heights not exceeding new head height become obsolete and have to be removed. Storing them in both memory and disk is a big concern because theoretical boundary on their sizes has an order of 100 MBs and we can't afford more than tens of blocks here.
Currently we just iterate over all available blocks in memory to find data to be removed, but we can consider more optimal versions in the future.
The implementation is safe because head update, applying deltas and removing old deltas happen in a single DB transaction. If node crashes in the middle, during restart new flat storage is created which takes all blocks and deltas from disk again.
* Updating `flat_storage_state_sanity` test
* Checking logs of localnet node. It is expected that number of …

feat: gc deltas and block infos from flat storage

---

Cargo.lock
Cargo.toml
deny.toml
runtime/runtime-params-estimator/Cargo.toml
runtime/runtime-params-estimator/src/vm_estimator.rs

The only thing for which walrus was used was `walrus::Result`.  The
fun fact is that this is literally just `Result` if both generic
arguments are specified.  Remove the unnecessary dependency on walrus.

runtime-params-estimator: remove unused walrus dependency

---

core/o11y/src/lib.rs

Provide a command-line flag to enable span events.
This reduces debug log volume by a factor of approximately x8.

feat(o11y): Disable span events in logs by default

---

chain/chain-primitives/src/error.rs
chain/chain/src/chain.rs
chain/chain/src/tests/challenges.rs
chain/chain/src/tests/simple_chain.rs
chain/client/src/client.rs
integration-tests/src/tests/client/process_blocks.rs

Because flat storage head is correlated with final head, we won't be able to process blocks on top of blocks which are behind final head. Processing such blocks doesn't make sense anyway, because they will never be finalized. We can check it during header validation and avoid attempts to apply chunks.
More concretely - we check parents of the new block, and if we fall behind final head at some point, we declare that block can't be finalized and return an error. To avoid long delays, we limit number of checked parents to 20.
* Existing tests.
* Updating `simple_chain` tests to reflect new behaviour
* `process_blocks::test_discard_non_finalizable_block` - integration test for checking chain behaviour

feat: discard non-finalizable blocks

---

chain/indexer/src/streamer/mod.rs

There is a typo in chain/indexer/src/streamer/mod.rs
`PROBLEMATIC_BLOKS` needs to be fixed to `PROBLEMATIC_BLOCKS`.

doc: fix typo in chain/indexer/src/streamer/mod.rs

---

chain/chain/src/chain.rs
chain/chunks/src/client.rs
chain/chunks/src/lib.rs
chain/client/src/client.rs

so that tx_pool will be synchronously used by the Client. Its functionality is completely independent from ShardsManager.

[chunks] Move tx_pool out of ShardsManager.

---

CHANGELOG.md
chain/jsonrpc/client/src/lib.rs
chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
chain/jsonrpc/src/api/query.rs
core/primitives-core/src/serialize.rs

Turns out there still are users of the old query format.  Bring it back.
This reverts commit be8a1ea7ded5c03a555421a009dd22d8c3499f01.
Fixes: https://github.com/near/nearcore/issues/7769

Revert "json: remove deprecated old style path+data request format"

---

integration-tests/src/tests/client/features/chunk_nodes_cache.rs

When we add flat storage, it is expected that we should record less DB
and memory trie node accesses. Here we simply change and explain the
values in test.
Small note: tests like `test_chunk_nodes_cache_same_common_parent`
still pass, because for nodes created there flat storage is not used.
https://buildkite.com/nearprotocol/nearcore-flat-state/builds/70#0183c218-7b2c-4eea-8cd6-32f80cec0441
Now all integration tests pass, if we unite this PR with
https://github.com/near/nearcore/pull/7789.

fix: adjust behaviour of chunk nodes cache test

---

tools/mock-node/src/lib.rs

`test_chain_history_access` fails because `setup_mock` creates two `Chain`s, each of them tries to create flat storage, and the latter one fails because the object already exists.
Looks like that `Chain::new_for_view_client` is a nice fix, because it is allowed to have both regular and view clients accessing the same shard.
Existing tests.

fix: failing mock node test for flat state

---

core/store/src/db/rocksdb.rs

iter can be view as a special case of iter_prefix when an empty prefix
is given.  There’s no reason to have a separate state for ‘no prefix’
and ‘empty prefix’ which is something RocksDB::iter_raw_bytes_impl
did.  Simplify it and all callers by simply handling empty prefix.

store: simplify RocksDB::iter, iter_prefix and iter_raw_bytes

---

chain/chain/src/chain.rs
chain/chain/src/store.rs
chain/chain/src/store_validator.rs
chain/chain/src/store_validator/validate.rs
core/primitives/src/transaction.rs
core/primitives/src/utils.rs
core/store/src/columns.rs
core/store/src/db/rocksdb.rs
core/store/src/migrations.rs
core/store/src/version.rs
nearcore/src/migrations.rs
tools/state-viewer/src/apply_chain_range.rs
tools/state-viewer/src/apply_chunk.rs

This migrates TransactionResult column, which mapped OutcomeId
(CryptoHash of transaction or receipt) to
`Vec<ExecutionOutcomeWithIdAndProof>` (outcome, outcome ID, proof,
block hash), to a new column TransactionResultForBlock, which maps
(OutcomeId, BlockHash) to singular ExecutionOutcomeWithProof (outcome,
proof).
Note that an execution of a transaction or receipt may have multiple
outcomes due to forks; that's why we store a list of them.  The old
implementation had to append to this list whenever it commits a new
block to the store, leading to a read-modify-write operation.  The new
implementation directly writes to an entry keyed by both the outcome
ID and block hash.
At RPC time, we will do a prefix scan using the OutcomeId to achieve
the equivalent querying capability as today.
A …

store: flatten TransactionResult column to remove need for RMW

---

chain/chain/src/chain.rs
chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/chunks/src/lib.rs
chain/network/src/network_protocol/edge.rs
chain/network/src/network_protocol/mod.rs
core/primitives-core/src/hash.rs
core/primitives/src/merkle.rs
core/primitives/src/network.rs
core/primitives/src/transaction.rs
core/primitives/src/validator_signer.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs
runtime/near-vm-runner/src/cache.rs

This makes call sites simpler and there is no need to require that
argument to CryptoHash::hash_bytes is a reference.  There’s a blanket
implementation for references so caller still has that option if they
need it.

core: accept passing arguments by value in CryptoHash::hash_bytes

---

runtime/runtime/src/lib.rs

Seems "treasure" should be changed to "treasury"

doc: fix typo treasure -> treasury

---

chain/chain/src/block_processing_utils.rs
chain/chain/src/chain.rs
chain/chain/src/metrics.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs

This PR actually includes two changes that should probably be separated into two PRs, for now, they are together since they are just going to 1.30.0
1) The important change is to move the check for is_height_processed before process_block_header. Previously, this check happens after, which means, the node will re-process the block header (which takes a few ms) and re-broadcast an invalid block before drops it. In the case when there are many invalid blocks circulating in the network, this can cause the node to be too busy, 
2) A less important change is around when the block processing pool is full. Previously, we drop the block if the block processing pool is full and saves the block height as processed. This change gets rid of that because we want to be able to process the block again. …

move the check for is_height_processed forward before process_block_header

---

core/store/src/migrations.rs

https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/DB.20migrate_32_to_33.20panics
That's the only reason I could think of.

[TransactionResult] Avoid panicing if original column had duplicate entries

---

CHANGELOG.md
chain/client/src/client_actor.rs
core/primitives/src/views.rs

Currently, response to the /status request returns a `node_key`
field. However, the field does not include node key but rather
validator key.  Deprecated it in favour of two new fields:
`node_public_key` and `validator_public_key`.
Fixes: https://github.com/near/nearcore/issues/7672

client: add {node,validator}_public_key field to /status response; deprecated node_key

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/epoch-manager/src/adapter.rs
nearcore/src/runtime/mod.rs

part of https://github.com/near/nearcore/issues/6910, depends on https://github.com/near/nearcore/pull/7726

refactor: move get_validator_info to EpochManagerAdapter

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/chunks/src/test_utils.rs
chain/client/src/client_actor.rs
integration-tests/src/tests/client/process_blocks.rs
nearcore/src/runtime/mod.rs
tools/mock-node/src/setup.rs

Replace RuntimeAdapter::get_store with RuntimeAdapter::store method
which returns reference to a Store rather than cloning it.  This
avoids some instances where the Store is cloned unnecessarily.

chain: don’t clone Store in RuntimeAdapter::get_store

---

chain/jsonrpc/res/rpc_errors_schema.json
runtime/near-vm-errors/src/lib.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime/src/actions.rs

This is an actual error, not a user abort. It should be treated as such,
therefore it belongs to `VMRunnerError` and not `CompilationError`
which is part of the use abort type aka `FunctionCallError`.
`CompilationError` implements `BorshSerialize` and is used in
`FunctionCallErrorSer`. Removing `UnsupportedCompiler` is okay because:
1) The error only gets thrown from unused`precompile`. It is is dead
code in production.
2) It is the last variant in the enum and hence does not affect the
borsh serialization format of other variants.
cc #7818

refactor: move `UnsupportedCompiler` to errors

---

runtime/near-vm-errors/src/lib.rs
runtime/near-vm-runner/src/cache.rs
runtime/near-vm-runner/src/lib.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/tests/fuzzers.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmer_runner.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime-params-estimator/src/vm_estimator.rs
runtime/runtime/src/actions.rs

This does two rather big code motions at the same time (sorry!):
* precompilation code is moved from "let's match on VMKind" style to "let's call Runtime's virtual method". To do so, we re-purpose existing `precompile` functions in the trait. Remember, those fns are essentially dead code from "pipelined" compilation
* code to deal with our two-layered caching is moved from `cache.rs` into impls of VM

refactor: streamline contract caching code

---

Cargo.lock
chain/jsonrpc/Cargo.toml
chain/jsonrpc/src/api/query.rs
core/primitives-core/src/serialize.rs

Currently, when RpcRequest::parse handles legacy path+data query
format, it first decodes the data and only later checks its size.
This means that the server will dutifully decode any oversized buffer
only to discard the result later reporting an error.  Problem with
that is that base58 is an atrocious format and decoding is O(n²)
operation.  Because of that, it’s desired to stop decoding as soon as
its known that the data is too long.  Change the implementation so
that this happens.
Note that for simplicity this commit doesn’t implement a short-circuit
taking advantage of the fact that the length of the decoded string can
be estimated based on the length of the source.  The path+data query
format is legacy and should be deleted at some point so I essentially
implemented the minimum …

jsonrpc: check base58 length limit before the whole buffer is decoded

---

runtime/near-vm-errors/src/lib.rs
runtime/runtime/src/actions.rs

`FunctionCallError::_EVMError` is not used and is not borsh serialised anywhere (unlike `FunctionCallErrorSer::_EVMError`) so there is no reason to keep it.

chore: remove FunctionCallError::_EVMError

---

chain/jsonrpc/res/debug.html

The example link leads to https://github.com/near/nearcore/tree/1.1.0-2956-g93b66337a
(Yes, that is a tag that github understands, apparently.)
#7861

[Debug UI] Show github link for version on debug page

---

chain/jsonrpc/res/rpc_errors_schema.json
core/primitives/src/errors.rs
integration-tests/src/tests/runtime/test_evil_contracts.rs
integration-tests/src/tests/standard_cases/mod.rs
runtime/near-vm-errors/src/lib.rs
runtime/runtime/src/actions.rs

The indirection from `FunctionCallError` to `ContractCallError`
to `FunctionCallErrorSer` seems to be obsolete after the latest
rounds of refactoring. Let's remove it.

refactor: remove `ContractCallError`

---

neard/src/cli.rs
neard/src/main.rs

`anyhow` is the type to return from `main`, we dont' get any value here from preserving well-typed errors, and creatng more work down the line to add all future error variants: *surely* we can fail due to more than these two errors, right?

refactor: simplify error handling in main

---

chain/client-primitives/src/types.rs
chain/jsonrpc/src/api/transactions.rs
chain/rosetta-rpc/src/errors.rs

The TxStatusError::InvalidTx variant is never constructed
so get rid of it.

chain: remove TxStatusError::InvalidTx variant

---

chain/epoch-manager/src/proposals.rs

The SliceRandom::shuffle implementation changed from rand 0.6.5 to 0.7.0 in a subtle way: https://github.com/rust-random/rand/pull/809 because the underlying gen_index implementation changed. (It appears that @matklad 's concern on #7717 turns out to be quite real!)
In order to reproduce the old behavior and to make sure this never changes again, this PR replicates the gen_index implementation (it's pretty straight-forward) from 0.6.5. The test case is updated (the old test case was unfortunately incorrect from #7717). Also, @mm-near 's #7909 now passes with this change.

[core] Fix proposals shuffling implementation

---

core/store/src/cold_storage.rs
core/store/src/columns.rs
integration-tests/src/tests/client/cold_storage.rs

This is the second column that breaks 'get keys -> combine keys -> read -> write' pipeline, but it is also the last one. Other columns don't require special magic with cache. Also, as mentioned before, this column shouldn't either, it should write values directly to colddb, not cache. This change for State and StateChanges will come in the future and it probably will not impact code all that much.

store: adding StateChanges to cold columns

---

core/store/src/cold_storage.rs
core/store/src/columns.rs
integration-tests/src/tests/client/cold_storage.rs

This should conclude population of is_cold columns list.
Test doesn't check DBCol::StateChangesForSplitStates and DBCol::StateHeaders, but it shouldn't matter, as keys for them are basic.

store: adding final cold columns

---

docs/practices/fast_builds.md

This all started with me noticing a typo ("to slow”), but then I realized there are other places that could be reworded to flow smoother as well.

docs: proof-read fast-builds nearcore book page

---

runtime/near-vm-logic/src/logic.rs
runtime/near-vm-logic/src/tests/ed25519_verify.rs

* Align doc comment with other host functions (not that we are super-consistent here)
* Align code style with other host functions
* Reduce some duplication from tests
* Add tricky test-cases where a value of the wrong length is read from the register.
https://github.com/near/nearcore/issues/7567

refactor: cleanup ed25519_verify

---

runtime/near-test-contracts/estimator-contract/src/lib.rs
runtime/runtime-params-estimator/src/cost.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/lib.rs

The old estimation just divided the base estimation by the number of
bytes to receive the cost per byte. Now the base is subtracted first and
the remainder is divided by the number of bytes.
Exact estimations will be done and added later. But icount estimations
show that the per byte cost can be reduced from the placeholder value
423 Mgas to 12 Mgas (safety multiplier of 3 included).
The base value is still a bit tricky to say. `icount` estimation gives
me 90 Ggas, so with a safety multiplier it would be 270 Ggas.
The current placeholder of 40 Ggas is quite a bit lower but it was
roughly what we expected based on
[external benchmarks](https://github.com/dalek-cryptography/ed25519-dalek#benchmarks).
It could be that qemu based estimation does not work well here because
AVX instructions are …

feat: estimate `ed25519` base and bytes separately

---

chain/chain/src/types.rs

This could be further simplified by removing unpacking, but better avoid that to make it clear that the order of things matters

refactor: simplify get_epoch_sync_data_hash

---

core/store/src/metadata.rs
nearcore/src/migrations.rs

When flat state is used, the database should be upgraded.
The migration code is not stable enough, yet to merge but
we already want to run the master code on migrated databases.

fix: use new database version for flat state

---

Cargo.lock
chain/network/Cargo.toml
chain/network/src/broadcast/mod.rs
chain/network/src/network_protocol/testonly.rs
chain/network/src/network_protocol/tests.rs
chain/network/src/peer/testonly.rs
chain/network/src/peer/tests/communication.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/testonly.rs
chain/network/src/peer_manager/tests/accounts_data.rs
chain/network/src/peer_manager/tests/routing.rs
chain/network/src/routing/routing_table_view.rs
chain/network/src/store/schema/tests.rs
chain/network/src/time.rs

Instead of triggering a fixing call when the unexpected edge arrives, the consistency between the graph and actual connection set will be checked periodically. This way it is straightforward to see that we will always eventually arrive at a consistent state.

moved fixing local edges to a background task.

---

Cargo.toml
runtime/near-test-contracts/Cargo.toml
runtime/near-test-contracts/contract-for-fuzzing-rs/Cargo.toml
runtime/near-test-contracts/estimator-contract/Cargo.toml
runtime/near-test-contracts/test-contract-rs/Cargo.toml
runtime/runtime-params-estimator/emu-cost/Dockerfile
rust-toolchain.toml

- GATs are finally here! I'd be surprised if we cannot make use of it.
- stabilized `std::backtrace::Backtrace`, we should see if we can remove
the `backtrace` dependency
- let else statements are now a thing

chore: upgrade rust-version to 1.65.0

---

runtime/near-vm-logic/src/utils.rs

This also makes us to rely less on VMLogicError: Eq

refactor: simplify `split_method_names` in vm Logic

---

core/store/src/trie/trie_storage.rs
core/store/src/trie/trie_tests.rs

To create flat storage, we will need to do many parallel unique reads from disk. We don't want to reuse `TrieCachingStorage` there because it uses shared trie cache, which is bad due to two reasons:
* it would affect chunk processing, which must remain on the same speed
* parallel threads may block each other, while having the same cache is useless for them. 
Instead, we implement simple `TrieDBStorage` for reading state data from DB directly.
It will be used in the following PR.
* `test_retrieve_db`

feat: trie storage for parallel reads

---

chain/network/src/routing/graph_with_cache.rs

The primary goal here was to get rid of `.lock()` on code paths where we
had `&mut` already. But I've noticed that we can simplify
synchronization here in general? We don't need a mutex, once cell is
enough.
In the old code, if two threads race to compute the table, they'll both
burn CPU to do that. With this patch, only one thread will be doing
computation, while the others would sleep.
In other words, if we get a thundering herd on `cached_next_hop`, only
one thread will do the work.

refactor: simplify synchronization for next hops table

---

Cargo.lock
Cargo.toml
core/o11y/Cargo.toml
core/o11y/src/lib.rs

the standard library now supports capturing backtraces

chore: remove backtrace dependency

---

runtime/runtime-params-estimator/src/utils.rs

print per block measurements, to debug high-variance results
example output:
```
|warmup| 21.77ms 17.63ms 12.18ms
|proper| 12.34ms 12.37ms 11.85ms
Ed25519VerifyBase    82_714_387_104 gas [  82.714µs]
|warmup| 26.50ms 16.66ms 16.50ms
|proper| 23.20ms 16.65ms 16.88ms
Ed25519VerifyByte    3_206_171 gas [ 3ns] UNCERTAIN [...]
```

debug: observe single measurements in estimator

---

core/primitives/res/runtime_configs/parameters.txt
runtime/near-test-contracts/estimator-contract/src/lib.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/utils.rs

On gcloud (Xeon Cascade Lake CPUs) the variance was
too high, so to reduce it:
- changed default block size for `fn_cost_count`
- increased inner iterations for ed25519 base estimation
Still, I found gcloud results to have high variance on some days.
It could be due to noisy neighbors, such as sharing interger 
multiplication units with a foreign hyper thread.
In the following, the estimation results are taken from a day where
results were stable. Outliers on other days were up to 2 times slower
but when outliers are removed, the same speed is achieved as
reported below.
```python
Ed25519VerifyBase    68_093_951_344 gas [68.094µs]
Ed25519VerifyByte    3_198_227 gas [3ns]
Ed25519VerifyBase    88_704_920_930 gas [709639.37i 0.00r 0.00w]
Ed25519VerifyByte    4_285_422 gas [34.28i 0.00r …
```

feat: set ed25519 verification gas parameters

---

chain/network/src/peer/testonly.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/peer_manager_actor.rs

PeerManagerActor has access to config via NetworkState so there’s no
reason for the NetworkState::config field.
Once that field is removed, the config doesn’t need to be cloned any
longer which means that it doesn’t need to be wrapped in an Arc when
saved in NetworkState.

network: remove PeerManagerActor::config field

---

chain/network/src/raw/connection.rs

it's not so helpful to see:
```
2022-11-10T19:23:28.325928Z  INFO neard: version="trunk" build="1.1.0-3079-g4692d28bd" latest_protocol=57
2022-11-10T19:23:28.326020Z  WARN ping: the ping command is not stable, and may be removed or changed arbitrarily at any time
Error: Error connecting to 127.0.0.1:24567: IO
```
much better is:
```
2022-11-10T19:21:46.750676Z  INFO neard: version="trunk" build="1.1.0-3079-g4692d28bd-modified" latest_protocol=57
2022-11-10T19:21:46.750781Z  WARN ping: the ping command is not stable, and may be removed or changed arbitrarily at any time
Error: Error connecting to 127.0.0.1:24567: Connection refused (os error 111)
```
and the underlying source() if any is still preserved anyway

nit(network): make ConnectError::IO transparent

---

chain/jsonrpc/res/chain_n_chunk_info.html
chain/jsonrpc/res/debug.html
chain/jsonrpc/res/epoch_info.html
chain/jsonrpc/res/last_blocks.js
chain/jsonrpc/res/network_info.html
chain/jsonrpc/res/sync.html
chain/jsonrpc/res/validator.html

This PR updates the request to debug pages and debug links to work in a reverse proxy setup.
Say, we have a reverse proxy that exposes a debug page at the following URL: `http://myproxy/node1/debug`.
Today that would not be possible, because the node would make requests to `http://myproxy/debug/api/status` which doesn't exist.
With this PR, the node would make a request to `http://myproxy/node1/debug/api/status` which can be reverse-proxied to the node correctly.
Demo: http://35.204.154.4:3131/level/debug

Use relative paths in debug pages

---

chain/chain/src/store.rs
core/store/src/flat_state.rs

Here we cover testing FlatStorageState on more mock chains:
* Chain with forks - we test that if we move flat head to incorrect block, then FS returns proper error. Blocks on top of which flat storage is stored should move only forward.
* Chain with skipped heights - we test that FS handles them normally. The previous mock impl had an error, and real chain impl deserves integration test for that as well.
* New `flat_state` tests.

feat: add more scenarios to FlatStorageState unit tests

---

docs/practices/style.md

Removes the redundant "use" word in the phrase.

doc: fix wording in styleguide

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/tests/routing.rs

Reimplemented the flaky test, to account for how poor the RoutingTable logic is.
I've managed to reproduce the flakiness locally to make sure that this PR actually fixes the problem.

fix: reimplemented flaky test

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/tests/nonce.rs

Removed a flake of fix_local_edges test that I managed to reproduce locally.
The event ConnectionClosed was being emitted too early: it should be sent only once the asynchronous call to unregister completes.

deflaked fix_local_edges test

---

chain/chain/src/block_processing_utils.rs
chain/chain/src/chain.rs
chain/chain/src/tests/challenges.rs
chain/chunks/src/client.rs
chain/chunks/src/lib.rs
chain/chunks/src/test_utils.rs
chain/client-primitives/src/debug.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/debug.rs
chain/client/src/metrics.rs
chain/client/src/test_utils.rs
chain/jsonrpc/res/validator.html
integration-tests/src/tests/client/features.rs
integration-tests/src/tests/client/features/adversarial_behaviors.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/shards_manager.rs

Previously this would lead to skips as validators filter out the invalid chunks. Now, any invalid chunk producer is immediately banned after the first invalid chunk, so the consensus performance is almost not affected at all.

Improve consensus performance when there are invalid chunks.

---

chain/chain-primitives/src/error.rs
chain/chain/src/chain.rs
chain/chain/src/metrics.rs
chain/client/src/client_actor.rs
chain/client/src/metrics.rs

Unfortunately, it is very hard to add test for this because the syncing logic is in ClientActor. I already tested this in localnet and Robin tested it on mocknet and we verified that it behaves as expected.
My plan is to merge this PR as it is, but I'll have a follow up PR where I refactor the ClientActor code to move the logic into client and also add tests.

do not enter sync mode if peer is at an invalid hash

---

docs/practices/security_vulnerabilities.md

Previously the padding was weird, because the first line wasn’t wrapped up in `<p>`s like it should have been.
Also add a link to the mail address.

docs: Paragraphize the aside callout

---

CHANGELOG.md
chain/chain/src/chain.rs
chain/chain/src/flat_storage_creator.rs
chain/chain/src/store.rs
chain/chain/src/store_validator.rs
chain/chain/src/test_utils.rs
chain/chain/src/tests/gc.rs
chain/chain/src/types.rs
chain/client/src/client.rs
chain/client/src/info.rs
chain/client/src/test_utils.rs
core/chain-configs/src/client_config.rs
core/store/src/config.rs
integration-tests/src/genesis_helpers.rs
nearcore/src/config.rs
tools/speedy_sync/src/main.rs

Make number of threads for background flat storage creation configurable. In the node config we set it to 8, but we also allow node owners to modify it if they observe that BP slows down or creation is too slow until FS becomes a requirement. In the tests we limit number of threads to 1.
I think introducing some general structure as `ChainConfig` makes sense here, as we already use a configuration option `save_trie_changes`.
I'm open to other opinions how to organize this. In general `NearConfig` structure looks a bit suspicious to me, because it includes `config` taken from `config.json` and many other configs which are just derived from `config`.
Checking that parameter is taken correctly by the node.

feat: configure num threads for flat storage creation

---

Cargo.lock
Cargo.toml
core/crypto/Cargo.toml
core/crypto/src/util.rs
core/store/Cargo.toml
core/store/src/db/refcount.rs
runtime/near-vm-logic/Cargo.toml
runtime/near-vm-logic/src/alt_bn128.rs
runtime/near-vm-logic/src/array_utils.rs
utils/stdx/Cargo.toml
utils/stdx/LICENSE-APACHE
utils/stdx/LICENSE-MIT
utils/stdx/src/lib.rs

This consolidates all the places where array splitting happens into
a single module.  In the future, once split_array_ref feature gets
stabilised, we’ll be able to get rid of those polyfills but for now
it’s nice to have them all in one place.
The new `stdx` crate also provides a place where other common utility
features can be put so that the same function doesn’t need to be
implemented in multiple crates or put in a crate it doesn’t fit in and
made public just because some other crate depends on it.
Crucially, the crate must not depend on any crates from the workspace.

Introduce ‘stdx’ crate with split array polyfills

---

docs/SUMMARY.md
docs/architecture/gas/estimator.md
docs/practices/workflows/gas_estimations.md

Since we now have a workflow chapter, the section on how to run the
estimator belong there.
Also added a pointer to #8031 as an example for gas parameter analysis.

doc: move estimator guide to workflows

---

chain/network/src/concurrency/demux.rs
chain/network/src/concurrency/mod.rs
chain/network/src/concurrency/rate.rs
chain/network/src/concurrency/tests.rs
chain/network/src/config.rs
chain/network/src/peer_manager/tests/accounts_data.rs

In a sense a demultiplexer is a specific implementation of the rate limiter, so I've moved the rate limit specification itself to a separate module, so that demux module doesn't appear in places like config module. I'm also planning on adding additional primitives for rate limiting in the near future.

moved rate limit to a separate module

---

tools/mirror/src/cli.rs

otherwise logs from other threads (the ones started by the near node) will not show up

fix(mirror): initialize global logging

---

chain/network/src/network_protocol/network.proto
chain/network/src/network_protocol/proto_conv/peer_message.rs

It has been originally removed in favor of SyncRoutingTable, however removing it for both sending and receiving was backward incompatible: if a new binary sends RequestUpdateNonce, it expects SyncRoutingTable, however the old binary will respond with ResponseUpdateNonce which used to be unparseable by the new binary.

revived UpdateNonceResponse message.

---

core/account-id/src/lib.rs

Fixes the following clippy error:
```
error: the since field must contain a semver-compliant version
--> core/account-id/src/lib.rs:302:18
|
302 |     #[deprecated(since = "#4440", note = "AccountId construction without validation is illegal")]
|                  ^^^^^^^^^^^^^^^
|
= note: `#[deny(clippy::deprecated_semver)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#deprecated_semver
```

refactor: fix clippy deprecated since warning

---

nearcore/src/config.rs
neard/src/cli.rs

When creating configs for multiple nodes with the `neard localnet` we should set the local_ports argument to true so that each node has different ports. Otherwise they will conflict and crash immediately.

[fix] Fix localnet config - local ports should be set to true

---

CONTRIBUTING.md

The "this document" link in the pull requests section of the https://github.com/near/nearcore/blob/master/CONTRIBUTING.md page doesn't work. I picked a reasonable replacement, please let me know if this is the right one.

[doc] Fix a link to the testing page in the CONTRIBUTING.md

---

chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/tests/routing.rs
chain/network/src/peer_manager/tests/tier1.rs
chain/network/src/stats/metrics.rs

Deprecating AnnounceAccount in favor of AccountData, when finding routing target. AnnounceAccount will be still used as a fallback. In the next release, once we confirm that AnnounceAccount is not used any more, we will remove the fallback. We will stop broadcasting AnnounceAccount only once MIN_SUPPORTED_VERSION > 57.

deprecating AnnounceAccount

---

integration-tests/src/node/mod.rs
nearcore/src/config.rs
neard/src/cli.rs

Changing tracked_shards is tricky so adding a cmd line option to set it initially in the localnet command. 
Added a small unit test for the config generation.

[feat] Add --track-all-shards cmd line arg to the LocalnetCmd

---

.buildkite/pipeline.yml
.config/nextest.toml
docs/practices/testing/README.md

it will allow us to set panic=abort per test (because each test is executed in a separate subprocess) and set test timeouts without developing a custom test harness. Additionally I've set the default test timeout to 2min (period = 1min, killing test after 2 periods), which seems reasonable, given that all presubmit tests execute <1min as of today.

use nextest for better test isolation

---

docs/architecture/gas/parameter_definition.md

doc: Fix typo in parameter_definition.md

---

docs/architecture/gas/estimator.md

doc: Fix typo in parameter estimator docs

---

runtime/runtime/src/prefetch.rs

Prefetcher tests have become flaky in CI lately, failing with
`"unexpected number of prefetched values"`.
I was not able to reproduce it locally. But there is a timeout that
is at least one source for flakyness. This commit removes this
source by properly waiting on the background threads to finish
instead of relying on a timeout.
Hopefully resolves  #8252. (Will have to reopen if not.)

fix: flaky prefetcher tests

---

runtime/near-vm-logic/src/logic.rs
runtime/near-vm-logic/src/receipt_manager.rs
runtime/near-vm-logic/src/vmstate.rs

Calling get_vec_from_memory_or_register method mutably borrows the
entire VMLogic structure.  If the method was to return a borrow, it
would ‘lock’ the VMLogic structure making it impossible to use any of
its fields or methods.
Replace the method with a separate get_memory_or_register function
which takes gas counter, memory and registers as parameters.  This
allows the compiler to track borrows separately allowing the method to
return reference to register values rather than having to make a copy
of the data.
With this, most places where the data is copied into a vector (via use
of Cow::into_owned) are where the vector is needed.  Though note that
this only applies to registers at the moment.  Data from memory is
always copied into a vector.

runtime: move get_vec_from_memory_or_register into separate function

---

Cargo.lock
integration-tests/src/tests/runtime/state_viewer.rs
test-utils/testlib/Cargo.toml
test-utils/testlib/src/runtime_utils.rs

The function is used in only one place and really it’s more readable
to just use i32::to_le_bytes.

test-utils: remove kind of pointless encode_int function

---

runtime/near-vm-logic/src/logic.rs
runtime/near-vm-logic/src/receipt_manager.rs

Currently when public key is read it’s unnecessarily copied into
a temporary vector.  The copy is necessary because otherwise public
key data would hold a shared reference on self.registers which
prevents any methods which take exclusive reference to self to be
called.
However, if we decode the public key immediately after reading it, we
can deal with sized objects which can be stored on stack.  This is
perfect except because we cannot change when errors are reported we
have to postpone returning of the deserialisation errors.
Introduce PublicKeyBuffer which facilitates that.  It hides from the
users the fact that deserialisation happens immediately as soon as the
data is read providing an interface which looks as if deserialisation
was happening separately from reading.
An alternative …

runtime: introduce PublicKeyBuffer to avoid memory allocation

---

runtime/near-vm-logic/src/dependencies.rs
runtime/near-vm-logic/src/lib.rs
runtime/near-vm-logic/src/logic.rs
runtime/near-vm-logic/src/mocks/mock_memory.rs
runtime/near-vm-logic/src/vmstate.rs
runtime/near-vm-runner/src/memory.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmtime_runner.rs

Add a view_memory method to MemoryLike trait which returns a view of
the guest memory.  This allows caller to read data directly from guest
memory instead of using read_memory to first copy it into a vector.
To accommodate implementations which cannot support borrowing the
memory, the method returns a Cow which allows such implementations to
return a copy of the memory.  WasmerMemory doesn’t support it because
its memory is made of `Cell`s and transmuting `&[Cell<u8>]` to `&[u8]`
is maybe not sound.  Importantly though, Wasmer2Memory supports
returning the view.
Also introduce a simple MemSlice structure which combines guest memory
pointer and slice length in a single object.  This avoids confusing
when function accepts two u64 arguments and caller just needs to know
which is the pointer …

runtime: introduce MemoryLike::view_memory to avoid memcpy

---

core/store/src/trie/prefetching_trie_storage.rs
core/store/src/trie/trie_storage.rs

Introduce `TrieCache::lock` method to encapsulate `self.0.lock().expect(POISONED_LOCK_ERR)` which is currently used in quite a few places.

refactor: avoid code code duplication when locking TrieCache

---

core/store/src/metrics.rs
core/store/src/trie/prefetching_trie_storage.rs
core/store/src/trie/trie_storage.rs

This is the second part of https://github.com/near/nearcore/issues/7723: avoid an unnecessary storage lookup from the main thread in the scenario of forks.

feat: try reading shard_cache if prefetcher blocking_get returns None

---

pytest/lib/cluster.py
pytest/tests/sanity/repro_2916.py
scripts/nayduck.py

Fix https://github.com/near/nearcore/issues/8272. 
The recently added --tracked-shards command line argument for the localnet command changed the default of tracked-shards and it broke some of the tests. In this PR I'm setting the --tracked-shards to none which is what the tests expect. 
I was able to confirm that this fixed the repro_2916.py test using the following command:
python3 tests/sanity/repro_2916.py
I was not able to check all the tests using nayduck because they are broken for unrelated reasons. 
Also added some small styling and logging improvements.

[fix] Set tracked shards to none in pytest localnet command usage

---

genesis-tools/genesis-populate/src/lib.rs
runtime/runtime-params-estimator/src/action_costs.rs

Fixes a problem for daily estimations, introduced in #8251.
Because account IDs were not constant, the TX sizes
depended on the randomly picked indices, which caused
some failures in daily estimations where more accounts
were used than in local testing.

fix: Deterministic tx size in estimation

---

integration-tests/src/tests/runtime/deployment.rs
integration-tests/src/tests/runtime/sanity_checks.rs
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status_nondeterministic.snap
integration-tests/src/tests/runtime/test_evil_contracts.rs
integration-tests/src/tests/standard_cases/mod.rs
integration-tests/src/user/runtime_user.rs

https://github.com/near/nearcore/pull/7928 changed `Chain::get_recursive_transaction_results()` to skip refund receipts, so the several checks for receipts outcome length in `standard_cases::rpc` are now wrong, because they expect to find the refunds. Fix it by changing all these asserts, and by changing
`RuntimeUser::get_recursive_transaction_results` to match `Chain::get_recursive_transaction_results`
failed tests (the ones that start with `standard_cases::rpc::`): https://nayduck.near.org/#/run/2802
to be safe, can check that these are indeed refunds by printing rceipts out like:
```
for r in transaction_result.receipts_outcome.iter() {
let b = node_user.get_block(r.block_hash).unwrap();
let mut found = false;
'outer: for c in b.chunks {
let ch = …
```

fix(integration-tests): fix tests after tx status RPC changes

---

Cargo.toml
chain/chain/src/missing_chunks.rs
chain/chunks/src/lib.rs
chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
runtime/runtime-params-estimator/emu-cost/Dockerfile
rust-toolchain.toml

https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html
Updated the same files as in the previous version bump: https://github.com/near/nearcore/pull/7993
This enables https://github.com/near/nearcore/issues/7650 (see [this comment](https://github.com/near/nearcore/issues/7650#issuecomment-1337180030)).
Also includes fixes for the following warning:
```
warning: for loop over an `Option`. This is more readably written as an `if let` statement
...
= note: `#[warn(for_loops_over_fallibles)]` on by default
```

chore: upgrade rust-version to 1.66.0

---

core/o11y/benches/metrics.rs
core/o11y/src/lib.rs
core/o11y/src/pretty.rs

Fix the issues reported by `cargo clippy -p near-o11y` as part of #8145

refactor: fix clippy issues for near-o11y

---

pytest/tests/sanity/switch_node_key.py

status1 isn't defined, so use the validator RPC response to print out the info

fix(pytest): fix assert in switch_node_key.py

---

runtime/runtime-params-estimator/src/lib.rs

In the estimation for CreateAccountAction, we appended a long hash to a
random account to generate a new and unique account ID. This could
trigger ParseAccountError { kind: TooLong, char: None }'.
New approach: Append a constant suffix to a random unused account.
This also guarantees the sender account is only used once.
This reduces randomness on whether the sender account is already
cached due to previous iterations, which was another source of
measurement noise.

fix: estimator generates too long account names

---

nearcore/src/config.rs

This constant is:
- wrong: it should be yocto near (10^-24) and not atto (10^-18)
- outdated: we haven't used atto near since 2019 (#1827)
- unused: there are no code references to it
Better we get rid of it.

chore: remove outdated constant ATTO_NEAR

---

Cargo.lock
Cargo.toml

replaces #8304
dependabot made us aware of bugfixes and wanted to update to 1.20.3
Instead I propose we update only the patch version and keep major/minor.
1.18.x is a LTS version and it is what we are currently using.
1.18.4 contains the same fixes the bot wants.
Updating further should be done as a conscious decision.
`version = "~1.18"` means we want a fixed 1.18 minor version with
the newest patch version.
The old `"1.16.1"` is equivalent to `^1.16.1"` but in the lock file it
was fixed to `"1.18.2"`. Since we check in the lock file and only update
versions occasionally and consciously, I suggest we use `~` which is
less confusing.

chore: tokio patch version update to 1.18.4

---

chain/client/src/debug.rs

Genesis block is not stored in the normal way, so we condition on the default hash to query genesis block from the chain.

[Debug UI] Last blocks: Fix rendering of genesis block

---

runtime/near-vm-runner/src/tests.rs

Running `cargo test` in the nearcore directory fails with build error as shown below. This PR fixes this issue by making the relevant code only compiled under the right conditions e.i. when the wasmer-runtime feature is enabled. 
Tested with:
- `cargo build`
- `cargo test --no-run` 
- TODO 
- How to test it with the wasmer feature enabled? 
- I tried `cargo build --features force_wasmer` but it fails with:
```
error: Wasmer only supports x86_64, but a force_wasmer* feature was passed to near-vm-runner
--> runtime/near-vm-runner/src/vm_kind.rs:28:9
```
The original error is:
```
~/near/nearcore % cargo test --no-run
error[E0433]: failed to resolve: use of undeclared crate or module `wasmer_types`
--> runtime/near-vm-runner/src/tests.rs:74:23
|
74 |     const PAGE: u64 = …
```

fix: fix wasmer build error

---

.cargo/config.toml

With #8284 we upgraded cargo version to `1.66`, so https://github.com/rust-lang/cargo/pull/11114 is available. This PR is the same as #7130, but we can safely merge it now.
See #7650 for more context.
In order to test it I've used the code from [`librocksdb-sys/build.rs`](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/librocksdb-sys/build.rs#L111) as part of `neard/build.rs`:
```
fn main() {
-    if let Err(err) = try_main() {
-        eprintln!("{}", err);
-        std::process::exit(1);
+    let target_feature = std::env::var("CARGO_CFG_TARGET_FEATURE").unwrap();
+    let target_features: Vec<_> = target_feature.split(',').collect();
+    if target_features.contains(&"neon") {
+        panic!("FAIL: {target_feature}");
+    } else {
+        panic!("OK: {target_feature}");
}
} …
```

fix: only add '-Ctarget-feature=+sse4.1,+sse4.2' flags for x86_64

---

Cargo.lock

This PR updates multiple paperclip crates:
- paperclip: 0.7.0 -> 0.7.1
- paperclip-actix: 0.5.0 -> 0.5.1
- paperclip-core: 0.5.1 -> 0.5.2
- paperclip-macros: 0.6.0 -> 0.6.1
It is necessary to update serde_yaml to 0.9 for https://github.com/near/nearcore/pull/8310
Tested: passes local `cargo test` run

chore: update paperclip deps

---

chain/network/src/peer_manager/peer_store/mod.rs
core/store/src/lib.rs
core/store/src/trie/iterator.rs
core/store/src/trie/mod.rs
neard/src/cli.rs
tools/cold-store/src/cli.rs
tools/state-viewer/Cargo.toml
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs

- added store_temperature cmdline argument to neard view-state 
- added neard view-state view-trie2 command that is similary to view-trie but
- can only iterate from the state root node
- prints leaves only
- prints data in more human friendly way
- added max_depth to the trie iterator (needed for the view-trie2)
- refactored the retrieve_raw_node_or_value to return NodeOrValue instead of Result

feat: support hot/cold store in state viewer and add view-trie2 command 

---

.buildkite/pipeline.yml
chain/chain/src/store_validator/validate.rs
chain/chunks/src/lib.rs
chain/network/src/concurrency/rate.rs
core/store/src/trie/mod.rs
scripts/run_clippy.sh
tools/state-viewer/src/apply_chunk.rs

This enables clippy `clippy::correctness` checks as part of CI as discussed [here](https://github.com/near/nearcore/pull/8291#issuecomment-1372547523).
It is added as part of `sanity check` step for consistency, since that is where `cargo check` is executed.
This fixes the following issues in order to pass the added checks:
* noop `.clone()`
* this loop never actually loops 
* `0` is the minimum value for this type, the case where the two sides are not equal never occurs, consider using `self.burst == 0` instead
This PR is a part of #8145

feat: enable clippy::correctness as part of CI

---

integration-tests/src/test_helpers.rs
scripts/run_clippy.sh

Enable `clippy::suspicious` checks as part of CI.
Part of #8145.

feat: enable clippy suspicious as part of CI

---

chain/chain/src/tests/simple_chain.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
core/primitives/src/version.rs

It will allow to introduce backward incompatible changes to network protocol (TIER1-related) in the next release (at version 59). Also AFAIR we agreed to preemptively bump the version at each release.

bumped protocol version

---

chain/chain/src/store_validator/validate.rs

`block_refcount_final` was incorrectly refactored in #8299 to check for `sv.inner.genesis_blocks` and `sv.inner.block_refcount` being non-empty. It should check for more than 1 element instead.
This was caught by [the nayduck test](https://nayduck.near.org/#/test/410756):
```
2023-01-15T12:31:09.117757Z ERROR handle{handler="NetworkAdversarialMessage" actor="ClientActor" msg_type="NetworkAdversarialMessage"}: client: Storage Validation failed, [ErrorMessage { col: "BlockRefCount", key: "\"BLOCK_REFCOUNT\"", err: ValidationFailed { func_name: "f", error: "Found 1 Blocks that are not counted, e.g. (B7Sbqj2uD5M3yACTDgSDG9haw2L5vEdLsJiosuPZCDn1, 1)" } }]
```
See [zulip thread](https://near.zulipchat.com/#narrow/stream/295302-general/topic/failing.20nayduck.20tests) for more context.

fix: fix block_refcount_final validation

---

pytest/tests/adversarial/malicious_chain.py

after having one of the nodes produce invalid blocks, this test checks that the specific string "Banned(BadBlockHeader)" appears in the logs. The format of this log line has changed slightly, so this test fails now. Fix it by checking that the network_info RPC reports only one active peer, instead of grepping the logs

fix(pytest): don't rely on log line format in malicious_chain.py

---

core/primitives-core/src/parameter.rs
core/primitives/res/runtime_configs/parameters.yaml
core/primitives/res/runtime_configs/parameters_testnet.yaml
core/primitives/src/runtime/parameter_table.rs

This is a part of https://github.com/near/nearcore/issues/8264.
This PR introduces structured values for Rationals in the parameter config in the form
```yaml
burnt_gas_reward: {
numerator: 3,
denominator: 10,
}
```
To support this in the code, we now interpret parameter values as one of
```rust
enum ParameterValue {
Null,
U64(u64),
Rational { numerator: isize, denominator: isize },
String(String),
}
```
In the future the plan is to extend this to support Fee structure and Weighted parameters.
One open Rust-related question here:
Things to finish:

feature: Structured parameters config

---

Cargo.lock
Cargo.toml

To unblock `serde_yaml` update for https://github.com/near/nearcore/issues/8320
I wasn't sure what the policy was, so updated to the latest version of `insta` crate. Please, let me know if I should chose some other version instead.

chore: Bump insta from 1.14.0 to 1.26.0

---

Cargo.lock
Cargo.toml
core/primitives/src/runtime/parameter_table.rs

To unblock serde_yaml update for https://github.com/near/nearcore/issues/8320
I wasn't sure what the policy was, so updated to the latest version of `paperclip` crate. Please, let me know if I should chose some other version instead.
There is another very similar PR happening in parallel https://github.com/near/nearcore/pull/8390 that is also necessary for the `serde_yaml` update and is blocking this PR, so feel free to take a look at that one as well ^^

chore: Bump paperclip from 0.7.0 to 0.8.0

---

core/store/Cargo.toml
core/store/src/columns.rs
core/store/src/db.rs
core/store/src/lib.rs
core/store/src/metadata.rs
core/store/src/metrics.rs
core/store/src/opener.rs
core/store/src/test_utils.rs
integration-tests/Cargo.toml
integration-tests/src/tests/client/mod.rs
integration-tests/src/tests/client/process_blocks.rs
nearcore/Cargo.toml
nearcore/src/config.rs
nearcore/src/lib.rs
neard/Cargo.toml
neard/src/cli.rs
tools/cold-store/Cargo.toml
tools/cold-store/src/cli.rs
tools/cold-store/src/lib.rs
tools/state-viewer/Cargo.toml
tools/state-viewer/src/cli.rs

- removing the cold store rust feature because:
- it's really annoying to add new cold store code 
- the conditional code is ugly
- the cold store tests were not running in buildkite
- development is slow because of need to build and run tests twice, once with and once without cold_store
- changed how opener sets the db kind - it used to be that once cold store is configured the hot store kind would be set to hot. I changed it in line with the migration plan to preserve the hot store kind as archive until migration is over. Sorry for sneaking that change in here but it kind of happened. 
- small changes to the cold store cli
- some cleanup

refactor: removing cold store rust feature and conditional compilation

---

core/primitives-core/src/runtime/fees.rs
core/primitives/src/runtime/parameter_table.rs
core/primitives/src/views.rs
runtime/runtime/src/config.rs
runtime/runtime/tests/runtime_group_tools/random_config.rs

As `Rational` uses `isize` that is platform specific which might lead to different behavior on different machines.

refactor: Migrate to Rational32 in parameter config

---

integration-tests/src/tests/client/features/wasmer2.rs
integration-tests/src/tests/client/process_blocks.rs

I made two types of tests conditionally compiled to exclude them from running on macbooks - because they don't work on macs anyway. 
- test_two_deployments 
The test relies on the contract cache to be populated but the precompile method of the wasmtime runner doesn’t populate the cache
- test_wasmer2_upgrade 
The test checks transition from wasmer0 to wasmer2 but wasmer0 and wasmer2 are not available on macs

fix: disable integration tests that are broken on mac

---

chain/network/src/routing/graph/mod.rs

Another overflow - looks like a similar technique to prevent failures like this exists above in the same file, so here's another fix.

Fix another issue causing test failures in near-network.

---

chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/tests/routing.rs
chain/network/src/peer_manager/tests/tier1.rs
chain/network/src/stats/metrics.rs

This is a roll forward of near/nearcore#8182 ,
which was reverted by near/nearcore#8314 .
The issue that #8182 caused has been fixed in https://github.com/near/nearcore/pull/8407 .
nayduck run: https://nayduck.near.org/#/run/2834
before the fix tests/sanity/switch_node_key.py was failing, now it succeeds.
No nayduck tests are newly failing with this PR, compared to master.

Rollforward "deprecating AnnounceAccount (#8182)"

---

runtime/runtime-params-estimator/Cargo.toml

Currently `runtime-params-estimator` build with `nightly` feature enabled:
```
> cargo build --package runtime-params-estimator --features "nightly"
...
error[E0599]: no variant or associated item named `delegate` found for enum `ActionCosts` in the current scope
--> runtime/runtime-params-estimator/src/costs_to_runtime_config.rs:58:26
|
58 |             ActionCosts::delegate => fee(Cost::ActionDelegate)?,
|                          ^^^^^^^^ variant or associated item not found in `ActionCosts`
```
This PR fixes the issue.

fix: protocol_feature_nep366_delegate_action feature for runtime-params-estimator

---

docs/architecture/flat_storage.md

Add brief docs for flat storage structures.

docs: add flat storage struct docs

---

chain/chain/src/store.rs
chain/client/src/client.rs
core/chain-configs/src/client_config.rs
nearcore/src/config.rs

full context in https://pagodaplatform.atlassian.net/browse/ND-284 
Making the save_trie_changes a Option<bool> and if not set defaulting it to !archive. 
- for the time being there is no need to save trie changes
- in split storage migration we'll get the RPC backup with trie changes already in place - and then we will need to ensure that save_trie_changes is set to true or codify it
- saving trie changes without need is wasteful and will increase archival node storage needs so let's not do that
Tested the following scenarios:
- archive = true, save_trie_changes = false -> verified that trie changes are not saved - this is how archival nodes should operate and this is the same as the default save_trie_changes not set. 
- archive = true, save_trie_changes = true -> verified that trie …

fix: make save_trie_changes an option and default it correctly
