near/nearcore

chain/chain/src/chain.rs
integration-tests/src/tests/client/process_blocks.rs

refactor: make leftover Chain getters non-mut

---

pytest/tests/shardnet/scripts/restaked.sh

when the log messages don't contain timestamps, it's very hard to
tell what happened when.

nit(shardnet): print date in restaked.sh

---

Cargo.toml
chain/chain/src/test_utils.rs
integration-tests/src/tests/client/benchmarks.rs
integration-tests/src/tests/client/process_blocks.rs
nearcore/src/runtime/mod.rs

closes https://nearinc.atlassian.net/browse/CPR-134

feat: limit the total size of a chunk

---

integration-tests/Cargo.toml
integration-tests/src/tests/client/process_blocks.rs

Add an integration tests for `FixContractLoadingCost`.
They test that gas costs in normal execution are unaffected by the
upgrade, while the specific case of a prepration error does show the
expected change. That is, loading costs are charged with the upgrade.

test: Integration test for fixed loading cost

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/stats/metrics.rs
chain/network/src/test_utils.rs

The code was used in integration tests which has since been deleted.
Additionally narrowed down visibility of network metrics.

removed unused broadcast metric

---

core/primitives/src/version.rs

refactor: simplify PROTOCOL_VERSION declaration

---

core/store/src/trie/shard_tries.rs

Due to the use of default case in a match, DBop::Insert case doesn’t
have explicit match branch in ShardTries::update_cache.  To be
consistent with Set and Delete handling, the code should be panicking
if inserting to ColState.
Remove the default case and replace conditional cases with `if`s
inside of the branches so that each operation need to be handled
explicitly.

store: handle Insert operation in ShardTries::update_cache

---

chain/jsonrpc/res/last_blocks.html
chain/jsonrpc/res/network_info.html

- Added links to the network page
- Validators that are not reachable are marked as red.

Shardnet improvements to debug page

---

SECURITY.md

Noticed some obvious grammatical errors and grammatical structural faults, I have fixed them.
Cheers!

Fixed grammatical errors in `SECURITY.md`

---

chain/client/src/client_actor.rs
core/primitives/src/views.rs

Context: https://nearinc.atlassian.net/browse/SHRD-115

Expose node_key in the status response

---

chain/network/src/peer_manager/peer_manager_actor.rs

There are two reasons why we are doing this:
* The current setup with an associated function just doesn't make sense,
this feels very much like a method.
* In the near future we want to split `connected_peers` into `tier1` and
everyone else, it would help if sending a message didn't talk about
connected_peers directly.

refactor: simplify send message

---

chain/client-primitives/src/debug.rs
chain/client/src/debug.rs
chain/jsonrpc/res/epoch_info.html

Add more detailed validator information in debug page

---

runtime/runtime/src/balance_checker.rs

Refactor .iter().map().collect().iter().try_fold() chains present in
check_balance function into a single invocation of .try_fold() with
a closure which incorporates all the necessary steps.  This not only
arguably simplifies the code but also removes .collect calls which
create unnecessary vectors.

runtime: refactor try_fold to avoid unnecessary collect in check_balance

---

core/primitives/src/runtime/apply_state.rs
core/primitives/src/views.rs
integration-tests/src/tests/client/process_blocks.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/src/testbed.rs
runtime/runtime/src/lib.rs

The Arc<CompiledContractCache> are never cloned.  Simplify code by
just using a Box instead.

runtime: Arc<CompiledContractCache> → Box<_>

---

Cargo.lock
chain/client/Cargo.toml
chain/client/src/client_actor.rs
chain/client/src/info.rs
core/primitives/src/telemetry.rs

The new text field is ignored by the explorer.
Expose block production delays in the freeform field.
https://nearinc.atlassian.net/browse/SHRD-116

Extend TelemetryInfo with an additional freeform field

---

chain/network/src/accounts_data/tests.rs
chain/network/src/network_protocol/mod.rs
chain/network/src/network_protocol/testonly.rs
chain/network/src/network_protocol/tests.rs
core/primitives/src/validator_signer.rs

and adjusted the accounts_data::Cache accordingly.

added signing of AccountData to ValidatorSigner

---

chain/chain/src/test_utils/validator_schedule.rs
chain/client/src/test_utils.rs
chain/client/src/tests/bug_repros.rs
chain/client/src/tests/catching_up.rs
chain/client/src/tests/consensus.rs
chain/client/src/tests/cross_shard_tx.rs
chain/client/src/tests/query_client.rs
integration-tests/src/tests/client/chunks_management.rs
integration-tests/src/tests/client/process_blocks.rs

This'll allow configuring chunk-only producers for tests using this infra
follow up to #7256

test: use ValidatorSchedule in setup_mock_all_validators

---

neard/build.rs

Because 1.x.y tags we’re using are not annotated, git describe ignores
them when describing a commit.  Add --tags flag to make it take a look
at such tags.  While at it, include --match=[0-9]* so that the command
excludes non-nearcore-release tags such as crates-0.14.0.

neard: use release tags when determining build string

---

integration-tests/src/node/process_node.rs

replace WaitOrTimeoutActor with wait_or_timeout function for the file `integration-tests/src/node/process_node.rs`
#6933

refactor: replace WaitOrTimeoutActor with wait_or_timeout function

---

integration-tests/src/tests/nearcore/run_nodes.rs
integration-tests/src/tests/nearcore/track_shards.rs

Replace WaitOrTimeoutActor with wait_or_timeout function in couple of files.

refactor: replace wait actor with function

---

chain/network/src/routing/actor.rs

to minimize the number of broadcasted edges

moved edge loading before filtering

---

chain/chain/src/blocks_delay_tracker.rs
chain/chain/src/chain.rs
chain/chain/src/tests/simple_chain.rs
chain/client/src/client.rs
chain/jsonrpc/res/chain_n_chunk_info.html
core/primitives/src/views.rs

Add more detailed chunk info in the chain and chunk debug page 

---

chain/network/src/network_protocol/testonly.rs
chain/network/src/peer_manager/testonly.rs
chain/network/src/peer_manager/tests.rs

Followup test for https://github.com/near/nearcore/pull/7349

test of edge broadcast after restart

---

chain/chain/Cargo.toml
chain/chain/src/test_utils.rs
chain/chain/src/test_utils/validator_schedule.rs
chain/chain/src/tests/simple_chain.rs
chain/chunks/Cargo.toml
chain/chunks/src/lib.rs
chain/chunks/src/test_utils.rs
chain/client/Cargo.toml
chain/epoch_manager/Cargo.toml
chain/epoch_manager/src/lib.rs
chain/epoch_manager/src/reward_calculator.rs
chain/epoch_manager/src/test_utils.rs
chain/epoch_manager/src/tests/mod.rs
chain/epoch_manager/src/validator_selection.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
chain/rosetta-rpc/Cargo.toml
core/chain-configs/Cargo.toml
core/chain-configs/src/genesis_config.rs
core/primitives/Cargo.toml
core/primitives/src/epoch_manager.rs
core/primitives/src/version.rs
core/primitives/src/views.rs
core/store/Cargo.toml
integration-tests/Cargo.toml
nearcore/Cargo.toml
nearcore/src/runtime/mod.rs
nearcore/src/shard_tracker.rs
neard/Cargo.toml
runtime/runtime/Cargo.toml
test-utils/testlib/Cargo.toml

Note that this PR doesn't enable max_kickout_ratio on shardnet. When we want to do that, we'll need to a hard fork on shardnet

StabIlize feature chunk_only_producers and max_kickout_stake

---

chain/rosetta-rpc/src/adapters/mod.rs
chain/rosetta-rpc/src/adapters/transactions.rs
chain/rosetta-rpc/src/lib.rs

This is refactoring.  No changes in behaviour of the code.

rosetta: avoid unnecessary clones by taking Genesis and Addr by ref

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/client/src/client.rs
chain/epoch_manager/src/lib.rs
nearcore/src/runtime/mod.rs

added a lot of comments about what and why

reimplemented get_tier1_accounts to avoid expensive calls

---

Cargo.lock
chain/indexer/Cargo.toml
core/store/Cargo.toml
core/store/src/db/rocksdb.rs
deny.toml
runtime/runtime-params-estimator/Cargo.toml

This reverts commit 7e7cac03c9c17fa0bf85a9fe02df7503b3e5d21d.
As we're about to cut the testnet release.

Revert "Update rocksdb to 0.19 (#7357)"

---

runtime/runtime-params-estimator/src/utils.rs

In #7175 the subtraction of block overhead was introduced wrong.
Instead of subtracting it once per block, it was subtracted once per
transaction within the block. This leads to subtraction underflows that
also showed up in the continuous estimation.

fix: subtract estimator block overhead per block

---

chain/client/src/metrics.rs
chain/client/src/view_client.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/stats/metrics.rs

Add metrics to track messages that view client receives and how much time it spends on processing these messages

Add metrics for view client

---

chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/testonly.rs
chain/network/src/test_utils.rs
integration-tests/src/tests/network/peer_handshake.rs
integration-tests/src/tests/network/runner.rs
integration-tests/src/tests/network/stress_network.rs
nearcore/src/lib.rs
tools/chainsync-loadtest/src/main.rs

clock can be replaced with a fake in tests.

made PeerManagerActor::new accept a clock

---

chain/network/src/config.rs
chain/network/src/config_json.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/stats/metrics.rs

Companion to https://github.com/near/nearcore/pull/7324. That didn't
fully worked, as not all nodes upgraded. So, let's prune tombstones from
the other end as well.
Kudos to pompon0 for the idea.

feat: early prunning of tombstones of sharnet

---

runtime/runtime-params-estimator/emu-cost/Dockerfile
runtime/runtime-params-estimator/src/main.rs

Update docker tag to force re-building any existing older docker images.

fix: estimator rust version

---

core/store/src/db/slice.rs

This consolidates three unsafe blocks into a single location.

store: extract DBSlice::Rocks into RocksSlice type

---

runtime/near-vm-runner/src/tests/fuzzers.rs

near-vm-runner: fix m1 build

---

runtime/near-vm-runner/src/tests/fuzzers.rs

Helps address part of https://github.com/near/nearcore/issues/7618

fix: Fix a compiler warning on mac

---

chain/chain/src/test_utils/validator_schedule.rs
integration-tests/src/tests/client/chunks_management.rs

Follow up to #7280 
closes https://nearinc.atlassian.net/browse/CPR-141

add cops to chunk management tests

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/epoch-manager/src/adapter.rs
nearcore/src/runtime/mod.rs

Part of https://github.com/near/nearcore/issues/6910, depends on https://github.com/near/nearcore/pull/7657
Must be reviewed per commit.

refactor: move shard layout API to EpochManagerAdapter

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/epoch-manager/src/adapter.rs
nearcore/src/runtime/mod.rs
tools/mock-node/src/setup.rs

Part of https://github.com/near/nearcore/issues/6910, depends on https://github.com/near/nearcore/pull/7660
Must be reviewed per commit.

move block->epoch APIs to EpochManagerHandle

---

book/src/README.md
book/src/SUMMARY.md
book/src/architecture/README.md
book/src/misc/README.md
book/src/practices/README.md

doc: book skeloton

---

chain/chain/Cargo.toml
core/account-id/Cargo.toml

Also see https://github.com/near/nearcore/pull/7669

chore: Update a couple of more crates to 1.64

---

pytest/tests/sanity/upgradable.py

See https://github.com/near/nearcore/pull/7607/files

Fix upgradable.py db migration flags too; like #7607

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/epoch-manager/src/adapter.rs
nearcore/src/runtime/mod.rs
tools/state-viewer/src/apply_chunk.rs

Part of https://github.com/near/nearcore/issues/6910

refactor: move shard_layout_from_prev_block to EMA

---

README.md
docs/src/README.md

Fix: typos

---

CHANGELOG.md

this was committed to the 1.29.0 branch but not on master

changelog: add 1.29.0 changes

---

core/o11y/src/lib.rs
pytest/lib/cluster.py

Thanks to @marcelo-gonzalez for providing the diff.

fix(o11y): Write all logs to stderr

---

core/crypto/src/signature.rs

Have a single place where binary buffers are formatted as base58,
namely a new helper Bs58 struct, and use it to reduce code
duplication.  It also avoids allocation as it can format the buffer
onto stack without creating a new string.  With some more cleanups,
remove bunch of other unnecessary vector and string allocations.

crypto: move base58 formatting into single struct reducing duplication

---

docs/practices/docs.md

Wasn’t as thorough as with the previous PR, and many of these changes are probably more on the subjective side.

docs: review docs/practices/docs.md

---

chain/network/src/peer/testonly.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/peer_manager_actor.rs

part of the larger effort to move all functionality from PeerManagerActor to NetworkState.

moved is_inbound_allowed to NetworkState

---

chain/network/src/accounts_data/mod.rs
chain/network/src/accounts_data/tests.rs
chain/network/src/concurrency/mod.rs
chain/network/src/concurrency/rayon.rs
chain/network/src/concurrency/tests.rs

It will be reused for edge signature verification.

moved rayon utils to concurrency module

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/chunks/src/lib.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/lib.rs
nearcore/src/runtime/mod.rs

cc https://github.com/near/nearcore/issues/6910

refactor: move parts API to the epoch manager

---

core/store/src/trie/mod.rs

This is a temporary change to always test that flat state has the same
result as normal state lookup. It should be removed for stabilization.

debug: add assertions to flat state get_ref

---

docs/architecture/gas/README.md

- explain why we need gas
- give a coherent overview instead of just a rough toc
- specific examples to make it easier to grasp

docs: more in-depth overview of gas parameters

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/epoch-manager/src/adapter.rs
nearcore/src/runtime/mod.rs

based on top of #7992
cc https://github.com/near/nearcore/issues/6910

refactor: move miscelaneous epoch APIs to epoch manager adapter

---

chain/network/src/network_protocol/borsh.rs
chain/network/src/network_protocol/borsh_conv.rs
chain/network/src/network_protocol/mod.rs
chain/network/src/network_protocol/network.proto
chain/network/src/network_protocol/proto_conv/peer_message.rs
chain/network/src/network_protocol/tests.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer/testonly.rs
chain/network/src/peer/tests/communication.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/private_actix.rs

SyncRoutingTable functionality is a superset of ResponseUpdateNonce functionality.

replaced ResponseUpdateNonce with SyncRoutingTable

---

docs/architecture/gas/estimator.md

A small additions to docs that explains the `--metric` argument and
helps understanding the results the estimator produces.

docs: estimator metrics

---

pytest/lib/mocknet.py
pytest/tests/mocknet/load_test_adversenet.py

This is for controlling the adversenet we use for testing adversarial behavior.

Adversenet operational scripts

---

docs/architecture/how/cross-shard.md

- hard wrap docs according to style gude
- one ` is enough for code
- bare urls require `<>`: `<http://example.com>`
- use `console` and `$` for shell commands
- use `**Note:**` style for "admonitions". Maybe one day we'll add <https://github.com/tommilligan/mdbook-admonish>

docs: formatting changes:

---

chain/chain/src/test_utils.rs
chain/chain/src/types.rs
chain/client/src/client_actor.rs
chain/epoch-manager/src/adapter.rs
nearcore/src/runtime/mod.rs

cc https://github.com/near/nearcore/issues/6910

refactor: move some leftover APIs to EpochManagerAdapter

---

docs/practices/rust.md

Rust for Rusteceans is probably the best read of the whole section, and nomicon, while interesting to understand how stuff works under the hood, isn't really that practically useful for us.

doc: better priority in the mastery section

---

docs/architecture/gas/parameter_definition.md

small and steady steps to replace all the TODO's I left in the docs :)

docs: runtime config store

---

Cargo.lock
core/dyn-configs/Cargo.toml
core/dyn-configs/src/lib.rs

Add metric for dynamic config change

---

runtime/near-vm-errors/src/lib.rs
runtime/near-vm-runner/src/wasmer2_runner.rs

log an error if wasmer compile fails after preparation

---

Cargo.lock
neard/Cargo.toml
neard/src/cli.rs
tools/cold-store/Cargo.toml
tools/cold-store/README.md
tools/cold-store/src/cli.rs
tools/cold-store/src/lib.rs

As outlined in #8039, we need a way to quickly test every new cold storage functionality on real data. 
This PR creates such a tool with two initial functions: 
- Open db and check for cold
- Open db and print heads of cold/hot storage
After this and some other PRs are merged I will add commands to check already implemented functionality: copying of one block and updating cold head. Then, new cold storage PRs will come with corresponding updates to this tool.

Cold storage testing tool

---

docs/SUMMARY.md
docs/practices/security_sensitive_issues.md
docs/practices/security_vulnerabilities.md

https://docs.google.com/document/d/14w1Sdk1wXBTJIuzEksl1U1X_tMtvjn3fwdaeP_mIdPE/edit is the internal document being exported here.

docs: document the process for tracking security sensitive issues

---

chain/chain/src/block_processing_utils.rs
chain/chain/src/chain.rs
chain/chain/src/tests/challenges.rs
chain/chunks/src/chunk_cache.rs
chain/chunks/src/lib.rs
chain/client-primitives/src/debug.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/debug.rs
chain/client/src/metrics.rs
chain/client/src/test_utils.rs
chain/jsonrpc/res/validator.html
integration-tests/src/tests/client/features.rs
integration-tests/src/tests/client/features/adversarial_behaviors.rs
integration-tests/src/tests/client/shards_manager.rs

Improve consensus performance when there are invalid chunks.

---

core/store/src/trie/mod.rs

In addition to testing whether RawTrieNode encode+decode round trip
works, hard-code the expected encoded representation to make sure that
refactoring or any other modifications to the code don’t change it.

store: test RawTrieNode encoding produces expected result

---

docs/architecture/README.md
docs/architecture/how/README.md
docs/architecture/how/cross-shard.md
docs/architecture/how/epoch.md
docs/architecture/how/gc.md
docs/architecture/how/serialization.md
docs/architecture/how/sync.md
docs/architecture/how/tx_receipts.md
docs/architecture/how/tx_routing.md

small changes to formatting - making names of components bold
minor corrections for using proper articles and plural versions of words
**P.S.**:  I'll be adding more changes as I am going through the docs which will hopefully help with the understandability and readability of the docs.

docs: formatting and sentence structure

---

core/primitives/res/runtime_configs/parameters_testnet.txt

I completely forgot to update it in #8031

fix: also update testnet ed25519 gas parameters

---

runtime/runtime-params-estimator/estimator-warehouse/src/estimate.rs
runtime/runtime-params-estimator/estimator-warehouse/src/import.rs
runtime/runtime-params-estimator/estimator-warehouse/src/main.rs
runtime/runtime-params-estimator/estimator-warehouse/src/zulip.rs
tools/rpctypegen/core/src/lib.rs
tools/themis/src/utils.rs
utils/near-cache/src/cell.rs

refactor: various changes to address clippy warnings

---

.buildkite/pipeline.yml

master HEAD happens to be not up to date with the origin for some reason.

fix for the protobuf check

---

Makefile
chain/chain/Cargo.toml
chain/client/Cargo.toml
chain/indexer/Cargo.toml
chain/network/Cargo.toml
chain/network/src/config_json.rs
core/primitives/Cargo.toml
core/primitives/src/epoch_manager.rs
core/primitives/src/shard_layout.rs
core/primitives/src/version.rs
nearcore/Cargo.toml
nearcore/src/config.rs
neard/Cargo.toml
tools/ping/src/cli.rs
tools/state-parts/src/cli.rs

Cleaning up shardnet as per https://github.com/near/nearcore/issues/7996. 
For now this is just a request for comments as there were some things that are unclear to me
- In version.rs there are a few other features that seem related to shardnet, should I also clean up any of those? See TODO in code. 
- I removed the whole pytest/tests/shardnet directory, is that correct?

[chore] cleanup after shardnet

---

CONTRIBUTING.md

This text will probably not be read very often but still documenting github UI in case it helps someone.

doc: add text about re-request reviews

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/tests/accounts_data.rs
chain/network/src/peer_manager/tests/routing.rs

I didn't manage to reproduce it locally, so this is a blind shot, but it won't hurt.

attempt to deflake test_dropping_duplicate_messages

---

chain/network/src/concurrency/demux.rs

Lack of in-flight limit caused a bug in implementation of network graph recomputation:
- recomputation demux rate limit was set to 1/s
- recomputation was taking >10s on mainnet (for unrelated reasons)
- recomputations cannot be executed in parallel (they acquire a single mutex)
- steady inflow of new edges was triggering a recomputation every 1s, while each recomputation took >10s (after acquiring the mutex), making the recomputations queue unboundedly
- the delay of adding an edge to the graph was growing indefinitely, eventually making the edges expire before even it was added to the graph

set the in-flight limit on the demuxed calls to 1 for now

---

runtime/near-vm-errors/src/lib.rs

Part of https://github.com/near/nearcore/issues/8145
<details>
<summary>Fixed issues</summary>
```
warning: you are deriving `PartialEq` and can implement `Eq`
--> runtime/near-vm-errors/src/lib.rs:292:17
|
292 | #[derive(Debug, PartialEq)]
|                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
|
= note: `#[warn(clippy::derive_partial_eq_without_eq)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
warning: this returns a `Result<_, ()>`
--> runtime/near-vm-errors/src/lib.rs:512:5
|
512 |     pub fn downcast<E: Any + Eq + Send + Sync + 'static>(self) -> Result<E, ()> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: …
```

refactor: fix clippy issues in near-vm-errors

---

CHANGELOG.md

@pompon0 Please check TIER1 major release version and referenced PRs.

Update changelog for 1.30 and 1.31

---

Cargo.toml
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs

refactor: Sort state-viewer commands and add missing documentation

---

chain/network/src/peer/peer_actor.rs

#1586 was closed as "won't do", see [this comment](https://github.com/near/nearcore/issues/1586#issuecomment-872849765) for more details.
This PR removes the left over code.
Part of #8145 since this code also produces clippy error:
```
error: this comparison involving the minimum or maximum element for this type contains a case that is always true or always false
```

refactor: remove noop code around abusive peer banning

---

chain/client/src/client_actor.rs

An attempt to make comments related to logic in `check_triggers` easier to understand. Feel free to suggest changes if I got something wrong here.

docs: comments for check_triggers

---

core/primitives/src/runtime/parameter_table.rs

This PR simplifies parameter parsing code by removing JSON usage and instead directly storing parameter values as YAML. Functionally, the code should behave the same for the users of `ParameterTable`.
This is a part of refactoring for https://github.com/near/nearcore/issues/8264.
I'm still pondering using a more specialized enum type to store parameter values, but not yet sure how the implementation will look like, so delaying this until I start implementing parameter weights in config.

refactor: Get rid of JSON in parameter_table

---

chain/chain/src/chain.rs
chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
integration-tests/src/tests/runtime/deployment.rs
integration-tests/src/tests/runtime/sanity_checks.rs
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status_nondeterministic.snap
integration-tests/src/tests/runtime/test_evil_contracts.rs
integration-tests/src/tests/standard_cases/mod.rs
integration-tests/src/user/runtime_user.rs

Reverts near/nearcore#7928 due to [breaking explorer](https://github.com/near/nearcore/issues/8321) and the [original issue](https://github.com/near/nearcore/issues/6834) has been deprioritized. 
Also reverts related: https://github.com/near/nearcore/pull/8289

Revert "Tx status query not waiting for refunds"

---

core/primitives/src/runtime/parameter_table.rs

This provides better encapsulation for the type `ParameterValue` at a cost of making error message a bit more general.
This is also a good step toward deduplicating `get_*` methods of `ParameterTable` and also storing `u128` directly in `ParameterValue`, though I still haven't figured out how to do this.

refactor: Add ParameterValue::as_u128

---

core/primitives/src/runtime/parameter_table.rs

As it was not used anywhere and this allows to simplify the function even further.

refactor: Remove `remove_prefix` from `yaml_map`

---

chain/chain/src/flat_storage_creator.rs
core/store/src/flat_state.rs
integration-tests/src/tests/client/flat_storage.rs

Added a possibility to iterate over flat storage.
Also finish migration even if no new blocks are showing up

[Flat storage] iteration support, finish migration even if no new blocks.

---

tools/mirror/src/lib.rs
tools/mirror/src/offline.rs
tools/mirror/src/online.rs

when --online-source is given, we start a full node for the source chain and get txs and receipts from a ViewClient. This is fine, but it actually results in incorrect DeployContract transactions, because the conversion from a SignedTransaction to a SignedTransactionView silently discards the contract code and replaces it with the code's hash. (This feels sort of sad, as it means the ViewClient is not quite complete?) So we can change the get_txs() function to return an `enum SourceTransaction`, to leave them untouched if we're running without --online-source. That way we can at least send DeployContract txs when --online-source is not given.

fix(mirror): don't convert SignedTransactions to SignedTransactionViews

---

core/primitives/src/block.rs

There is no functional change, just rearranging the code to make it more readable and adding a few comments.

refactor: Simplify gas price calculation logic

---

scripts/remote_diff/diff_remote_files.sh

Coupled with #8458 this PR gives tools to diff config.json
Flow:
- Use #8458 to display hash of the config file on all machines of interest
- Use this script to display actual diff between configs on two specific machines (that can be selected based on the previous step)

adding script to diff file on two google cloud machines

---

integration-tests/src/tests/client/features/zero_balance_account.rs

better to have it in code than a pure on-paper analysis

test the derived limit of 770 bytes is correct

---

nearcore/src/cold_storage.rs

Tail is u64, not Tip.
Missed that, until started running this code on non-archival db that actually has tail.

fix(cold-store): tail type

---

chain/network/src/peer_manager/connection/mod.rs

Due to actix shutting down arbiters in unpredictable order it panics sometimes.
With this change it will still disallow establishing a connection, but won't be treated as bug any more.

downgraded PermitDrop error from panic to regular error

---

docs/architecture/how/meta-tx.md

As meta transactions are on their way to testnet, we discover more and
more corner cases that are slightly unclear in the NEP itself. Adding
explanations here in the nearcore guide is a good first step to document
these technical details somewhere.

doc: describe corner cases of meta transactions

---

CHANGELOG.md

add allow comments in configs and config validation command to CHANGELOG.md

add allow comments and config validation to CHANGELOG.md

---

pytest/tools/prober/prober.py
pytest/tools/prober/prober_split.py
pytest/tools/prober/prober_util.py

Implemented a prober that queries a legacy archival node and a split archival node and compares the results. It run continuously for the specified duration to compare as many blocks as possible. 
I also refactored the code a tiny bit and changed some log levels to debug to make output more readable. 
Example output from running the command on two legacy testnet nodes:
```
./prober_split.py --duration 10000 --legacy-url http://34.85.207.41:3030 --split-url http://34.150.139.181:3030
[2023-03-09 12:22:03] INFO: Running Prober
[2023-03-09 12:22:03] INFO: The genesis height is 42376888. The head height is 119678883
[2023-03-09 12:22:03] INFO: Checking blocks at height 73099618
[2023-03-09 12:22:04] INFO: Checking chunks
[2023-03-09 12:22:05] INFO: Checking blocks at height 71891442 …
```

feat: implemented prober for comparing legacy and split archival nodes

---

pytest/lib/mocknet.py
pytest/tests/mocknet/helpers/genesis_updater.py
pytest/tests/mocknet/helpers/load_test_spoon_helper.py
pytest/tests/mocknet/helpers/load_test_utils.py
pytest/tests/mocknet/load_test_spoon.py

As discussed in https://github.com/near/nearcore/pull/8707#discussion_r1131251734 refactoring some code around neard_amend_genesis_path. I kept this function itself by now it can only return neard.upgrade or raise an exception.

chore: mocknet improvements

---

pytest/tools/prober/prober_split.py

Changed the prober split to pick a random legacy archival node instead of having it passed as a cmdline parameter. The reason is that cloudprober can only provide one target so we need an alternative way to choose the other one. In the new version:
- the split archival node url should be passed as cmdline argument
- the legacy archival node url will be picked at random by the prober script itself

feat: make prober_split pick a random reference legacy node

---

docs/architecture/storage/flat_storage.md

As we are on the finish line with the MVP and in the midst of OKR
planning, I think it's a good time to take a step back and write down
where we stand on a high level.

doc: flat state high-level overview

---

tools/themis/src/rules.rs

Unblocks https://github.com/near/nearcore/pull/8782, `cargo` doesn't require `dev-dependencies` to be published. There's no need for themis to have that requirement.

themis: skip dep publish requirement for dev-deps

---

nightly/fuzz.toml

Making two changes to fuzzer at once -- adding 1.32.1 and 1.33.0 releases.

Fuzz 1.33.0

---

core/dyn-configs/src/lib.rs
core/o11y/src/lib.rs

fix: Make the logging layer dynamically configure-able, as it used to be

---

docs/advanced_configuration/networking.md

Adds a sample config showing the snippets relevant to advanced networking configuration.

Update networking.md with sample config

---

tools/debug-ui/.dockerignore
tools/debug-ui/Dockerfile
tools/debug-ui/README.md
tools/debug-ui/nginx.conf
tools/debug-ui/src/LandingPage.scss
tools/debug-ui/src/LandingPage.tsx
tools/debug-ui/src/index.tsx

This is so we can easily deploy it to a server we bring up.
#8355

[Debug UI] Dockerize debug UI project for deployment.

---

chain/pool/src/lib.rs

This commit makes docstrings of `TransactionPool` more consistent and simplifies `remove_transaction` implementation.
This is a part of refactoring for https://github.com/near/nearcore/issues/8878.

Improve docstrings and code of `TransactionPool`

---

chain/chain/src/doomslug.rs
chain/chain/src/store.rs
chain/chain/src/store_validator.rs
chain/chain/src/validate.rs
chain/client/src/client_actor.rs
chain/client/src/sync/header.rs
chain/client/src/tests/catching_up.rs
chain/network/src/config.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/network_state/tier1.rs
runtime/near-vm/lib/compiler-singlepass/src/codegen_x64.rs
runtime/near-vm/lib/compiler-singlepass/src/machine.rs
runtime/runtime-params-estimator/src/action_costs.rs
scripts/run_clippy.sh
tools/ping/src/cli.rs

refactor: Fix clippy's len_zero errors

---

pytest/requirements.txt
runtime/runtime-params-estimator/src/main.rs

fixing CI for the 1.34 branch
there were some compilation errors with the rust upgrade after the cherry pick
also, a pure CI error, buildkite has OpenSSL issues

fix CI for the 1.34.0 branch

---

pytest/tests/sanity/gc_sync_after_sync.py

Forgot to enable state sync for the switched node.

Fix: swap nodes test case

---

chain/chain/src/store.rs
core/store/src/config.rs
core/store/src/lib.rs
core/store/src/trie/config.rs
core/store/src/trie/mod.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/trie_storage.rs

Partially addresses issue #7425

refactor: Extract `update_cache` in store

---

nearcore/src/runtime/mod.rs

As discussed in https://near.zulipchat.com/#narrow/stream/308695-pagoda.2Fprivate/topic/mainnet.20new.20RPC.20nodes.20errors.

fix: improve error message in get_gc_stop_height after the gc_num_epochs_to_keep is increased

---

chain/chain/src/chain.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/lib.rs
chain/epoch-manager/src/types.rs
genesis-tools/genesis-populate/src/lib.rs
nearcore/src/runtime/mod.rs
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs

@Longarithm and I found the `add_validator_proposals` function present in runtime which feels like it belongs better in the epoch_manager.
This PR is a quick refactor.

[refactor] Refactor function `add_validator_proposals` from runtime to epoch_manager

---

Cargo.lock
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/cache.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmer_runner.rs

remove near-cache dep from near-vm-runner

---

chain/chain/src/chain.rs
chain/client-primitives/src/types.rs
chain/client/src/client.rs
chain/client/src/sync/state.rs
core/o11y/src/lib.rs
nearcore/src/runtime/mod.rs

- refactored some code to smaller methods, renamed some variables, added comments
- extracted block.header() to a variable in preprocess_block to simplify
- made a spammy log line less spammy

refactor: refactoring and commenting some resharding code

---

integration-tests/src/tests/nearcore/sync_state_nodes.rs

Extracted a test from #9237 . No fix is available yet.

fix(state-sync): Test showing that state sync can't always generate state parts

---

chain/chain/src/chain.rs
chain/chain/src/lib.rs
chain/chain/src/resharding.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/sync/state.rs
chain/client/src/sync_jobs_actor.rs
chain/client/src/test_utils.rs
nearcore/src/runtime/mod.rs

PR to refactor all resharding related code into one file `resharding.rs`
All future resharding related code should hopefully live here.

[resharding] Refactor `build_state_for_split_shards` and related functions in one file

---

chain/epoch-manager/src/reward_calculator.rs

As the previous link was stale

[doc] Update link to rewards calculation

---

chain/jsonrpc/src/lib.rs

This endpoint was added mistakenly (by me) in #8181.
It returns a response completely identical to the one given by the `network_info` endpoint and adds no functionality.
Also, @telezhnaya pulled numbers from the last 6 months and `tier1_network_info` was used 0 times.

Delete tier1_network_info RPC endpoint

---

chain/client/src/test_utils.rs
chain/network/src/network_protocol/borsh.rs
chain/network/src/network_protocol/borsh_conv.rs
chain/network/src/network_protocol/mod.rs
chain/network/src/network_protocol/network.proto
chain/network/src/network_protocol/proto_conv/peer_message.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/raw/connection.rs
chain/network/src/raw/tests.rs
chain/network/src/types.rs
tools/state-parts/src/lib.rs

Convert the state sync messages to direct messages.

feat(state-sync) convert state sync messages to peer messages

---

chain/chain/src/resharding.rs
core/primitives/src/types.rs
core/store/src/flat/delta.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/split_state.rs
nearcore/src/runtime/mod.rs

For more context on the change, please look at https://github.com/near/nearcore/issues/9420 and https://github.com/near/nearcore/issues/9418

[resharding] Include state_changes in ApplySplitStateResult for split_state

---

chain/chain/src/chain.rs
core/store/src/flat/delta.rs
core/store/src/trie/split_state.rs

For more context on the change, please look at https://github.com/near/nearcore/issues/9422, https://github.com/near/nearcore/issues/9423 and https://github.com/near/nearcore/issues/9418
Although this PR is independent, it logically comes after PR https://github.com/near/nearcore/pull/9419

[resharding] Write flat state and update head during resharding and handling split_state

---

core/primitives/src/runtime/config_store.rs

When adding a parameter file it is fairly easy to forget to include it in the array of configs, which then leads to wasted time.

config_store: add a test to verify all config files are included

---

runtime/near-vm/compiler-singlepass/src/codegen_x64.rs
runtime/near-vm/compiler-singlepass/src/compiler.rs
runtime/near-vm/compiler/src/translator/environ.rs
runtime/near-vm/compiler/src/translator/module.rs
runtime/near-vm/compiler/src/translator/state.rs
runtime/near-vm/engine/src/universal/engine.rs
runtime/near-vm/engine/src/universal/link.rs
runtime/near-vm/test-api/src/sys/instance.rs
runtime/near-vm/test-api/src/sys/module.rs
runtime/near-vm/vm/src/instance/mod.rs
runtime/near-vm/vm/src/vmoffsets.rs

https://near.zulipchat.com/#narrow/stream/297873-pagoda.2Fnode/topic/release.201.2E36/near/384954807

fix(logging): Change near_vm log level to debug

---

chain/chain/src/chain.rs
chain/chain/src/store.rs
chain/client/src/client.rs

Refactoring some methods handling the incoming receipts. It's a warm up before handling that during resharding :).

refactor: refactoring code around incoming receipts handling

---

docs/architecture/how/gas.md

I thought it was 10x the base but checking in the code again I see it is 20x.

doc: fix gas price limits

---

chain/chunks/README.md

This basic PR will serve as a test for github merge queue validation

remove trailing spaces

---

CONTRIBUTING.md

found a minor typo while reviewing contributing.md

doc: fix typo in contributing.md

---

chain/jsonrpc/src/lib.rs

We have metrics about all our RPC methods. However, we can't distinguish between different query requests. Adding this.

split query metrics by request type

---

chain/chain/src/metrics.rs
chain/chain/src/resharding.rs

Added resharding metrics to
a) track the status of resharding
b) track much much data (in batches count and batchs size) was written for each shard

feat(resharding): added metrics

---

core/store/src/trie/mod.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/state_snapshot.rs

Pure refactor, better locality of functions for making changes/adding new functions related to snapshots.

[refactor] Move ShardTries snapshot related code to a separate file

---

core/store/src/test_utils.rs
integration-tests/src/tests/client/resharding.rs
tools/mock-node/src/setup.rs

I'm not sure who and why hates the letters i..z but I kind of need them for testing resharding.

feat: resharding - use full alphabet in tests

---

Cargo.toml
chain/chain/src/store_validator/validate.rs
chain/chain/src/test_utils.rs
chain/chunks/src/lib.rs
chain/client/src/client.rs
chain/client/src/sync/state.rs
chain/epoch-manager/src/tests/mod.rs
chain/epoch-manager/src/tests/random_epochs.rs
chain/network/src/network_protocol/testonly.rs
core/primitives/src/sharding.rs
core/store/src/trie/nibble_slice.rs
integration-tests/src/tests/client/features/increase_storage_compute_cost.rs
integration-tests/src/tests/client/features/zero_balance_account.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/resharding.rs
integration-tests/src/tests/network/runner.rs
runtime/near-vm-runner/src/imports.rs
runtime/near-vm-runner/src/instrument/stack_height/mod.rs
runtime/near-vm-runner/src/instrument/stack_height/thunk.rs
runtime/near-vm-runner/src/logic/tests/alt_bn128.rs
runtime/near-vm-runner/src/logic/tests/gas_counter.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime-params-estimator/emu-cost/Dockerfile
runtime/runtime/src/actions.rs
rust-toolchain.toml
tools/state-viewer/src/apply_chunk.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/epoch_info.rs

https://blog.rust-lang.org/2023/10/05/Rust-1.73.0.html
Best reviewed commit-by-commit.

rust: upgrade to 1.73.0

---

Cargo.lock
chain/jsonrpc/src/api/transactions.rs

I mixed up adding tests and introducing new functionality here https://github.com/near/nearcore/pull/9648
Please have a look just at tests separately

jsonrpc: add tx serialisation tests

---

pytest/tests/mocknet/helpers/neard_runner.py
pytest/tests/mocknet/mirror.py

- Set use_production_config to true - this config needs to be set to true in order to trigger resharding. 
- The alternative would be to hardcode it here for mocknet as well: https://github.com/near/nearcore/blob/7b2a504ebf75d1b86f52470b62fb669b6d9153d1/core/chain-configs/src/genesis_config.rs#L185-L189 . I like that and I think it should be done this way for pre-release mocknet tests but I don't know if there are any other use cases for mocknet where it would be undesired. 
- I'm currently forcing it to true but I'll be happy to make it configurable if there is need for that. 
- Allow updating config with 'state_snapshot_enabled'. It's only needed for resharding until we ensure snapshots are always taken before resharding. In the meantime I still need it. 
- Added --yes to bypass …

[feat] mirror - improvements to enable testing of resharding

---

chain/chain/src/chain.rs
chain/chain/src/metrics.rs
chain/chain/src/resharding.rs

- added some new metrics that are useful for resharding - shard layout version, shard layout num shards
- adjusted the existing resharding metrics to always report for the children shard uids
- added a few debug logs

[feat] resharding improvements

---

chain/client/src/test_utils/test_env_builder.rs
nearcore/src/test_utils.rs

Minor cleanup, followup from PR https://github.com/near/nearcore/pull/9664

[cleanup] Minor changes to test_env_builder

---

chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/sync/adapter.rs
chain/client/src/sync/sync_actor.rs
chain/client/src/test_utils/setup.rs
chain/client/src/test_utils/test_env_builder.rs
chain/network/src/state_sync.rs
integration-tests/src/tests/network/runner.rs
nearcore/src/lib.rs

Start one actor per shard. 
Send start message from client.

feat(state-sync): Pass sync adapter to client

---

.github/workflows/master_fuzzer_binaries.yml

Should fix [the current build issue](https://github.com/near/nearcore/actions/runs/6733170192/job/18301287582)

disable swap for fuzzer builds, now we have a bigger runner

---

core/store/src/trie/mem/updating.rs

[Flaky test] Fix test_trie_consistency_random.

---

chain/epoch-manager/src/adapter.rs

Not sure why we had the map_err

[cleanup] Remove unnecessary map_err in epoch_manager

---

docs/practices/protocol_upgrade.md

As per https://near.zulipchat.com/#narrow/stream/295302-general/topic/gating.20new.20features

docs: update feature gating documentation

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/near_crates_publish.yml
.github/workflows/near_workspaces_publish.yml
.github/workflows/nearcore_deploy.yml
.github/workflows/ondemand_fuzzer_binaries.yml
scripts/binary_release.sh

First try to implement the release pipeline in GHA.

Binary release to GHA

---

.github/workflows/near_crates_publish.yml
.github/workflows/nearcore_deploy.yml
scripts/binary_release.sh

adjusted near release and crate publishing workflows:
https://github.com/near/nearcore/actions/runs/6829530241/job/18575861116
https://github.com/near/nearcore/actions/runs/6829340549/job/18575289879

Adjustments to release GHA workflows

---

.github/workflows/near_crates_publish.yml
.github/workflows/neard_linux_binary.yml
scripts/binary_release.sh

Small fixed to branch naming
Trigger near-workspaces updated only on Cargo.toml changes

Run neard Linux build on release

---

.github/workflows/neard_assertion_binary.yml
.github/workflows/neard_nightly_binary.yml

These should be the last missing pieces from buildkite

Add assertion and nightly binaries release workflows

---

core/primitives/src/trie_key.rs
tools/fork-network/src/cli.rs

For consistency with genesis.json.
cc: @vlad-kopcil

fix(fork-tool): Use dec_format to serialize u128

---

.github/workflows/ci.yml

Issue #9634 has been solved since.

remove overcommit settings from CI

---

core/store/src/config.rs

Until we see that it works on our testing infrastructure. cc @robin-near

fix: disable in-memory trie in master

---

chain/chain/src/chain.rs
chain/client/src/client.rs
core/primitives-core/src/version.rs
core/primitives/src/block.rs
core/primitives/src/block_header.rs
core/primitives/src/sharding.rs
core/primitives/src/sharding/shard_chunk_header_inner.rs
core/primitives/src/test_utils.rs
core/primitives/src/views.rs
integration-tests/src/tests/client/block_corruption.rs
integration-tests/src/tests/client/process_blocks.rs
test-utils/testlib/src/process_blocks.rs

This PR removes all the code which was introduced as part of the post-state-root effort.

refactor: clean up post-state-root code

---

core/primitives/src/shard_layout.rs

based on the analysis done in #10119
it's not yet set in stone but it's the most likely candidate so let's set it and test it

feat(resharding): set the shard boundary in the new shard layout

---

chain/chain/src/chain.rs
integration-tests/src/tests/client/resharding.rs

Reverting the GC code for resharding till we figure out what's wrong...
Context: https://near.zulipchat.com/#narrow/stream/295558-pagoda.2Fcore/topic/Master.20binary.20Can't.20clear.20old.20data/near/402240517

[resharding] Revert call to clear_resharding_data

---

.github/workflows/issue-metrics.yml

Add GH_TOKEN environment. Required by the action even though the repo is public
Report example: https://github.com/near/nearcore/issues/10208

GH metrics adjustments

---

chain/client/src/debug.rs

Previously the function created a vector of tuples just to deconstruct it right away.  This change hopefully makes it easier to digest the function.

refactor: improve readability of `get_tracked_shards_view()`

---

Makefile
scripts/binary_release.sh

as per discussion in https://near.zulipchat.com/#narrow/stream/308695-pagoda.2Fprivate/topic/store-validator.20binary.20to.20S3

Disable building store-validator and genesis-populate binaries in CI

---

chain/epoch-manager/src/shard_tracker.rs

See https://github.com/near/nearcore/pull/10230 and https://github.com/near/nearcore/pull/10242 for prior works.
CC: @wacban.

refactor: remove yet another instance of assuming contiguous shard ids

---

chain/chain/src/chain.rs
chain/chain/src/types.rs
chain/network/src/network_protocol/testonly.rs
core/primitives/benches/serialization.rs
core/primitives/src/block.rs
genesis-tools/genesis-populate/src/lib.rs

See https://github.com/near/nearcore/pull/10230 for prior work.  
CC: @wacban.

refactor: remove another instance of assuming contiguous shard ids

---

chain/chain/src/chain.rs

See https://github.com/near/nearcore/pull/10230; https://github.com/near/nearcore/pull/10242; etc. for prior works.
I am slowly trying to remove all uses of the `num_shards()` function and improving the code quality in process.  
Changes made in this PR:
- Use better names for variables to improve readability.
- Before `shard_receipts` was a vector but it is cleaner for it to be a hashmap instead.
- clarify that `account_id_to_shard_id_map` is just a simple cache.  And use more idiomatic rust around accessing it.
CC: @wacban

refactor: stop using `num_shards()` in `build_receipts_hashes()`

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/ondemand_fuzzer_binaries.yml

See eg. the likely-OOM at https://github.com/near/nearcore/actions/runs/6890897651/job/18744849948

build fuzzers on Big machines

---

chain/chain/src/chain.rs
chain/chain/src/resharding.rs
chain/chain/src/tests/simple_chain.rs
chain/chain/src/types.rs
chain/client/src/client.rs
chain/client/src/sync_jobs_actor.rs
chain/client/src/test_utils/setup.rs
core/chain-configs/src/client_config.rs
core/chain-configs/src/updateable_config.rs
nearcore/src/config.rs
nearcore/src/dyn_config.rs
tools/speedy_sync/src/main.rs

make the resharding config dynamic

feat(resharding): dynamic config

---

integration-tests/src/tests/client/resharding.rs
pytest/lib/resharding_lib.py

This should fix a bunch of the nayduck tests. 
https://nayduck.near.org/#/run/3318

fix(resharding): fix tests

---

chain/chain/src/chain.rs

get_state_response_part():
- remove the contiguous shard_ids assumption.  Instead of checking the shard id against the number of chunks, look up the list of shard ids instead.  
- since the epoch id is remains the same for the current and the prev block, the set of shard ids should also remain the same so we only need to do the check once.
- remove some unnecessary clones
- finally rename some variables to make them shorter.  Mainly remove the `sync_` prefix.  I am not sure how much value this prefix is adding and the shorter variables are still conveying the same amount of information.
compute_state_response_header():
- Similar to above, remove the contiguous shard_ids assumption.  
- Remove some unnecessary clones and dereferences
save_receipt_id_to_shard_id_for_block():
- there is a …

refactor: various cleanups and fixes in `chain.rs`

---

chain/chain/src/block_processing_utils.rs
chain/chain/src/chain.rs
chain/chain/src/lib.rs
chain/chain/src/orphan.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs

Trying to reduce the size of chain.rs file

[refactor] Refactor orphan block management related functions into a single file

---

.github/workflows/ci.yml
codecov.yml

Fixes #10245
Related to https://github.com/near/near-one-project-tracking/issues/12

configure codecov properly

---

chain/chain/src/blocks_delay_tracker.rs
chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/garbage_collection.rs
chain/chain/src/resharding.rs
chain/chain/src/store.rs
chain/chain/src/store_validator.rs
chain/chain/src/test_utils.rs
chain/chain/src/tests/garbage_collection.rs
chain/chain/src/tests/simple_chain.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/debug.rs
chain/client/src/sync/block.rs
chain/client/src/sync/header.rs
chain/client/src/test_utils/client.rs
chain/client/src/test_utils/setup.rs
chain/client/src/view_client.rs
integration-tests/src/tests/client/challenges.rs
integration-tests/src/tests/client/epoch_sync.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/resharding.rs
integration-tests/src/tests/client/state_dump.rs
integration-tests/src/tests/client/state_snapshot.rs
nearcore/src/state_sync.rs
tools/mock-node/src/lib.rs
tools/state-viewer/src/state_dump.rs
tools/state-viewer/src/state_parts.rs

Follow up from PR https://github.com/near/nearcore/pull/10388

[refactor] Rename store in `Chain` to chain_store

---

chain/client/src/adapter.rs
chain/client/src/chunk_validation.rs
chain/client/src/client_actor.rs
chain/client/src/test_utils/setup.rs
chain/client/src/test_utils/test_env.rs
chain/network/src/client.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/testonly/fake_client.rs
chain/network/src/types.rs
core/primitives/src/chunk_validation.rs
integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
integration-tests/src/tests/client/features/adversarial_behaviors.rs
tools/chainsync-loadtest/src/network.rs

This PR has the basic network stack stub for receiving and handling chunk endorsements.

[stateless_validation] Stub code for handling chunk endorsement

---

core/primitives/src/action/mod.rs

This replaces the exact size checks with increasingly tight bound checks in certain configurations that we know are using nightly versions. But otherwise the crate will still compile if somebody is using nightly…

primitives: make builds work on nightly out-of-box

---

chain/client/src/chunk_validation.rs

Was broken in #10482:
```
ERROR chunk_validation: shadow chunk validation failed err=NotAValidator shard_id=0 block_hash=3b5YES7sbmVCf3iK9...
```
We should be able to run shadow validation on non-validator node, so we skip signature generation for shadow chunk validation.

fix: shadow chunk validation signature error

---

chain/client/src/chunk_validation.rs

This is extremely useful in 90% of the test cases that have just one validator. This way we don't need to explicitly handle network messages related to `ChunkStateWitness` and `ChunkEndorsement`
Created an issue to fix this in the future: https://github.com/near/nearcore/issues/10508

[stateless_validation] Hack sending chunk endorsement to self for single validator tests

---

tools/state-parts-dump-check/src/cli.rs

With re-sharding feature being rolled out, the number of shards will change. Read the number of shards to monitor from the epoch info.

fix(state-sync): Track all shards in state dump monitoring tool

---

codecov.yml

Fixes the issue pointed out in https://github.com/near/nearcore/pull/10574#issuecomment-1932010128

do not count coverage for integration tests

---

integration-tests/src/tests/client/process_blocks.rs

This test didn't work with stateless validation.
It manually creates a chunk and blocks containing this chunk, but it didn't set the `chunk_endorsements` field in the blocks, because of which the blocks couldn't be accepted.
Let's fix it by generating the correct chunk endoresment and setting the field in the generated blocks.
Refs: https://github.com/near/nearcore/issues/10506

fix: make test_validate_chunk_extra work with stateless validation

---

runtime/runtime-params-estimator/README.md

Super irritating to see the Lychee lint test continuously failing

[fix] Fix Lychee lint test

---

Cargo.lock
chain/network/Cargo.toml
chain/network/src/peer_manager/testonly.rs
chain/network/src/peer_manager/tests/fuzzers.rs
chain/network/src/peer_manager/tests/mod.rs

Part of:
- https://github.com/near/near-one-project-tracking/issues/19

fuzz the handshake reception

---

pytest/lib/resharding_lib.py
pytest/tests/sanity/resharding.py
pytest/tests/sanity/resharding_restart.py

Small refactoring before I add more checks for the flat storage issues.

refactor(resharding): refactoring the resharding nayduck tests

---

Cargo.toml

https://near.zulipchat.com/#narrow/stream/300659-Rust-.F0.9F.A6.80/topic/Unable.20to.20compile.20.60core.2Fchain-configs.2Fsrc.2Fclient_config.2Ers.60/near/424938946

Fix compilation error due to missing time crate feature.

---

chain/chain/src/tests/simple_chain.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
core/primitives-core/src/version.rs

bump protocol version for 1.38.0

---

tools/chainsync-loadtest/README.md

[fix] Fix Lychee lint test (again)

---

Cargo.lock
tools/congestion-model/Cargo.toml
tools/congestion-model/src/main.rs

Added the --shards, --rounds, --workflow, and --strategy arguments. workflow and strategy support "all" as a valid value, are case insensitive and strip spaces.

feat(congestion): Added argument parsing to the congestion model

---

core/primitives-core/src/version.rs
integration-tests/src/tests/client/resharding.rs

it's not pretty but it should work
making sure that we don't accidently trigger resharding in statelessnet

feat(statelessnet): disable resharding V3 in StatelessNet

---

docs/practices/style.md

fixing one of the lychee failures
The other one is mysterious, it works for me but not for lychee. I do not have the strenght to look into it now. 
I'm going to mark this PR merge when ready, please remove it from the queue if you have any feedback.

fix(docs): Fix an "instrument" link in the docs

---

chain/chain/src/test_utils.rs
chain/chain/src/tests/simple_chain.rs
chain/client/src/sync/header.rs

Part of https://github.com/near/nearcore/issues/10678 and https://github.com/near/nearcore/issues/10634.

refactor: use NightshadeRuntime in chain test_utils

---

integration-tests/src/tests/network/runner.rs

Part of https://github.com/near/nearcore/issues/10678 and https://github.com/near/nearcore/issues/10634.

refactor: use NightshadeRuntime with network integration tests

---

chain/jsonrpc/client/src/lib.rs
docs/practices/testing/python_tests.md
integration-tests/src/tests/nearcore/rpc_nodes.rs
pytest/lib/cluster.py
pytest/tests/sanity/resharding_rpc_tx.py
pytest/tests/sanity/rpc_finality.py
pytest/tests/sanity/rpc_tx_submission.py

https://nayduck.near.org/#/run/3425
3 tests are fixed, compared to https://nayduck.near.org/#/run/3424
And 1 more as well
https://nayduck.near.org/#/run/3428

fix some of nayduck tests

---

chain/chain/src/chain.rs
chain/chain/src/stateless_validation/chunk_endorsement.rs
chain/client-primitives/src/debug.rs
tools/mirror/src/chain_tracker.rs

chore: fix typos

---

chain/chain/src/runtime/mod.rs

snapshot: remove the error about missing snapshot on node startup

---

runtime/near-vm-runner/src/near_vm_runner.rs

vm: do not hold a lock while executing the contract

---

runtime/near-vm-runner/src/cache.rs

It is possible that `generate` will have to compile some WASM code. This is especially notable with contract factories. Each such compilation would lead to a global lock being held which would prevent other shards from making progress at the same time.

vm: don't hold lock while potentially compiling

---

runtime/near-vm-runner/src/cache.rs

It is possible that `generate` will have to compile some WASM code. This is especially notable with contract factories. Each such compilation would lead to a global lock being held which would prevent other shards from making progress at the same time.
Backport of https://github.com/near/nearcore/pull/10881
cc @VanBarbascu

[1.39] vm: don't hold lock while potentially compiling

---

tools/debug-ui/package-lock.json

This PR tests how everything works with different gas prices, related to #10849

[gas price testing]

---

chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/tests.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/chain/src/update_shard.rs
chain/client/src/client.rs
chain/client/src/stateless_validation/chunk_validator/mod.rs
chain/client/src/stateless_validation/shadow_validate.rs

Revert #10859 because it's causing trouble on statelessnet
This reverts commit c2f96956eb3072b2ba2e42aefbda272ac997ae44.

Revert "Always record storage when stateless validation is enabled"

---

core/store/src/trie/prefetching_trie_storage.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/prefetch.rs

[1.39.0] runtime: prefetch account keys and data for chunk finalization

---

runtime/runtime/src/metrics.rs

As it was spotted in the previous PR, let's quickly fix that as well.

fix: [1.39] local receipts count

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/workload/all_for_one.rs

Added some more workloads, all variations of the All To One workload.

feat(congestion) - Added a few more All To One workloads.

---

tools/congestion-model/src/strategy/nep.rs

replacing the general congestion with outgoing congestion 
(renaming + removing the incoming receipts stats from this metric)

feat(congestion) - general congestion -> outgoing congestion

---

CHANGELOG.md

We also need to add other changes in this release to the changelog.

[docs] Add changelog entry for 1.39.0 release

---

tools/congestion-model/src/strategy/nep.rs

Without this, the "Big Linear Imbalance" workload on the NEP strategy uses 36.8 GB after 1000 rounds with 4 shards.
With this extra limit, we stay around 1GB.

congestion: put size limit on incoming congestion

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/workload/all_for_one.rs

An approximation of what game.hot.tg workload would look like with new gas costs.

congestion: add hot.tg model strategy

---

tools/debug-ui/package.json
tools/debug-ui/src/BlocksView.tsx
tools/debug-ui/src/ChainInfoSummaryView.tsx
tools/debug-ui/src/ClusterNodeView.tsx
tools/debug-ui/src/ConnectionStorageView.tsx
tools/debug-ui/src/CurrentPeersView.tsx
tools/debug-ui/src/EpochShardsView.tsx
tools/debug-ui/src/EpochValidatorsView.tsx
tools/debug-ui/src/FloatingChunksView.tsx
tools/debug-ui/src/HeaderBar.tsx
tools/debug-ui/src/LatestBlocksView.tsx
tools/debug-ui/src/PeerStorageView.tsx
tools/debug-ui/src/RecentEpochsView.tsx
tools/debug-ui/src/RoutingTableView.tsx
tools/debug-ui/src/SnapshotHostsView.tsx
tools/debug-ui/src/Tier1View.tsx
tools/debug-ui/src/index.tsx

Fixes: https://github.com/near/nearcore/issues/10914
I'm not sure if that's the proper solution, would appreciate a review from someone familiar with the javascript ecosystem.
I found this solution on stackoverflow:
https://stackoverflow.com/questions/73207151/could-not-find-a-declaration-file-for-module-react-query

fix: debug-ui: use tanstack/react-query instead of react-query

---

tools/mirror/src/genesis.rs

When we map delayed and postponed receipts, we need to change keys and account IDs in any delegate actions. Otherwise they will fail with invalid access key errors and/or add keys that we cannot control. This can be done by mapping all the actions inside the delegate action the same way we map the other actions.
We still need to handle delegate actions correctly in `mirror run` when sending transactions containing them, but that is best left for a separate PR, as there might be some tricky nonce ugliness to deal with.

fix(mirror): map delegate actions correctly in the genesis state

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/strategy/nep.rs

This adds the ability to parametrize the NEP strategy.
Plus, it add sever model parametrizations for comparisons..

congestion: fine-tuning parameters in the model

---

chain/network/src/routing/graph/mod.rs
chain/network/src/store/mod.rs
chain/network/src/store/schema/mod.rs
core/store/src/db.rs
core/store/src/db/refcount.rs
core/store/src/db/rocksdb.rs
core/store/src/lib.rs

These instrumentation have helped with tracking down https://github.com/near/nearcore/pull/11018 which was causing some pretty severe performance issues on the rocksdb write path.

store: additional instrumentation around the storage stack

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/workload/fairness_benchmark.rs
tools/congestion-model/src/workload/mod.rs

This workload shows a weakness of the NEP that's based on decoupled congestion.
So far, only traffic light can keep a high utilization in this workload.
Running with `--rounds 2000 --warmup 1000 --shards 8 --tx-pool-size 200`.
```
WORKLOAD                 STRATEGY                       BURNT GAS PER CHUNK    TRANSACTIONS FINISHED MEDIAN TX DELAY    90p TX DELAY   MAX QUEUE LEN  MAX QUEUE SIZE  MAX QUEUE PGAS
Fairness Test            No queues                                1014 TGas                   159920               1             305           64010        640.1 MB           12802
Fairness Test            Global TX stop                            151 TGas                    27032             150             244            2466         24.7 MB             493
Fairness Test …
```

congestion: workload testing fairness

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/strategy/nep.rs

Put final fine-tuning results inside the model code for future reference.

congestion: clean up NEPv3 strategy

---

tools/congestion-model/run_eval.sh

This script was used to produce the data in https://docs.google.com/spreadsheets/d/1Vt_-sgMdX1ncYleikYY8uFID_aG9RaqJOqaVMLQ37tQ/edit#gid=0.
It contains the set of model runs that I found informative to come up with a proposal for the fine-tuned parameters.
Maybe other people can use it to quickly compare their improvement ideas, I'm sure we haven't found the "best" strategy, yet, if such a thing exists.
I think it makes sense to store it along the source. But I am also open to just storing on the drive and not adding it to git repo.

congestion: script to reproduce fine-tuning data

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/strategy/smooth_traffic_light.rs

These variants are to explore different design points, optimizing for delay or utilization.
I tried many different angles and distances to find a good set of parameter combinations. I can't say for sure if these are optimal, but I think they are reasonable representations of how we can change parameters to get better delays or utilization.

congestion: Smooth traffic light variations

---

tools/state-viewer/README.md

The argument name should be `--end-index`.

Fix command in state-viewer README

---

CHANGELOG.md

1.39.0 Changelog

---

runtime/near-vm-runner/src/near_vm_runner/memory.rs
runtime/near-vm/engine/src/resolver.rs
runtime/near-vm/test-api/src/sys/externals/memory.rs
runtime/near-vm/vm/src/export/mod.rs
runtime/near-vm/vm/src/export/vmmemory.rs
runtime/near-vm/vm/src/instance/mod.rs
runtime/near-vm/vm/src/memory/linear_memory.rs
runtime/near-vm/vm/src/memory/mod.rs

reduce visibility around LinearMemory

---

chain/chain-primitives/src/error.rs
chain/chain/src/chain.rs

This error can happen for a few different reasons, adding an extra description to make debugging easier.

refactor(InvalidChunk) - added debug message to the InvalidChunk error

---

chain/jsonrpc/res/sync.html
tools/debug-ui/src/ClusterNodeView.tsx
tools/debug-ui/src/LandingPage.tsx
tools/debug-ui/src/RoutingTableView.tsx
tools/debug-ui/src/SnapshotHostsView.tsx
tools/debug-ui/src/api.tsx
tools/debug-ui/src/log_visualizer/events.ts
tools/debug-ui/src/log_visualizer/layout.ts

Also run "npm run fix" and fix issues.

[Debug UI] Fix the start_height UI crash.

---

pytest/lib/configured_logger.py
pytest/lib/messages/block.py
pytest/lib/messages/network.py
pytest/lib/proxy.py
pytest/lib/serializer.py
pytest/tests/sanity/proxy_simple.py

The new fields need to be added to the borsch schema in python. 
Some logs, comments and styling changes.

fix(congestion_control) - fixing nayduck test - proxy simple

---

chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/client/src/sync/state.rs

small refactoring and added comments
Please check the comments are accurate, it was best effort :)

 refactor(state-sync): small refactor and adding comments 

---

.github/workflows/neard_custom_release.yml

Create an action to build custom binaries

custom build action

---

core/primitives/src/epoch_manager.rs

This reverts commit f77f832da6348cb1ef9860d662144927e9d0e5ae.

Revert "Shard assignment shuffling"

---

chain/chain/src/state_snapshot_actor.rs
chain/chain/src/test_utils/test_loop.rs
integration-tests/src/tests/client/features/multinode_test_loop_example.rs
nearcore/src/lib.rs

This PR is mainly a refactor with no functional changes.
Follow up of PR https://github.com/near/nearcore/pull/11214

[actor] Migrate StateSnapshotActor to use ActixWrapper

---

pytest/lib/cluster.py
pytest/tests/sanity/rosetta.py

* set proper path to `fungible_token.wasm`
* don't use `mocknet_helpers` since it assumes node running on a fixed port

fix: sanity/rosetta.py test

---

docs/architecture/network.md
docs/practices/workflows/otel_traces.md

Similar to https://github.com/near/nearcore/pull/11233, fixed some typos under `docs`.

Fix some typos

---

chain/client/src/adapter.rs
chain/client/src/lib.rs
chain/client/src/test_utils/setup.rs
chain/client/src/view_client_actor.rs
core/async/src/actix_wrapper.rs
integration-tests/src/tests/network/runner.rs
nearcore/src/lib.rs

This PR is mainly a refactor with no functional changes.
Follow up of PR https://github.com/near/nearcore/pull/11214

[actor] Migrate ViewClientActor to use ActixWrapper

---

chain/chunks/src/chunk_cache.rs

* be more specific by adding `rear` and `front` to `horizon`
* fix `HEIGHT_HORIZON` -> `MAX_HEIGHTS_AHEAD`

refactor: fix chunk_cache.rs comments

---

chain/client/src/stateless_validation/chunk_validator/mod.rs
chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
core/primitives/src/stateless_validation.rs

Some debug logs, will add metrics soon.

[stateless_validation] Debug logs for partial_witness

---

chain/rosetta-rpc/README.md

I couldn't find the right link so I'm just deleting it to fix the lints. If anyone knows the right link please share it and I'll update it. 
The best I could find is this, but this is not what's needed based on context. 
https://docs.cloud.coinbase.com/rosetta/docs/welcome

fix(lychee) - remove bad link

---

runtime/runtime/src/balance_checker.rs

Extract from check_balance the code that extracts details from receipts, transaction, and state.
These submethods are extracted:
- buffered_receipts()
- potential_postponed_receipt_ids()
- all_touched_accounts()
- validator_rewards()
The first two are just extracted without modification.
The last two used to be intertwined. I think its cleaner to read to separate them.

refactor: split check_balance into submethods

---

runtime/runtime/src/prefetch.rs

sweat: update prefetcher for record_batch_for_hold

---

chain/network/src/routing/graph/mod.rs

We are in a peculiar situation at the moment:
- After #11018, nodes are repeatedly spamming each other with ancient edge tombstones
- The subsequent PR #11321 stops the spam by expiring the old edges
If a node has both commits but its neighbor(s) have only the first, it continues to be bombarded with what it now recognizes as expired edges.
The problem is that processing many copies of the same expired edge(s) is very slow. That is because expired edges aren't stored at all:
https://github.com/near/nearcore/blob/66031e2d7bfd796bbca7418bf24d65b01a4ada9b/chain/network/src/routing/graph/mod.rs#L63-L68
so every copy which arrives has its signature verified again:
https://github.com/near/nearcore/blob/66031e2d7bfd796bbca7418bf24d65b01a4ada9b/chain/network/src/routing/graph/mod.rs#L155-L162
The …

routing: check edge nonce before signature

---

pytest/tests/loadtest/locust/common/base.py

We migrate away from `broadcast_tx_commit` and `broadcast_tx_async` which are now deprecated in favor of `send_tx`: https://docs.near.org/api/rpc/transactions
I believe this PR should preserve the behavior that we had before and I plan to do any behavior changes in the future PRs.
Tested by running:
```sh
locust -H 127.0.0.1:3030 \
-f locustfiles/ft.py \
--funding-key=$KEY --headless -u 2000 -r 50 -t 120s
```
This is a part of work on improving the performance of Locust load test runner: https://github.com/near/nearcore/issues/11352

locust: Migrate to new transaction API

---

pytest/tests/mocknet/mirror.py

if --gcs-state-sync is not provided, we set this config parameter to null, but it leads to an error deserializing the config. so only set non-null state sync locations. Also warn the user if this is happening, because if there's a state dumper node configured but this option wasn't given, probably you did something wrong

fix(forknet): dont set state_sync.dump.location to null

---

core/store/src/trie/mem/iter.rs
core/store/src/trie/mod.rs
core/store/src/trie/trie_tests.rs

Based on @Longarithm 's #11402 , and added a unit test.

[Memtrie] Fix memtrie iterator plus unit tests

---

chain/client/src/sync/adapter.rs
chain/client/src/sync/sync_actor.rs

This PR is mainly a refactor with no functional changes.
Follow up of PR https://github.com/near/nearcore/pull/11214

[actor] Migrate SyncActor to use ActixWrapper

---

integration-tests/src/tests/client/features/yield_timeouts.rs
integration-tests/src/tests/runtime/test_yield_resume.rs
runtime/near-test-contracts/test-contract-rs/src/lib.rs

remove nightly flags on yield/resume tests

---

nearcore/src/download_file.rs

Hyper is not opinionated enough to care about connection StatusCode.
In case of errors such as AccessDenied, return code 403, it will still download the return body and not raise any errors (see https://github.com/near/nearcore/issues/7121).
status_code.is_success checks if status is within 200-299.
```
nearcore/target/debug/neard --home ".near" init --chain-id inexistent_network --download-genesis --download-config
2024-06-01T18:23:34.118646Z  INFO neard: version="trunk" build="1.36.1-671-g99a05c482" latest_protocol=67
2024-06-01T18:23:34.121032Z  INFO near: Downloading config file from: https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/inexistent_network/config.json ...
Error: Failed to initialize configs
Caused by:
0: Failed to download the config file from …
```

Handle correctly failed downloads

---

chain/client/src/stateless_validation/chunk_validator/orphan_witness_handling.rs

This error is annoying in integration tests and localnet.

nit(stateless_validation) - Gracefully handle genesis in orphan witness cleanup

---

rust-toolchain.toml

Added rust-analyzer to the toolchain file, so it's easier to work with the repo on fresh start.

[chore] Added rust-analyzer to the toolchain file

---

runtime/near-vm-runner/src/imports.rs

I'm exploring movement of the import code to their respective implementations in order to make the interfaces to the import code a little more flexible (and possibly less dependent on VMLogic struct.)
Part of #11319

vm: deduplicate code on  host function tracing

---

integration-tests/src/tests/client/features/stateless_validation.rs

Enhanced the `run_chunk_validation_test` test helper with ability to drop blocks with given probability and added a few tests that have both missing chunks and missing blocks.

test(stateless_validation) - Added tests with missing blocks

---

pytest/lib/cluster.py

before:
```
/home/waclaw/nearcore/pytest/lib/cluster.py:243: ResourceWarning: unclosed <socket object, fd=11, family=2, type=1, proto=6>
r = session(timeout).get("http://%s:%s/status" % self.rpc_addr())
```
after:
```
```

fix(nayduck) - fix ResourceWarning unclosed socket

---

Cargo.lock
Cargo.toml
chain/chain/src/chain.rs
chain/chain/src/crypto_hash_timer.rs
chain/chain/src/state_request_tracker.rs
chain/chain/src/stateless_validation/chunk_validation.rs
chain/chunks/src/shards_manager_actor.rs
chain/client/src/chunk_inclusion_tracker.rs
chain/client/src/client.rs
chain/client/src/debug.rs
chain/client/src/info.rs
chain/client/src/stateless_validation/chunk_endorsement_tracker.rs
chain/client/src/stateless_validation/chunk_validator/orphan_witness_pool.rs
chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
chain/client/src/stateless_validation/state_witness_tracker.rs
chain/client/src/sync/state.rs
chain/client/src/view_client_actor.rs
chain/network/src/announce_accounts/mod.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/peer_store/mod.rs
chain/network/src/raw/connection.rs
chain/network/src/routing/routing_table_view/mod.rs
chain/network/src/snapshot_hosts/mod.rs
core/store/src/trie/trie_storage.rs
utils/near-cache/benches/cache.rs
utils/near-cache/src/cell.rs
utils/near-cache/src/sync.rs

reed-solomon-erasure package still depends on version 0.7.8 unfortunately

[lru] Bump version from 0.7.8 to 0.12.3

---

chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs

This PR updates `validate_partial_encoded_state_witness` to not return `Err` when partial witness could be potentially valid at some point. Instead we write a debug log for now and I will emit metrics as part of a separate PR.
For more context see #11545.

fix: fix log spam from partial witness validation

---

scripts/ft-benchmark-data-sender.py
scripts/ft-benchmark.sh

This code will take collected data and send it to ft-benchmark db using CLI

[ft-benchmark] add using of db cli

---

docs/misc/state_witness_size_limits.md

Added two new paragraphs to make things clearer

Improve documentation about state witness size limits

---

chain/client-primitives/src/debug.rs
chain/client/src/debug.rs
chain/jsonrpc/res/congestion_control.js

Add `congestion_level` to the debug page dedicated to congestion control.

feat(debug): add congestion_level in congestion control debug page

---

core/store/src/migrations.rs

Unexpected follow-up to #11569.
If I need to handle two migrations touching the same data, I have to support intermediate legacy version. For this case, it is version 39, so migrate_38_to_39 stopped working.

fix: proper migration to db version 39

---

pytest/tests/loadtest/locust/common/base.py

Makes it easier to see these requests in the dashboard and error messages.

locust: Annontate NearUser creation

---

core/parameters/res/runtime_configs/80.yaml
core/parameters/src/snapshots/near_parameters__config_store__tests__129.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__138.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__80.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__83.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__85.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__87.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__90.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_129.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_138.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_80.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_83.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_85.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_87.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_90.json.snap

As discussed in the congestion control meeting.

param(congestion_control) - Increase max_congestion_missed_chunks to 5 

---

pytest/tests/loadtest/locust/README.md

Locust is now a part of base dependencies.

Update locust README.md

---

pytest/tests/sanity/rpc_tx_status.py

Use correct tx in the end of test. Checked that test is still passing locally.

fix: variable in rpc_tx_status test

---

integration-tests/src/test_loop/mod.rs
integration-tests/src/test_loop/tests/in_memory_tries.rs
integration-tests/src/test_loop/tests/multinode_stateless_validators.rs
integration-tests/src/test_loop/tests/multinode_test_loop_example.rs
integration-tests/src/test_loop/tests/simple_test_loop_example.rs
integration-tests/src/test_loop/utils.rs

This is a common logic used in all (3) TestLoop tests and I extract it to separate utils module. I want to achieve test logic to be as simple as possible.

refactor: execute money transfers util in TestLoop

---

integration-tests/README.md

Hopefully this should help to write new integration tests without prior experience.

doc: writing integration tests in TestLoop

---

Makefile
scripts/binary_release.sh

feat: add release with test_features enabled

---

chain/client/src/stateless_validation/chunk_validator/mod.rs

This is a stopgap measure for the problem highlighted in #11750 
There's a corner case related to switching validator key that brings the node to temporarily fail to apply self chunk endorsement. I think it might be better to carry on rather than crash since this doesn't break the chain.
Also fixes the failing test `validator_switch_key`

Avoid crashing upon failing to process self chunk endorsements

---

scripts/run-ft-benchmark.py

We don't want to delete not ours lock file

[ft-benchmark] small fix

---

docs/architecture/how/meta-tx.md

use master link of nep-366 to improve readability.
@race-of-sloths

chore(docs): use master link of nep-366

---

Cargo.lock

chore: update openssl

---

chain/network/src/network_protocol/mod.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/rate_limits/messages_limits.rs

StateResponse message had been long deprecated.

[cleanup] Remove deprecated StateResponse message

---

integration-tests/src/test_loop/builder.rs

When constructing runtime adapters, the builder currently passes `None` as `Option<RuntimeConfigStore>` into the constructor. As a result, ultimately the config store corresponding to the chain id is used [[ref](https://github.com/near/nearcore/blob/658ec13c1b0de6aa5c0fc1bb1a6cdfec9703f439/chain/chain/src/runtime/mod.rs#L99)].
This PR adds the option to pass a `RuntimeConfigStore` into the builder that will be used to construct runtime adapters. The builder's default behavior remains unchanged.
Enable using custom `RuntimeConfig`s in `TestLoop`. This will be used to test the upcoming (test/benchmark) feature of [adjusting the gas limit at runtime](https://near.zulipchat.com/#narrow/stream/295302-general/topic/Adjusting.20gas.20limit.20at.20runtime/near/455661815).

test(TestLoop): enable passing `RuntimeTimeConfigStore` into builder

---

Cargo.toml
integration-tests/src/test_loop/builder.rs
runtime/runtime-params-estimator/emu-cost/Dockerfile
rust-toolchain.toml
tracing/Cargo.toml

https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html

chore: upgrade toolchain to 1.80.1

---

pytest/requirements.txt
pytest/tests/sanity/epoch_switches.py

Nodes need to track all shards. Otherwise they get stuck trying to state sync and state sync is not configured for this test.
https://nayduck.nearone.org/#/run/224

fix(nayduck): epoch_switches

---

CHANGELOG.md

Describe changes from the [2.2.0 branch](https://github.com/near/nearcore/commits/2.2.0/)

Add 2.2.0 release to CHANGELOG.md

---

Cargo.lock
Cargo.toml
chain/network/Cargo.toml
chain/telemetry/Cargo.toml
core/dyn-configs/Cargo.toml
core/primitives/Cargo.toml
core/time/Cargo.toml
integration-tests/src/tests/dependencies.rs
nearcore/src/lib.rs
runtime/near-vm-runner/fuzz/Cargo.toml
tools/storage-usage-delta-calculator/Cargo.toml

Tested with:
```
cargo ws exec -- cargo check --all-features
cargo ws exec -- cargo check --no-default-features
cargo ws exec -- cargo check      # This is the one that we needs to be pass. Others are nice to have for now.
cargo ws publish --dry-run
cargo build -pneard
```

Fix the crates publishing process

---

.cargo/config.profiling.toml
.cargo/config.toml
docs/practices/workflows/profiling.md

I have been investigating some microarchitectural details of parts of neard (memtrie in particular) and I ended up spending quite some time on figuring out ways to obtain information I knew I had available to me.
Documented the processes and considerations here...

profiling: add a profiling config and docs on hw counters

---

chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/connection/mod.rs
chain/network/src/peer_manager/network_state/mod.rs

Fixes: https://github.com/near/nearcore/issues/12010

fix(network): Use DEBUG log level for network messages to reduce spam

---

chain/jsonrpc-primitives/src/types/entity_debug.rs
chain/jsonrpc/src/lib.rs
nearcore/src/entity_debug.rs
nearcore/src/lib.rs
tools/debug-ui/src/CurrentPeersView.tsx
tools/debug-ui/src/EpochValidatorsView.tsx
tools/debug-ui/src/LogFileDrop.tsx
tools/debug-ui/src/RecentEpochsView.tsx
tools/debug-ui/src/api.tsx
tools/debug-ui/src/entity_debug/EntityDataRootView.tsx
tools/debug-ui/src/entity_debug/EntityDataValueView.tsx
tools/debug-ui/src/entity_debug/EntityDebugView.tsx
tools/debug-ui/src/entity_debug/EntityQueryComposer.tsx
tools/debug-ui/src/entity_debug/PinnedKeysView.scss
tools/debug-ui/src/entity_debug/PinnedKeysView.tsx
tools/debug-ui/src/entity_debug/fetcher.tsx
tools/debug-ui/src/entity_debug/fields.tsx
tools/debug-ui/src/entity_debug/keys.tsx
tools/debug-ui/src/entity_debug/pinned_keys.tsx
tools/debug-ui/src/entity_debug/types.tsx
tools/debug-ui/src/log_visualizer/LogVisualizer.tsx
tools/debug-ui/src/log_visualizer/events.ts

Entity Debug UI now shows a little "Use cold storage" checkbox at the bottom. Any new query that is being sent will use the current state of the checkbox to decide whether it should query from cold storage.
Also run "npm run fix" to fix file formatting of all the tsx files.

[Debug UI] Add cold storage support to Entity Debug.

---

runtime/runtime/src/ext.rs

This fixes the stalls that some of the 2.1 and 2.2 nodes experienced while doing state sync.

fix(eth-wallet-contract): use hash of the contract WASM in contract cache

---

.cargo/audit.toml

chore: ignore `RUSTSEC-2024-0370`

---

chain/network/src/peer_manager/network_state/mod.rs

This simple limit is added for security purposes; it prevents the node from going OOM due to unbounded addition to the queue. In the future we will implement separate resource pools to prioritize incoming requests from validator nodes.
--- 
Currently a node processes at most one tier3 request per second:
https://github.com/near/nearcore/blob/d6d6e4782f7d57a7b7acc2894e1668355012ff74/chain/network/src/peer_manager/peer_manager_actor.rs#L92
and the default timeout on the node which sent the request is 60 seconds:
https://github.com/near/nearcore/blob/d6d6e4782f7d57a7b7acc2894e1668355012ff74/core/chain-configs/src/client_config.rs#L282
Hence a queue limit of 60 means that any dropped requests would not have been served in time anyway.

fix(network): bound size of tier3_requests queue

---

lychee.toml

This was getting irritating...

[fix] Fix lychee workflow

---

.github/workflows/nayduck_ci.yml
nightly/ci.txt

removing -e jq argument as it's causing jq to return non-null exit codes.

CI Nayduck fix

---

docs/architecture/gas/README.md

[fix] Fix Lychee lint

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/ondemand_fuzzer_binaries.yml
Cargo.toml
core/crypto/Cargo.toml

add rand-std to crypto crate
successful run https://github.com/near/nearcore/actions/runs/11143409511/job/30968440679

Fuzz binaries build workflow fix

---

Cargo.lock
Cargo.toml
chain/client/src/client_actor.rs
chain/client/src/sync/state.rs

bump version string and cherry pick https://github.com/near/nearcore/pull/12205

2.3.0-rc.3

---

nightly/ci.txt
nightly/ci_dev.txt

test: all nayduck tests in ci, except flaky ones

---

chain/chain/src/chain.rs
chain/chain/src/resharding/manager.rs
chain/chain/src/store/mod.rs
core/store/src/trie/mem/mem_tries.rs
core/store/src/trie/mem/resharding.rs
core/store/src/trie/shard_tries.rs

Basically a response to https://github.com/near/nearcore/pull/12211#pullrequestreview-2367062535.

chore(resharding): logging on memtrie update

---

chain/chain/src/flat_storage_resharder.rs

This PR enhances the flat storage resharder with the logic to split all types of keys, including receipts.
As talked during the offsite the logic is more or less the following:
- Delayed receipt: copy key to both children
- Promise yield: copy key to both children
- Buffered receipt: copy key to first(left) children
The tests are in first commit, the logic in the second.

feat(resharding): flat storage resharding split all keys

---

tools/debug-ui/src/log_visualizer/LogVisualizer.scss
tools/debug-ui/src/log_visualizer/LogVisualizer.tsx

[Debug UI] Add "Copy" button to log visualizer log view.

---

chain/client/src/sync/epoch.rs

[Epoch Sync] Only run epoch sync if we're at genesis.

---

chain/epoch-manager/src/lib.rs

Auto fixed issue https://github.com/near/nearcore/issues/5080

[fix] Set BLOCK_CACHE_SIZE to 1 in epoch manager for no_cache feature

---

chain/chain/src/runtime/tests.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/client/src/stateless_validation/partial_witness/partial_deploys_tracker.rs
chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
chain/client/src/stateless_validation/validate.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/lib.rs
chain/epoch-manager/src/tests/mod.rs
core/primitives/src/reed_solomon.rs
core/primitives/src/stateless_validation/contract_distribution.rs

Implements basic validation for `PartialEncodedContractDeploys`.

feat: add partial contract deploys validation

---

core/primitives/src/shard_layout.rs
integration-tests/src/test_loop/tests/resharding_v3.rs

Derive shard layout

---

core/primitives/src/receipt.rs

Refactor `Receipt` deserialization

---

integration-tests/src/test_loop/tests/resharding_v3.rs
integration-tests/src/tests/client/features/stateless_validation.rs

The be exact, I'm removing the last bad usages, there are still some that are ok - mostly in the v1 tests.

refactor(resharding) - remove the last remaining usages of ShardLayout::v1

---

chain/epoch-manager/src/lib.rs

`ok_or_else` are better suited so that if the error paths are not triggered then we do not construct potentially expensive error values needlessly

  refactor: undo replacing `ok_or_else` with `ok_or` in #12481

---

core/primitives/src/views.rs
pytest/tests/sanity/congestion_control.py

Fix and test the congestion_level rpc endpoint. 
cc @telezhnaya

fix(congestion) - fix the congestion level rpc

---

chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/test_utils.rs
chain/chain/src/runtime/tests.rs

[cleanup] Separate test_utils for nightshade runtime

---

tools/flat-storage/src/commands.rs

Also remove hack which is not needed since 1.40.

fix(flat-storage): inline values on move head back

---

core/primitives/src/shard_layout.rs
integration-tests/src/test_loop/tests/resharding_v3.rs
runtime/runtime/src/congestion_control.rs

Some small improvements, mostly following up on the previous PR. Most importantly the V2 ShardLayout is now better validated on both paths (the v2 ctor and the serde deserialize).

refactor(resharding) - small refactors, improvements and asserts

---

chain/indexer/src/streamer/mod.rs

**Problem**
The current implementation incorrectly mixes `shard_index` values, causing inconsistencies during the data collection process. This leads to incorrect shard mapping and potential data inaccuracies.
**Solution**
This PR updates the logic to correctly collect `indexer_shards` and get the `shard_index` directly from the `shard_id`. The updated approach ensures accurate shard indexing and resolves the problem of mixed `shard_index` values.

improve logic to collect `indexer_shards` to get `shard_index` from `shard_id`

---

runtime/runtime/src/lib.rs

Fixing unhandled protocol upgrade introduced in #12555.

fix(congestion_control) - proper protocol upgrade handling for congestion seed

---

.github/workflows/ci_nightly.yml

Chore: notify on CI periodic run failures in Zulip

---

core/chain-configs/src/client_config.rs

PR to update resharding config to "good" starting values.

Set tentatively good default values in resharding config

---

.github/workflows/ci.yml
Justfile

chore: check publishable crates separately

---

core/chain-configs/src/test_genesis.rs
integration-tests/src/tests/client/features/in_memory_tries.rs

refactor: bake defaults into test builders

---

core/async/src/test_loop/futures.rs
core/o11y/src/metrics.rs
core/primitives-core/src/types.rs
integration-tests/src/tests/client/features/zero_balance_account.rs
runtime/near-vm-runner/src/runner.rs

**What does this pull request do? Explain your changes.**  
This pull request addresses several typographical errors in various files within the repository. The following files were updated:
- `futures.rs` (in `core/async/src/test_loop/`)
- `metrics.rs` (in `core/o11y/src/`)
- `types.rs` (in `core/primitives-core/src/`)
- `zero_balance_account.rs` (in `integration-tests/src/tests/client/features/`)
- `runner.rs` (in `runtime/near-vm-runner/src/`)
**Specific updates:**
- Fixed the usage of incorrect articles such as changing "a event-loop-based" to "an event-loop-based."
- Corrected other minor typographical issues across different files.
**How did you test each of these updates?**  
The changes were tested by reviewing the files for correctness, ensuring that the typographical issues were …

Fix typos in various Rust and TypeScript files

---

tools/mock-node/src/setup.rs
tools/state-viewer/src/replay_headers.rs

**Setup up - Set up** 
**reasong - reason**

fix spelling issues 

---

integration-tests/src/test_loop/tests/resharding_v3.rs

This should be fixed by #12661

test(resharding) - remove track all shards from yield resume test

---

utils/near-cache/src/cell.rs
utils/near-cache/src/sync.rs

chore: correct typos docs

---

tools/replay-archive/src/cli.rs

chore: fix typos cli.rs

---

chain/chain/src/chain.rs
chain/chain/src/resharding/manager.rs
chain/client/src/sync/state/shard.rs
core/store/src/config.rs
core/store/src/test_utils.rs
core/store/src/trie/config.rs
core/store/src/trie/mem/arena/alloc.rs
core/store/src/trie/mem/arena/concurrent.rs
core/store/src/trie/mem/arena/metrics.rs
core/store/src/trie/mem/loading.rs
core/store/src/trie/mem/lookup.rs
core/store/src/trie/mem/memtrie_update.rs
core/store/src/trie/mem/memtries.rs
core/store/src/trie/mem/metrics.rs
core/store/src/trie/mem/mod.rs
core/store/src/trie/mod.rs
core/store/src/trie/ops/tests.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/trie_recording.rs
integration-tests/src/test_loop/builder.rs
integration-tests/src/test_loop/tests/in_memory_tries.rs
integration-tests/src/test_loop/tests/resharding_v3.rs
integration-tests/src/test_loop/utils/trie_sanity.rs
integration-tests/src/tests/client/features/in_memory_tries.rs
runtime/runtime-params-estimator/src/estimator_context.rs
tools/database/src/memtrie.rs
tools/fork-network/src/cli.rs
tools/fork-network/src/single_shard_storage_mutator.rs
tools/state-viewer/src/apply_chain_range.rs
tools/state-viewer/src/cli.rs

No functional change, only change of variable name

[cleanup] Rename mem_trie to memtrie

---

chain/rosetta-rpc/CHANGELOG.md

Typo fix in `CHANGELOG.md`
---
This pull request addresses a typo in the `CHANGELOG.md` file located in `chain/rosetta-rpc/`:
- Corrected "submittion" to "submission."
**Original:**  
> Construction API exposes the bare minimum signed transaction submittion API  
**Fixed:**  
> Construction API exposes the bare minimum signed transaction submission API

Typo fix CHANGELOG.md

---

Cargo.lock
Cargo.toml
core/store/src/db/rocksdb.rs

Reverts near/nearcore#12672
Attempt to fix regression related to disk usage.
cc @mina86

Revert "chore: update rocksdb dependency to 0.22"

---

chain/chain/src/resharding/resharding_actor.rs
chain/chain/src/resharding/resharding_v2.rs
chain/chunks/src/client.rs
chain/client/src/client.rs
core/store/src/flat/manager.rs

- Removing a few TODOs which aren't valid anymore
- Adding more context to an existing TODO

chore: remove or improve resharding TODOs

---

nearcore/src/state_sync.rs

Currently the part upload tasks (shard_id, part_id) are enumerated in a Vec that we shuffle and take from with buffer_unordered(). But if there's a shard that can't be dumped because obtain_state_part() is giving an error, and this happens for enough parts in the shard, then this stream of tasks will no longer start any new part upload tasks, even for shards that have no issues.
Fix it by having one stream of tasks per shard so that each one will be allowed to complete even if there are errors in the others. This also simplifies things somewhat since there's no need to keep the `oneshot::Sender` in a `HashMap`

fix(state-dumper): continue dumping state for other shards upon error

---

benchmarks/synth-bm/src/account.rs
benchmarks/synth-bm/src/contract.rs
benchmarks/synth-bm/src/native_transfer.rs

The project does not compile on current master.
Most probably this issue sneaked in due to auto-merging of recent commits.

fix compilation of synth-bm

---

core/store/src/trie/update.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/pipelining.rs

This PR adds proper Global Contracts support for contract preparation pipeline.
Global contract deployments are triggered by `ReceiptEnum::GlobalContractDistribution`, so we block contract identifiers observed in such receipts. This is similar to what we already have with `block_accounts`.
`TrieUpdate::get_ref_no_side_effects` is added in order to be able to resolve global contract hash deployed by account id without actually reading the contract code from the storage.
Part of #12716.

feat: global contracts pipelining support

---

chain/chain/src/chain.rs
chain/chain/src/flat_storage_resharder.rs
chain/chain/src/state_snapshot_actor.rs
chain/chain/src/state_sync.rs
core/store/src/flat/manager.rs
core/store/src/flat/storage.rs
integration-tests/src/test_loop/builder.rs
nearcore/src/lib.rs

These cherry picks fix some issues found in testing:
* https://github.com/near/nearcore/pull/12907
* https://github.com/near/nearcore/pull/12912
* https://github.com/near/nearcore/pull/12920

snapshot fix cherry picks

---

Cargo.toml
chain/network/src/config.rs
core/primitives/src/shard_layout.rs
core/primitives/src/utils.rs

Move test function under the test namespace.

Fix crates

---

chain/indexer/src/streamer/mod.rs
core/primitives/src/views.rs

 fix(resharding) - fix indexer using old chunks shard id 

---

chain/client/src/info.rs

fix(metrics) - fix shard id / shard index mixup

---

chain/chain/src/doomslug.rs

...so it becomes a lot more readable.

chore: reduce indentation in doomslug ready_to_produce_block

---

chain/chain/src/flat_storage_resharder.rs
chain/chain/src/resharding/manager.rs
core/store/src/trie/trie_recording.rs

fix(resharding): Refcounts quick fix

---

pytest/tests/mocknet/local_test_node.py
pytest/tests/mocknet/mirror.py
pytest/tests/mocknet/node_handle.py
pytest/tests/mocknet/remote_node.py

Add a simple yet useful command to upload a file from the host machine to the forknet nodes.

feat(mirror): add command to upload a file on nodes

---

core/primitives/src/version.rs

```
Epoch -1: 13 hours, 21 minutes
Epoch -2: 13 hours, 38 minutes
Epoch -3: 13 hours, 30 minutes
Epoch -4: 13 hours, 37 minutes
Epoch -5: 13 hours, 23 minutes
Epoch -6: 13 hours, 34 minutes
Epoch -7: 13 hours, 39 minutes
Epoch -8: 13 hours, 40 minutes
Epoch -9: 13 hours, 39 minutes
Epoch -10: 13 hours, 25 minutes
Epoch -11: 13 hours, 27 minutes
Epoch -12: 13 hours, 36 minutes
Epoch -13: 13 hours, 56 minutes
Epoch -14: 13 hours, 32 minutes
Epoch -15: 13 hours, 33 minutes
Epoch -16: 13 hours, 39 minutes
Epoch -17: 13 hours, 44 minutes
Epoch -18: 13 hours, 37 minutes
Epoch -19: 13 hours, 49 minutes
Epoch -20: 13 hours, 28 minutes
Exponential weighted average epoch length: 13 hours, 34 minutes
Predicted start of epoch 1: 2025-03-04 01:54:18 UTC+0000 Tuesday
Predicted start of epoch 2: …
```

Protocol voting schedule

---

chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs

[log] Better logging of partial_witness in validation path

---

chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs

Currently we release lock right after `maybe_insert_new_entry_in_parts_cache` and then immediately acquire it again immediately. This can result in race condition when newly inserted entry is evicted in between. This is highly unlikely and also won't cause any real issues since we have `else { return Ok(()); }`, so this fix is more of a nice-to-have refactor.

refactor: hold parts lock when creating new entry

---

chain/chunks/src/shards_manager_actor.rs

#5886 was addressed and no longer relevant

doc: remove outdated todo in shards manager actor rustdoc 

---

chain/pool/src/lib.rs

fix a bug in `insert_transaction` where unique_transactions is updated but due to more error checking, the tx might not actually be inserted into the pool.

bugfix: tx pool: unique_transactions could fall out of sync

---

integration-tests/src/env/test_env.rs
integration-tests/src/tests/client/challenges.rs
integration-tests/src/tests/client/doomslug.rs

refactor: don't use mock epoch manager in doomslug and challenges.

---

integration-tests/src/env/nightshade_setup.rs
integration-tests/src/env/test_env_builder.rs
integration-tests/src/tests/tools/state_viewer.rs

refactor: remove MockEpochManager and KVRuntime from test env.

---

runtime/near-vm-runner/src/logic/dependencies.rs
runtime/near-vm-runner/src/logic/logic.rs
runtime/near-vm-runner/src/logic/mocks/mock_external.rs
runtime/near-vm-runner/src/logic/mod.rs
runtime/near-vm-runner/src/logic/tests/storage_read_write.rs
runtime/near-vm-runner/src/tests/ts_contract.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/ext.rs
runtime/runtime/src/state_viewer/mod.rs

refactor: `StorageGetMode` to `External` implementation detail

---

integration-tests/src/env/setup.rs

Note that additionally setup.rs heavily depends on mock epoch manager which we want to remove anyways as part of https://github.com/near/nearcore/issues/10634

refactor: remove dead code from integration-tests setup.rs

---

core/primitives/src/transaction.rs
core/primitives/src/utils.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/tests/apply.rs

Part of work tracked in #13140.

refactor: use validated txs in more places

---

core/store/src/trie/mem/loading.rs
core/store/src/trie/mem/memtrie_update.rs
core/store/src/trie/mod.rs
core/store/src/trie/trie_recording.rs
core/store/src/trie/update.rs
integration-tests/src/tests/client/flat_storage.rs
runtime/runtime/src/ext.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/pipelining.rs
tools/flat-storage/src/commands.rs

At the same time add some documentation so that people past me spend less time breaking their brain.

refactor: rename `KeyLookupMode`s to better reflect their behaviour

---

benchmarks/transactions-generator/src/lib.rs
chain/client/src/lib.rs
chain/client/src/metrics.rs

This will provide somewhat more relevant metric for the single node benchmarks

read the CHUNK_TRANSACTIONS_TOTAL metrics in tx injection benchmark

---

chain/chain/src/garbage_collection.rs
chain/chain/src/metrics.rs

Follow-up to https://github.com/near/nearcore/pull/13153#pullrequestreview-2702352500
I tested metrics reporting with running local node and prometheus.

feat: report state transition data gc metrics

---

runtime/runtime/src/tests/apply.rs

During the development of parallel transaction
processing (#12983), we encountered a bug when multiple transactions from the same account using different keys were included in a single chunk. In this scenario, the account balance was calculated incorrectly because these transactions were processed in parallel.
This PR adds two new tests: one to verify the correct ordering of transaction outcomes and another to validate transactions signed with different keys from
the same account.

runtime: more regression tests for Runtime::apply

---

runtime/runtime/src/lib.rs

The big match statement can make code slightly harder to follow especially when there are failure conditions nested throughout the match statement.
This new way is an equivalent linear/early return way to write the same thing.

refactor: simplify the flow of process_transaction

---

chain/chain/src/runtime/mod.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/verifier.rs

The function commits nothing.
Stacked on top of #13216

refactor: rename commit_charging_for_tx to better reflect its behaviour

---

benchmarks/sharded-bm/README.md
docs/practices/workflows/benchmarks.md

- Adding a section in the book about benchmarking multi-node, multiple-shard networks. 
- Minor improvement to a README linked in the above section.

doc: add brief section about sharded benchmarks

---

.github/workflows/benchmarks.yml
.github/workflows/ci.yml
.github/workflows/ci_nightly.yml
.github/workflows/mac_m1_binary.yml
.github/workflows/master_fuzzer_binaries.yml
.github/workflows/near_crates_publish.yml
.github/workflows/neard_assertion_binary.yml
.github/workflows/neard_nightly_binary.yml
.github/workflows/neard_test_features_binary.yml
.github/workflows/ondemand_fuzzer_binaries.yml

Moving remaining GHA workflows to WarpBuilds

Chore: moving remaining workflows to WarpBuilds

---

chain/indexer/src/streamer/mod.rs

The previous code had a quadratic receipt-outcome matching loop. That's
slow for no reason!
Moving to maps makes that faster and also makes the code more resilient
by no longer assuming 1-1 matching and ordering which was never a guarantee.

indexer: match outcomes to txs/receipts faster and resilient 

---

chain/chain/src/block_processing_utils.rs
chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/genesis.rs
chain/chain/src/store/mod.rs
chain/client/src/client.rs
core/primitives/src/types.rs
core/store/src/adapter/chain_store.rs
integration-tests/src/tests/client/cold_storage.rs
tools/protocol-schema-check/res/protocol_schema.toml

Part of https://github.com/near/nearcore/issues/13231.  This struct is no longer needed as it is only used to store challenges.

cleanup: remove BlockExtra

---

chain/indexer/src/streamer/fetchers.rs
chain/indexer/src/streamer/mod.rs

All the chunks returned by this fetcher are always new chunks.

fix(indexer): remove duplicate check

---

chain/chain/src/block_processing_utils.rs
chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/tests.rs
chain/chain/src/types.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/tests/apply.rs
tools/state-viewer/src/apply_chunk.rs

Part of https://github.com/near/nearcore/issues/13231.

cleanup: remove some more code related to challenges

---

nightly/pytest-sanity.txt

Tracking issue https://github.com/near/nearcore/issues/13296

[nayduck] Disable flaky epoch_sync.py nayduck test

---

tracing/Cargo.toml
tracing/Dockerfile
tracing/docker-compose.yml

Can we find some way to update rust everywhere? :)

chore: rust 1.86 in tracing server

---

benchmarks/sharded-bm/bench.sh

chore: bench fix binary upload

---

chain/jsonrpc/src/lib.rs

Before:
```
> GET /debug HTTP/1.1
> Host: localhost:3030
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 3113
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
< access-control-expose-headers: host, accept, user-agent
< access-control-allow-credentials: true
< date: Sun, 13 Apr 2025 21:28:22 GMT
< 
```
After:
```
*   Trying 127.0.0.1:3030...
* Connected to localhost (127.0.0.1) port 3030 (#0)
> GET /debug HTTP/1.1
> Host: localhost:3030
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< content-length: 0
< access-control-allow-credentials: true
< access-control-expose-headers: user-agent, accept, host
< vary: Origin, Access-Control-Request-Method, …
```

fix(http_server): return 404 when debug RPC is off

---

runtime/runtime/src/lib.rs
runtime/runtime/src/types.rs

driving https://github.com/near/nearcore/pull/13357 to completion

runtime: parallel transaction processing

---

core/store/src/trie/update.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/state_viewer/mod.rs
test-loop-tests/src/tests/global_contracts.rs

This PR fixes view function calls and view code RPC requests for accounts using global contracts.
Part of #12639.

fix: global contract RPC calls

---

chain/epoch-manager/README.md

doc: update link

---

chain/client/src/client_actor.rs
chain/client/src/info.rs
chain/client/src/metrics.rs
core/primitives/src/version.rs
integration-tests/src/env/setup.rs
test-loop-tests/src/examples/simple.rs
test-loop-tests/src/setup/builder.rs

Closes: https://github.com/near/nearcore/issues/12099

feat(chain/client,core/primitives): per chain_id upgrade schedule

---

core/primitives/src/epoch_manager.rs

First commit is the fix.
Second commit is a refactoring.

fix(epoch-config): Do not load epoch configs for unknown protocol versions

---

CHANGELOG.md

...to reflect receipt id computation change.

chore(2.6): receipt id note

---

pytest/tests/sanity/upgradable.py

This test was flaking in two different ways:
- `wait_epoch` waits for one particular node to reach the new epoch. Then, we immediately call `assert_protocol_version` and check the protocol version on all of the nodes. Another node may be in the process of transitioning to the new epoch and need a little more time.
- `num_expected_endorsements` and `num_produced_endorsements` may not update synchronously. Again, allowing a little time for them to match resolves the issue.
In my local setup without the fixes, I observed the test flake in 2 of 3 runs. After these changes it ran successfully 5/5 times.

fix flaky pytest upgradable.py

---

core/primitives/src/errors.rs

ref: 
https://github.com/near/nearcore/blob/c49288bd29a72ab979a0a6fac261ae3f347e858d/runtime/runtime/src/verifier.rs#L158-L164

fix the comment on InvalidNonce error

---

benchmarks/sharded-bm/bench.sh

Acting on https://github.com/near/nearcore/pull/13473#discussion_r2073836580
We don't need firefox-profiler for now, so this file raises more questions than helps.

chore: disable firefox profile by default

---

tools/debug-ui/src/App.tsx
tools/debug-ui/src/ChainAndChunkInfoView.tsx
tools/debug-ui/src/EpochInfoView.tsx
tools/debug-ui/src/EpochValidatorsView.scss
tools/debug-ui/src/EpochValidatorsView.tsx
tools/debug-ui/src/LatestBlocksView.tsx
tools/debug-ui/src/NetworkInfoView.tsx
tools/debug-ui/src/RecentEpochsView.tsx
tools/debug-ui/src/api.tsx
tools/debug-ui/src/entity_debug/fields.tsx
tools/debug-ui/src/index.tsx
tools/debug-ui/src/log_visualizer/LogVisualizer.tsx
tools/debug-ui/src/log_visualizer/arrows.ts
tools/debug-ui/src/log_visualizer/events.ts
tools/debug-ui/src/log_visualizer/layout.ts

v7 brings two main changes:
* Navigation needs to go to "../something" instead of "something", otherwise it just appends another part of the path.
* The "*" path no longer matches the case of no route; instead, that is a separate case called "index". So I needed to add move those index cases to the parent components.
Also fix lint. These aren't caught by the CI...

[Debug UI] Fix routing due to react-router v7 upgrade, and fix the lint errors.

---

chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/network/src/peer_manager/network_state/tier1.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/types.rs
integration-tests/src/env/setup.rs
test-loop-tests/src/utils/peer_manager_actor.rs

This is a version of https://github.com/near/nearcore/pull/13527 rebased on top of 2.6.2.
There were some merge conflicts, but I was able to resolve them.

2.6.3: Include Chunk Validators in Tier1

---

nightly/pytest-sanity.txt

Tracking issue https://github.com/near/nearcore/issues/13551

[nayduck] Disable flaky gc_sync_after_sync.py nayduck test

---

.github/workflows/ci.yml

Tracking issue https://github.com/near/nearcore/issues/13556

[ci] Disable flaky upgradable pytest

---

benchmarks/sharded-bm/README.md
benchmarks/sharded-bm/cases/forknet/realistic_20_cp_1_rpc_20_shard/params.json

Update some defaults in readme and params.json to make it easier to start benchmarks with the correct configuration.

chore: update defaults in sharded-bm

---

CHANGELOG.md
core/primitives-core/src/version.rs
core/primitives/res/epoch_configs/mainnet/78.json
core/primitives/res/epoch_configs/testnet/78.json
pytest/tests/mocknet/mirror.py
tools/fork-network/src/cli.rs

Cherry-picks:
- https://github.com/near/nearcore/pull/13629
- https://github.com/near/nearcore/pull/13635
- https://github.com/near/nearcore/pull/13636
- https://github.com/near/nearcore/pull/13609

2.7.0 cherry-picks

---

chain/chain/src/garbage_collection.rs
core/store/src/columns.rs
core/store/src/db/rocksdb.rs
integration-tests/src/tests/client/cold_storage.rs

BlockExtra is no longer used since we got rid of challenges

[cleanup] Deprecate DBCol::BlockExtra

---

chain/jsonrpc/openapi/openapi.json

fix(ci) - fix openapi

---

core/primitives/src/epoch_manager.rs

@staffik Plz cherry-pick for 2.7

Fix epoch config include for protocol version 78

---

chain/chain/src/garbage_collection.rs

Exactly what @Trisfald proposed, lgtm: [#nearone/private > 2.7 release testing @ 💬](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/2.2E7.20release.20testing/near/523911042)
I think we were protected from that before, but recent changes removed that protection:
- Only run it after new resharding: https://github.com/near/nearcore/pull/13680/files#diff-770f5411fa2d9f774f59424194e326fb2d9722e2fd0c011933614325b6ac91eaL1138
- Assert that the old mapping does not exist: https://github.com/near/nearcore/pull/13693/files#diff-770f5411fa2d9f774f59424194e326fb2d9722e2fd0c011933614325b6ac91eaL1167

fix(resharding): Do not delete parent shard state if it is referenced

---

chain/chain/src/garbage_collection.rs

https://github.com/near/nearcore/pull/13680

2.7.0 cherry pick 3

---

chain/chain/src/garbage_collection.rs

Cherry-pick https://github.com/near/nearcore/pull/13693

[resharding] Fix check shard_uid_mapping (#13693)

---

core/primitives/src/epoch_manager.rs

https://github.com/near/nearcore/pull/13713

Fix epoch config include for protocol version 78 (#13713)

---

chain/chain/src/garbage_collection.rs

https://github.com/near/nearcore/pull/13708

fix(resharding): Do not delete parent shard state if it is referenced (#13708)

---

chain/chain/src/resharding/flat_storage_resharder.rs
chain/chain/src/resharding/trie_state_resharder.rs

https://github.com/near/nearcore/pull/13751

fix - Trie resharding resume when children memtries don't exist anymore (#13751)

---

chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs

The `decode_witness` span was a bit wrong - it covered only decoding witness parts, but didn't include decompressing and deserializing.
Change `decode_witness` to `decode_witness_parts` and add `decode_state_witness` span which covers decompression and deserialization. It's not really possible to have separate spans for decompressing and deserializing because it's done using streaming.
Also add `encoded_witness_size` which tells us the compressed size of a witness. Now we'll be able to determine what was the compressed and uncompressed witness size and part sizes using traces alone.

feat(tracing) - better witness distribution spans

---

pytest/tests/mocknet/docs/sharded_bm.md
pytest/tests/mocknet/helpers/get-profile.sh
pytest/tests/mocknet/local_test_node.py
pytest/tests/mocknet/mirror.py
pytest/tests/mocknet/node_handle.py
pytest/tests/mocknet/remote_node.py
pytest/tests/mocknet/sharded_bm.py

Suggestions from here: https://github.com/near/nearcore/pull/13712#pullrequestreview-2930991198

benchmarks(cleanup): review suggestions for get-profiles

---

chain/chain/src/resharding/manager.rs
test-loop-tests/src/tests/resharding_v3.rs
test-loop-tests/src/utils/resharding.rs

Do not perform resharding at all if the node does not track any children shard in next epoch.
Added:
Fix
Test

fix (master) - skip resharding when children are not tracked in next epoch

---

chain/network/src/peer/peer_actor.rs

Seems leftover cleanup from https://github.com/near/nearcore/pull/7582/files

nit: send_message_or_log -> send_message

---

Cargo.lock
Cargo.toml
core/primitives/src/version.rs

Prepare 2.7.0-rc.1 release
* Set neard version to `2.7.0-rc.1`
* Set crates version to `0.31.0-rc.1`
* Set voting date to Wednesday 2025-07-02 03:00 UTC - protocol upgrade will happen 7-14 hours later, on 2025-07-02 between 10:00 and 17:00 UTC.
According to our estimation tool the upgrade will happen at 2025-07-02 13:00 UTC
```
$ python3 debug_scripts/estimate_epoch_start_time.py  --url http://34.13.153.53:3030 --num_past_epochs 10 --num_future_epochs 25
Epoch -1: 07 hours, 14 minutes
Epoch -2: 07 hours, 16 minutes
Epoch -3: 07 hours, 16 minutes
Epoch -4: 07 hours, 14 minutes
Epoch -5: 07 hours, 16 minutes
Epoch -6: 07 hours, 16 minutes
Epoch -7: 07 hours, 16 minutes
Epoch -8: 07 hours, 18 minutes
Epoch -9: 07 hours, 17 minutes
Epoch -10: 07 hours, 15 minutes
Exponential weighted average …
```

Prepare 2.7.0-rc.1

---

core/chain-configs/src/client_config.rs
nearcore/src/config.rs

Updating the default as per discussion on [zulip](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/garbage.20collection.20stuck/near/526149978). 
If approving without comments please merge.

update garbage collection default config

---

chain/client/src/gc_actor.rs

GC ideally should never fail, however it's not critical for the working of a validator node.
Currently we are only tracing the error but it makes sense to add a debug_assert on GC failures for better testing.

[test] Add debug assert to gc_actor

---

chain/jsonrpc/openapi/openapi.json

should be updated to match https://github.com/near/nearcore/pull/13825

nit: patch openapi.json with new default

---

chain/chain/src/store/utils.rs
chain/client/src/sync/header.rs
chain/client/src/view_client_actor.rs
tools/mock-node/src/lib.rs

https://github.com/near/nearcore/pull/13814

fix(header_sync): Use ordinals for header sync (#13814)

---

chain/jsonrpc/res/congestion_control.js
chain/jsonrpc/res/last_blocks.js
tools/debug-ui/src/LatestBlocksView.tsx

Quick fix for Debug UI indexing problems. Also ordering shards by ID.

fix - shard uid indexing bugs in debug ui

---

chain/chain/src/garbage_collection.rs

Added logs would have been helpful when debugging the last GC issue we had with our mainnet node, see #13857 for more details.

refactor: add more GC debug logs

---

.github/workflows/ci.yml
Justfile

I can't run a GH action on my local machine.

ci: add a cspell justfile command and use that in CI

---

chain/client/src/state_request_actor.rs

Flatten the code structure by early returns and moved some code to helper functions.

refactor(state_sync) - refactor the state request actor a bit

---

chain/chain/src/store/mod.rs

nit: remove unused ChainStoreCacheUpdate::block_hash_per_height

---

pytest/lib/cluster.py
pytest/tests/mocknet/helpers/neard_runner.py
pytest/tests/mocknet/release_scenarios/__init__.py
pytest/tests/mocknet/remote_node.py

- remove one more occurrence of `legacy_records`
- fix neard-runner logs file. ( @ssavenko-near do you have a strong preference here? )
- improve test scenario detection logic

chore: tidy up forknet stack

---

tools/fork-network/src/cli.rs

Add option to use existing protocol version for cases where we want to snapshot mainnet before it was upgraded.

feat(forknet): use shard layout from given protocol version

---

runtime/near-vm-runner/src/wasmtime_runner.rs

This PR replaces `thread_local`s with an `Arc<RefCell<Option<Caller>>>`.  Instead of storing as a `thread_local`, we now access the caller as a property of the Wasm memory table.
This better suits the use of the caller with `wasmtime`'s API but doesn't introduce any functional changes.  Now that we don't rely on the thread_local variable, we can begin optimizations for multithreaded contexts.
As a nice side effect, this also reduced the number of lexical `unsafe` lines in the codebase.

fix: replace thread_local in wasmtime-runner

---

pytest/lib/cluster.py

Make it resilient to sporadic failures

feat(forknet): add retry to GCloud API

---

chain/chain/src/tests/simple_chain.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
core/primitives-core/src/version.rs
core/primitives/res/epoch_configs/mainnet/80.json
core/primitives/res/epoch_configs/testnet/143.json
core/primitives/res/epoch_configs/testnet/80.json
core/primitives/src/epoch_manager.rs

Cherry-picked [9afbaa1](https://github.com/near/nearcore/commit/9afbaa1f9a15bf6b1cb8fcc413abe1d2b8052296).

feat: increase validators number to 500 (#14033)

---

Cargo.lock
runtime/runtime/Cargo.toml

Seems unintentionally added here: https://github.com/near/nearcore/pull/14066/files

chore(runtime/Cargo.toml): remove dependency unintentionally added

---

Cargo.lock
Cargo.toml
Makefile

cherry pick https://github.com/near/nearcore/pull/14120

fix: vendor and statically link openssl (#14120)

---

chain/indexer/src/streamer/mod.rs

This hack is for blocks around height 47317863. That is more than 3 years old, so that protocol version is no longer supported by neard since we adopted limited replayability. So we can safely remove that code from indexer.
Part of #14109.

refactor: remove indexer restored receipts hack

---

chain/epoch-manager/src/lib.rs

One of issues we've hit during testing [#releases/2.8 > 2.8 @ 💬](https://near.zulipchat.com/#narrow/channel/522473-releases.2F2.2E8/topic/2.2E8/near/537292816).
There are spontaneous stake tx from mainnet validators which we don't clean up properly; for now we ignore them by multiplying all stakes by 10**5. This, however, brings token supply closer to `u128::MAX`. This, in turn, breaks all formulas of kind `stake * a / b` where `a / b <= 1`.
We could try `stake / b * a`, but I guess using `U256` is safer and shouldn't really slow down the chain.

fix: don't overflow when token supply is close to u128::MAX

---

runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests/test_builder.rs

The test runner has been skipping all tests for the currently enabled runtime :facepalm:

runtime: actually test near-vm-2

---

chain/client/src/chunk_producer.rs

fixing job https://github.com/near/nearcore/actions/runs/17546657590/job/49829563234
The test `Build and publish ARM Linux Ubuntu neard binary` has to be run to check if more fixes needed

Fix unused type Gas

---

chain/indexer/README.md

Update the config links and tracked shards config.

chore(indexer): update README

---

CHANGELOG.md

changelog(resharding) - described the archival data loss recovery in changelog (#14224)

---

core/store/src/trie/update.rs

Seems the expectation would be that contains_key returns false if get returns None.

nit(TrieUpdate): make contains_key consistent with get for prospective

---

nearcore/src/migrations.rs

This likely was forgotten in https://github.com/near/nearcore/pull/9033

fix: remove dead migrate_30_to_31 code.

---

chain/chain/src/store_validator/validate.rs
chain/client/src/archive/cloud_archival_actor.rs
chain/client/src/view_client_actor.rs
core/chain-configs/src/client_config.rs
nearcore/src/entity_debug.rs
nearcore/src/lib.rs
test-loop-tests/src/setup/setup.rs
test-loop-tests/src/tests/cloud_archival.rs
test-loop-tests/src/utils/cloud_archival.rs
test-loop-tests/src/utils/mod.rs
test-loop-tests/src/utils/node.rs
tools/cold-store/src/cli.rs
tools/state-viewer/src/scan_db.rs

This PR contains a set of refactoring changes extracted from [#14322](https://github.com/near/nearcore/pull/14322) in order to reduce its size and make review easier.
It is not intended to introduce any functional changes.

chore(cloud_archival): Refactor actor and tests

---

chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/tests.rs
chain/chain/src/runtime/trie_update_wrapper.rs
chain/chain/src/types.rs
chain/client/src/chunk_producer.rs
core/store/src/trie/update.rs

Part of https://github.com/near/nearcore/pull/14321

feat(early_prepare) 2/n: prepare_transactions_extra

---

runtime/runtime/src/deterministic_account_id.rs

We must charge for the key and the extra amount
per record, too. It has to be exactly the same storage usage as it would be when inserting with `storage_write`.
Tests checking this case are coming with a follow up PR that adds integration tests.

fix: storage usage for det-accounts

---

chain/chain/src/chain.rs
chain/chain/src/store/mod.rs
chain/chain/src/store/utils.rs

Part of https://github.com/near/nearcore/pull/14321

feat(early_prepare) 3/n: Early prepare validity period check
