pytest/lib/cluster.py
pytest/tests/sanity/repro_2916.py

This is due to a change in the code that, when a request could only find some of the parts or receipts that were requested, instead of not responding at all, would now respond with whatever was found. This caused the nayduck test to fail because it was checking the existence of a response. We now check exactly what the response was, and make the test much clearer about what it's asserting.
Also, I noticed that the test framework assumes that the cargo target dir is "./target", and added support to honor the CARGO_TARGET_DIR env var if specified.

Fix Nayduck test repro_2916.py.

---

chain/jsonrpc-primitives/src/message.rs
chain/jsonrpc/client/src/lib.rs
chain/jsonrpc/src/api/blocks.rs
chain/jsonrpc/src/api/changes.rs
chain/jsonrpc/src/api/chunks.rs
chain/jsonrpc/src/api/config.rs
chain/jsonrpc/src/api/gas_price.rs
chain/jsonrpc/src/api/light_client.rs
chain/jsonrpc/src/api/maintenance.rs
chain/jsonrpc/src/api/mod.rs
chain/jsonrpc/src/api/query.rs
chain/jsonrpc/src/api/receipts.rs
chain/jsonrpc/src/api/sandbox.rs
chain/jsonrpc/src/api/split_storage.rs
chain/jsonrpc/src/api/transactions.rs
chain/jsonrpc/src/api/validator.rs
chain/jsonrpc/src/lib.rs

There’s really no need to distinguish lack of params from a null
params.  In all existing cases both of those situations are treated
the same way and it’s unlikely that in the future there would be
a need to treat those two differently.  Meanwhile, assuming missing
params is equivalent to null value simplifies the code slightly.

jsonrpc: simplify params representation

---

nightly/pytest-sanity.txt

#8417 fixes these tests, but nayduck doesn't build `genesis-populate` with nightly features, so disabling again until  https://github.com/near/nayduck/pull/38 is merged.

fix: temporary disable state sync nightly nayduck tests

---

runtime/runtime/tests/runtime_group_tools/mod.rs

Replaces `is_emtpy` with `is_empty`.

refactor: Fix typo in the function name

---

core/primitives/src/types.rs
core/store/src/trie/trie_tests.rs
runtime/near-vm-logic/src/logic.rs

Part of #8210.
This potentially changes runtime behaviour to return `Err` instead of panicking (see [this comment](https://github.com/near/nearcore/pull/8370#pullrequestreview-1265508077)). I've discussed this with @jakmeier and returning `InconsistentStateError` will effectively result in panic later.
`saturating_sub` was considered as an alternative, but underflow when subtracting trie nodes count means that we have some kind of bug in our logic. Since we use those count diffs when to calculate gas, it is better to panic instead of hiding the issue by saturating the result to 0.

refactor: replace TrieNodesCount sub with checked_sub

---

tools/amend-genesis/src/lib.rs

when computing genesis state roots, neard expects to find code records only after seeing the account record: https://github.com/near/nearcore/blob/df429f47491f67cdab7e352d0d64d6939fcaebc2/runtime/runtime/src/genesis.rs#L137 With the current implementation, the amend-genesis command will write account records after code records for accounts we're modifying. This leads to failures in mocknet tests, so this PR fixes that

fix(amend-genesis): write account records before code records

---

core/primitives/src/runtime/parameter_table.rs

This PR implements `TryFrom` for `ParameterValue` for a few types that we need while working with `ParameterTable`.
This helps to get rid of a lot of duplication in `get_*` methods, but I wasn't able to get rid of `get_number` that is already generic as it was violating Rust foreign trait rules (see commented out code, the exact error is [1]). Any advice there?
I also feel that `TryFrom` implementations have a bit more duplication than `as_*` methods that we had before. Particularly in re-defining the error type each time and constructing very similar error messages. Any advice here would be appreciated.
[1]
```
error[E0210]: type parameter `T` must be covered by another type when it appears before the first local type (`ParameterValue`)
--> …
```

refactor: Implement TryFrom for ParameterValue

---

chain/jsonrpc-primitives/src/types/client_config.rs
core/chain-configs/src/client_config.rs
core/chain-configs/src/updateable_config.rs

When we enable dynamically config, we use a MutableConfigValue type to represent the mutable fields. 
Only value field is valuable to end users. This PR aims to only show MutableConfigValue.value to users and hide the other 2 fields.
For example, if you navigate to /debug/client_config, and look at the field `expected_shutdown`, this PR should show 
`"expected_shutdown": "null"`
instead of 
`"expected_shutdown: "expected_shutdown":{"value":null,"field_name":"expected_shutdown","last_update":"2023-01-23T19:26:43.817152Z"}`

feat: better `Serializer` for `MutableConfigValue`

---

.buildkite/pipeline.yml

We have git, we can always look up the stuff if we need it in the future.

refactor: remove some commented out ancient rules

---

docs/architecture/how/cross-shard.md

A few improvements to get the documentation up-to-date:
- Fix broken link to a transfer transaction (presumably it got broken because it was pointing to testnet)
- Add a link to article that described fees paid during conversion from Transaction to Receipt

docs: Update Cross shard transactions deep dive

---

core/store/src/cold_storage.rs
core/store/src/metrics.rs
integration-tests/src/tests/client/cold_storage.rs

Adding height of the head of the cold storage to the metrics page.
It is updated when we call for update_cold_head.
Technically, it can be absent from metrics with this implementation in these cases:
1. During initial migration, but it is useless during that time and is not set in the storage at all.
2. If copying loop is broken during normal run of the node. I'm okay with that kind of additional signal that something is wrong.
3. If node does not have a cold storage. We don't need it in that case anyway. 
@nikurt, making you a reviewer as an expert on metrics (at least from my point of view).

adding cold_head_height metric

---

tools/mirror/src/chain_tracker.rs
tools/mirror/src/lib.rs

receipts in a chunk might have been delayed, but right now we're
assuming that they were applied. Instead we should be looking at the
outcomes in each block to determine what was applied. This makes things
simpler actually, because there is only one place where we need to
check if access keys are updated, so we can delete some old code.
In this PR we will store every tx and subsequent receipt that we
generate in the DB. We could just store the ones that update access
keys, but in the future it might be useful if we store all of
them. Currently there's a problem where staking pool contract calls
result in unwanted validator stakes when running this with mainnet
traffic. So one way we could fix that is by unstaking whenever we see
a stake action show up in the target chain. But we would …

fix(mirror): dont assume receipts are always executed

---

Cargo.lock
core/store/src/test_utils.rs
neard/Cargo.toml
tools/state-viewer/Cargo.toml
tools/state-viewer/README.md
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/contract_accounts.rs

List account names with contracts deployed and additional 
information about the contracts.
See the state-viewer README for docs and examples.
This has been used to produce reports in #8427

feat(state-viewer): list actions invoked by each contract

---

core/primitives-core/src/profile.rs

Given that the profiles already store `Gas` inside it seemed logical to also accept `Gas` in the public interface instead of `u64` (the callers seem to be using `Gas` already).
@akhi3030 , Is there anything else I should be doing in this refactoring to simplify the migration to strongly-typed Gas that you're working on?

refactor: Use `Gas` instead of `u64` in ProfileDataV3

---

docs/architecture/gas/gas_profile.md

The old command was returning an error because transaction was no longer cached in the active validating(?) nodes. So adding `nodeUrl` to query the archive node as this is most likely what the user would want to do in this case anyway.
Also separate the code block in two parts to make it easier to copy.

docs: Update command to retrieve transaction gas profile

---

nightly/pytest-sanity.txt

Was disabled in https://github.com/near/nearcore/pull/8463. https://github.com/near/nayduck/pull/38 and https://github.com/near/nayduck/pull/41 are deployed now, so we can enable those tests again.

fix: re-enable nayduck nightly state_sync_massive tests

---

chain/client-primitives/src/types.rs
chain/client/src/view_client.rs
chain/jsonrpc-primitives/src/types/split_storage.rs
core/primitives/src/views.rs
core/store/src/lib.rs
core/store/src/metadata.rs
core/store/src/migrations.rs
core/store/src/opener.rs
nearcore/src/lib.rs
nearcore/src/migrations.rs
pytest/lib/branches.py
pytest/lib/cluster.py
pytest/tests/sanity/split_storage.py

Currently the opener expects both stores to exist or not exist. The case when hot store exists and should be openened and cold store doesn't exist and should be created is not supported. 
This PR addresses this issue - allowing opening hot and creating cold - as well as refactors some of the opener code. 
The overaching principle here is that we can treat hot and cold storages separately and just open/create each and only combine them into NodeStorage as the last step. 
Some side effects of this refactoring are:
- That the opener will apply migrations to both store independently. Previously only the hot storage had migrations applied to it. It's not what we initially discussed but I think it doesn't hurt. 
- We don't need to do as many check on the kind and version - instead we just …

feat: allow creating cold store when hot store exists

---

chain/client/src/test_utils.rs
chain/jsonrpc/res/rpc_errors_schema.json
core/primitives/src/delegate_action.rs
core/primitives/src/errors.rs
core/primitives/src/lib.rs
core/primitives/src/transaction.rs
core/primitives/src/views.rs
integration-tests/src/tests/client/features/delegate_action.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/verifier.rs

Reviewer note: You may want to review this commit by commit,
as I also moved code between modules.
Background: I first added an integration test for
`DelegateActionCantContainNestedOne`.
It had the node panic with an "InvalidChunk" message.
So I started thinking. Since we define recursive delegate actions
to be syntactically wrong (parser error) it really is an invalid chunk
when it includes such a transaction. I could only construct it for the
test while bypassing borsh deserialization. Such a test doesn't really
make sense, because then I violate type invariants and in such a case
it's entirely possible that the node crashes.
My conclusion is, we must forbid the creation of an invalid
`NonDelegateAction`. I changed the code to make it obvious that
there is no violating code, using …

feat: type guarantees for NonDelegateAction

---

core/store/src/cold_storage.rs
core/store/src/metrics.rs
nearcore/src/cold_storage.rs
nearcore/src/metrics.rs

added two new metrics for the cold store:
- COLD_COPY_DURATION that is a histogram that tracks the time to copy one height from hot to cold
- COLD_STORE_COPY_RESULT that is a counter vector that tracks counters for each possible result of cold store copy (error, no blocks copied, latest block copied, other block copied) 
From the metrics page:
```
near_cold_store_copy_result{copy_result="latest_block_copied"} 246
near_cold_store_copy_result{copy_result="no_block_copied"} 1
near_cold_store_copy_result{copy_result="other_block_copied"} 175
near_cold_copy_duration_bucket{le="0.005"} 358
near_cold_copy_duration_bucket{le="0.01"} 413
near_cold_copy_duration_bucket{le="0.025"} 421
near_cold_copy_duration_bucket{le="0.05"} 421
near_cold_copy_duration_bucket{le="0.1"} 421 …
```

feat: adding metrics for the cold store loop

---

.github/workflows/mac_binary.yml
.github/workflows/mac_m1_binary.yml

tldr - regexes are hard
The mac_binary.yml configures that macbook binaries should be uploaded to S3 for any commit pushed to master as well as any tag matching the given pattern. Unforunately the pattern is invalid and it doesn't capture our release tags and so we never upload mac binaries. This breaks a few things including `nearup localnet` and `db_migration.py` pytest.
I have no clue how to test this PR so I'm looking for suggestions. It's broken anyway so I don't think I'll make it any worse though so merging without a test would be acceptable too. 
references:
- [6426](https://github.com/near/nearcore/pull/6426/files#r831461185)  the PR that introduced the tag trigger and discussion about whether the right pattern is `.*` or `*` 
- …

fix: fixed the mac binary release tag pattern

---

core/primitives/src/test_utils.rs
integration-tests/Cargo.toml
integration-tests/src/node/runtime_node.rs
integration-tests/src/tests/client/features/delegate_action.rs
integration-tests/src/tests/standard_cases/mod.rs
integration-tests/src/user/mod.rs
test-utils/testlib/Cargo.toml
test-utils/testlib/src/fees_utils.rs
test-utils/testlib/src/runtime_utils.rs

1. Extend the test utilities to make meta transaction tests easy to add.
2. Add two tests as an example. a) NEAR token transfer b) simple function call
I will cover more cases in future PRs. This is to establish the framework:
- `fn meta_tx` in `trait User`
- Checker function specific to meta transactions
- Provide helpers to do tricky gas checks
The 2 test cases show that it works as intended.

test: first rust meta tx integration tests

---

Cargo.lock
core/async/Cargo.toml
core/async/README.md
core/async/src/actix.rs
core/async/src/examples/sum_numbers.rs
core/async/src/examples/sum_numbers_test.rs
core/async/src/lib.rs
core/async/src/messaging.rs
core/async/src/test_loop.rs

See README.md changes for details.
This is intended to replace:
- `MsgRecipient` (which was similar to a combination of Sender and AsyncSender, but is Actix-specific)
- `NetworkRecipient` (which is basically LateBoundSender)
- adapters that are trait combinations (e.g. PeerManagerAdapter used to be defined as a trait that requires two MsgRecipient supertraits, but now would be a struct of Senders - making it much more flexible, e.g. we can extract one sender out of the combination)
- Calling `.with_span_context` everywhere (now we just need to call it once during construction of the Senders)
- MockXXXAdapters (with a generic Sender implementation)
- NoOpXXXAdapters (with Sender::noop())
Note that Sender<T> and AsyncSender<T> are structs, so no more having to spell out Arc<dyn …

[TestLoop] (2/n) Introduce Sender<T> and AsyncSender<T>.

---

Cargo.lock
Cargo.toml
chain/network/src/network_protocol/borsh.rs
core/account-id/src/borsh.rs
core/crypto/src/signature.rs
core/crypto/src/traits.rs
core/primitives-core/src/account.rs
core/primitives-core/src/hash.rs
core/primitives-core/src/profile.rs
core/primitives-core/src/profile/profile_v2.rs
core/primitives/src/delegate_action.rs
core/primitives/src/time.rs
deny.toml
tools/speedy_sync/Cargo.toml

Reverts b8196b1aa735b5f9ea1c53c1a248fdd4a4bf54bd due to fuzzer-found OOM issue in our code with a more recent borsh.
With a more recent borsh the fuzzer finds OOM issues in our account-id deserialization code. To repro, run with a file like this: (unfortunately github doesn’t allow random file uploads)
```
$ cd core/account-id/fuzz
$ hexdump artifacts/borsh/clusterfuzz-testcase-minimized-borsh-5679095853613056 
0000000 fe00 ffff                              
0000004
$ cargo +nightly fuzz run borsh artifacts/borsh/clusterfuzz-testcase-minimized-borsh-5679095853613056  -- -rss_limit_mb=2560 -timeout=60 -runs=100
```
This attempts a ~4G RAM allocation for a 4B input. Unfortunately I don’t think we can easily add a unit test for this, as it’d rely on limiting the RAM available to the test. …

Revert borsh update

---

tools/debug-ui/src/ConnectionStorageView.scss
tools/debug-ui/src/ConnectionStorageView.tsx
tools/debug-ui/src/CurrentPeersView.tsx
tools/debug-ui/src/NetworkInfoView.tsx
tools/debug-ui/src/PeerStorageView.tsx
tools/debug-ui/src/api.tsx
tools/debug-ui/src/utils.js

Followup to https://github.com/near/nearcore/pull/8337:

[Debug UI] Update the migrated NetworkInfoView

---

tools/debug-ui/src/CurrentPeersView.tsx
tools/debug-ui/src/NetworkInfoView.tsx
tools/debug-ui/src/Tier1View.scss
tools/debug-ui/src/Tier1View.tsx
tools/debug-ui/src/api.tsx
tools/debug-ui/src/utils.js

Adds the TIER1 debug page to the new project and moves some code shared with the TIER2 page (CurrentPeersView) into utils.js.
Closes https://github.com/near/nearcore/issues/8354
Old:
New:

[Debug UI] Migrate TIER1 debug page

---

chain/network/src/config.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/tests/tier2.rs
neard/src/cli.rs

This is a follow-up to https://github.com/near/nearcore/pull/8318, in which reliable peers are persisted to storage in the ConnectionStore.
A new boolean flag `--connect-to-reliable-peers-on-startup` is added to neard. If set to `true`, the node will attempt to reconnect to known reliable peers from storage upon starting up. The default value is `true`.
Note that setting the flag to `false` skips reconnection, but does not purge the reliable peers in storage.
Closes https://github.com/near/nearcore/issues/8580

Add a flag to neard configuring reconnection to reliable peers on startup

---

tools/debug-ui/package-lock.json
tools/debug-ui/package.json
tools/debug-ui/src/App.tsx
tools/debug-ui/src/EpochInfoView.scss
tools/debug-ui/src/EpochInfoView.tsx
tools/debug-ui/src/EpochShardsView.scss
tools/debug-ui/src/EpochShardsView.tsx
tools/debug-ui/src/EpochValidatorsView.scss
tools/debug-ui/src/EpochValidatorsView.tsx
tools/debug-ui/src/RecentEpochsView.scss
tools/debug-ui/src/RecentEpochsView.tsx
tools/debug-ui/src/api.tsx
tools/debug-ui/src/index.tsx
tools/debug-ui/src/utils.tsx

I've turned the many tables on that page to three tabs: recent epochs, validators, and shard sizes:
**Recent Epochs**
**Validators** (this is all combined into one table)
Kickout reason:
**Shard Sizes** (this table is transposed from the original, so that the bars can more easily be compared visually, and also this will look much better with 100 shards)
(includes changes from the base PR for now, will be moved out when that's merged)

[Debug UI] Migrate Epoch Info page to new UI

---

chain/client/src/test_utils.rs
core/primitives/src/delegate_action.rs
core/primitives/src/lib.rs
core/primitives/src/signable_message.rs
integration-tests/src/user/mod.rs
pytest/lib/transaction.py
runtime/runtime/src/actions.rs

This is a necessary change to the meta transaction signature scheme to
address security related concerns with the original proposal.
Meta transactions introduce `DelegateAction` and 
`SignedDelegateAction` where the signature key is an account key.
Transactions are also signed by account keys. 
We don't want to have the possibility that the borsh serialization of a 
`Transaction` and a `DelegateAction` end up with the same binary 
representation. In that case it would be indistinguishable whether the 
account owner signed the Transaction or the DelegateAction, which 
opens the door to various security vulnerabilities.
There is the draft NEP-461 to solve this in a general way. To push
forward with meta transaction, we will use that proposed schema.
Regardless of whether the standard gets …

feat: signable message prefix for meta tx

---

core/primitives/res/runtime_configs/parameters.snap
core/primitives/res/runtime_configs/parameters.yaml

for estimation data, please refer to
https://github.com/near/nearcore/issues/8114#issuecomment-1435304213

feat: update delegate action gas cost

---

Cargo.toml

Update the cargo workspace version to trigger a new tag and
release for all crates. More info on this process here: 
https://github.com/near/nearcore/blob/f7a6bd472ceaff270ed913a30dc39cd714195553/docs/misc/README.md
The main motivation for the release it to make meta transaction related
structs (`DelegateAction`, `SignedDelegateAction` and a few others) 
accessible to downstream projects, such as near-cli or near-lake.
The changes also includes a new variant to `Action`, which is not marked
as `non_exhaustive`, therefore this alone is a breaking change for code
that exhaustively matched an action.
I don't know of any other breaking changes but most likely we have
some in the last ~5 months of changes across all the published crates.

chore: bump crates version to 0.16.0

---

Cargo.lock
Cargo.toml
deny.toml

See https://github.com/near/nearcore/issues/8604

fix: crates.io compatible stdx dependency

---

chain/jsonrpc-primitives/src/types/status.rs

Building this was just broken, I don't know for how long.
It was now caught when publishing crates, because you can't publish
with compilation errors.
error:
```
error[E0433]: failed to resolve: use of undeclared crate or module `near_client_primitives`
--> chain/jsonrpc-primitives/src/types/status.rs:1:5
|
1 | use near_client_primitives::debug::{
|     ^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `near_client_primitives`
```

fix: JSON RPC Primitives with default features

---

chain/jsonrpc/src/api/blocks.rs
chain/jsonrpc/src/api/changes.rs
chain/jsonrpc/src/api/chunks.rs
chain/jsonrpc/src/api/config.rs
chain/jsonrpc/src/api/gas_price.rs
chain/jsonrpc/src/api/light_client.rs
chain/jsonrpc/src/api/maintenance.rs
chain/jsonrpc/src/api/mod.rs
chain/jsonrpc/src/api/query.rs
chain/jsonrpc/src/api/receipts.rs
chain/jsonrpc/src/api/sandbox.rs
chain/jsonrpc/src/api/split_storage.rs
chain/jsonrpc/src/api/transactions.rs
chain/jsonrpc/src/api/validator.rs
chain/jsonrpc/src/lib.rs
core/primitives-core/src/serialize.rs

Some JSON RPC requests support a legacy parameters format where
instead of a structured object the `params` field is an array.
Currently this is handled by first trying to parse parameters value
into a tuple and only if that fails it’s then parsed as a request
type.  Unfortunately, this introduces a clone of the value.
With this commit, parameters parsing now checks whether value is an
array of appropriate length.  Depending if it is or not, the value
will be parsed accordingly.  It’s parsed only once and thus no clone
is necessary.

jsonrpc: optimise parsing of legacy params format

---

Cargo.lock
Cargo.toml
chain/network/src/network_protocol/borsh.rs
core/account-id/src/borsh.rs
core/crypto/src/signature.rs
core/crypto/src/traits.rs
core/primitives-core/src/account.rs
core/primitives-core/src/hash.rs
core/primitives-core/src/profile.rs
core/primitives-core/src/profile/profile_v2.rs
core/primitives/src/delegate_action.rs
core/primitives/src/time.rs
deny.toml
tools/speedy_sync/Cargo.toml

This is re-application of commit b8196b1aa with the same subject alas
this time borsh is updated to 0.10.2.  Previous attempt to update the
dependency was reverted becauses of potential DOS which was addressed
in borsh 0.10.2 (see <https://github.com/near/borsh-rs/pull/129>).
Like before, the update is mostly a matter of replacing deserialize
function in BorshDeserialize implementations by deserialize_reader.
In a few of existing custom implementations for (de)serialization
could be removed altogether.

Update borsh dependency; again

---

chain/network/src/types.rs

They have been superseded by Sender/AsyncSender and LateBoundSender.

[TestLoop] (3.4/n) Remove MsgRecipient and NetworkRecipient which are no longer used.

---

nearcore/src/metrics.rs
nearcore/src/runtime/mod.rs

Adding `shard_id` to allow understanding on which shard the undercharging is happening.
Given that this is changing the existing metric, is there any migration process that I need to follow?

feature: Add shard_id to SECONDS_PER_PETAGAS metric

---

chain/indexer/src/lib.rs
nearcore/src/config.rs
neard/src/cli.rs

cc: @anshal-savla @wacban 
```
% ./target/debug/neard --home /tmp/h init
2023-02-22T10:01:50.785498Z  INFO neard: version="trunk" build="1.1.0-3443-g179b3eee4-modified" latest_protocol=59
2023-02-22T10:01:50.786814Z  INFO config: Validating Config, extracted from config.json...
2023-02-22T10:02:05.791962Z  INFO near: Using key ed25519:7ZdLJmUGUBXGmwYuDXNaRsnZphvGLKQadseHKpohchx8 for test.near
2023-02-22T10:02:05.792411Z  INFO near: Using key ed25519:AEHuWUqhFQVi4Sef8GrDSjos55JHhbBjBFocyNzgLp1t for node
% ./target/debug/neard --home /tmp/h init
2023-02-22T10:02:19.591430Z  INFO neard: version="trunk" build="1.1.0-3443-g179b3eee4-modified" latest_protocol=59
2023-02-22T10:02:19.592395Z  INFO config: Validating Config, extracted from config.json...
2023-02-22T10:02:34.521485Z  INFO near: …
```

feat: neard init can initialize only node and validator keys if both Config and Genesis exist

---

tools/state-viewer/src/apply_chunk.rs
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs

right now the apply command only prints out the old and new chunk extra that results. We'd like to automatically detect when the results don't match, so change it to compare the two chunk extras and return with an error when they don't match.

feat(state-viewer): exit w nonzero code on bad apply result

---

core/crypto/src/errors.rs
core/crypto/src/test_utils.rs
core/crypto/src/util.rs
integration-tests/src/tests/client/features/delegate_action.rs
runtime/runtime/src/actions.rs
tools/mirror/src/key_mapping.rs
tools/mirror/src/lib.rs

`PublicKey::from_implicit_account` derives the implicit PK for
an account ID, both for tests/tooling as well as for production code.
Closes #8588

refactor: Util function to derive an implicit PK

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/release_fuzzer_binaries
scripts/build_fuzzers.py

In this PR I'm adjusting build_fuzzers script to allow specification of the conventional "branch" name.
Workflows will be calling it with either "release" or "master" arg and the resulting archive will be pushed to corresponding bucket: gs://fuzzer_targets/release/ or gs://fuzzer_targets/master/
Release fuzz building workflow will be triggered on release publish even.
Test ran successfully in https://github.com/near/nearcore/actions/runs/4292093900/jobs/7478099145

Feat: Adding release fuzz builder workflow

---

core/store/benches/store_bench.rs
core/store/src/cold_storage.rs
core/store/src/db/database_tests.rs
core/store/src/db/rocksdb.rs
core/store/src/db/rocksdb/snapshot.rs
core/store/src/lib.rs
core/store/src/test_utils.rs
genesis-tools/genesis-populate/src/main.rs
genesis-tools/genesis-populate/src/state_dump.rs
integration-tests/src/tests/client/cold_storage.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/network/runner.rs
nearcore/benches/store.rs
nearcore/src/cold_storage.rs
nearcore/src/config.rs
nearcore/src/lib.rs
nearcore/src/runtime/mod.rs
pytest/lib/cluster.py
pytest/tests/sanity/split_storage.py
runtime/runtime-params-estimator/src/main.rs
test-utils/runtime-tester/src/run_test.rs
test-utils/store-validator/src/main.rs
tools/cold-store/src/cli.rs
tools/mirror/src/offline.rs
tools/mock-node/src/setup.rs
tools/speedy_sync/src/main.rs
tools/state-viewer/src/cli.rs

- use split store in the view client - when configured
- removed the get_store(Temperature) method and replaced usages with safer get_cold_store and get_hot_store
- added SplitStorageConfig and used it to configure a few things

feat: use split store in the view client

---

core/primitives/src/state.rs
core/store/src/trie/insert_delete.rs
core/store/src/trie/iterator.rs
core/store/src/trie/mod.rs
core/store/src/trie/state_parts.rs
integration-tests/src/tests/runtime/state_viewer.rs

Rather than handling value references as a (size, hash) tuples, use
existing ValueRef type in RawTrieNode and ValueHandle.  This better
documents what the u32 and CryptoHash mean and simplifies some code
by having a single object representing what so far was handled with
two variables.

core: use ValueRef in trie nodes structs

---

chain/chunks/src/lib.rs
chain/chunks/src/metrics.rs

See https://near.zulipchat.com/#narrow/stream/295302-general/topic/UnknownChunk.20bug.20report
Problem:
> Getting a lot of "WARN chunks: Error processing partial encoded chunk forward: UnknownChunk" in the testnet after upgrading to 1.32.0-rc.1
Cause:
> This "error" happens in a normal code path (where we cache a forwarded chunk even if header isn't available - what Marcin said), so there's nothing wrong. However, a recent refactoring changed the handler of this error, and instead of ignoring it, it was printed out.
Fix: don't return error anymore. This is no longer necessary after migrating ShardsManager to its own actor. Verified that unit tests still have good coverage even without asserting the error (a test fails if one of the insertion statements is commented out). Also rename one …

Fix unwanted UnknownChunk warning log messages.

---

chain/chunks/src/lib.rs

[TestLoop] (9.1/n) Forgot to include the tests into the source tree.

---

chain/chain/src/chain.rs
chain/chain/src/flat_storage_creator.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
core/store/src/columns.rs
core/store/src/flat/delta.rs
core/store/src/flat/storage.rs
core/store/src/flat/store_helper.rs
genesis-tools/genesis-populate/src/lib.rs
integration-tests/src/tests/client/flat_storage.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime/src/genesis.rs
tools/flat-storage/src/commands.rs

Prepend `ShardUId` to flat state keys, as motivated in https://github.com/near/nearcore/issues/8670.
Ideally we need to replace `shard_id` with `shard_uid` everywhere, including other DB keys and `RuntimeAdapter` flat storage methods. But this change would be too involved, so let's do it incrementally.
The biggest structural consequence is that `FlatStorage` now stores `shard_uid`, which makes sense, and later it will be used for writing deltas as well. It's not a big deal, but because of that changes are scattered throughout the code and may look scary.
* `test_flat_storage_iter` checks that new `key_belongs_to_shard` impl is aligned with shard layout; also we can see that the change takes place in this failing test: https://buildkite.com/nearprotocol/nearcore/builds/25676#0186bc8f-12a2-4 …

refactor: use shard uid in flat state keys

---

neard/src/cli.rs
tools/state-viewer/src/cli.rs

State viewer is pretty much useless with cold db only.
Replacing cold store with split store in case Temperature::Cold was provided. 
If you feel bad about this decision, choose one of these alternative options:
- introduce some config flag that essentially means "use_split_store_in_state_viewer_instead_of_cold"
- introduce third Temperature -- Split
- introduce StoreType enum in neard with hot, cold, and split and use it in args instead of Temperature

use split store in state-viewer

---

chain/network/src/config.rs
chain/network/src/network_protocol/borsh_conv.rs
chain/network/src/network_protocol/mod.rs
chain/network/src/network_protocol/network.proto
chain/network/src/network_protocol/proto_conv/peer_message.rs
chain/network/src/network_protocol/tests.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer/tests/communication.rs

PeersResponse has a bounded size. Sending an excessive number of peers is spammy and should be considered abusive.
Closes #8642

Ban nodes sending excessively large PeersResponse

---

chain/chain/src/chain.rs
chain/chain/src/flat_storage_creator.rs
core/primitives/src/shard_layout.rs
core/store/src/flat/delta.rs
core/store/src/flat/storage.rs
core/store/src/flat/store_helper.rs
integration-tests/src/tests/client/flat_storage.rs
tools/flat-storage/src/commands.rs

Part of https://github.com/near/nearcore/issues/8577.
Use `ShardUId` instead of `ShardId` in delta key, for consistency with flat state keys. This is not strictly needed today, but may help later if we do resharding - that's how we can support flat storages for old and new shard versions.
Existing tests should not fail.

feat: use shard uids in deltas

---

chain/client/src/info.rs
chain/client/src/metrics.rs
nearcore/src/metrics.rs
nearcore/src/runtime/mod.rs

As is turned out to be too noisy, hard to aggregate and not allowing to filter out chunks with small gas usage. We have better metrics based on average gas usage and apply delays.
I've added an alternative metric at panel "Processing time per gas burnt" at https://nearinc.grafana.net/goto/UvpFf7-4z?orgId=1 which ended up less noisy and easier to work with.

cleanup: Remove `SECONDS_PER_PETAGAS` metric

---

pytest/tests/adversarial/fork_sync.py

This test spins up some nodes using `start_cluster`, then brings them down and back up again. They are brought back up with incorrectly configured `boot_nodes`, preventing them from reconnecting and causing the test to fail.
Before #8617 information about peers learned in the first run was persisted to disk, so the boot nodes configured when restarting the nodes didn't matter.

Fix boot nodes in fork_sync

---

chain/chain/src/chain.rs
chain/chain/src/flat_storage_creator.rs
chain/chain/src/store.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
core/store/src/columns.rs
core/store/src/flat/manager.rs
core/store/src/flat/mod.rs
core/store/src/flat/storage.rs
core/store/src/flat/store_helper.rs
core/store/src/flat/types.rs
integration-tests/src/tests/client/flat_storage.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/src/estimator_context.rs
tools/flat-storage/src/commands.rs

Part of #8577
This PR introduces `FlatStorageStatus`:
* it generalises `FlatStorageCreationStatus`
* `FlatStorageCreationStatus::DontCreate` is moved to `::Disabled` status
* flat head is now stored as a part of `::Ready` status.
* `::Empty` status is added to explicitly express that flat storage does not exist
* we no longer need `FlatStateMisc` column, so it is removed 
nayduck run: https://nayduck.near.org/#/run/2905

feat: introduce flat storage status

---

Cargo.toml
core/crypto/src/signature.rs
core/primitives-core/src/hash.rs
runtime/runtime-params-estimator/emu-cost/Dockerfile
rust-toolchain.toml

Routine update to the latest version of Rust.
Release post: https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html
I don't see anything exciting for nearcore in the release.
Maybe `pin!` for custom futures could be useful.
The commit also includes clippy changes, they renamed 
`derive_hash_xor_eq` to `derived_hash_with_manual_eq`
and changed the check. Now, we no longer need an `allow()`.
There is also a new [future incompatibility warning](https://github.com/rust-lang/rust/pull/103418)
which we hit in `fs_extra v1.2.0` and `wasmparser v0.78.2`.
I don't think we can get rid of the second anytime soon, assuming we
hang on to replayability.

toolchain: update to Rust 1.68.0

---

core/store/src/trie/insert_delete.rs
core/store/src/trie/iterator.rs
core/store/src/trie/mod.rs
core/store/src/trie/state_parts.rs
integration-tests/src/tests/runtime/state_viewer.rs
tools/cold-store/src/cli.rs

Add a generic Children type which holds references to the children
of a trie branch node.  This is a minor refactoring which does three
things.
* It provides iterator which filters missing children.  This
simplifies usage as explicit `filter` call is no longer necessary.
* It eliminates ‘as usize’ casts from the code. NibbleSlice returns
nibbles as `u8`, to use the value as an index in an array a cast is
necessary.  Now that Children uses `u8` indexes this is no longer
needed leading to slightly cleaner code.
* It provides a common generic type for children in RawTrieNode and
TrieNode types providing common interface for those two cases.

core: add Children type representing trie branch’s childrenas 

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/ondemand_fuzzer_binaries.yml

With this workflow we will be able to build fuzz targets based on:
- release events: new release or new prerelease (release candidate)
- manual builds - required to retroactively build missing binaries or for development purposes (fixing bugs)

Ondemand fuzz target build

---

core/store/src/config.rs

`BlockHeight` and `BlockInfo` had an increased request count in an
earlier implementation snapshot of flat state. At the time, there was a
measurable positive effect for increasing these two caches from 32MB to
64MB. This is no longer the case, so let's not increase them.

feat(flat-state): don't increase column caches

---

core/store/src/config.rs
core/store/src/flat/storage.rs
core/store/src/metrics.rs
core/store/src/trie/config.rs
core/store/src/trie/shard_tries.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/src/estimator_context.rs

Part of #8577 and #8684, was introduced in #8540.
This PR removes custom `FlatState` cache from `FlatStorage` since experiments show very low hit rate which is not worth used memory.

feat: remove flat state cache

---

.buildkite/pipeline.yml

Revert [near/nearcore/pull/8714](https://github.com/near/nearcore/pull/8714) because of issues with GCP auto-scaler.

Revert "Move buildkite pipeline from AWS to GCP"

---

core/store/src/flat/store_helper.rs
core/store/src/flat/types.rs

We plan introducing small value inlining as a next step in Flat Storage, see #8243 for more details. This is not a part of MVP which means it will not be included in the first Flat Storage release.
This PR wraps `ValueRef` in `FlatStateValue` enum, so later we can simply add another variant for inlined value there without changing the format on disk. This significantly simplifies migration in the future.

feat: make FlatState value future proof for value inlining support

---

core/primitives/src/errors.rs
core/store/src/flat/storage.rs
core/store/src/flat/types.rs
core/store/src/trie/mod.rs
integration-tests/src/tests/client/flat_storage.rs
nearcore/src/runtime/mod.rs

Making flat storage errors more clear and fix error types in several places. Fixes [flat storage failure on March 14](https://near.zulipchat.com/#narrow/stream/345766-pagoda.2Fstorage.2Fflat-storage/topic/FS.20failure.20March.2014th/near/341648913).
This PR needs a review with **extra caution**, because `StorageInternalError` in incorrect place may lead to node panic and `BlockNotSupported` when DB is corrupted may lead to weird behaviour of node.
Here I claim that there are two types of `FlatStorageError`:
* `BlockNotSupported` - can occur in normal circumstances, when flat storage head was moved forward during processing some chunk.
* `StorageInternalError` - means that flat storage is corrupted, we have to panic.
I looked at every single place where we return these errors, and replaced …

fix: more precise flat storage errors

---

CHANGELOG.md
chain/client/src/client_actor.rs
chain/client/src/info.rs
chain/client/src/metrics.rs

* Current block height since the start of the current epoch
* shards tracked by the current node. (currently all shards but in the feature it might change)
* whether the node is a block producer
* whether the node is a chunk producer and for which shard
Tested on localnet and mainnet on a canary rpc node.
The gist of metrics from the node in prod. [link](https://gist.github.com/VanBarbascu/ccb1d60dbcc66a0444eb7092e4970fc9)
For additional test results check each commit message

feat: add Prometheus metrics

---

chain/chain/src/chain.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
core/store/src/flat/manager.rs
core/store/src/flat/storage.rs
core/store/src/trie/shard_tries.rs
integration-tests/src/tests/client/flat_storage.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/src/estimator_context.rs
tools/flat-storage/src/commands.rs

Part of #8577.
This finishes flat storage transition from `shard_id` to `shard_uid`.

refactor: use shard_uid as a key in FlatStorageManager

---

core/store/src/flat/delta.rs
runtime/runtime-params-estimator/src/config.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/main.rs
runtime/runtime-params-estimator/src/transaction_builder.rs
runtime/runtime-params-estimator/src/trie.rs
runtime/runtime-params-estimator/src/utils.rs

Force FlatState used by the estimator to resolve deltas.
The number of deltas and the number of keys per delta is configurable.
Example usage:
```
cargo run -r -p runtime-params-estimator --features=protocol_feature_flat_state -- \
--accounts-num 10000 --additional-accounts-num 10000 \
--finality-lag 50 --fs-keys-per-delta 100 \
--metric time --debug --costs StorageReadBase
```

feat(params-estimator): flat state deltas overhead

---

chain/chain/src/flat_storage_creator.rs
core/primitives/src/state_record.rs
core/store/src/flat/delta.rs
core/store/src/trie/mod.rs
core/store/src/trie/split_state.rs

Previously we didn't have `shard_uid` prefix for `FlatState` keys on disk which meant that we couldn't easily store delayed receipts for different shards there. This is no longer the case and we can store delayed receipts in flat storage now.
This makes `FlatState` store exactly the same data as `State` which makes overall setup more consistent and enables easier flat storage use for state sync without any special cases.
Existing tests should not fail.

feat: don't exclude delayed receipts from flat storage

---

CHANGELOG.md
tools/state-viewer/src/apply_chain_range.rs
tools/state-viewer/src/cli.rs
tools/state-viewer/src/state_parts.rs

Also rework the state parts command API to be a single command with two subcommands instead of two separate commands.

Fix: Add --dry-run to the tool for applying state-parts

---

chain/chain/src/flat_storage_creator.rs
core/store/src/flat/metrics.rs
core/store/src/flat/mod.rs
core/store/src/flat/storage.rs
core/store/src/lib.rs
core/store/src/metrics.rs

Part of https://github.com/near/nearcore/issues/8577.
This PR moves flat storage metrics structs to a separate module under `near_store::flat`.
Benefits of this change:
* separation of concerns
* metrics setup involves quite some boilerplate code which pollutes business logic and increases file size, hence moving that to a separate file

refactor: move flat storage metrics to a separate module

---

docs/practices/protocol_upgrade.md

As they are broken when viewed through https://near.github.io/nearcore/practices/protocol_upgrade.html due to being relative

Fix links to version.rs file

---

pytest/lib/mocknet_helpers.py
pytest/tests/mocknet/helpers/load_test_spoon_helper.py
pytest/tests/mocknet/load_test_spoon.py

- make the spoon test wait with upgrading nodes until the helper is done deploying contracts 
- make the helper test ignore connection refused exceptions when sending transactions - those happen when the selected rpc node is being upgraded
- added log level cmd line argument and cleaned up some logs

fix: mocknet fixed helper crashing 

---

Cargo.toml
utils/near-cache/README.md

Following up PR #8762 by bumping versions for the `near-*` crates to `0.16.1` in order to release the ones mentioned in the PR and updating the others to have a set of compatible packages released.
cc @jakmeier As you said to bump the version
P.S. adding an empty README to the `near-cache` crate to avoid "publisher" from failing

chore: Bump crates version to 0.16.1

---

utils/near-cache/Cargo.toml
utils/near-cache/README.md

The publishing of the  crate `near-cache` failing with an error
```
Uploading near-cache v0.16.1 (/var/lib/buildkite-agent/builds/buildkite-i-04b8708aca8b70702-1/nearprotocol/nearcore-release/utils/near-cache)
error: failed to publish to registry at https://crates.io/
Caused by:
the remote server responded with an error: missing or empty metadata fields: description. Please see https://doc.rust-lang.org/cargo/reference/manifest.html for how to upload metadata
error: unable to publish package near-cache
🚨 Error: The command exited with status 1
```
I hope this PR is fixing it.

fix(near-cache): Failed to puslibh the crate

---

chain/chain-primitives/src/error.rs
chain/chain/src/chain.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chunks-primitives/src/error.rs
chain/client-primitives/src/types.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/view_client.rs
chain/epoch-manager/src/adapter.rs
tools/mirror/src/offline.rs

As a reminder of the overall goal, we want to split `RuntimeWithEpochManagerAdapter`, so that any code that needs the runtime will use an `Arc<RuntimeAdapter>`, and any code that uses the epoch manager will use the `EpochManagerHandle`.
We're doing this refactoring bottom-up, i.e. propagating `RuntimeWithEpochManagerAdapter` around at the top-level, but making some lower-level components use `Arc<RuntimeAdapter>` and/or `EpochManagerHandle`.
That means we need to be able to obtain an `Arc<RuntimeAdapter>` and an `EpochManagerHandle` from a `RuntimeWithEpochManagerAdapter`. However, this is not trivial at all:
1. `KeyValueRuntime`, the implementation of `RuntimeWithEpochManagerAdapter` for testing, does not contain an `EpochManager` at all, so it's not possible to extract an …

[Runtime Epoch Split] (2/n) Narrow EpochManagerAdapter error type to EpochError wherever possible.

---

tools/themis/src/rules.rs
tools/themis/src/utils.rs

In the absence of the `rust-toolchain.toml` file, themis exits with "No such file or directory".
Since there's no rule enforcing the presence of a toolchain file, we can ignore its absence.

themis: fix ENOENT when rust-toolchain.toml doesn't exist

---

core/primitives-core/src/config.rs
core/primitives-core/src/profile.rs
runtime/near-vm-logic/src/gas_counter.rs

This seemed like the simplest approach that introduced minimal runtime overhead and code changes (as opposed to introducing a dedicated field in the GasCounter). Happy to consider the alternatives though.
Part of https://github.com/near/nearcore/issues/8032
Some follow-up work is planned in https://github.com/near/nearcore/issues/8795

feature: Get compute usage from profile

---

core/async/src/examples/sum_numbers_test.rs
core/async/src/test_loop.rs
core/async/src/test_loop/adhoc.rs
core/async/src/test_loop/event_handler.rs
core/async/src/test_loop/multi_instance.rs

Adhoc events allow executing arbitrary logic as part of a TestLoop event, so that it shows up on the visualizer. This helps with understanding the test setup, and also when assertions fail, we know which assertion failed - e.g. in the following screenshot, if that assertion failed, the logs for that event should show the panic, and the assertions to the right would be missing (since the test crashed).
Also two minor improvements:
- Make test loop panic if non-timer events remain in the queue when the test ends. This is useful if the test has forgotten to run() everything, and if not done can lead to tests not actually running what it's supposed to run or what it's supposed to assert (if assertion is done in an adhoc event). This is implemented by having each handler specify whether an …

[TestLoop] Add AdhocEvent to allow executing arbitrary logic as part of a TestLoop event.

---

chain/chain/src/tests/simple_chain.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
core/primitives/src/version.rs

Are we still on track to increase protocol version each release?

bump protocol version for 1.33.0

---

Cargo.toml
runtime/runtime-params-estimator/emu-cost/Dockerfile
rust-toolchain.toml

This version has added support for revoked ssh keys and has revoked the leaked github key. Seems like a thing to be
better-safe-than-sorry about.

Upgrade to rust 1.68.2

---

integration-tests/src/tests/nearcore/sync_nodes.rs
pytest/lib/cluster.py
pytest/tests/sanity/state_sync.py
pytest/tests/sanity/state_sync1.py
pytest/tests/sanity/state_sync2.py
pytest/tests/sanity/state_sync3.py
pytest/tests/sanity/state_sync4.py
pytest/tests/sanity/state_sync5.py
pytest/tests/sanity/state_sync_fail.py
pytest/tests/sanity/state_sync_late.py
pytest/tests/sanity/state_sync_massive.py
pytest/tests/sanity/state_sync_massive_validator.py
pytest/tests/sanity/state_sync_routed.py

State Sync remains important functionality that needs to be tested, and which is expected to work on networks that are smaller than testnet/mainnet
TODO: Run Nayduck before merging

fix: Update integration and pytests to enable state sync

---

runtime/runtime/src/lib.rs

First off, we should always use `safe_add_gas` when adding gas to avoid bugs and for code consistency, even in cases when we know there won't be an overflow.
Moreover, in this particular case, I actually wasn't able to strictly prove that the value never overflows as it depends on the send fees set in the config.
This is technically a protocol change. In practice, we don't expect this addition to ever overflow and if this actually happens in practice, I argue that it's better to loudly fail rather than corrupt the state of the network by acting on the overflowed value of the `total_gas_burnt`.

fix: Safely accumulate burnt gas for transaction to receipt conversion

---

nightly/fuzz.toml

GA workflow is failing past few days with:
`FileNotFoundError: [Errno 2] No such file or directory: 'runtime/near-vm/fuzz'`
This will fix it.
No-op for anything else

fix: fuzz target builder CI

---

pytest/tools/prober/prober.py
pytest/tools/prober/prober_split.py
pytest/tools/prober/prober_util.py

Make a contarct call from the prober on the legacy and the split archival nodes and check that the results are the same. 
They aren't right now and this seems to be a real issue in the split store implementation - I'll be debugging that. If anyone happens to have any idea on where this error is coming from let me know. 
```
[2023-03-15 13:21:08] INFO: Running Prober Split
[2023-03-15 13:21:08] INFO: gcloud compute instances list
[2023-03-15 13:21:09] INFO: Selected random legacy node - 35.194.243.155
[2023-03-15 13:21:10] INFO: The genesis height is 42376888. The head height is 120422174
[2023-03-15 13:21:10] INFO: Checking blocks at height 48488222
[2023-03-15 13:21:11] INFO: Checking chunks
[2023-03-15 13:21:12] ERROR: Check failed, the legacy response and the split response are …
```

feat: prober checks contract function call on split store node

---

runtime/near-vm-logic/src/gas_counter.rs
runtime/near-vm-logic/src/logic.rs
runtime/near-vm/lib/types/src/types.rs

This PR proposes some small additions to documentation that could aid to understand the purpose and usage of `FastGasCounter`.
https://github.com/near/nearcore/blob/24c4f4981c18edc003413dfc2c3fa4a0b98a810f/runtime/near-vm-logic/src/gas_counter.rs#L28
A hint on how this exposure is generated would have been helpful for me. In particular since the comment below may raise the question ‘Why have `FastGasCounter` when gas metering is done on the host?’. I think knowing about the (potential) intrinsification of the `gas` host function helps to clarify this.
https://github.com/near/nearcore/blob/83b1f80313ec982a6e16a1941d07701e46b7fc35/runtime/near-vm-runner/src/instrument/gas/mod.rs#L396-L402

docs: mention intrinsification of `gas` host fn

---

core/store/src/db.rs
core/store/src/db/colddb.rs
core/store/src/db/rocksdb.rs
core/store/src/db/splitdb.rs
core/store/src/db/testdb.rs
core/store/src/lib.rs
core/store/src/opener.rs

This should be safe to use with already open db.
Not sure about easy, though. home_dir, config, and archive flag are not available everywhere right now without any hustle.

feat: create NodeStorage from checkpoint

---

CHANGELOG.md
chain/network/src/config.rs
chain/network/src/config_json.rs

Added config.experimental.network_config_overrides field. It contains the overrides for the currently default values from NetworkConfig.
The JSON config override is done before the CLI overrides.

feat: override NetworkConfig from JSON config

---

nightly/pytest-sanity.txt
pytest/lib/cluster.py
pytest/tests/sanity/split_storage.py

Adding localnet test to make sure that node can sync from cold storage.
Introducing _migrate_to_split_storage a.k.a moving code around. Using it in old migration test (literally nothing changed).
The main part of this PR is test_archival_node_sync -- spinning up legacy archival node, split storage archival node + validator and rpc node (to make split storage node split). 
Test flow is as follows:
1. Migrate split storage node
2. Kill legacy archival node
3. Produce bunch more epochs (twice as more as number of epochs to keep by split storage node)
4. Kill validator
5. Restart legacy archival node
6. Check that it is syncing a bit
Will restart Nayduck when it will feel better, but for now no red flags, one green flag https://nayduck.near.org/#/run/2934

adding TestSplitStorage.test_archival_node_sync

---

Cargo.lock

chore: minor updates to crypto dependencies
No particular reason to do this now, staying up to date is 
just good practice.
I reviewed all relevant changelogs, nothing of particular
interest to us was changed. I also ran a few performance checks,
it doesn't look like anything changed.
Crates updated:
- sha1 0.10.4 -> 0.10.5
- sha2 0.10.2 -> 0.10.6
- sha3 0.10.1 -> 0.10.6
- digest 0.10.3 -> 0.10.6
- secp256k1 0.24.2 -> 0.24.3 
These are the newest stable versions of all crates, except secp256k1.
I will look into updating secp256k1 to 0.27.0 in another PR because the
update could include breaking changes according to semver.

chore: minor updates to crypto dependencies

---

Cargo.lock
Cargo.toml
deny.toml

Updating a couple of dependencies allows to remove old duplicates.
None of the "breaking" API changes affect us.
redis 0.21.5 -> 0.23 gets rid of an old "sha1"
csv 1.1.1 -> 1.2.1 gets rid of an old "itoa"
Also, remove unnecessary exception for "num-rational".
And while I was already going through dependencies and changelogs,
also update "secp256k1" to the latest version.

chore: remove duplicate dependencies

---

core/primitives-core/src/profile.rs
runtime/near-vm-logic/src/gas_counter.rs

This is a solution to https://github.com/near/nearcore/issues/8908.
Now when we try to prepay the gas for some operation and run into the gas limit, both the gas and compute usage for that operation will be paid partially, where compute cost is calculated as `gas_burnt / gas_cost * compute_cost`.

feature: Account for gas running over the limit

---

runtime/runtime/src/lib.rs

As it fails with:
```
thread 'tests::test_contract_precompilation' panicked at 'Compilation result should be non-empty', runtime/runtime/src/lib.rs:2550:14
```
presumably, because the compilation cache is not populated on aarch64-apple.
A prior art: https://github.com/near/nearcore/pull/8412

tests: Disable precompilation test on aarch64-apple

---

chain/client/src/client_actor.rs
core/chain-configs/src/client_config.rs
core/store/src/config.rs
nearcore/src/config.rs

Part of #8827.
Adds `flat_storage_creation_enabled` config flag to enable/disable flat storage creation. The default value is `true`.
This is needed for SREs to be able to manually enable/disable flat storage creation when taking state backup.

Add flat_storage_creation_enabled config flag

---

chain/network/src/store/testonly.rs
core/primitives-core/src/account.rs
core/primitives/src/transaction.rs
core/primitives/src/types.rs
core/primitives/src/views.rs
runtime/near-vm-runner/src/instrument/gas/validation.rs
runtime/runtime-params-estimator/src/qemu.rs
scripts/run_clippy.sh

We have two types of errors in the codebase resulting in `clippy::derivable_impls` warning:
1. Enums implement `default()` explicitly when it can be derived. This seems to be an unambiguous readability improvement. Removing an explicit function definition is good. `#[default]` is clear enough.
2. Structs implement `default()` to initialize all fields to default values of corresponding types. This seems an improvement too. @jakmeier please check whether it's a readability for `QemuCommandBuilder`.
The PR was generated by running this and adjusting the result manually
```sh
cargo clippy --fix -- -A clippy::all -W clippy::derivable_impls
```
This is part of #8145

cleanup: Fix clippy::derivable_impls

---

CHANGELOG.md

Adds a message to the changelog of the next release about compute costs protocol change.

Add Compute Costs to CHANGELOG

---

CHANGELOG.md
Cargo.lock
Cargo.toml
chain/chain/src/store.rs
integration-tests/Cargo.toml
integration-tests/src/tests/client/mod.rs
integration-tests/src/tests/client/undo_block.rs
neard/Cargo.toml
neard/src/cli.rs
tools/undo-block/Cargo.toml
tools/undo-block/src/cli.rs
tools/undo-block/src/lib.rs

undo-block tool to revert the current head of the chain to its previous block. Typically used when the state of current chain head is messed up, e.g. running a wrong binary like in the case of protocol upgrade or gas price param changes.
To use the tool:
1. stop the node
2. run command `./target/release/neard --home {path_to_config_directory} undo-block`
3. restart node
Assuming only the head of the chain was messed up, not a long fork, then after using the tool, the node should be able to catch up and produce block (if they are block producers).
We intentionally forbid users from reverting beyond final block so that nothing is messed up for flat storage and finality is not broken.
[Design doc for the tool](https://docs.google.com/document/d/1bqdGtMCNwyHDNGWmcsVCR23q1BdcK2tu6ab87Kd43r0/edi …

feat: undo-block tool

---

chain/chain/src/chain.rs
chain/chain/src/migrations.rs
chain/chain/src/store.rs
tools/state-viewer/src/apply_chain_range.rs
tools/state-viewer/src/apply_chunk.rs
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/epoch_info.rs

As a reminder of the overall goal, we want to split RuntimeWithEpochManagerAdapter, so that any code that needs the runtime will use an Arc<RuntimeAdapter>, and any code that uses the epoch manager will use the EpochManagerHandle.
This PR splits usages in state-viewer, so that it no longer uses RuntimeWithEpochManagerAdapter. It will use EpochManagerHandle wherever possible, but when needed, we fall back to EpochManagerAdapter for code that still needs to convert from RuntimeWithEpochManagerAdapter (since that cannot in general provide an EpochManagerHandle). When EpochManagerAdapter is no longer created from RuntimeWithEpochManagerAdapter, we can remove EpochManagerAdapter and always use EpochManagerHandle, a concrete type.

[Runtime Epoch Split] (6/n) Refactor state-viewer away from RuntimeWithEpochManagerAdapter.

---

CHANGELOG.md
core/primitives/res/runtime_configs/61.yaml
core/primitives/res/runtime_configs/parameters.snap
integration-tests/src/tests/client/features.rs
integration-tests/src/tests/client/features/increase_storage_compute_cost.rs

This is a protocol feature, updating the storage cost as agreed in #8006
to allow flat storage to be deployed without undercharging risks.

feat: set storage compute cost > gas cost

---

core/store/src/cold_storage.rs
core/store/src/columns.rs
integration-tests/src/tests/client/cold_storage.rs

Addressing some of the TODOs by Waclaw.
Making PartialChunks, ChunkHashesByHeight, and BlockPerHeight cold instead of implementing logic to recompute them.
This adds ~30Gb to cold DB. 
Should be included in 1.34.

more cold columns

---

chain/chain/src/store.rs

There was a minor conflict while merging #8681 and #8761. Removing cfg(feature) because feature is stabilized now.

fix: remove cfg from undo block tool

---

CHANGELOG.md
chain/client/src/info.rs
chain/client/src/metrics.rs

The producer to block/chunk assignment is known ahead of time so we can
estimate what we expect to see at the end of the epoch.
We are computing these numbers only once per epoch.
Tested on mainnet and localnet. 
On localnet:
- started 4 nodes
- stopped one of them for a delta of 200 blocks
- started it again

feat: Export number of expected chunks/blocks in epoch to prometheus

---

chain/client/src/client.rs

At the moment transactions are indefinitely stored on RPC nodes that are not validators (https://github.com/near/nearcore/issues/8878, https://github.com/near/nearcore/pull/6713).
The intent of this commit is to avoid storing transactions on any node that can't be a chunk/block producer and as far as I understand, such node **requires** a validator key, so we use it as a condition to store the transaction.

Only store transactions on validator nodes

---

chain/indexer/src/streamer/mod.rs
chain/indexer/src/streamer/utils.rs
core/primitives/src/views.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs

In https://github.com/near/nearcore/pull/8426 this conversion became lossy due to the introduction of Compute Costs. This raised the question of whether this conversion is needed at all. I've found one place in the Indexer code that uses it and replaced it with a direct lookup for config from `RuntimeConfigStore`. As a part of this I've also simplified some code in the indexer.
This should fix the failing nayduck test https://github.com/near/nearcore/issues/8967

cleanup: Removing RuntimeConfigView -> RuntimeConfig

---

runtime/near-vm-logic/src/dependencies.rs
runtime/near-vm-logic/src/logic.rs
runtime/near-vm-logic/src/mocks/mock_external.rs
runtime/runtime/src/ext.rs

In `storage_has_key` we were setting `KeyLookupMode::FlatStorage` by default. This is correct for most reads, but not for reads inside contracts, as it impacts chunk cache and contract call costs.
We must read from flat storage deterministically and derive lookup mode from protocol version.

fix: correct read mode for storage_has_key

---

tools/cold-store/src/cli.rs

Don't scare users, because rpc head being behind cold head is normal. Rpc DB comes from backups, we only publish those once every 12 hours, it is very likely that cold db is lagging behind by less than 12 hours. 
Error message in this case is confusing, warning is more appropriate.

cold-store:  prepare-hot: error -> warn

---

chain/client/src/client.rs
integration-tests/src/tests/client/benchmarks.rs
integration-tests/src/tests/client/challenges.rs
integration-tests/src/tests/client/cold_storage.rs
integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
integration-tests/src/tests/client/features/chunk_nodes_cache.rs
integration-tests/src/tests/client/features/flat_storage.rs
integration-tests/src/tests/client/features/increase_storage_compute_cost.rs
integration-tests/src/tests/client/features/lower_storage_key_limit.rs
integration-tests/src/tests/client/features/wasmer2.rs
integration-tests/src/tests/client/features/zero_balance_account.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/sandbox.rs
integration-tests/src/tests/client/sharding_upgrade.rs
nearcore/tests/economics.rs
test-utils/runtime-tester/src/run_test.rs
tools/state-viewer/src/apply_chain_range.rs
tools/state-viewer/src/apply_chunk.rs
tools/state-viewer/src/state_dump.rs

The result of `process_tx` is important because it tells whether the submitted transaction is valid and has been accepted.
So we add `#[must_use]` annotation to it and fix all the tests that were not checking it.
As a part of this, we fix two tests that were using incorrect nonce (but still somehow functioned...):
- `benchmark_large_chunk_production_time`
- `test_verify_chunk_invalid_state_challenge`
This is a part of the work on introducing the transaction pool limits https://github.com/near/nearcore/issues/8878.

tests: Verify that transaction is valid and accepted

---

core/primitives-core/src/serialize.rs
core/primitives/src/state_record.rs
core/primitives/src/types.rs
core/primitives/src/views.rs
integration-tests/src/tests/client/sandbox.rs
integration-tests/src/tests/runtime/state_viewer.rs
integration-tests/src/tests/standard_cases/runtime.rs
runtime/runtime/src/genesis.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/state_viewer/mod.rs
tools/state-viewer/src/commands.rs

Derive serialisation code for StoreKey, StoreVlaue and FunctionArgs
primitive types and then use those types more in various structures
which so far has been using raw `Vec<u8>` instead.
This improves self-documentation of the code (the type of the struct
field indicates what it is) and moves base64 format declaration to the
primitive types rather than having to annotate individual structures
with `#[serde(with = ...)]`.
On the flip side, it does add a couple `.into()` calls when converting
between one of the aforementioned types and `Vec<u8>`.

core: make StoreKey, StoreValue and FunctionArgs serde serialisable

---

core/primitives/src/views.rs
pytest/lib/lightclient.py
pytest/lib/messages/block.py

Unclear why this is here, opening it just to see if anything breaks, and see what does. Curious if it's a refactor that's broken this support, as I've gotten some server-side RPC errors relating to this type.

fix: remove unused validator stake view type

---

chain/chain/src/flat_storage_creator.rs
core/store/src/flat/chunk_view.rs
core/store/src/flat/delta.rs
core/store/src/flat/mod.rs
core/store/src/flat/storage.rs
core/store/src/flat/store_helper.rs
core/store/src/flat/types.rs
core/store/src/trie/mod.rs
core/store/src/trie/state_parts.rs
integration-tests/src/tests/client/flat_storage.rs
runtime/runtime-params-estimator/src/estimator_context.rs

Part of #8243.
This PR implements value inlining MVP for state sync:
* add `FlatStateValue::Inlined` variant to store inlined values as part of `FlatState` and `FlatStateChanges` on disk.
* change flat storage API to return `FlatStateValue` instead of `ValueRef`.
The following will be implemented separately:
* Migration for existing `FlatState` values. This is required for state sync, but quite involved, so decided to keep it separately.
* Inlining for cached flat state deltas: for now we keep those as `ValueRef`.
* Using inlined values for transaction processing: for now we convert inlined values to `ValueRef`.

feat: implement inlining for small values in flat storage

---

neard/src/cli.rs

Sorry for such a small change, the typo was a bit distracting :D

chore: fix typo in proof verification CLI

---

chain/chain/src/flat_storage_creator.rs
core/store/src/trie/mod.rs
core/store/src/trie/prefetching_trie_storage.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/trie_storage.rs
core/store/src/trie/trie_tests.rs
tools/state-viewer/src/commands.rs

There is no need to duplicate logic of reading from DB in `TrieRecordingStorage`. It makes more sense to create it over existing `TrieStorage` and reuse `retrieve_raw_bytes` impl from it. Also this allows us to get rid of annoying `as_caching_storage` cast. It is not actually necessary for underlying storage to be `TrieCachingStorage`.
Some consequences:
* `Rc` replaces `Box` in Trie, because we need to be able to copy pointer to trie storage. Looks like a reasonable requirement.
* `TrieStorage` is not `Send` anymore, but this is not needed in the code anyway. Otherwise we can consider `Arc`.
cc @jbajic as an example of existing issues with trie logic

refactor: no logic duplication in `TrieRecordingStorage`

---

chain/chain/src/flat_storage_creator.rs
core/store/src/flat/chunk_view.rs
core/store/src/flat/delta.rs
core/store/src/flat/mod.rs
core/store/src/flat/storage.rs
core/store/src/flat/store_helper.rs
core/store/src/flat/types.rs
core/store/src/trie/mod.rs
core/store/src/trie/state_parts.rs
integration-tests/src/tests/client/flat_storage.rs
runtime/runtime-params-estimator/src/estimator_context.rs

This reverts #8988 as it results in node crashing: [zulip](https://near.zulipchat.com/#narrow/stream/345766-pagoda.2Fstorage.2Fflat-storage/topic/Canary.20crashes/near/355722627).
The original PR changes data format for delta changes on disk, so binary with the new code failed to deserialise deltas written by the old code.
I suggest we revert the change for now and then re-publish it along with the db migration.

Revert "feat: implement inlining for small values in flat storage"

---

integration-tests/src/tests/client/sharding_upgrade.rs

The previous sampling scheme had two problems:
- It could sample accounts test2 and test3 which will likely be on the same shard
- It could sample the same account twice
The reason I looked into this is that sampling the same account results in deploying the same contract twice, which leads to the submission of duplicate transactions and fails on the check that I've introduced here to deal with transaction pool limits https://github.com/near/nearcore/pull/8970/files#diff-69c20a1a7276bee390fe2844bff3d2fc4c1ed09f0faaa832f0c8d39776ebf9e8R2013
We probably need some special handling for duplicate transactions to avoid forwarding them.

fix: Sample different accounts in sharding test

---

runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/wasmer2_runner.rs

The hashes were for rust 1.69, which is what master uses.
Before this  change:
```
cargo +1.69.0 test -p near-vm-runner // succeeds
cargo test -p near-vm-runner // fails because it uses 1.68.2 specified in rust-toolchain.toml
```
After this  change:
```
cargo +1.69.0 test -p near-vm-runner // fails
cargo test -p near-vm-runner // succeeds
```
1.34 MUST be compiled with rust 1.68.2 or else the smart contract binaries will be incompatible!

fix wasmer2 output hashes for rust 1.68.2

---

pytest/tests/sanity/split_storage.py

One of the tests doesn't clean the nodes and causes subsequent ones to fail.

fix: split storage tests

---

Cargo.lock
Cargo.toml

[Audits](https://github.com/near/near-sdk-rs/actions/runs/4690517670/jobs/8376852068?pr=1010) in `near-sdk` highlight a security vulnerability [RUSTSEC-2023-0001](https://rustsec.org/advisories/RUSTSEC-2023-0001) that affects the Windows platform.
As far as I could tell, we're not directly impacted by this, but the severity suggests we make an upstream dep update.
https://github.com/near/nearcore/pull/8309#issue-1525418158 pinned `tokio` to `1.18` and suggested not updating the minor version unconsciously. Whereas #8472 required a bump to `1.19`, which has no versions that patch this vulnerability.
This PR seizes the opportunity to re-pin the minor version to the latest, after which subsequent updates can uphold the bump requirement outlined in #8309.

chore: update `tokio` to `1.28`

---

chain/client/src/info.rs
chain/client/src/metrics.rs

Prometheus metric for the actual version of the protocol.
The existing metric statically exports the maximal version supported by the node, which is not the same.

fix(metrics): Current protocol version

---

pytest/tests/loadtest/loadtest2.py

This should be multiplication, not exponential.
At least in local testing, this caused problems and txs
were never submitted.
(Flyby updating a comment at the same place as well)

fix(loadtest2): gas amount

---

pytest/tests/sanity/garbage_collection1.py
pytest/tests/sanity/gc_sync_after_sync.py

This PR is to fix long running issue with garbage collection test.
Test was failing because node 1 could not sync from remaining 3 peers, which did not have the required by node 1 blocks, for example target heigh 1:
epoch_length = 10
target_heigh1 = 60 
gc_num_epochs_to_keep = 5
This means that by the time network reached target heigh 60, nodes 0, 2 and 3 garbage collection mechanism will clear blocks from 1 to 10:  
60 (heigh) - 10 (epoch length) * 5 (epochs to keep).
Fix is to enable STATE SYNC

Fix: garbage collection test

---

core/store/src/migrations.rs
nearcore/src/migrations.rs

Remove support for ancient database versions. Keep support for the last five database versions only. This removes a lot of code which isn’t used in practice.
Anyone operating a node will go through migrations as new database versions are introduced. Anyone still holding onto ancient databases will need to use older neard releases.

cleanup(migrations): Remove old migration code

---

chain/pool/src/lib.rs

This PR introduces accounting of the size of the transaction pool in bytes that will later be used rejecting incoming transactions that push the size over the limit.

feature: Introduce transaction pool size accounting

---

core/store/src/test_utils.rs
core/store/src/trie/split_state.rs
integration-tests/src/tests/client/sharding_upgrade.rs

As before, even though the setup specified `num_init_accounts` in reality this was an upper bound on the number of accounts to generate, which ended up breaking an assumption in one of the tests:
```
thread 'tests::client::sharding_upgrade::test_shard_layout_upgrade_missing_chunks_mid_missing_prob' panicked at 'index out of bounds: the len is 1 but the index is 1', integration-tests/src/tests/client/sharding_upgrade.rs:623:35
```

fix: Make sure we generate enough accounts for sharding test

---

chain/chunks/src/client.rs
chain/client/src/client.rs
chain/pool/src/lib.rs
core/chain-configs/src/client_config.rs
nearcore/src/config.rs

The PR introduces a limit to the size of the transaction pool for each shard and a logic that rejects transactions that go over this limit. The reasoning for this work is described in https://github.com/near/nearcore/issues/3284.
To start, the limit will be disabled (effectively set to infinity) and this PR shouldn't have any effect. The node operators can override it with a config option. In the future, we will come up with a safe value to set by default (probably between 10 MiB - 1 GiB).
We also start with a simple option where the RPC client will not know if their transaction runs into this limit. We will need to rework this part in the future, but it will have to touch the transaction forwarding code in a non-trivial way, and I would prefer to work on this when we have a congestion …

feature: Introduce a limit to transaction pool size

---

chain/pool/src/lib.rs

Previous logic didn't take into account that the pool can be modified by the iterator created for it.
I think overall this behavior is quite confusing and I'm not sure it is warranted, so I'm looking for ways to simplify this.
This is a part of https://github.com/near/nearcore/issues/3284

fix: Adjust transaction pool size after draining iterator

---

chain/jsonrpc/client/src/lib.rs
core/primitives-core/src/serialize.rs
utils/fmt/src/lib.rs

1. Use serde::from_slice instead of String::from_utf8+serde::from_str
to avoid separate UTF-8 validation and vector allocation.
2. Use serde:\:de::Visitor to avoid String allocation when
deserialising base64 data.
3. Switch serialising from using serialize_str to calling collect_str
on base64_display which again avoids temporary String.
4. Postpone when base64 decode error is converted to avoid boxing it.

core: avoid memory allocations when dealing with Serde data

---

chain/pool/src/lib.rs
chain/pool/src/metrics.rs

This will allow us to understand how big the transaction pools get in practice and what is the realistic limit to set for them.
The logic within pool iterator is a bit complex due to the need to return transactions back to the pool and I'm working on a way to simplify it in a separate PR, but for now this accounting should do the job.
This is one of the steps for https://github.com/near/nearcore/issues/3284

feature: Add metric measuring size of transaction pool

---

core/o11y/src/metrics.rs

Expect metrics exported by nearcore to have a common prefix. This helps in the following cases:
* Avoids name conflicts with metrics from other systems.
* Helps filter and query metrics
* Makes it easy to understand which binary export a certain metric.

fix(metrics): Enforce 'near_' prefix for new metrics

---

Cargo.lock
tools/state-viewer/Cargo.toml
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/epoch_info.rs

Extends the `neard view-state epoch-info` command to show only the kickouts.
Fixes that tool not to panic while displaying EpochInfo which doesn't have the corresponding blocks.

feat(state-viewer): Display kickouts information

---

tools/themis/src/rules.rs
tools/themis/src/types.rs
tools/themis/src/utils.rs

`themis` needs to read directly from package manifests in some cases. Since we updated to workspace inheritance, this format has changed.
To avoid the flow potentially breaking in the future, this patch allows the interpretation of `.workspace = true` entries.

chore: add support for workspace inheritance to themis

---

Cargo.lock
Cargo.toml
chain/chain/src/tests/simple_chain.rs
chain/client/src/debug.rs
chain/jsonrpc/Cargo.toml
chain/jsonrpc/fuzz/fuzz_targets_disabled/fuzz_target_1.rs
chain/jsonrpc/src/api/transactions.rs
core/primitives-core/Cargo.toml
core/primitives-core/src/serialize.rs
core/primitives/Cargo.toml
core/primitives/src/receipt.rs
core/primitives/src/state_record.rs
core/primitives/src/transaction.rs
core/primitives/src/types.rs
core/primitives/src/upgrade_schedule.rs
core/primitives/src/utils.rs
core/primitives/src/views.rs
deny.toml
genesis-tools/genesis-csv-to-json/src/csv_parser.rs
runtime/near-test-contracts/test-contract-rs/Cargo.lock
runtime/near-test-contracts/test-contract-rs/Cargo.toml
runtime/near-test-contracts/test-contract-rs/src/lib.rs
runtime/runtime-params-estimator/estimator-warehouse/src/db.rs

Using serde_with to customise serde serialisation removes some of the
code while at the same time enables more powerful customisation
annotations.
Bringing the dependency forces update of base64 and chrono
dependencies.

Switch to using serde_with

---

tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs

This PR is related to issue https://github.com/near/nearcore/issues/8650
In this PR we are adding a new `clear-cache` subcommand under neard command `view-state`.
The idea is to create a command to reset state/delete all recoverable data from the DB. `clear-cache` command, for now, deletes all data in the column `DBCol::CachedContractCode`.

[neard] Add `view-state clear-cache` command to neard

---

core/store/src/flat/inlining_migration.rs
core/store/src/flat/manager.rs
core/store/src/flat/mod.rs
core/store/src/flat/storage.rs
core/store/src/flat/store_helper.rs
core/store/src/metrics.rs
tools/flat-storage/src/commands.rs

Part of #8243.
This PR implements migration process for inlining `FlatState` values. For more details see the second approach in [this comment](https://github.com/near/nearcore/issues/8243#issuecomment-1532930290).
Migration is not currently executed on the running node, that will be implemented in a separate PR. Instead `migrate-value-inlining` sub-command is added as part of `flat-storage` command.
Can be executed via `cargo run --release -p neard -- --verbose store flat-storage migrate-value-inlining`. Progress log example:
```
2023-05-15T14:22:54.280387Z  INFO store: Starting FlatState value inlining migration read_state_threads=16 batch_size=50000
...
2023-05-15T16:00:24.210821Z DEBUG store: Processed flat state value inlining batch batch_index=1580 inlined_batch_count=50000 …
```

feat: flat state value inlining migration

---

core/store/src/db.rs
core/store/src/db/colddb.rs
core/store/src/db/rocksdb.rs
core/store/src/db/splitdb.rs
core/store/src/db/testdb.rs
core/store/src/flat/store_helper.rs
core/store/src/lib.rs
integration-tests/src/tests/client/flat_storage.rs
tools/flat-storage/src/commands.rs

Needed for #8927.
1. From what I see in https://doc.rust-lang.org/rust-by-example/scope/lifetime/explicit.html, lifetimes introduce restriction over passed variables - they must outlive function lifetime. But this doesn't make sense for iterator. It doesn't save much memory, because iterator is expected to return lots of vectors anyway. And slices `from` and `to` are converted to vectors inside anyway. This allows us to construct DB keys inside `iter_flat_state_entries`.
2. Construction of DB keys is hidden inside `flat` module now. You give state keys and receive state keys back, without knowing how they are stored on the lower level.
@jbajic would you like to cover `iter_flat_state_entries` with some test? 
This function will be covered by integration tests for state parts anyway and it …

refactor: convenient iteration over flat state entries

---

chain/chain/src/flat_storage_creator.rs

Fixes panicking of threads fetching state on flat storage creation.
If binary is stopped by SIGTERM, channel for receiving messages with state part stats can be disconnected. We shouldn't panic in such case, it's enough to log an error. Still, the node will stall for ~5 minutes because existing rayon threads need to finish heavy IO work. 
Original thread https://near.zulipchat.com/#narrow/stream/308695-pagoda.2Fprivate/topic/Flat.20storage.20crash.20on.20SIGTERM.201.2E34-RC1/near/358803319

fix: don't panic on SIGTERM during flat storage creation

---

chain/chain/src/chain.rs
chain/chain/src/types.rs
nearcore/src/runtime/mod.rs
nearcore/src/state_sync.rs
tools/mock-node/src/setup.rs
tools/state-viewer/src/state_parts.rs

Replace `block_hash` in `RuntimeAdapter::obtain_state_part` with `prev_hash`.
This doesn't impact functionality but is quite convenient for flat storage integration here: #8927. Existing obstacle is that flat storage includes aggregated updates until flat storage block hash, **included**. So if we want block hash to correspond to state root, state root must be **post state root** for a block.
Existing tests must not fail. Notably, contract precompilation tests passed incorrect hash, but we didn't notice that because block hash was used only for getting shard uids.

refactor: put `sync_prev_prev_hash` to `obtain_state_part`

---

integration-tests/src/tests/runtime/deployment.rs
runtime/near-vm-runner/fuzz/fuzz_targets/diffrunner.rs
runtime/near-vm-runner/src/prepare.rs

Without that, it tries running with contract prepare version v1 since the near-vm landing revert.
In turn, this means that gas accounting becomes nonsensical, as near-vm has its own gas accounting that is only compatible with contract prepare version v1, and is only expected to be consistent with contract prepare version v1

make sure diffrunner fuzzer actually runs with contract prepare version v2

---

core/primitives/src/views.rs
integration-tests/src/tests/runtime/state_viewer.rs
runtime/runtime/src/state_viewer/mod.rs

Change ViewStateResult::proof serialisation to base64.  This has been
the plan all along but back when proof was added¹ I forgot to follow
up with encoding change.  At the moment the proof is sent as an array
of integers which is inefficient and inconsistent with how binary data
is other JSON messages is encoded.
Furthermore, follow up with the deprecation notices: don’t include
proof field in StateItem and don’t include proof field in the response
if it hasn’t been requested.
¹ See commit faa1811d1625: ‘add proof to ViewState response’.

jsonrpc: encode state proofs using base64 and remove deprecated field

---

runtime/near-vm-runner/src/imports.rs
runtime/near-vm-runner/src/tests/regression_tests.rs

This should fix the issue we hit in https://github.com/near/nearcore/pull/9066 with one test being too slow.
Intrinsic-ifying could help even more, but this should already bring a significant multiplier to the performance, which hopefully should be enough to handle all practical concerns.

do not spend time tracing finite_wasm_gas

---

nearcore/src/config.rs

So that it will be read from `config.json` that each node provides
This is a part of https://github.com/near/nearcore/issues/3284

feature: Add transaction pool size to Config

---

core/account-id/src/lib.rs

Looks like the former implementation of `Arbitrary` for `AccountId` would assume all strings were well-formed `AccountId`'s. Skipping the validation logic. Which is untrue.
This patch swaps out the derive for a custom implementation that ensures all arbitrary byte slices are validated before an `AccountId` is constructed.

fix: implement valid AccountId generation from arbitrary data

---

chain/network/src/config.rs
chain/network/src/network_protocol/borsh_conv.rs
chain/network/src/network_protocol/mod.rs
chain/network/src/network_protocol/network.proto
chain/network/src/network_protocol/proto_conv/handshake.rs
chain/network/src/network_protocol/proto_conv/net.rs
chain/network/src/network_protocol/testonly.rs
chain/network/src/network_protocol/tests.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer/tests/communication.rs
chain/network/src/peer_manager/tests/connection_pool.rs
chain/network/src/peer_manager/tests/nonce.rs
chain/network/src/raw/connection.rs
chain/network/src/testonly/stream.rs
core/chain-configs/src/genesis_config.rs
core/chain-configs/src/genesis_validate.rs
nearcore/src/config_validate.rs
nearcore/src/state_sync.rs

https://github.com/near/nearcore/issues/8902
The problem being solved
- Prevent man in middle attacks on Tier2 network 
The approach taken
- Pass the signed ip address of the sender 
Remaining steps to fully deploy this solution after this PR is merged
- Fail the handshake only after all nodes on both mainnet and testnet have updated to the latest version of Tier2 handshake that includes signing the ip address. It currently only fails if the signed ip address is present and faulty but doesn't fail if the signed ip address is absent (for backward compatibility temporary migration purposes)
Also needed to run auto-linter to pass buildkite tests
```
cargo fmt -- --emit files 
cargo clippy --fix -- -A clippy::all -W clippy::useless_format -W clippy::clone_on_copy
cargo clippy --fix -- -A …
```

Include signed ip address in TIER2 handshake. #8902 

---

chain/chain/src/chain.rs
chain/chain/src/flat_storage_creator.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
core/store/src/flat/manager.rs
core/store/src/flat/storage.rs
docs/architecture/storage/flat_storage.md
integration-tests/src/tests/client/flat_storage.rs
nearcore/src/runtime/mod.rs
tools/flat-storage/src/commands.rs

With #9093 `RuntimeAdapter` has access to `FlatStorageManager` which makes all other flat storage related methods redundant. This PR removes those methods to keep `RuntimeAdapter` trait leaner.

refactor: remove redundant flat storage methods from RuntimeAdapter

---

chain/client/src/info.rs
chain/client/src/metrics.rs

Information about the block/chunk production was not cleared between epochs.
Clear the metrics before adding new data.
Add `epoch_height` as a field.

fix: clear previous epoch block/chunk production metrics

---

core/store/src/flat/chunk_view.rs
core/store/src/flat/store_helper.rs
core/store/src/trie/state_parts.rs
integration-tests/src/tests/client/flat_storage.rs
tools/flat-storage/src/commands.rs

use `FlatStateValue` instead of ra aw `Box<[u8]>`.

refactor: use proper type for FlatState iterator values

---

pytest/tests/loadtest/locust/common/base.py

I didn't test #9111 properly, this doesn't actually
work as expected. We need `retrying` not `retry`.

fix(test): import correct retry library

---

chain/client/src/info.rs
chain/client/src/metrics.rs

Get validator version on the go from every block we process and report it.

feat: report validator stake

---

core/account-id/src/lib.rs

Fixes unintended panic in the `Arbitrary` implementation of `AccountId`.
As pointed out in https://github.com/near/nearcore/pull/9107#discussion_r1207737121, certain `Unstructured` data sources like `a|bcd` or `a_-b` causes a panic with the current implementation.
This patch reduces the consumed input to the limit of validity adherence. Failing otherwise. But never panics.
Worth noting this implementation does not provide a fallback for input sources shorter than `AccountId::MIN_LEN` or longer than `AccountId::MAX_LEN`.

chore: fix panic on arbitrary `AccountId` generation

---

chain/network/src/accounts_data/mod.rs
chain/network/src/accounts_data/tests.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/network_state/tier1.rs
chain/network/src/peer_manager/testonly.rs

This crate exposes some very generic names such as `Error`, `Cache`, and `CacheSnapshot` which we end up referring to elsewhere by the full path (for example, writing `accounts_data::Error` everywhere).
This PR makes the names less generic so that we can directly import them.

Improve naming of public definitions in crate accounts_data

---

runtime/runtime/src/verifier.rs

As long as AccountId is created in a valid way, this check is redundant.
But in tests, we can create all kinds of transactions and it can be
annoying to debug serde parsing errors popping up randomly across the
code.

feat: extra validation for beneficiary id

---

chain/chain/src/chain.rs
chain/chain/src/flat_storage_creator.rs
core/store/src/flat/chunk_view.rs
core/store/src/flat/delta.rs
core/store/src/flat/manager.rs
core/store/src/flat/mod.rs
core/store/src/flat/storage.rs
core/store/src/flat/store_helper.rs
core/store/src/flat/types.rs
core/store/src/trie/state_parts.rs
integration-tests/src/tests/client/flat_storage.rs
tools/flat-storage/src/commands.rs

* Replace `StorageError` with `FlatStorageError` in `store_helper`.
* Add message to `FlatStorageError::StorageInternalError` to avoid losing information about the underlying error
* Introduce `FlatStateIterator` and get rid of the hack around empty iterator (not exactly related to error handling, just a general improvement)

refactor: improve flat storage error handling

---

pytest/tests/loadtest/locust/common/base.py
pytest/tests/loadtest/locust/common/ft.py
pytest/tests/loadtest/locust/common/social.py

Mainly adding some type annotations across the code to make pyright type
checker happy.
To use the type checker, you'll need to install it [1] and run "pyright file.py"
to show the warnings.
[1] https://github.com/microsoft/pyright

refactor: Fix pyright warnings in locust loadtests

---

core/primitives/src/syncing.rs
integration-tests/src/tests/client/state_dump.rs

1MB state parts are too inefficient.
The issue is deduplication of contract codes. State part stores values by references. Small state parts only get to store a few contract codes and they are likely to be all unique. Increasing the state part size, a lot more contracts fit into a single state part, and get "compressed" much better.
30MB state part:
* saves 15% of total state dump size for mainnet
* saves 60% of total state dump size for testnet
* 30x-60x reduces the number of state parts. Managing a few thousand files is much easier than 100k files per epoch.
Also this PR removes unconditional addition of 2 state parts. History lost the reasoning for doing it, and not doing it seems to be working fine.

fix(state-parts): Adjust state part size

---

core/primitives/src/receipt.rs
nearcore/src/metrics.rs
nearcore/src/runtime/mod.rs
runtime/runtime/src/lib.rs

Adding a new metric for the delayed receipts queue length as part of #8880. 
The delayed receipts are updated in the apply method on runtime. I considered three ways to implement logging the length of that queue:
- Log from the apply method itself. It's nice becase it's right next to where the queue is updated. It's not nice because it would require passing the shard id as an argument to the apply method. In principle I would rather keep runtime agnostic of the shard id as far as possible. 
- Log from the process_state_update method on NightshadeRuntime. 
- Read the value directly from the trie - seems cumbersome and requires touching the trie. 
- Get the value passed from the apply method in the ApplyResult - this seems passable as the delayed receipts queue can easily be considered to …

feat: Adding metric for the delayed receipts queue length

---

chain/pool/src/lib.rs
chain/pool/src/types.rs

Right now the metric has noticeable blips due to rapid change when transactions are drawn from the pool: https://nearinc.grafana.net/goto/YZwyDllVR?orgId=1 To avoid this, we only decrease the metric after the pool iterator is dropped.
This is a part of https://github.com/near/nearcore/issues/3284

Fix blips in the transaction pool size metric

---

CHANGELOG.md
nearcore/src/config.rs

This PR enables the limit discussed in https://github.com/near/nearcore/issues/3284.
I've [considered](https://near.zulipchat.com/#narrow/stream/297873-pagoda.2Fnode/topic/Adding.20a.20new.20field.20to.20config.2Ejson/near/358955785) another approach to rolling this out by changing the value in `config.json` distributed through S3, but that would require more work both on our side and on validators without adding much benefit. 
Specifically, I've checked that we have a good safety margin here, as over the last month on the testnet, the max size of the transaction pool on the validators was < 40 KB: https://nearinc.grafana.net/goto/AhZFN__4R?orgId=1.
@nikurt What would be a good place to document this field for validators? I saw https://near-nodes.io/, but couldn't find the appropriate …

Set default transaction pool size limit to 100MB.

---

pytest/tests/loadtest/locust/README.md
pytest/tests/loadtest/locust/common/congestion.py
pytest/tests/loadtest/locust/locustfile.py
pytest/tools/prober/prober_split.py

This PR introduces a Locust Workload for the Congestion Test: https://github.com/near/nearcore/issues/8920.
A typical run would be:
```sh
CONTRACT="path/to/nearcore/runtime/near-test-contracts/res/test_contract_rs.wasm"
locust -H 127.0.0.1:3030 \
CongestionUser \
--congestion-wasm=$CONTRACT \
--funding-key=$KEY \
--tags congestion
```
Then cranking up the number of users to 50-200 should be enough to cause congestion.
Wishlist of things I want to improve:
- Remove the need to specify `CONTRACT` variable every time as we know which contract we want to use for each workload type, we just don't know where it is stored
- We can use the same approach as "runtime/runtime-params-estimator/res/" - submitting WASM contracts that this test depends on alongside the code and update them once in a …

Locust Congestion Workload

---

chain/pool/src/lib.rs

The previous version of the code had a leak in the `total_transaction_size` because we didn't update it when we were dropping the empty group from `sorted_groups`.
Overall, I find the current implementation of transaction pool really tricky to work with and I'm more and more tempted to do https://github.com/near/nearcore/issues/9060 sooner.

fix: Handle size update on partial pool iterator update

---

chain/network/src/peer_manager/peer_manager_actor.rs
core/primitives/src/views.rs

It is currently possible to fetch the list of known edges in the network via the debug api.
This PR adds the node's computed "next hops" as well to the result. It will be useful in understanding and comparing the state of the old routing protocol as we roll out and test the V2 protocol.
The amount of data returned now is roughly double; both the number of edges and the size of the next hop table scale with `num_nodes * max_node_degree`.
The result is potentially large (with 700 nodes each with degree 35, around 3 MB for edges plus next hops), but this API endpoint is used only for manual debugging and is not programmatically queried. In testnet/mainnet nodes, the debug port is typically either blocked entirely or gated behind a password.
Example result via `:3030/debug/api/network_graph`:

debug/api/network_graph: include next hops

---

core/primitives-core/src/version.rs
core/primitives/src/version.rs
runtime/near-vm-logic/src/logic.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/config.rs
runtime/runtime/src/lib.rs

Replace `is_implicit_account_creation_enabled` with an actual `ProtocolFeature::ImplicitAccountCreation`

remove old function checking for protocol version

---

pytest/tests/loadtest/locust/README.md
pytest/tests/loadtest/locust/common/base.py
pytest/tests/loadtest/locust/common/congestion.py
pytest/tests/loadtest/locust/common/ft.py
pytest/tests/loadtest/locust/common/social.py
pytest/tests/loadtest/locust/locustfiles/congestion.py
pytest/tests/loadtest/locust/locustfiles/ft.py
pytest/tests/loadtest/locust/locustfiles/social.py

This removes the need for tags and makes the start command simpler. We still can combine the workloads by passing multiple locustfiles during launch as in:
```sh
locust -H 127.0.0.1:3030 \
-f locustfiles/ft.py,locustfiles/social.py \
--fungible-token-wasm=$FT_CONTRACT \
--social-db-wasm=$SOCIAL_DB_CONTRACT \
--funding-key=$KEY \
--headless
```
Because we don't import all workloads in a single file, there is no need to conditionally check for tags in the library modules, so I got rid of `is_tag_active` altogether.

refactor: Separate locust workloads into different files

---

tools/undo-block/src/cli.rs
tools/undo-block/src/lib.rs

Reset the block head to the tail block to trigger the state sync.
Does not apply the db migration. You need to run `neard run` for that. 
Example of the first run:
```
./neard undo-block -r
2023-06-14T12:31:13.537336Z  INFO neard: version="trunk" build="10778b837" latest_protocol=62
2023-06-14T12:31:13.554894Z  INFO config: Validating Config, extracted from config.json...
2023-06-14T12:31:13.601524Z  WARN genesis: Skipped genesis validation
2023-06-14T12:31:13.601651Z  INFO config: Validating Genesis config and records. This could take a few minutes...
2023-06-14T12:31:13.603661Z  INFO config: All validations have passed!
2023-06-14T12:31:13.604209Z  INFO db_opener: Opening NodeStorage path="/home/ubuntu/.near/data" cold_path="none"
2023-06-14T12:31:13.604279Z  INFO db: Opened a new …
```

feat: Reset block head to tail

---

pytest/tests/loadtest/locust/common/base.py

As the previous fails with:
```
File "/home/ubuntu/repos/nearcore/pytest/tests/loadtest/locust/common/base.py", line 195, in NearNodeProxy
def post_json(self, method: str, params: list(str)):
^^^^^^^^^
TypeError: 'type' object is not iterable
```

fix: Change `post_json` type annotation

---

pytest/tests/loadtest/locust/common/base.py

From the [docs](https://docs.near.org/api/rpc/transactions):
> TIMEOUT_ERROR:
> Transaction was routed, but has not been recorded on chain in 10 seconds.
From an end-to-end testing perspective, this means we should retry rather than drop the transaction.

feat(loadtest): retry on  timeout

---

pytest/tests/loadtest/locust/common/base.py
pytest/tests/loadtest/locust/common/congestion.py
pytest/tests/loadtest/locust/common/ft.py
pytest/tests/loadtest/locust/common/social.py

Just a DRY refactor. At least in spirit.
There are some consequences, such as more calls being tracked
by locust and different paths for error handling.
This method was used to avoid restrictions in the sync RPC api.
Now that we have properly retrying async api access, we might as well
use that in all places.

refactor(loadtest): remove `send_transaction`

---

pytest/tests/loadtest/locust/common/base.py
pytest/tests/loadtest/locust/common/congestion.py
pytest/tests/loadtest/locust/common/ft.py
pytest/tests/loadtest/locust/common/social.py

Previously the second run on the same state would fail due to the
funding accounts already existing.
Now one can choose between reusing old state (default) or starting
a new run with a new state (set a `--social-db-index` to a unique value)
Already existing accounts are simply not created, so things should work
fine as long as the initial balance per account doesn't run out.

feat(loadtest): allow rerunning on the same state

---

pytest/lib/key.py
pytest/tests/loadtest/locust/common/base.py
pytest/tests/loadtest/locust/common/congestion.py
pytest/tests/loadtest/locust/common/social.py

Currently all callers use seed=account_id.
Make this the default but still allow to use a different seed.

refactor: default seed in `key.from_seed_testonly`

---

pytest/tests/loadtest/locust/common/congestion.py
pytest/tests/loadtest/locust/common/ft.py
pytest/tests/loadtest/locust/common/social.py

- CLI arg checks are no longer necessary, we have default args
- cluster import is not used
- worker id is no longer part of account id seed

refactor(loadtest): remove dead code

---

integration-tests/src/tests/client/state_dump.rs
nearcore/src/state_sync.rs

caveat is in get_latest_epoch(): turns out in the case that head is in epoch x+1, final block is in epoch x, the get_latest_epoch() function will return epoch_id of x+1 but sync_hash (first block hash) of epoch x and our code logic will recognize this as a new complete epoch available. The sync_hash returned by get_latest_epoch() and its sync_prev_prev_hash will be used to get the state part in obtain_and_store_state_part(), which means the state part obtained are actually not for the latest complete epoch, but for the one before that.

fix: generate state part for the correct epoch and make total_num_parts stable for dump parts 

---

chain/client-primitives/src/types.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/sync/state.rs
chain/client/src/test_utils.rs

Limit the number of downloading threads started.
Use join handler to track the status of the downloads.
Testing on an RPC node with the following tracked shards schedule: `[[0], [1], [2]]`.
Setting 60 concurrent downloads, it was able to download the state in ~5 min. [Grafana](https://nearinc.grafana.net/goto/FcTGJJu4R?orgId=1)

feat: limit state sync downloading threads

---

Cargo.lock
Cargo.toml
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/near_vm_runner.rs
runtime/near-vm/compiler/src/error.rs
runtime/near-vm/engine/Cargo.toml
runtime/near-vm/engine/src/universal/artifact.rs
runtime/near-vm/engine/src/universal/builder.rs
runtime/near-vm/engine/src/universal/code_memory.rs
runtime/near-vm/engine/src/universal/engine.rs
runtime/near-vm/engine/src/universal/mod.rs
runtime/near-vm/test-api/src/sys/instance.rs
runtime/near-vm/test-api/src/sys/store.rs
runtime/near-vm/tests/compilers/compilation.rs
runtime/near-vm/tests/compilers/config.rs
runtime/near-vm/tests/compilers/deterministic.rs
runtime/near-vm/tests/compilers/stack_limiter.rs
runtime/near-vm/vm/src/artifact.rs

This gives us potential to manage our memory consumption and worst-case function call expense in a much better managed way.
This may, however be a decrease in continuous param estimator outputs for function call costs, depending on how and what workload it tests.

near-vm: use a recycling pool of shared code memories instead of a in-memory cache of loaded artifacts

---

core/primitives/src/state.rs
core/store/src/flat/delta.rs
core/store/src/flat/inlining_migration.rs
core/store/src/flat/mod.rs
core/store/src/flat/types.rs
core/store/src/trie/state_parts.rs

This logic is used in multiple places, so it makes sense to abstract it behind a method in `FlatStateValue`.
`on_disk` name is chosen over `new` since this logic is only applicable for values to be persisted on disk. Later we will also add inlining for values as part of Flat Storage Delta and those will have lower inlining threshold, so we will have another constructor.

refactor: add FlatStateValue constructor for on-disk values

---

chain/chain/src/chain.rs
chain/chain/src/tests/simple_chain.rs
core/primitives-core/Cargo.toml
core/primitives-core/src/version.rs
core/primitives/Cargo.toml
core/primitives/src/epoch_manager.rs
core/primitives/src/shard_layout.rs
nearcore/Cargo.toml
neard/Cargo.toml
pytest/tests/sanity/upgradable.py

Introduced new protocol version called SimpleNightshadeV2, guarded it behind the rust feature `protocol_feature_simple_nightshade_v2` and added it to nightly. 
Refactored the AllEpochConfig::for_protocol_version a bit and added the SimpleNightshadeV2 shard layout to it. 
Note that I'm only hiding the SimpleNightshadeV2 behind the rust feature, I'm not planning on adding it everywhere. I'm reusing the same ShardLayout::V1 structure, just with bumped version and an extra boundary account. This should allow for smooth development since we won't need to guard all of the new code behind the new rust feature. 
I tested it manually and some sort of resharding did happen. I'm yet to fully appreciate what exactly happened and if it's any good, as well as add some proper tests. I'll do that in …

feat: simple nightshade v2 - shard layout with 5 shards

---

Cargo.lock
chain/chain/src/block_processing_utils.rs
chain/chain/src/chain.rs
chain/chain/src/store.rs
core/o11y/Cargo.toml
core/o11y/src/log_config.rs
docs/architecture/how/resharding.md
docs/architecture/how/sync.md
nearcore/src/config.rs
nearcore/src/dyn_config.rs
runtime/near-vm-runner/src/utils.rs

- Renamed a lot of "dl_info" and 'to_dl" to "state_sync_info". I'm too afraid to ask what "dl" stands for but either way it's very confusing. (it could be download). I'm not sure I fully appreciate the difference between state sync, catchup and download and I'm open for a better suggestion how to rename those. 
- In the LocalnetCmd I added logic to generate default LogConfig - to get rid of a pesky log message about this config missing when starting neard. 
- In docs, renamed `SyncJobActor` to `SyncJobsActor` which is the correct name. 
- Allowing the `stable_hash` to be unused. It's only unused on macOS so we need to keep it but let's not generate a warning. All of the failed builds (red cross) below are due to this. cc @andrei-near shall we add some automation to notify us when builds …

refactor: small refactorings and improvements

---

Cargo.lock
chain/jsonrpc/res/rpc_errors_schema.json
core/primitives/src/errors.rs
integration-tests/src/tests/client/features/limit_contract_functions_number.rs
integration-tests/src/tests/runtime/test_evil_contracts.rs
integration-tests/src/tests/standard_cases/mod.rs
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/logic/errors.rs
runtime/near-vm-runner/src/logic/tests/promises.rs
runtime/runtime/Cargo.toml
runtime/runtime/src/actions.rs

This allows to drop a dependency on `near-account-id` and `near-rpc-error-macro` crates and brings us ever-so-slightly closer to having a contract runtime suitable for limited replayability.
But more importantly this also solves a long-term pain point in the contract runtime where we never really felt too confident modifying errors that are output from the contract runtime due to our fears about it possibly affecting the protocol output. Now that the schemas are outside of `nearcore/runtime` there's also a neat rule of thumb: anything goes inside `nearcore/runtime` (as far as errors are concerned.)

near-vm-runner: move protocol-sensitive error schemas to near-primitives

---

runtime/runtime-params-estimator/src/cost.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/transaction_builder.rs
runtime/runtime-params-estimator/src/trie.rs

Since we have flat storage for reads, we no longer charge for touched trie nodes (TTN) on reads.
Remove the gas estimation for it.
More specifically, we used to estimate TTN cost as `max(read_ttn, write_ttn)` and therefore had 3 numbers reported. (read, write, combined).
Now we only need a single number reported.
The removed code (read TTN estimation) also didn't work anymore, as it didn't actually touch any trie nodes, and hence an assertion was triggered.
```
thread 'main' panicked at 'assertion failed: nodes_touched_delta as usize >= 2 * final_key_len - 10', runtime/runtime-params-estimator/src/trie.rs:118:5
stack backtrace:
0: rust_begin_unwind
at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt
at …
```

chore(estimator): remove TTN read estimation

---

chain/network/src/peer/peer_actor.rs
chain/network/src/stats/metrics.rs

The metric has been deprecated since 1.30.  Users should use
near_peer_message_received_by_type_total instead.

chain: remove deprecated near_peer_message_received_total metric

---

chain/chain/src/types.rs
chain/client/src/client.rs
core/o11y/src/testonly.rs
integration-tests/src/tests/client/sharding_upgrade.rs
nearcore/src/runtime/mod.rs
runtime/runtime/src/lib.rs

There are plenty of log lines that don't fit in a single line, even on a quite wide monitor. This is an attempt to improve that. 
- Removed a few variables in tracing spans that were redundant - already included in parent span.
- Removed `apply_transactions_with_optional_storage_proof` span that immediately enters `process_state_update` and doesn't provide much value.
- Set the test formatter to use a new custom time formatter that only prints seconds and milliseconds since the test started. The default one prints full date, time, and nanoseconds. 
- Mini refactor of the sharding_upgrade.rs that I'm just trying to sneak through. These tests are the inspiration for improving the spam log since I can't parse it. 
- **RFC: changed the log level of the `process_receipt` log to `trace!`. This …

refactor: improvements to logging

---

nearcore/src/config.rs

Users have had enough time to update their config files to no longer
specify network.external_address.  The comment dictates the warning
should be removed by the end of 2022 which was half a year ago.

nearcore: remove old deprecation notice about network.external_address

---

chain/chain/src/store.rs
nearcore/src/state_sync.rs
tools/state-viewer/src/scan_db.rs

No reason why `StateSyncDumpProgress` had to be stored as `Some(x)` instead of simply `x`

fix(state-sync): Simplify storage format of state sync dump progress

---

nightly/pytest-sanity.txt
pytest/tests/sanity/block_chunk_signature.py
pytest/tests/sanity/network_drop_package.py
pytest/tests/sanity/proxy_example.py
pytest/tests/sanity/proxy_restart.py
pytest/tests/sanity/proxy_simple.py
pytest/tests/sanity/recompress_storage.py
pytest/tests/sanity/sync_ban.py

Before this, running proxy-based nayduck tests (such as proxy_simple.py) fails on Mac because on Mac, multiprocessing.Process uses spawn, not fork, and our tests were written in a way that was unfriendly to spawn:
1. the entry point was not protected by `if __name__ == '__main__':`, causing spawned processes to re-execute the main module's code;
2. shared memory was not properly passed to the child process - we relied on referencing the same global variable which only worked with the fork implementation.
This PR fixes these. Also, re-enable two tests which are now fixed.

Fix proxy-based nayduck tests so that they can run on non-unix systems.

---

pytest/lib/cluster.py
pytest/tests/sanity/state_sync_fail.py

In #9274 I introduced simple nightshade V2 layout and added it to the nightly build. This broke the nayduck test state_sync_fail.py. Here is the fix for it. 
The test performs resharding and then checks some postconditions. It broke because it attempted to reshard from V0 shard layout to V2 shard layout. This doesn't work because ShardLayout contains shard split map that only makes sense when resharding from a shard layout version to the immediate next. 
The fix is to check what is the protocol version supported in the binary and depending on it reshard from V0 to V1 or from V1 to V2.

fix: fixed nayduck test state_sync_fail.py for nightly build

---

Cargo.lock
tools/database/Cargo.toml
tools/database/README.md
tools/database/src/adjust_database.rs
tools/database/src/analyse_data_size_distribution.rs
tools/database/src/commands.rs
tools/database/src/lib.rs
tools/database/src/state_perf.rs
tools/database/src/utils.rs

This PR adds a tool used to evaluate State read performance as part of `neard database` CLI. For more details on the approach see [the Methodology section](https://github.com/near/nearcore/discussions/9235).
Also includes some minor refactoring around database tool.
<details>
<summary>Example executions</summary>
```
ubuntu@pugachag-mainnet:~/nearcore$ ./target/quick-release/neard database state-perf --help
Run performance test for State column reads
Usage: neard database state-perf [OPTIONS]
Options:
-s, --samples <SAMPLES>
Number of requsts to use for the performance evaluation. Increasing this value results in more precise measurements, but longer test execution [default: 10000]
-w, --warmup-samples <WARMUP_SAMPLES>
Number of requests to use for database warmup. Those requests will be …
```

feat: add database tool subcommand for State read perf testing

---

pytest/tests/loadtest/locust/common/base.py
pytest/tests/loadtest/locust/common/ft.py
pytest/tests/loadtest/locust/common/social.py
pytest/tests/loadtest/locust/common/sweat.py

`list[...]` in type hints only works for python 3.9 and up.
For older python versions, we should use `typing.List[...]`.
I first thought we should require newer python for locust tests, also using `match` (see #9125) but it seems we are somewhat dependent on older Ubuntu versions for now. At least I've been checking out code on gcp machines created by terraform templates and needed to patch the type hints to get the code running without installing a new python version.
This PR makes the code fully backward compatible again by simply using the `typing` module which is available since python 3.5.

refactor(loadtest): backwards compatible type hints

---

chain/client/src/client.rs
chain/client/src/sync/state.rs
core/chain-configs/src/client_config.rs
integration-tests/src/tests/nearcore/sync_state_nodes.rs

We can limit the impact of state sync during catchup by turning this number down. This way validation of blocks will not be hindered while the node downloads the state.

feat(state-sync): Add config for number of downloads during catchup

---

tools/state-viewer/src/apply_chunk.rs
tools/state-viewer/src/cli.rs

For example, the ChunkExtra column key is block_hash + shard_uid.
It's much more convenient to use the tool as `neard view-state scan-db-column --column ChunkExtra --from-hash 11153w1N1bFv8fun2FdHfTMj97mF3gaUoV6fdrAQU9 --max-keys 4` to get ChunkExtra of that block.

fix(state-viewer): use hashes to determine scanning range

---

integration-tests/src/tests/client/process_blocks.rs
nearcore/src/runtime/mod.rs

This PR introduces a soft limit on the number of delayed receipts in each shard. The limit is around 10000 delayed receipts to make sure this is enough to saturate the chunk capacity even if receipts are very small. The largest number of delayed receipts that we've seen in the last 3 months is around 400 and it stays at 0 most of the time.
In the future, we would be also using other signals like the size of delayed receipts, but this information will have to be first computed and stored in the chunk headers/trie store and will be done in https://github.com/near/nearcore/issues/9228.
Addresses: https://github.com/near/nearcore/issues/8877

Stop accepting transactions when number of delayed receipts is large

---

chain/chain/src/flat_storage_creator.rs
core/primitives/src/types.rs
core/store/src/metrics.rs
core/store/src/test_utils.rs
core/store/src/trie/accounting_cache.rs
core/store/src/trie/chunk_cache.rs
core/store/src/trie/iterator.rs
core/store/src/trie/mod.rs
core/store/src/trie/prefetching_trie_storage.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_recording.rs
core/store/src/trie/trie_storage.rs
core/store/src/trie/trie_tests.rs
core/store/src/trie/update.rs
docs/architecture/storage/trie.md
docs/practices/workflows/io_trace.md
integration-tests/src/tests/client/features/chunk_nodes_cache.rs
integration-tests/src/tests/client/flat_storage.rs
integration-tests/src/tests/standard_cases/mod.rs
integration-tests/src/tests/standard_cases/runtime.rs
nearcore/src/entity_debug.rs
nearcore/src/runtime/mod.rs
runtime/runtime-params-estimator/README.md
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/replay.rs
runtime/runtime-params-estimator/src/replay/cache_stats.rs
runtime/runtime-params-estimator/src/trie.rs
runtime/runtime/src/prefetch.rs
tools/state-viewer/src/contract_accounts.rs
tools/state-viewer/src/state_parts.rs

For stateless validation, it must be possible to generate a state proof when applying a chunk, and we must ensure that
- During generation of the state proof, the execution outcome is identical to if we weren't generating a state proof
- When reapplying the same chunk using only the state proof (no full trie or flat storage), the outcome must also be identical.
The tricky part is storage gas accounting. 
For background, the trie is stored as two kinds of entries: trie nodes, and values. For trie nodes, the key is the hash of the node and the value is the node. For values, the key is the hash of the whole value, and the value is the value.
When doing a lookup of either a trie node or a value, there can be three cases:
- If looking up a trie node, the node is returned from flat storage …

Restructure TrieStorage and implement correct semantics for state proofs

---

pytest/lib/cluster.py
pytest/tests/loadtest/locust/common/base.py

Instead of submitting a transaction that builds on top of the very
latest block the queried node knows, we should build on top of the final
head. This avoid race conditions where transactions could reach a chunk
producer before the block the transaction builds upon is processed.
This was the main problem that caused the issue described in #9326

fix(loadtest): submit tx on top of final chain

---

pytest/tests/loadtest/locust/README.md
pytest/tests/loadtest/locust/common/base.py
pytest/tests/loadtest/locust/common/ft.py
pytest/tests/loadtest/locust/common/sweat.py
pytest/tests/loadtest/locust/locustfiles/sweat.py

For stress testing the storage performance, we fit as many Sweat
balance updates in a single receipt as possible.
For this, we combine multiple actions in a single receipt
to get around the per-receipt log output limit.
Of course, we are still limited by gas.
To run these large batches, use the `SweatUser` with `--tags=storage-stres-test`.
Otherwise, the `SweatUser` performs "small" batches and FT transfers in a 1:3 rate.
(Small batches are around the size of real SWEAT load.)

feat(loadtest): Sweat record large batches

---

chain/chain/src/chain.rs
core/store/src/flat/storage.rs

Also avoid printing WARNings when too many cached deltas are in memory.
Currently the number of cached deltas doesn't matter, only the number of blocks needed to get from a block to flat head is important.

fix(flat-storage): Handle chain forks gracefully

---

chain/chain/src/chain.rs
chain/chain/src/resharding.rs
chain/chain/src/types.rs
chain/client-primitives/src/debug.rs
chain/client-primitives/src/types.rs
chain/client/src/adapter.rs
chain/client/src/client_actor.rs
chain/network/src/test_utils.rs
core/o11y/src/macros.rs
core/store/src/trie/shard_tries.rs
integration-tests/src/tests/client/chunks_management.rs

Apparently, even the most verbose logging level gives us no information about the actual actix requests processed by actix actors.
Log the request messages at the debug and trace levels.

fix: Verbose handler spans

---

tools/debug-ui/src/RoutingTableView.tsx

In RoutingTableView we display a table of routing distances in the network.
Currently, distances of `0` (indicating a trivial path from a node to itself) and distances of `null` (indicating no advertised path between two nodes) are both displayed as `_` due to use of the `||` operator (OR).
What we actually want is for `null` to be rendered as `_` while all defined values are displayed as they are (including 0, a valid distance). Using the `??` operator (nullish coalescing) achieves what we want.

RoutingTableView: fix handling of 0 distances

---

chain/chain/src/doomslug.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/client/src/client.rs
chain/client/src/sync/header.rs
chain/epoch-manager/src/adapter.rs
core/primitives/src/block.rs
core/primitives/src/block_header.rs
core/primitives/src/test_utils.rs
core/primitives/src/views.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/nearcore/sync_nodes.rs

BlockHeaders contains a Vec "approvals" which contains entries of type `Option<Signature>`. 
This PR optimizes BlockHeaders' in-memory size for cases with many None approvals by changing the approval type to `Option<Box<Signature>>`.
Before this change:
- 66 bytes to store Some(approval)
- 66 bytes to store None
After this change:
- 74 bytes to store Some(approval)
- 8 bytes to store None

BlockHeaders: move approval Signatures into Box

---

runtime/near-vm-runner/src/tests/compile_errors.rs
runtime/near-vm-runner/src/tests/runtime_errors.rs
runtime/near-vm-runner/src/tests/test_builder.rs
runtime/near-vm-runner/src/tests/wasm_validation.rs

This change allows more control over which versions of the protocols tests will be run. Sorting the tested versions also helps with maintaining the consistent order of expects, and finally expects can be passed across multiple different test builders now, thus ensuring that tests which verify result stays the same don't become wrong after a stray `UPDATE_EXPECT=1` run.

test_builder: more flexibility and control

---

pytest/tests/loadtest/locust/common/base.py
pytest/tests/loadtest/locust/common/sweat.py

Create accounts in parallel where easily possible. This shaves off 20-30s in a typical Sweat load scenario.
Sadly, we still block on FT contract creation and deployment. We need some generalization of what I do here, or maybe some `deploy_contracts` helper.
Submitting this PR for now as it is a step in the right direction. Maybe feedback on the PR will change the direction of the next.

test: parallel account creation in loadtest

---

pytest/tests/mocknet/helpers/neard_runner.py
pytest/tests/mocknet/mirror.py

I find it useful to modify config.json-s for mirrored traffic tests. This doesn't require separate binaries which are built in >10 minutes and allows to skip setup restarts and manual ssh-ing to each node.
Here I allow to modify only state cache size because this is required for testing #9375 - we want to reduce size of 3GB cache at least. But it is easily extendable for other config parameters, I just didn't find generic way to do it.

feat: allow updating config.json in mirror script

---

chain/chain/Cargo.toml
chain/chain/src/chain.rs
chain/chain/src/store.rs
chain/client/Cargo.toml
chain/epoch-manager/Cargo.toml
core/primitives/Cargo.toml
core/primitives/src/epoch_manager.rs
core/store/Cargo.toml
core/store/src/columns.rs
integration-tests/Cargo.toml
integration-tests/src/tests/client/epoch_sync.rs
integration-tests/src/tests/client/mod.rs
nearcore/Cargo.toml
neard/Cargo.toml

First step towards new epoch sync. Everything should be under new_epoch_sync feature.
Design doc: https://docs.google.com/document/d/14Itc9Hs7ewTRmcGANid9UCaYcJzaLzzM7FsvYYIFKDY/edit
Adding EpochSyncInfo column and its population on epoch end in block postprocessing.

feat(epoch-sync): adding EpochSyncInfo column and its continuous population

---

integration-tests/src/tests/client/sharding_upgrade.rs

The test is fine since #9449 but I didn't notice it. Enabling it now. 
Tested it 10x and it passed every time.

fix: enable the test_shard_layout_upgrade_cross_contract_calls_v2

---

Cargo.toml
chain/client/src/test_utils.rs
integration-tests/src/tests/client/features/delegate_action.rs
runtime/near-vm/test-api/src/sys/externals/function.rs
runtime/near-vm/test-api/src/sys/module.rs
runtime/near-vm/test-api/src/sys/ptr.rs
runtime/runtime-params-estimator/emu-cost/Dockerfile
runtime/runtime-params-estimator/src/gas_cost.rs
runtime/runtime/src/receipt_manager.rs
rust-toolchain.toml

The code changes largely just address warnings from the compiler. The `drop` one is fairly straightforward in that `Box::from_raw` got a `#[must_use]` annotation, and the `resolver = "2"` one was a solution to a complaint from cargo about the fact that the default resolver in `edition = "2021"` crates is version 2, but this is only applicable for individual crates and workspaces must opt-in manually.

toolchain: update to 1.72.0

---

runtime/runtime-params-estimator/src/config.rs
runtime/runtime-params-estimator/src/main.rs
runtime/runtime-params-estimator/src/rocksdb.rs
runtime/runtime-params-estimator/src/trie.rs
runtime/runtime-params-estimator/src/utils.rs

There are several expensive things we do in the estimator that are only
necessary to make results more accurate. If we want to have CI checks,
we want to avoid them. `--check-only` allows to opt out.
Specifically, `--check-only` does:
- Disable CPU cache spoiling.
- Use a single tx per block instead of multiple.
- Reduce RocksDB benchmarks to a single operation.

feat(estimator): --check-only option for estimator

---

.buildkite/pipeline.yml

This change will specify buildkite pipeline to use default-public agents.

Fix: adding public queue to buildkite pipeline

---

.config/nextest.toml
runtime/runtime-params-estimator/estimator-warehouse/src/estimate.rs
runtime/runtime-params-estimator/estimator-warehouse/src/main.rs
runtime/runtime-params-estimator/src/main.rs

Add a test that runs a minimal estimator setup, just to ensure we have no crashes.
Crashes we had in the past:
- using host functions that didn't exist
- assertions that check estimation still does what it's supposed to do

test: CI check for estimator

---

nearcore/src/runtime/mod.rs

The following message occurs after the state sync when a node does not have previous epoch data. This is not an error so I am lowering the log level.
`ERROR runtime: Error when getting the gc stop height. This error may naturally occur after the gc_num_epochs_to_keep config is increased. It should disappear as soon as the node builds up all epochs it wants. Error: DB Not Found Error: epoch block:. ...`

fix(logs) reduce gc stop height log level

---

chain/jsonrpc/src/lib.rs

css was moved to separate files in https://github.com/near/nearcore/pull/9472 but it isn't properly routed, so [the debug page is broken](https://github.com/near/nearcore/pull/9472#issuecomment-1708795219).

fix: add debug page css routing

---

chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/tests/routing.rs

Updates to the routing table trigger a broadcast advising all peers of the latest information:
https://github.com/near/nearcore/blob/9ddfd49fb33288a43dc0ed8f4a37d66a11e69531/chain/network/src/peer_manager/network_state/routing.rs#L36-L41
Connection of a new peer is one type of event which results in a routing table update. The update should be broadcast after registering the new connection, so that the new peer is included in the broadcast.

Finish registering a new connection before sending routing update

---

core/primitives/src/sharding.rs

The encoded part bytes can be quite large. Printing the list of bytes as
```
part: [0, 0, 0, 0, 12, 0, 0, 0, 6, 0, 0, 0, 115, 121, 115, 116, 101,
109, 22, 0, 0, 0, 117, 117, 57, 120, 115, 56, 95, 117, 115, 101,
114, 53, 95, 114, 117, 110, 46, 110, 111, 100, 101, 48,
(this continues wih 3M entries and no cut-off)
```
in full is not very useful and usually blows
up debug output to an unreadable amount.
With this change, it will show like this:
```
part: (25555924)AAAAAAwAAAAGAAAAc3lzdGVtFgAAAHV1OXhzOF91c2VyNV9ydW4ubm9kZTCnKiyPMf578ZGhbYrbTF8CUXboIjS24ycaZcV0gp8IOgAWAAAAdXU5eHM4X3Vz…
```
It starts with the length and shows the first 128 bytes base64 encoded.

debug: abbreviate `PartialEncodedChunkPart`.`part`

---

core/store/src/test_utils.rs
integration-tests/src/tests/client/sharding_upgrade.rs

- use seeded rng everywhere
- reuse the same rng everywhere
- refactoring because the rng needs to be mutable and rust doesn't allow having it mutable in a closure and elsewhere at the same time
- minor other change - ensure catchup happens before the last block, otherwise some annoying errors are printed

feat: make the resharding tests more deterministic

---

core/store/benches/finalize_bench.rs
core/store/src/db/rocksdb.rs
core/store/src/lib.rs
core/store/src/migrations.rs
core/store/src/opener.rs
core/store/src/test_utils.rs
tools/database/src/make_snapshot.rs
tools/state-viewer/src/contract_accounts.rs

Avoid an unnecessary copy of the inserted value.
This improves the `finalize_bench.rs` by 40% - 50%, reducing the time to finalize a single `PartialEncodedChunk` from 130ms to 70ms and for `ShardChunk` it goes from 10ms to 6ms.
(Number before & after are on AMD Ryzen 9 5950X and 3200 MT/s DDR4)

perf: optimize `insert` and `insert_ser`

---

core/primitives-core/src/version.rs

This PR introduces `ProtocolFeature::PostStateRoot` which is included in nightly.
After a discussion with @nikurt and @jakmeier it was decided not to introduce a cargo feature for conditional compilation until it is actually needed. As far as I see all post-state-root code can be added without need for conditional compilation. The only switch we need is to enable post-state-root chunk and block production based on protocol version check.
This PR is a groundwork for https://github.com/near/nearcore/issues/9450.

feat: introduce post-state-root protocol feature

---

chain/chain/src/store.rs

Chunks can be MBs in size. We should not force a read from DB when it's not cached already.
Also alters the `chunk_exists` method to check the cache first. An `exists` call on the DB is still more expensive than looking up an `Arc` in the in-memory cache.

perf: don't read chunk when checking existence

---

neard/src/cli.rs

`--verbose` is not a `bool`, but a `String` argument, which is confusing.

Logging: Deprecate `--verbose`

---

chain/network/src/peer/peer_actor.rs

The clone was only there because of lifetime complaints that were due to the message being moved to the test observer after processing. We can avoid the clone entirely in non-test setup.
This is important because these messages can be 100MB+

perf: don't clone all incoming `PeerMessage`s

---

core/primitives/res/runtime_configs/parameters.snap
core/primitives/src/runtime/config_store.rs

The point of this file is to quickly see the current parameters.
Showing the nightly changes is not in this spirit IMO.

fix: remove nightly changes from parameters.snap

---

Cargo.lock
Cargo.toml

`cargo-deny advisories` complains about an old libsqlite-sys version.
We depend on it through rusqlite, which is only used in the
`estimator-warehouse`, a CI /&debug script. So it's not super
important but still worth updating.

chore: bump rusqlite version

---

Cargo.toml

This brings down the runtime of tests involving the runtime-tester by 40%, ie. 7.5s -> 4.5s for the runtime quickcheck added in #9602. Hopefully other tests will also profit from it, though I haven’t benchmarked it all.
The overall runtime on buildkite of the `cargo test nightly not integration-tests*` test seems, on a sample of 1, to be roughly the same (+- 10s) before addition of the test from #9602, so there should not be a significant delay in CI round-trip due to it, and it should mostly impact local development that rarely sees changes from dependencies.

optimize curve25519 for tests

---

tools/state-viewer/src/state_dump.rs

The state-dump command changes the amounts of validator accounts to match the epoch we're dumping state in, in case a validator stakes during that epoch, and the locked amount is different than the stake. The new locked amount computation is correct if a validator staked more, but overflows if the locked amount is smaller than the stake plus amount, which actually does occur on mainnet

fix(state-viewer): fix balance overflow in state-dump command

---

core/primitives/src/errors.rs
core/store/src/lib.rs
core/store/src/trie/iterator.rs
core/store/src/trie/mod.rs
core/store/src/trie/prefetching_trie_storage.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_storage.rs
core/store/src/trie/trie_tests.rs

Addressing
https://github.com/near/nearcore/blob/65af455f6f7f1bb8bc8cb399666468daebb28c66/core/primitives/src/errors.rs#L86

Add hash of the node to the MissingTrieValue

---

chain/chain/src/chain.rs
chain/client-primitives/src/types.rs
chain/client/src/tests/query_client.rs
chain/client/src/view_client.rs
chain/jsonrpc-primitives/src/types/transactions.rs
chain/jsonrpc/CHANGELOG.md
chain/jsonrpc/client/src/lib.rs
chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
chain/jsonrpc/src/api/transactions.rs
chain/jsonrpc/src/lib.rs
core/primitives/src/views.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs
integration-tests/src/user/rpc_user.rs

This PR is a part of RPC tx methods redesign https://docs.google.com/document/d/1jGuXzBlMAGQENsUpy5x5Xd7huCLOd8k6tyMOEE41Rro/edit?usp=sharing
Addressing point 3 in https://github.com/near/nearcore/issues/9542 and start working on https://github.com/near/nearcore/issues/6837
Changes:
- New field `status` appeared in the response of RPC methods `tx`, `EXPERIMENTAL_tx_status`, `broadcast_tx_commit`, `broadcast_tx_async`
- Added some comments with the explanations
In https://github.com/near/nearcore/issues/6837, Illia suggested to have the structure
```rust
enum BroadcastWait {
/// Returns right away.
None,
/// Waits only for inclusion into the block.
Inclusion,
/// Waits until block with inclusion is finalized.
InclusionFinal,
/// Waits until all non-refund receipts are executed.
Executed, …
```

add status field to response in RPC methods `tx`, `EXPERIMENTAL_tx_status`, `broadcast_tx_commit`, `broadcast_tx_async`

---

chain/jsonrpc/CHANGELOG.md
chain/jsonrpc/client/src/lib.rs
chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
chain/jsonrpc/src/lib.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs

This PR is a part of RPC tx methods redesign https://docs.google.com/document/d/1jGuXzBlMAGQENsUpy5x5Xd7huCLOd8k6tyMOEE41Rro/edit?usp=sharing
It has no usages on our RPC nodes, but I can't say anything about 3rd party nodes.
It is not covered by documentation in any of our sources.
If there's anyone who uses this method, I suggest switching to `tx` method instead.
The return type differs, giving more information to the user.

drop EXPERIMENTAL_check_tx RPC method

---

chain/chain/src/resharding.rs
chain/client/src/sync_jobs_actor.rs
core/store/src/trie/mod.rs
core/store/src/trie/state_snapshot.rs

For resharding, the snapshots must be created. We use the flat storage from snapshots to iterate over trie key, value to create child shards.
Creating snapshots is async and handled via the `StateSnapshotActor`. This PR adds logic to poll/wait for snapshots to be created before starting resharding.
We use the actix [notify_later](https://docs.rs/actix/latest/actix/prelude/trait.AsyncContext.html#method.notify_later) call to push the same resharding message back to the queue of the `SyncJobsActor` after a time period.

[resharding] Add logic to poll for snapshot before resharding

---

chain/chain/src/chain.rs
core/primitives-core/src/version.rs

Part of #9618.
In post-state-root, chunk production is moved before block production, thus we don't have a `Block` during applying chunk anymore. We need to make sure that all necessary data is still propagated to `Runtime::apply`.
It should've not have been an error for gas price, as it is taken from previous block in the general case: https://github.com/near/nearcore/blob/9c8d0bbec6a71876bb3317db2ade425f0077a184/chain/chain/src/chain.rs#L4120 However, when there is no chunk, there seem to be a very old error - it is taken from the same block.
Luckily, after `ProtocolFeature::FixApplyChunks` it is not an issue: when there is no chunk, gas price is not used at all. So I just start taking it from previous block for consistency, to ensure that in post-state-root current block can be safely …

fix: always take gas price from previous block

---

.github/workflows/rust.yml

Merge queue has already verified the changes as-if integrated into master, so there's no good reason to spend any additional compute resources running the tests one extra time after the merge.
We also have sufficient branch protections in place that a direct push to master is not a concern.

ci: do not run the CI checks after a merge queue

---

chain/network/src/peer/peer_actor.rs
chain/network/src/routing/edge_cache/mod.rs
chain/network/src/routing/graph_v2/mod.rs
chain/network/src/routing/graph_v2/testonly.rs
chain/network/src/routing/graph_v2/tests.rs

DistanceVector messages contain timestamped edges, which by default expire after 30 minutes. However, transmission of DistanceVectors is triggered only by changes to the network topology. As a result, nodes in a stable network will needlessly expire their DistanceVectors after 30 minutes. When a DistanceVector expires, the connection with the associated peer is terminated, resulting in unnecessary churn of network connections.
RoutingTableUpdate is an existing message type used by the V1 protocol to periodically flood refreshed edge nonces to the whole network. This PR passes the refreshed nonces from RoutingTableUpdate messages into the local storage for the V2 protocol so that the timestamps for stable DistanceVectors can be kept up to date.

V2 Routing: Refresh distance vector nonces

---

scripts/run_clippy.sh

I like to see the output of clippy when it's working. Passing --no-capture to enable that.

nit: always show full output in run_clippy.sh

---

core/store/src/trie/mod.rs
tools/state-viewer/src/cli.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/state_parts.rs

Part of https://github.com/near/nearcore/issues/9548
This commit adds a few cmdline options to the `neard view-state view-trie` tool:
- `--limit` - limits how many entries are printed to the output
- `--record-type` - only records of given type from the state trie would be printed
- `--from` - skip nodes with key lexicographically less than `from` (unless it is a prefix of `from`)
- `--to` - skip nodes with key lexicographically greater than `to`

Limit output for view-trie full mode

---

chain/jsonrpc-primitives/src/errors.rs
chain/jsonrpc-primitives/src/types/transactions.rs
chain/jsonrpc/src/api/mod.rs
chain/jsonrpc/src/api/transactions.rs
chain/jsonrpc/src/lib.rs
core/primitives/src/transaction.rs

Adding the possibility to pass object as params for tx status methods:
```
{
"jsonrpc": "2.0",
"id": "dontcare",
"method": "EXPERIMENTAL_tx_status", // could be "tx"
"params": {
"tx_hash": "6zgh2u9DqHHiXzdy9ouTP7oGky2T4nugqzqt9wJZwNFm",
"sender_account_id": "sender.testnet"
}
}
```
This is just a nice improvement, it looks cleaner.
But I specifically need this as a prep step for https://github.com/near/nearcore/issues/6837
Having json params will allow me to add new request parameter easier.
I thought about adding passing object to send tx methods as well, but the user has to pack it by borsh to be able to sign it.
So, deserialising SignedTransaction by serde makes no sense, I dropped this functionality.
Serialisation can still be useful to be able to dump tx to json so that humans may …

jsonrpc: allow parse object at tx status requests

---

Cargo.toml

The runtime of the whole test suite gets down by ~2.5% with this change.
Integration tests get a similar speedup.
CI times will be confirmed to not have too much change by it running on this PR.
See #9606.

optimize unsafe-libyaml for tests

---

Cargo.lock
Cargo.toml

https://github.com/near/nearcore/pull/9524#issuecomment-1759241641
I turned `~1.28` into `1.28` and ran `cargo update -p tokio`  as @frol recommended. 
`cargo deny --all-features check bans` returns two warnings but zero errors. 
I want to point out that we have several errors in the `advisories` section of `cargo-deny` output. I hope the team is well aware of those errors. 
Fixing the issue with `ed25519-dalek` requires an upgrade to crate version 2.0 and changes in codebase of nearcore

chore: update tokio

---

Cargo.toml

The runtime of the whole test suite gets down by ~2% with this change.
Integration tests and near-vm-runner also get a similar speedup.
CI times will be confirmed to not have too much change by it running on this PR.
See also #9606.

optimize dynasmrt for tests

---

core/primitives/src/runtime/config.rs
core/primitives/src/runtime/parameter_table.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/vm_kind.rs

People with M1 Macs run the neard node too, not just the test suites. Unfortunately a proper regression test for this is not obvious… I’ll think about it.
(Possibly)
Fixes #9665

runtime: "normalize" VMKind as soon as it is parsed

---

chain/chain/src/test_utils/kv_runtime.rs
chain/epoch-manager/src/adapter.rs

Even though the types are just aliases, still use correct type definitions.

nit: use correct type

---

.github/workflows/rust.yml

Lets try this out...
cc @Ekleog

ci: cache Rust build dependencies for faster builds

---

Cargo.toml

The runtime of the whole test suite gets down, on my test VM, from 224 seconds to 138 seconds, ie. 40% faster. Single-threaded runs show a 30% speedup over the whole test suite.
Integration tests show a 35% multi-threaded speedup, and 30% single-threaded speedup.
As for the bigger simple crates:
- near-vm-runner shows a decrease from 62s to 30s, ie. 50% speedup. Single-threaded tests show a 65% speedup.
- near-chain only shows a 10% speedup
- near-store shows a 25% speedup, or 35% single-threaded
- estimator-warehouse does not change, as it already rebuilds internally with optimizations
As for the time to build, building the whole test suite, including dependencies, is 20% slower, with 18 minutes to build as opposed to 15 minutes before, so a decrease in performance of 3 minutes.
However, …

optimize all dependencies for tests

---

chain/client/src/view_client.rs
chain/jsonrpc-primitives/src/types/transactions.rs
chain/jsonrpc/CHANGELOG.md
chain/jsonrpc/client/src/lib.rs
chain/jsonrpc/jsonrpc-tests/src/lib.rs
chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
chain/jsonrpc/src/api/mod.rs
chain/jsonrpc/src/api/transactions.rs
chain/jsonrpc/src/lib.rs
core/primitives/src/transaction.rs
core/primitives/src/views.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs
integration-tests/src/user/rpc_user.rs

Fixes https://github.com/near/nearcore/issues/6837
I'll need to update the [docs](https://github.com/near/docs) and [jsonrpc_client](https://github.com/near/near-jsonrpc-client-rs) (and maybe something else, I haven't already checked)
Important updates:
1. We have a new concept for all tx-related methods - `finality`. `finality` in the response is merged to master 2 weeks ago: https://github.com/near/nearcore/pull/9556. `finality` field in the request means "I want at least this level of confidence". So, the stricter the level, the longer the user needs to wait.
2. I decided to use `Final` as a default `finality` value because it gives the strongest guarantee and does not change backward compatibility for any of the methods (though, the waiting time may be increased sometimes to achieve …

jsonrpc: add finality to tx requests (`tx`, `EXPERIMENTAL_tx_status`), add method `broadcast_tx`

---

chain/chain/src/chain.rs
chain/chain/src/types.rs
chain/client/src/client.rs
chain/client/src/test_utils/setup.rs
chain/client/src/test_utils/test_env_builder.rs
core/chain-configs/src/client_config.rs
core/store/src/config.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/state_snapshot.rs
integration-tests/src/tests/client/state_snapshot.rs
nearcore/src/runtime/mod.rs
nearcore/src/test_utils.rs
test-utils/runtime-tester/src/run_test.rs
tools/speedy_sync/src/main.rs

1 of n parts to clean up state snapshot for resharding related changes.
This PR we are adding a new `StateSnapshotConfig` to store config.

[state_sync] Part 1: Add new state_snapshot_config to NearConfig

---

Cargo.lock
chain/chain/src/chain.rs
chain/chain/src/metrics.rs
chain/chain/src/resharding.rs
chain/chain/src/types.rs
chain/client/src/client.rs
chain/client/src/test_utils/setup.rs
core/chain-configs/Cargo.toml
core/chain-configs/src/client_config.rs
core/chain-configs/src/lib.rs
nearcore/src/config.rs
tools/speedy_sync/src/main.rs

- Added SplitStateConfig that configures the resharding batch size and delay between batches. Both can be used to throttle resharding. 
- Added metrics to check how much time do different parts of resharding take.

feat: resharding config allowing throttling

---

chain/client/src/client_actor.rs
chain/client/src/lib.rs
chain/client/src/sync/adapter.rs
chain/client/src/sync/mod.rs
chain/client/src/sync/sync_actor.rs
chain/network/src/lib.rs
chain/network/src/state_sync.rs
chain/network/src/types.rs
nearcore/src/lib.rs

Create dummy state sync actors.
Wrap them in an adapter that will be used to command and control them from client and network.

feat(state-sync) State sync actors

---

chain/chain/src/resharding.rs
core/store/src/config.rs
core/store/src/trie/state_snapshot.rs
integration-tests/src/tests/client/resharding.rs

A recent PR https://github.com/near/nearcore/pull/9993 cleaned up the logic of allowing state snapshots to be created even with the config is disabled. This is required for resharding.
This PR adds the appropriate tests (which I forgot to add previously) to verify this behavior.
This was originally a part of PR https://github.com/near/nearcore/pull/9681 but I had to close that.

[reshading] Enable snapshot creation for resharding with state_snapshot_type as ForReshardingOnly

---

core/store/src/trie/accounting_cache.rs
core/store/src/trie/mod.rs

This is an optimization, but is also preparation work for in-memory tries. The old behavior is that no matter what, we will get_ref first, but that will always return a ValueRef, so even if a flat storage value was inlined, we would ignored the inlined value and still go and lookup the value from the trie storage. Now, we would use the inlined value where possible.
Also, refactor the flat storage fetching logic so that it is contained within a function, and trie fetching logic is in another function. This will make it easier to introduce the in-memory fetching function. Otherwise it would be a giant mess. (The end result will be simpler than the prototype code (at least what is required to make the prototype code completely correct)).

Improve the performance of flat storage when values are inlined.

---

chain/chain/src/state_snapshot_actor.rs
chain/client/src/test_utils/test_env_builder.rs
core/store/src/metrics.rs
core/store/src/trie/state_snapshot.rs
integration-tests/src/tests/client/state_snapshot.rs
nearcore/src/lib.rs

This PR splits the MakeSnapshotRequest into two parts, DeleteSnapshotRequest and CreateSnapshotRequest.
The use case here is that now we can independently call DeleteSnapshotRequest for the case where we would only need to delete a snapshot (and not create one) for the ForReshardingOnly config of state_snapshot_type. (PR https://github.com/near/nearcore/pull/10012 )
DeleteSnapshotRequest (internal to state_snapshot_actor) takes an optional CreateSnapshotRequest.

[state_sync] Part 3: Split make_state_snapshot into a delete_snapshot + create_snapshot

---

core/store/src/cold_storage.rs
core/store/src/trie/insert_delete.rs
core/store/src/trie/mod.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_tests.rs

This is because for subtraction we don't need the value, and currently that value is just being passed around and eventually dropped. This refactoring is also useful for in-memory trie operations, because otherwise, deleting a node would require fetching the node's value (from on-disk trie) unnecessarily.

Split TrieRefcountChange to TrieRefcountAddition/Subtraction.

---

pytest/tests/mocknet/helpers/neard_runner.py
pytest/tests/mocknet/mirror.py

We'll change things to bind to "localhost" instead of "0.0.0.0", and make HTTP requests by SSH + curl on the remote server. It's also possible to set up an explicit SSH/SOCKS proxy, but that would require one for each server and would be long-lived, which might be a bit annoying for people running the test scripts

feat(mocknet): change HTTP request logic

---

chain/client/src/client.rs
chain/client/src/test_utils/test_env.rs
chain/client/src/test_utils/test_env_builder.rs
chain/epoch-manager/src/lib.rs
core/chain-configs/src/genesis_config.rs
core/primitives/src/epoch_manager.rs
core/store/src/trie/state_snapshot.rs
integration-tests/src/tests/client/resharding.rs

* generalized the missing chunk test
* added missing chunk test cases to cover the v2 resharding
* fixed the check for `get_next_block_hash_with_new_chunk` that didn't work for the V2 resharding
* fixed validators getting kicked out of the test when missing chunks
* introduced AllEpochConfigTestOverrides - overrides that allow changing the epoch config in tests

feat: resharding - tests for missing chunks

---

chain/chain/src/chain.rs
integration-tests/src/tests/client/block_corruption.rs
integration-tests/src/tests/client/field_changes.rs
integration-tests/src/tests/client/mod.rs

Moving `shard_id` check before any other chunk validation.
Adding test to check that blocks with invalid `shard_id` fail with `Error::InvalidShardId`.
The test is in a separate file because I am going to add more tests like it.

fix: check shard_id early

---

core/store/src/cold_storage.rs
core/store/src/trie/insert_delete.rs
core/store/src/trie/mod.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_tests.rs

Reverts near/nearcore#10006 . Breaks TrieChanges column. We'll look for a solution, but reverting in the meantime.

Revert "Split TrieRefcountChange to TrieRefcountAddition/Subtraction."

---

nightly/expensive.txt

Tests were moved without updating the list. Nayduck was trying to pick them up from the wrong location.

fix(state-sync): integration tests moved

---

Cargo.lock
chain/chain/src/resharding.rs
chain/client/src/sync/state.rs

It actually makes sense to label metrics by parent shard uid. Otherwise the same metric value is duplicated for the children. It's because the processing also happens per parent.

feat(resharding): label metrics with the parent shard uid

---

.github/workflows/master_fuzzer_binaries.yml

This should fix eg. https://github.com/near/nearcore/actions/runs/6723034524/job/18272218040, that failed due, AFAICT, to out of disk space. Hopefully with this bigger builder, we should not run out of disk space any longer. And rust compilation is pretty well-parallelized anyway, so the cost should not be significantly higher.

use larger runner for fuzzer binary builder

---

tools/state-parts-dump-check/src/cli.rs

fix the bug that monitoring was checking prev_epoch_height/prev_epoch_id/shard_id=x instead of latest_epoch_height/latest_epoch_id/shard_id=x

fix: state parts dump monitoring was not checking latest dumped directory

---

integration-tests/src/tests/client/resharding.rs

In stateless validation behaviour of aggregating outgoing receipts will change, it as object of many discussions ([example](https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/delaying.20chunk.20execution/near/399785439)). In any case, it requires specific test setup. I'm fine with checking that for given probabilities chain moves forward and for all generated txs final outcome does exist.
Resharding env is a perfect setup for this. We could consider making this specific test not dependent on resharding, but this is more work.
Also moving resharding_type into the env. Looks like it is the same for its lifetime, so this parameter can be removed from step_impl. 
Adding new tests test_latest_protocol...

test: use resharding setup to test missing chunks for latest version

---

core/store/src/cold_storage.rs
core/store/src/trie/insert_delete.rs
core/store/src/trie/mod.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_tests.rs

Previous change #10006 caused an issue because it made the borsh encoding of TrieRefcountSubtraction incompatible. This change makes it compatible by ignoring the value field when deserializing, and when serializing outputs an empty vector. Also adds a test to check that the previous encoding is compatible with the new one.

Reintroduce refactoring to split TrieRefcountChange to TrieRefcountAddition/Subtraction

---

chain/chain/Cargo.toml
chain/chain/src/chain.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/lib.rs
core/primitives/src/epoch_manager.rs

#10030 
Changing EpochSyncInfo to contain all data outlined in https://docs.google.com/document/d/14Itc9Hs7ewTRmcGANid9UCaYcJzaLzzM7FsvYYIFKDY/edit#heading=h.oixofhftbu1p
Blocking generation of epoch block hashes is a known problem.
IMO this is not a problem for header sync. Still, during regular block processing it is not ideal to spend additional time reading something that should have been saved in memory during the epoch.
I will change this part after I have an epoch sync node setup that allows for realistic delay estimation.
In the meantime the only optimisation is to collect this information from BlockInfos rather than from BlockHeaders, as BlockInfos is a much smaller column.

feat(epoch-sync): update EpochSyncInfo

---

.github/workflows/ci.yml

Previously, merge groups would try to compare protobuf against the previous merge queue commit. However, it’s not yet possible to do that comparison.
Instead, compare all ongoing merge queue commits against master, rather than against the commit just before them.

fix merge queue ci

---

chain/chain/src/test_utils/kv_runtime.rs
chain/client/src/test_utils/test_env.rs
core/store/benches/trie_bench.rs
core/store/src/test_utils.rs
core/store/src/trie/iterator.rs
core/store/src/trie/mem/loading.rs
core/store/src/trie/mem/metrics.rs
core/store/src/trie/mem/mod.rs
core/store/src/trie/mem/updating.rs
core/store/src/trie/mod.rs
core/store/src/trie/shard_tries.rs
core/store/src/trie/split_state.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_recording.rs
core/store/src/trie/trie_tests.rs
core/store/src/trie/update.rs
integration-tests/src/runtime_utils.rs
nearcore/src/metrics.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/balance_checker.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/verifier.rs
runtime/runtime/tests/runtime_group_tools/mod.rs
tools/state-viewer/src/contract_accounts.rs

so that we stop the proliferation of various test trie creation methods - or else, there will be even more when I add ability to construct tries with memtries.

[Test] Refactor create_*_tries() and ShardTries::test_*() into TestTriesBuilder.

---

pytest/tests/mocknet/README.md
pytest/tests/mocknet/mirror.py

Small fix of prefix module for `run_cmd` in `mirror.py` script

fix: Small fix mirror script

---

test-utils/style/src/lib.rs

This shouldn’t be accidentally happening especially in cases where user might have passed `--locked` to the `cargo test` command or something like that.

ci: make sure to not update lockfile as part of style checks

---

tools/fork-network/src/cli.rs

Fix for #10034
`chain_id_suffix` can now start with however many hyphens we want

fix(fork-network): allow hyphen values for chain_id_suffix

---

core/store/src/trie/mem/loading.rs
core/store/src/trie/mem/updating.rs
core/store/src/trie/mod.rs
core/store/src/trie/trie_recording.rs
core/store/src/trie/update.rs
integration-tests/src/tests/client/flat_storage.rs

Previously in #9991 , `Trie::get` was improved so that it would not issue an on-disk lookup of a value if the value was fetched from flat storage and was already inlined in flat storage. However, during contract execution, the `Trie::get` code path is never executed; instead we still always go through `Trie::get_ref`.  The problem is that `Trie::get_ref` always throws away the value even if it's already available via `FlatStateValue::Inlined`, so that means during contract execution, the flat state inlined value is useless.
This PR applies the same optimization for contract executions. In fact, it cleans up the code so that it's less confusing than the state that the previous PR left it in. We're pretty much back to `get_ref` and `get`, except that `get_ref` is now changed to …

[Trie] Optimize runtime trie access by avoiding wasted lookups of inlined values.

---

integration-tests/src/tests/client/block_corruption.rs
nightly/expensive.txt

We want to make sure that every field in the block is properly validated.
One of the ways to do that is to flip random bits in the correct block and check that the resulting block is considered invalid. We can also add processing of correct blocks to the same test.
This test checks that our system is resilient to random changes in block in two ways:
- blocks with random changes are not processed
- blocks with random changes do not affect normal block production
Each block contains one 'send' transaction.
First three blocks are produced without changes.
For the fourth block we are calculating two versions – correct and corrupt.
Corrupt block is produced by
- serialising correct block
- flipping one bit
- deserialising resulting string
- resigning the resulting block
If the corrupt block …

add bit flip test

---

.github/workflows/ci.yml
chain/jsonrpc/build_errors_schema.sh
pytest/lib/branches.py
pytest/tests/sanity/db_migration.py
pytest/tests/sanity/upgradable.py
scripts/state/update_res.py

This should hopefully free up the runners for other jobs, reduce CPU time these tests take (thus saving money) and test latency (thus saving even more money!)

ci: prebuild and share a single neard binary between different jobs

---

tools/state-parts-dump-check/src/cli.rs

Problem:
The current state parts dump monitoring [dashboard](https://nearinc.grafana.net/d/e2777598-608e-4a99-b522-e720d9334c03/state-parts-dump?orgId=1&var-node_id=.%2A&var-chain_id=mainnet&from=1699037114000&to=1699041014000) has gaps on panels %dumped, and %valid. 
Fix:
The problem happens because the monitoring app works by checking the dumped parts, if parts dumped < total parts, it will sleep 60s then check again. Every time it checks, it will first reset the num parts metrics including total parts, dumped parts, valid parts and invalid parts all to 0. Since %dumped = dump parts/ total parts, and %valid = valid parts / dumped parts, when denominator becomes 0, the result will be a gap on the graph. This happens by chance, I guess depending on when prometheus server pulls the metric, …

fix: remove unnecessary gaps in dump monitoring graphs

---

integration-tests/src/tests/client/resharding.rs

Minor follow-up after TestReshardingEnv changes: `step_impl` became small enough to be called directly, so we can rename it with just `step`.

rename: step_impl -> step

---

chain/client/src/client.rs
chain/client/src/client_actor.rs
core/primitives/src/state_record.rs
tools/state-viewer/src/commands.rs

- group records by account id and aggregate it to get the total size of all records belonging to each account is used
- re-arrange records to be sorted by account id, rather than type and account id
results on mainnet
```
2023-11-07T13:25:00.063905Z  INFO state_viewer: s0.v1
2023-11-07T13:25:00.063968Z  INFO state_viewer: StateStats {
total_size: 6.5 GB,
total_count: 18507133,
average_size: 351 B,
middle_state_record: StateStatsStateRecord {
account_id: "66fde23ac459779474beb6d1f8b72164e67946de.lockup.near",
size: 344.9 KB,
},
top_accounts: [
StateStatsStateRecord {
account_id: "athlete.promotional.basketball.playible.near",
size: 10.0 MB,
},
StateStatsStateRecord {
account_id: "amm.counselor.near",
size: 11.7 MB,
},
StateStatsStateRecord {
account_id: …
```

feat(resharding): state-stats improvements

---

.github/workflows/ci.yml

This will hopefully make CI cache actually be reused by MacOS, which before that was always restarting from scratch and thus ended up being the last one to complete.
Splitting linux and linux-nightly caches should hopefully help a bit with CI times too, but this will most likely be much less impactful.

Reuse CI cache for MacOS too

---

tools/state-parts-dump-check/src/cli.rs

change default prometheus addr from 0.0.0.0:9090 to 4040

state parts dump to use 4040 as default prometheus port

---

chain/jsonrpc-primitives/src/types/validator.rs
chain/jsonrpc/client/src/lib.rs
chain/jsonrpc/src/api/validator.rs
core/primitives/src/types.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs
integration-tests/src/user/rpc_user.rs
tools/state-parts-dump-check/src/cli.rs

1. removed the previously added `validator_by_epoch_id()` api
2. modified the pre-existing `validators(maybe_block_id)` api to be `validators(maybe_epoch_reference)`. Basically now within rust, we can input `None`, or `Some(EpochReference::EpochId(epoch_id))` or `Some(EpochReference::BlockId(block_id))`. 
3. added some unit tests to test all currently supported json inputs to the `validators` RPC endpoint are working. When users send requests to the near rpc validators endpoint, they could use as input the legacy format `[block_id]` or the map format `{"epoch_id": epoch_hash}` or `{"block_id": block hash/height}`

modify existing validators() rust api to take both epoch_id and block_id

---

Cargo.lock
chain/chain/src/chain.rs
core/primitives/Cargo.toml
core/primitives/src/epoch_manager.rs
core/primitives/src/errors.rs
integration-tests/src/tests/client/epoch_sync.rs

First part of #10031
Adding support for `EpochInfo` validation through `epoch_sync_data_hash` in new epoch sync.
Included in PR:
- reconstruction of `BlockInfo` headers
- calculation of `epoch_sync_data_hash` from `EpochSyncInfo`
- bad attempt at good errors in all of that
- test for both `BlockInfo` and `epoch_sync_data_hash` reconstruction
Coming next: epoch sync testing tool, specifically command to test that reconstructed `epoch_sync_data_hash` matches recorded `epoch_sync_data_hash` on all real data in testnet/mainnet.

feat(epoch-sync): calculate legacy epoch_sync_data_hash from EpochSyncInfo

---

integration-tests/src/tests/nearcore/rpc_nodes.rs

this test checks that the result of the EXPERIMENTAL_protocol_config rpc matches the stored protocol config, but the rpc response will give the latest stable protocol version's config, and the protocol config returned when asking for ProtocolVersion::MAX is going to be the nightly one, which might not match the stable protocol config

fix(integration-tests): fix protocol version in test_protocol_config_rpc

---

chain/client/src/sync_jobs_actor.rs
core/store/src/flat/manager.rs
core/store/src/flat/storage.rs
core/store/src/flat/store_helper.rs
core/store/src/trie/shard_tries.rs
integration-tests/src/tests/client/flat_storage.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/state_dump.rs
integration-tests/src/tests/client/sync_state_nodes.rs
tools/flat-storage/src/commands.rs

This PR has two main changes
1. It adds a function to remove data associated with a trie from store `remove_flat_storage_for_shard`. We clear the cache and view cache and remove all data associated with the shard_uid from RocksDB
2. Change the flat storage `clear_state` and `remove_flat_storage_for_shard` to accept a `store_update` instead of directly committing the changes to store. This is helpful to club a set of RocksDB changes from other store_update.

[store] Add functionality to delete trie from store

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/ondemand_fuzzer_binaries.yml

We have tests that fail with `cargo test`, and this throws off `cargo bolero list`, that runs `cargo test` to list the fuzzers.
With this change, we add camshaft/bolero#195, that ignores such failures and actually lists all fuzzers.
This should fix the issue, that all the latest uploads to the fuzzers bucket actually were empty tarballs.

fix: use cargo-bolero with a fix for `cargo bolero list` with failing tests

---

chain/jsonrpc-primitives/src/types/transactions.rs
chain/jsonrpc/src/lib.rs
core/primitives/src/views.rs

This PR tries to fix [test_check_unknown_tx_must_return_error](https://github.com/near/nearcore/blob/0e0f191ea31c173e266530505cf7147b14f509ab/integration-tests/src/tests/nearcore/rpc_nodes.rs#L420)
Master code: 
The timeout() returns Elapsed if after polling there are no result, and if this happens, we return a TIMEOUT error instead of the specific error that we got that was not returned as a result. For example, when polled result matched `Err(err @ near_jsonrpc_primitives::types::transactions::RpcTransactionError::UnknownTransaction {
..
})`, there are some edge cases that will always be TIMEOUT; and if the transaction never got finalized within timeout, then the error returned will always be TIMEOUT too.
The change:
use a mutable variable to represent the result we got inside the …

fix: test_check_unknown_tx_must_return_error nayduck test

---

chain/jsonrpc/client/src/lib.rs
chain/jsonrpc/src/api/validator.rs

Problem:
I have a piece of code in my monitoring tool:
```
let latest_epoch_response = rpc_client
.validators(Some(EpochReference::EpochId(EpochId(latest_epoch_id))))
.await.unwrap()
```
And on latest master, this is failing with
```
RpcError { error_struct: Some(RequestValidationError(ParseError { error_message: "Failed parsing args: data did not match any variant of untagged enum BlockId" })), code: -32700, message: "Parse error", data: Some(String("Failed parsing args: data did not match any variant of untagged enum BlockId")) }
```
Solution: 
change validators() rust api by letting it directly call the "validators" method.

fix: make validators() rust api compatible with RPC servers 

---

chain/network/src/config.rs
chain/network/src/config_json.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/snapshot_hosts/mod.rs
chain/network/src/snapshot_hosts/tests.rs

This PR configures a hard limit on the size of SnapshotHostsCache. The internal storage is replaced with `lru::LruCache`, which implements a simple least-recently-used eviction policy.
In the short term, this will prevent memory exhaustion via unbounded addition of entries to the cache.
In the long term, we may wish to revisit and implement a more sophisticated eviction policy, especially after we implement a reputation system for peers sharing state parts.

Bound the size of SnapshotHostsCache

---

integration-tests/src/tests/nearcore/rpc_error_structs.rs
nightly/expensive.txt

Tests were removed so I am excluding them from nightly nayduck run.
One test was changed [here](https://github.com/near/nearcore/pull/9596/files#r1386748297).

fix(nightly): Remove deleted test from list

---

chain/client/src/adapter.rs
chain/client/src/client_actor.rs
chain/client/src/test_utils/setup.rs
chain/client/src/view_client.rs
chain/jsonrpc/res/last_blocks.js
chain/jsonrpc/res/network_info.html
chain/network/src/announce_accounts/mod.rs
chain/network/src/announce_accounts/tests.rs
chain/network/src/client.rs
chain/network/src/lib.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/network_state/routing.rs
chain/network/src/peer_manager/peer_manager_actor.rs
chain/network/src/peer_manager/testonly.rs
chain/network/src/peer_manager/tests/routing.rs
chain/network/src/peer_manager/tests/tier1.rs
chain/network/src/stats/metrics.rs
chain/network/src/store/mod.rs
chain/network/src/testonly/fake_client.rs
chain/network/src/types.rs
tools/chainsync-loadtest/src/network.rs

This reverts commit 5f942be30fa0aeab3ddf97e2fb289e6835370dc7 in order to fix some integration tests.
x "pytest sanity/network_drop_package.py --features nightly",
"pytest sanity/network_drop_package.py",
x "pytest sanity/proxy_restart.py --features nightly",
"pytest sanity/proxy_restart.py",
x  "pytest sanity/proxy_simple.py --features nightly",
"pytest sanity/proxy_simple.py",
x  "pytest sanity/restart.py --features nightly",---Jan
"pytest sanity/restart.py",---Jan
x "pytest sanity/sync_ban.py false --features nightly",
"pytest sanity/sync_ban.py false",
"expensive integration-tests integration_tests tests::client::block_corruption::check_process_flipped_block_fails --features nightly",
"expensive integration-tests integration_tests …

Revert "Deprecate AnnounceAccounts (#10024)"

---

pytest/tests/sanity/restart.py

The test [`tests/sanity/restart.py`](https://github.com/jancionear/nearcore/blob/7c0b58fd02a7ecc401736628cc977f6c8cff5fbf/pytest/tests/sanity/restart.py)  is failing because one of the validators gets kicked out. Let's disable kickout to make the test pass again.
The test sets up a network with two validator nodes and epoch size equal to 10 blocks. It lets the network run for 20 blocks, then stops both nodes and starts them again. After the restart it checks that the blockchain still produces blocks.
The problem is that validators might miss some blocks due to the restart, and then they're kicked out for it. Once one of the two validators gets kicked out, the blockchain stops producing blocks. The kickout threshold was set at 80%, so if a validator misses even one block out of four, that …

fix: sanity/restart.py: don't kick out validators

---

pytest/lib/cluster.py
pytest/tests/sanity/rpc_finality.py

https://github.com/near/nearcore/pull/9644 added a new RPC method for sending transactions, and added unused "wait_until" arguments to the existing ones. This change was actually not a no-op for the "broadcast_tx_commit" method, since now that method will wait until all transactions and descendant receipts are final, whereas the previous behavior was closer to the new "INCLUDED" "wait_until" parameter, and we used to just wait for the receipt outcomes to show up, but would return before they're executed and finalized.
So fix it by making send_tx_and_wait() call the send_tx method to get something closer to the old behavior.
Also, an unrelated problem with this test is that the "consensus" change to the config were put in the wrong place, so that measure to decrease the flakiness of this …

fix(pytests): fix rpc_finality.py

---

nightly/expensive.txt

`check_process_flipped_block_fails` takes around 7 minutes locally, but I have no idea how powerful Nayduck machines are, so setting timeout to 20 minutes.
Default timeout is 3 minutes, so this test times out constantly right now.

fix(nayduck): add realistic timeout for check_process_flipped_block_fails

---

Cargo.lock
core/store/Cargo.toml
core/store/src/trie/mem/arena/alloc.rs
core/store/src/trie/mem/arena/mod.rs
core/store/src/trie/mem/flexible_data/children.rs
core/store/src/trie/mem/loading.rs
core/store/src/trie/mem/mod.rs
core/store/src/trie/mem/node/encoding.rs
core/store/src/trie/mem/node/mod.rs
core/store/src/trie/mem/node/tests.rs
core/store/src/trie/mem/updating.rs
tools/database/src/memtrie.rs

This solves an issue with the current memtrie implementation that mmap requires either NO_RESERVE or overcommit enabled, by avoiding mmap altogether.
It's not actually necessary to have contiguous memory. We'll instead have chunks of contiguous memory. Individual allocations will be entirely within a chunk anyway.
Instead of using `usize` to represent a position in the arena, we now use `ArenaPos`, which simply is just the chunk index and position within chunk. We just needed some simple tweaks to use ArenaPos everywhere and there are no big changes.
I've picked 4MB as the chunk size, so that the memory overhead for not being able to allocate a big value is at most 8KB (I think in practice it's at most key size (2k?) + value size (4k?)) per chunk. So with 16GB of total size the overhead …

[Memtrie] No longer use mmap for memtrie arena.

---

chain/chain/src/chain.rs
chain/client/src/client.rs
chain/client/src/sync_jobs_actor.rs
core/chain-configs/src/client_config.rs
nightly/pytest-sanity.txt
pytest/lib/resharding_lib.py
pytest/tests/sanity/resharding.py
pytest/tests/sanity/state_sync_fail.py

- Added a simple nayduck test for resharding. It checks that the shard layout version and number of shards change at the right block. 
- Added configuration for the delay while waiting for the state snapshot. Needed it, otherwise the test was all over the place. 
- Refactored some common resharding test logic in nayduck.

feat(resharding): simple nayduck test for resharding

---

docs/practices/testing/README.md
docs/practices/testing/python_tests.md

Summary:
- Update Runner Test Results URL.
- Fix `cargo nextest` command for running `cross_shard_tx`test target.
- Update outdated / not working links in the documentation.
`python_tests.md` file already has a guidance about cargo build command for local test runs.
Feature guards are test-specific. Depending on what test do we want to run, we should modify the script below accordingly.
> ## Compiling the client for tests
> The local tests by default expect the binary to be in the default location for a
> debug build (`{nearcore}/target/debug`). Some tests might also expect
> test-specific features guarded by a feature flag to be available. To compile the
> binary with such features run:
> ```
> cargo build -p neard --features=adversarial
> ```

Fix test related documentation issues

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/ondemand_fuzzer_binaries.yml
Cargo.lock
Cargo.toml
runtime/near-vm-runner/src/prepare/prepare_v1.rs
runtime/near-vm-runner/src/prepare/prepare_v2.rs
runtime/near-vm-runner/src/tests/fuzzers.rs
runtime/near-vm/types/Cargo.toml
runtime/near-vm/types/tests/partial-sum-map/main.rs
test-utils/runtime-tester/src/fuzzing.rs

See discussion at [1]. Here, the solution is what would be a bad solution for bolero upstream (because it no longer works with un-harnessed fuzzers), but is fine enough for our use case.
[1] https://github.com/camshaft/bolero/issues/196

use a hack to make fuzzer building actually work

---

.github/workflows/ci.yml
.github/workflows/neard_assertion_binary.yml
.github/workflows/neard_linux_binary.yml
.github/workflows/neard_nightly_binary.yml

neard binaries built on Ubuntu 22 are no compatible with Ubuntu 20 libs:
$ ./neard --version
./neard: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./neard)
./neard: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./neard)
./neard: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./neard)

Ubuntu 20 distro for GHA binary builds

---

chain/chain/src/chain.rs
chain/chain/src/store.rs
core/store/src/flat/manager.rs

Adding logs for generic GC.
Tracing for GC during the last block of the epoch during which resharding happened.

[tracing] Add tracing for Garbage Collection

---

chain/chain/src/chain.rs
chain/chain/src/metrics.rs
chain/chain/src/resharding.rs
chain/client/src/client.rs
chain/client/src/sync/state.rs
chain/client/src/sync_jobs_actor.rs
core/chain-configs/src/client_config.rs
nightly/pytest-sanity.txt
pytest/lib/cluster.py
pytest/lib/resharding_lib.py
pytest/lib/utils.py
pytest/tests/sanity/resharding.py
pytest/tests/sanity/resharding_error_handling.py
tools/database/src/commands.rs
tools/database/src/corrupt.rs
tools/database/src/lib.rs
tools/database/src/utils.rs

- added a new ReshardingStatus - Failed - and use it when resharding fails
- made a number of delays and timeouts configurable so that it's testable
- added a new nayduck test for checking the error handling
- added a bunch of new debug, warn and error logs
https://nayduck.near.org/#/run/3270

feat(resharding): implemented error handling and test for it

---

Cargo.lock
tools/fork-network/Cargo.toml
tools/fork-network/src/cli.rs
tools/fork-network/src/single_shard_storage_mutator.rs
tools/fork-network/src/storage_mutator.rs

https://near.zulipchat.com/#narrow/stream/297873-pagoda.2Fnode/topic/New.20betanet.20infra

[fork-network] Optimize amend-access-keys using in-memory tries.

---

.github/workflows/neard_linux_binary.yml
.github/workflows/neard_release.yml
Dockerfile

In this PR I split the neard release WF into 2 jobs: 1 for binary and second for docker image.
In addition, I make the Dockerfile standalone so it can function independent of the binary build job.
test run [here](https://github.com/near/nearcore/actions/runs/6889456250/job/18740477267)

Standalone dockerfile

---

chain/jsonrpc-primitives/src/types/split_storage.rs
chain/jsonrpc-primitives/src/types/status.rs
chain/jsonrpc/res/debug.html
chain/jsonrpc/res/split_store.html
chain/jsonrpc/src/lib.rs

Add a new debug page: `/debug/pages/split_store`
This page provides basic information about the state of split store.
An example report looks like this:
Fixes: https://github.com/near/nearcore/issues/9549

feat: add a debug page with basic information about split store

---

chain/chain-primitives/src/error.rs
chain/chain/src/chain.rs
chain/chain/src/metrics.rs

The metric `near_num_invalid_blocks` counts the number of invalid blocks processed by neard. Up until now there was no information why the blocks are invalid. Let's add a label that describes what kind of error caused the block to be invalid. This will make it easier to diagnose what's wrong when there are lots of invalid blocks.
The label is called "error", an example prometheus report looks like this:
```
near_num_invalid_blocks{error="chunks_missing"} 1234
```
Fixes: https://github.com/near/nearcore/issues/9661

feat: add error type label to the `near_num_invalid_blocks` metric

---

tools/state-viewer/src/commands.rs

Added simple stat about how well the middle account splits the shard. 
```
s0
split_size: "3.3 GB : 245 B : 3.3 GB",
split_percent: "49:0:49",
s1
split_size: "0 B : 6.0 GB : 0 B",
split_percent: "0:100:0",
s2
split_size: "2.8 GB : 168.2 MB : 3.0 GB",
split_percent: "47:2:49",
s3
```

feat(resharding): added state split statistics to the state stats tool

---

test-utils/style/src/lib.rs

Previously cargo themis (builds code) and cargo clippy (checks entire crate) condended with each other for the target directory lock and most likely invalidated each other’s cache, at least to some extent.
Keeping target directories between the two separate resolves this problem altogether.

style: improve how CARGO_TARGET_DIR is handled

---

core/chain-configs/src/client_config.rs

Without the individual defaults for fields it was impossible to set only some fields while leaving others out. Now by setting only some fields the rest will get the sensible defaults. It was annoying for mocknet and would be for node maintainers if they need to adjust this config.

feat(resharding): set defaults for state split config

---

chain/network/src/config_json.rs
core/chain-configs/src/client_config.rs
nearcore/src/config.rs

Discovered simplified way to have default values in serde for structs only when ALL fields have a default.
We can have a #[serde(default)] attribute for the whole struct and any missing fields are picked up from the Default::default() implementation of the struct.
Playground example
```
#[derive(Serialize, Deserialize, Debug)]
#[serde(default)]
struct Point {
x: i32,
y: i32,
}
impl Default for Point {
fn default() -> Self {
Self { x: 1, y: 2 }
}
}
#[test]
fn serde() {
let point = Point { x: 10, y: 20 };
let serialized = serde_json::to_string(&point).unwrap();
println!("serialized = {}", serialized);
let deserialized: Point = serde_json::from_str(&serialized).unwrap();
println!("deserialized = {:?}", deserialized); // I get Point { x: 10, y: 20 }
let serialized = "{\"x\":15}";
let …
```

[cleanup] Minor cleanup in serde default

---

pytest/tests/sanity/rpc_state_changes.py

https://github.com/near/nearcore/pull/9658 stabilized a protocol feature that restricts creating top level accounts unless you're the registrar, and in this test we were trying to create one. change it to be a subaccount of the tx signer

fix(pytests): fix rpc_state_changes.py

---

.github/workflows/nightly_nayduck.yml

Considering in four weeks of always seeing red on all PRs, we still have not fixed the nayduck tests… I’m suggesting we remove it so that we get the signal again, of whether a PR passes tests or not.
Indeed, this failing means that we no longer see the actual value added by other tests, and especially the green checkmark that would otherwise be a good indicator that a PR is ready to be merged: we now need to manually check and scroll the statuses list in order to figure out whether a PR is actually ready for merge.
Currently, this is a net negative in developer experience. I’m not questioning the nayduck problem, but the solution seemed wrong to me, and time has shown it does not actually works. We need another solution, like a round-robin of everyone having to look at nayduck once a week …

remove the currently omnipresent red mark

---

chain/chain/src/chain.rs
chain/chain/src/lib.rs
chain/chain/src/update_shard.rs

This is just a refactor, which shouldn't change any behaviour of the code but prepares it for stateless validation.
We came up with idea that logic contained in `get_apply_chunk_job_*` method should not depend on Chain that heavily. Here I extract all logic where Chain is required to `get_apply_chunk_job` only. All remaining logic is moved to `update_shard.rs`. For better readability, I introduce more updates:
* "apply_chunk" is mostly replaced with "update_shard" because it is closer to what actually happens. When new chunk exists, we indeed apply it. But in two other cases listed in `ShardUpdateReason` enum we only update validator accounts or process split state info.
* excessive info about blocks and chunks is replaced with exact `BlockContext` and `ShardUpdateReason` contents which …

refactor: prepare shard update impl for stateless validation

---

.cargo/audit.toml
Cargo.lock
Cargo.toml
chain/chain/Cargo.toml
chain/client-primitives/Cargo.toml
chain/client-primitives/src/types.rs
chain/client/Cargo.toml
chain/client/src/debug.rs
chain/client/src/info.rs
core/o11y/Cargo.toml
core/o11y/src/subscriber.rs
core/primitives/src/upgrade_schedule.rs
core/primitives/src/utils.rs
deny.toml
genesis-tools/genesis-csv-to-json/src/csv_parser.rs
neard/Cargo.toml
neard/src/cli.rs
test-utils/store-validator/Cargo.toml
test-utils/store-validator/src/main.rs
tools/state-viewer/Cargo.toml
tools/state-viewer/src/commands.rs

In particular:
- cpufeatures
- ahash
- hashbrown
- criterion
- pretty-assertions
- tracing-subscriber
- chrono
- h2
- tempfile
- hermit-abi
Also:
- replaced ansi_term with yansi
- removed our dependency on atty altogether
All this together, alongside with https://github.com/near/nearcore/pull/10201, gets us to zero cargo-audit warnings :)
This might be best reviewed commit-by-commit, to more easily see which changes are due to which dependency (though I tried bumping chrono and replacing ansi_term at the same time, resulting in alternating commits as my test compilations made progress)

Bump various dependency versions

---

.github/workflows/ci.yml

Note: I’m removing the preparatory "Build neard" job here. The reason is twofold:
- I didn’t manage to get coverage output to actually write *.profraw files without the whole target folder
- Uploading the whole compressed (to 3G) target folder as an artifact takes 6 minutes for compression and 15 minutes for upload
- Just building, on the commit on which I was, took 2 minutes, multiplied by 4 it gives 8 minutes, so quite a lot less than the compress+upload time
- So overall we’re spending less time by just redoing the compilation work, as opposed to uploading+downloading it; and the tests themselves are relatively fast too so having them on the bigger machines (8cores, enough for them to not be the bottleneck) shouldn’t hog them for too long.

introduce code coverage analysis in CI

---

integration-tests/src/tests/client/process_blocks.rs

The main motivation for the test is to see how garbage collection will behave without caches if we restart from the middle of an epoch.

Add test_long_chain_with_restart_from_snapshot

---

chain/chain/src/chain.rs
chain/chain/src/store.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/lib.rs
integration-tests/src/tests/client/resharding.rs

Tested on updated #10193
`is_next_block_epoch_start` reads `BlockInfo` of the first block of the epoch, which is not correct in the case of garbage collection.
The previous version of the test was passing, because that `BlockInfo` was still in the cache of the epoch manager (as we call `is_next_block_epoch_start` on every block)
Implemented safer version of `is_next_block_epoch_start` -- `is_last_block_in_finished_epoch` (didn't think too much about the name, open to suggestions).
`is_last_block_in_finished_epoch` works by relying on the fact that if we processed block, and it was the last block of an epoch according to `is_next_block_epoch_start`, then we wrote an `EpochInfo` with the hash of that block, and `EpochInfo` is not garbage collectible.

reintroduce clear_resharding_data

---

pytest/tests/sanity/rpc_tx_submission.py

https://github.com/near/nearcore/pull/9596 removed an RPC Method and altered this test, but the previous version of the test sends 3 transfer txs with amounts 100, 101 and 102, and now the test only sends 2 transfer txs with amounts 100 and 101. So update the expected balance changes to reflect that

fix(pytest): fix rpc_tx_submission.py

---

tools/state-parts-dump-check/src/cli.rs

Problem: 
Occasionally, the monitoring will be stuck. What happens is there are a few parts for which the process_part() is called, but never finished, i.e. not retried, not success, not failed.
My guess is that the get_part().await somehow is stuck waiting forever, and since there was no timeout bound for the process_part(), the tokio task that runs process_part could be hung forever, thus the monitoring app is stuck.
I tried making the task for part_id = 100 sleep for 1000000 seconds, and the program finishes all other parts except this one and hangs. This is similar to what I see on monitoring node.
Solution:
bound process_part by a timeout, and initiate retry if timeout passed. Thus no matter for which reason the task hangs, it will retry itself.
Note, the timeout is set to 10 mins …

fix(state-parts-dump-check): bound process_part by timeout

---

chain/chain-primitives/Cargo.toml
chain/chain-primitives/src/error.rs
chain/chain/Cargo.toml
chain/chain/src/chain.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/epoch-manager/src/adapter.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/errors.rs
integration-tests/src/tests/client/epoch_sync.rs

#10031 
This PR is a step towards `EpochSyncInfo` validation that doesn't actually include any validation.
I want to combine creation of necessary `StoreUpdate` with validation, because to validate `EpochSyncInfo` we need to rebuild `BlockMerkleTree` for every block in the epoch, but also not commit it if anything goes bad, and that is supported in `ChainStoreUpdate`.
Creation of `StoreUpdate` is already a big change, so I want to do a separate PR for it.
To test that we process `EpochSyncInfo` correctly I create a VERY hacky test, that should not be included in CI ever. Right now it works as intended, but if we change implementation of any sync, we will have to rewrite this test.
I hope I will add epoch sync into `run_sync_step` flow soon enough for us to replace this test with something …

feat(epoch-sync): EpochSyncInfo processing

---

pytest/tests/sanity/recompress_storage.py
scripts/nayduck.py

allows to cancel pending tests for given build ID
```
./scripts/nayduck.py --cancel 3288
Scheduling tests for: 
branch - remotes/origin/disable-store-validator-build 
commit hash - c221f8f92cb3e20767a0fa2c66a9b64c34ea3cf5
Sending request ...
Cancelled 1 tests
```

Nayduck cli - add cancel option

---

tools/debug-ui/package-lock.json
tools/debug-ui/package.json

Supersedes https://github.com/near/nearcore/pull/10232.  That PR had a conflict due to a recent merge and it was easier to create a new PR instead of fixing the conflict there.

nit: upgrade react-router-dom from 6.17.0 to 6.18.0

---

integration-tests/src/tests/nearcore/rpc_error_structs.rs
integration-tests/src/tests/nearcore/rpc_nodes.rs
nightly/expensive.txt

I dropped check_tx method https://github.com/near/nearcore/pull/9601
But I decided to leave this test and I replaced `check_tx` with `tx_status`. `tx_status` returns timeout instead of `does_not_track_shard`. Instead of fixing this, I suggest to wait until we implement forwarding logic, I planned to work on forwarding anyways.
Let's disable the test for now, and hopefully, in one day, we will return the real status to the user.

fix(nightly): disable broken test

---

chain/chain/src/chain.rs
chain/chain/src/flat_storage_creator.rs
chain/chain/src/test_utils.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chunks/src/client.rs
chain/chunks/src/lib.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/debug.rs
chain/client/src/info.rs
chain/client/src/view_client.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/shard_tracker.rs
chain/epoch-manager/src/validator_selection.rs
core/primitives/src/shard_layout.rs
core/store/src/cold_storage.rs
core/store/src/genesis/initialization.rs
genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs
genesis-tools/genesis-populate/src/lib.rs
integration-tests/src/tests/client/state_dump.rs
nearcore/src/runtime/mod.rs
nearcore/src/state_sync.rs
tools/amend-genesis/src/lib.rs
tools/mock-node/src/main.rs
tools/state-viewer/src/epoch_info.rs
tools/state-viewer/src/state_changes.rs

There are many places in the repo where we assume that the valid shard ids are in the range [0, num_shards).  This PR is an attempt to improve the current state of affairs.
- ShardLayout introduces a new method: `fn shard_ids()` which still employs the above assumption.
- All instances above assumption are moved to calls to the above function so that the assumption is centralised in a single place.
Future work:
- If we have a function that returns a list of shard ids, we do not need `fn num_shards()`.  It can be derived from the previous function.  It should be removed for consistency reasons.

refactor: reduce places where we assume shard ids are contiguous 

---

.github/workflows/ci.yml
runtime/near-test-contracts/build.rs
scripts/rustc-coverage-wrapper.sh

When collecting coverage we want to instrument only the crates in our workspace, and not the external dependencies. There is no value in doing otherwise – we don’t run tests for our dependencies anyway. Furthermore, instrumenting the external dependencies runs a risk of significant performance regressions, such as seen in #10201.

coverage: apply `-Cinstrument-coverage` to workspace crates only

---

Cargo.lock
Cargo.toml

Contains https://github.com/near/near-account-id-rs/pull/20

chore: Bump near-account-id version

---

.github/workflows/master_fuzzer_binaries.yml

Fuzzer building runs on rustc nightly, which can have a different set of warnings than rustc stable. Rather than introduce a new compilation step for all the PRs, just compile fuzzers without caring about warnings.
Fixes a recent fuzzer building issue, probably caused by a nightly upgrade: https://github.com/near/nearcore/actions/runs/6929988512/job/18848791016

allow warnings for fuzzer building

---

chain/chain/src/chain.rs
chain/client/src/client.rs
chain/client/src/view_client.rs

Functions `find_chunk_producer_for_forwarding()`, `find_validator_for_forwarding()` are not used much, one calls another, and they both call `chain.head()`.
That seems unnecessary. Refactored to call `get_chunk_producer()` directly, and not worry about 3 layers of functions using different types of heads.
See https://github.com/near/nearcore/pull/10251 for context

fix: use header_head to determine validators for forwarding transactions

---

core/chain-configs/src/lib.rs
core/primitives/src/chains.rs
genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs
integration-tests/src/tests/client/sync_state_nodes.rs
nearcore/src/config.rs
neard/src/cli.rs
tools/chainsync-loadtest/src/main.rs

* Simplifies `state_sync_enabled` and `enable_multiline_logging`.
* Adjusts {min,max}_block_production_delay config options when generating configs for testnet and mainnet.
* Simplifies config initialization logic.
* Deletes betanet and stakewars

fix(config): disable epoch sync, enable state sync

---

Cargo.lock
Cargo.toml

Fixes https://rustsec.org/advisories/RUSTSEC-2023-0072, reported by the cargo-audit CI job

bump openssl

---

chain/epoch-manager/src/validator_selection.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/types.rs
core/primitives/src/validator_mandates.rs

Adds support for partial mandates in chunk validator assignment.
Currently only full mandates are considered. Assume `stake_per_mandate = 5`, then:
- Valdiator `V1` with stake 12 holds 2 full mandates corresponding to a stake of 10. The remaining stake of 2 does not participate in validation.
- Validator `V2` with stake 4 holds 0 full mandates and does not participate in validation at all.
With support for partial mandates `V1` gets a partial mandate with weight 2 and `V2` gets a partial mandate of 4. So partial mandates allow to increase the number of validators and allows them to commit their entire stake to validation.
In [these simulations](https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/chunk.20validator.20assignment.20simulation.20with.20pa …

feat: support partial mandates in chunk validator assignment

---

core/primitives/src/shard_layout.rs

The following code is currently used for comparing `boundary_account` and `account_id`:
```rust
if boundary_account.cmp(account_id) == Greater {
...
}
```
IMO it's a bit confusing - it isn't immediately obvious whether this means `boundary_account` > `account_id` or `account_id` > `boundary_account`. I misread this line and because of that I made a mistake in #10240.
Let's change it to something that is easier to read:
```rust
if account_id < boundary_account {
...
}
```

feat: use the < operator instead of cmp method to improve readability

---

Cargo.lock
tools/database/Cargo.toml
tools/database/src/analyse_gas_usage.rs
tools/database/src/block_iterators/height_range.rs
tools/database/src/block_iterators/last_blocks.rs
tools/database/src/block_iterators/mod.rs
tools/database/src/commands.rs
tools/database/src/lib.rs

Add a command which allows to analyse gas usage on some part of the blockchain.
The command goes over the specified blocks and gathers information about how much
gas was used by each block, shard and account.
Then it displays an analysis of all the data.
The analysis contains:
* Total gas used
* Gas used on each shard
* Top 10 accounts by gas usage
* The optimal account by which a shard could be split into two halves with similar gas usage
Help page:
```bash
$ ./neard database analyse-gas-usage --help
Analyse gas usage in a chosen sequnce of blocks
Usage: neard database analyse-gas-usage [OPTIONS]
Options:
--last-blocks <LAST_BLOCKS>
Analyse the last N blocks in the blockchain
--from-block-height <FROM_BLOCK_HEIGHT>
Analyse blocks from the given block height, inclusive
--to-block-height …
```

feat: add database analyse-gas-usage command

---

chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/peer_manager_actor.rs

Reported by @wacban.
Debug printing results in multiline strings, which are hard to interpret. It also breaks tooling one might want to use to analyze logs.
Example:
```
2023-12-01T10:22:08.186809Z INFO network: failed to connect to ed25519:AF4j@91.226.87.212:54063 result=Err(tcp::Stream::connect()
Caused by:
deadline has elapsed)
```
I believe this is coming from the default `Debug` impl for `anyhow::Error`. Using `Display` impl should fix it as it concatenates the context via `:` instead.

fix: format tcp connection error using `Display`

---

core/primitives/src/shard_layout.rs

See https://github.com/near/nearcore/issues/10237.

refactor: remove some more usage of `num_shards()`

---

Cargo.toml
chain/chain-primitives/Cargo.toml
chain/chunks-primitives/Cargo.toml
chain/client-primitives/Cargo.toml
chain/indexer-primitives/Cargo.toml
chain/jsonrpc-primitives/Cargo.toml
core/chain-configs/Cargo.toml
core/crypto/Cargo.toml
core/dyn-configs/Cargo.toml
core/o11y/Cargo.toml
core/primitives-core/Cargo.toml
core/primitives/Cargo.toml
runtime/near-vm-runner/Cargo.toml
runtime/near-vm/compiler-singlepass/Cargo.toml
runtime/near-vm/compiler/Cargo.toml
runtime/near-vm/engine/Cargo.toml
runtime/near-vm/types/Cargo.toml
runtime/near-vm/vm/Cargo.toml
tools/rpctypegen/core/Cargo.toml
tools/rpctypegen/macro/Cargo.toml
tools/themis/src/rules.rs
utils/config/Cargo.toml
utils/fmt/Cargo.toml
utils/near-cache/Cargo.toml
utils/near-stable-hasher/Cargo.toml
utils/stdx/Cargo.toml

This comes at the request of dev-hub, where dependencies downstream have been having issues with our aggressive rust-version policy. Supporting only the latest rust-version is not enough for them.
As a consequence, we’re removing rust-version here. This sounds like a more semantically reasonable use for rust-version anyway: a crate without rust-version set should be assumed to work with the latest stable version anyway, and maybe more without guarantees… which is exactly our guarantees.
Also update the themis tool to make sure we don’t make this mistake again.

Remove rust-version.workspace = true from published crates

---

nightly/pytest-sanity.txt
pytest/lib/resharding_lib.py
pytest/tests/sanity/resharding.py
pytest/tests/sanity/resharding_error_handling.py
pytest/tests/sanity/resharding_rpc_tx.py
pytest/tests/sanity/rpc_tx_resharding.py

This PR adds a basic pytest to check if the RPC calls to tx endpoint work after a resharding event.
Note that this test currently works under the assumption that the node is tracking all shards and future improvements to the tests where we may need to redirect the request to a node tracking the specific shard we are interested in, would come later.
Resolving https://github.com/near/nearcore/issues/5047

[resharding] Add pytest for checking RPC calls after resharding

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/ondemand_fuzzer_binaries.yml
Cargo.lock
Cargo.toml

Currently, our clusterfuzz runners do not have the glibc version required to run builds made on ubuntu-22.04.
Building fuzzers on ubuntu-20.04 should fix the issue (that is only apparent in fuzzer logs); hopefully once we upgrade our clusterfuzz runners we’ll be able to bump to a newer ubuntu LTS.

build fuzzers on ubuntu-20.04

---

chain/chain/src/resharding.rs
chain/client/src/client.rs

Fixing the dynamic config since #10290 was accidentaly merged prematurely before it was fully tested and fixed. 
Tested on localnet for now, will then test on mocknet and only then merge.

fix(resharding): fix dynamic config

---

core/store/src/trie/state_snapshot.rs

This function calls the closure just once so no need to take a more restrictive closure.

refactor: don't use `Fn` when `FnOnce` will suffice

---

CHANGELOG.md
core/primitives-core/src/version.rs

This PR stabilizes the Resharding V2 protocol feature. It introduces a new implementation for resharding and a new shard layout for the production networks - mainnet and testnet. The resharding process from the current shard layout to the new shard layout will be triggered automatically an epoch before the switch to the new protocol version. 
- https://github.com/near/NEPs/pull/508
- https://github.com/near/nearcore/issues/8992
This feature was extensively tested in unit tests, integration tests, nayduck tests, mocknet, testnet and mainnet.

enable resharding v2

---

chain/chain/src/chain.rs
chain/chain/src/store.rs
chain/chunks/src/client.rs
chain/client/src/client.rs
core/primitives/src/shard_layout.rs
core/store/src/cold_storage.rs
core/store/src/flat/inlining_migration.rs
core/store/src/genesis/initialization.rs
integration-tests/src/tests/client/flat_storage.rs
integration-tests/src/tests/client/resharding.rs
nearcore/src/entity_debug.rs
nearcore/src/runtime/mod.rs
nearcore/src/runtime/tests.rs
tools/database/src/corrupt.rs
tools/database/src/state_perf.rs
tools/fork-network/src/cli.rs
tools/fork-network/src/storage_mutator.rs
tools/state-viewer/src/commands.rs

- renames `get_shard_uids()` to `shard_uids()`
- `shard_uids()` return an iterator instead of a vector.

refactor: same treatment for `get_shard_uids()` as for `shard_ids()`

---

chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/sync/state.rs

We only use this logic for state sync when the nodes starts with old blocks.
If the nodes has been running during the epoch change, it is supposed to have the block so it does not need it at state sync during catchup.

refactor(state-sync): Request sync block in client actor before starting state sync

---

chain/chain/src/chain.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/chain/src/update_shard.rs
nearcore/src/runtime/mod.rs
nearcore/src/runtime/tests.rs
tools/state-viewer/src/apply_chain_range.rs
tools/state-viewer/src/apply_chunk.rs
tools/state-viewer/src/commands.rs

This PR groups block- and chunk-related `RuntimeAdapter::apply_transactions` arguments into a separate structs. It also replaces usage `update_shard::BlockContext` with `ApplyTransactionsBlockContext` as well as a bit of refactoring around `ShardUpdateReason` to only require data which is actually used.
Implements the first idea from https://github.com/near/nearcore/issues/10261.

refactor: group runtime apply_transactions block/chunk-related arguments

---

chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/client/src/client.rs
core/chain-configs/src/client_config.rs
core/chain-configs/src/lib.rs
core/chain-configs/src/updateable_config.rs
nearcore/src/config.rs
nearcore/src/dyn_config.rs
nearcore/src/runtime/mod.rs

To produce a chunk the node fetches transactions from the transaction pool and adds them to the chunk. Adding a transaction to the chunk can be computationally expensive - the transaction is converted to receipt, which burns gas. Because of that the number of transactions has to be limited. The node will fetch transactions until some kind of limit is reached, and then decide that the chunk is ready and publish it.
Currently we have a limit of gas that can be used for preparing transactions, but there is a big problem with it - it doesn't take into account discarding invalid transactions from the pool. Processing an invalid transaction doesn't burn gas, so the node could spend a lot of time discarding invalid transactions without ever reaching the limit. This would make chunk production …

feat: add a time limit for processing transactions in produce_chunk

---

chain/epoch-manager/src/validator_selection.rs
core/primitives/src/validator_mandates.rs

Introduces a shuffling of shard ids when assigning chunk validators to shards. Without that shuffling it is predictable which shards receive fewer (partial) mandates when they cannot be distributed evenly across shards. See this [comment](https://github.com/mooori/sim-validator-assignment/pull/12#discussion_r1389895314) which also brings up the idea of shard id shuffling.
If there was only one shuffling for both full and partial mandates, then the shard(s) that get a full mandate less may also get a partial mandate less. Separate shufflings counter that and ideally (depending on randomness) stake is distributed more evenly as shards that receive a full mandate less may still get the maximum amount of partial mandates.
#10014

feat(chunk-validator-assignment): shuffle shard ids

---

chain/network/src/concurrency/rayon.rs

`try_map_result` is a function which takes a list of tasks and runs them on multiple threads producing task outputs until the first error occurs.
The test `try_map_result_stops_on_error` asks to execute an infinite list of tasks, but the 100th task throws an error, so the function should stop after executing ~100 tasks.
The test checked that the function produces outputs for the first 10 tasks, but this isn't always true. The first 10 tasks could end up on a thread that is preempted and the tasks aren't executed before the error is hit on the 100th task. Because of this the test is flaky.
I assumed that the first 10 tasks would be executed first, but this was wrong, we can't assume anything here. Let's remove all checks that could be broken by race conditions, no matter how unlikely. This …

fix: remove flakiness in the test try_map_result_stops_on_error

---

chain/chain/src/chain.rs
chain/chain/src/resharding.rs
chain/client/src/client_actor.rs
core/chain-configs/src/client_config.rs
core/chain-configs/src/lib.rs
nearcore/src/lib.rs
neard/src/cli.rs

Currently ctrl-c doesn't fully stop neard while it's in the middle of resharding.
Adding StateSplitHandle that allows for stopping resharding in the `build_state_for_split_shards` method. 
to be tested in mocknet soon

feat(resharding): making resharding interruptible

---

chain/network/src/peer_manager/tests/snapshot_hosts.rs

The test `snapshot_hosts::invalid_signature_not_broadcast` sends out a message containing three instances of `SnapshotHostInfo`, one of which has an invalid signature, and then verifies that this message is rejected.
There is a subtelty here that I didn't take into account when I wrote this test. When the `PeerManager` receives a message with multiple `SnapshotHostInfos`, it can accept the valid instances, even in the case where there are other invalid instances in the message. Because of this the test could fail - `PeerManager` could accept `ok_info_a` or `ok_info_b` and then the final assert would fail. Whether it accepts them or not depends on the timing, as the instances are processed on multiple threads and the processing stops at the first invalid instance. Because of that the test …

fix: remove potential flakiness from a snapshot_hosts test

---

pytest/tests/loadtest/locust/common/base.py

To run a locust loadtest the user has to pass an URL to the RPC node. This is done using the `-H` flag:
```bash
locust -H 127.0.0.1:3030 ...
```
This works with IPv4 addresses, but breaks with IPv6, because the code splits the host address by `:` to find the hostname and port. Ipv6 addresses can contain colons, which breaks this logic.
This command didn't work before this change:
```bash
locust -H "[::1]:3030" ...
```
Let's fix it by splitting on the last colon in the string. This makes it possible to use IPv6 addresses with locust loadtests.

feat: support IPv6 node address in locust loadtests

---

Cargo.lock

Fixes https://rustsec.org/advisories/RUSTSEC-2023-0074

bump zerocopy to a non-yanked version

---

core/chain-configs/src/genesis_config.rs
nearcore/src/config.rs

It's a bit sad to throw away the original error messages, because then it becomes a lot harder to see what the problem is when all you see is "Failed to deserialize config from ~/.near/config.json"

fix(configs): print out underlying deserialization errors

---

.github/workflows/near_crates_publish.yml
Cargo.toml

Considering rust compilation is heavily parallelized, increasing the number of cores also means that compilation will go faster by basically this amount, which means no additional charge compared to a smaller large runner.
This should fix [the last crate publishing failure](https://github.com/near/nearcore/actions/runs/7278852375).
Also bump the prerelease version number to be able to attempt a second crate publishing with the new runner straight away.

increase crate publisher runner’s disk space

---

docs/architecture/gas/parameter_definition.md
docs/architecture/how/gas.md

This fixes the lychee check, that had started failing after #10343 landed. It also uses local links rather than remote links, which should help future breakage to be detected before the PR lands, and not after.

fix broken links

---

Cargo.lock

Fixes https://rustsec.org/advisories/RUSTSEC-2023-0075

bump unsafe-libyaml

---

core/primitives/src/action/mod.rs

Nightly probably introduced an optimization that further reduces the size of `Action`.
This change should fix [our fuzzer builds](https://github.com/near/nearcore/actions/runs/7287168944/job/19857279411), as well as get us ready for when said nightly optimization will land on master
cc https://github.com/near/near-one-project-tracking/issues/9

fix build on nightly

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/ondemand_fuzzer_binaries.yml

Due to cargo-bolero first compiling in test mode and then in fuzz mode, #10364 was not actually enough to fix the issues.
With this change, cargo-bolero will always set `--cfg fuzz`, even when compiling in test mode, so that all builds performed with nightly do see the assertion skipped.
Part of https://github.com/near/near-one-project-tracking/issues/9

always set cfg(fuzz) when building for fuzzers

---

Cargo.toml
runtime/near-vm/test-api/src/sys/externals/mod.rs
runtime/near-vm/test-api/src/sys/types.rs
runtime/near-vm/vm/src/mmap.rs
runtime/runtime-params-estimator/emu-cost/Dockerfile
rust-toolchain.toml

Release notes: https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html
I briefly looked for instances where we could replace our code with the newly added `pointer::byte_` methods, but found nothing of note.

rust: 1.75.0

---

core/primitives/src/state_record.rs
core/primitives/src/trie_key.rs
nearcore/src/metrics.rs
tools/state-viewer/src/cli.rs
tools/state-viewer/src/trie_iteration_benchmark.rs

Currently both `TrieKey::DelayedReceipt` and `TrieKey::DelayedReceiptIndices` are serialized with `col::DELAYED_RECEIPT_INDICES`, probably due to a typo in the original implementation. It was accidentally discovered when debugging an unrelated issue using mainnet State. 
Changing this is quite involved and requires data migration for State and FlatState rocksdb columns. This PR makes existing behaviour more explicit and adds a bit of documntation. 
See also [the corresponding zulip thread](https://near.zulipchat.com/#narrow/stream/295302-general/topic/Delayed.20receipts.20serialized.20with.20the.20wrong.20column.20id.3F).

refactor: Fix delayed receipts trie key column identifier

---

core/store/src/trie/config.rs

Current value is 50MB which might not be enough when the shard is overloaded. One example when this can be an issue is when delayed receipts queue grows to 20k+ items, which already happened during NEAT inscription load. Insufficient cache size results in increased number of disk reads to State rocksdb column. That increases chunk application time which results in more missed chunks.
This only applies to shards 0,1,2 since we have an overwrite for shard 3. So overall expected RAM increase is 3 * (500 - 50) = 1350MB.

feat: Change default shard trie cache size to 500MB

---

Justfile

In my local environment lychee was crawling through the `target/` directory, which contained a link to a PDF at `dl.acm.org`. Running the test suite one too many times has got me a ban(ana)d off their site.
Conversely having checked lychee's code, it only ever checks links in markdown and html files. So for instance whatever links we might have in our code or docstrings can easily remain broken and we’d be none-the-wiser.
For what it is worth at least for the time being the number of links checked remains the same as before.

lychee: only check checked-in files

---

tools/amend-genesis/src/cli.rs
tools/amend-genesis/src/lib.rs

After https://github.com/near/NEPs/issues/92, the min gas price was set to 100M yoctoNEAR. But the genesis file we get from the state viewer dump-state command copies the 1B min gas price from the genesis file. This results in a network with 10x the gas fees as mainnet when we launch mocknet testing networks, and many transactions sent by the mirror run command fail with too little balance. So this PR allows setting the min/max gas prices in the mocknet genesis file so we can fix that. It might also be worth changing the behavior of `view-state dump-state` to set the min gas price, but this will work for now and lets us get the right gas price in all cases

feat(amend-genesis): allow setting the gas price

---

chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/chain/src/update_shard.rs
nearcore/src/runtime/mod.rs
nearcore/src/runtime/tests.rs
tools/state-viewer/src/apply_chain_range.rs
tools/state-viewer/src/apply_chunk.rs
tools/state-viewer/src/commands.rs

`apply_transactions` is confusing for multiple reasons:
- this function processes not only transactions but also receipts
- transactions are not directly applied, but converted to receipts

refactor: rename runtime apply_transactions -> apply_chunk

---

chain/chain-primitives/src/error.rs
chain/chain/src/chain.rs
chain/chain/src/lib.rs
chain/chain/src/sharding.rs
chain/chain/src/validate.rs
chain/chunks/src/lib.rs
chain/client/src/chunk_validation.rs
chain/client/src/client.rs
core/primitives/src/chunk_validation.rs
core/primitives/src/sharding.rs
integration-tests/src/tests/client/features/chunk_validation.rs

This fills in the ChunkStateWitness struct with real data that would be included in a chunk state witness.
It also includes a prototype implementation for validating the ChunkStateWitness against the chain, which includes a pre-validation part where the ChainStore is used to retrieve necessary blocks and chunk headers (to verify receipts and transactions against), as well as the main validation part where transactions and receipts are applied with the runtime.
This verification logic is untested right now because the state witness production part is not implemented.
#9292

[stateless validation] Real ChunkStateWitness struct, and prototype validation logic

---

chain/network/src/network_protocol/mod.rs
chain/network/src/peer/peer_actor.rs

Randomly found ReceiptOutcomeRequest which is currently unused.

[cleanup] Remove ReceiptOutcomeRequest from RoutedMessageBody

---

core/store/src/cold_storage.rs
core/store/src/columns.rs
integration-tests/src/tests/client/cold_storage.rs
nearcore/src/cold_storage.rs
nearcore/src/metrics.rs

The current approach means that when looking for a trie node in the db we need to check all shards. In practice most nodes are only ever present in one shard so the current implementation is ~4x slower when it comes to reading trie nodes than it could be. The state reads also happen to account for majority of time spent in copying heights from hot to cold. 
This fix should resolve the ever growing cold head lag that is described in more detail on [zulip](https://near.zulipchat.com/#narrow/stream/308695-pagoda.2Fprivate/topic/Split.20storage.20nodes.20increasing.20cold.20head.20lag) which is a major issue for our archival nodes.

fix(split-storage) - optimize copying of state

---

core/store/src/config.rs
core/store/src/trie/config.rs

* Do not apply default size increase introduced in #10373 to `view_trie_cache` since view calls are not latency-sensitive
* Opt out shard 1 from the increase since it only contains aurora account and based on the current metrics has very low cache miss rate even with a size of 50MB
* Configure shard 3 override of 3GB to also apply after resharding

config: adjust shard cache sizes

---

integration-tests/src/tests/client/cold_storage.rs
nearcore/src/cold_storage.rs

In the recent split archival incident the nodes were bootstrapped with inconsistent hot and cold DBs. In such a case the node should crash immediately on startup so that the issue can be detected as early as possible. 
* Refactored the sanity check code to two new methods
* Added the sanity check before the cold loop is spawned - at this place it would crash the node if failed
* Note that once the loop is spawned the sanity check doesn't crash the node but prints an error message and bumps approproate metric - this part remained unchanged. I'm open to suggestions here. 
I'm also refactoring the cold storage tests becuase it's a pain to work with those. Dear reviewers if you prefer to review those separately I'm happy to move it to a new PR, just let me know.  
* moving create_tx_* logic …

feat(split-storage): crash on startup if the hot and cold are inconsistent

---

chain/client/src/tests/process_blocks.rs
core/primitives/src/block.rs
core/primitives/src/block_body.rs
core/primitives/src/lib.rs
core/primitives/src/test_utils.rs
integration-tests/src/tests/client/challenges.rs
integration-tests/src/tests/client/process_blocks.rs

This PR introduces versioned BlockBody struct which would be a part of BlockV4. Note that this isn't being used with the current protocol version.
Eventually with stateless validation, we are going to have chunk endorsements as part of the BlockBody, the structure of which would look something like this or equivalent (still undecided if we need `Vec<Vec<ChunkEndorsement>>` or `Vec<ChunkEndorsement>`)
```
pub struct BlockBodyV2 {
pub chunks: Vec<ShardChunkHeader>,
pub challenges: Challenges,
// Data to confirm the correctness of randomness beacon output
pub vrf_value: Value,
pub vrf_proof: Proof,
// Chunk Endorsements
pub chunk_endorsements: Vec<ChunkEndorsement>,
}
```

[stateless_validation] Introduce versioned BlockBody

---

Cargo.lock
core/store/src/config.rs
core/store/src/trie/config.rs
core/store/src/trie/trie_storage.rs
core/store/src/trie/trie_tests.rs
integration-tests/Cargo.toml
integration-tests/src/tests/client/state_snapshot.rs

As suggested in https://github.com/near/nearcore/pull/10409#discussion_r1450075629 to keep it consistent with the rest of `StoreConfig`.

refactor: use bytesize::ByteSize for TrieCacheConfig

---

runtime/near-vm-runner/src/logic/dependencies.rs

This function does not take an argument named `generate_data_id`.

nit: fix comment documenting args of create_receipt

---

.github/workflows/ci.yml
Cargo.lock
Justfile
integration-tests/Cargo.toml
runtime/near-vm-runner/Cargo.toml
runtime/near-vm-runner/src/features.rs
runtime/near-vm-runner/src/imports.rs
runtime/near-vm-runner/src/lib.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/tests/fuzzers.rs
runtime/near-vm-runner/src/tests/test_builder.rs
runtime/runtime-params-estimator/Cargo.toml
runtime/runtime/Cargo.toml

Helps end users who want to use just the data structures representing the host interface available for contracts and such.
For nearcore specifically this changes very little – the `runtime/runtime` crate enables all of these features so unless you're building something that specifically depends on `near-vm` but not on `node-runtime` (e.g. `cargo check -p near-vm-runner`) the features will still get enabled.
The build of the `near-vm-runner` crate like this becomes quite minimal by default (transitively "just" 150-ish common dependencies, many of which come from `near-crypto`…)
Missing parts currently:
Fixes? #10421

near-vm-runner: make runtimes non-default features

---

chain/chunks/src/lib.rs
chain/network/src/network_protocol/edge.rs
chain/network/src/peer_manager/network_state/mod.rs
chain/network/src/peer_manager/network_state/routing.rs
chain/network/src/peer_manager/peer_store/mod.rs
chain/network/src/peer_manager/peer_store/tests.rs
chain/network/src/routing/edge_cache/mod.rs
chain/network/src/routing/graph/mod.rs
integration-tests/src/tests/network/runner.rs
integration-tests/src/tests/runtime/state_viewer.rs
nearcore/src/lib.rs
runtime/near-vm-runner/src/instrument/gas/validation.rs
runtime/near-vm-runner/src/prepare/prepare_v0.rs
runtime/near-vm-runner/src/prepare/prepare_v1.rs
runtime/near-vm/vm/src/table.rs
runtime/near-vm/wast/src/wast.rs
tools/state-viewer/src/rocksdb_stats.rs

Option::is_and_then and Result::is_ok_then have been stabilised
in 1.70 and are slightly more concise and arguably more descriptive
than map_or.

Prefer is_and_then and is_ok_than over map_or

---

chain/chain-primitives/src/error.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/client/src/chunk_validation.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/tests/mod.rs
core/primitives/src/chunk_validation.rs

This PR adds the implementation for `process_chunk_endorsement` function in client.
When a client gets a new chunk endorsement, we do the following
- Verify if the chunk endorsement is from a valid chunk validator
- Verify if the signature is correct
- Store the chunk endorsement in-memory in a LRU cache `LruCache<ChunkHash, HashMap<AccountId, ChunkEndorsement>>`
The ChunkEndorsements would later be included in the block body during block production.
Minor cleanup to the ChunkEndorsement struct as well.

[stateless_validation] Process and store incoming chunk endorsements to block produce

---

Cargo.toml
tools/themis/src/main.rs
tools/themis/src/rules.rs
tools/themis/src/types.rs

It looks like we’re prone to accumulating trash in our root `Cargo.toml` file. Even dependencies that are no longer valid in any way (as evidenced by `near-vm-engine-universal`.) This themis check verifies that all deps in `Cargo.toml` are being referenced.

themis: add a check for unused dependencies in root Cargo.toml

---

runtime/near-wallet-contract/Cargo.toml
runtime/near-wallet-contract/README.md
runtime/near-wallet-contract/build.rs

In some circumstances, `runtime/near-wallet-contract/build.rs` is triggered and it regenerates the Wallet Contract WASM file for unrelated PRs: https://github.com/near/nearcore/pull/10422#issuecomment-1892794073.
The `Wallet Contract` will be generated differently (https://github.com/near/nearcore/pull/10269#discussion_r1430139987), but for now I would like to include this tiny PR to stops auto-generating the WASM file by default.
To test that the WASM file is not auto-regenerated, add a space to `runtime/near-wallet-contract/wallet-contract/src/lib.rs` and run `cargo build --features nightly`.

Disable auto-generation of wallet contract by default

---

core/parameters/src/fixture_base_0.yml
core/parameters/src/fixture_base_1.yml
core/parameters/src/fixture_diff_0.yml
core/parameters/src/fixture_diff_1.yml
core/parameters/src/parameter_table.rs

One of these strings intentionally has some trailing space at the end of the line. This is pretty hard to work with when the editor is set up to strip these off, as in my case, making modifying those files a chore.
Moving them into files that’ll never get touched as a common case solves this problem altogether.

parameters: move out test strings to a separate file

---

chain/chain/src/test_utils/kv_runtime.rs
chain/client/src/chunk_validation.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/lib.rs
core/primitives/src/chunk_validation.rs

This PR adds a layer or caching for calls to `get_chunk_validators` in epoch_manager

[stateless_validation] Add cache for generated chunk_validators

---

chain/client/src/chunk_validation.rs

In the current implementation, we only send the chunk endorsements to the next block producer. As discussed in [this Zulip thread](https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/chunk.20endorsements.20with.20missing.20chunks.2Fblocks/near/416015998), it's possible for a chunk to be included in a block at a height different from that it was created for. This leads to the situation where this new block producer hasn't received the chunk endorsements for this chunk.
The solution here is to broadcast the chunk endorsement message to the next 5 block producers and hope that the chunk would get included in any one of them in cases of skipped blocks.
Note that this also means we are always going to use the chunk_validators as of the …

[stateless_validation] Broadcast chunk endrosement to next 5 block producers

---

core/primitives/src/chunk_validation.rs

The comment on the `source_receipt_proofs` field in `ChunkStateWitness` mentions `B1` twice, which looks like a typo:
```rust
/// where B1 is the block that contains the last new chunk of shard S before this chunk,
/// and B1 is the block that contains the last new chunk of shard S before B2.
```
It doesn't make much sense to mention `B1` twice there, IIUC the first `B1` was supposed to be `B2`.

fix: typo in ChunkStateWitness comment

---

.github/workflows/ci.yml

This should make us thrash our cache less often, thus helping it stay alive long enough to actually be useful.

save the cache only from master

---

chain/chain/src/chain.rs
chain/client/src/sync/state.rs
integration-tests/src/tests/client/resharding.rs

As long as the snapshot is present the storage overhead will keep increasing. This PR makes it so that the snapshot is deleted immediately after resharding is finished. The snapshot is only deleted if the node is not configured to take snapshots every epoch. 
Initially I wanted to put the trigger logic somewhere between sync jobs actor and chain but there it was hard to tell if resharding is finished for **all** the shards. It was made trickier by the fact that we only resharding shards that we will track next epoch and should only check those. At the end of the day I placed it in the state sync logic where it'll be triggered once all state syncs and hence all reshardings are done.

feat(resharding) - delete snapshot immediately after resharding is finished

---

nearcore/src/cold_storage.rs

Updated the error reporting for cold_store_copy function to be more expressive. 
This way we can report the reason for the error in the metric
Context: [zulip](https://near.zulipchat.com/#narrow/stream/308695-pagoda.2Fprivate/topic/Split.20storage.20nodes.20increasing.20cold.20head.20lag/near/411978107)

feat(split-storage): Error handling and reporting for cold_store_copy

---

chain/client/src/chunk_inclusion_tracker.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/debug.rs
chain/client/src/lib.rs
chain/client/src/test_utils/test_env.rs
integration-tests/src/tests/client/process_blocks.rs

Refactoring effort needed for adding in future functionality related to stateless validation where we filter out chunks based on whether they have enough chunk_endorsement or not.

[refactor] Add chunk_inclusion_tracker to track chunks to be included in block

---

chain/chain/src/test_utils/kv_runtime.rs
chain/client/src/chunk_validation.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/tests/mod.rs
chain/network/src/types.rs
core/primitives/src/block_body.rs
core/primitives/src/chunk_validation.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/validator_mandates.rs

Couple of awesome changes here...
- Expose validator_mandates_config as we need this to calculating total stake. See function `does_chunk_have_enough_stake`
- `Vec<Option<Box<Signature>>>`??? Wth is this??? Type aliased it to `ChunkEndorsementSignatures`
- Added `validate_signature` function to `ChunkEndorsement` that checks whether a signature + public key is valid or not. This is used for verifying chunk endorsement signature in header.
- `ChunkValidatorAssignments` just got coooooler!! Now we have a `does_chunk_have_enough_stake` function that calculates whether we have 2/3rd stake and we are good to go?
- Some other minor improvements to `ChunkValidatorAssignments` like adding `ordered_chunk_validators` function and `contains` function

[stateless_validation] Add helper functions for chunk endorsement validation

---

runtime/near-vm/compiler-singlepass/src/compiler.rs
runtime/near-vm/engine/src/universal/engine.rs

The span emission levels should not be higher than "debug" for that's approximately the level at which spans are emitted at the near-vm-runner before they make it into the runtime. It makes sense to `debug` still the compilation of a single module (a comparatively rare event) but a module may have a boatload of functions so those should already be trace. And each function may have many other invocations. Those ideally would be another level below, but I imagine if you're enabling `trace` level for neard you won’t be losing any sleep over individual operators being traced too.

near-vm: harmonize tracing levels

---

.github/workflows/ci.yml
codecov.yml

This should help us with the number of caches for the tools we use. Each one is lightweight, but they are a lot.
Currently, 23 of the 25 caches on the github first page are `cargo-install` caches, and that just continues in the next pages. My guess is the action doesn’t deal with the cache properly and has the same cache uploaded multiple times, because we don’t even have that many cargo-install calls. Unfortunately, reading the code of the cargo-install action, I was not able to see an obvious reason why it resulted in this.

install tools from github releases rather than building and caching them

---

chain/client/src/chunk_validation.rs

The comments on these two variables don't match the code:
```rust
// Blocks from the last new chunk (exclusive) to the parent block (inclusive).
let mut blocks_after_last_chunk = Vec::new();
// Blocks from the last last new chunk (exclusive) to the last new chunk (inclusive).
let mut blocks_after_last_last_chunk = Vec::new();
````
It seems that instead of `(last_last_chunk, last_chunk]` `(last_chunk, parent_block]`, in reality it's `[last_last_chunk, last_chunk)`, `[last_chunk, parent_block]`.
The rest of the code follows this convention, so the code itself does the correct thing, but it doesn't match what was said in the comment, which makes it much harder to read.
Let's adjust the comments to match what's in the code.
Refs: https://github.com/near/nearcore/pull/10413#discussion_r14512912 …

fix: adjust comments in `pre_validate_chunk_witness` to match the code

---

chain/chain/src/chain.rs

https://github.com/near/nearcore/pull/9316 extracted maybe_mark_block_invalid() as a helper function, but it changed the behavior so that near_num_invalid_blocks is incremented even if we're not marking a block as invalid.  So fix it by just putting that metric increment inside the if block like it was before

fix(metrics): fix false positives in the near_num_invalid_blocks metric

---

chain/chain/src/test_utils/kv_runtime.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/validator_selection.rs
core/primitives/src/chunk_validation.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/validator_mandates.rs

As per [this comment](https://github.com/near/nearcore/pull/10464#discussion_r1457862142) by Robin, it makes sense to abstract out the `num_mandates` and `partial_weight` and directly use stake values for chunk validator stake assignments.
This removes the necessity of expose `ValidatorMandatesConfig` outside epoch manager.

[stateless_validation] Use Balance instead of AssignmentWeight in ValidatorMandatesAssignment

---

Cargo.toml

Merges the version bump commit from https://github.com/near/nearcore/tree/crates-0.20.x

crates: Release 0.20.1

---

chain/chain/Cargo.toml
chain/chain/src/chain.rs
chain/client/Cargo.toml
chain/client/src/chunk_validation.rs
chain/client/src/client.rs
chain/client/src/metrics.rs

This is the first PR for #10440.
New feature `shadow_chunk_validation` is introduced. When enabled it makes the node produce state witness for every chunk in every processed block and then self-validate it. New metrics are introduced for validation failures and state witness size.
Detailed state witness size breakdown metrics from [robin/witness-size](https://github.com/near/nearcore/compare/robin/witness-size) will be added in a separate PR.

feat: add shadow stateless validation

---

chain/network/src/config_json.rs

the command `neard --home {home_dir} init --chain-id mainnet --download-config` downloads the config at
https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/mainnet/config.json and then saves a config file built from that one to {home_dir}/config.json. This is expected to work even when particular fields are missing by filling them in with defaults, which is why many config fields are marked with some sort of `#[serde(default)]` or `#[serde(default = default_fn)]`. But the `ExperimentalConfig` doesn't fill in these defaults. The existing `#[serde(default)]` over that field in `near_network::config_json::Config` will have us fill it in if it's totally missing, but we get an error if it's present with some fields missing, which is the case today:
```
Error: Failed to …
```

fix(configs): fill in missing values in ExperimentalConfig with defaults

---

chain/client/src/metrics.rs
chain/client/src/sync/external.rs
chain/client/src/sync/state.rs
integration-tests/src/tests/client/state_dump.rs
nearcore/src/state_sync.rs
tools/state-parts-dump-check/src/cli.rs
tools/state-viewer/src/state_parts.rs

Upload state sync headers to external storage to enable single shard tracking. 
Fixes #10459
Tested in `testnet` and [Headers were uploaded to GCP](https://console.cloud.google.com/storage/browser/state-parts/chain_id%3Dtestnet/epoch_height%3D2608/epoch_id%3DjdwKefy7yQQW4FiATDcBkNzWmopccsLhFcZ2kj2nJ4y/headers;tab=objects?project=pagoda-public-services&prefix=&forceOnObjectsSortingFiltering=false&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22)))

feat(state-sync): save state sync header to external storage

---

chain/chain/src/chain.rs
chain/client/src/chunk_inclusion_tracker.rs
chain/client/src/chunk_validation.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/debug.rs
core/primitives/src/block.rs
core/primitives/src/block_body.rs
integration-tests/src/tests/client/process_blocks.rs

This PR writes the logic to include chunk endorsement signatures in block. We tap into the logic in chunk_inclusion_tracker to filter out chunks that don't have enough endorsed signatures.
In case of missing chunk, just like we borrow chunk headers from previous block, we also borrow the chunk endorsement signatures corresponding to the chunk from the previous block.
Updated the ChunkInclusionTracker module to have an LRU cache for `prev_block_to_chunk_headers_ready_for_inclusion` + HashMap for chunk hash to random info associated with the chunk.
This is a two step indirection, and we handle cleaning up the `chunk_hash_to_chunk_info` during cache eviction.
Additionally, call to `get_chunk_headers_ready_for_inclusion` now returns just the chunk hash instead of all the random details for …

[stateless_validation] Include chunk_endorsement signatures in block body

---

chain/client/src/chunk_validation.rs
chain/epoch-manager/src/tests/mod.rs
core/primitives/src/chunk_validation.rs

We are skipping state witness validation for the chunk right after genesis chunk due to some complications of trying to run the genesis chunk in runtime (it's not possible to do so).
Initially this edge case check was a part of `send_chunk_state_witness_to_chunk_validators` and we didn't send state witness at all.
This has an issue that we do not process and send chunk endorsements either due to this. Instead pushed this check into `process_chunk_state_witness` and we send chunk endorsements for this special case.

[stateless_validaiton] Skip validation of state witness for chunk right after genesis

---

chain/chain/src/chain.rs
chain/chain/src/chunk_endorsement.rs
chain/client/src/client.rs
core/primitives/src/block.rs
core/primitives/src/block_body.rs

This is a follow up to comment https://github.com/near/nearcore/pull/10469#discussion_r1464954843
If we have an old chunk header present in the block, which happens in case a new chunk isn't included/is missing in the block, we don't need to include the chunk endorsement signatures in the block body.
Updated the block validation logic to reflect the same

[stateless_validation] Do not include chunk endorsement signatures for old chunks in block

---

chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/update_shard.rs

The enum was introduced in order to have different types for validation as part of chain and stateless validation. It is no longer required.

refactor: remove ShardUpdateResult enum

---

chain/chain/src/test_utils/kv_runtime.rs
chain/client/src/adapter.rs
chain/client/src/chunk_validation.rs
chain/client/src/client_actor.rs
chain/client/src/test_utils/test_env.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/tests/mod.rs
chain/network/src/client.rs
chain/network/src/peer/peer_actor.rs
chain/network/src/testonly/fake_client.rs
chain/network/src/types.rs
core/primitives/src/chunk_validation.rs
core/primitives/src/validator_signer.rs
tools/chainsync-loadtest/src/network.rs

It looks reasonable to have some protection against sending arbitrary data pretending to be state witness, as it is large message causing a lot of computation. Also having a message to reject of state witness is more convenient for testing.
Here I modify state witness message to include signature; construct and verify it; and also spawn message to ban peer if state witness is invalid. As chunk producer is uniquely determined by state witness data, we don't need to pass it in message. Ideally the test also should be here but it is not a trivial change so I'll send it in the next PRs.
The logic of `SignatureDifferentiator` can be done better but for now I just follow chunk endorsements pattern. Also I recognize that signing/verifying logic is quite duplicated around epoch manager, but I …

feat: sign chunk state witness

---

chain/client/src/chunk_validation.rs
chain/client/src/metrics.rs

Measures `validate_chunk_state_witness` function execution time per `shard_id`.

feat: add metric for state witness validation latency

---

chain/client/src/chunk_validation.rs
core/primitives/src/chunk_validation.rs

This is mainly to solve issues related to testing where we were initially not getting the chunk endorsements.
I've created an issue for this here: https://github.com/near/nearcore/issues/10502
Fixes issue in PR https://github.com/near/nearcore/pull/10487

[stateless_validation][fix] Hack sending state witness for chunk after genesis

---

chain/client/src/test_utils/test_env.rs
integration-tests/src/tests/client/features/chunk_validation.rs

This PR improves the testing infrastructure for stateless validation to handle cases of network message propagation of `ChunkStateWitness` and `ChunkEndorsement`.
With the changes in validation of signature in chunk header, we need to handle `ChunkEndorsement` messages at the time of block production.

[stateless_validation] Add testing for handling state witness and chunk endorsements

---

.github/workflows/neard_release.yml
scripts/binary_release.sh

On release triggered workflow runs, the HEAD is detached and no local branch is present.
Due to this, BRANCH var ends up as an empty string and this causes failures to publish artifacts:
https://github.com/near/nearcore/actions/runs/7640475082/job/20815674136
++ git branch --show-current
+ BRANCH=
++ git rev-parse HEAD
+ COMMIT=c869dd6c1e942f21e27a74c7e47a698de
++ uname
this leads to incorrect S3 paths:
`s3://build.nearprotocol.com/nearcore/$(uname)/${BRANCH}/latest` -> `s3://build.nearprotocol.com/nearcore/Linux//latest`

Fix: get branch on RELEASE event triggered workflow

---

chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/client/src/chunk_validation.rs
chain/client/src/client.rs
nearcore/src/runtime/mod.rs
nearcore/src/runtime/tests.rs

* Wrap block/chunk-related arguments into separate struct, consistent with `apply_chunk`
* Get rid of arguments that can be derived by runtime using its `epoch_manager`
* Move some of the logic (such as `next_block_height = prev_block.height + 1`, determining `epoch_id` and `protocol_version`, etc.) inside since it is part of the implementation and should not be decided by clients

refactor: improve runtime `prepare_transactions` api

---

core/store/src/trie/mem/flexible_data/value.rs
core/store/src/trie/mem/loading.rs
core/store/src/trie/mem/lookup.rs
core/store/src/trie/mem/mod.rs
core/store/src/trie/mem/updating.rs
core/store/src/trie/mod.rs

This is primarily intended to enable cheap existence lookups eventually but stylistically it seems quite awkward to force a conversion on the users of the API when a choice can be given at low-to-no cost.

store: return borrow to memtrie data on lookups

---

chain/chain/src/chain.rs
chain/client/src/chunk_validation.rs
chain/client/src/client.rs

Runtime `prepare_transactions` accepts `chain_validate` callback to perform additional transaction validation using data from chain. This PR extract common code into a separate function as part of `Chain`.

refactor: extract `transaction_validity_check` function

---

chain/jsonrpc-primitives/src/types/entity_debug.rs
core/primitives/src/challenge.rs
core/primitives/src/chunk_validation.rs
nearcore/src/entity_debug.rs
nearcore/src/entity_debug_serializer.rs
tools/debug-ui/src/entity_debug/fields.tsx
tools/debug-ui/src/entity_debug/types.tsx

Two new queries added:
- StateTransitionData: given block hash, query the StateTransitionData stored for each shard at that block (we don't query by chunk hash here because this data also exists for missing chunks).
- ValidatorAssignmentsAtHeight: given block height and epoch ID, query the block producer, chunk producer for each shard, and the chunk validator assignments.
Also add the ChunkEndorsements field to the Block result. Here, adding it to the BlockView is probably better, but that is a larger change.

Add EntityDebug UI entities for stateless validation

---

.github/workflows/neard_release.yml

https://github.com/near/nearcore/pull/10495 was meant to fix the builds triggered by release events.
With actions/checkout GHA action only a single commit is fetched by default and thus missing branch match.
To fetch all history for all branches and tags, setting fetch-depth to 0 for both binary and docker image release jobs.
This was [tested](https://github.com/near/andrei-playground/actions/runs/7696882172/job/20972653224) on a private repo.

Fix: neard-release pipeline

---

chain/chain/src/garbage_collection.rs
chain/client/src/client_actor.rs
chain/epoch-manager/src/lib.rs

Removing spam from info logs.
1. GC shouldn't announce itself every block in `info` mode
2. `BlockResponse` handle shouldn't spam 10 times per block
3. `EpochOutOfBounds` is a normal error in `is_last_block_in_finished_epoch`, and we shouldn't flag it.

remove spammy info logs

---

chain/chain/src/chain.rs
chain/chain/src/test_utils.rs
chain/chunks/src/chunk_cache.rs
chain/chunks/src/lib.rs
chain/chunks/src/logic.rs
chain/chunks/src/test/multi.rs
chain/chunks/src/test_loop.rs
chain/chunks/src/test_utils.rs
chain/client/src/tests/catching_up.rs
core/primitives/src/sharding.rs
core/store/benches/finalize_bench.rs
tools/mock-node/src/lib.rs
tools/state-viewer/src/apply_chunk.rs

The `receipts` field in `PartialEncodedChunk` represents the outgoing receipts of the previous chunk. Let's modify the name to make it more descriptive: `prev_outgoing_receipts` is much clearer than just `receipts`. The same name is already used in `ShardChunk`, so it'll make the code more consistent and readable.
The change shouldn't break anything, the reasoning is the same as in https://github.com/near/nearcore/pull/9500:
> This change is safe since field names are not used for serialisation because those structs only support Borsh serialization.
This PR doesn't make any changes to the logic, it just renames `receipts` to `prev_outgoing_receipts`.

refactor: add prev_ prefix to receipts in PartialEncodedChunk

---

Cargo.lock
chain/client/Cargo.toml
chain/client/src/stateless_validation/chunk_endorsement_tracker.rs
chain/client/src/stateless_validation/chunk_validator.rs
chain/client/src/stateless_validation/state_witness_producer.rs
utils/near-cache/src/sync.rs

Internal testing revealed that our network doesn't send messages to ourselves, so if we try sending state witness or endorsement to ourselves, this message gets dropped: https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/Internal.20testnet.20findings/near/418348484
Making the quick fix for it to unblock stateless net. Because there are two messages - witness/endorsement, there are two patches:
1. if we are chunk producer and chunk validator, we immediately send endorsement to block producer, bypassing sending state witness to ourselves;
2. if we are block producer and chunk validator, we immediately add endorsement to chunk endorsement cache, bypassing sending endorsement to ourselves.
Note that when node operates in all three roles, it happily …

fix: bypass sending stateless validation messages to ourselves

---

core/store/src/trie/mod.rs

Turns out I missed this crucial statement which led to regular trie being queried in either mode...
~~Unfortunately it seems like the tests are failing...~~

flat: fix contains_key to return flat storage value

---

.github/workflows/ci.yml
Justfile

This adds a `coverage-html` as well as a `coverage-lcov` artifact. They can be used for easier access to the coverage data than codecov.
In particular:
- `coverage-lcov` can be loaded into vscode with eg. [the coverage gutters extensions](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters), allowing for easily looking into which code is currently not covered by unit/integration tests
- `coverage-html` contains:
- One `unit` and one `integration` folder, respectively showing the full coverage report for just unit tests and for integration tests
- One `unit-diff.html` and one `integration-diff.html` file, respectively showing how well-covered the diff is under just the unit tests and under integration tests

implement custom coverage generation

---

integration-tests/src/tests/client/features/limit_contract_functions_number.rs

It looks like this test now works with stateless validation, so let's enable it again.
I didn't need to make any changes to the test, maybe something was fixed in the meantime.
Refs: https://github.com/near/nearcore/issues/10506

fix: enable test_function_limit_change

---

chain/chain/src/chain.rs
chain/client/src/stateless_validation/chunk_endorsement_tracker.rs
chain/client/src/stateless_validation/state_witness_producer.rs
chain/epoch-manager/src/tests/mod.rs
chain/epoch-manager/src/validator_selection.rs
core/primitives-core/src/version.rs
core/primitives/src/block.rs
core/primitives/src/block_body.rs
core/primitives/src/epoch_manager.rs
integration-tests/src/tests/client/chunks_management.rs
integration-tests/src/tests/client/features/adversarial_behaviors.rs
integration-tests/src/tests/client/features/in_memory_tries.rs
integration-tests/src/tests/client/features/limit_contract_functions_number.rs
integration-tests/src/tests/client/features/stateless_validation.rs
integration-tests/src/tests/client/process_blocks.rs

Originally discussed in [this comment](https://github.com/near/nearcore/pull/10522#discussion_r1469792827), I feel like renaming feature `ChunkValidation` to `StatelessValidationV0` makes sense. With subsequent releases, we can have `StatelessValidationV1` etc.
@wacban @robin-near, thoughts?

[stateless_validation] Rename feature `ChunkValidation` to `StatelessValidationV0`

---

chain/client/src/chunk_inclusion_tracker.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/stateless_validation/chunk_endorsement_tracker.rs
chain/client/src/stateless_validation/chunk_validator.rs
chain/client/src/stateless_validation/state_witness_producer.rs
integration-tests/src/tests/client/process_blocks.rs

I wasn't too happy exposing chunk_endorsements cache in `ChunkEndorsementTracker` that was introduced as part of this PR: https://github.com/near/nearcore/pull/10531
Hopefully this is better structured. Suggestions are welcomed!

[stateless_validation] Cleanup for bypass sending stateless validation messages to ourselves

---

runtime/near-wallet-contract/Cargo.toml
runtime/near-wallet-contract/README.md
runtime/near-wallet-contract/build.rs

Looks like https://github.com/near/nearcore/pull/10436 is not enough, because the WASM file is still generated if someone manually run tests with `--all-features` flag, which triggers `build_wallet_contract` too.
To make sure it does not happen at all, I would disable the Wallect Contract build completely. We currently do not use it anyway.

fix: Disable generation of WASM file for Wallet Contract

---

nightly/pytest-sanity.txt
pytest/tests/sanity/resharding_restart.py

Test that resharding is correctly resumed (not restarted) if the node is restared after resharding was finished. 
cc @posvyatokum @marcelo-gonzalez 
I wonder what is the difference between this setup and the mocknet setup where it failed?

test(resharding) - test node restart after resharding

---

chain/chain/src/chunk_endorsement.rs
chain/client/src/metrics.rs
chain/client/src/stateless_validation/chunk_endorsement_tracker.rs
core/primitives/src/stateless_validation.rs
integration-tests/src/tests/client/features/limit_contract_functions_number.rs

This PR adds the following metrics emitted by the block producer:
* Histogram for the endorsed stake ratio. This could help us to identify if chunks are missed because of insufficient endorsement stake.
* Histogram for the number of missing endorsement signatures, so we can track how many validators failed to send the endorsement in time.

feat: add metrics around chunk endorsements

---

chain/chain/src/garbage_collection.rs
core/store/src/columns.rs

My node running shadow chunk validation recently crashed with `IO error: No space left on device`.
RocksDB metrics over the last 7 days confirm that `StateTransitionData` caused that: 
This PR makes `StateTransitionData` a part of block c collection.

feat: add gc for StateTransitionData

---

chain/chain/src/chain.rs
chain/client/src/sync/state.rs

I haven't verified it but it seem that restarting the node during catchup does not resume the catchup but rather it restarts the whole resharding from scratch. While suboptimal I'm not aiming to fix that now. This PR merely moves the deletion of state snapshot to after catchup is finished. This way the restarted resharding can succeed.

fix(resharding): delay deleting the snapshot until after catchup

---

tools/amend-genesis/src/lib.rs

currently we are only setting it if --shard-layout is passed to amend-genesis, but it should be set either way. Also get rid of a TODO that is actually done

fix(amend-genesis): set num_block_producer_seats_per_shard correctly

---

chain/client/src/stateless_validation/state_witness_producer.rs
chain/epoch-manager/src/tests/mod.rs
core/primitives/src/validator_signer.rs

We already serialise state witness in order to sign it, so this PR extends `sign_chunk_state_witness` to also return serialised data size and emits as `near_chunk_state_witness_total_size` metric (was added as part of shadow chunk validation in #10478).

feat: emit state witness size metric as part of `send_chunk_state_witness_to_chunk_validators`

---

.github/workflows/ci.yml

Considering that neither sccache nor swatinem’s cache seem to work well for us, let’s just kill the caches altogether, both for simplicity and to avoid wasting time tarballing&uploading the cache.
Also increase a bit the size of the runners for the 3 jobs that were taking our CI runtime from 13’ to 18’ before we started trying out sccache.

remove useless ci cache, increase a bit the size of runners for the slowest jobs

---

chain/client/src/client_actor.rs
chain/client/src/stateless_validation/chunk_validator.rs
chain/client/src/stateless_validation/mod.rs
chain/client/src/stateless_validation/processing_tracker.rs
chain/client/src/test_utils/test_env.rs
integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
integration-tests/src/tests/client/features/in_memory_tries.rs
integration-tests/src/tests/client/features/stateless_validation.rs

State witnesses are processed asynchronously - a task is spawned on a separate thread, which validates the state witness and then sends out chunk endorsements. Currently there's no way to directly wait for this processing to finish, one can only wait for the chunk endorsements to appear. This makes writing integration tests difficult. Let's add a way to wait for the processing to finish, which will make writing the tests easier.
Details:
There's no network stack in integration tests, all messages are passed around manually. We first propagate all state witness messages, which starts their processing in the background, but then we have to wait for this processing to finish before propagating chunk endorsements. As there's no way to wait for it, we have to do tricky things. The current …

Add a way to wait until a state witness is fully processed, which makes writing integration tests easier

---

chain/client/src/test_utils/test_env.rs
integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
integration-tests/src/tests/client/features/adversarial_behaviors.rs
integration-tests/src/tests/client/features/in_memory_tries.rs
integration-tests/src/tests/client/features/stateless_validation.rs

The tests in `adversarial_behaviors.rs` didn't work with stateless validation, let's make them pass again.
To achieve this we first need to propagate chunk state witnesses and endorsements, and then adjust the expected behavior to match the one exhibited by stateless validation. 
The most complex part of this PR is modifying which blocks should be skipped in `test_banning_chunk_producer_when_seeing_invalid_chunk_base()`.
This function creates a blockchain with one malicious chunk producer and runs it for a few epochs. 
Which blocks will be skipped depends on whether we are using stateless validation or not.
In the old version of the protocol the invalid chunk is included in a block and then the whole block is validated. The chunk is invalid, so the whole block is also invalid and the …

fix: make adversarial_behaviors tests pass with stateless validation

---

chain/client/src/chunk_inclusion_tracker.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs

Currently `prepare_chunk_headers_ready_for_inclusion` is called twice when producing a block:
* directly as part of `ClientActor::handle_block_production` 
* `ClientActor::handle_block_production`  -> `ClientActor::produce_block` -> `Client::produce_block`
This results in endorsement metrics (see #10533) emitted twice.
This PR fixes it by adding `produce_block_on_head` with `prepare_chunk_headers` argument to avoid calling `prepare_chunk_headers_ready_for_inclusion` from `ClientActor` while still calling it from the tests.

fix: compute chunk signatures once

---

integration-tests/src/tests/runtime/test_evil_contracts.rs
runtime/near-test-contracts/test-contract-rs/src/lib.rs

A very minimal test I wrote to check just how deep can we go with calling self to delay completion of a receipt.

test: add a test for self-call delay via x-contract calls

---

chain/client/src/stateless_validation/chunk_endorsement_tracker.rs

Testing is pending. It's not very easy because ShardsManager right now still forwards all parts to all block producers.

[Chunk Endorsement] Use partial chunk to get header instead of full chunk

---

nightly/pytest-sanity.txt

Stateless Validation is enabled in nightly and it breaks the resharding tests. This PR disabled those tests in nightly. 
sample output:
```
2024-02-07T13:49:51.368919Z  INFO network: ed25519:FXXrTXiKWpXj1R6r5fBvMLpstd8gPyrBq3qMByqKVzKF: Peer Some(ed25519:He7QeRuwizNEhBioYG3u4DZ8jWXyETiyNzFD3MkTjDMf@127.0.0.1:24577) disconnected, reason: peer banned: BadChunkStateWitness
```
Then the validators refuse to talk to each other stop producing blocks and the tests timeouts.

fix(resharding) - disable nightly nayduck tests

---

nightly/expensive.txt

The tests were failing in nayduck because the name of the test was wrong and no tests were actually executed. 
e.g.
```
https://nayduck.near.org/#/test/571329
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 57 filtered out; finished in 0.00s
```
I'm hoping this should help. I tried one of the tests and it passed.

fix(nayduck) - update test names after refactoring

---

chain/client/src/test_utils/client.rs
integration-tests/src/tests/client/process_blocks.rs

This test didn't work with stateless validation because it didn't propagate chunk state witnesses and endorsements as needed.
I modified the test to use `TestEnv`, which allowed me to use the exisiting functionality for propagating all the partial chunk requests, state witnesses and endorsements.
This changed the assignment of chunk and block producers. Previously one of the clients was a chunk producer and the other a block producer, with their roles swapped on each block. Now the roles are assigned based on the logic in `EpochManager`. IMO it doesn't affect the test, in the crucial moment when the bad chunk mask is tested, the chunk producer is different from the block producer, just like in the original test.
The test manually produces a single chunk on shard 0 to achieve the desired …

fix: make test_bad_chunk_mask work with stateless validation

---

chain/client/src/test_utils/setup.rs
integration-tests/src/tests/client/process_blocks.rs

Cleanup of tests. One more reference of MockEpochManager and KeyValueRuntime removed! 🎉 
Waiting for PR https://github.com/near/nearcore/pull/10583 to be merged in

[cleanup] Remove references of `setup_client_with_synchronous_shards_manager`

---

chain/chunks/src/lib.rs
chain/chunks/src/test/multi.rs
chain/chunks/src/test_utils.rs
chain/client/src/test_utils/setup.rs
chain/client/src/test_utils/test_env.rs
chain/client/src/test_utils/test_env_builder.rs
core/primitives-core/src/version.rs
integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
integration-tests/src/tests/client/features/adversarial_behaviors.rs
integration-tests/src/tests/client/features/stateless_validation.rs

This properly tests the changes introduced in #10575 ; I've verified that without 10575, the stateless validation integration now fails.
This also properly implements chunk forwarding for the single shard (or rather, any number of shards) tracking case. Previously we were forwarding all parts to all block producers and all incoming chunk producers, but now we're forwarding to only those who track the corresponding shard. The TestLoop-based integration test in multi.rs have been modified to test the behavior of this new logic, too.

[Single Shard] Introduce SingleShardTracking, and fix partial chunk forwarding logic for single shard tracking.

---

core/primitives-core/src/version.rs

Setting protocol version to use `ProtocolFeature::SingleShardTracking` introduced in https://github.com/near/nearcore/pull/10582.

fix: bump statelessnet to 82

---

.github/workflows/ci.yml
Justfile
chain/chain/Cargo.toml
chain/chain/src/tests/mod.rs
integration-tests/Cargo.toml
integration-tests/src/tests/client/features/limit_contract_functions_number.rs
nearcore/Cargo.toml
neard/Cargo.toml

Introduce automatic CI checks for latest statelessnet binary used for https://github.com/near/near-one-project-tracking/issues/20. This PR adopts new check automatically.
The check is not required, in order not to block main development flow.
Wanted to make this trigger only on demand, but there is no simple way to do it.

test: statelessnet ci

---

pytest/lib/mocknet.py
pytest/tests/mocknet/load_test_spoon.py
pytest/tests/mocknet/run_adversenet.py

1. It is quite annoying to wait for sequential JSON uploading, especially for many nodes, so I parallelize this.
2. Not sure why neard init script always clears data if there is a specific function for it. Removing it from neard init - now it makes `update` command in adversenet actually working.
3. Removing neard logs on each restart because this file grows extremely quickly.
@robin-near why each "Adding account..." execution takes 5 seconds?

fix: adversenet speedups and fixes

---

core/store/src/opener.rs
integration-tests/src/tests/client/resharding.rs

In testnet we hit an issue during resharding with split storage nodes where they failed to create the snapshot required for resharding. This PR is a fix for this issue.
Link to zulip thread: https://near.zulipchat.com/#narrow/stream/308695-pagoda.2Fprivate/topic/cutting.201.2E37.2E0/near/420092380
Creation of snapshot happens via the function call `checkpoint_hot_storage_and_cleanup_columns` which takes a hot_store and creates a snapshot out of it. Later we open the snapshot `opener.open_in_mode(Mode::ReadWriteExisting)`.
The function `open_in_mode` -> `ensure_kind` -> `is_valid_kind_archive` was the point of failure. This is evident from the log line
```
Feb 06 14:19:29 testnet-rpc-archive-public-02-asia-east1-b-fc341f59 neard[1753]: 2024-02-06T14:19:29.215599Z ERROR state_snapshot: …
```

[resharding] Fix opening snapshot for split storage nodes

---

integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs

The main assertion in the integration test `test_chunk_forwarding_optimization` is disabled on `--features nightly`, which is a recent change that was introduced due to single shard tracking in https://github.com/near/nearcore/pull/10582.
Let's also disable it on `--features statelessnet_protocol`, the reasoning is similar.
Fixes: https://github.com/near/nearcore/issues/10600

fix: test_chunk_forwarding_optimization with statelessnet_protocol feature

---

core/store/src/flat/delta.rs
core/store/src/flat/storage.rs

Temporary optimization for cases when there are no state changes for a while and deltas are not removed from storage.
If we know from metadata that delta is empty, set it to empty without reading it.

fix: don't read empty flat storage deltas

---

chain/chain-primitives/src/error.rs

This error variant contains a String with additional description, but it isn't printed when the error is displayed.
Let's print the description to make errors clearer, it'll make debugging things easier.

Print error description in InvalidChunkStateWitness error

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/ondemand_fuzzer_binaries.yml
Cargo.toml

Apparently https://github.com/near/nearcore/pull/10630 was not actually enough to disable builds, as cargo does not seem to support this syntax. Instead, just remove the explicit warnings=deny setting when building fuzzers

ignore warnings when building fuzzers

---

pytest/lib/mocknet.py

Setting up adversenet failed when I used a neard binary url with `&` sign.
It worked so far with `s3` urls as they did not have ampersand.
Related PR: https://github.com/near/near-ops/pull/1579

Missing parentheses around url for wget for mocknet

---

.github/workflows/master_fuzzer_binaries.yml

This should hopefully counter the issue that our fuzzers are currently facing, and that stem from -C target-cpu=native in bolero code: https://github.com/camshaft/bolero/blob/a9dc98616435c85daca4b1612eb4b014c757d7db/bin/cargo-bolero/src/project.rs#L143

hardcode target cpu for clusterfuzz targets

---

chain/chain/src/chain.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/epoch-manager/src/adapter.rs
integration-tests/src/tests/client/features/stateless_validation.rs

When Client start processing a new `ChunkStateWitness` which it received, it immediately fetches the previous block and the previous chunk using `prev_block_hash` and `shard_id` provided by the `ChunkStateWitness`.
It turns out that the current implementation of `Chain::get_prev_chunk_header` will panic if it's given an invalid `shard_id`, which means that a malicious peer could send  a `ChunkStateWitness` with a bad `shard_id` and it would crash the node that received it.
https://github.com/near/nearcore/blob/c5c84adbadf54957083a33ec243cb334b411daee/chain/client/src/stateless_validation/chunk_validator.rs#L596-L607
`Chain::get_prev_chunk_header` is very deceptive, it returns a `Result`, but still does an `unwrap()` inside. Let's fix the problem by removing the `unwrap()`. From now on …

fix: don't panic when a Client receives ChunkStateWitness with invalid shard_id

---

chain/chain/src/chain.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/client/Cargo.toml
chain/client/src/client.rs
chain/client/src/stateless_validation/chunk_validator.rs
chain/client/src/stateless_validation/state_witness_producer.rs
chain/client/src/view_client.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/lib.rs
chain/epoch-manager/src/tests/mod.rs
chain/epoch-manager/src/types.rs
chain/epoch-manager/src/validator_selection.rs
core/primitives/src/block_header.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/errors.rs
core/primitives/src/sharding.rs
core/primitives/src/stateless_validation.rs
integration-tests/src/tests/client/features/adversarial_behaviors.rs
integration-tests/src/tests/client/features/stateless_validation.rs
tools/state-viewer/src/epoch_info.rs

This PR removes "approve anything" shortcut when previous chunk is part of genesis. The only difference in case of genesis is that we don't want to execute main state transition and instead just check that post state root matches genesis state root for that shard.
This also exposed some issue I had to fix to make tests work:
* `MockEpochManager::get_epoch_chunk_producers` returns empty Vec which results in `Chain:: should_produce_state_witness_for_this_or_next_epoch` returning `false`. Fixed by adding `is_chunk_producer_for_epoch` as part of `EpochManagerAdapter` so `MockEpochManager` can override it.
* `test_chunk_state_witness_bad_shard_id` test started failing: this actually uncovered a real issue which could result in crashing chunk validator when state witness contains invalid shard …

fix: properly handle genesis as part of stateless validation

---

tools/mirror/src/lib.rs

When `mirror run` is run for the first time, we call add_create_account_txs() for each of the first 5 blocks before we start sending transactions because normally this is called on the block that's 5 blocks ahead of the block we're currently preparing transactions for. But there is an off-by-one error here, where we take the first 5 block heights, say [10, 11, 12, 13, 14]. And then on the first call to queue_txs(), `tracker.next_heights()` will return 10 for the next height, and 16 for the height to look for create account receipts, skipping 15. So we need to just add one to the number of blocks we send create account txs for at the start of sending traffic

fix(mirror): fix skipped account creations in the fifth block

---

chain/client/src/stateless_validation/state_witness_producer.rs

With `ok_or` string interpolation is executed even when there is no error which is the prevalent case.

fix: avoid unnecessary string interpolation

---

chain/client/src/stateless_validation/state_witness_producer.rs

To be consistent with how we handle missing state transition data for applying chunks:
```
let StoredChunkStateTransitionData { base_state, receipts_hash } = store
.get_ser(
near_store::DBCol::StateTransitionData,
&near_primitives::utils::get_block_shard_id(main_block, shard_id),
)?
.ok_or(Error::Other(format!(
"Missing main transition state proof for block {main_block} and shard {shard_id}"
)))?;
```

fix: return an error instead of panic for missing transactions validation storage proof

---

chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/store.rs

This PR is a fix for the issue where when we restart a node doing resharding and in the catchup phase.
High level issue: When we restart a node in the epoch when resharding in happening, what happens is we go through the whole state_sync process from the beginning which includes resharding. Once building of the child trie is completed, we then do a catchup, apply the split state to the child tried and delete the split state changes for resharding [here](https://github.com/near/nearcore/blob/e00dcaa72cfed35831b1e72760d21bb8152f1049/chain/chain/src/chain_update.rs#L399).
Zulip thread link: https://near.zulipchat.com/#narrow/stream/308695-pagoda.2Fprivate/topic/Problems.20after.20resharding.20restart/near/421312417
This is the implementation of Option 1 in the thread.
The key idea here is to …

[resharding] Handle case of restarting node during resharding catchup

---

chain/rosetta-rpc/src/adapters/nep141.rs

A new clippy lint has recently been activated in https://github.com/near/nearcore/pull/10654, which caused `cargo clippy` to emit a warning because the rosetta rpc code uses `.or()` instead of `.or_else()`. Fix by changing it to `or_else()`:
```console
~/nearcore$ cargo clippy
Checking near-rosetta-rpc v0.0.0 (/home/ubuntu/nearcore/chain/rosetta-rpc)
error: use of `or` followed by a function call
--> chain/rosetta-rpc/src/adapters/nep141.rs:119:66
|
119 |       let serde_call_result = serde_json::from_slice(&call_result).or(Err(
|  __________________________________________________________________^
120 | |         crate::errors::ErrorKind::InternalInvariantError(format!(
121 | |             "Couldn't read the value from the contract {:?}, for the account {:?}",
122 | | …
```

fix: clippy lint in rosetta rpc

---

chain/client/src/client_actions.rs
chain/client/src/stateless_validation/chunk_validator/mod.rs
chain/client/src/stateless_validation/chunk_validator/orphan_witness_handling.rs
chain/client/src/test_utils/test_env.rs
chain/network/src/client.rs
chain/network/src/peer/peer_actor.rs
integration-tests/src/tests/client/features/orphan_chunk_state_witness.rs
integration-tests/src/tests/client/features/stateless_validation.rs

The current logic of banning peers that sent a message with invalid ChunkStateWitness is flawed - it bans the peer that forwarded the message instead of the one that produced it, which means that innocent peers could be banned for forwarding a bad message.
Let's remove the existing banning logic because it's invalid. Later it can be properly reimplemented in another PR.
Fixes: https://github.com/near/stakewars-iv/issues/17
Refs: [zulip conversation](https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/StatelessNet.20monitoring/near/423565210)

fix: Don't ban peers for invalid ChunkStateWitness messages

---

chain/client/src/client.rs
chain/client/src/stateless_validation/chunk_validator/orphan_witness_handling.rs
chain/client/src/stateless_validation/chunk_validator/orphan_witness_pool.rs

Orphaned witnesses which are below the final height of the chain will never be processed, so let's remove them from the orphan pool to free up memory.
Fixes: https://github.com/near/nearcore/issues/10649

feat: clean orphaned witnesses below the last final height

---

chain/chain/src/chain.rs
chain/chain/src/store.rs
chain/chain/src/test_utils.rs
chain/client/src/sync/header.rs
chain/epoch-manager/src/lib.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/test_utils.rs
tools/state-viewer/src/apply_chain_range.rs

Noticed the introduction of `is_genesis` function in https://github.com/near/nearcore/pull/10633
This PR tries to use the `is_genesis` function in place of comparing prev_hash with CryptoHash::default()

[cleanup] Use `is_genesis` function where ever possible

---

pytest/tests/sanity/staking2.py

Force tracking shard 0 for all nodes in staking-related pytests.
Current failures are caused by stake of some nodes going to 0, which causes node to fall out of validator set and stop tracking shard 0. When it gets back, state sync is triggered, which is (currently?) supported only in state-sync related tests.
With that simple change, all staking tests pass now: https://nayduck.near.org/#/run/3398.

fix: pytest staking tests and tracking shards

---

Cargo.lock
core/async/Cargo.toml
core/async/src/messaging.rs

Also add a test for this behavior.
Closes #10660

Fix AsyncSender so that the callback does not panic when the response future is dropped.

---

chain/client/src/stateless_validation/state_witness_producer.rs

Such situations indicate illegal state/programmatic error that will result in missing chunk. It is still better to avoid panic in such case, so we return `Err` instead. This PR adds `log_assert_fail` which was introduced specifically for such cases.

fix: use `log_assert_fail` when creating state witness with missing proof

---

runtime/near-vm/compiler/src/lib.rs
runtime/near-vm/engine/src/lib.rs
runtime/near-vm/types/src/lib.rs
runtime/near-vm/vm/src/lib.rs
runtime/near-vm/wast/src/lib.rs

https://blog.rust-lang.org/2024/02/28/Clippy-deprecating-feature-cargo-clippy.html

fix: fix feature = "cargo-clippy" deprecation

---

chain/chain/src/flat_storage_creator.rs
core/store/src/flat/manager.rs
core/store/src/flat/storage.rs

The root cause of the resharding issue in mocknet testing seems to be that when the node is restarted the flat storage is not recreated. Without flat storage when applying the first block of the new epoch we get different state roots than the nodes that do have flat storage. 
This PR introduces creating the flat storage for the children shards aka next epoch shards. This is depended on the flat storage status that is set at the end of resharding [here](https://github.com/near/nearcore-private/blob/1a4756e1acbebc073f312fde1457be47e1da3fc0/chain/chain/src/resharding.rs#L180). 
I failed to reproduce the issue so we'll need to test it in mocknet unfortunately. We should test all the cases (no restart, restart during resharding, restart during catchup, restart post catchup). cc …

fix(resharding): create flat storage for children shards after node restart

---

core/primitives-core/Cargo.toml
core/primitives/Cargo.toml
core/store/Cargo.toml
nearcore/Cargo.toml
runtime/runtime/src/lib.rs

#10676 introduced receipt variant `ReceiptEnum::PromiseResume` to distinguish yield resume receipts from normal data receipts. We should use that type not just for receipts submitted via `promise_yield_resume` but also for the receipts generated by yield timeouts.
Also in that PR, deserialization for the `PromiseResume` and `PromiseYield` types is gated behind a feature flag `yield_resume`. However, the flag was not properly configured everywhere.

fix: Deliver correct receipt type for yield timeouts

---

core/primitives/src/utils.rs
runtime/runtime/src/ext.rs
runtime/runtime/src/lib.rs

This PR renames the utility function `create_data_id` to `create_receipt_id_from_action_hash`.
The receipt id is a concept which exists at the Receipt level and is not specific to a kind of Receipt (whether action or data). Each id needs to be globally unique across receipts of all kinds, and the ids used for action and data receipts share the same properties. 
There is no meaningful distinction to be made between "data ids" and other kinds of receipt ids, so I find the name of this low-level utility to be misleading.  In particular, it would not be incorrect to generate an id for an action receipt using the function in question.
Renaming the function better reflects what it actually does rather than how it happens to be used.

refactor: Rename receipt id utils for clarity

---

chain/chain/src/flat_storage_creator.rs
core/store/src/flat/metrics.rs
core/store/src/flat/storage.rs
core/store/src/metrics.rs

During resharding we maintain flat storage for both the parent and children shards. In order to disambiguate and not mix the metrics for shards with the same ids we should use shard_uid instead of shard_id.

fix(metrics): changed shard id to shard uid in flat storage metrics

---

chain/indexer/src/lib.rs
chain/indexer/src/streamer/mod.rs

Hello everyone!
This pull request addresses two urgent tasks related to our project's [Read RPC](https://github.com/near/read-rpc) functionality.
[Issue 1](https://github.com/near/read-rpc/issues/188): 
Making our state-indexer compatible with the near-indexer to eliminate the 3-second delay caused by [Lake-framework](https://github.com/near/near-lake-framework-rs). This compatibility enhancement ensures smoother and more efficient operation of our system by removing unnecessary delays.
[Issue 2](https://github.com/near/read-rpc/issues/186): 
Enhancing our service to handle requests for optimistic blocks directly, without proxying to nodes. This optimization streamlines the process, improving response times and overall system performance.
To achieve these tasks, modifications have been …

Enhancements for Read RPC: Compatibility with near-indexer and Handling Optimistic Blocks

---

pytest/lib/resharding_lib.py
pytest/tests/sanity/resharding_restart.py

Checking that flat storage exists for the right shards at right times before and after the restart. 
Again, I couldn't actually trigger the error condition from mocknet but this is better than nothing.

feat(resharding): Added checks for flat storage in the resharding restart test

---

core/store/src/flat/manager.rs

Removing the assertion and allowing flat storage to be created multiple times for a shard. This is needed so fix an issue when node is restarted in the middle of resharding. The flat storage may be created already for a subset of shards but unless all are finished resharding will get restarted. Becuase the flat storage was created, for those shards, it will be created on node startup as well as after the second resharding is finished. 
This is not a perfect solution and not particularly clean. The best alternative seems to be to implement resuming of resharding where we don't restart resharding for shards that were finished. This is more a comlex change and we want to get this PR in to the release so for now I'm sticking to the simplest approach. 
This seems to be safe because even though …

fix(resharding): Allow creating the flat storage multiple times for a shard. 

---

chain/chain/src/store_validator.rs

refactor: use NightshadeRuntime in store_validator tests

---

chain/chain/Cargo.toml
chain/chain/src/test_utils.rs
chain/chain/src/tests/garbage_collection.rs

Part of https://github.com/near/nearcore/issues/10678 and https://github.com/near/nearcore/issues/10634.
Tests are updated to reflect the actual behaviour of chain garbage collection.

refactor: use NightshadeRuntime for chain garabage collection tests 

---

chain/chain/src/test_utils/kv_runtime.rs
core/primitives/src/receipt.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/prefetch.rs
tools/mirror/src/chain_tracker.rs
tools/mirror/src/lib.rs

In #10676 we introduced ReceiptEnum variants `PromiseYield` and `PromiseResume`.
At the time `Action` and `PromiseYield` receipts were treated identically through the protocol, so it was reasonable to have unified helpers `is_action` and `action`.
After #10689 there are fundamental  and subtle differences between `Action` receipts and`PromiseYield` receipts (for example how they are handled in [apply_receipt](https://github.com/near/nearcore/blob/6a68a2b18a8e17c9f1946d5ccd49742e7e14b587/runtime/runtime/src/lib.rs#L1039)). It seems safer now to explicitly specify behavior everywhere.

refactor: erase ReceiptEnum::is_action and ::action

---

pytest/lib/cluster.py
pytest/tests/sanity/resharding_rpc_tx.py

Something's changed and now when submitting the transaction the result has status "EXECUTED" and when getting the status later via RPC the result has status "FINAL". Previously the test was asserting equality of those, now adjusted to accomodate the different statuses. 
First commit is just a minor refactor and the second one is the actual fix. Best reviewed separately.

fix(resharding): fixed the resharding_rpc_tx nayduck test

---

chain/chunks/src/test/basic.rs
chain/chunks/src/test/multi.rs
chain/client/src/test_utils/client_actions_test_utils.rs
chain/network/src/test_loop.rs
core/async/src/examples/actix_component_test.rs
core/async/src/examples/async_component_test.rs
core/async/src/examples/sum_numbers_test.rs
core/async/src/test_loop.rs
core/async/src/test_loop/adhoc.rs
core/async/src/test_loop/delay_sender.rs
core/chain-configs/src/updateable_config.rs
integration-tests/src/tests/client/features.rs
integration-tests/src/tests/client/features/multinode_test_loop_example.rs
integration-tests/src/tests/client/features/simple_test_loop_example.rs

An integration test written in TestLoop that runs 4 validators while propagating network messages Block and Approval. We can see from the visualizer that the four nodes produce blocks together:
Now, there's an issue - the blocks don't have any chunks. And that is because the chunks never finish processing, since processing of the chunks happen in a rayon thread that isn't supported by test loop yet. The blocks are still produced anyway after waiting long enough (in virtual time).
The test completes in 0.19s.
Btw, I'm not attempting to make the test modular or clean yet. My goal right now is just to work towards a functional integration test that does state sync and later in-memory trie.

[TestLoop Refactoring] Basic multi-node Client test based on TestLoop

---

Cargo.lock
core/primitives/Cargo.toml
core/primitives/src/lib.rs

Based on the clusterfuzz web UI I cannot confirm whether it is actually working properly, and I’m under the impression that it is actually not running the fuzzers we’re asking it to.
This fuzzer should make it obvious: if clusterfuzz does not report a fuzzer failure on it, then it is broken.
There is no good place for it, so I just put it in our current "everything else" near-primitives crate, as it has basically no internal dependencies on anything it’ll be very easy to move it out whenever we actually get close to getting rid of near-primitives.

introduce an always-failing fuzzer, to sanity-check our clusterfuzz setup

---

runtime/near-vm-runner/src/logic/tests/promises.rs

The panic message for this assert doesn't match the behavior. See also:
https://github.com/near/nearcore/blob/8e0bdf35153bb830521788451a57585ca6263573/runtime/near-vm-runner/src/logic/logic.rs#L2225-L2249

fix: test_promise_results panic message

---

core/parameters/Cargo.toml
core/parameters/src/view.rs

Runtime config check related tests are not supposed to run on nightly and statelessnet.
Originally broken in https://github.com/near/nearcore/pull/10703

[fix] Fix Linux StatelessNet Github CI

---

pytest/tests/mocknet/helpers/neard_runner.py

sys.exit() doesn't do what you'd think in python threading.Threads. If it's called in an RPC handler, it just causes that handler to exit, and when it's called in main_loop(), it just causes that function to exit, but the program is still running and accepting connections, which can be quite confusing when main_loop() was expected to do some work after an RPC call returns OK. 
So instead of calling sys.exit(), we can add a TestState.ERROR variant and set the state to that when something bad seems to have happened, and then the test operator can take a look and hopefully fix it.

fix(mocknet): avoid calling sys.exit() in neard runner

---

chain/epoch-manager/src/lib.rs
chain/epoch-manager/src/tests/mod.rs

The HashMap returned by `EpochManager::compute_kickout_info()` currently removes all stats for validators who were kicked for not producing enough blocks before returning. This is required because `RewardCalculator::calculate_reward()` requires that the `validator_block_chunk_stats` arg passed to it only contain non-kicked validators that get rewards. But an unintended consequence of this is that we don't save to disk the stats for kicked validators, and calls to the "validators" RPC method will return all zeros for those validators. 
Since the only two places where this validator stats map is accessed is in responding to those RPC calls and computing rewards, we can change it to not to forget about kicked validators as long as we remove those before computing rewards.
To make sure this …

fix(epoch-manager): save all validator production stats

---

chain/indexer-primitives/src/lib.rs
core/primitives/src/views.rs

This pull request adds the Clone derive for specified primitive structs, enabling easy creation of deep copies. It improves usability, consistency, and readability while adhering to Rust conventions.
**Why This Matters:**
- **Enhanced Usability:** With the `Clone` trait implemented, users can easily create copies of these structs without manually implementing the clone functionality, which improves usability and reduces boilerplate code.
- **Consistency and Readability:** By ensuring consistency in our codebase and following Rust conventions, we enhance code readability and maintainability.
- **Performance:** While cloning can incur performance overhead, it's often necessary in certain contexts, and having it readily available can streamline development processes.

Add Clone derive for primitive structs

---

tools/congestion-model/src/model/chunk_execution.rs
tools/congestion-model/src/model/transaction.rs
tools/congestion-model/src/workload/transaction_builder.rs

Adding several reader methods on the chunk execution context to allow strategies to depend on transaction details and block height.

congestion: more context info for strategies

---

chain/client/src/chunk_inclusion_tracker.rs
chain/client/src/client_actions.rs
chain/client/src/stateless_validation/chunk_endorsement_tracker.rs
core/primitives/src/stateless_validation.rs

@Longarithm mentioned that chunk endorsement metrics (added in #10533) are recorded every time we check if the chunk is ready for inclusion. The intent was to only emit those when the block is actually produced which is implemented in this PR.
I've also noticed that we emit a warning log in a similar fashion, that is also fixed in this PR.

fix: record chunk endorsement metrics only when the block is actually produced

---

core/store/src/genesis/initialization.rs
core/store/src/genesis/mod.rs
core/store/src/genesis/state_applier.rs
integration-tests/src/runtime_utils.rs
nearcore/src/lib.rs
pytest/tests/mocknet/helpers/neard_runner.py
runtime/runtime/tests/runtime_group_tools/mod.rs

`near_store::genesis::initialize_genesis_state()` uses the shard layout found in the genesis config when computing the initial state roots. This works fine as long as the `use_production_config` parameter is `false`. But when it's `true`, this shard layout is not necessarily the same as the one we'll get in the first epoch of the chain. So with the resharding in protocol version 64, that means that if we try to start a mocknet test forked from a 4-shard mainnet with starting protocol version 64, we hit [this assert](https://github.com/near/nearcore/blob/fb500f5b976669e2e481f1d8e3bee49dced022ec/core/primitives/src/block.rs#L102) because `initialize_genesis_state()` computed its state roots based on the 4 shards specified in the genesis config, but the `shard_ids` slice we're comparing it …

fix(genesis-init): respect genesis.use_production_config when computing genesis state

---

chain/chain/src/store.rs
core/primitives-core/src/version.rs
core/primitives/src/epoch_manager.rs
core/primitives/src/shard_layout.rs
core/store/src/config.rs

This PR is to be cherry-picked into release 1.38.0 for splitting shard 2 into two parts.
Hot and kai-ching both fall on shard 2 which has been causing a lot of congestion.
Zulip thread: https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/constant.20congestion.20on.20shard.202/near/425367222

[resharding] Nightshade V3 shard layout for protocol version 65

---

Cargo.lock
core/primitives/src/action/mod.rs

backport: crates 0.20.1 had two important fixes that has to be in 1.37.x release

---

neard/Cargo.toml

This allows building only `neard` binary for testing with `cargo build -p neard --features shadow_chunk_validation`.

feat: add `shadow_chunk_validation` feature to neard

---

core/store/src/metrics.rs

As these metrics were recently changed and continuity of data is broken, we can add "near_" prefix to prometheus metrics which was missing all the time. 
@wacban I wonder how painful is it to add this to 1.38 for convenience?

fix: near_ prefix to flat storage metrics

---

core/parameters/res/runtime_configs/139.yaml
core/parameters/src/snapshots/near_parameters__config_store__tests__139.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_139.json.snap
integration-tests/src/tests/runtime/mod.rs
integration-tests/src/tests/runtime/test_evil_contracts.rs
integration-tests/src/tests/runtime/test_yield_resume.rs
runtime/near-test-contracts/test-contract-rs/src/lib.rs

This PR adds a couple of basic integration tests for yield execution:
- tests behavior in the case `promise_yield_resume` is called with an unexpected data id
- tests behavior in the case that `promise_yield_create` and `promise_yield_resume` are called within the same transaction
Why do we start with these edge cases? As it stands the testing infrastructure in [runtime_user.rs](https://github.com/near/nearcore/blob/master/integration-tests/src/user/runtime_user.rs#L344) expects all receipts generated by a transaction to be resolved immediately once the transaction is executed. Calling yield without resume in any transaction breaks that assumption, so adding such tests will be a bit more involved.
I had to drop the placeholder gas costs to get these tests to pass.
I will follow up with a …

yield/resume: init integration tests

---

tools/congestion-model/src/evaluation/mod.rs
tools/congestion-model/src/model/queue.rs

So far, we only printed the queue length, as in "number of elements". But we are much more interested in the size in bytes, as this is the real constraint. Also add the same for attached gas, as this can be interesting, too.
The way this is computed, it's rather inefficient. We might want to compute the sums more efficiently.
But running
`time cargo run --release -- --write-stats`
still finishes in
`real    0m18.183s`
on my machine, so I guess it's still tolerable, for now...

congestion: print queue size in bytes and gas

---

chain/client/src/stateless_validation/state_witness_producer.rs

Currently shadow validation node crashes in `dev-release` when started with mainnet database snapshot due to missing `StateTransitionData` not being previously saved, which is expected.

fix: don't fail on missing state transition data with shadow validation

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/workload/all_for_one.rs

Rather than just sending single-receipt actions, we want transactions that touch multiple shards. Specifically, we want workloads that are not very predictable with regards to which shard will be burning most of the gas.
With  this commit, we have an "All To One" and an "Indirect All To One" strategy. The first is what we had before, depth 1 transactions only. The second is with transaction of up to depth 3.

congestion: multi-hop transactions in all-for-one workload

---

integration-tests/src/tests/runtime/test_yield_resume.rs
integration-tests/src/tests/standard_cases/mod.rs
integration-tests/src/user/mod.rs
integration-tests/src/user/rpc_user.rs
integration-tests/src/user/runtime_user.rs
runtime/near-test-contracts/test-contract-rs/src/lib.rs

Follow up to #10746. Adds a test with separate transactions creating a yield and then resuming it.

yield/resume: add test create_then_resume

---

docs/practices/style.md

Pushing people towards the `tracing::*_span!` has caused us some significant grief, especially in https://github.com/near/nearcore/pull/10663 so we better allow and encourage `#[instrument]`.

doc: adjust the style guide on `#[instrument]`

---

runtime/near-vm-runner/src/cache.rs

While this span is not very frequent, it does not provide particularly much information to trace it, so lets redelegate it to a more verbose level.

refactor: downgrade `vm::get_key` span to the trace level

---

chain/jsonrpc/src/lib.rs
core/primitives/src/views.rs

All the logic of `tx_status_fetch` function is: we poll tx_status method and wait for the desired level of tx finality.
`tx_status_fetch` is used in several places including `broadcast_tx_commit` RPC method.
With the chunk congestions we have right now, we return `UNKNOWN_TRANSACTION` error to `broadcast_tx_commit` after 20 seconds of waiting, which is both sad and weird.
The error we store in `tx_status_result` is not good enough to show it to the user, otherwise we would break from the loop with it immediately.
If we reach the timeout boundary, I suggest always to return timeout error.

rpc: return timeout error from tx_status_fetch

---

chain/network/src/peer/peer_actor.rs

refactor: replace explicit spans with `#[instrument]` in peer_actor

---

core/store/src/lib.rs
runtime/near-vm-runner/src/logic/mod.rs

This instruments the `StoreCompiledContractCache` to show an overall cost of these operations whenever they are used. The level I've chosen here is `trace` to avoid polluting the traces too much in default operation. #10774 has a targeted instrumentation at a higher level.

tracing: instrument contract cache operations

---

chain/chain/src/chain.rs
chain/client/src/view_client.rs

Ideally, we need to rewrite `chain.get_final_transaction_result` method completely.
But for now, let's start at least with supporting `TxExecutionStatus::Included` status.

support Included transaction status

---

tools/database/src/analyze_delayed_receipt.rs
tools/database/src/commands.rs
tools/database/src/lib.rs

Add a script that analyzes congestion of shards by looking at delayed receipts for each shard.

feat(tool): add analysis for delayed receipts

---

Cargo.lock
Cargo.toml
chain/indexer/CHANGELOG.md
chain/indexer/Cargo.toml
chain/indexer/src/lib.rs
chain/indexer/src/streamer/fetchers.rs
chain/indexer/src/streamer/metrics.rs
chain/indexer/src/streamer/mod.rs

Today on testnet, we encountered very weird behavior from the indexers. Indexing BPS dropped to 0.004 blocks per second. This speed is unacceptable, especially when indexing the blocks already synced by the node.
After an investigation, we found the suspect. The most obvious suspect was the process of looking for the local delayed receipt. This kind of receipt is treated differently by the indexer. On the indexer side, we tend to include them in the `StreamerMessage` while `nearcore` avoids storing them to save some space.
During some special periods (e.g., congestion), the number of local delayed receipts grows, leading to extra work by the indexer.
This PR introduces a local (in-memory) cache for the indexer instance to keep such receipts until they are needed. This should prevent the …

refacor(indexer): Add local cache for delayed local receipts. Metrics, log clean up and improvements

---

runtime/runtime/src/balance_checker.rs
runtime/runtime/src/lib.rs

**What?**
Before: when a yield timed out, we would resolve it by creating a new outgoing data receipt.
After: we directly process the data receipt, which we know for a fact is destined for the local shard.
To keep the balance checker happy, these receipts are essentially interpreted as additional incoming receipts.
**Why?**
This is both an efficiency improvement and a correctness fix. We avoid the need to create an outgoing receipt. We also eliminate the following possibility:
1. User submits a transaction which creates a yielded promise.
2. After some time, the timeout triggers and the protocol delivers a new outgoing receipt. Due to congestion, the timeout receipt enters the delayed receipts queue.
3. The user submits a transaction which calls yield resume. The yield callback hasn't …

yield/resume: directly process receipts from the timeout queue

---

Cargo.lock
chain/epoch-manager/Cargo.toml
chain/epoch-manager/src/lib.rs
chain/epoch-manager/src/metrics.rs
pytest/tests/sanity/upgradable.py

* Added logs about the protocol voting. Please note those are INFO level logs. I allowed myself to make it INFO because it only happens at the epoch boundary. This adds 2-3 log lines every 16 hours. 
* Added metrics about the protocol voting. This can be used for grafana and monitoring. Again, the metrics are populated only at the epoch boundary so a bit too late but it's better than nothing. It should be enough to tell why the voting didn't happen when expected. 
neard logs from the upgradable test:
```
2024-03-15T14:11:58.469094Z  INFO {height=21}: epoch_manager: Protocol version voting. version=64 stake_percent=75
2024-03-15T14:11:58.469120Z  INFO {height=21}: epoch_manager: Protocol version voting. version=65 stake_percent=25
2024-03-15T14:11:58.469143Z  INFO {height=21}: …
```

feat(voting): added logs and metrics for the protocol version voting

---

chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/tests.rs
chain/chain/src/state_snapshot_actor.rs
core/store/src/config.rs
core/store/src/db.rs
core/store/src/db/colddb.rs
core/store/src/db/rocksdb.rs
core/store/src/db/splitdb.rs
core/store/src/db/testdb.rs
core/store/src/lib.rs
core/store/src/metrics.rs
core/store/src/opener.rs
core/store/src/trie/mod.rs
core/store/src/trie/state_snapshot.rs
integration-tests/src/tests/client/state_snapshot.rs
integration-tests/src/tests/client/sync_state_nodes.rs
nearcore/src/config.rs
tools/database/src/make_snapshot.rs

If the `columns_to_keep` arg of `checkpoint_hot_storage_and_cleanup_columns()` is `Some`, then we delete all the data in every other column. Then if snapshot compaction is enabled in the configs, we rely on that to clean up the files on disk. Instead of doing that, we can just call `drop_cf()` on every unwanted column family, and the associated sst files will be removed without the need for any compactions.
So this moves the `columns_to_keep` arg to `near_store::db::Database::create_checkpoint()`, and has the rocksdb implementation of that trait call `drop_cf()` on unwanted column families. These column families are then immediately recreated in  `checkpoint_hot_storage_and_cleanup_columns()` by the call to `StoreOpener::open_in_mode()`, but the data on disk is gone.
This also means we …

fix(snapshots): drop unwanted column families instead of deleting all keys

---

Cargo.lock
tools/congestion-model/Cargo.toml
tools/congestion-model/src/evaluation/mod.rs
tools/congestion-model/src/evaluation/queue_lengths.rs
tools/congestion-model/src/evaluation/summary_table.rs
tools/congestion-model/src/lib.rs
tools/congestion-model/src/main.rs

Instead of showing the snapshot of the model in the end, it is better to display the max values throughout the model execution in the final summary table.
Also add gas and byte values of queues, rather than just the number of receipts.
This makes the summary table much more useful to quickly compare the performance of many different strategies.

congestion: Max size, gas and bytes in summary

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/workload/balanced.rs

Add configuration parameters to the balanced workload to adjust:
- How deep each transaction should be. (number of hops)
- Different receipt sizes for different depth-levels.
- How wide each transaction should be. (how many children each parent receipt spwans)
Note that the workload is still balanced evenly across all shards.
Using these new parameters, I also add two new workloads to the test suite:
- Increasing Size: Start with small receipts locally but produce large outgoing receipts.
- Shard War: Each shard multiplies small receipts locally and then blast 64 larger receipts per tx to the receiving shard.
These two workloads produce >1GB large queue in some workloads.

congestion: advanced balanced workloads

---

chain/client/src/info.rs

refactor: use NightshadeRuntime in telemetry_info test

---

core/primitives/src/receipt.rs
core/primitives/src/trie_key.rs
core/primitives/src/types.rs
core/store/src/genesis/state_applier.rs
core/store/src/lib.rs
core/store/src/trie/resharding.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/balance_checker.rs
runtime/runtime/src/ext.rs
runtime/runtime/src/lib.rs

Cleans up a few things across the board:
- All DB columns related to yield/resume now have a name with form `PROMISE_YIELD_???`
- Replaces instances of "yielded promise" so that we consistently use "promise yield" everywhere
- Columns and structs containing timeout information are named accordingly, replacing generic names e.g. `PromiseYieldQueueEntry` -> `PromiseYieldTimeout`
- The behavior of the get/set/remove methods in the store which specifically operate on PromiseYield _receipts_ and do not interact with the queue are clarified by including "receipt" in the name
- Queue metadata is named `PROMISE_YIELD_INDICES`, consistent with the other queue `DELAYED_RECEIPT_INDICES`
Apologies if this is a tough one to review; I tried to read over it and my brain is melting from reading the words …

yield/resume: improve naming consistency

---

core/parameters/res/runtime_configs/139.yaml
core/parameters/src/snapshots/near_parameters__config_store__tests__139.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_139.json.snap
runtime/near-test-contracts/estimator-contract/src/lib.rs
runtime/runtime-params-estimator/src/cost.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime-params-estimator/src/utils.rs

Somewhat surprising to me is that estimations for the resume are much more high than for create. I suspect that the estimation is covering a significant part of the transaction runtime that is not really related to the resumes, but I'm struggling to isolate the interesting parts well.
So for the time being I'm submitting the baseline safe estimates. In practice the time will be (likely, much) lower than the fees charged for the operations, but the fees are still low enough that these host functions are very usable still.
We can explore dedicating additional engineering time to isolating the regions of interest better if these turn out to be a pain point. But in the meantime lets land these.

yield/resume: gas fee estimations

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/workload/balanced.rs
tools/congestion-model/src/workload/linear_imbalance.rs

Two more workloads to really push the limits of large receipts with low gas.
Below are the results I'm getting for them with the current settings.
Note how the "no queue" strategy has 61 GB and 373 GB delayed receipts.
But even the traffic light strategy goes up to 1.5 GB and 2 GB.
```txt
WORKLOAD                 STRATEGY             BURNT GAS  TRANSACTIONS FINISHED MEAN TX DELAY   MAX QUEUE LEN  MAX QUEUE SIZE  MAX QUEUE PGAS
Extreme Increasing Size  No queues            4010 PGas                  34928           228           68955         61.6 GB            2161
Extreme Increasing Size  Global TX stop       4022 PGas                  37313           212           14169         13.2 GB             230
Extreme Increasing Size  Simple backpressure   264 PGas                   2350 …
```

congestion: workloads with big receipts

---

chain/chain/src/chain.rs
chain/chain/src/store.rs
chain/client/src/client.rs
chain/client/src/info.rs
chain/epoch-manager/src/lib.rs
core/primitives/src/block.rs

Removed some of the usage of [shard_id] that can end up with "out of bounds" panics. This is both to better handle malicious inputs and shard layout changes during resharding. Ideally I'd like to remove the Index trait on ChunkCollection but I'm not quite there yet. Deprecating it doesn't work because it's a trait...

fix: remove direct indexing by shard id

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/model/mod.rs
tools/congestion-model/src/strategy/mod.rs
tools/congestion-model/src/strategy/traffic_light.rs

A congestion strategy featuring 3 levels of traffic control.
This strategy is designed to guarantee:
- Hard limit on incoming queue length measured in attached gas.
- Soft limit on total size of receipts in incoming + outgoing receipts.
- Provably no deadlocks.
Each shard set its own traffic signal to one of:
- green (full-speed)
- amber (senders must stop accepting more load for this shard)
- red (senders must stop all load to this shard)
When a shard turns on the red light, manual traffic control ensures no
deadlocks occur. The congested shard will assign one shard each turn
that is allowed to send a limited amount of traffic. This way, some amount
of progress is guaranteed on every shard and complete deadlocks are impossible.

congestion: traffic light strategy

---

pytest/tests/mocknet/helpers/neard_runner.py

if the neard runner gets a ReadTimeout error from neard when trying to check the epoch height, this isn't a reason to crash, since it can just be retried later

fix(mocknet): ignore ReadTimeout errors from neard status page

---

pytest/tests/mocknet/helpers/neard_runner.py

with the normal min_gas_price (10x higher than this one), many mirrored mainnet transactions fail with too little balance. One way to fix that would be to increase everybody's balances in the amend-genesis command. But we can also just make this change in neard_runner.py.

mocknet: lower the genesis min_gas_price config value

---

nearcore/src/config.rs

As per https://near.zulipchat.com/#narrow/stream/295306-contract-runtime/topic/bottleneck.20on.20compile_and_load/near/427771708
This should be 2GB of RAM at most.

config: default `max_loaded_contracts` to 256

---

nearcore/src/config.rs
runtime/near-vm-runner/src/near_vm_runner.rs
runtime/near-vm/engine/src/universal/builder.rs
runtime/near-vm/engine/src/universal/code_memory.rs
runtime/near-vm/engine/src/universal/engine.rs
runtime/near-vm/engine/src/universal/mod.rs
runtime/near-vm/test-api/src/sys/store.rs
runtime/near-vm/tests/compilers/compilation.rs
runtime/near-vm/tests/compilers/config.rs
runtime/near-vm/tests/compilers/deterministic.rs
runtime/near-vm/tests/compilers/stack_limiter.rs

Now that the size of the `UniversalArtifact` cache is configurable by the operator, the `LimitedMemoryPool` would need to account for the configuration and allocate an appropriate number of pages depending on that configuration. However, we do not have easy access to that configuration from the contract runtime, and I don't think I want to unravel the thread of moving the set up of contract runtime resources all the way down to the place where this configuration is directly available.
In the long term we should still keep memory pool limited somehow and make sure we pre-allocate exactly the required number of maps of the right size. To do that we would have to refactor the contract runtime setup to rely less on the global state and do it somewhere near the setup of the transaction runtime …

near_vm: change LimitedMemoryPool to create new maps if dry

---

core/store/src/lib.rs
integration-tests/src/tests/client/process_blocks.rs
runtime/near-vm-runner/fuzz/fuzz_targets/diffrunner.rs
runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
runtime/near-vm-runner/src/cache.rs
runtime/near-vm-runner/src/lib.rs
runtime/near-vm-runner/src/logic/logic.rs
runtime/near-vm-runner/src/logic/tests/vm_logic_builder.rs
runtime/near-vm-runner/src/near_vm_runner.rs
runtime/near-vm-runner/src/runner.rs
runtime/near-vm-runner/src/tests.rs
runtime/near-vm-runner/src/tests/cache.rs
runtime/near-vm-runner/src/tests/fuzzers.rs
runtime/near-vm-runner/src/tests/rs_contract.rs
runtime/near-vm-runner/src/tests/test_builder.rs
runtime/near-vm-runner/src/tests/ts_contract.rs
runtime/near-vm-runner/src/wasmer2_runner.rs
runtime/near-vm-runner/src/wasmer_runner.rs
runtime/near-vm-runner/src/wasmtime_runner.rs
runtime/runtime-params-estimator/src/function_call.rs
runtime/runtime-params-estimator/src/gas_metering.rs
runtime/runtime-params-estimator/src/lib.rs
runtime/runtime/src/actions.rs
runtime/runtime/src/lib.rs

Backport of https://github.com/near/nearcore/pull/10852 to the 1.39.0 branch (that will be released as 1.38.1)

backport: optimization: do not load the wasm contract code if it is already cached

---

core/chain-configs/src/client_config.rs
core/chain-configs/src/updateable_config.rs
nearcore/src/config.rs

Apparently by default Option is deserialized to None when the field is missing, but if you use `serde(with = ...)`, that behavior is gone. So add `serde(default)` to bring that behavior back.

Fix `Option<Duration>` deserialization when None.

---

.gitignore

.orig files are the "originals" that you get when doing git mergetool resolutions. We don't really want them checked in anyway.
.core files are the core dumps that you may end up with around the repository in many typical linux configurations when running neard locally and it panics for any reason.

misc: add additional working files to .gitignore

---

Cargo.lock
Cargo.toml
chain/chain/src/tests/simple_chain.rs
core/parameters/src/config_store.rs
core/store/src/db/colddb.rs

Recently `cargo audit` started complaining that the `yaml-rust` dependency is unmaintained (https://github.com/near/nearcore/issues/10876). `yaml-rust` is an indirect dependency that comes from the `insta` crate, so to fix the warning we must upgrade `insta` to a version that doesn't have this problem.
The `insta` crate just had a new release which fixes the problem detected by `cargo audit` (they pasted the whole `yaml-rust` crate into their tree x.x (https://github.com/mitsuhiko/insta/pull/465)). We can upgrade to the latest version to get rid of the warning.
Upgrading to the latest version is relatively painless, I just had to replace `assert_display_snapshot` with `assert_snapshot` because `assert_display_snapshot` is now deprecated (see …

Upgrade the 'insta' dependency to version 1.37.0 to fix cargo audit warning

---

pytest/tests/sanity/resharding_rpc_tx.py

The test waits for transactions to get fully processed which slows it down. I extended the epoch lenght so that we can comfortably prepare and send transactions before resharding and check the status after. 
There was a small bug in the epoch boundary calculation that wasn't exposed until now because we would always enter the loop late.

fix(resharding) - fixed resharding rpc tx test

---

chain/chain/src/chain.rs
chain/chain/src/resharding.rs
chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/tests.rs
chain/chain/src/store_validator.rs
chain/chain/src/test_utils.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/chunks/src/logic.rs
chain/client/src/client.rs
chain/client/src/client_actions.rs
chain/client/src/info.rs
chain/client/src/sync_jobs_actions.rs
chain/client/src/test_utils/setup.rs
chain/epoch-manager/src/adapter.rs
core/store/src/config.rs
core/store/src/test_utils.rs
core/store/src/trie/config.rs
core/store/src/trie/mem/loading.rs
core/store/src/trie/shard_tries.rs
integration-tests/src/genesis_helpers.rs
integration-tests/src/tests/client/features/multinode_test_loop_example.rs
integration-tests/src/tests/client/state_snapshot.rs
tools/fork-network/src/cli.rs
tools/speedy_sync/src/main.rs

**Issue**: https://github.com/near/nearcore/issues/10564
**Summary**
Adds logic to load / unload in-memory tries that works with state sync. Enables in-memory trie with single shard tracking.
**Changes**
- Add optional `state_root` parameter for memtrie loading logic - it's needed when we cannot read the state root from chunk extra.
- Add `load_mem_tries_for_tracked_shards` config parameter.
- Add methods for loading / unloading in-memory tries.
- Remove obsolete tries from memory before each new state sync.
**Follow up tasks**
- Add shard assignment shuffling every epoch for StatelessNet: https://github.com/near/nearcore/issues/10845.
- Make sure the logic works well with resharding, and state is fully GC-ed, add integration tests: https://github.com/near/nearcore/issues/10844.

Enable in-memory trie when state sync

---

pytest/tests/sanity/resharding.py

The resharding nayduck test is [flaky](https://nayduck.near.org/#/test_history/593017). I believe that is because every now and then taking the state snapshot takes a long time and the test breaks before snapshot is ready for resharding. 
I went all the way to the following line and it seems like most of the slowness is there. It's down to rocksdb at this point and I don't feel like debugging it further so I'm just going to increase the epoch length to give the test enough time to take the snapshot and finish resharding. 
https://github.com/near/nearcore/blob/d4d1b82f39a57932eff0a7a28c5745b72915f848/core/store/src/db/rocksdb/snapshot.rs#L98

fix(resharding) - fixing the resharding.py nayduck test

---

core/primitives/src/state_sync.rs
nearcore/src/state_sync.rs
pytest/tests/sanity/gc_after_sync.py
pytest/tests/sanity/gc_after_sync1.py

This addresses `sanity/state_sync_fail.py` and `sanity/gc_after_sync.py`.
`sanity/state_sync_fail.py`- the node was trying to dump after the shard layout change.
`sanity/gc_after_sync.py` did not have state sync configured and the epoch was to short for the node to sync to the right epoch.

fix(nayduck): State sync skip state dump

---

tools/debug-ui/package-lock.json
tools/debug-ui/package.json
tools/debug-ui/src/App.tsx
tools/debug-ui/src/EpochInfoView.tsx
tools/debug-ui/src/LandingPage.tsx

I ran into errors trying to run the debug UI because of mismatched versions between `react-router` and `react-router-dom`. 
From [react-router documentation](https://github.com/remix-run/react-router/tree/main/packages/react-router#react-router):
> If you're using React Router, you should never `import` anything directly from the `react-router` package, but you should have everything you need in either `react-router-dom` or `react-router-native`. Both of those packages re-export everything from `react-router`.

debug-ui: import directly from react-router-dom

---

chain/network/src/peer_manager/network_state/mod.rs

Re-connect attempts are triggered either by:
- A newly started node reading peers from its in-database `connection_store`
- A node losing a connection and attempting to re-establish it
In both cases the peer info isn't drawn from the peer store, so it doesn't make sense to print this storage error. It leads to a bunch of log spam when a node is started:
At the same time it doesn't make sense to populate the peer store from the re-connect attempts, which may be to peers no longer present in the network.

network: clean up tracing error for reconnect

---

chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/tests.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/chain/src/update_shard.rs
chain/client/src/client.rs
chain/client/src/stateless_validation/chunk_validator/mod.rs
chain/client/src/stateless_validation/shadow_validate.rs
core/store/src/trie/mod.rs
core/store/src/trie/trie_recording.rs

Fixes the issue that caused https://github.com/near/nearcore/pull/10859 to break validation.
The flag `charge_gas_for_trie_node_access` should be forwarded to the new Trie created by `recording_reads`, otherwise the node counting won't work correctly and there'll be invalid state.
Fix the issue and bring back #10859 which was reverted in https://github.com/near/nearcore/pull/10900.

Fix gas charging when using recorded_storage + recording_reads(), bring back always recording storage

---

core/store/Cargo.toml
core/store/src/trie/shard_tries.rs
nearcore/Cargo.toml
neard/Cargo.toml

This feature was introduced long time ago but never stabilized. I believe we had canary nodes running with this feature enabled, so I think it's time.
Goal is to always save all state changes to disk. This allows to rollback flat storage without replaying previous chunk.
There is always a concern with disk usage increase. If this happens even after canary node testing, we can always roll it back. However, the proper reduction of DBCol::StateChanges should be done via replacing all values with ValueRefs, as the values are always stored in DBCol::State.

feat: stabilize serialize_all_state_changes

---

chain/epoch-manager/src/reward_calculator.rs

Fix overflow found at https://near.zulipchat.com/#narrow/stream/422293-core.2Fstake-wars-iv/topic/StatelessNet.20v84.20issue/near/430321806.
It happened with values
```
epoch_validator_reward = 1303530277894885217220048460336356
uptime_numer = 5149480000
stake = 19417599724822422137067484572677335
```
and `log2(epoch_validator_reward * uptime_numer * stake) is ~= 256.17`, so it couldn't fit in `U256`.
However, it can fit in U512, because epoch_validator_reward and stake are Balances = u128; uptime_numer fits in u64.
Note that final conversion to u128 is valid because uptime_numer/uptime_denom and stake/total_stake are <= 1.

fix: u512 on reward computation 

---

pytest/tests/mocknet/helpers/neard_runner.py

the default config produced by neard init gives us different times between blocks than what we have on mainnet. Changing this to the mainnet values will make the test conditions closer to production

mocknet: set mainnet consensus timing parameters

---

core/o11y/src/metrics.rs
nearcore/src/runtime/mod.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/metrics.rs

And also time it takes to process them.
I kinda didn't really think about how to do this right and more about how to do it fast. My head is also not working anymore today so unless its minor typo fixes, its probably better if somebody else addresses it...

[1.39] runtime: add metrics for receipt throughput

---

pytest/tests/mocknet/helpers/neard_runner.py
pytest/tests/mocknet/mirror.py
pytest/tests/mocknet/node_handle.py
pytest/tests/mocknet/remote_node.py

It is often useful to stop all the nodes and make backups of their data dirs so that we can reset to that point later. For example, when testing resharding it's nice to have a backup at a point right before the resharding epoch starts so that we can test the resharding part over and over without having to start from the beginning. So this PR adds a `make_backup` RPC method to `neard_runner.py` that stops neard and copies its data dir, remembering the `backup_id` parameter associated with it. Then in the `reset` command, the same `backup_id` can be referenced to restore to a previous backup.

feat(mocknet): add a make-backup command

---

chain/chain/src/chain.rs
chain/client/src/view_client.rs
chain/jsonrpc/src/lib.rs
core/primitives/src/views.rs
integration-tests/src/user/runtime_user.rs

More about tx execution levels: https://docs.near.org/api/rpc/transactions#tx-status-result
The levels that allow having not all the execution outcomes (Included, IncludedFinal), actually had to wait for all of the execution outcomes anyway.
[1.37.3 had a separate partial fix for supporting Included status, but let's not overcomplicate]
With the current change, we can show everything we have at the moment without extra waiting.
Also, current change helps us to be 1 step closer to resolving https://github.com/near/nearcore/issues/6834
That would be my next step after we merge this PR.
TLDR: I partially copy pasted the code.
I could have rewritten `chain:get_final_transaction_result` instead, but it has LOTS of usages everywhere. I decided it's just not safe.
I anyway changed it a little …

RPC: improve supporting tx execution levels

---

pytest/tests/mocknet/helpers/neard_runner.py

When the `force` arg of download_binaries() is true, we want to redownload everything, but the way it's done before this PR is by appending info on the new binaries downloaded to the existing "binaries" field in data.json. This is not correct because it will mess up the mid-test binary upgrade logic. So just make sure to clear that field instead of appending to the existing one
Also in the future we could consider making this a bit easier to use by passing the URLs to download from in the RPC arguments, which wasn't done originally because the ports were open to the internet. Now that it's behind ssh this isn't a concern

fix(mocknet): clear old binaries from data.json in update-binaries

---

Cargo.lock

This probably does not require a backport: the worst that could happen is RPC nodes having (much) increased latency when under attack, under some specific conditions.

bump h2 following RUSTSEC-2024-0332

---

core/store/src/trie/prefetching_trie_storage.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/prefetch.rs

This significantly reduces the cost of finalize, especially for shard 3 where they were the largest:
The effect on the overall apply duration is not as high however:
This is understandable, as ultimately all of this data that we were seeing in `finalize` still needs to be retrieved. The important part, however is that the duration of this is much more consistent and less jumpy now.
cc @saketh-are keep an eye out on whether we need to prefetch receipt data for yield-resume receipts.

runtime: prefetch account keys and data for chunk finalization

---

core/store/src/lib.rs

This reflect my understanding of DBKinds. `Archive`, `Hot`, and `Cold` dbs are only present in archival nodes. `RPC` is the only non-archival db kind.
This change will make it harder for people to open `Hot` storage as a single DB in non-archival mode. They will first have to change DBKind of hot db to `RPC` using the `database` tool of neard. Then, if they want to open this db as part of split storage again, they will need to change DBKind back using the same tool.
This whole part of code is due to a refactoring. I will think about the best project for this tasks on Monday.

fix(db): Consider hot and cold dbs archivals

---

core/store/src/flat/store_helper.rs
core/store/src/trie/iterator.rs
tools/flat-storage/src/commands.rs

Add feature to move flat head back to allow applying range of blocks for replayability and performance testing. Does not depend on `apply_chunk`, uses `DBCol::StateChanges` and some hack to account for other keys which are not yet recorded there. In future releases hack should be removed because of #10903.
Command: `./neard flat-storage move-flat-head --shard-id 2 --version 3 back --blocks 100`
Note that it doesn't record "visited" deltas to DB. This command is used for performance testing during which "future" deltas must not exist.

feat: effective flat storage rollback

---

chain/indexer/src/streamer/mod.rs
chain/indexer/src/streamer/utils.rs
core/primitives/src/version.rs
runtime/runtime/src/config.rs
runtime/runtime/src/verifier.rs

This addresses the issue from https://github.com/near/nearcore/issues/10829.
Because we plan to decrease the function call cost, we need to modify the refund estimation logic that [relies](https://near.zulipchat.com/#narrow/stream/295306-contract-runtime/topic/major.20function.20call.20fees.20today/near/427527995) on function call base cost.
This PR sets [minimum_new_receipt_gas](https://github.com/near/nearcore/blob/32ef06752f3702e22bd69542df07a4e6e123477e/runtime/runtime/src/config.rs#L270) to 108_059_500_000 + 2_319_861_500_000 + 2_319_861_500_000 ~= 4.7TGas which would limit the overcharging to 6x which is the current level.

Use constant minimum_new_receipt_gas

---

chain/chain/src/runtime/mod.rs

The checked_feature macro should always be used with the protocol version of the current block, not the binary protocol version. Otherwise the new feature would take effect during binary upgrade instead of protocol upgrade. If that happens all sorts of trouble may happen as nodes using different binaries may get diverge e.g. in state roots. 
This is a preparation for safe mainnet release.
I know it was under discussion previously but even if in this particular case it doesn't matter I would feel much safer having it done the proper way. Also it's all to easy to copy paste it elsewhere when working on the next feature so best to just stick to the rules. 
I picked the StateWitnessSizeLimit as it seemed like the proper ProtocolFeature to use for this, please correct me if I'm wrong. It …

fix(stateless-validation) - fix protocol version checks

---

chain/chain/src/runtime/mod.rs
core/o11y/src/metrics.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/metrics.rs

And also time it takes to process them.
This is a forward-port of https://github.com/near/nearcore/pull/10944

runtime: add metrics for receipt throughput

---

chain/chain/src/chain.rs
chain/chain/src/runtime/mod.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/chain/src/types.rs
chain/client/src/client.rs
chain/client/src/sync_jobs_actions.rs
core/store/src/trie/shard_tries.rs
tools/fork-network/src/cli.rs

Cleanup the Runtime interface a bit. There's no reason to have memtrie related functions in the runtime interface.
FIxed this: https://github.com/near/nearcore/issues/10872

[cleanup] Remove memtrie related function from Runtime interface

---

chain/client/src/view_client.rs
core/primitives/src/views.rs

(drums)
Resolves https://github.com/near/nearcore/issues/6834 
This PR changes the default behaviour of `broadcast_tx_commit`, `send_tx`, `tx`, `EXPERIMENTAL_tx_status` RPC methods. We no longer wait for refund receipts by default.
If you do need to wait for refund receipts, you need ask about it explicitly by using `TxExecutionStatus::Final` option (`"wait_until": "FINAL"` in the json request).
[We had a discussion with @bowenwang1996 about the case described below, tldr: he thinks it's unreachable. I haven't reproduced it, but I still think it may be an issue. I'm investigating, leave it here for now]
Ugly side-effect:
Sometimes, the response for any of mentioned methods may look like
```json
{
"jsonrpc": "2.0",
"result": {
"final_execution_status": "EXECUTED_OPTIMISTIC",
"status": …
```

rpc: ignore refunds in RPC tx methods

---

chain/chain/src/chain.rs
chain/client/src/view_client.rs

This PR is based on https://github.com/near/nearcore/pull/10948 because it touches the same places
It's better to look at the separate commits
So first commit can be reviewed separately in https://github.com/near/nearcore/pull/10948
Second commit is a partial revert of https://github.com/near/nearcore/pull/10792
I just returned this piece back, no changes is made
https://github.com/near/nearcore/pull/10792/files#diff-ef9c6aaa80a330e446c5365f42be9bff37ba4f898cf519dadd7e17545783c77cL3099-L3126 
Third commit is the meaningful part. We need to adjust the logic with the old implementation.
1. We now treat incomplete list of the receipts as a valid state. It means no `expect` usage, handle empty list of outcomes
2. We no longer can use `status` field for `finalExecutionStatus`

rpc: partial revert of #10792

---

integration-tests/src/tests/standard_cases/mod.rs

With the changes made in #10948, we may no longer see refund receipts in the result.

nayduck: fix integration rpc tests

---

.github/PULL_REQUEST_TEMPLATE/feature_stabilization.md
.github/workflows/nightly_nayduck.yml
docs/practices/testing/README.md
nightly/README.md
scripts/nayduck.py

Nayduck testing infrastructure was moved from Pagoda to NearOne:
https://nayduck.near.org -> https://nayduck.nearone.org

Near one nayduck

---

chain/chain/src/tests/simple_chain.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
core/parameters/res/runtime_configs/66.yaml
core/parameters/res/runtime_configs/parameters.snap
core/parameters/src/config_store.rs
core/parameters/src/snapshots/near_parameters__config_store__tests__129.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__139.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__66.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__83.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_129.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_138.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_139.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_66.json.snap
core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_83.json.snap
core/parameters/src/snapshots/near_parameters__view__tests__runtime_config_view.snap
core/primitives-core/src/version.rs
core/primitives/src/snapshots/near_primitives__views__tests__runtime_config_view.snap
integration-tests/src/tests/client/features/fix_contract_loading_cost.rs
integration-tests/src/tests/client/features/increase_storage_compute_cost.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic.snap
integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic_nightly.snap
integration-tests/src/tests/runtime/test_evil_contracts.rs
runtime/near-vm-runner/src/tests/compile_errors.rs
runtime/near-vm-runner/src/tests/regression_tests.rs
runtime/near-vm-runner/src/tests/runtime_errors.rs

This PR decreases the function call base execution cost to 1TGas.
It is stacked on https://github.com/near/nearcore/pull/10941.

[protocol_change] Decrease function call base cost

---

pytest/tests/mocknet/helpers/neard_runner.py

JSON RPC errors should return 200 on error, since there's nothing wrong with the HTTP layer. This simplifies error handling in general, and makes it more straightforward to see that the error was at the JSON RPC level instead of HTTP, and to inspect the type of error returned in that case
This will be useful when we add support for fork-network in mocknet, because then we'll want to add a new RPC method that tells what type of mocknet we're running (legacy records.json vs fork-network), and we'll want to more granularly tell whether that RPC call fails because the neard runner doesn't recognize the method name, which will tell us that it's an older neard_runner.py and that we can assume it's using the legacy records

fix(mocknet): return HTTP 200 on error in neard_runner.py

---

chain/chain/src/test_utils/kv_runtime.rs
chain/client/src/stateless_validation/chunk_validator/mod.rs
chain/client/src/stateless_validation/chunk_validator/orphan_witness_handling.rs
chain/client/src/stateless_validation/chunk_validator/orphan_witness_pool.rs
chain/client/src/stateless_validation/shadow_validate.rs
chain/client/src/stateless_validation/state_witness_producer.rs
chain/client/src/stateless_validation/state_witness_tracker.rs
chain/client/src/test_utils/test_env.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/tests/mod.rs
chain/network/src/client.rs
chain/network/src/network_protocol/mod.rs
chain/network/src/types.rs
core/primitives/src/stateless_validation.rs
core/primitives/src/validator_signer.rs
integration-tests/src/tests/client/features/orphan_chunk_state_witness.rs
integration-tests/src/tests/client/features/stateless_validation.rs

This PR is a preparation for introducing state witness compression as part of #10780.
It addresses the following issues:
* State witness is implicitly deserialised when it is received via network and then serialised again in order to verify signature. While this is not a big issue now, we can't afford doing that once compression is introduced. In this PR `ChunkStateWitness` is renamed to `SignedChunkStateWitness` and now it holds raw bytes of `ChunkStateWitnessInner` (now renamed to  just `ChunkStateWitness`). 
* Duplicate validation in orphan witness handling and normal validation process. Currently we perform bunch of validations multiple times: first in `handle_orphan_state_witness` and then in `start_validating_chunk`, it would be nice to avoid that. This is addressed by introducing …

refactor: state witness struct

---

chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/store.rs
core/store/src/lib.rs
core/store/src/trie/shard_tries.rs

Add tracings inside `ChainUpdate::commit` and a number of related functions as part of an effort to investigate #10970

Tracing block postprocessing

---

core/store/src/trie/shard_tries.rs

There is a lock contention issue on `caches` in `ShardTries`. We always acquire the write lock for the `Rwlock` but that is only needed when there is a change in the number of shards, which happens extremely rarely. This lock contention partially leads to #10970. The fix here works by always checking whether the shard already exists and only acquire a write lock if the shard does not exist and the outer hash map needs to be modified.

Fix update cache

---

tools/congestion-model/src/evaluation/summary_table.rs

For quickly comparing many different parameters in the fine-tuning phase, knowing the median latency is not good enoungh.

congestion: show 90th tx delay percentile in summary

---

pytest/tools/mirror/mirror_utils.py

protocol version 66 causes these contract calls to fail now with prepaid gas exceeded errors. Bumping the gas to 10**14 like the other calls fixes this.

fix(mirror): bump the gas for create_account function calls in the test

---

tools/mirror/src/chain_tracker.rs

The test pytest/tools/mirror/offline_test.py often fails with many fewer transactions observed than wanted, and the logs reveal that many transactions are invalid because the access keys used do not exist in the target chain. This happens because some early transactions that should have added those keys never make it on chain. These transactions are sent successfully from the perspective of the ClientActor, but the logs show that they're dropped by the peer manager:
```
DEBUG handle{handler="PeerManagerMessageRequest" actor="PeerManagerActor" msg_type="NetworkRequests"}: network: Failed sending message: peer not connected to=ed25519:Fz7d1xkkt3XsvTPiwk4JRhMuPru4Ss7cLS8fdhshDRj3 num_connected_peers=1 msg=Routed(RoutedMessageV2 { msg: RoutedMessage { ... body: tx …
```

fix(mirror): wait 15 seconds before sending transactions

---

tools/congestion-model/src/evaluation/mod.rs
tools/congestion-model/src/main.rs

To report utilization in terms of burnt gas, it can be useful to disregard the first N rounds.

feat(congestion-model): simple warmup

---

tools/congestion-model/src/evaluation/mod.rs
tools/congestion-model/src/evaluation/summary_table.rs
tools/congestion-model/src/main.rs

This is better for comparing different strategies under different configurations.
It is easier to interpret how much gas has been burnt per chunk, rather than in total.

congestion: report gas per chunk in the summary

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/model/mod.rs

If we run with infinite transaction pools, some workloads report really long transaction delays. This reflects reality in some sense. But is not really useful for comparison.
The CLI flag `tx_pool_size` allows to trim the pool, possibly even empty it completely. Then, the reported delays are shorter because started transactions are fresher.

congestion: transaction pool trimming

---

core/store/src/trie/mod.rs
core/store/src/trie/trie_recording.rs
core/store/src/trie/update.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/metrics.rs

In https://github.com/near/nearcore/issues/10890 we considered adding extra 2000 bytes to the storage proof size for every removal operation on the trie (Idea 1). This PR implements the logic of recording the number of removals and calculating the adjusted storage proof size. It's not used in the soft witness size limit for now, as we have to evaluate how viable of a solution it is. There are concerns that charging 2000 bytes extra would cause the throughput to drop.
To evaluate the impact of adjusting the size calculation like this, the PR adds three new metrics.
* `near_receipt_recorded_size` - a histogram of how much storage proof is recorded when processing a receipt. Apart from https://github.com/near/nearcore/issues/10890, it'll help us estimate what the hard per-receipt storage …

Add metric for recorded storage proof size, also calculate adjusted size based on number of trie removals

---

pytest/tests/contracts/deploy_call_smart_contract.py

This is resolving one of the items from https://github.com/near/nearcore/issues/11031
It is quite bizarre that this test is failing in the first place, as the change in the gas costs should be strictly beneficial to the users.
Here is an example failure: https://nayduck.nearone.org/#/test/12357
@Ekleog-NEAR , any ideas?

Fix `deploy_call_smart_contract`

---

chain/network/src/network_protocol/mod.rs
chain/network/src/peer_manager/connection/mod.rs
chain/network/src/peer_manager/network_state/mod.rs

Two main changes
- ChunkStateWitness and ChunkEndorsement are not sent multiple times over network.
- Change preference of ChunkStateWitness and ChunkEndorsement to send over Tier 1 connection
ChunkStateWitness are heavy and we do not want to send them over the network multiple times.
ChunkEndorsement do not need to be sent multiple times either as they are mainly over tier 1 network.
Minor cleanup and renaming functions.

[network] Changes to StatelessValidation related network messages

---

chain/network/src/peer_manager/network_state/mod.rs

The current default behavior was to send Tier 1 network messages over both Tier 1 and Tier 2.
This PR changes that behavior to not send message over Tier 2 in case it was successfully sent over Tier 1

[network] Do not resend successful Tier 1 network messages over Tier 2 network

---

chain/client/src/test_utils/test_env.rs
integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
integration-tests/src/tests/client/features/fix_contract_loading_cost.rs
integration-tests/src/tests/client/features/flat_storage.rs
integration-tests/src/tests/client/features/increase_deployment_cost.rs
integration-tests/src/tests/client/features/increase_storage_compute_cost.rs
integration-tests/src/tests/client/features/limit_contract_functions_number.rs
integration-tests/src/tests/client/features/lower_storage_key_limit.rs
integration-tests/src/tests/client/features/nearvm.rs

Renames `pub fn upgrade_protocol(&mut self, protocol_version: ProtocolVersion)` to `pub fn upgrade_protocol_to_latest_version(&mut self)`.  The function is unable to upgrade to a specific version but instead always upgrades to the latest version.
Also see https://github.com/near/nearcore/issues/8590.

bug: rename function to reflect actual ability

---

core/store/src/db.rs
core/store/src/db/mixeddb.rs
core/store/src/db/splitdb.rs

MixedDB allows to have dedicated read-only db, and specify the order of data retrieval.
With `ReadOrder::ReadDBFirst` you can overwrite some information in DB, without actually modifying it.
With `ReadOrder::WriteDBFirst` you can record results of any operations only in a separate DB.
This way you can conduct several experiments on data, without having to create checkpoints or restoring data.
And you can compare data from different experiments faster, as your write DB will be smaller.
SplitDB can be considered a `MixedDB { read_db: cold_db, write_db: hot_db, read_order: ReadOrder::WriteDBFirst }`
But it also has several assertions about types of columns we can retrieve from `read_db`,
And it is suitable for production.
MixedDB is designed to be used with neard tools, and is not planned …

feat(db): Adding MixedDB

---

tools/congestion-model/src/main.rs
tools/congestion-model/src/strategy/mod.rs
tools/congestion-model/src/strategy/smooth_traffic_light.rs

This is already reasonably fine-tuned, with decent results across all the workloads. But the parameter values are not finalized, yet.
```
Running `congestion-model --strategy SmoothTrafficLight --rounds 1000 --warmup 100 --shards 8 --tx-pool-size 200`
WORKLOAD                 STRATEGY                       BURNT GAS PER CHUNK    TRANSACTIONS FINISHED MEDIAN TX DELAY    90p TX DELAY   MAX QUEUE LEN  MAX QUEUE SIZE  MAX QUEUE PGAS
Balanced                 Smooth Traffic Light                     1019 TGas                    77200               9              11             151        108.9 KB              31
Increasing Size          Smooth Traffic Light                     1001 TGas                    75550               5               6             448        192.0 MB              25 …
```

congestion: smooth traffic light strategy

---

tools/congestion-model/src/strategy/nep.rs

The filter is per outgoing shard, we should keep
working on new transactions for other shards even
after hitting the limit for one shard.

congestion: fix nep strategy filtering

---

Cargo.lock
Cargo.toml
chain/client/src/metrics.rs
chain/client/src/stateless_validation/chunk_validator/mod.rs
chain/client/src/stateless_validation/shadow_validate.rs
chain/client/src/stateless_validation/state_witness_producer.rs
chain/client/src/test_utils/test_env.rs
chain/epoch-manager/src/tests/mod.rs
core/primitives/Cargo.toml
core/primitives/src/stateless_validation.rs
integration-tests/src/tests/client/features/orphan_chunk_state_witness.rs
integration-tests/src/tests/client/features/stateless_validation.rs

This PR adds state witness compression as well as metrics around it. See #10780 for the big picture analysis.
We explicitly limit the size of the decompressed state witness to 64MB to handle [Zip bomb](https://en.wikipedia.org/wiki/Zip_bomb) attack. This is implemented by using `BufMut` and `Limit` along with `zstd::stream::copy_decode`, so it fails when attempting to write data beyond the limit.
Compression reduces state witness size particularly well for large state witnesses (containing many `ContractCode` values), which makes it worthwhile. For cases when compression doesn't yield much improvements the latency overhead is not significant.
In practice shadow validation was used to verify the statements above with the current mainnet traffic:
* overall traffic reduction …

feat: compress state witness

---

pytest/tests/sanity/rpc_max_gas_burnt.py

Another instance of test broken by the gas cost increase.
This completes https://github.com/near/nearcore/issues/11031

Fix rpc_max_gas_burnt

---

core/o11y/src/opentelemetry.rs

With the default-default values we're having a hard time keeping up with
publishing traces even on some of the most strict filters due to the
fact that our spans are pretty bursty.
This leads to a large number of
OpenTelemetry trace error occurred.
cannot send span to the batch span processor because the channel is
full
being output to the standard output. This attempts to mitigate it.
---
Stacked on top of #11029

o11y: better default values for otel batch processor 

---

runtime/runtime/src/lib.rs
runtime/runtime/src/metrics.rs

In #11000 I added some metrics for the size of receipt/chunk storage proofs, along with upper bound estimation of those sizes. The buckets chosen in the PR weren't that good, as I didn't know what sort of values to expect.
I have spent some time looking at the data and I'd like to adjust the buckets to better fit the data distribution.
* Most receipts generate < 100KB of storage proof, so for receipt-level sizes I'd like to use  a few small buckets and then some more big buckets to catch the big outliers.
* Chunk level proofs are usually within 2-6MB, so I changed the metric to use buckets between 0 and 15MB with 500KB increases
* The ratio for receipts was sometimes extremely high. I think it was due to small receipts (a receipt which writes little, but removes two nodes could easily …

Better buckets for storage proof size metrics

---

runtime/near-vm-runner/src/near_vm_runner/memory.rs
runtime/near-vm-runner/src/near_vm_runner/mod.rs
runtime/near-vm-runner/src/near_vm_runner/runner.rs

This is basically just moving code around, to be able to reduce visibility into NearVmMemory’s internals and thus derisk modifying them.
Part of #11033

split NearVmMemory into a separate file to limit visibility

---

core/store/src/trie/mod.rs

This is a very initial step on optimizing parts of the storage implementation that stick out in the profiles.
Overall the `RefcountDeltaMap` operations show up as taking 400ms of wall clock time when applying 250 blocks of a single shard. With this change, the number decreases to 250ms.
One of the reasons for using BTreeMap here is the observation that inside `into_changes` we sort the changes eventually. So we might as well build up a sorted representation in the first place.
https://share.firefox.dev/3U3nF3K
---
As a side note, we seem to be storing a huge number of maps from `CryptoHash` to some value. This hash when stored in a hashmap then gets hashed again, which costs us quite some time. Once I create a `CryptoHashMap` data structure, I will re-evaluate whether it may make sense to …

trie: optimize TrieRefcountDeltaMap

---

core/store/src/test_utils.rs
core/store/src/trie/insert_delete.rs
core/store/src/trie/mem/loading.rs
core/store/src/trie/mem/updating.rs
core/store/src/trie/mod.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_recording.rs
core/store/src/trie/trie_tests.rs
integration-tests/src/runtime_utils.rs

Yet another cornercase fix: if deleted key doesn't exist, read only nodes required to prove its non-existence, thus only nodes along the path.
The chaos it caused is described on #11065 and discussed on [Zulip](https://near.zulipchat.com/#narrow/stream/308695-nearone.2Fprivate/topic/Forknet.20.2B.20Stateless.20Validation/near/432971999).
This is not a protocol change, because currently nodes read on `Trie::update` don't impact costs, so we can modify current disk trie logic to follow the principle that only necessary nodes should be read. 
Unfortunately disk tries logic, on descending, always subtracts child' memory usage from parent' memory usage and requires "backwards iteration" along the path to recompute potentially changed memory usages. I want to minimise changes, so I just …

fix: read only nodes along the path on non-existent key deletion

---

chain/client/src/stateless_validation/chunk_validator/orphan_witness_pool.rs

It is safe to also drop state witness with `height_created` equal to the height of the last final block.
This is mostly to stay consistent with the check introduced in #11081.

fix(minor): more aggressive state witness orphan pool final block height check

---

chain/chain/src/tests/simple_chain.rs
chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
core/primitives-core/src/version.rs

1.39.0 release has protocol version 66 https://github.com/near/nearcore/blob/1.39.0/core/primitives-core/src/version.rs#L202
This means that 1.40 should have protocol version 67. As no new protocol features were stabilised since the last release, making an empty protocol upgrade

Bump protocol version for 1.40.0

---

pytest/tests/mocknet/README.md
pytest/tests/mocknet/local_test_node.py

This adds some instructions on how to set up a mocknet locally, plus a small fix in flag prompting in local_test_node.py.

feat(mocknet): add info on local mocknet tests to the README

---

docs/practices/workflows/io_trace.md
pytest/tests/sanity/recompress_storage.py
runtime/runtime-params-estimator/README.md

It was broken after #10961 because format of command changed. Fixing the format.
Note that it is not a complete solution because of #8741, but the issue may occur only if charged costs are complicated, which is unlikely the case for the test.
Nayduck https://nayduck.nearone.org/#/run/50

fix: recompress_storage.py

---

chain/client/src/client_actor.rs
chain/client/src/gc_actor.rs
chain/jsonrpc/jsonrpc-tests/src/lib.rs
chain/jsonrpc/src/lib.rs
nearcore/src/lib.rs
pytest/lib/cluster.py
pytest/tests/sanity/garbage_collection_archival.py
pytest/tests/sanity/garbage_collection_intense.py

Re-enable store validator tests that were disabled in #11022. It works by first sending a signal to GC actor to stop garbage collection, then run the store validator, and send a signal to re-enable gc afterwards.
Nayduck run https://nayduck.nearone.org/#/run/58

feat(pytest): reenable store validator

---

.github/workflows/master_fuzzer_binaries.yml
.github/workflows/ondemand_fuzzer_binaries.yml

Changing target bucket along with required auth.
Test run: https://github.com/near/nearcore/actions/runs/8783766575

New bucket for fuzz targets

---

core/primitives-core/src/version.rs
integration-tests/src/tests/client/resharding.rs

Originally we had disabled V3 layout (6 shards) for stateless_net as we do not support resharding with stateless net.
This more recently has been causing some problems with forknet + stateless validation where all the traffic from mainnet shards 2 and 3 is hitting shard 2 on forknet.
Since we have the capability to redeploy and restart forknet nodes at will, we can remove this shard layout constraint.

[resharding] Shard layout V3 for statelessnet_protocol

---

chain/client/src/stateless_validation/state_witness_actions.rs
chain/client/src/stateless_validation/state_witness_actor.rs
chain/client/src/stateless_validation/state_witness_producer.rs
chain/network/src/peer/testonly.rs
chain/network/src/peer_manager/testonly.rs
chain/network/src/types.rs
core/primitives-core/src/version.rs
core/primitives/src/stateless_validation.rs
core/primitives/src/validator_signer.rs

This PR implements the following
- Compressing state witness and creating Reed Solomon encoding parts out of it.
- Sending the parts over the network to the appropriate part owners.
- Forwarding parts received by owners to other chunk validators.
Future PRs would handle the following
- Validation logic for the parts
- Part management and reconstruction of state witness from parts.
- Add tests after end to end implementation

[stateless_validation] Implement distribution of state witness parts

---

chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
core/store/src/flat/manager.rs
core/store/src/flat/storage.rs
nightly/pytest-sanity.txt
pytest/lib/cluster.py
pytest/tests/sanity/single_shard_tracking.py

@Longarithm fixed #11135 by forcing flat storage head to move after state sync. The pytest `single_shard_tracking` exposes this issue.
Instructions to run the test
```
cargo build -p neard --features test_features,statelessnet_protocol
python3 pytest/tests/sanity/single_shard_tracking.py
```

Fix #11135

---

neard/Cargo.toml
tools/epoch-sync/Cargo.toml
tools/epoch-sync/src/cli.rs
tools/epoch-sync/src/lib.rs

The epoch sync was getting enabled when using wide build commands that included the epoch sync tool. 
I'm moving the conditional enablement from Cargo.toml to the rust files. 
Additional information: https://near.zulipchat.com/#narrow/stream/300659-Rust-.F0.9F.A6.80/topic/PSA.3A.20don't.20use.20.60cargo.20build.20--bin.20neard.60

fix(epoch_sync) - fix unintential epoch sync feature inclusion

---

core/store/src/trie/mod.rs
core/store/src/trie/receipts_column_helper.rs
runtime/runtime/src/lib.rs

Today, the delayed receipts queue is modified by directly accessing and modifying the data structure's internal indices. This increases complexity inside the `apply()` function, which is over 600 lines large and contains a lot of complicated logic.
This refactor abstracts the queue in a separate struct which does the index handling. It also adds the ability to read-only iterate delayed receipts. For now, this is only used for testing the new code more easily. But the upcoming congestion control feature will need it in production code, too.
Postponed receipts and yielded promises could potential benefit from similar abstractions. But their internal wokrings are different enough that it should be done in a seprate PR, if at all.

refactor: delayed receipts queue helper

---

core/store/src/trie/receipts_column_helper.rs

`cfg!(debug_assertions)` still requires the code inside to be valid, so let's put in a dummy function for the release build.
fixes #11163 introduced in #11159.

fix: release build error

---

chain/jsonrpc-primitives/src/types/light_client.rs
chain/jsonrpc/src/api/light_client.rs
chain/jsonrpc/src/lib.rs

Added json rpc api `light_client_block_proof` to get the block proof.
Inputs:
```
pub struct RpcLightClientBlockProofRequest {
pub block_hash: near_primitives::hash::CryptoHash,
pub light_client_head: near_primitives::hash::CryptoHash,
}
```
outputs:
```
pub struct RpcLightClientBlockProofResponse {
pub block_header_lite: near_primitives::views::LightClientBlockLiteView,
pub block_proof: near_primitives::merkle::MerklePath,
}
```
The current `light_client_proof` api returns two kinds of proofs:
1. Outcome proof: this proof is needed to prove that the outcome was included in a block.
2. Block proof: to prove the block is part of the chain.
Currently, we can use only the archival node to get proof of historical outcomes because the regular nodes store only blocks for the last five epochs. …

jsonrpc: add api to get block proof

---

pytest/tests/mocknet/helpers/neard_runner.py

We currently copy the `data` folder of a node to a separate folder. 
in this PR we are introducing backups using RocksDB snapshots.
This will take advantage of RocksDB property that `.sst` files are immutable and we are just linking them instead of making a copy.
This will allow us to take subsequent backups by using less space. The network downtime is also reduced to ~10 seconds.
`neard_runner.py` logs when restoring old backup took 5 minutes
```
[2024-04-25 00:01:57,606] INFO: do_reset TestState.STOPPED
127.0.0.1 - - [25/Apr/2024 00:01:57] "POST / HTTP/1.1" 200 -
[2024-04-25 00:01:58,431] INFO: removing the old directory
[2024-04-25 00:02:02,545] INFO: restoring data dir from backup at /home/ubuntu/.near/neard-runner/backups/start
[2024-04-25 00:07:07,751] INFO: data dir restoration …
```

feat(forknet): make backups using RockDB snapshots

---

pytest/tests/mocknet/helpers/neard_runner.py
pytest/tests/mocknet/local_test_node.py
pytest/tests/mocknet/remote_node.py

The old version of forknet/mocknet has one disk for each node, where there are the starting genesis and records files in `~/.near/setup/`, and the traffic generator includes those plus a full NEAR home dir in `~/.near/`. With the new faster `fork-network` based mocknet setup, we need a full home dir for both the source chain and the target chain setup directory. So it's not economical to include the target setup directory in both images (validator node and traffic generator). Instead we'll want to have two images, and mount two disks on the traffic generator. This PR implements the logic necessary to have `neard_runner.py` keep the old mountpoints when the legacy records.json method is being used, and to assume that with the new version, the source home directory will be mounted at …

feat(forknet): move the traffic generator mount points for the new image type

---

pytest/tests/mocknet/cmd_utils.py
pytest/tests/mocknet/local_test_node.py
pytest/tests/mocknet/mirror.py
pytest/tests/mocknet/node_handle.py
pytest/tests/mocknet/remote_node.py

This PR introduces `run-cmd` subcommand that allow the user to issue commands to all the mocknet hosts.
It can target `--all` the host, only `--nodes` or only `--traffic` hosts.
It can also `--filter` the selected nodes with a regex.
It prints out the output of the command on every host. ` > /dev/null` if you don't want it.

feat(mocknet): add subcommand to mirror.py to run commands on all mocknet hosts

---

core/primitives/src/receipt.rs
core/store/src/trie/receipts_column_helper.rs
runtime/runtime/src/lib.rs

In #11159 we added a helper for the delayed receipts queue. To add more queues as simply as possible, we need to generalize the implementation a bit more.
First: Move code that is independent of the queue content to a new trait `TrieQueue`. Trie keys and access to fields is done through trait methods that each specific queue impl needs to define.
Second: Introduce `struct TrieQueueIndices` for a general way of storing queue indices. We keep the type `DelayedReceiptIndices` for backwards compatibility of dependencies to the primitives crate but provide conversion from and to it.
Third: Change the internals of `ReceiptIterator` to make use of these generalizations. We can avoid boxing a weird closure this way and make the addition of new queue implementations much easier.

refactor: generalize state trie queue

---

neard/build.rs
neard/src/main.rs

Print all of the build time features enabled using the `--features` flag in the output of `neard --version`
Examples:
```
$ cargo run -p neard -- --version
...
neard (release trunk) (build 1.36.1-489-gdf22f90b9) (rustc 1.77.0) (protocol 67) (db 39)
features: [default, json_rpc, rosetta_rpc]
```
```
$ cargo run -p neard --features statelessnet_protocol,new_epoch_sync -- --version
...
neard (release trunk) (build 1.36.1-489-gdf22f90b9) (rustc 1.77.0) (protocol 85) (db 39)
features: [default, json_rpc, near_epoch_sync_tool, new_epoch_sync, rosetta_rpc, statelessnet_protocol]
```
```
$ cargo run -p neard --features nightly -- --version
...
neard (release trunk) (build 1.36.1-489-gdf22f90b9) (rustc 1.77.0) (protocol 140) (db 39)
features: [default, json_rpc, nightly, nightly_protocol, …
```

feat(neard): print all enabled features in `neard --version`

---

Cargo.lock
Cargo.toml
chain/chunks/src/lib.rs
chain/chunks/src/test/basic.rs
chain/chunks/src/test_loop.rs
chain/chunks/src/test_utils.rs
chain/client/src/client.rs
chain/client/src/stateless_validation/state_witness_actions.rs
chain/client/src/test_utils/client.rs
chain/network/Cargo.toml
chain/network/src/network_protocol/testonly.rs
core/primitives/src/block.rs
core/primitives/src/reed_solomon.rs
core/primitives/src/sharding.rs
core/primitives/src/stateless_validation.rs
core/store/Cargo.toml
core/store/benches/finalize_bench.rs
deny.toml
integration-tests/Cargo.toml
integration-tests/src/tests/client/challenges.rs

Based on the [conversation on Zulip](https://near.zulipchat.com/#narrow/stream/300659-Rust-.F0.9F.A6.80/topic/RefCell.20usage/near/435417054), seems like the memory leak bug in reed-solomon-erasure encoding crate has been fixed with the latest version 6.0.0
This PR removes the ReedSolomonWrapper which was a workaround and upgrades the crate to version 6.0.0

[reed_solomon] Remove ReedSolomonWrapper

---

chain/chain/src/tests/garbage_collection.rs

Currently failing on nayduck, was missed as part #10694.
Verified the fix with `cargo test -pnear-chain --features test_features,expensive_tests -- --exact --nocapture tests::garbage_collection::test_gc_pine`.

fix: make test_gc_pine green again

---

core/primitives/src/receipt.rs
core/primitives/src/trie_key.rs
core/primitives/src/types.rs
core/store/src/lib.rs
core/store/src/trie/receipts_column_helper.rs
core/store/src/trie/resharding.rs

Add an outgoing receipt buffer for each other shard to the state trie.
This is part of congestion control (NEP-539).
This PR only adds the new buffers and unit tests for it, without actually using them. Future PRs will use it.

feat: add outgoing receipt buffers

---

nightly/pytest-sanity.txt

commented out a test the breaks because of missing congestion control and resharding integration

fix(congestion_control) - disable broken resharding nayduck test 

---

core/primitives/src/congestion_info.rs

Define all congestion evaluations as defined in the current NEP-539 proposal.
This is still not actually using the values in the runtime but the contained tests should be sufficient to show that the values are calculated as defined in the NEP.

feat: congestion info calculations

---

pytest/requirements.txt

This should make installing all dependencies trivial with `pip install -r pytest/requirements.txt`

deps: Add Locust Python deps

---

chain/chain/src/chain_update.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/client/src/stateless_validation/chunk_validator/mod.rs
core/primitives/src/types.rs
core/store/src/trie/mem/loading.rs
core/store/src/trie/trie_recording.rs
core/store/src/trie/trie_tests.rs
genesis-tools/genesis-populate/src/lib.rs
integration-tests/src/tests/client/resharding.rs
nightly/pytest-sanity.txt
tools/state-viewer/src/state_dump.rs

Removing a few TODOs and updating some others.
* Renamed all TODOs related to resharding to "integration with resharding" so that it's easier to filter those out. 
* Resolved TODO in chunk validation when getting genesis transition params - reading epoch id directly from header
* Resolved TODOs in ChunkExtra::new - uncommented the asserts. 
* Resolved TODO is validate_prepared_transactions - I checked that the method that calls this function reads multiple blocks including this one. It's not convenient to pass the block as an argument but it should be in the db cache so fetching it again should be really cheap.

 cleanup(congestion_control) - resolved a few minor TODOs 

---

Cargo.lock

For some reason, rustix was recompiled on every code change on my Mac M1 ([Zulip](https://near.zulipchat.com/#narrow/stream/300659-Rust-.F0.9F.A6.80/topic/.E2.9C.94.20can.20we.20avoid.20rustix.20recompilation.3F/near/436855608)). Removing dependencies on old rustix versions by running cargo update seem to solve the issue.

chore: remove deps on old rustix versions

---

docs/architecture/gas/README.md
docs/architecture/how/receipt-congestion.md
docs/architecture/how/tx_routing.md

Fix some typos in `docs`

---

chain/chain/src/chain.rs
chain/chain/src/chain_update.rs
chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/tests.rs
chain/chain/src/test_utils/kv_runtime.rs
core/primitives-core/src/version.rs
core/primitives/src/sharding.rs
core/primitives/src/types.rs
core/store/src/trie/mem/loading.rs
core/store/src/trie/trie_recording.rs
core/store/src/trie/trie_tests.rs
genesis-tools/genesis-populate/src/lib.rs
integration-tests/src/tests/client/process_blocks.rs
runtime/runtime/src/congestion_control.rs
runtime/runtime/src/lib.rs

Add `fn ProtocolVersion::enabled` to avoid making direct comparisons all over the code.
`checked_feature!` used to be the right choice.
But without cfg, a complex macro is overkill.
This PR only uses the new fn for `ProtocolFeature::CongestionControl` checks. We can consider replacing the checks for other features, too.

refactor(congestion): Clearer protocol version checks

---

.github/workflows/neard_custom_release.yml

We added a [new GitHub action](https://github.com/near/nearcore/actions/workflows/neard_custom_release.yml) to pass a release type param to the binary_release.sh script, so that we can compile neard with different features (eg. with stateless validation). But missed passing the parameter to the script. This change passes the param value to the script.

fix: Pass release type to binary_release.sh in custom-release GitHub action

---

pytest/tests/mocknet/README.md

[LycheeLints check is currently failing](https://github.com/near/nearcore/actions/runs/8974625442/job/24647400166?pr=11178#logs) because it seems GitHub action is unable to locate the "private" repository. I am updating README file while we fix this issue to unblock merges.

fix: Temporarily update the mirror/README file to fix Lychee Lints check

---

pytest/tests/mocknet/mirror.py

This will automate enabling in-memory tries and changing tcp sysctl values, which is something we want to do manually anyway when starting a stateless network

feat(forknet): add a --stateless-setup flag to new-test

---

chain/chain/src/runtime/tests.rs
chain/epoch-manager/src/lib.rs
chain/epoch-manager/src/proposals.rs
chain/epoch-manager/src/tests/mod.rs
chain/epoch-manager/src/validator_selection.rs

Remove fishermen-related code from epoch info generation and tests, because it is unlikely to be used but is distracting.
Also fix some typos and names.
Fields will be marked as deprecated in future PRs, I'd like to continue removing code later.

refactor: remove fisherman related code from epoch

---

chain/chain/src/runtime/mod.rs
chain/network/src/tcp.rs

Previous limit was 13MB, let's reduce it to 4MB and see what happens.

stateless forknet: limit size of new transactions to 4MB

---

chain/client/src/client.rs
chain/client/src/client_actions.rs
chain/jsonrpc/src/lib.rs
nightly/pytest-adversarial.txt
pytest/lib/cluster.py
pytest/lib/utils.py
pytest/tests/adversarial/adv_chunk_missing.py
pytest/tests/adversarial/chunk_missing.py
pytest/tests/adversarial/fork_sync.py

* Added a new adversarial control that disables/enables chunk production.
* Added a new rpc endpoint to control the above. 
* Added an example python test using the controls. 
I need to test the scenario where a range of blocks is missing chunks at the end of epoch. This is needed to test the state sync and congestion control integration. I'll do that in a follow up PR.

feat(test_infra) - added adversarial controls for chunk production

---

pytest/tests/mocknet/helpers/neard_runner.py
tools/fork-network/src/cli.rs

We want to set a particular protocol version for forknet/mocknet when running this command. So add a --protcool-version flag that will set it, keeping the old behavior if it's not present

fix(fork-network): set protocol version in fork-network set-validators

---

chain/chain/src/state_snapshot_actor.rs
chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
chain/client/src/sync_jobs_actor.rs
chain/telemetry/src/lib.rs
core/async/src/actix_wrapper.rs
core/async/src/messaging.rs

This PR introduces a generic trait `Actor` to handle actix::Actor started function calls.
This PR introduces a new type of handler, `HandlerWithContext` that takes in a context object as input to the handle function.
This is to mimic the actix::Context<Self> that's usually passed to the handler. We require the `DelayedActionRunner` capability of the context and hence, that's the only thing we are exposing for now.
Note that the old `Handler` still stays in place and we have a default implementation for the extension `HandlerWithContext` trait.
 
Follow up of PR https://github.com/near/nearcore/pull/11214

[actor] Introduce Actor and HandlerWithContext trait

---

chain/client/src/metrics.rs
chain/client/src/stateless_validation/partial_witness/partial_witness_actor.rs
chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs

Added 4 set of metrics
- PARTIAL_WITNESS_ENCODE_TIME: Time taken to encode state witness to parts. This should ideally be super tiny
- PARTIAL_WITNESS_DECODE_TIME: Time taken from receiving the first part of the partial witness to when the state witness is decoded. Note that if we are one of the validators, this time would be longer as we auto-add our own part to the cache.
- PARTIAL_WITNESS_TOTAL_TIME: Time taken from receiving the first part to the last part
- PARTIAL_WITNESS_PARTS_RECEIVED_RATIO: Ratio of parts received to total parts. Note that we capture this during cache entry eviction so we should have enough time to receive all parts (even if we have decoded the state witness)
Biggest gotcha I can think of is when the chunk producer is the validation, then the first network delay …

[stateless_validation] Adding some much useful metrics to partial witness

---

core/store/src/trie/receipts_column_helper.rs
runtime/runtime/src/lib.rs

The previous implementation wrote the outgoing buffer indices to the trie in `pop_n` even if the buffer was still empty. To prevent this as showing up as a trie change, I added logic that checks specifically for empty values.
As it turns out, it is much easier to prevent writing indices back in the first place, which is also how it's done for the existing delayed receipts queue to avoid the same issue.

congestion: only init outgoing buffers when used

---

pytest/tests/mocknet/local_test_node.py
pytest/tests/mocknet/mirror.py
pytest/tests/mocknet/node_config.py
pytest/tests/mocknet/node_handle.py
pytest/tests/mocknet/remote_node.py

This adds some fields (`can_validate`, `want_state_dump`, `want_neard_runner`) to `NodeHandle`. If `want_neard_runner` is false, then we ignore it when running all commands. If `want_state_dump` is true, we configure its state sync dump config, along with configuring it and the rest of the nodes with a correct `state_sync.sync` config. If `can_validate` is false, we ignore it when building the list of validator nodes.
The nodes will be configured in `node_config.py`, where for now we match on the names of instances

fix(forknet): ignore tracing server and set up state dumper node properly

---

chain/chain/src/store_validator/validate.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/sync/block.rs
nightly/pytest-sanity.txt
pytest/tests/sanity/state_sync_missing_chunks.py

* Fixed a number of bugs in the congestion control and state sync implementation.
* Each needed block needs a separate timer for requesting it, otherwise some never get requested. 
* More blocks need to be allowed to be stored for state sync. 
* Wait until all sync blocks are ready before starting state sync. 
* Check if block exists depending on how we store it. 
* Added a nayduck test that tests state sync with missing chunks at the end of the epoch.

fix(congestion control) - fix integration with state sync, add tests

---

pytest/tests/mocknet/mirror.py

State dumper node need to track all shards.

fix(forknet): track all shards on dumper nodes

---

chain/client/src/test_utils/test_env.rs
core/primitives/src/test_utils.rs
integration-tests/src/tests/client/features.rs
integration-tests/src/tests/client/features/congestion_control.rs

Add 2 integration tests to check the protocol upgrade works.
The first test is without any traffic at all. This already works.
The second test is with congestion at the time of the upgrade. We haven't handled congestion initialization, yet, therefore the last check is disabled with a TODO comment.

test: congestion control protocol upgrade

---

.github/workflows/neard_custom_release.yml
scripts/binary_release.sh

The current custom release logic will upload to a url that changes every time based on commit. 
This PR introduces the option to have the same url for subsequent builds of the same branch: `/${os}/${BRANCH}/${target}/neard`

fix(custom-build) Add the build target to the url

---

core/primitives/src/types.rs
pytest/tests/sanity/resharding_rpc_tx.py

There were two new issues in this test, fixing both. 
- congestion control was not properly initialized for some feature configuration
- the response had more values in the receipt outcomes

fix(nayduck) - fixing the resharding_rpc_tx nayduck test

---

pytest/tests/mocknet/mirror.py

Node needs to take snapshots every epoch in order to generate state parts.

fix(forknet) Set snapshot on every epoch for dumper nodes

---

pytest/tests/mocknet/helpers/neard_runner.py

Set the file size to 100Mb, set max log size to 100GB.
All logs will be written to logs.txt.
Rotated files will be renamed with the time of rotation. Rotation logic is: copy, then truncate the current file.
If logs go over the 100GB limit, oldest log file (lexicographically) will be removed until the logs size is under the limit.
The log rotation trigger will be called in the main loop of `neard_runner.py`.
Example output of `ls neard-logs`:
```
total 342M
drwxrwxr-x 2 ubuntu ubuntu 4.0K May 13 10:23 .
drwxr-xr-x 8 ubuntu ubuntu 4.0K May 13 10:13 ..
-rw-rw-r-- 1 ubuntu ubuntu   83 May 13 10:23 .logrotate_status
-rw-rw-r-- 1 ubuntu ubuntu  664 May 13 10:13 .neard_logrotate_policy
-rw-rw-r-- 1 ubuntu ubuntu 6.2M May 10 11:09 initlog.txt
-rw-rw-r-- 1 ubuntu ubuntu  28M May 13 10:23 logs.txt …
```

fix(forknet) Set log rotation policy

---

.github/workflows/book.yml
.github/workflows/ci.yml

Currently there are tons of warnings on Actions:
As some actions are relying on Node16 which is going to EOL(https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), and some workflows are being deprecated.
For example https://github.com/actions/download-artifact
> actions/download-artifact@v3 is scheduled for deprecation on November 30, 2024. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) Similarly, v1/v2 are scheduled for deprecation on June 30, 2024.
https://github.com/actions/upload-artifact
> actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) Similarly, v1/v2 …

fix(ci): bump actions workflow versions

---

Cargo.lock
tools/database/Cargo.toml
tools/database/src/analyze_contract_sizes.rs
tools/database/src/commands.rs
tools/database/src/lib.rs

Add a command which looks at the current state and finds accounts with the biggest contract sizes.
Example usage:
```
$ ./neard database analyze-contract-sizes --topn 10
...
Analyzed 33165 accounts
Accounts per shard:
s0.v3: 6443
s1.v3: 1
s2.v3: 7916
s3.v3: 3643
s4.v3: 11208
s5.v3: 3954
Top 10 accounts by contract size:
3.9 MB: nearpay-portals.near
3.8 MB: moodev.near
2.8 MB: v2_1_0.perp.spin-fi.near
2.8 MB: v2_0_2.perp.spin-fi.near
2.8 MB: v2.perp.spin-fi.near
2.7 MB: switchboard-v2.near
2.6 MB: nft.contented.near
2.5 MB: spot.spin-fi.near
2.5 MB: nftstaking.jumpfinance.near
2.5 MB: exchange.slowisfast.near
```

Add database analyze-contract-sizes

---

chain/chain/src/chain_update.rs
chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/tests.rs
chain/chain/src/types.rs
core/primitives/src/block.rs
core/primitives/src/congestion_info.rs
core/store/src/trie/resharding.rs
integration-tests/src/tests/client/features/congestion_control.rs
integration-tests/src/tests/client/features/stateless_validation.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/user/runtime_user.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime/src/congestion_control.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/metrics.rs
runtime/runtime/tests/runtime_group_tools/mod.rs

When there are multiple missing chunks in a row in a shard we want to consider that shard as congested. That is in order to prevent outgoing receipts to that shard accumulating and then blowing up the state witness size. 
I decided to not embed the information about missing chunks in the congestion info but rather I added a new struct called ExtendedCongestionInfo. The Block now constructs congestion info, extends it with the information about missing chunks and provides this new struct to the runtime. 
Since from now the congestion level cannot be calculated without the missing chunks information I added `missing_chunks_count` argument to all methods that rely on the congestion level. That is to make sure the users of those structs do not forget about the missing chunks - compiler will …

 feat(congestion_control) - handling missing chunks 

---

chain/client/src/client.rs

Currently we run shadow validation for every new block, even if we're only syncing up to reach the current tip of the chain. This causes sync to be extremely slow, as every synced block is applied. Because of that it's often faster to setup a new node from scratch rather than wait for a node to sync.
Let's not run shadow validation when syncing, it'll make it possible to catch up with the rest of the network in a reasonable amount of time.

Don't run shadow chunk validation when syncing blocks

---

core/primitives/src/errors.rs
core/store/src/trie/receipts_column_helper.rs
runtime/runtime/src/balance_checker.rs

Buffered receipts need to be accounted for in the balance checker.
I decided to treat them similarly to delayed receipts, counting the balance for receipts are added and removed to the queue, not counting what is actually in the queue. This avoids reading additional buffered receipts per chunk.

congestion: balance checker changes

---

chain/client/src/metrics.rs
chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs

`CacheEntry` tracks its own size in `total_parts_size`, that is pretty straightforward since we can only increment it as we add more parts. The total size across all cached entries in `PartialEncodedStateWitnessTracker` is calculated by simply iterating across all entries. We can afford that performance-wise since LRU cache size is currently limited to 200 entries and we plan to reduce that before the mainnet release.

feat: add metric for total size of cached partial state witnesses

---

chain/chain/src/flat_storage_creator.rs
chain/chain/src/store_validator/validate.rs
chain/chain/src/tests/garbage_collection.rs
core/store/src/lib.rs
core/store/src/test_utils.rs
core/store/src/trie/iterator.rs
core/store/src/trie/mem/iter.rs
core/store/src/trie/mem/mod.rs
core/store/src/trie/mod.rs
core/store/src/trie/resharding.rs
core/store/src/trie/state_parts.rs
core/store/src/trie/trie_tests.rs
core/store/src/trie/update.rs
core/store/src/trie/update/iterator.rs
integration-tests/src/tests/client/flat_storage.rs
nearcore/benches/store.rs
nearcore/src/metrics.rs
runtime/runtime/src/state_viewer/mod.rs
tools/flat-storage/src/commands.rs
tools/state-viewer/src/commands.rs
tools/state-viewer/src/contract_accounts.rs
tools/state-viewer/src/state_dump.rs
tools/state-viewer/src/state_parts.rs
tools/state-viewer/src/trie_iteration_benchmark.rs

Closes https://github.com/near/nearcore/issues/11278
This mostly copies from the on-disk trie implementation except adapting it to memtrie data structures. This eliminates the sole remaining disk-trie use during normal validator node operation (when memtrie is enabled), remove_account.
The memtrie implementation requires a different API because there's no way to grab a read lock and construct an iterator at the same time, due to there necessarily being two layers of lifetimes. So whereas we used to have Trie::iter(), we now must have Trie::lock_for_iter() and then use the result to .iter().

[Memtrie] Implement trie iterator based on memtrie.

---

chain/chain/src/stateless_validation/chunk_endorsement.rs
chain/chain/src/test_utils/kv_runtime.rs
chain/client/src/chunk_inclusion_tracker.rs
chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/stateless_validation/chunk_endorsement_tracker.rs
chain/epoch-manager/src/adapter.rs
chain/epoch-manager/src/lib.rs
core/primitives/src/stateless_validation.rs
integration-tests/src/tests/client/features/stateless_validation.rs
integration-tests/src/tests/client/process_blocks.rs

The logic in #11255 is not correct because chunk endorsement is dependent on the chunk header included in the current block and endorses that chunk header is valid. Block approvals cannot replace chunk endorsements because when a block approval is sent, there is no guarantee that the chunk producer has seen the new chunk header and therefore a malicious attacker can still produce an invalid chunk with correct block approvals. Thanks @pugachAG for catching this!

Revert "feat: count block approval towards chunk endorsement (#11255)"

---

tools/mirror/src/chain_tracker.rs
tools/mirror/src/lib.rs

Before this change, the `TxTracker` returns a `MappedBlock` from `next_batch()` and accepts it (via `SentBatch`) in `on_txs_sent()`. This struct contains a vec of transactions per chunk, and corresponds to a particular block height. In preparation for implementing a qps option to `mirror run`, we refactor it to return a new `struct TxBatch`, which only has a `Vec` of the transactions we want to send. The previous separation of the transactions by shard served no purpose, really, and removing that will make it easier to implement the qps option, since then we'll no longer be batching transactions by block height, but will just be sending them at a regular interval regardless of block height or shard ID. 
The `struct MappedBlock` doesn't fully go away with this PR, since it's cumbersome to …

refactor(mirror): return a struct with a Vec of txs in next_batch()

---

chain/jsonrpc/res/network_info.html
chain/network/src/network_protocol/edge.rs
chain/network/src/peer/tests/communication.rs
chain/network/src/peer_manager/tests/connection_pool.rs
chain/network/src/peer_manager/tests/nonce.rs
chain/network/src/peer_manager/tests/routing.rs
chain/network/src/raw/connection.rs
chain/network/src/raw/tests.rs
chain/network/src/routing/edge.rs
chain/network/src/routing/graph/tests.rs
chain/network/src/stats/metrics.rs
tools/debug-ui/src/CurrentPeersView.tsx
tools/ping/src/lib.rs
tools/state-parts/src/lib.rs

This PR completes the planned deprecation of old-style nonces:
https://github.com/near/nearcore/blob/1479c9084dcfa7480add2ff69a499596a237df55/chain/network/src/network_protocol/edge.rs#L9-L14
It will also address an increase in network traffic seen after #11018 due to transmission of ancient tombstone edges which lingered in the DB storage. After we remove this special logic preventing them from expiring they will simply be discarded.
---
A few tests had to be updated because they were using hardcoded nonce 1 and relying on the fact that it never expires.
Similarly raw connection was (ab)using the fact that a handshake containing a partial edge with nonce 1 will always be accepted. Now it generates a proper timestamp when initiating a handshake. It means that the users of raw connection …

routing: finish deprecation of old-style nonces

---

core/store/src/config.rs
runtime/runtime/src/prefetch.rs

Sweat coin has migrated to new data structures that seem to require fewer storage accesses. Regardless the current prefetcher no longer works, so lets remove it.
Fixes #11327

prefetch: remove code for prefetching claim.sweat::claim

---

pytest/tests/mocknet/helpers/neard_runner.py
pytest/tests/mocknet/helpers/requirements.txt
pytest/tests/mocknet/local_test_node.py
pytest/tests/mocknet/mirror.py
pytest/tests/mocknet/node_handle.py
pytest/tests/mocknet/remote_node.py

This PR changes the way we load the env variables on the host.
The neard_runner.py will now load ~/.env.secret and $NEARD_RUNNER_HOME/.env when it starts `neard`.
This PR also introduces new mirror commands to modify the env variables on the forknet hosts.
This feature will enable the configuration of state dumper and the tracing server.
tested on a host:
```
ubuntu@mocknet--t4dm:~$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "clear_env", "params": {}, "id": 1}' 127.0.0.1:3000
{"result": null, "id": 1, "jsonrpc": "2.0"}
ubuntu@mocknet--t4dm:~$ cat ~/.near/neard-runner/.env
ubuntu@mocknet--t4dm:~$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "add_env", "params": {"key_value": …
```

feat(forknet): add host env variable control to the mirror tool

---

chain/client/src/client.rs
core/primitives/src/test_utils.rs
tools/mirror/src/lib.rs

The Transaction::new() function was changed to create V1 transactions, but we want only V0 transactions in the mirror tool for now, because otherwise all our transactions will be rejected. So we can fix this by making the priority_fee field an Option, and having it return a V0 transaction if it's None

fix(mirror): send V0 transactions

---

chain/client/src/stateless_validation/chunk_validator/mod.rs

As noted in https://github.com/near/nearcore/pull/11330, we cannot skip validation of state witness altogether even if we have applied the chunk itself because chunk header still needs to be validated. Otherwise the invariant that no blocks contain invalid chunks could be broken. This PR does a much less invasive optimization and only skip apply state witness if we have the previous chunk extra locally. Other validation of state witness still remains the same.
Existing tests should suffice since we still send chunk endorsement inside the same function `start_validating_chunk`, just slightly earlier.

feat: skip applying state witness for chunk producers

---

chain/client/src/stateless_validation/chunk_validator/orphan_witness_pool.rs
chain/client/src/stateless_validation/partial_witness/partial_witness_tracker.rs
core/primitives/src/stateless_validation.rs

Currently both partial witness tracker and orphan witness pool use `(height_created, shard_id)` pair as LRU cache key when tracking received state witnesses. This is not entirely correct: different chunk producers can produce a chunk for a given `(height_created, shard_id)`  in different epochs. For example that could happen with a fork on epoch boundary when some validators keep producing chunks for the old epoch while other have already transitioned to the new one.
This PR introduces new struct `ChunkProductionKey` to be used as a key for tracking chunk state witnesses.

fix: add epoch_id to the key identifying chunk state witness

---

runtime/runtime/src/lib.rs

receipt_id already stores that very same info.

tracing: remove duplicate field

---

tools/mirror/src/lib.rs

This reverts commit e301c09e5acf75a4e1603c8ae3904f24eef9962f from https://github.com/near/nearcore/pull/11325. This small commit was not necessary, and actually incorrect, because there's an assumption that changed access keys will only appear in SentBatch::MappedBlock(). Otherwise we hit an assertion here: https://github.com/near/nearcore/blob/510948178c5920c614448dc7bcce72873a1655fd/tools/mirror/src/chain_tracker.rs#L1026

fix(mirror): queue fake blocks for initial create account txs

---

pytest/tests/contracts/gibberish.py

Fixed by making nodes track all shards.

fix: contracts/gibberish.py nayduck test

---

core/store/src/trie/mem/construction.rs
core/store/src/trie/mem/flexible_data/children.rs
core/store/src/trie/mem/flexible_data/encoding.rs
core/store/src/trie/mem/flexible_data/extension.rs
core/store/src/trie/mem/flexible_data/mod.rs
core/store/src/trie/mem/flexible_data/value.rs
core/store/src/trie/mem/freelist.rs
core/store/src/trie/mem/mod.rs
core/store/src/trie/mem/node/encoding.rs
core/store/src/trie/mem/node/mod.rs
core/store/src/trie/mem/node/tests.rs
core/store/src/trie/mem/updating.rs
core/store/src/trie/nibble_slice.rs

This contains two top optimizations that speed up the memtrie construction code:
* Rather than allocating a new Vec<u8> every time we encode nibbles, we use a freelist so that previously allocated Vec<u8> can be reused. This reduces allocations from O(millions) to O(tens).
* As a side effect, InputMemTrieNode has to be changed to contain borrowed slices, as we can no longer give owned Box<[u8]> to it. This is totally fine though because anyway the InputMemTrieNode's data needs to be copied into the constructed memtrie nodes in the arena.
* Optimize the nibble slice encoding function so that rather than encoding nibble by nibble, we encode the first nibble and then just copy the remaining bytes directly. Also optimize the at(i) function, removing branching entirely (this code now gets …

[Memtrie] Optimize NibbleSlice during the memtrie construction code path

---

chain/chain/src/chain.rs
chain/client/src/stateless_validation/chunk_validator/mod.rs

A small PR to initialize the congestion info for genesis.
Please check if this is correct. But I think we can just take the genesis block and read the congestion info from there. I assume it's usually empty, but if genesis somehow contains delayed or buffered receipts, I assume it should be included in the chunk header.

congestion: genesis congestion info

---

core/store/src/trie/trie_storage.rs

This just moves some code from `retrieve_raw_bytes` into separate method `read_for_shard_cache_miss`.
But additionally, if that read results in storage error, we release prefetcher staging area.
If we don't do this, additional read of non-existing value will observe prefetch pending slot and hang on it.

fix: release prefetch slot if there is storage error

---

core/parameters/src/config.rs
core/parameters/src/config_store.rs
integration-tests/src/tests/client/features/stateless_validation.rs
nearcore/src/test_utils.rs

The test was broken in nightly because with congestion control enabled some transactions were being rejected due to missing chunks congestion. I implemented a test configuration that disables congestion control, used it in the broken test and enabled it.

test(stateless_validation) - Fixed and enabled chunk validation test

---

chain/chain/src/runtime/mod.rs
chain/chain/src/runtime/tests.rs
core/primitives/src/block.rs
core/primitives/src/congestion_info.rs
core/primitives/src/errors.rs
core/primitives/src/sharding.rs
core/primitives/src/sharding/shard_chunk_header_inner.rs
core/primitives/src/types.rs
integration-tests/src/tests/client/features/congestion_control.rs
integration-tests/src/user/runtime_user.rs
runtime/runtime-params-estimator/src/estimator_context.rs
runtime/runtime/src/congestion_control.rs
runtime/runtime/src/lib.rs
runtime/runtime/src/metrics.rs
runtime/runtime/tests/runtime_group_tools/mod.rs

We still had an unresolved issue: Where in the code will the first congestion info be computed? This is referred to as bootstrapping the congestion info.
In this PR, I suggest we let the runtime compute it inside `apply`, which means it is done on the shard level, rather than the chain level. I believe this makes sense, since we don't need anything other than the state trie to make this computation. And I'd rather not dig into the trie from the chain level.
As a side-effect of this, the `ContextError` introduced for congestion control is no longer possible. Implementation errors, which would have previously caused this error followed by a crash, would now cause an expensive recomputation of the congestion info and print a warning.
This PR also suggest a semantic change to how …

congestion: glue together congestion info bootstrapping

---

chain/client/src/stateless_validation/chunk_validator/mod.rs
chain/client/src/stateless_validation/shadow_validate.rs

This is a suboptimal fix to #11339 that is easy to implement. The core of the problem is as follows: if a chunk is slow to apply for chunk validators, then their chunk endorsements will not get included in the following block. However, the next block could still be produced, at which point it becomes impossible to include that chunk because when a block producer produces a block, it only includes chunks whose prev block hash is the same as its tip. Now, when a new block is a produced, a chunk producer, after processing that block, will produce a new chunk, which again will cause chunk validators to take a long time to apply and therefore not able to send endorsement before the next block is produced.
This fix works by caching the state validation result so that if there are multiple …

fix: a slow chunk should not lead to chain getting stuck

---

runtime/near-vm-runner/src/near_vm_runner/runner.rs
runtime/near-vm-runner/src/wasmer2_runner.rs

This was a headscratcher to me as I ended up with the two blocks in the same area and the `Err` branch in the 2nd block seemed unreachable to me (and there were not any side-effects in between.) At first I thought that maybe this is a holdover from wasmer2 times, but it is the same there!

vm: simplify calculation of entrypoint index

---

chain/client/src/client.rs
chain/client/src/client_actor.rs
chain/client/src/sync/header.rs

If one wants to take old backup to run some blocks on top of its head, node will first run header sync, and its default behaviour is to download **all** headers from chain. If backup is couple days old, this takes a while.
The solution is to use `expected_shutdown` config, which will stop header sync after shutdown height is reached and let the node download and process blocks. I tested this on my node, it worked nicely, allowing to change shutdown height on the fly.

feat: use shutdown height as sync stop height

---

pytest/tests/mocknet/helpers/neard_runner.py

we've been using the mirror tool without a secret used to map keys, which is fine when we're running internal tests. but if we want to start a forknet instance that will later be opened up to the public, we'll want to use a mix the mapped keys with a secret. so here we will assume that it will be placed in ~/.near/setup/mirror-secret.json (or ~/.near/target/setup/mirror-secret.json for V2 setups) and we'll use it if so

feat(forknet): allow running traffic generator with a key map secret

---

chain/epoch-manager/src/lib.rs
chain/epoch-manager/src/proposals.rs
chain/epoch-manager/src/validator_selection.rs
core/primitives/src/epoch_manager.rs
core/store/src/migrations.rs

On #11322 there was a fair suggestion to clarify what is "next" and "next next" epoch, and in fact, there was some inaccuracy there, which I want to resolve.
With the fixed definitions,
* As epoch T defines epoch T+2, EpochSummary field for epoch T must be called `next_next_version`, not `next_version`. Self-check: on epoch T validators voted for new protocol version; however, on epoch T+1 upgrade doesn't happen because validators need to already sync at some state, which corresponds to old protocol version; protocol version of T+2 is defined by epoch_summary(T).next_next_version.
* `proposals_to_epoch_info` arguments are aligned with what is "prev" and "next". `prev_prev_protocol_version` is kept for legacy reasons, `prev_epoch_info` is indeed info of the epoch before, `protocol_version` …

refactor: clarify what is the next epoch on generation

---

chain/chain/src/chain.rs
chain/client/src/stateless_validation/chunk_validator/mod.rs

We need to use the congestion info stored in the latest block, which was the output of apply the previous chunks.

fix(congestion): use latest congestion info

---

neard/src/main.rs

This causes a few problems:
1. rlimit is a privileged call requiring certain capabilities, which the user might not have, making them unable to run the node even *if* their current limits are high enough;
2. historically operators have attempted to set a higher limit but neard would override it to a smaller one and still run into problems that the operators were attempting to workaround by setting limit higher in the first place;
3. arguably this is not the responsibility of neard to set up limits like these for itself, and systemd gives plenty of good tools to fiddle with these...

neard: don't fiddle with file limits unnecessarily

---

scripts/ft-benchmark.sh

This PR aims to MVP FT transfer benchmark (#11348). This `.sh` script restarts locust and neard if there are changes on remote. It will be runned on one of our VMs. Later it probably should be triggered by CI job, but for now we can just make a cron job which will run it time to time.

[ft transfer benchmark] Restart locust script

---

chain/indexer/Cargo.toml

This is simply adds the `statelessnet_protocol` feature to the `chain/indexer` so we can use it during the StakeWars (statelessnet)

chore(indexer): Add feature `statelessnet_protocol` to be able to use indexer nodes in statelessnet

---

chain/chain/src/runtime/metrics.rs
chain/chain/src/runtime/mod.rs

- Count how many transactions are rejected due to congestion and hence dropped from the pool. Store it as a histogram for detailed insights.
- Keep track of the gas limit for ty conversions, as a simple gauge since this should be a relatively stable value.
- Keep track of how much gas is actually used for tx conversions, in a histogram.

congestion: add metrics for prepare_tx

---

scripts/ft-benchmark.sh

Description of the script I changed: #11391.
I need to add this to `$PATH`, otherwise job inside `cron` don't see `nearup` and `cargo`. Probably it could be done in some more generic way, but I think since we want MVP asap this is fine.
Also added some lines to enrich logs and make debugging easier.

[ft transfer benchmark] Add nearup to PATH

---

integration-tests/src/tests/client/features/congestion_control.rs

Add integration tests to check the TX processing limits are applied for congested shards, both the linearly decreasing limit and the rejection condition when the receiver shard is congested above 25%.

test(congestion): integration tests for new tx limit

---

pytest/lib/transaction.py
pytest/tests/loadtest/locust/common/base.py
pytest/tests/loadtest/locust/common/congestion.py
pytest/tests/loadtest/locust/common/social.py

The transaction id is available after its creation, which we want to use in https://github.com/near/nearcore/pull/11364. It was tricky to extract it because we were receiving a serialized transaction from this API, so I refactored the code to return SignedTransaction instead which also now contains transaction_id.

refactor: Simplify retrieval of transaction id

---

pytest/lib/key.py
pytest/lib/transaction.py
pytest/tests/sanity/rosetta.py

We use it extensively in Locust benchmarks and it shows as a hotspot. A single signature takes around 1-2ms on my machine. PyNacl is a recommended replacement for python-ed25519 that is supposed to be 10-20 times faster for signatures.
This is a part of https://github.com/near/nearcore/issues/11352
I've followed this guide: https://github.com/warner/python-ed25519?tab=readme-ov-file#migrating-to-pynacl

perf: Migrate to pynacl.SigningKey

---

docs/SUMMARY.md
docs/practices/workflows/profiling.md

This includes both the somewhat well known information on how to use perf as well as text on bytehound, which is the only tool that seems to work for memory profiling neard.
Fixes #11389

doc: add a page on profiling

---

chain/client/src/metrics.rs
core/primitives/src/upgrade_schedule.rs
core/primitives/src/version.rs
integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
integration-tests/src/tests/client/features/flat_storage.rs
integration-tests/src/tests/client/features/increase_deployment_cost.rs
integration-tests/src/tests/client/features/increase_storage_compute_cost.rs
integration-tests/src/tests/client/features/lower_storage_key_limit.rs
integration-tests/src/tests/client/features/zero_balance_account.rs
integration-tests/src/tests/client/process_blocks.rs
integration-tests/src/tests/client/resharding.rs
pytest/tests/sanity/upgradable.py

Implemented the feature described in #10911. 
It may or may not be needed for the congestion control and stateless validation release but it should be useful in general and I just want to take this variable out of the equation.

feat(protocol_upgrade) - implemented multiple protocol version upgrades in one release

---

nearcore/res/example-config-gc.json
nearcore/res/example-config-no-gc.json
nearcore/src/config.rs

Add a new telemetry endpoint hosted on N1 alongside the old telemetry endpoint hosted by Pagoda and based on the legacy explorer.  Part of #11156.
EDIT: adding the new endpoint without replacing the old one

chore: Add a new NearOne telemetry endpoint alongside the old explorer telemetry
