node/runtime/src/lib.rs
Addresses https://github.com/nearprotocol/nearcore/issues/89. Could use error! instead of debug!
=> Better runtime error message

Cargo.toml, node/cli/src/chain_spec.rs, node/cli/src/lib.rs, node/client/Cargo.toml, node/client/src/test_utils.rs, node/network/src/test_utils.rs, node/service/Cargo.toml, node/service/src/config.rs, node/service/src/lib.rs, node/service/src/produce_blocks.rs, node/service/src/rpc/mod.rs, node/service/src/test_utils.rs, scripts/rpc.py, test-utils/devnet/Cargo.toml, test-utils/devnet/src/main.rs, tests/test_rpc_cli.rs
fixes https://github.com/nearprotocol/nearcore/issues/102
=> add integration tests for rpc, refactor service

core/txflow/src/dag/message/generated_tests.rs
=> Add failing test

Cargo.toml, core/beacon/src/authority.rs, core/beacon/src/types.rs, core/primitives/src/signature.rs, core/primitives/src/types.rs, core/txflow/src/dag/message/testing_utils.rs, core/txflow/src/dag/mod.rs, core/txflow/src/testing_utils.rs, core/txflow/src/txflow_task/mod.rs, node/network/src/message.rs, node/network/src/protocol.rs, node/network/src/test_utils.rs, node/runtime/src/lib.rs, node/service/Cargo.toml, node/service/src/lib.rs, node/service/src/rpc/api.rs, node/service/src/rpc/types.rs, scripts/rpc.py, test-utils/keygen/Cargo.toml, test-utils/keygen/src/bin/keystore.rs, test-utils/keygen/src/lib.rs, test-utils/keygen/src/main.rs, test-utils/node/src/main.rs, tests/test_rpc_cli.rs
fixes https://github.com/nearprotocol/nearcore/issues/103
cc: @nearmax because i am modifying txflow a little
=> keystore, signed transactions

core/beacon/src/authority.rs, core/beacon/src/types.rs, core/chain/src/lib.rs, core/primitives/src/hash.rs, core/primitives/src/types.rs, core/primitives/src/utils.rs, core/wasm/src/ext.rs, node/beacon-chain-handler/Cargo.toml, node/beacon-chain-handler/src/lib.rs, node/cli2/src/lib.rs, node/client/src/chain.rs, node/client/src/lib.rs, node/client/src/tx_pool.rs, node/network/src/message.rs, node/network/src/network_handler.rs, node/network/src/protocol.rs, node/network/src/test_utils.rs, node/rpc/src/api.rs, node/rpc/src/types.rs, node/runtime/src/lib.rs, node/runtime/src/test_utils.rs, node/service/src/produce_blocks.rs, scripts/rpc.py, test-utils/node/src/main.rs, tests/test_rpc_cli.rs
Moving towards the transaction and receipt model for smart contract execution. Several things are missing in this PR, including mana and gas counting, refund, and promise joins.
=> multi-stage smart contract execution

node/runtime/src/lib.rs, scripts/rpc.py
Add tests that test async calls, callbacks, execution with arguments. Also updated the rpc script.
=> add receipt tests

core/primitives/src/hash.rs, core/primitives/src/types.rs, node/beacon-chain-handler/src/lib.rs, node/network/src/protocol.rs, node/rpc/src/api.rs, node/rpc/src/types.rs, node/runtime/src/lib.rs, scripts/rpc.py, test-utils/node/src/main.rs
fixes https://github.com/nearprotocol/nearcore/issues/93
=> use enum for transaction body

core/primitives/src/types.rs, core/wasm/src/ext.rs, node/beacon-chain-handler/src/importer.rs, node/beacon-chain-handler/src/producer.rs, node/network/src/message.rs, node/network/src/protocol.rs, node/runtime/src/lib.rs, tests/test_rpc_cli.rs
- Fixed bugs in promise_then and apply_receipt
- Refactored apply_receipt
- handle execution errors properly
=> Receipt improvement

core/wasm/src/ext.rs, core/wasm/src/resolver.rs, core/wasm/src/runtime.rs, core/wasm/src/types.rs
Trying to implement log() function usable for debugging AssemblyScript guest.
=> Implement log() function

Cargo.toml, README.md, node/cli/src/lib.rs, node/cli/src/service.rs, test-utils/devnet/src/bin/devnet.rs, test-utils/devnet/src/lib.rs, tests/test_rpc_cli.rs
fixes https://github.com/nearprotocol/nearcore/issues/206
let me know if the changes in the README seem like a sane solution 
also:
- fixes up default values via cli
- disables devnet logging during integration tests by default
=> add logging configuration to service

node/cli/src/lib.rs, node/cli/src/service.rs, node/network/src/message.rs, node/network/src/protocol.rs, node/network/src/service.rs
more support for https://github.com/nearprotocol/nearcore/issues/166
=> add boot nodes

core/primitives/src/types.rs, node/runtime/src/ext.rs, node/runtime/src/lib.rs
Fixes https://github.com/nearprotocol/nearcore/issues/210
=> Move callbacks from Runtime to RuntimeData

core/chain/src/lib.rs, core/primitives/src/types.rs, node/network/Cargo.toml, node/network/src/message.rs, node/network/src/protocol.rs, node/network/src/service.rs, node/network/src/test_utils.rs, node/network/tests/integration_test.rs
- Add integration test to test block catchup with network
- Fix bugs in block request and block response
- Remove outdated tests in the network crate
Resolves https://github.com/nearprotocol/nearcore/issues/248
=> Test block catchup

core/shard/src/lib.rs, node/beacon-chain-handler/src/importer.rs, node/beacon-chain-handler/src/producer.rs, node/runtime/src/ext.rs, node/runtime/src/lib.rs, node/runtime/src/state_viewer.rs
Fixes https://github.com/nearprotocol/nearcore/issues/197. Also removes some nonce cloning.
=> Avoid cloning transactions

core/txflow/src/adapters/mod.rs, core/txflow/src/adapters/receipt_transaction_to_payload.rs, core/txflow/src/adapters/signed_transaction_to_payload.rs, node/beacon-chain-handler/src/producer.rs, node/cli/Cargo.toml, node/cli/src/lib.rs, node/cli/src/service.rs, node/cli/src/test_utils.rs, node/network/src/protocol.rs, node/network/src/test_utils.rs, node/network/tests/integration_test.rs
Also fixes the broken master -- when I was merging the previous PR on github it missed some renaming.
Also fixes the problem with logs being not flushed.
=> Interface consensus through adapters

node/beacon-chain-handler/src/producer.rs, node/cli/src/service.rs, node/network/src/protocol.rs, node/network/src/service.rs, node/network/tests/integration_test.rs
add block announcement to network and channels to send produced block from block producer to network protocol.
=> add block announcement

core/beacon/src/types.rs, core/chain/src/lib.rs, core/primitives/src/signature.rs, core/shard/src/lib.rs, node/beacon-chain-handler/src/producer.rs, node/network/tests/integration_test.rs
=> fork-choice-rule tests

core/beacon/src/types.rs, node/network/tests/integration_test.rs, node/runtime/src/lib.rs
Fixes https://github.com/nearprotocol/nearcore/issues/288
=> fix nonce update bug

nearlib/account.js, nearlib/package-lock.json, nearlib/package.json, nearlib/test-tools/in_memory_key_store.js, nearlib/test/integration.test.js
This only signs with alice keys for now. TBD: how to provide signature?
=> [nearlib] add create account functionality + integration test

core/txflow/src/dag/message/mod.rs, core/txflow/src/lib.rs, test-utils/txflow-test-gen/common_rust_code_for_tests.txt, test-utils/txflow-test-gen/nighty_gen.js, test-utils/txflow-test-gen/txflow.js, test-utils/txflow-test-gen/utils.js
Nightly stress test for txtflow
=> Nightly stress tests

.gitlab-ci.yml, docker/builder.Dockerfile, node/runtime/src/lib.rs, scripts/waitonserver.sh
=> Speeding up CI

core/primitives/Cargo.toml, core/primitives/src/aggregate_signature.rs, core/primitives/src/lib.rs
=> Bls signatures

tests/test_rpc_cli.rs
https://github.com/nearprotocol/nearcore/issues/391
=> Disable flaky integration test, see #391.

nearlib/test/integration.test.js
Also a few additional improvements.
=> [nearlib] add test case for subtracting account balance from orginator on create 

core/wasm/src/executor.rs, core/wasm/src/runtime.rs, core/wasm/src/types.rs, node/runtime/src/lib.rs, node/runtime/src/test_utils.rs
Updating system method_names to start with "_".
Preventing creation of promises with prefix "_" (those methods considered private and other contracts should not be able to call them).
Refactoring node/runtime slightly and adding checks for account_id
=> Updating method_names to prevent some security issues

nearlib/account.js, nearlib/test/integration.test.js
this helps reduce test flakiness
=> [nearlib] add wait for transaction to complete to integration test

node/runtime/src/lib.rs
=> Update node runtime to prevent calling private and empty methods

node/runtime/src/lib.rs, node/runtime/src/system.rs, node/runtime/src/test_utils.rs
Put system functions in a separate file.
=> Runtime system functions

core/txflow/src/txflow_task/mod.rs, node/client/src/lib.rs, node/network/src/peer.rs, node/network/src/peer_manager.rs, node/network/src/protocol.rs, node/testnet/src/lib.rs, tests/test_testnet.rs
* Adds a single testnet integration test;
* Currently, there is a lot of code duplication between testnet and devnet integration tests. I am going to fix it later. For now I would like this test to be submitted so that @mfornet can start working on testnet without concerning of breaking it.
=> Added testnet integration test

core/storage/src/lib.rs, core/transaction/src/lib.rs, node/client/src/test_utils.rs, node/http/src/api.rs, node/runtime/benches/bench.rs, node/runtime/src/lib.rs, node/runtime/src/state_viewer.rs, node/runtime/src/system.rs, node/runtime/src/test_utils.rs, node/shard/src/lib.rs
=> Verify signature at runtime

nearlib/test/integration.test.js, node/runtime/benches/bench.rs, node/runtime/src/test_utils.rs, tests/hello/assembly/main.near.ts, tests/hello/assembly/main.ts
Adding more benchmarks.
Updating integration test to match line as regex.
=> Fix wasm benchmarks to actually execute deployed contract

node/runtime/src/test_utils.rs
Also adding a simple test to cover the bug.
=> Fix node runtime test-utils for deploy

node/runtime/src/lib.rs, node/runtime/src/system.rs
=> Fix create_account to fail on existing account

ATTRIBUTIONS.md, core/storage/src/nibble_slice.rs
Ref #545 Adding attributions + copyright for nibble slice.
=> Attributions file

tests/hello/build.sh
This gives performance boost for contracts, cause it optimizes some simple operations.
We should also enable -O3 for templates in studio
=> Enable -O3 optimization for hello.wasm for benchmarks

scripts/rpc.py
=> Add 'utf-8' to bytearray

node/runtime/src/lib.rs
I verified promise. It works now
=> Flush callbacks in other part of async call

Cargo.lock, node/beacon/Cargo.toml, node/beacon/src/authority.rs, node/beacon/src/lib.rs, node/client/src/lib.rs
Adding logs to help before #612 is fixed.
=> Adding progress for loading authorities

core/primitives/src/logging.rs
Fixes #630 
It fixes panic for non-aligned char
=> Fix unsafe String truncation in logs

nearlib/package.json
published at c50c0b5d331a7e2a10d92c6e71c99db538fe3ee5
=> [nearlib] version bump to 0.3.3

node/runtime/src/lib.rs, node/runtime/src/system.rs
=> Fixing deposit callbacks

pynear/setup.py, pynear/src/near/pynear/cli.py, pynear/src/near/pynear/key_store.py
fixes https://github.com/nearprotocol/nearcore/issues/618
=> pynear: ed25519 -> pyca/cryptography

pynear/setup.py, pynear/src/near/pynear/cli.py, pynear/src/near/pynear/key_store.py
Reverts nearprotocol/nearcore#633
=> Revert "pynear: ed25519 -> pyca/cryptography"

.gitlab-ci.yml, core/wasm/runtest/src/lib.rs, core/wasm/src/prepare.rs, core/wasm/src/runtime.rs, node/beacon/src/authority.rs, node/client/src/lib.rs, node/configs/src/chain_spec.rs, node/http/src/api.rs, node/http/src/types.rs, protos/builder/src/lib.rs, scripts/run_clippy.sh, test-utils/keygen/src/main.rs
Clippy now works with nightly, so I re-enabled it. Fixes #648
=> Enable clippy

core/primitives/src/aggregate_signature.rs
This should speed up signature aggregation by about 4x.  The new bottleneck is computing the y-coordinate during decompression.  This will be fixed in a later review.
=> Faster bls signature decompression

node/client/src/lib.rs
Verify that hash struct field matches block contents and signature matches the hash and public keys.
TODO: support rejecting in pending_blocks logic
=> Verify blocks on import

core/chain/src/lib.rs, core/chain/src/test_utils.rs, core/storage/src/storages/mod.rs, node/beacon/src/beacon_chain.rs
=> Check validity of genesis block at initiliaztion of blockchain

core/primitives/src/logging.rs
Before:
```
args: (173)`{"args":{"receiver":"test_0.5725…`,
```
After:
```
args: (173)`{"args":{"receiver":"test_0.9508344592981046","methodName":"callbackWithName","args":null,"additionalMana":0,"callback":null,"ca…`,
```
=> Increase logging truncation limit to be able to read more arguments

nearlib/test/integration.test.js, node/runtime/src/lib.rs, tests/hello/assembly/json/decoder.ts, tests/hello/assembly/json/encoder.ts, tests/hello/assembly/main.near.ts, tests/hello/assembly/main.ts, tests/hello/assembly/model.near.ts, tests/hello/assembly/model.ts, tests/hello/assembly/near.ts, tests/hello/build.sh
Adding integration tests for promises.
Have to upgrade `hello.wasm`. Updating encoder, decoder and near.ts.
Fixes #689 
Fixes #670
=> Fixing routing bug for callback

node/runtime/src/lib.rs
=> Improve error message for promise returns

node/client/src/lib.rs
Currently, when we produce a shard block, we only use the previous receipts from the same shard. While this is fine until we have multiple shards, it is better to incorporate receipts from other shards now so that we don't need to revisit this in the future.
=> Use receipts in payload when producing a shard block

core/mempool/src/lib.rs, core/primitives/src/beacon.rs, core/primitives/src/chain.rs, core/primitives/src/hash.rs, core/primitives/src/transaction.rs, node/client/benches/client_bench.rs, node/client/src/lib.rs, node/client/src/test_utils.rs, node/consensus/src/adapters/transaction_to_payload.rs
=> Fix #189: use HashSet

Cargo.lock, Cargo.toml, node/alphanet/Cargo.toml, node/alphanet/src/lib.rs, node/devnet/Cargo.toml, node/devnet/src/lib.rs, test-utils/testlib/Cargo.toml, test-utils/testlib/src/alphanet_utils.rs, test-utils/testlib/src/generate_test_spec.rs, test-utils/testlib/src/lib.rs, tests/test_alphanet.rs
alphanet test utils -> separate crate
=> testing utils crate

core/primitives/src/network.rs, node/alphanet/src/lib.rs, test-utils/testlib/src/alphanet_utils.rs, tests/test_alphanet.rs, tests/test_alphanet_command_line.rs
test that kills one node and restarts it
TODO: connect to that node with a client and send transactions / check state
=> test for alphanet

core/nightshade/src/nightshade_task.rs
=> Send RequestPayload to sender instead of proposer.

node/client/src/lib.rs, node/coroutines/src/client_task.rs, node/network/src/protocol.rs
=> Minimal importing of set of blocks instead of indiviudal import+announce

nearlib/account.js, nearlib/package.json, nearlib/test/integration.test.js
=> Fix nearlib createAccount to work with 0 amount

Cargo.lock, core/storage/Cargo.toml, core/storage/src/storages/beacon.rs, core/storage/src/storages/mod.rs, core/storage/src/storages/shard.rs
Change caches used in storage from `HashMap` to LRU cache.
=> Use LRU cache for storage

node/network/src/peer.rs, node/network/src/peer_manager.rs, node/network/src/protocol.rs, node/network/src/testing_utils.rs
Implement `ban_peer` for `PeerManager`.
=> Ban malicious peers

node/client/src/lib.rs, node/network/src/peer_manager.rs, tests/test_alphanet_command_line.rs
Increase timeout to 60 seconds in test_ban_peer and test_4_20_kill1.
=> Increase timeout to 60 seconds on some tests

node/configs/src/chain_spec.rs, test-utils/testlib/src/alphanet_utils.rs
Don't create the wrong number of accounts in testing_spec
=> Unbreak master

core/wasm/src/runtime.rs
Tested using local studio. Going to update near-runtime-ts later and add test/hello tests after that one
=> Export storage_range to WASM Runtime API

test-utils/testlib/src/lib.rs, test-utils/testlib/src/nodes_monitor.rs
A struct that monitors a group of nodes and computes the following:
* whether they are all running;
* whether they are all in sync;
* average tps.
=> Node observer

core/nightshade/src/nightshade.rs, core/nightshade/src/verifier.rs, core/primitives/src/crypto/group_signature.rs, core/primitives/src/crypto/signature.rs, core/primitives/src/logging.rs, core/primitives/src/test_utils.rs, core/primitives/src/traits.rs, core/primitives/src/transaction.rs, core/storage/src/trie/mod.rs, core/storage/src/trie/update.rs, node/coroutines/src/client_task.rs, node/network/src/peer_manager.rs, node/network/src/protocol.rs, node/runtime/src/lib.rs, test-utils/testlib/src/node/mod.rs, test-utils/testlib/src/nodes_monitor.rs, test-utils/testlib/src/test_helpers.rs, test-utils/testlib/src/transactions_executor.rs, test-utils/testlib/src/transactions_generator.rs
=> Fix some clippy warnings

node/http/src/api.rs, node/http/src/server.rs, node/http/src/types.rs
=> Return latest block index and genesis hash in healthz

Cargo.lock, Cargo.toml, core/primitives/src/account.rs, core/primitives/src/lib.rs, core/primitives/src/utils.rs, core/storage/src/lib.rs, core/storage/src/storages/mod.rs, node/runtime/src/ext.rs, node/runtime/src/lib.rs, node/runtime/src/state_viewer.rs, node/runtime/src/system.rs, node/runtime/src/test_utils.rs, node/runtime/src/tx_stakes.rs, tests/test_runtime.rs
=> Refactor node runtime and move common functions into core

ops/deploy_local.sh, ops/deploy_remote.sh, ops/run.sh, ops/update_remote_testnet.sh
The testnet was already reloaded
=> Bump testnet to 0.1.3

test-utils/testlib/src/standard_test_cases.rs, tests/test_cases_runtime.rs, tests/test_cases_testnet_direct.rs, tests/test_cases_testnet_rpc.rs
Testing allowed call and rejected calls
=> Adding access_key calls tests

nearmint/src/main.rs
Status 1 means failed.
Fixes #909
=> Fix integration test to return Failed transaction on WASM Assert

test-utils/testlib/src/node/runtime_node.rs, test-utils/testlib/src/user/runtime_user.rs
send_money benchmark was not sending any money because of nonce check fail
=> Fix RuntimeNode

runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/wasm/src/cache.rs, runtime/wasm/src/lib.rs
Improves the case of large contract + small function call.
=> Cache reading contract code from storage

nearmint/src/lib.rs, nearmint/tests/test.rs, runtime/primitives/src/utils.rs, runtime/runtime/src/adapter.rs
Add rpc for access key through tendermint abci interface. Fixes #943.
=> Add rpc for access key

Cargo.lock, runtime/runtime/src/ext.rs, runtime/runtime/src/lib.rs, runtime/wasm/Cargo.toml, runtime/wasm/src/executor.rs
The bug that broke the testnet
=> Fix non-deterministic receipts order

Cargo.lock, Cargo.toml, nearmint/src/lib.rs, runtime/runtime/src/lib.rs, test-utils/state-viewer/Cargo.toml, test-utils/state-viewer/src/main.rs
Printing the whole state for debugging purposes.
=> State viewer tool

Cargo.lock, runtime/runtime/tests/test_evil_contracts.rs, runtime/wasm/Cargo.toml, runtime/wasm/runtest/src/lib.rs, runtime/wasm/src/executor.rs, runtime/wasm/src/types.rs
- Update wasmer version
- Propagate errors
- Add tests for error cases
=> Propagate RuntimeError from contract calls

.gitlab-ci.yml, nearmint/src/lib.rs
=> Fix response code

.gitlab-ci.yml
Set up NEAR_PROTOS_DIR for CI.
=> fix nearlib CI

nearmint/src/lib.rs, nearmint/tests/test.rs
Add more error messages to the RPC log.
=> Better error message

nearmint/src/lib.rs, nearmint/tests/test.rs, runtime/runtime/src/adapter.rs
Return access keys and their public keys on `access_keys` view call. Also add rpc to view an access key given its public key.
=> Update access key rpc

README.md
Minor updates to the format of the readme:
- Add emoji
- Center logo
=> Update format of README to the hype train

Cargo.lock, chain/client/src/client.rs, chain/client/src/sync.rs, chain/client/src/types.rs, core/primitives/src/rpc.rs, core/primitives/src/types.rs, core/primitives/src/utils.rs, near/Cargo.toml, near/src/config.rs, near/src/main.rs
For example 
```
{
"chain_id": "test-chain-RS43F",
"rpc_addr": "0.0.0.0:3030",
"sync_info": {
"latest_block_hash": "Gf1aDbCi8YE8PtfPEN4sQB4mBbjZPkDjCxvUcLB72awK",
"latest_block_height": 2866,
"latest_block_time": "2019-07-12T04:08:53.243110Z",
"latest_state_root": "EjwBRcW2j9CSJGCbsQ5dwxxBA4pBBHZzVJQvAimSm3rZ",
"syncing": false
},
"validators": [
"test.near"
],
"version": {
"build": "288c74b5-modified",
"version": "0.2.4"
}
}
```
Useful to check what version a node is running and if there was modified code.
=> Adding version + git version to status & CLI

chain/client/src/client.rs
Fix broken code introduced in #1061. We should be more careful with future PRs.
=> Fix broken master

chain/client/src/client.rs
=> Remove forced block production schedule

Cargo.lock, runtime/wasm/Cargo.toml, runtime/wasm/runtest/src/lib.rs
Singlepass backend is crashing
=> Revert back to cranelift backend for now

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/client.rs, core/primitives/src/rpc.rs, core/store/src/lib.rs, near/src/runtime.rs, near/src/validator_manager.rs, near/tests/stake_nodes.rs
TODO: add slashing to runtime, but this requires integration with fishermen.
=> Add slashing in validator manager

near/tests/stake_nodes.rs
This fix will not solve the main problem of the `kickout` test, but will solve other minor issue.
=> Finish kickout test after everything gets verified

Cargo.lock, chain/telemetry/Cargo.toml
Otherwise, I get `Connect(SslIsNotSupported)`.
=> Enable sending telemetry data over HTTPS

Dockerfile, near/src/runtime.rs, near/tests/stake_nodes.rs, scripts/tag_release.sh
* Remove not needed source files from docker image
* Dedup validators from get_epoch_validators
=> Update testnet genesis

Cargo.lock, test-utils/state-viewer/Cargo.toml, test-utils/state-viewer/src/main.rs
Add replay chain functionality to help debugging.
=> Allow state viewer to replay chain

Cargo.lock, chain/network/Cargo.toml, chain/network/tests/announce_account.rs
=> Network tests as heavy

near/res/testnet.json, scripts/state/migrate-from-2.7.py
Fix bugs in state migration where public keys and access permissions are not properly serialized.
=> Fix state migration

chain/client/tests/catching_up.rs
expensive test to make sure that all OneParts have necessary receipts
=> test_catchup_random_single_part_sync

Cargo.lock, core/crypto/Cargo.toml, core/crypto/src/signature.rs, core/crypto/src/test_utils.rs
=> Add secp256k1 support

.gitlab-ci.yml, chain/chain/Cargo.toml, chain/chain/src/chain.rs, chain/chain/src/lib.rs, chain/chain/src/test_utils.rs, chain/chunks/Cargo.toml, chain/chunks/src/lib.rs, chain/client/Cargo.toml, chain/client/src/client.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs, chain/client/tests/catching_up.rs, chain/client/tests/chunks_management.rs, chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/proposals.rs, chain/network/src/peer.rs, core/primitives/src/test_utils.rs, near/src/runtime.rs, runtime/runtime/src/system.rs
- Removing all the "cow mine" tracing
- Replacing "cow mine" asserts with a new macro `byzantine_assert` that triggers if a `byzantine_asserts` feature is enabled, and enabling the feature in CI
=> Cleaning up chunks

scripts/nodelib.py, scripts/start_localnet.py, scripts/start_testnet.py, scripts/start_unittest.py, scripts/state/migrate-from-2.7.py, scripts/stop.py
=> Use env python

chain/network/src/peer.rs, chain/network/src/types.rs
=> Notify if peer connection was dropped b/c of genesis mismatch

chain/chain/src/chain.rs, chain/chain/src/error.rs, core/primitives/src/block.rs
ISSUE
===
https://github.com/nearprotocol/nearcore/issues/1236
TEST PLAN
===
- sanity tests
- assert!(false), tested locally
- cargo test --all --verbose -- --nocapture
LOGIC REVIEWER
===
Alex Skidanov
=> Proper checks for a block in a new epoch

chain/chain/src/chain.rs, chain/chain/src/error.rs, core/primitives/src/block.rs
ISSUE
===
https://github.com/nearprotocol/nearcore/issues/1236
TEST PLAN
===
sanity tests
cargo test --all --verbose --no-fail-fast -- --nocapture
LOGIC REVIEWER
===
Alex Skidanov
=> Proper checks for a block in a new epoch (#1256)

Cargo.lock, chain/chain/Cargo.toml, chain/chunks/Cargo.toml, chain/client/Cargo.toml, chain/epoch_manager/Cargo.toml, chain/jsonrpc/Cargo.toml, chain/jsonrpc/tests/rpc_query.rs, chain/network/Cargo.toml, core/crypto/Cargo.toml, core/primitives/Cargo.toml, core/primitives/src/merkle.rs, core/primitives/src/serialize.rs, core/primitives/src/views.rs, core/store/Cargo.toml, core/store/src/lib.rs, near/Cargo.toml, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-logic/README.md, runtime/near-vm-logic/tests/test_registers.rs, runtime/runtime/Cargo.toml, scripts/state/migrate-from-2.7.py, test-utils/loadtester/Cargo.toml, test-utils/state-viewer/Cargo.toml, test-utils/testlib/Cargo.toml
Bringing changes post 0.3.0 release & merging trees back to not have future conflicts.
=> Merging master to staging

chain/chain/src/chain.rs, chain/client/src/client.rs
Filter transaction that have expired or from a different fork when producing chunks.
=> Filter transaction when producing chunks

core/primitives/src/views.rs, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-logic/tests/test_storage_usage.rs
Also add Debug and Display for CryptoHashView
=> Fix broken test

chain/client/src/info.rs
Report whether the node is a validator at the moment to telemetry.
=> Add is_validator to telemetry

Cargo.lock, runtime/near-vm-runner/Cargo.toml
=> Update Wasmer to 0.7.0

README.md
Also as a test with external contributor
=> Remove running and developing as link is dead

chain/chain/src/chain.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/client/src/types.rs, near/src/config.rs
=> Remove transaction validity period from client config

Cargo.lock, core/crypto/Cargo.toml, core/crypto/src/key_file.rs
Ref @zedt3ster recommendation from https://github.com/sigp/lighthouse/pull/541
=> Change key file permissions to minimum required

runtime/near-vm-logic/src/context.rs, runtime/near-vm-logic/src/errors.rs, runtime/near-vm-logic/src/logic.rs, runtime/near-vm-logic/tests/fixtures.rs, runtime/near-vm-logic/tests/test_registers.rs, runtime/near-vm-logic/tests/test_storage_usage.rs, runtime/near-vm-logic/tests/test_view_method.rs, runtime/near-vm-runner/benches/bench.rs, runtime/near-vm-runner/tests/test_rs_contract.rs, runtime/near-vm-runner/tests/test_ts_contract.rs, runtime/runtime/src/actions.rs, runtime/runtime/src/state_viewer.rs
Implements https://github.com/nearprotocol/NEPs/pull/18.
=> Prohibit certain binding methods in view call

chain/epoch_manager/src/lib.rs
Fixes a bug found in https://github.com/nearprotocol/nearcore/pull/1423. The bug is caused by incorrect computation of kickout when someone first unstakes and then stakes in the same epoch.
=> Fix a bug in staking when unstake and stake happens in the same epoch

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/info.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs, chain/client/src/types.rs, chain/client/tests/challenges.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, core/primitives/benches/serialization.rs, core/primitives/src/block.rs, core/primitives/src/sharding.rs, core/primitives/src/types.rs, core/primitives/src/views.rs, core/store/src/lib.rs, genesis-tools/genesis-populate/src/lib.rs, near/src/runtime.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/runtime/tests/runtime_group_tools.rs, test-utils/testlib/src/node/runtime_node.rs, test-utils/testlib/src/runtime_utils.rs, test-utils/testlib/src/user/runtime_user.rs
=> Dividing state into parts

Cargo.lock, core/crypto/Cargo.toml, core/primitives/Cargo.toml, runtime/near-vm-logic/Cargo.toml, runtime/runtime/Cargo.toml
https://www.reddit.com/r/rust/comments/dguqt3/vulnerability_in_sodiumoxide_generichashdigesteq/
=> Sodiumoxide vulnerability fix

chain/chain/src/test_utils.rs, chain/client/tests/process_blocks.rs
TODO: enable test that relies on real crypto once https://github.com/nearprotocol/nearcore/pull/1458 is merged.
=> Remove crypto from KeyValueRuntime

Cargo.lock, near/Cargo.toml, near/src/config.rs, test-utils/testlib/src/standard_test_cases.rs, tests/test_cases_runtime.rs, tests/test_errors.rs
Give test.near 1M NEAR for CI purposes.
=> Give more money to test.near

core/store/src/trie/update.rs, runtime/runtime/src/lib.rs
Temporary fix the initial state cloning using actual cloning.
=> Clutch for #1481

chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/src/types.rs, chain/network/tests/peer_handshake.rs
Fix the problem for dropping connection if nonce is invalid, which happens after loosing data on shutdown.
=> Add new round on handshake if invalid nonce.

chain/client/src/client.rs, chain/client/src/client_actor.rs
=> Broadcast produced blocks before applying them

scripts/start_testnet.py
3 more boot nodes to speed up syncing.
=> Add more bootnodes

Cargo.lock, core/crypto/Cargo.toml, core/crypto/src/signature.rs
eth-secp256k1 got renamed to parity-secp256k1
=> Fix a dependency

chain/chain/src/chain.rs, chain/chain/src/types.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, core/primitives/benches/serialization.rs, core/primitives/src/block.rs, core/primitives/src/sharding.rs, core/primitives/src/views.rs, genesis-tools/genesis-populate/src/lib.rs
=> Backported `chunk` API

conf/grafana-dashboard.json
=> fix a few queries which was work for only one node by aggregate

runtime/near-vm-logic/tests/test_miscs.rs
=> Fix bad test in near-vm-logic

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs, chain/client/tests/process_blocks.rs, chain/network/src/codec.rs, chain/network/src/peer.rs, chain/network/src/types.rs, chain/network/tests/announce_account.rs, chain/network/tests/peer_handshake.rs, chain/network/tests/routing.rs, core/primitives/src/block.rs, near/src/config.rs, near/src/lib.rs, test-utils/testlib/src/lib.rs
Check that genesis hash and chain id match before accepting this peer.
=> Add chain id to handshake.

chain/client/tests/challenges.rs, core/primitives/src/challenge.rs, core/store/src/trie/mod.rs
=> Remove key from StateItem

chain/epoch_manager/src/lib.rs, near/src/runtime.rs, runtime/runtime/src/lib.rs
=> Fix slashing violating invariant

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/chain/src/test_utils.rs, chain/client/src/test_utils.rs, chain/client/tests/challenges.rs, core/primitives/src/sharding.rs
Update caches in `ChainStore` when committing `ChainStoreUpdate`.
=> ChainStore cache update

Cargo.lock, runtime/near-vm-runner/Cargo.toml, runtime/near-vm-runner/src/prepare.rs, runtime/near-vm-runner/tests/test_invalid_contracts.rs
It's the same parser that wasmer uses.
=> Run wasmparser::validate before pwasm utils

chain/network/src/peer.rs, chain/network/src/rate_counter.rs
It's now infinite times faster (so long as you push infinite items inside)
Fixes #1314
=> Improve rate counter

.gitlab-ci.yml
With help from @abacabadabacaba , tried gitlab-runner locally and simulate broken pipe in a python script. Hopefully this fix broken pipe issue on ci.
=> Fix ci broken pipe

near/src/config.rs
=> Fix an epochal failure

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/chain/src/types.rs, chain/chain/src/validate.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs, chain/client/tests/challenges.rs, chain/client/tests/process_blocks.rs, chain/network/src/codec.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, chain/network/tests/peer_handshake.rs, pytest/lib/utils.py, pytest/tests/sanity/skip_epoch.py
Requesting shard state from peers who report to have it (not only from block producers)
- Also making it possible to sync as of immediately after first chunk
=> State sync from peers

Cargo.lock, core/primitives/src/types.rs, core/store/src/trie/mod.rs, near/src/runtime.rs, near/tests/sync_state_nodes.rs
=> Don't panic on empty state

Cargo.lock, chain/chain/Cargo.toml, chain/chain/src/lib.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chunks/src/lib.rs, chain/chunks/src/types.rs, chain/client/src/client.rs, chain/client/src/types.rs, chain/client/tests/challenges.rs, chain/pool/Cargo.toml, chain/pool/src/lib.rs, chain/pool/src/types.rs, core/crypto/src/signature.rs, core/primitives/src/block.rs, core/primitives/src/sharding.rs, near/src/runtime.rs
This reverts commit 07941ad67c9555e9ecca0a2e9edc9a46d2b165e8.
=> Revert "Client TX limiting (#1657)"

runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs
=> Fix gas_used should be larger than gas_burnt

chain/chain/src/chain.rs, chain/client/tests/cross_shard_tx.rs, nightly/nightly.py, nightly/nightly.txt, nightly/nightly_small.txt, nightly/requirements.txt, pytest/tests/sanity/rpc_tx_forwarding.py, pytest/tests/sanity/skip_epoch.py, pytest/tests/sanity/state_sync.py, pytest/tests/sanity/transactions.py, pytest/tests/stress/stress.py
Also fixing a couple of tests:
- Cross-shard tx with 75ms on my machine sometimes fails due to synchrony assumption violation, so making it 100ms (still has decent forkfulness).
Long term need to figure out how to make it not specific to partiuclar hardware
- Python tests started failing after fixing gas price, setting it to zero where matters
=> Hacky Nightly runner for python and expensive tests

runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs, test-utils/testlib/src/fees_utils.rs, test-utils/testlib/src/node/runtime_node.rs, test-utils/testlib/src/standard_test_cases.rs
=> Switch rewards to 30% for function call only

scripts/nodelib.py
=> fix verbose

Cargo.lock, chain/chain/Cargo.toml, chain/chunks/Cargo.toml, chain/client/Cargo.toml, chain/epoch_manager/Cargo.toml, chain/network/Cargo.toml, chain/network/src/codec.rs, chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/src/test_utils.rs, chain/network/tests/cache.rs, core/store/Cargo.toml, core/store/src/lib.rs, runtime/near-vm-runner/Cargo.toml, runtime/runtime/Cargo.toml
Fix memory leaks on routing table.
=> Routing table cache

chain/client/src/client.rs, chain/network/src/peer_manager.rs, chain/network/src/peer_store.rs, chain/network/tests/routing.rs
=> Churn attack

runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs
In some places it uses the default config instead of the actual
=> Use real runtime fees config

pytest/tests/sanity/fork_sync.py, pytest/tests/sanity/one_val.py, pytest/tests/sanity/rpc_query.py, pytest/tests/sanity/rpc_tx_forwarding.py, pytest/tests/sanity/skip_epoch.py, pytest/tests/sanity/state_sync.py, pytest/tests/sanity/transactions.py
Fix some nightly tests caused by the `min_gas_price` change.
=> Fix some nightly tests

Dockerfile
*Resolves #1840*
Should we cherry-pick this to master?
=> nearcore build in our official Docker image did not sent telemetry data

Cargo.lock, chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/epoch_manager/Cargo.toml, chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/test_utils.rs, chain/epoch_manager/src/types.rs, core/primitives/src/challenge.rs, near/src/runtime.rs, near/src/shard_tracker.rs, runtime/runtime/src/balance_checker.rs, runtime/runtime/src/lib.rs
Implements progressive slashing described in #1830.
=> Progressive Slashing

chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs, chain/client/src/types.rs, chain/client/tests/catching_up.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, near/tests/sync_state_nodes.rs
We don't assign ourselves in State Sync.
NOT related to #1824.
=> state sync not asking itself

.gitlab-ci.yml, scripts/testlib.py
=> Print which test is runned before run it

chain/chain/src/chain.rs, chain/chain/src/lightclient.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/epoch_manager/src/lib.rs, near/src/runtime.rs, test-utils/state-viewer/src/main.rs
Fixes https://github.com/nearprotocol/nearcore/issues/1855. Relies on https://github.com/nearprotocol/nearcore/pull/1882.
- discuss with @bowenwang1996 and @SkidanovAlex where seats are necessary
- how to test?
=> get_all_block_producer_seats + get_all_block_producers_ordered

nightly/nightly.txt, pytest/lib/cluster.py, pytest/tests/sanity/block_sync.py, pytest/tests/sanity/validator_switch.py
* Test that if one validator somehow takes over the network other validators are still in sync
* Test that it is possible to sync through block sync
=> Add some pytests

chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs, chain/client/src/view_client.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs
Allow client to handle the case when a message was not delivered.
Allow to solve #1824. cc: @Kouprin
=> Network report if a message was delivered or not

chain/network/src/codec.rs, chain/network/src/peer_manager.rs, chain/network/src/test_utils.rs, chain/network/src/types.rs, chain/network/tests/routing.rs, near/src/config.rs
=> Routed message ttl

chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/types.rs
`impl PartialEq for DownloadStatus` shouldn't be used by mistake.
=> unreachable PartialEq for DownloadStatus

Cargo.lock, chain/chain/Cargo.toml, chain/chain/src/chain.rs, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs
=> answer to StateRequest in parallel

.gitignore, chain/chain/src/store.rs, chain/chunks/src/lib.rs, chain/chunks/src/types.rs, chain/client/src/client_actor.rs, core/store/src/db.rs, nightly/nightly.txt, pytest/lib/adversary.py, pytest/tests/adversarial/malicious_chain.py, pytest/tests/adversarial/start_from_genesis.py
Fixes https://github.com/nearprotocol/nearcore/issues/1917.
Contains tests which should be fixed by doomslug and https://github.com/nearprotocol/nearcore/issues/1936.
=> limiting number of blocks / chunks per height + adversary tests

chain/client/src/test_utils.rs
=> Fix `setup_mock_all_validators`

pytest/lib/cluster.py
=> Fix pytest

chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/tests/catching_up.rs, nightly/nightly.txt
Fixes https://github.com/nearprotocol/nearcore/issues/1919.
=> seals implementation and testing chunks grieving

test-utils/testlib/src/user/rpc_user.rs
Our RpcUser is implemented by using async jsonrpc client and spinning up an
actix runtime on every query.
Seems like there is something in actix implementation that makes it
work fine in nearcore tests but break in RpcUser usage from near-evm.
The workaround for now is to create a new JsonRpcClient on every
query.
=> Fix RpcUser

chain/chain/src/test_utils.rs, chain/jsonrpc/tests/rpc_query.rs, core/primitives/src/views.rs, near/src/runtime.rs
Add block hash to rpc query result in addition to block height.
=> Add block hash to query result

chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/client/tests/catching_up.rs, chain/client/tests/cross_shard_tx.rs, chain/client/tests/query_client.rs, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, core/primitives/src/lib.rs, core/primitives/src/rpc.rs, core/primitives/src/serialize.rs, core/primitives/src/types.rs, core/primitives/src/views.rs, near/src/runtime.rs, near/tests/rpc_nodes.rs, near/tests/stake_nodes.rs, test-utils/testlib/src/user/rpc_user.rs
=> RPC query account information and access keys by a specific block id

Cargo.lock, chain/epoch_manager/Cargo.toml, chain/epoch_manager/tests/finality.rs, chain/jsonrpc/Cargo.toml, core/crypto/Cargo.toml, core/crypto/src/signature.rs, core/crypto/src/test_utils.rs, core/crypto/src/vrf.rs
This fixes compilation errors we had because of conflicting versions of `rand` across various dependencies.
Fixes #1820
=> Update rand & dalek in crypto

Cargo.lock, chain/client/Cargo.toml, chain/client/src/info.rs
=> Move sysinfo fix from staging

scripts/docker-release.sh
A script for release docker build, tag, push image
Test Plan
------------
I run it except the last line. And also separately test last line for a different image
=> Release docker build

Cargo.lock, chain/client/tests/catching_up.rs
Fix catchup tests. Fixes #2145 
Test plan
--------
Test that catchup tests work after this fix.
=> Fix(test): fix catch up test

near/src/lib.rs, pytest/tests/stress/hundred_nodes/README.md, pytest/tests/stress/hundred_nodes/create_gcloud_image.py, pytest/tests/stress/hundred_nodes/start_100_nodes.py
test: Enable diagnostic in one hundred nodes test
=> Marx block prod 100

core/primitives/src/utils.rs
Remove doctest that was running incorrectly.
=> fix(doctest): Refactor comment.

chain/chain/src/chain.rs, chain/chain/src/lib.rs, chain/chain/src/store.rs, chain/client/src/client_actor.rs, chain/jsonrpc/src/lib.rs, chain/network/src/types.rs, core/store/src/db.rs, pytest/lib/cluster.py
Fixes https://github.com/nearprotocol/nearcore/issues/2270.
=> feat(GC): block refcount map

pytest/tests/delete_remote_nodes.py, pytest/tests/stress/hundred_nodes/create_gcloud_image.py, pytest/tests/stress/hundred_nodes/start_100_nodes.py
Can create K docker node and 100-K binary node now
Test Plan
------------
I run this script for total 6 node, 4 docker node (to avoid address insufficient) and works well
=> feat(script): docker node in 100 node test

Cargo.lock, pytest/lib/branches.py
In one test we found compile changes cargo.lock cause git checkout back fail
Test Plan
------------
Fixed version pass ci
=> fix(script): stash after build to fix fail on cargo.lock change

pytest/tests/sanity/rpc_state_changes.py
This fixes a broken `pytest/tests/sanity/rpc_state_changes.py`.
The test got into a broken state after #2272
=> fix(jsonrpc): Removed a test creating an account without a balance since it is invalid

chain/chunks/src/lib.rs
Remove the debug assert in `request_partial_encoded_chunk` since it is possible that requesting from self happens. For example it could be that a node somehow lost its data and resync to the network, at which point it has to request chunks that it produced from others. Also fixes the case when choosing random block producer fails due to lack of block producers to choose from other than self. Resolves #2369.
Test plan
--------
`test_request_partial_encoded_chunk_from_self` passes and also pytest `block_sync.py` which failed to due debug assert failure, also passes.
=> fix: fix test failure due to requesting chunk parts from self

core/primitives/src/test_utils.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/verifier.rs
Fixes: #2371
Increasing balance from yocto to NEAR.
- unit tests
=> fix(Runtime): node tests

chain/network/src/test_utils.rs
While testing it is possible that TestA calls open_port and it gets port 1234. Since this port is not in use yet, if TestB calls open_port it is possible to get port 1234 again. This will make on of the two test fails as one of them will try to open port 1234 failing since the port is already in use by the other test.
=> fix: Address port collision when calling open_port.

chain/chain/src/chain.rs, chain/chain/src/types.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/client/src/types.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs
This PR add some comments and refactor code regarding chain syncing. This is part of the stability push, as I try to make progress through all code related to state/header/block syncing. 
Check also [notion page](https://www.notion.so/nearprotocol/Sync-Review-22a043d5dadc4b1ba921c65883f07a90) where progress is more clear.
=> [refactor]: Add comments for sync related logic.

chain/epoch_manager/src/lib.rs
Attribute first block in an epoch to the correct validator id.
Test plan
---------
test_bad_block_tracker
=> fix(epoch_manager): Block tracker for first block in epoch

chain/epoch_manager/src/lib.rs
We have special logic for keeping at least one validator not in kickout
set, but it breaks if all blocks are produced by validators in previous
kickout set.
Test plan
---------
test_all_kickout_edge_case
=> fix(epoch_manager): small fix to all kicked out case

chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/proposals.rs
Test that starts with an account as a validator,
then reduces stake and then gets kicked out for missing a block.
Test plan
---------
new test
=> fix(epoch_manager): fisherman kickout bug fix

chain/client/src/client_actor.rs
Fixes two issues:
1. Orphan pool getting overwhelmed during syncing and burns a lot of unnecessary cpu cycles. Resolves #2418.
2. We currently don't explicitly request sync block and relies on orphan sync to get to it. This means that state sync might be slow when epoch length is large (40k in practice).
Test plan
---------
It is hard to test the changes here as what is fixed here is mostly performance rather than correctness. I tested syncing with betanet and it worked well, whereas before this change the node would get stuck in state sync with high cpu usage.
=> fix(chain): drop blocks that are too far in the future

chain/client/src/client.rs, chain/client/tests/challenges.rs
Disabling challenges until they are fully working. Fixes #2290.
Test plan
----
All CI tests pass
=> Disable challenges

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/client/src/client_actor.rs, chain/client/tests/process_blocks.rs, neard/src/runtime.rs, nightly/nightly.txt, pytest/tests/sanity/garbage_collection1.py, pytest/tests/sanity/gc_after_sync.py, pytest/tests/sanity/gc_sync_after_sync.py
Fixes https://github.com/nearprotocol/nearcore/issues/2413.
Fixes https://github.com/nearprotocol/nearcore/issues/2399.
=> feat(GC): tail upd

test-utils/state-viewer/src/main.rs
For testnet and mainnet, we will need to stop the node after some given height. This PR adds an optional argument to state dump, which, if instantiated, will make state dump find the first final block whose height is greater than or equal to the provided height and dump state from that block.
Test plan
---------
Manually test state dump with a local node.
=> feat: add option to state dump at stop height

genesis-tools/README.md, runtime/runtime-params-estimator/README.md, runtime/runtime-params-estimator/test-contract/build.sh, runtime/runtime-params-estimator/test-contract/src/lib.rs
Test plan
---
* ./test-contract/build.sh works
* commands in README.md can execute
=> fix(rt costs): update docs and scripts

core/store/src/trie/mod.rs, core/store/src/trie/trie_storage.rs
=> fix(storage) RcTrieNode struct removed

core/store/src/trie/insert_delete.rs, core/store/src/trie/mod.rs
=> fix(trie): Remove delete flag from Trie::delete method return value

chain/chain/src/chain.rs, chain/client/src/client_actor.rs, genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs, neard/res/mainnet_genesis.json, neard/src/config.rs
Cherry picking commit https://github.com/nearprotocol/nearcore/commit/857b5d8986bc0f13cd80a4ace552641171a4b841 from master.
Test plan
---------
Test locally that a node can start.
=> feat: Mainnet config

chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/test_utils.rs, chain/epoch_manager/tests/random_epochs.rs
Test for epoch manager. Generates random chains and asserts some
invariants.
Test plan
---------
N/A
=> fix(epoch_manager): test

chain/client/src/client_actor.rs
Previously announce accounts were sent once per epoch, but some
validator didn't manage to learn old announce accounts.
=> fix: Send announce account every half epoch always.

chain/client/src/client.rs
Fix a bug where a node doesn't forward transactions
if it will be a chunk producer in next epoch.
Fixes #2550
Test plan
---------
transactions.py only.
Regression test similar to test_tx_forward_around_epoch_boundary
would be hard due to chunk distribution complications.
=> fix(client): fix tx forwarding regression

chain/client/src/client.rs
#2524 extracted `get_next_epoch_id_if_at_boundary` from
`possibly_forward_tx_to_next_epoch`, but missed some code.
Fixes #2585
Test plan
---------
transactions.py shouldn't have stacktrace spam in the log
=> fix(client): fix get_next_epoch_id_if_at_boundary

chain/epoch_manager/src/lib.rs
=> fix: remove unnecessary print

chain/chain/src/chain.rs, chain/chain/src/store.rs
=> feat(GC): commit after each block GCed

runtime/runtime-standalone/src/lib.rs
Some things turn out to be more clear being utilized.
For example, after adding `produce_blocks(num)` it turned out that `produce_block` in a better name for `process_block` since it better reflects semantics of what it actually does. 
This branch accumulates  patches which are produced in the process of utilizing RuntimeStandalone.
=> [WIP] Patches for RuntimeStandalone

core/primitives/src/merkle.rs
=> refactor(primitives): remove debug output from merkle

chain/chain/src/chain.rs, chain/client/src/view_client.rs
Accidentally introduced this one in one of my recent PRs
=> fix: Reverting an accidental extra clone

.github/workflows/mac_binary.yml, Dockerfile, Makefile, scripts/binary-release.sh
Reverts nearprotocol/nearcore#2704
=> Revert "fix(script): fix release build fails of current nightly rust"

runtime/runtime-standalone/src/lib.rs
Previously, the Runtime expected to get the outcome in the next block, but it possible to get the outcome in later blocks instead of the immediate next block.
- verified that the fix addressed the issue where it was discovered
- CI
=> fix (Runtime): Wait for more blocks when looking for the outcome

test-utils/store-validator/src/lib.rs, test-utils/store-validator/src/validate.rs
Related to https://github.com/nearprotocol/nearcore/issues/2597.
According to https://github.com/nearprotocol/nearcore/issues/2699#issuecomment-633252514, we need to remove any checks dependent on `height_included` and replace them with another ones.
=> feat(store validator): block_chunks_exist function

core/chain-configs/src/lib.rs, core/primitives/src/transaction.rs, neard/res/genesis_config.json, scripts/migrations/18-exclude-debug-info-from-outcome-proof.py
Fixes https://github.com/nearprotocol/nearcore/issues/2584 
It's a protocol change. Please review if there is something missing.
=> fix(chain): Exclude debug info from ExecutionOutcome proof

chain/chain/src/store_validator.rs, chain/chain/src/store_validator/validate.rs, chain/chain/tests/gc.rs, chain/client/src/client_actor.rs, test-utils/store-validator/src/main.rs
- Includes #2808 (Execution limiting in Nightly validation)
- Checking validity of Blocks on the Canonical Chain
- Caching Misc data
- More conditions added
- Avoiding multiple deserializations
=> feat(Store Validator): Store Validator updates

chain/chain/src/store.rs
Fixing sanity test after introducing https://github.com/nearprotocol/nearcore/pull/2820
=> fix(test): test_clear_old_data_too_many_heights

Cargo.toml, chain/chain/src/store.rs, chain/chain/src/store_validator.rs, chain/chain/src/store_validator/validate.rs, core/primitives/src/utils.rs, core/store/Cargo.toml, core/store/src/trie/mod.rs, neard/Cargo.toml
According to @mikhailOK here: https://github.com/nearprotocol/nearcore/issues/2623#issuecomment-641826029
Test plan
---------
`sanity/skip_epoch.py` is not failing because of Storage Inconsistency.
=> feat(Store Validator): check ColTrieChanges

chain/chain/src/store_validator/validate.rs
Store validator update to make sure that both Tail and Chunk Tail should exist or absent.
=> feat(store validator): check tail + chunk_tail upd

neard/src/lib.rs
Spawn PeerManagerActor in its own thread since it can run concurrently with other actor in the system without any problem.
Test Plan
=======
- Check there is no regression
=> feat(thread): Run PeerManager in separate thread.

chain/chain/src/chain.rs, chain/client/src/view_client.rs, chain/client/tests/catching_up.rs, chain/client/tests/process_blocks.rs
Fixes https://github.com/nearprotocol/nearcore/issues/2884.
TEST PLAN
---------
CI + python tests `gc_sync_after_sync.py`, `gc_sync_after_sync.py swap_nodes`, `gc_after_sync.py`.
=> feat(State Sync): sync_hash is 1st epoch block + within last two epochs

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/chain/src/store_validator.rs, chain/chain/src/store_validator/validate.rs, core/primitives/src/syncing.rs, core/primitives/src/types.rs
For each State Header stored, there is a Block with same hash is available.
For each State Part stored, there is a State Header stored, and id of State Part is not greater than num_parts in Header.
=> feat(Store Validator): State Headers and State Parts validation

nightly/nightly.txt, pytest/lib/peer.py, pytest/tests/contracts/deploy_call_smart_contract.py, pytest/tests/contracts/gibberish.py
`deploy_call_smart_contract.py` and `gibberish.py` were failing because of the gas cost change in #2845.
=> fix(nightly): fix some nightly tests

chain/network/src/peer.rs, core/primitives/src/block_header.rs, core/primitives/src/test_utils.rs, core/primitives/src/version.rs, core/primitives/src/views.rs, neard/res/genesis_config.json, nightly/nightly.txt, pytest/tests/sanity/upgradable.py
Remove `chunks_included` from `BlockHeaderInnerRest` as it is not needed. Fixes #2877 
Test plan
---------
`upgradable.py` passes
=> test: test upgradability in production

chain/epoch_manager/src/lib.rs
Currently `get_validator_info` is hugely inefficient due to recalculation of the aggregator for every current validator. This potentially causes exorbitant rpc response time since each aggregator calculation is already expensive.
=> fix(rpc): fix inefficiency in get_validator_info

pytest/lib/messages/block.py, pytest/lib/proxy.py, pytest/tests/sanity/network_drop_package.py, pytest/tests/sanity/proxy_simple.py
Test plan
=======
Tests using python proxy should pass
=> Fix python proxy infrastructure

nightly/nayduck.py
Few additional functionalities:
1. If user wants to run only specific tests, he can create new file which includes only that tests. 
2. User can include test files in one another
3. User can specify how many times he wants to run some particular tests in the run. If first argument in line is a number, the test will run as many times as that number, otherwise just once. 
Example, user created uncommitted file test_file1, which contains:
pytest 1
pytest 2
./test_file2
10 pytest my_flaky_test
User can trigger the run with:
./nayduck.py -t test_file1
=> NayDuck. Additional functionality to request tests

Cargo.lock, Cargo.toml, chain/indexer/Cargo.toml, chain/indexer/README.md, chain/indexer/src/lib.rs, chain/telemetry/Cargo.toml, chain/telemetry/src/lib.rs, neard/Cargo.toml, neard/src/main.rs, tools/indexer/example/Cargo.toml, tools/indexer/example/src/configs.rs, tools/indexer/example/src/main.rs
* Expose `neard::init_configs` into NEAR Indexer. 
* Update `tools/indexer/example` and NEAR Indexer README according to changes.
=> feat(indexer): NEAR Indexer can init configs

pytest/tests/sanity/switch_node_key.py
`switch_node_key.py` was failing because the second node doesn't stop before the epoch change and would send an announcement with old key in the new epoch before it changes its node key. Fixes #3172.
Test plan
---------
run `switch_node_key.py` 50 times and observe no failure.
=> fix(test): switch_node_key

pytest/tests/sanity/db_migration.py
Deploy a contract, send some transactions before and after upgrade
Test plan
---------
N/A
=> test: add some tx to db migration test

chain/client/src/client_actor.rs, chain/client/src/lib.rs, chain/client/src/test_utils.rs, chain/client/src/view_client.rs, chain/network/tests/runner/mod.rs, neard/src/lib.rs
Adversarial tests broke after running multiple view client actors,
fix them.
Fixes #3137
Test plan
---------
wrong_sync_info.py
=> fix(tests): Fix adversarial tests with view client

nightly/nayduck.py
Adding info about user who triggered the run and type of the run to nayduck request
=> Adding info to nayduck request.

nightly/nayduck.py
If user is part of neaprotocol org, he can trigger NayDuck runs, otherwise it is forbidden.
=> Adding GitHub auth to NayDuck.

chain/chain/src/store_validator/validate.rs, core/store/src/trie/mod.rs
Enable the check in store-validator.
Fixes #2843
Test plan
---------
run tests with this check
=> fix(store): fix prev_state_root check

pytest/tests/adversarial/start_from_genesis.py
Fixes #3138
Make the test do adv_produce_blocks when the node is disconnected,
so it doesn't accidentally sync and produce blocks on top of main chain.
Also remove disabling header sync, because it disables sync in both
directions and prevents the correct node from getting malicious headers.
Test plan
---------
Run start_from_genesis.py in all modes many times
=> fix(test): fix start_from_genesis.py

chain/indexer/src/streamer/streamer.rs
Indexer streamer always fetches the chunks in the block struct, which are not necessarily the chunks included in the block. This causes problem because the streamer tries to pair the transaction with their outcomes and the outcomes are stored by block hash. Therefore if a block doesn't contain any new chunk the indexer will panic because it tries to pair transactions in the previous chunk with the empty set.
@frol @khorolets it is not clear how I can test this change. It seems that streamer is written in such a way that it is difficult to test anything. Have you considered using some trait to abstract `ViewClientAddr` which will make testing a bit easier?
Fixes #3370
=> fix(indexer): only fetch chunks that are included in the block

chain/chain/src/chain.rs, chain/client/tests/challenges.rs, chain/client/tests/process_blocks.rs, core/primitives/src/block.rs
Verify chunk header signatures when we process blocks.
Test plan
---------
manually tested with a change that alters chunk signatures
=> fix(chain): verify chunk header signature

core/primitives/src/version.rs, neard/res/genesis_config.json
#3302 changed the protocol but didn't update protocol version.
=> fix: update protocol version

nightly/tests_for_nayduck.txt, pytest/tests/sanity/block_chunk_signature.py
Make a proxy that invalidates chunk signatures in blocks, and check
that chain doesn't get built.
Test plan
---------
N/A
=> test: test for block chunk signatures

core/store/src/migrations.rs, core/store/src/migrations/v8_to_v9.rs
Don't discard the last batch.
If we haven't migrated anything yet, we don't need to bump
to 13.
Test plan
---------
no testing
=> fix(store): fix migrate 11 to 12

chain/jsonrpc/CHANGELOG.md
Docs is also needed: https://github.com/near/docs/issues/494
=> doc(jsonrpc): added a changelog entry about a new `EXPERIMENTAL_tx_status`

pytest/lib/cluster.py, pytest/tests/stress/stress.py
Added a few missed steps to make remote stress tests to work with NayDuck.
=> Enabling remote stress test run with nayduck

nightly/nightly.txt
Increase timeout for test_gc_after_state_sync
Test plan
---------
before: 10/30 timeout
after: 30/30 passed
=> fix(test): increase timeout

pytest/lib/cluster.py
config now has new value  'release', if True the binary is build with --release flag.
=> Adding ability to run release version on Preexisting cluster

pytest/tests/sanity/block_chunk_signature.py
Test was failing if first block was missed
Test plan
---------
run many times
=> fix(test): block_chunk_signature.py

pytest/tests/sanity/epoch_switches.py
Fixes #3443
Test plan
---------
run many times
=> fix(test): epoch_switches.py

Cargo.lock, chain/client/src/lib.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/indexer/CHANGELOG.md, chain/indexer/Cargo.toml, chain/indexer/src/lib.rs, chain/indexer/src/streamer/mod.rs, chain/indexer/src/streamer/streamer.rs
=> feat(indexer): Add receipts to execution outcome in streamer

chain/indexer/README.md
Add link to mainnet config.json
=> fix(indexer): Update README

chain/client/src/client.rs, pytest/tests/adversarial/malicious_chain.py
Don't crash on adv_produce_blocks.
Fixes #3322
Test plan
---------
malicious_chain.py
=> fix(test): fix adv_produce_blocks(false)

chain/client/src/view_client.rs
When we query a chunk through block hash or block height, we should return the chunk with chunk header included in the block in case the chunk stored in the storage is the same chunk but from a different fork and therefore with a different `height_included`.
=> fix(rpc): return the proper chunk header when querying through block

neard/src/migrations.rs
Fixes error in DB migration 12 to 13.
Test plan: applying migrations to old data.
=> fix(migrations): Use ShardChunkV1 in migration_12_to_13

chain/jsonrpc/src/lib.rs, chain/jsonrpc/src/metrics.rs
Simple monitoring to get info about errors.
=> feat(jsonrpc): Per method error tracking on prometheus

chain/jsonrpc/Cargo.toml, chain/jsonrpc/tests/rpc_query.rs, neard/Cargo.toml, neard/src/config.rs
Remove some useless tests and make sure that tests work with `--features nightly_protocol,nightly_protocol_features` enabled.
=> fix: nightly protocol feature tests

pytest/lib/branches.py, pytest/tests/sanity/upgradable.py
For NayDuck the test should not compile any binaries as part of the test.
=> Change upgradable test for NayDuck

Dockerfile, scripts/binary-release.sh, scripts/run_docker.sh
=> fix(Add neard to release scripts)

chain/rosetta-rpc/src/utils.rs
Without this fix fetching a genesis block on testnet results in JSON RPC and Rosetta RPC being unresponsive due to view-client being bombarded with the view account requests
=> fix(rosetta-rpc): Fixed aggressive data polling leading to view-client unavailability

runtime/near-vm-runner/src/cache.rs, runtime/near-vm-runner/tests/test_error_cases.rs, runtime/near-vm-runner/tests/test_utils/mod.rs
Distinguish deserialized errors and errors coming from deserialization itself.
=> Fix deserialization of cached error.

chain/network/src/peer_manager.rs, neard/tests/stake_nodes.rs
There is a potential rounding error in `test_inflation`. Fixed by following the exact same calculation done in reward calculator. Fixes #3723.
Test plan
---------
run the test many times
=> fix(test): fix test_inflation

Cargo.lock, Cargo.toml, chain/client/Cargo.toml, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/client/src/view_client.rs, chain/jsonrpc/Cargo.toml, chain/network/Cargo.toml, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/test_utils.rs, chain/telemetry/Cargo.toml, chain/telemetry/src/lib.rs, neard/Cargo.toml, neard/src/main.rs, tools/indexer/example/src/configs.rs, utils/near-performance-metrics-macros/Cargo.toml, utils/near-performance-metrics-macros/src/lib.rs, utils/near-performance-metrics/Cargo.toml, utils/near-performance-metrics/src/actix.rs, utils/near-performance-metrics/src/lib.rs, utils/near-performance-metrics/src/process.rs, utils/near-performance-metrics/src/stats.rs
Currently we don't measure how much time it takes to process messages in actors. In this PR we will add an option to print every minute CPU usage of every thread, and printing whenever execution time takes more than 50ms.
=> add performance metrics feature

test-utils/testlib/src/standard_evm_cases.rs, tests/test_cases_runtime.rs
=> expand the CryptoZombies tests

runtime/near-evm-runner/src/meta_parsing.rs, runtime/near-evm-runner/src/types.rs, runtime/near-evm-runner/tests/failures.rs
Unwrap that can lead to potential failure.
Test plan
---
Adding offending test
=> Fix a bug in meta call parsing

Cargo.lock, neard/Cargo.toml, utils/near-performance-metrics/Cargo.toml
=> fix memory_stats on mac

chain/client-primitives/src/types.rs, chain/client/src/view_client.rs, chain/indexer/src/streamer/fetchers.rs, chain/jsonrpc-primitives/src/types/mod.rs, chain/jsonrpc-primitives/src/types/receipts.rs, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs
Add `EXPERIMENTAL_receipt` jsonrpc method
Test for method is in progress
=> feat (jsonrpc): Add EXPERIMENTAL_receipt jsonrpc method

core/primitives/src/version.rs
Addresses circular dependency mentioned in #3893. Fixes #3893 
Test plan
---------
CI
=> fix: address circular dependency in PROTOCOL_FEATURE_MAPPING

chain/network/src/peer_manager.rs
Seems like this Resolver stuff is just ... unnecessary? It sounds like
it does DNS resolution (with its notoriously sync-only APO), but this
isn't needed in this case. addr is a `SocketAddr`, ie, a resolved IP.
=> refactor: remove roundabout way to connect to socket

chain/jsonrpc/src/lib.rs
=> feat(jsonrpc): Add timeout log for query method

Makefile
Tested on the pipeline: https://buildkite.com/nearprotocol/nearcore-release/builds/379#867d3eb7-8795-4e14-9848-48a21b501ea9
=> fix(buildkite): fix broken master build

pytest/lib/cluster.py
=> fix(tests): remove `Block Missing` error message from get_all_heights

pytest/tests/sanity/state_sync1.py, pytest/tests/sanity/validator_switch.py
Fixes #4051
Test plan
---------
validator_switch.py
=> fix(test): validator_switch.py

Cargo.lock, chain/chain/Cargo.toml, chain/chain/src/chain.rs, chain/chain/src/missing_chunks.rs, chain/chain/src/store.rs, chain/chain/src/store_validator.rs, chain/chain/src/test_utils.rs
tracing is a superset of log:
https://tracing.rs/tracing/#for-log-users
=> refactor: don't use both log and tracing in chain

runtime/near-vm-runner/src/tests/contract_preload.rs
=> refactor: fix one last usage of include_bytes

tools/indexer/example/src/main.rs
Test Plan:
```
sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/n/t/i/example (master)> cargo run -p indexer-example run
Compiling indexer-example v0.1.0 (/home/sandi/workspace/near/nearcore/tools/indexer/example)
Finished dev [unoptimized + debuginfo] target(s) in 34.21s
Running `/home/sandi/workspace/near/nearcore/target/debug/indexer-example run`
Mar 15 15:15:15.352  INFO indexer: Starting Streamer...
Mar 15 15:15:15.363  INFO stats: Server listening at ed25519:HumL9eo6ZHmNNkwmB6LpswH3YP7AA2RCjPR476LErS1i@0.0.0.0:24567
Mar 15 15:15:17.385  INFO indexer_example: #1 HNA6J8v6LHv6Ak3uD4X81GPS2sfvDgMHZhoy69AXJwkr Chunks: 0, Transactions: 0, Receipts: 0, ExecutionOutcomes: 0
Mar 15 15:15:18.401  INFO indexer_example: #2 5K2rKMqBUAua9eCA3uP46t3yntNZ8vbEFRLnBazBB6wH Chunks: 1, Transactions: 0, …
```
=> fix(example): Fixed the indexer SystemRunner to run

chain/network/src/peer_manager.rs, chain/network/src/routing.rs
In this PR we will simplify the logic, to make sure we compute routing graph at most once per second.
Opening PR again replacing #4099
=> recompute routing graph at most once a second

test-utils/testlib/src/node/process_node.rs
Fix the tests that run neard binary in nayduck.
Test plan
---------
the test works again
=> fix(test): fix test_rejoin

chain/jsonrpc/build_errors_schema.sh, pytest/empty-contract-rs/build.sh, runtime/near-evm-runner/tests/build.sh, runtime/near-vm-runner/tests/test-contract-rs/build.sh, runtime/runtime-params-estimator/compiler.sh, runtime/runtime-params-estimator/emu-cost/README.md, runtime/runtime-params-estimator/emu-cost/ci.sh, runtime/runtime-params-estimator/emu-cost/io_cost.sh, runtime/runtime-params-estimator/emu-cost/run.sh, runtime/runtime-params-estimator/estimate.sh, runtime/runtime-params-estimator/setup.sh, runtime/runtime-params-estimator/small-test-contract/build.sh, runtime/runtime-params-estimator/test-contract/build.sh, runtime/runtime/tests/tiny-contract-rs/build.sh, scripts/build_wasm.sh, scripts/install_precommit.sh, scripts/mac-release.sh, scripts/run_clippy.sh, scripts/run_docker.sh, scripts/setup_hooks.sh, scripts/test_nearlib.sh, scripts/waitonserver.sh
=> Switch all script to use /usr/bin/env bash as /bin/bash is not portable

runtime/near-vm-logic/src/gas_counter.rs
* remove unused pub
* put related code together
As side benefit, this fixes compilation error in `cargo test --features nightly_protocol,nightly_protocol_features,protocol_feature_evm --no-run`
=> refactor: code cleanup

core/primitives-core/src/profile.rs
RefCell incurs a runtime check for borrow/borrow_mut. For plain
counters, that's not needed, as we can use zero overhead Cell instead.
Pure refactoring, covered by existing tests
=> refactor: remove unnecessary runtime checks from ProfileData

utils/near-performance-metrics/src/process.rs, utils/near-performance-metrics/src/stats_enabled.rs
Pure refactoring, covered by existing tests.
=> refactor: simplify performance metrics code

chain/chain/src/chain.rs, core/primitives/src/block_header.rs, core/primitives/src/sharding.rs, core/primitives/src/version.rs, core/primitives/src/views.rs, runtime/runtime/src/actions.rs
closes #4171 
Pure reafactor, covered by existing tests.
=> refactor: simplify protocol feature checking API

CODEOWNERS
* add myself as a codeowner 
* fixup #4160 to re-install codeowners for the new crate.
=> Update contract runtime code owners

runtime/near-test-contracts/build.rs
Before, the error looked like
No such file or directory (os error 2)
Now, it is
command `“rustup” “target” “add” “wasm32-unknown-unknown”` failed to run: No such file or directory (os error 2)
This helps to debug issues like rustup not being present on the system.
The code in question is a part of an internal test suite, will be exercised by the existing CI
=> refactor: improve error reporting in the build script

scripts/migrations/107-2-revert-add-account-versioning.py
Previous version deletes account_id by mistake
=> Fix for account revert script

Cargo.lock, chain/chain/src/chain.rs, chain/indexer/CHANGELOG.md, chain/indexer/Cargo.toml, chain/indexer/src/lib.rs, chain/indexer/src/streamer/fetchers.rs, chain/indexer/src/streamer/mod.rs, chain/indexer/src/streamer/types.rs, chain/indexer/src/streamer/utils.rs, tools/indexer/example/src/main.rs
* Add IndexerShard structure
* Bump version to 0.9.0
* update CHANGELOG
Also I've updated `example-indexer` to keep it up to date and changed the commented example of `StreamerMessage` it was a bit outdated.
=> refactor(indexer): Update Indexer Framework 0.9.0 (IndexerShard)

neard/src/migrations.rs
Fixes #4258
Test plan
--------
CI
=> fix(migration): only apply 19->20 migration on mainnet

chain/telemetry/src/lib.rs
=> fix(telemetry) Decrease connection lifetime to remove stale connections

chain/indexer/src/streamer/mod.rs
* Fix the loop
* Limit the loop for 1000 blocks before panic
For a reference it will be changed in #4317
=> fix(indexer): Fix the logic in NEAR Indexer Framework loop over previous block

chain/jsonrpc/client/src/lib.rs
=> Increase JsonRpcClient payload receivable size to 100mb

Cargo.lock, chain/indexer/CHANGELOG.md, chain/indexer/Cargo.toml, chain/indexer/src/streamer/mod.rs
=> refactor(indexer): Optimize delayed local receipts tracking in Indexer Framework

docs/architecture.md
Add some information about vm runner in architecture.md
=> doc: add vm-runner to architecture.md

pytest/lib/utils.py, pytest/tests/contracts/deploy_call_smart_contract.py, pytest/tests/contracts/gibberish.py, pytest/tests/contracts/infinite_loops.py, pytest/tests/mocknet/sanity.py, pytest/tests/sandbox/patch_state.py, pytest/tests/sanity/backward_compatible.py, pytest/tests/sanity/concurrent_function_calls.py, pytest/tests/sanity/db_migration.py, pytest/tests/sanity/upgradable.py
Issue: https://github.com/near/nearcore/issues/4408
=> pytest: introduce helper `load_test_contract` function

pytest/tests/sanity/backward_compatible.py
Fix the backward compatible test that failed due to the new release. For more details, see #4464.
Test plan
---------
CI passes
=> fix(test): fix backward compat test

CONTRIBUTING.md
=> doc: add documentation on issue labels

CODEOWNERS
I still don't understand the relevant code in depth, so I'll delegate
harder reviews to olonho. I however feel confident enough to review
smaller changes to unblock PRs
=> chore: add matklad to params-estimator codeowners

pytest/lib/bridge.py
Issue: https://github.com/aurora-is-near/rainbow-bridge/issues/150
=> pytest: document why bridge checks for Go

nightly/nayduck.py
Issue: https://github.com/near/nayduck/issues/8
Issue: https://github.com/near/nearcore/issues/2736
=> nayduck: remove --run_type flag; it’s never used by anything

nightly/TODO-disabled-4552.txt, nightly/pytest-sanity.txt
Issue: https://github.com/near/nearcore/issues/4552
=> nightly: enable three of the passing tests

nightly/expensive.txt
Issue: https://github.com/near/nearcore/pull/4567
=> nightly: fix test_gc_after_state_sync test after recent test moves

pytest/lib/cluster.py
Use os.listdir rather than unnecessarily forking and calling find.
Furthermore, remove polling from the threads spinning up the nodes.
=> pytest: refactor cluster.start_cluster

pytest/lib/bridge.py
=> pytest: bridge: make sure rainbow-bridge repository is up to date

nearcore/src/runtime/mod.rs, nearcore/src/shard_tracker.rs
=> remove unused code in shard tracker: untrack_account and untrack_shard

nightly/README.md
Issue: https://github.com/near/nearcore/issues/2411
=> nightly: add a README

pytest/tests/runtime/fuzz.py
Issue: https://github.com/near/nearcore/issues/4550
=> pytest: fuzz: enable parallelism

pytest/README.md
Issue: https://github.com/near/nearcore/issues/2411
=> pytest: add a bit more detail to README.md

scripts/nayduck.py
Issue: https://github.com/near/nayduck/issues/16
=> NayDuck has it’s own domain now \o/

scripts/nayduck.py
Issue: https://github.com/near/nayduck/issues/16
=> nayduck: use correct URL when scheduling runs

core/chain-configs/src/lib.rs
=> refactor: remove dead code

chain/client/src/test_utils.rs
Don’t assume account ids of the clients use test{} format.  Instead,
introduce get_client_id method which allows getting account id used
when creating given client and use that to fetch the actual ids.  The
method will allow other users of TestEnv to query that information as
well without having to rely on any particular format TestEnv might use.
=> near_chain: don’t hard-code account ids in TestEnv

chain/client/src/test_utils.rs
Various documentation and minor code fixes to the TestEnv structure.
Also, make TestEnv::validators public so that tests can access it to
figure out the AccountIds used by the validators rather than having to
relay on a knowledge of the account ids format used by the builder.
Fixes: https://github.com/near/nearcore/issues/4835
=> Minor small improvements to TestEnv structure

test-utils/runtime-tester/README.md
Issue: https://github.com/near/nearcore/issues/4771
=> runtime-tester: update README.md after changes to Scenario

scripts/state/update_res.py
Firstly, use TemporaryDirectory to properly clean up the temporary
directory after the command runs.  Secondly, use context managers
more which is a better Python form.  It doesn’t really matetr for
this script but it’s a good thing to use.  Lastly, update some
minor wording, documentation, uses of hard-coded path in messages
etc.
=> scripts: minor updates to `update_res.py` script

scripts/mac-release.sh
@chefsale thanks for your help! Here is the same for macos.
=> feat: add tar files and sandbox to macos release

chain/network/src/routing.rs
Timeouts were set incorrectly during refactor.
=> Hotfix timeout set to ms instead of secs

nightly/expensive.txt
=> nightly: enable some of the currently-passing expensive tests

chain/network/src/peer.rs
=> chain: make debug panic a bit more verbose

test-utils/state-viewer/src/apply_chain_range.rs
Just remove some extra characters :)
=> refactor: simplify

chain/network/src/routing.rs, chain/network/tests/cache_edges.rs
We will add extra checks to make sure `RoutingTable` updates `Graph` properly. In addition I added documentation for `Graph`.
=> Add extra checks to `Graph` and more comments

CODEOWNERS
Add @mm-near and @yordanmadzhunkov to code owners for chain
=> chore: change codeowners for chain

runtime/near-vm-logic/src/gas_counter.rs
If during execution of a contract both prepaid gas and max burnt gas
limits were exceeded, the `GasCounter` would report `GasExceeded`
error.  This was purely based on which condition was checked first
and entirely accidental based on how the code was written.
Unfortunately, that’s exactly the opposite preference to what we did
in old code which preferred reporting `GasLimitExceeded` instead.
Change the code to match the old behaviour and thus avoid protocol
changes.
=> runtime: prefer reporting GasLimitExceeded

chain/network/src/utils.rs
Add missing comments to `utils.rs`
Related to https://github.com/near/nearcore/issues/5156
=> Add comments to utils.rs

core/store/src/db.rs
Use `ByteSize` for size constants in db.rs. We are currently using `ByteSize` in other places. Let's use it here as well.
=> Use bytesize for size constants in db.rs

chain/network/src/peer/rate_counter.rs
Add comments/refactor rate_counter.rs
We also need to fix a bug in RateCounter https://github.com/near/nearcore/issues/5226
Mentioned in https://github.com/near/nearcore/issues/5156
=> Add comments/refactor rate_counter.rs

CODEOWNERS
I delegate my owner-reviews to those who are more in touch with the specific subsystems than I do today.
=> chore: Reduced @frol's code ownership

chain/client/src/client_actor.rs
Rename OldDuration to chrono::Duration
=> refactor: Rename OldDuration to chrono::Duration

core/account-id/src/lib.rs, utils/near-performance-metrics/src/stats_enabled.rs
Refactor `near-performance-metrics` based on #5412 feedback from @matklad.
=> re: Refactor  `near-performance-metrics`  based on #5412

chain/network/src/peer/codec.rs
Let's add comments to what `is_forward_tx` does.
Also refactor the code to be more readable.
=> Figure out what does `near-network::...::codec::is_forward_tx` do

chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/route_back_cache.rs, chain/network/src/routing/routing.rs
This reverts commit c34ea39d2315a977f4882e4d280649bdbaee05bd.
This reverts the PR that caused #5442
=> Revert "Add extra logs to investigate issues (#5192)"

chain/client/src/chunks_delay_tracker.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/info.rs, chain/client/src/sync.rs, chain/client/src/view_client.rs, chain/client/tests/bug_repros.rs, chain/client/tests/catching_up.rs, chain/client/tests/consensus.rs, chain/client/tests/cross_shard_tx.rs, chain/client/tests/query_client.rs, docs/style.md
Fix grouping dependencies in `chain/client`.
=> refactor: Reorganize imports in `chain/client`

chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/edge_verifier_actor.rs, chain/network/src/routing/routing_table_actor.rs, chain/network/src/types.rs
Document methods as requires in https://github.com/near/nearcore/pull/5230#discussion_r754603985 https://github.com/near/nearcore/pull/5230#discussion_r754604357
=> re: Document `EdgeVerifierActor` pt1

chain/network/src/peer_manager/peer_manager_actor.rs
Currently `PeerManagerActor` uses triggers various tasks. In order to make triggers more readable, let's put their intervals inside arguments.
For example:
```
self.monitor_peer_stats_trigger(ctx, self.config.peer_stats_period);
self.broadcast_edges_trigger(ctx, BROADCAST_EDGES_INTERVAL);
self.update_routing_table_trigger(ctx, UPDATE_ROUTING_TABLE_INTERVAL);
```
=> re: Refactor triggers in `PeerManagerActor`

nightly/README.md, nightly/fuzzing.txt, scripts/check_pytests.py
Issue: https://github.com/near/nearcore/issues/3186
Issue: https://github.com/near/nearcore/issues/4726
=> nightly: document --skip-build test flag plus some other minor updates

nearcore/src/config.rs
The download_file function does not use any of the Actix features so
enabling it is unnecessary.  A less complex and heavy-handed solution
is to set up a Tokio runtime so do that.
Issue: https://github.com/near/nearcore/issues/4951
=> nearcore: don’t bring in Actix when Tokio is enough while dling a file

scripts/nayduck.py
Let's add `--dry-run` option to `nayduck.py`. This will allow us to see which tests would run in nay-duck, without actually running them.
```
>>>  python3 ./scripts/nayduck.py --dry-run | grep integration | head
expensive integration-tests test_catchup test_catchup
expensive integration-tests test_catchup test_catchup --features nightly_protocol,nightly_protocol_features
expensive integration-tests standard_cases rpc::test::test_access_key_smart_contract_testnet
expensive integration-tests standard_cases rpc::test::test_access_key_smart_contract_testnet --features nightly_protocol,nightly_protocol_features
expensive integration-tests standard_cases rpc::test::test_access_key_smart_contract_testnet
expensive integration-tests standard_cases rpc::test::test_access_key_smart_contract_testnet …
```
=> feat: Add `--dry-run/-d` optional argument to `nayduck.py`

core/account-id/src/errors.rs, core/account-id/src/lib.rs
Merges into https://github.com/near/nearcore/pull/5665
Context: https://github.com/near/nearcore/pull/5665#discussion_r763005759
=> feat: struct variants for account-id error-kinds

chain/chain/src/chain.rs
Remove not needed ` -> ()` in `near-chain`.
See https://github.com/near/nearcore/pull/5571
=> re: `near-chain` Remove not needed ` -> ()`

chain/network/src/routing/routing_table_actor.rs
This should improve performance in our code base.
=> feat: Remove redundant `clone()`

docs/network.md
-  Database
See https://github.com/near/nearcore/issues/5156
=> doc: Add `near-network` reference level documentation `Database`

.buildkite/pipeline.yml
Reduce CI build time, by splitting `integration-tests` and the rest.
=> feat: Reduce CI build time to 12m.

chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
Hit this while debugging #5565
=> test: more informative failure message

Cargo.lock, utils/near-rate-limiter/Cargo.toml, utils/near-rate-limiter/src/framed_read.rs
Lets add tests to `ThrottledFramedRead`.
For, some reason, the test times out. Any ideas?
=> feat: Add test to `ThrottledFramedRead`

nightly/fuzzing.txt
Issue: https://github.com/near/nearcore/issues/5859
=> nightly: disable broken fuzz test

Cargo.lock, chain/indexer/Cargo.toml, chain/indexer/src/lib.rs, core/chain-configs/Cargo.toml, core/chain-configs/src/genesis_config.rs, nearcore/Cargo.toml, nearcore/src/config.rs, neard/src/cli.rs, runtime/runtime-params-estimator/src/costs_to_runtime_config.rs, runtime/runtime-params-estimator/src/main.rs, tools/indexer/example/Cargo.toml, tools/indexer/example/src/configs.rs, tools/indexer/example/src/main.rs, tools/restaked/src/main.rs
Indexer doesn't have a good output, in case input `--download-genesis` argument is missing.
Let's improve it.
=> Feature: Improve error output for indexer in case `--download-genesis` flag is missing

chain/client/src/client_actor.rs
`AnnounceAccount` code can be inlined, and it will be much easier to read what's going on.
=> re: Simplify `AnnounceAccount`

chain/network/benches/graph.rs, chain/network/benches/routing_table_actor.rs, chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/routing.rs
There are a couple of improvements we can make in `near-network` to improve code quality.
=> re: continue refactoring `near-network`

chain/network/src/peer_manager/peer_manager_actor.rs
The logic in computing `monitor_peers_trigger` is too complicated.
This PR rewrites logic, to an equivalent logic, that's easier to comprehend.
We can have a discussion, whenever this logic makes sense, but that should be another PR.
TODO:
=> re: Rewrite `monitor_peers_trigger` in a cleaner way

chain/network/src/peer_manager/peer_manager_actor.rs
In order to make reading `PeerManagerActor` easier, let's order all code into a few groups:
- ActivePeer
- AdvHelper
- IncomingCrutch
- PeerManagerActor
Work related to https://github.com/near/nearcore/issues/5156 to document `near-network`, and also make it more readable.
=> re: Reorder methods in `peer_manager_actor.rs`

runtime/near-vm-runner/src/wasmer2_runner.rs
QEMU with the TCG plugin does not support running AVX instructions and
makes it impossible to set the CPUID flag. This fails wasmer's CPU
feature checks when the default (host's) Target is used.
We already have a work-around for this kind of issue in place – the
`no_cpu_compatibility_checks` feature flag. Here we manually construct a
known-good target when this flag is enabled so that the param estimator
can run (so long as it does not actually invoke any NaN
canonicalization…)
cc @ekleog
=> Manually set the target for wasmer Singlepass

nightly/pytest-sanity.txt
Issue: https://github.com/near/nearcore/issues/6021
=> nighthly: disable broken `routing_table_sync.py` test

integration-tests/src/tests/client/chunks_management.rs, integration-tests/src/tests/client/process_blocks.rs, integration-tests/src/tests/nearcore/rpc_error_structs.rs, integration-tests/src/tests/nearcore/rpc_nodes.rs, integration-tests/src/tests/nearcore/run_nodes.rs, integration-tests/src/tests/nearcore/stake_nodes.rs, integration-tests/src/tests/nearcore/sync_nodes.rs, integration-tests/src/tests/nearcore/sync_state_nodes.rs, integration-tests/src/tests/nearcore/track_shards.rs, nightly/expensive.txt
Issue: https://github.com/near/nearcore/issues/4490
=> Move tests taking over 60 s to nightly

Makefile
the neard-debug target doesn't exist, so "make debug" currently fails
=> fix debug make target

runtime/near-vm-runner/src/cache.rs, runtime/near-vm-runner/src/preload.rs
I wanted to utilize the features here to disable and not deal with
wasmer0 in some experiments, but was surprised to find out the code
simply does not compile if the feature is disabled.
=> make near-vm-runner build /w --no-default-features

pytest/lib/branches.py
`git rev-parse --symbolic-full-name HEAD` returns HEAD when on
detached head.  Since HEAD does not relate to specific commit, it
cannot be used to track previous checked-out commit.  When on detached
head, we want to get the commit sha instead.  Unfortunately, there’s
no single git command which gets us that but combination of `git
symbolic-ref` and `git rev-parse` can make that work.
=> pytest: improve getting current branch name

Cargo.lock, runtime/near-vm-runner-standalone/Cargo.toml, runtime/runtime-params-estimator/Cargo.toml, test-utils/runtime-tester/Cargo.toml
There are a few unused dependencies, which should be removed from runtime.
=> re: Remove unused dependencies from runtime

pytest/lib/cluster.py
Without knowing how the script works it is pretty hard to investigate
issues when there is no output and it is not obivious how to run the
command!
Hopefully these changes help a little. They helped me, at least.
=> pytest: print more information about nodes

pytest/lib/branches.py
=> pytest: ensure branch is always reset

chain/client/src/client_actor.rs, chain/network/src/peer_manager/peer_manager_actor.rs
While reading `client-actor` code I noticed that some code improvements can be made. We can improve code quality / optimize code by doing `clone()` in a smarter way.
=> re: chore: Refactor `client-actor` code

Cargo.lock, deny.toml, runtime/near-vm-runner/Cargo.toml, runtime/near-vm-runner/src/imports.rs, runtime/near-vm-runner/src/tests/runtime_errors.rs, runtime/near-vm-runner/src/wasmtime_runner.rs, runtime/runtime-params-estimator/Cargo.toml
Hacky version of #6127, as per https://near.zulipchat.com/#narrow/stream/295306-nearinc.2Fcontract-runtime/topic/wasmtime.20upgrade
Hopefully we can rekindle #6096 after this lands to eliminate the need for unsafe code :)
=> debt: upgrade wasmtime to latest version

chain/network/src/peer_manager/peer_manager_actor.rs
We can replace some `send` method calls with `do_send`, and therefore simplify the code, that will allow us reducing the need to use `actix::spawn` as a side effect.
=> re: `near-network` Remove usage of `actix::spawn` when it's not necessary

chain/rosetta-rpc/src/adapters/transactions.rs
Move converting account update and account delete changes into list of
operations into their own functions thus significantly shortening the
convert_block_changes_to_transactions function.
This is a pure refactoring with mostly just code moving around.  This
causes no changes to behaviour of the code.
=> chain: rosetta: refactor convert_block_changes_to_transactions function

chain/network/src/routing/routing_table_view.rs
Visibility level of functions inside `routing_table_view` can be decreased, and some dead code can be deleted in `routing_table_view`.
=> re: chore: `routing_table_view` Change visibility to pub(crate) / remove dead code

chain/network/src/routing/routing_table_actor.rs
`prune_unreachable_edges_and_save_to_db` can be rewritten to a cleaner functional style. We can get rid of 2 variables as a side effect.
Made on top of https://github.com/near/nearcore/pull/6145
=> re:  rewrite `prune_unreachable_edges_and_save_to_db` to functional style pt2

chain/client/src/info.rs
Just moving some code around and very minor refactoring.
Most notably, introduce `paint` function which takes care of deciding
whether text should be colourised or not.  With it, there is no longer
need for two different `info!` invocations.
Furthermore, make it handle `None` values for information pieces which
are missing.  With including spaces at the beginning of each log entry
this fixes an issue of double spaces when some information are missing.
Issue: https://github.com/near/nearcore/issues/2454
=> chain: refactor status line formatting

tools/state-viewer/src/apply_chain_range.rs
Adding more debug information to our state viewer tool.
Example:
Processed 200 blocks, 1.0906 blocks per second (0 skipped), 276.00 secs remaining 0 empty blocks 956.98 avg gas per non-empty block
Processed 300 blocks, 1.4386 blocks per second (0 skipped), 139.72 secs remaining 0 empty blocks 827.99 avg gas per non-empty block
Processed 400 blocks, 1.6076 blocks per second (0 skipped), 62.83 secs remaining 0 empty blocks 740.46 avg gas per non-empty block
=> Adding more debug information (like avg gas) to apply_chain)

chain/chain/src/chain.rs
This could help us investigate Issue #6317
=> Log to WARN information about invalid chunk state and invalid challenges

Cargo.lock, core/primitives/src/version.rs, deny.toml, neard/Cargo.toml, neard/build.rs, neard/src/main.rs
Fixes: https://github.com/near/nearcore/issues/5979
=> client: add rustc_version to --version page and /status response

runtime/runtime-params-estimator/src/main.rs
=> fix(params-estimator): Use correct docker tag

chain/chain/src/chain.rs
This change was included in 1.24.0 but I forgot to merge it on master
=> change NUM_ORPHAN_ANCESTORS_CHECK to 3

chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/tests/random_epochs.rs, nearcore/tests/economics.rs, runtime/near-vm-logic/src/tests/fixtures.rs, runtime/near-vm-logic/src/tests/helpers.rs, runtime/near-vm-logic/src/tests/vm_logic_builder.rs, runtime/runtime-params-estimator/src/testbed.rs
=> chore(tests): remove dead code

Cargo.lock, Cargo.toml, tools/chainsync-loadtest/Cargo.toml, tools/chainsync-loadtest/README.md, tools/chainsync-loadtest/src/concurrency/ctx.rs, tools/chainsync-loadtest/src/concurrency/ctx_test.rs, tools/chainsync-loadtest/src/concurrency/mod.rs, tools/chainsync-loadtest/src/concurrency/once.rs, tools/chainsync-loadtest/src/concurrency/rate_limiter.rs, tools/chainsync-loadtest/src/concurrency/scope.rs, tools/chainsync-loadtest/src/concurrency/scope_test.rs, tools/chainsync-loadtest/src/concurrency/weak_map.rs, tools/chainsync-loadtest/src/fetch_chain.rs, tools/chainsync-loadtest/src/main.rs, tools/chainsync-loadtest/src/network.rs
Implemented a loadtest tool which fetches a fragment of the chain at a given QPS.
Additionally implemented a bunch of structured concurrency primitives.
=> a loadtest tool which fetches a fragment of the chain

.buildkite/pipeline.yml, Cargo.lock, tools/state-viewer/Cargo.toml, tools/state-viewer/src/cli.rs, tools/state-viewer/src/commands.rs, tools/state-viewer/src/state_dump.rs
Port vgrichina code for dumping account info and contract data
into redis.
Also add test for checking if the redis dump works.
=> feat(fast-near) View state dump to redis

chain/chain/src/chain.rs, chain/client/src/client.rs, chain/client/src/sync.rs
See issue https://github.com/near/nearcore/issues/6266#issuecomment-1063517980
=> add some debug lines for debugging why blocks catchup for archival nodes takes too long 

core/store/src/db.rs
Using cfg!() expression is more readable as it fits with the normal
if-else syntax and also avoids having to use conditional uses which
further removes noise from the code.  Prefer it.
=> db: prefer cfg!() expression to cfg attribute

pytest/tests/sanity/block_sync_archival.py
Specify max_block_production_delay in addition to min delay in node’s
configuration in block_sync_archival.py test.  This speeds up
generation of blocks by the node and shortens the test’s run time.
=> pytest: reduce block production delay in block_sync_archival.py

chain/chain/src/store_validator.rs, chain/chain/src/store_validator/validate.rs, core/store/src/db.rs, core/store/src/lib.rs
Instead of manually setting value of NUM_COLS constant, use EnumCount
trait which can be automatically derived for DBCol.
=> db: use EnumCount instead of NUM_COLS

runtime/runtime-params-estimator/src/config.rs, runtime/runtime-params-estimator/src/gas_cost.rs, runtime/runtime-params-estimator/src/lib.rs, runtime/runtime-params-estimator/src/main.rs
Optional JSON output of estimation results for scripts to consume
=> feature(params-estimator): JSON output

neard/src/cli.rs
Issue: https://github.com/near/nearcore/issues/6119
=> neard: document ‘recompress-storage’ command more

chain/rosetta-rpc/src/adapters/mod.rs, pytest/tests/sanity/rosetta.py
Because we are using a hash set when identifying accounts which were
changed in a block, the order in which change events are collected is
nondeterministic.  This means that operations in transactions which
cause the changes in nondeterministic order as well.
This is an issue because we assign operation indexes based position in
the list.  This means, that querying the same block multiple times may
result in transactions whose operation indexing changes.
To make sure that doesn’t happen and operation indexes remain
consistent store accounts in a vector in the same order the view
client returns them.
=> chain: rosetta: guarantee order of operations in transactions

Cargo.lock, runtime/near-vm-runner/fuzz/Cargo.toml
This is mostly to update wasm-encoder
=> chore: update wasm-smith

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/client_actor.rs, core/primitives/src/lib.rs, core/primitives/src/state_part.rs, core/store/src/trie/split_state.rs, core/store/src/trie/state_parts.rs, integration-tests/src/mock_network/setup.rs, integration-tests/src/tests/client/process_blocks.rs, nearcore/src/runtime/mod.rs
Basically this is just an updated version of https://github.com/near/nearcore/pull/5731 which is not updated for several months.
=> refactor: combine part_id+num_parts into PartId struct #5731

Cargo.lock, nearcore/Cargo.toml, nearcore/src/config.rs
https://github.com/near/nearcore/issues/6436
@mina86
=> feat(serde): show missed de fields in debug mode #6436

runtime/near-vm-errors/src/lib.rs, runtime/near-vm-logic/src/alt_bn128.rs, runtime/near-vm-logic/src/logic.rs
=> Alt-bn128 audit fixes and tests

runtime/near-vm-logic/src/tests/gas_counter.rs
We needed this for historical reasons, but now we can get without it just fine.
=> refactor: remove needless closure

debug_scripts/request_chain_info.py, scripts/formatting
With ‘debug_scripts’ added to ‘scripts/formatting’ the style will be
enforced for all future Python code in that directory.
=> debug_scripts: enforce Python style

chain/epoch_manager/src/lib.rs
Mostly just removing needless clones here and there!
=> refactor: minor cleanups to EpochManager

chain/epoch_manager/src/lib.rs, core/primitives/src/epoch_manager.rs, nearcore/src/runtime/mod.rs
=> feat(shardConfig): remove `impl From<EpochConfig> for ShardConfig`

Cargo.lock, chain/chain/Cargo.toml, chain/chunks/Cargo.toml, chain/client-primitives/Cargo.toml, chain/client/Cargo.toml, chain/indexer/Cargo.toml, chain/jsonrpc-primitives/Cargo.toml, chain/jsonrpc/Cargo.toml, chain/jsonrpc/fuzz/Cargo.toml, chain/jsonrpc/jsonrpc-tests/Cargo.toml, chain/network-primitives/Cargo.toml, chain/network/Cargo.toml, chain/rosetta-rpc/Cargo.toml, chain/telemetry/Cargo.toml, deny.toml, integration-tests/Cargo.toml, nearcore/Cargo.toml, neard/Cargo.toml, tools/chainsync-loadtest/Cargo.toml, tools/indexer/example/Cargo.toml, utils/near-performance-metrics/Cargo.toml, utils/near-rate-limiter/Cargo.toml
Nothing particularly interesting in the changelog:
https://github.com/actix/actix/blob/master/actix/CHANGES.md#0130---2022-03-01
=> chore: upgrade actix to 0.13.0

chain/chain/src/chain.rs
The near_block_height_head and near_header_head_height metrics are
only updated when new block / header is successfully received.  This
means that if a node is syncing headers (and thus not getting any new
blocks) the former metric is not set.  Similarly, if the node takes
a long time to get its first new header or block the corresponding
metric is not set.  This result in the metric not being published.
Initialise the two metrics when Chain is created so that as soon as
node starts up the counters can be monitored.
Fixes: https://github.com/near/nearcore/issues/6409
=> chain: initialise block and header head height metrics at startup

pytest/tests/sanity/gc_sync_after_sync.py
The test had a flaky failure.
Couldn't reproduce and couldn't figure out what exactly failed without additional info.
=> Add debug information to gc_sync_after_sync.py

integration-tests/src/tests/client/process_blocks.rs
This test currently fails when the protocol upgrade schedule for version 53
is set to the future, as it only changes one block's protocol version (at the
beginning of an epoch). The last block produced in the epoch is what will be
taken into account in voting, and it won't take effect for 2 epochs, so fix that
by producing some blocks with the new version advertised for a couple epochs before
proceeding.
=> integration-tests: fix test_deploy_cost_increased() with set upgrade schedule

integration-tests/src/tests/client/process_blocks.rs
See https://github.com/near/nearcore/pull/6649, as the changes here
are basically copy-pasted from there. This test does the same protocol
upgrading, and also currently fails when the new upgrade schedule is
set to a time in the future.
=> integration-tests: fix lower_storage_key_limit_test protocol upgrading

Cargo.lock, deny.toml, runtime/near-test-contracts/Cargo.toml, runtime/near-test-contracts/src/lib.rs, runtime/near-vm-runner/Cargo.toml, runtime/near-vm-runner/fuzz/Cargo.toml, runtime/near-vm-runner/src/tests/cache.rs, runtime/near-vm-runner/src/wasmer2_runner.rs
The basic simple contract does not really cover all that much
=> test artifact stability with more contracts

chain/chain/src/store.rs, core/store/src/lib.rs
=> test: fix regressed nightly test

chain/chain/src/chain.rs
=> move the saving of block_extra to after apply_chunks

chain/client/src/client.rs
=> Reduce verbosity of transaction receiving/forwarding.

Cargo.lock, chain/chain-primitives/Cargo.toml, chain/chain-primitives/src/error.rs, chain/chain-primitives/src/lib.rs, chain/chain/src/chain.rs, chain/chain/src/lib.rs, chain/chain/src/store.rs, chain/chain/src/test_utils.rs, chain/chain/src/tests/challenges.rs, chain/chain/src/tests/simple_chain.rs, chain/chain/src/validate.rs, chain/chunks/src/lib.rs, chain/client-primitives/src/types.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/client/src/view_client.rs, integration-tests/src/tests/client/challenges.rs, integration-tests/src/tests/client/process_blocks.rs, integration-tests/src/tests/client/sharding_upgrade.rs, nearcore/src/runtime/mod.rs
=> refactor: simplify chain::Error

chain/client/src/info.rs
Use the same code for formatting numbers in human-readable format.
The algorithm will show three significant digits of the number and
use appropriate k, M, G etc. prefixes.
Use SI prefixes for all the numbers.  It makes no sense to use binary
prefixes for bandwidth.  An argument could be made that binary prefixes
work better with memory (since RAM sticks have sizes which are powers
of two) but using decimal prefixes everywhere simplifies the code.
Issue: https://github.com/near/nearcore/issues/2454
=> chain: normalise number formatting in status line

CONTRIBUTING.md
And throw in some advise on making builds speedier/less memory
intensive.
=> doc: describe the required toolchain version

tools/state-viewer/src/state_dump.rs
closes https://github.com/near/nearcore/issues/6677
See for motivation for plain removal
https://github.com/near/nearcore/issues/6677#issuecomment-1111522775
=> fix: remove test that fails locally

chain/client/src/client_actor.rs
I've noticed that `check_triggers` accounts for a high precentage of
DEBUG-level logging. This is because we check very frequently, but often
the check is no-op, as we don't have to run any triggers. So remove the
span from checking, and make sure that we always span the actual
triggers themselves.
That is, this should now log only when the trigger is executed
=> fix: reduce spammy logging

chain/chain/src/chain.rs
Just a mechanical simplification of syntax
=> refactor: use ?

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs, integration-tests/src/genesis_helpers.rs, tools/state-viewer/src/apply_chain_range.rs, tools/state-viewer/src/apply_chunk.rs, tools/state-viewer/src/commands.rs
Cleanup post https://github.com/near/nearcore/pull/6811
=> refactor: make some of ChainStore methods &

Cargo.lock, runtime/near-vm-runner/Cargo.toml, runtime/near-vm-runner/src/wasmer2_runner.rs
2.4.0 includes some API changes that make the calling code tad-a-bit cleaner.
=> Update to wasmer 2.4.0

integration-tests/src/tests/network/peer_handshake.rs
Model PR for https://github.com/near/nearcore/issues/6933
=> refactor: use simpler wait_or_timeout

Cargo.lock, tools/state-viewer/Cargo.toml, tools/state-viewer/src/cli.rs, tools/state-viewer/src/commands.rs, tools/state-viewer/src/state_dump.rs
This PR adds account ID selection as part of the command line arguments of state dump.
[CP-86](https://nearinc.atlassian.net/browse/CP-86)
- Unit testing
- @mzhangmzz 
- @mm-near
=> state dump with account selection

core/store/src/columns.rs
Eliminate custom col_set function (which creates a mapping from all
DBCol variants to a boolean value) in favour of using match statement
in methods which used those mappings.
The main motivation for this is to get rid of the dependency on values
assigned to DBCol variants and the strum::EnumCount derive.
The problem is that strum::EnumCount defines COUNT constant which
returns number of variants while what we actually want is the value
one greater than the highest value of any variant.  This is currently
the same, but as we might want to delete deprecated variants those two
numbers would diverge.
=> store: use match instead of col_set for DBCol::if_foo methods

chain/chain/src/store.rs
Also avoids one extra clone of the hash set.
=> refactor: use entry API more efficiently

chain/chain/src/store.rs
We don't seem to use caches for these fields. We might want to start
doing that at some point, but, as this didn't happen for quite a while,
it's less confusing to just remove the code.
cc https://near.zulipchat.com/#narrow/stream/322379-pagoda.2Fcore.2Fconcurrent-client/topic/Unused.20caches.20in.20ChainStore
=> refactor: drop unused fields

Cargo.lock, chain/network-primitives/src/blacklist.rs, chain/network-primitives/src/config.rs, chain/network-primitives/src/config_json.rs, chain/network-primitives/src/lib.rs, chain/network-primitives/src/types.rs, chain/network/src/network_protocol/network.proto, chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/peer_manager/peer_store.rs, chain/network/src/peer_manager/peer_store_test.rs, chain/network/src/test_utils.rs, integration-tests/src/tests/network/infinite_loop.rs, integration-tests/src/tests/network/peer_handshake.rs, integration-tests/src/tests/network/peer_manager.rs, integration-tests/src/tests/network/runner.rs, integration-tests/src/tests/network/stress_network.rs, nearcore/Cargo.toml, nearcore/src/config.rs, nearcore/src/lib.rs, neard/src/cli.rs, tools/chainsync-loadtest/src/main.rs, tools/mock_node/benches/sync.rs, tools/mock_node/src/main.rs, tools/mock_node/src/setup.rs
[Announcing Validator IPs - design](https://docs.google.com/document/d/1RDd9ETfLQL_JfnEePmUPjkLvIxAtLV-c5AKWV8IMJEo/edit)
Added relevant protobuf message definitions (currently unused).
Added relevant fields to config.json (currently unused, not visible to the end users yet).
Refactored NetworkConfig - grouped together fields relevant to being a Validator.
Made RoutingTableAgent an implementation detail of the PeerManager.
=> proto and config for the Validator IP announcement

runtime/runtime-params-estimator/emu-cost/Dockerfile, runtime/runtime-params-estimator/src/main.rs
=> Update estimator to rustc 1.61.0

genesis-tools/genesis-populate/src/lib.rs, genesis-tools/genesis-populate/src/main.rs, genesis-tools/genesis-populate/src/state_dump.rs, nearcore/src/runtime/mod.rs, runtime/runtime-params-estimator/src/main.rs
closes https://github.com/near/nearcore/issues/4745
=> refactor: privatise NightshadeRuntime::new

chain/client-primitives/src/debug.rs, chain/client-primitives/src/lib.rs, chain/client-primitives/src/types.rs, chain/client/src/client_actor.rs, chain/client/src/debug.rs, chain/client/src/lib.rs, chain/jsonrpc-primitives/src/types/status.rs, chain/jsonrpc/src/api/status.rs, core/primitives/src/views.rs
There is no logic change - just moving things around.
=> Refactor: moving debug-related objects to separate debug.rs files
