README.md, core/primitives/Cargo.toml, core/primitives/src/hash.rs, node/runtime/src/lib.rs, node/service/Cargo.toml, node/service/src/lib.rs, node/service/src/rpc/api.rs, node/service/src/rpc/mod.rs, node/service/src/rpc/types.rs, scripts/rpc.py
fixes https://github.com/nearprotocol/nearcore/issues/92
i think this is a step in the right direction of https://github.com/nearprotocol/nearcore/issues/93 .. it would  be nice if the client could have these interfaces also, but that seems like it will require a bit more massaging.
note: this also fixes the breaking changes i made to the script you were seeing @ilblackdragon
=> rpc: make api semantics more clear

core/txflow/src/dag/mod.rs, core/txflow/src/dag/reporter.rs
Following up PR #61 
All requested changes at #61 were made.
1. Remove declaration of computed_signature
2. Store MisbehaviourReporter as a reference in the DAG
IMPORTANT: It doesn't work yet because txflow_task DAG usage needs an update.
=> Add Misbehaviour trait

.gitignore, core/beacon/Cargo.toml, core/beacon/src/authority.rs, core/beacon/src/lib.rs, core/beacon/src/types.rs, core/chain/src/lib.rs, core/primitives/src/types.rs, node/cli/src/chain_spec.rs, node/cli2/src/chain_spec.rs, node/cli2/src/lib.rs, node/client/src/lib.rs, node/network/src/lib.rs, node/runtime/src/chain_spec.rs, node/runtime/src/lib.rs, node/runtime/src/test_utils.rs, scripts/rpc.py
=> Finish initial Authority implementation

core/beacon/src/authority.rs, core/beacon/src/types.rs, core/chain/src/lib.rs, core/primitives/src/traits.rs, node/beacon-chain-handler/Cargo.toml, node/beacon-chain-handler/src/importer.rs, node/beacon-chain-handler/src/lib.rs, node/beacon-chain-handler/src/producer.rs, node/cli/Cargo.toml, node/cli/src/lib.rs, node/cli2/Cargo.toml, node/cli2/src/lib.rs, node/client/src/chain.rs, node/client/src/lib.rs, node/network/src/io.rs, node/network/src/network_handler.rs, node/network/src/protocol.rs, node/network/src/service.rs, node/network/src/test_utils.rs, node/service/src/lib.rs, node/service/src/produce_blocks.rs, node/service/src/test_utils.rs, test-utils/node/src/main.rs
In the original substrate code there are Mutex/RwLock/Arc around the following structs. After we copied some the code we deleted them and replaced runner with a single_thread runner. This however prevents us from using the network concurrently and also reduces flexibility on where we can spawn the network. We need this change so that we can send stuff to network from anywhere in our codebase.
At some point we have to revisit the whole design of the libp2p library and the fact that their network is one singleton with a lock.
=> Making network code more flexible

Cargo.toml, node/beacon-chain-handler/Cargo.toml, node/beacon-chain-handler/src/lib.rs, node/beacon-chain-handler/src/producer.rs, node/cli/Cargo.toml, node/cli/src/lib.rs, node/cli/src/test_utils.rs, node/rpc/src/api.rs, test-utils/devnet/Cargo.toml, test-utils/devnet/src/main.rs
fixes https://github.com/nearprotocol/nearcore/issues/153
basically does the same thing as https://github.com/nearprotocol/nearcore/pull/155 except for:
- doesn't sign transactions in RPC implementation
- doesn't move chainspec serde out of cli
- reuses `node_cli::start_service`. think we should just be able to pass in task generators/traits (for consensus, network, etc) rather than duplicating everything.
=> restore devnet functionality

core/txflow/src/dag/message/group.rs, core/txflow/src/dag/message/mod.rs, core/txflow/src/dag/mod.rs, core/txflow/src/dag/reporter.rs
Detecting forks: store the last message from each participant on the DAG, it must be the case that each new message from Alice must approve its previous last message stored otherwise its a fork.
=> Txflow fork detection

core/primitives/src/types.rs, core/shard/src/lib.rs, node/beacon-chain-handler/src/importer.rs, node/beacon-chain-handler/src/producer.rs, node/cli/src/test_utils.rs, node/runtime/src/ext.rs, node/runtime/src/lib.rs, node/runtime/src/test_utils.rs
Add Transaction enum to put transaction and receipt in one data type so that the order of transactions in a block can be preserved. Fixes https://github.com/nearprotocol/nearcore/issues/174
=> Put transaction and receipt together

README.md, core/storage/src/lib.rs, node/rpc/src/api.rs, node/rpc/src/types.rs, node/runtime/src/state_viewer.rs, scripts/rpc.py, tests/test_rpc_cli.rs
Fixes #212 allows to retrieve state of the current contract via RPC.
Useful for initial debugging and in future can be extended to query parts of the contract state (e.g. logs / events / notifications / etc).
=> State viewer

core/primitives/src/types.rs, node/rpc/src/api.rs, node/rpc/src/types.rs, node/runtime/src/lib.rs, scripts/rpc.py
Update schedule_function_call to execute on the contract's account instead of originator's account.
Also adding amount to function_call so you can attach money for the execution. E.g. pay for service.
=> Update schedule_function_call to execute on the contract's account

node/runtime/src/lib.rs
We prefix the storage with the contract's account to avoid name conflicts, but it was incorrectly using sender's account instead
=> Fix storage account prefix to be the actual contract

core/beacon/src/authority.rs, core/beacon/src/types.rs, core/primitives/src/signer.rs, core/primitives/src/traits.rs, node/beacon-chain-handler/src/authority_handler.rs, node/beacon-chain-handler/src/importer.rs, node/beacon-chain-handler/src/lib.rs, node/beacon-chain-handler/src/producer.rs, node/cli/src/chain_spec.rs, node/cli/src/lib.rs, node/cli/src/service.rs, node/network/src/protocol.rs, node/network/src/service.rs, node/network/src/test_utils.rs, node/network/tests/integration_test.rs, node/runtime/src/chain_spec.rs, node/runtime/src/lib.rs, node/runtime/src/test_utils.rs, scripts/run_clippy.sh
When a block is imported or produced, we send the authority information for the next block to consensus and network.
=> send authority info when discovers new block

core/primitives/src/hash.rs, core/primitives/src/signature.rs, core/shard/src/lib.rs, node/cli/src/service.rs, node/http/Cargo.toml, node/http/src/api.rs, node/http/src/lib.rs, node/http/src/server.rs, node/http/src/types.rs, scripts/rpc.py, tests/test_rpc_cli.rs
fixes https://github.com/nearprotocol/nearcore/issues/277
fixes https://github.com/nearprotocol/nearcore/issues/278
this adds the following calls:
- view_latest_beacon_block
- get_beacon_block_by_hash
- view_latest_shard_block
- get_shard_block_by_hash
this also:
- fixes CryptoHash deserialization.. the old implementation was not working for truncated values including the default hash
- adds a Signature struct that wraps the sodiumoxide signature as we do for PublicKey and SecretKey
=> add rpc block calls

core/wasm/runtest/src/lib.rs, core/wasm/src/ext.rs, core/wasm/src/resolver.rs, core/wasm/src/runtime.rs, node/runtime/src/ext.rs, tests/hello/assembly/main.near.ts, tests/hello/assembly/main.ts, tests/hello/assembly/near.ts
@ilblackdragon  looks like `storage_iter` doesn't work as expected.
I'm getting such output:
```
2019-01-23T09:18:08Z DEBUG node_http::api] Schedule function call transaction "test_contract"."setValue"
[2019-01-23T09:18:08Z DEBUG node_http::api] Received transaction SignedTransaction { body: FunctionCall(FunctionCallTransaction { nonce: 138, originator: alice.near, contract_id: test_contract, method_name: Ok("setValue"), args: ..., amount: 0 }), signature: C568ttsRdLBH33bcYQNJbiXFvoUAPS1xqyYdpbiNnWxH9k7C3n6g7jLQ71HNoYonNRf1NDjHebQSVjS2Afvsca1 }
[2019-01-23T09:18:08Z DEBUG consensus::adapters::transaction_to_payload] Received transaction! SignedTransaction(SignedTransaction { body: FunctionCall(FunctionCallTransaction { nonce: 138, originator: alice.near, contract_id: test_contract, …
```
=>  Fix runtime binding bugs for storage_iter

Cargo.lock, core/wasm/Cargo.toml, core/wasm/src/cache.rs, core/wasm/src/executor.rs, core/wasm/src/lib.rs, core/wasm/src/prepare.rs, core/wasm/src/runtime.rs, core/wasm/src/types.rs
- Standardize memory so we can initiate memory without code inspection
- Adding file cache that stores compiled code into temporary directory
Caveats:
- Disk Cache is insecure.
- It uses lazy static init, that might crash if temp dir is failed to create.
- Wasmer cache has one of the functions as unsafe. We should probably change this cache to be LRU memory cache. I'll explore it next.
- It also has assumption about config for execution being the same.
But this change improves WASM benchmarks from 93ms overhead to much less:
```
test runtime_send_money                 ... bench:     541,875 ns/iter (+/- 225,776)
test runtime_wasm_benchmark_10_reads    ... bench:   1,941,265 ns/iter (+/- 298,672)
test runtime_wasm_benchmark_sum_1000    ... bench:   1,877,210 ns/iter (+/- 502,444)
test …
```
=> Improving WASM instance spawn performance

Cargo.toml
Benchmarks before:
```
test runtime_send_money                 ... bench:     474,562 ns/iter (+/- 31,684)
test runtime_wasm_benchmark_10_reads    ... bench:   1,835,657 ns/iter (+/- 134,443)
test runtime_wasm_benchmark_sum_1000    ... bench:   1,709,746 ns/iter (+/- 95,359)
test runtime_wasm_benchmark_sum_1000000 ... bench:  22,743,437 ns/iter (+/- 406,030)
test runtime_wasm_set_value             ... bench:   1,688,506 ns/iter (+/- 158,844)
```
Benchmarks after:
```
test runtime_send_money                 ... bench:     470,033 ns/iter (+/- 15,350)
test runtime_wasm_benchmark_10_reads    ... bench:   1,743,149 ns/iter (+/- 102,474)
test runtime_wasm_benchmark_sum_1000    ... bench:   1,591,865 ns/iter (+/- 88,726)
test runtime_wasm_benchmark_sum_1000000 ... bench:  18,217,341 ns/iter …
```
=> Enable lto (link time optimizations) and set codegen-units to 1

.gitlab-ci.yml
this allows us to just point to a specific branch and grab this file rather than downloading rust + compiling everything from scratch via salt
=> add release devnet artifact to gitlab build

core/wasm/src/cache.rs, core/wasm/src/executor.rs, core/wasm/src/lib.rs, core/wasm/src/prepare.rs, core/wasm/src/types.rs, node/runtime/benches/bench.rs
Fixes #568 
Also adding a benchmark to try run some bad code.
Before this commit:
```
test runtime_send_money                 ... bench:     472,202 ns/iter (+/- 27,107)
test runtime_wasm_bad_code              ... bench:   4,042,358 ns/iter (+/- 269,702)
test runtime_wasm_benchmark_10_reads    ... bench:   1,441,188 ns/iter (+/- 168,624)
test runtime_wasm_benchmark_sum_1000    ... bench:   1,257,166 ns/iter (+/- 118,543)
test runtime_wasm_benchmark_sum_1000000 ... bench:  14,212,002 ns/iter (+/- 328,197)
test runtime_wasm_set_value             ... bench:   1,286,205 ns/iter (+/- 52,033)
```
After this commit:
```
test runtime_send_money                 ... bench:     473,913 ns/iter (+/- 42,013)
test runtime_wasm_bad_code              ... bench:     804,576 ns/iter (+/- 46,408)
test …
```
=> Update WASM cache to store Result instead

node/runtime/benches/bench.rs, tests/hello/assembly/main.near.ts, tests/hello/assembly/main.ts
Current WASM benchmarks:
```
test runtime_wasm_bad_code                  ... bench:     855,170 ns/iter (+/- 35,851)
test runtime_wasm_benchmark_10_reads_legacy ... bench:   1,473,611 ns/iter (+/- 75,770)
test runtime_wasm_benchmark_storage_100     ... bench:   2,460,959 ns/iter (+/- 371,112)
test runtime_wasm_benchmark_storage_1000    ... bench:  14,395,528 ns/iter (+/- 590,294)
test runtime_wasm_benchmark_sum_1000        ... bench:   1,365,750 ns/iter (+/- 121,627)
test runtime_wasm_benchmark_sum_1000000     ... bench:  14,090,552 ns/iter (+/- 626,896)
test runtime_wasm_set_value                 ... bench:   1,331,113 ns/iter (+/- 83,177)
```
=> Adding WASM storage benchmarks

core/nightshade/src/lib.rs
Error in CI:
```
error[E0603]: module `nightshade` is private
--> core/nightshade/benches/bench.rs:6:17
|
6 | use nightshade::nightshade::BareState;
|                 ^^^^^^^^^^
error: aborting due to previous error
```
=> Fix CI. Make it work for benches inside nightshade

Cargo.lock, core/chain/src/lib.rs, core/mempool/Cargo.toml, core/mempool/src/lib.rs, core/nightshade/src/fake_network.rs, core/storage/benches/trie_bench.rs, core/storage/src/storages/mod.rs, core/storage/src/storages/shard.rs, node/client/benches/client_bench.rs, node/client/docs/client.puml, node/client/docs/client_storage.puml, node/client/src/lib.rs, node/client/src/test_utils.rs, node/coroutines/src/producer.rs, node/http/src/api.rs, node/network/src/message.rs, node/network/src/protocol.rs, node/shard/Cargo.toml, node/shard/src/lib.rs
- Refactor shard chain to put `transaction_address` and `transaction_results` into `BlockChain`. 
- Rename `ShardBlockChain` to `ShardClient`
- Integrate mempool with ShardClient.
Todo: figure out the details for beacon chain transaction/receipt and beacon chain mempool.
=> Integrate mempool with shard chain

docker/Dockerfile, ops/k8s/run.yaml, ops/utils/build_and_run, ops/utils/requirements.txt
1) generates PeerId in python based on hash, rather than using chainspecbuilder tool
2) adds DNS to k8s run command, so that we can pass IP via cli until we have DNS support in network
=> ops: set up boot nodes in docker via new network

core/nightshade/src/nightshade.rs
The best proposal now is the block with higher hash, instead of authority with a higher ID. Block proposal uses lexicographical order, and field hash is now before field author.
This doesn't work long term because authorities might try to produce blocks with higher hashes and effectively pass its proposal (this is something we don't want). Workaround: randomly rotate validators, and use authority Id as tie-breaker before.
=> Change tie breaker for winning proposal.

core/storage/src/storages/mod.rs, core/storage/src/storages/shard.rs, node/shard/src/lib.rs, test-utils/keygen/src/main.rs
We current store the new receipts generated from shard blocks directly in `ShardClient`, which seems inappropriate. I moved them to `ShardChainStorage`.
=> Move receipts stored in shard client to storage

node/coroutines/src/client_task.rs, node/network/src/protocol.rs
Remove hardcoded block index in `network/protocol` and `client_task` to use most recent authority map.
=> Remove hardcoded block index

core/nightshade/src/nightshade.rs, core/primitives/benches/bls.rs, core/primitives/src/aggregate_signature.rs
Uncompressed signature decompresses in about 3us compared to 750us for compressed signature.
=> Add uncompressed encoding for BLS signatures

core/mempool/src/lib.rs, core/storage/src/storages/mod.rs, core/storage/src/storages/shard.rs, node/client/src/lib.rs, node/runtime/src/lib.rs, node/runtime/src/test_utils.rs, node/shard/Cargo.toml, node/shard/src/lib.rs, tests/test_alphanet.rs
Group transactions in mempool by account and order each group by nonce so that runtime does not reject some transactions. Also persist information about transaction nonces across blocks to not accept old transactions.
=> Order transactions in mempool by account and nonce

node/alphanet/src/lib.rs, node/client/src/lib.rs, node/client/src/test_utils.rs, node/consensus/src/passthrough.rs, node/coroutines/src/client_task.rs, node/http/src/api.rs, node/network/src/protocol.rs, node/shard/src/lib.rs
If we produce block X but there are blocks X+1, ... X+Y that we have already received through the announcements, then we should be able to progress to block X+Y.
=> Block production should be able to unlock pending blocks

node/client/src/lib.rs
Make get_missing_indices return missing indices rather than indices that
are present in pending_blocks.
This bug is what caused non-deterministic failures in the alphanet test.
The bug reproduces on losing some block announcement messages or
a race condition during node startup: simple test with a node starting
late won't catch it because of on_new_peer logic for fetching blocks.
=> Fix missing_indices

core/wasm/runtest/src/lib.rs, nearlib/near.js, nearlib/package.json, pynear/setup.py, pynear/src/near/pynear/lib.py, pynear/tests/integration/test_cli.py, tests/hello/assembly/main.ts, tests/hello/assembly/model.ts, tests/hello/package.json
Bump nearlib to 0.4.0 to work with new AS compiler that removes wrapped object with `"result"` key from returned result. See https://github.com/nearprotocol/assemblyscript/pull/26
Update tests to work with new result format.
=> Update nearlib and tests to use result JSON directly instead of a "result" key

.gitignore, node/network/src/lib.rs, node/network/src/proxy/benchmark.rs, tests/test_alphanet.rs
**DONT MERGE**
This branch will be merged with #735 after merging issues are resolved there. Right now some monitoring is performed on the network on test `test_4_10_multiple_nodes`, each message type is counted and logged in a file. To see results:
> `git checkout network-proxy-monitor`
Run `test_4_10_multiple_nodes`. This should create the file `monitor.log` in the root of the project.
> `cargo test --package nearcore --test test_alphanet test_4_10_multiple_nodes -- --exact`
Run in a separate terminal, from the root of the project, while the test is running
> `watch -n 1 tail -n 12 monitor.log`
(Or simply open `monitor.log`)
You should see something like this:
```
Instant { tv_sec: 13328, tv_nsec: 67098609 }
"Gossip": 1755
"Connected": 0
"Transaction": 0
"Receipt": 0
"BlockAnnounce": …
```
=> Add monitor

node/configs/src/authority.rs, node/configs/src/chain_spec.rs, node/configs/src/client.rs, node/configs/src/lib.rs, node/configs/src/network.rs
#807 Introduced a bug that incorrectly overrides the chainspec. `test_4_20_kill1` caught it (yay @mikhailOK ) and started failing, but I incorrectly attributed it to the flakiness (see #801 , cc @azban ) because the same integration test sometimes fails randomly due to flakiness, see failure before #807 was merged: https://gitlab.com/nearprotocol/nearcore/-/jobs/187118763 It is my fault, though, for not double checking.
=> Fix PoA chainspec being incorrectly overridden

Cargo.lock, Cargo.toml, core/nightshade/Cargo.toml, core/nightshade/src/nightshade_task.rs, node/alphanet/Cargo.toml, node/alphanet/src/lib.rs, node/consensus/Cargo.toml, node/consensus/src/passthrough.rs, node/coroutines/Cargo.toml, node/coroutines/src/client_task.rs, node/devnet/Cargo.toml, node/devnet/src/lib.rs, node/network/Cargo.toml, node/network/src/peer.rs, node/network/src/peer_manager.rs, node/network/src/protocol.rs, node/network/src/proxy/mod.rs, node/network/src/proxy/throttling.rs, node/tokio-utils/Cargo.toml, node/tokio-utils/src/lib.rs, test-utils/testlib/Cargo.toml, test-utils/testlib/src/alphanet_utils.rs, tests/test_alphanet_command_line.rs
Very hacky version:
- use tokio runtime shutdown_now to shutdown the node
- it removes all jobs from the queue, but doesn't wait for currently running jobs, and if they call tokio::spawn they panic
=> Make nodes shutdownable (hacky)

docker/scripts/run_alphanet, node/configs/src/chain_spec.rs, ops/deploy_alphanet.sh, ops/local_alphanet.sh, ops/reset_alphanet.sh, ops/update_alphanet.sh, ops/update_studio.sh
need to rebuild docker image, push new version, and update ops scripts
=> docker: fix typo in run alphanet script on chain spec generation path

node/client/src/lib.rs, node/coroutines/src/client_task.rs, node/tokio-utils/src/lib.rs, tests/test_alphanet.rs
Issue #817
The bug was that the main loop of ClientTask processes one event from
each channel at a time, and for the channel that receives partial BLS
signatures it meant that it drained it slower than it produced new
requests.
The workaround for now is to request signatures with a higher interval
(50 ms -> 500 ms).
Some additional changes:
- change log format to output nanoseconds
- cache your own BLS signature and don't recompute on each request
- make the requester of BLS signatures request from all authorities
instead of up to his own index
=> Fix alphanet with >4 nodes

test-utils/testlib/src/lib.rs, test-utils/testlib/src/sampler.rs, test-utils/testlib/src/transactions_executor.rs, test-utils/testlib/src/transactions_generator.rs
Adds the following features:
* Transactions generator -- can generate one transaction or an endless stream of transactions. With correct nonce;
* Transactions executor -- executes one transaction or a stream of transactions against a set of nodes. Can limit transactions by number and time. Can imitate network lag to produce load spikes;
* Sampler -- a set of functions to sample nodes that optimizes not for the runtime, but the number of expensive invocations to nodes.
=> Generating and executing transactions in bulk

Cargo.lock, core/mempool/src/lib.rs, node/alphanet/src/lib.rs, node/client/Cargo.toml, node/client/src/lib.rs, node/client/src/test_utils.rs, node/configs/src/chain_spec.rs, node/configs/src/client.rs, node/runtime/src/lib.rs, node/runtime/src/test_utils.rs, node/shard/Cargo.toml, node/shard/src/lib.rs, test-utils/testlib/src/node/mod.rs, test-utils/testlib/src/node/shard_client_node.rs, tests/test_alphanet.rs, tests/test_alphanet_command_line.rs, tests/test_alphanet_tps_regression.rs, tests/tests_custom_handler.rs
Limiting block size by limiting the size of transactions only. It is hard to limit the size of receipts because they come in blocks and if we try to limit the size of receipt blocks when producing them, we cannot send all receipts in one shard block, which is also suboptimal. So we decide to limit only transaction size for now.
=> Limiting block size

core/primitives/src/test_utils.rs, core/primitives/src/transaction.rs, core/protos/protos/signed_transaction.proto
First step to add access keys is to be able to provide public key that is used for the signature, so we can check access_key in addition to the public keys on the account.
=> Add optional public key to the SignedTransaction

core/wasm/runtest/src/lib.rs, core/wasm/src/cache.rs, core/wasm/src/executor.rs, core/wasm/src/prepare.rs, core/wasm/src/types.rs, node/runtime/benches/bench.rs, node/runtime/src/lib.rs, node/runtime/src/state_viewer.rs, node/runtime/src/system.rs
#886 
before:
```
test runtime_send_money                     ... bench:     170,030 ns/iter (+/- 12,920)
test runtime_wasm_bad_code                  ... bench:   1,040,480 ns/iter (+/- 147,577)
test runtime_wasm_benchmark_10_reads_legacy ... bench:     883,079 ns/iter (+/- 115,454)
test runtime_wasm_benchmark_storage_100     ... bench:   1,778,676 ns/iter (+/- 235,356)
test runtime_wasm_benchmark_storage_1000    ... bench:  12,418,531 ns/iter (+/- 1,074,537)
test runtime_wasm_benchmark_sum_1000        ... bench:     762,753 ns/iter (+/- 341,578)
test runtime_wasm_benchmark_sum_1000000     ... bench:  13,355,861 ns/iter (+/- 861,692)
test runtime_wasm_set_value                 ... bench:     750,164 ns/iter (+/- 100,792)
```
after:
```
test runtime_send_money                     ... …
```
=> Store the hash of contract code

Cargo.lock, chain/devnet/src/lib.rs, chain/http/Cargo.toml, chain/http/src/api.rs, nearmint/src/main.rs, runtime/primitives/src/account.rs, runtime/primitives/src/utils.rs, runtime/runtime/Cargo.toml, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/storage/src/lib.rs, runtime/verifier/Cargo.toml, runtime/verifier/src/lib.rs, test-utils/testlib/src/user/runtime_user.rs, test-utils/testlib/src/user/shard_client_user.rs, test-utils/testlib/src/user/thread_user.rs
Adding TX Verifier that mimics current Runtime checks.
It also verifies AccessKeys, but they are not tested and you can't add one yet.
Remove `&mut` from `get` resulted in a lot of files touched.
Also rust_fmt modified some style in the touched files 
For #687
=> Create Transaction Verifier and switch runtime/api to use it

nearmint/tests/test.rs
#921 introduced a bug by adding `eve.near` to `default_devnet` chain spec. Some nearmint integration tests assume that `eve.near` does not exist and therefore fail.
=> Fix integration tests

Cargo.lock, test-utils/testlib/src/user/runtime_user.rs
it's breaking runtime benchmarks
=> Take tempdir creation out of RuntimeUser::new

Cargo.lock, runtime/runtime/src/ext.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/runtime/src/system.rs, runtime/runtime/tests/test_evil_contracts.rs, runtime/storage/Cargo.toml, runtime/storage/src/lib.rs, runtime/storage/src/storages/mod.rs, runtime/storage/src/storages/shard.rs, runtime/storage/src/trie/mod.rs, runtime/storage/src/trie/nibble_slice.rs, runtime/storage/src/trie/update.rs, runtime/wasm/Cargo.toml, test-utils/testlib/src/standard_test_cases.rs, tests/hello/assembly/main.ts
- change structure, make an storage object for temporary mutable trie nodes
- normalize nodes after delete, a test for unique representation
- non-recursive trie methods, an evil contract test
- correctly compute refcounts
- TrieChanges to support storing multiple versions in the future
- Cache for storage, will be more useful later, also fix cached crate
Performance got better but still a lot of time is spent allocating.
=> Trie changes

nearmint/src/lib.rs, nearmint/tests/test.rs, runtime/primitives/src/account.rs, runtime/runtime/src/chain_spec.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, scripts/start_nearmint.sh
Limitations:
* Currently we subtract storage cost from the account balance only when the transaction is sent from that account. We don't debit all accounts on each block automatically, because that would be too much of the computation.
* We do not debit AccessKeys, because they are not fully implemented yet. Specifically, their balance is not used;
* The `storage_usage` field of the account does not include the storage that it takes to store the account itself, because we would have to update it too frequently -- every time we change the nonce, public keys, etc of the account because the resulting serialized size is not easily computable.
* The callbacks do not pay for storage because they are temporary.
=> Subtract storage cost from the account's balance

Cargo.toml
LTO makes a huge difference for our runtime exported functions so it
makes sense to benchmark with the same config as release.
=> Make profile.bench match profile.release

runtime/runtime/src/system.rs
Fixes https://github.com/nearprotocol/nearcore/issues/981
=> Clarify `Account {} does not match requirements` error message

chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/client.rs, chain/client/src/test_utils.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/client/tests/query_client.rs, chain/jsonrpc/src/client.rs, core/primitives/src/account.rs, core/primitives/src/rpc.rs, near/src/config.rs, near/src/runtime.rs, runtime/runtime/src/adapter.rs, runtime/runtime/src/state_viewer.rs, scripts/start_near.sh, test-utils/loadtester/src/remote_node.rs, test-utils/testlib/src/node/mod.rs, test-utils/testlib/src/standard_test_cases.rs, test-utils/testlib/src/user/mod.rs, test-utils/testlib/src/user/rpc_user.rs, test-utils/testlib/src/user/runtime_user.rs
I think from this moment, we should not change the Query API, but instead add new options to the enum, pretty much allowing for versions of return values.
The only question is if we want to have some version number as part of response JSON for example or something else explicit.
=> Change query response to be just plain json instead of base58 encoded

core/primitives/src/crypto/signature.rs, core/primitives/src/transaction.rs, core/protos/protos/receipt.proto, runtime/runtime/src/ext.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/runtime/src/system.rs, runtime/wasm/runtest/src/lib.rs, runtime/wasm/src/types.rs, test-utils/testlib/src/standard_test_cases.rs
Currently `originator_id` and `public_key` from the `RuntimeContext` is not exposed yet to WASM runtime.
=> Include originator_id and public_key into receipts and callbacks

README.md
removing links for running local devnet and joining testnet as links have been deprecated
=> removing deprecated links on README

chain/client/src/client.rs
PR resolves #991 
Adds wait_until_genesis function , where we
1)find out current Utc time
2)getting number of seconds by deducting genesis_time from current utc time
3)if number of seconds larger than zero then wait for a number of seconds
=> Wait for genesis when starting node

rust-toolchain
This will automatically download nightly rust when a user runs cargo build --all
in the nearcode directory as opposed to failing with the following error:
```
error: failed to parse manifest at `/home/user/code/nearcore/Cargo.toml`
Caused by:
the cargo feature `profile-overrides` requires a nightly version of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more
information about Rust release channels.
```
=> Add a nightly rust-toolchain file

Cargo.lock, runtime/wasm/Cargo.toml, runtime/wasm/runtest/src/lib.rs
Singlepass backend should hopefully be safe from compiler bombs.
Results on our existing benchmarks are actually the same.
=> Update wasmer and switch to singlepass backend

near/src/runtime.rs, near/src/validator_manager.rs, runtime/runtime/src/system.rs, test-utils/testlib/src/standard_test_cases.rs, tests/test_cases_runtime.rs
Enables unstaking and change of stake for validators. Unstaking is done by sending a staking transaction with amount 0 and now the amount in staking transaction means the total amount staked, so it is easy for validators to change their stakes. Fixes #1060.
=> Change of stake

rust-toolchain
Currently our code is not working with `cargo 1.38.0-nightly` due to an error in library `hex-literal`.
If the last version of nightly installed in a computer is `1.38` cargo will try to use it on this configuration, and throw an error.
Particularly for me doesn't work `cargo test --all --verbose`.
For now let's have the toolchain we know that works `1.36.0-nightly` (`nightly-2019-05-22`) This is the one we are using to run the CI right now.
=> Specify custom toolchain version

Cargo.lock, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/client.rs, near/Cargo.toml, near/src/runtime.rs, near/src/test_utils.rs, near/src/validator_manager.rs, near/tests/stake_nodes.rs
Fix block producer assignment calculation in `proposals_to_assignments` so that `block_producers` are now indices into validators in each epoch. Still need to properly keep track of random seeds for each epoch.
=> Fix block producer assignment

chain/chain/src/chain.rs, chain/chain/src/error.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chain/tests/simple_chain.rs, chain/client/src/client.rs, chain/client/tests/process_blocks.rs, chain/network/src/peer.rs, chain/network/src/types.rs, core/primitives/src/block.rs, core/protos/protos/chain.proto, near/src/runtime.rs, near/src/validator_manager.rs, near/tests/runtime_fork.rs, near/tests/stake_nodes.rs, near/tests/sync_nodes.rs
Block headers now record the epoch hash that the block belongs to.
=> Add epoch hash to block headers

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/client.rs, near/src/runtime.rs, near/tests/stake_nodes.rs
=> Check validator signature

README.md
=> Removing neartest.com from ReadMe

Cargo.lock, chain/network/Cargo.toml, chain/network/src/peer_store.rs
=> Ban peer doesn't save to storage fix

near/src/runtime.rs, near/src/validator_manager.rs, near/tests/stake_nodes.rs, runtime/runtime/src/system.rs
Before we return stakes to validators 2 epochs after the change of stake, but this has the problem of not leaving enough time for slashing. More specifically, a validator could do whatever they want at the end of epoch X + 1 where they are still validating, since their stake would be returned in the next block.
=> Return stake 3 epochs later

near/tests/stake_nodes.rs
Working on validator propagation I noticed this test was stopping earlier because at the beginning there are two validators (specified in the config) and both are the same account (`near.0`). The test was exiting successfully without testing that `near.1` join the validators.
=> Fix stake test

chain/client/src/info.rs, core/primitives/src/transaction.rs, core/primitives/src/types.rs, core/primitives/src/utils.rs, core/protos/protos/signed_transaction.proto, core/store/src/lib.rs, core/store/src/trie/update.rs, near/res/testnet.json, near/src/config.rs, near/src/runtime.rs, runtime/runtime/benches/bench.rs, runtime/runtime/src/config.rs, runtime/runtime/src/ext.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/runtime/src/system.rs, runtime/runtime/tests/test_evil_contracts.rs, test-utils/state-viewer/src/main.rs, test-utils/testlib/src/node/process_node.rs, test-utils/testlib/src/node/runtime_node.rs, test-utils/testlib/src/node/thread_node.rs, test-utils/testlib/src/runtime_utils.rs, test-utils/testlib/src/standard_test_cases.rs, test-utils/testlib/src/user/mod.rs, test-utils/testlib/src/user/rpc_user.rs, test-utils/testlib/src/user/runtime_user.rs, tests/test_cases_runtime.rs
If account has less balance to support it for given number of blocks, anyone can initiate deletion and receive reward from that.
TODO: need to add logic when before running a staking auction staking to check that validator has enough rent on the account.
=> Account deletion

scripts/nodelib.py
+ Better error messages and KeyboardInterrupt handling
=> Fix issue with running localnet second time

scripts/nodelib.py
Running the scripts with Python 3.x crashes due to str/bytes difference:
```
Starting NEAR client and Watchtower dockers...
Traceback (most recent call last):
File "./scripts/start_testnet.py", line 30, in <module>
args.boot_nodes, args.verbose)
File "/mnt/storage/projects/near.ai/nearcore-testnet/scripts/nodelib.py", line 171, in setup_and_run
run_docker(image, home_dir, boot_nodes, verbose)
File "/mnt/storage/projects/near.ai/nearcore-testnet/scripts/nodelib.py", line 120, in run_docker
docker_stop_if_exists('watchtower')
File "/mnt/storage/projects/near.ai/nearcore-testnet/scripts/nodelib.py", line 105, in docker_stop_if_exists
if name in result:
TypeError: a bytes-like object is required, not 'str'
```
P.S. I have checked that this fix does not break Python 2.x compatibility.
=> Fixed a minor Python 3.x compatibility issue in the deployment scripts

Cargo.lock, chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/proposals.rs, chain/epoch_manager/src/reward_calculator.rs, chain/epoch_manager/src/test_utils.rs, chain/epoch_manager/src/types.rs, core/primitives/src/rpc.rs, core/primitives/src/test_utils.rs, core/store/src/lib.rs, near/Cargo.toml, near/src/config.rs, near/src/runtime.rs, near/tests/run_nodes.rs, near/tests/stake_nodes.rs, runtime/runtime/src/state_viewer.rs
Make validator reward work with runtime. Re-enable all runtime tests.
=> Validator reward with runtime

test-utils/state-viewer/src/main.rs
Allow printing block headers from chain with specified range.
=> Add print headers to state-viewer

test-utils/state-viewer/src/main.rs
If a block at some index doesn't exist we should just skip it instead of panicking.
=> Fix bug in printing blocks

chain/chain/src/test_utils.rs, core/primitives/src/account.rs, core/primitives/src/rpc.rs, core/primitives/src/serialize.rs, core/protos/protos/access_key.proto, core/protos/protos/account.proto, near/src/config.rs, near/src/runtime.rs, runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/runtime/src/store.rs, runtime/verifier/src/lib.rs, test-utils/loadtester/src/remote_node.rs, test-utils/testlib/src/node/mod.rs, test-utils/testlib/src/standard_test_cases.rs, test-utils/testlib/src/user/mod.rs, test-utils/testlib/src/user/rpc_user.rs, test-utils/testlib/src/user/runtime_user.rs, tests/test_cases_runtime.rs, tests/test_errors.rs, tests/test_rejoin.rs, tests/test_simple.rs
Reworking access keys, by introducing permissions to access keys. See https://github.com/nearprotocol/NEPs/blob/master/text/0005-access-keys.md
This change removes `public_keys` from the account and replaces them with full access access keys.
It also removes `nonce` from the account and moves it to `access_key` which means there can be multiple TX nonces per account. It's probably not correctly handled in the mempool, but it also needs additional work to make sure TX verification correctly addresses costs.
=> Replace access keys (implements NEP#0005)

chain/chain/src/test_utils.rs, chain/chain/src/types.rs, core/store/src/lib.rs, core/store/src/trie/mod.rs, near/src/runtime.rs
Record every read of a trie node from storage to use
the recorded values for a proof of execution.
This includes all key paths for keys requested for reads, but also
in case of updates can include additional nodes which are
necessary to provide a canonical resulting trie (i.e. no branch nodes
with <= 1 branch and extension is always followed by a branch).
=> Recording partial trie for storage proofs

core/primitives/src/utils.rs, runtime/runtime/src/actions.rs, runtime/runtime/src/config.rs, runtime/runtime/src/lib.rs, test-utils/testlib/src/runtime_utils.rs, test-utils/testlib/src/standard_test_cases.rs, tests/test_cases_runtime.rs
This change implements https://github.com/nearprotocol/NEPs/pull/6
Fixes #968
=> Implement ANS (NEP#0006)

Cargo.lock, core/primitives/Cargo.toml, core/primitives/src/crypto/signature.rs, core/primitives/src/hash.rs, core/primitives/src/lib.rs, core/primitives/src/test_utils.rs, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-logic/src/logic.rs
We used a fork of [sodiumoxide](https://github.com/sodiumoxide/sodiumoxide) for no good reason. It's time to switch to using actual sodiumoxide.
=> Switch to sodiumoxide

Cargo.lock, chain/client/src/client.rs, core/primitives/Cargo.toml, near/Cargo.toml
Currently we incorrectly use `head.epoch_hash` for computing block proposer for the next block, which could be in a new epoch. https://github.com/nearprotocol/nearcore/blob/38d2c76ca7bf7fd8d9ad44d14efe4159d66998aa/chain/client/src/client.rs#L632.
=> Fix incorrect epoch hash computation

Cargo.lock, core/primitives/Cargo.toml, runtime/near-runtime-fees/Cargo.toml, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-logic/src/dependencies.rs, runtime/near-vm-logic/src/lib.rs, runtime/near-vm-logic/src/logic.rs, runtime/near-vm-logic/src/mocks/mock_external.rs, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner/Cargo.toml, runtime/near-vm-runner/src/prepare.rs, runtime/runtime/Cargo.toml, runtime/runtime/src/ext.rs
* Allowing floats until we solve json;
* Using old bs58;
* Extracting sodiumoxide from near-vm-logic;
* Bumping version of crates.
=> Some dependencies changes needed for smart contract testing.

tests/hello/package.json
This is needed because out was added to //@nearfile annotation, and right
now it requires out/assembly to exist
=> Create out/assembly dir so that hello contract can compile

Cargo.lock, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/client.rs, core/store/src/lib.rs, core/store/src/trie/mod.rs, core/store/src/trie/update.rs, near/src/runtime.rs, runtime/near-vm-logic/src/dependencies.rs, runtime/near-vm-runner/src/errors.rs, runtime/runtime/src/actions.rs, runtime/runtime/src/cache.rs, runtime/runtime/src/ext.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/verifier/src/lib.rs
Divide storage errors into three cases:
```
pub enum StorageError {
/// Key-value db internal failure
StorageInternalError,
/// Storage is PartialStorage and requested a missing trie node
TrieNodeMissing,
/// Either invalid state or key-value db is corrupted.
/// For PartialStorage it cannot be corrupted.
/// Error message is unreliable and for debugging purposes only. It's also probably ok to
/// panic in every place that produces this error.
/// We can check if db is corrupted by verifying everything in the state trie.
StorageInconsistentState(String),
}
```
1st error - nothing we can do about it, node has to manually recover
2nd error - normal case when verifying challenges, code that runs in challenge verification context should be able to handle
3rd error - Either state is invalid, …
=> [WIP] Storage errors

chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chain/tests/simple_chain.rs, chain/client/src/client.rs, chain/client/tests/process_blocks.rs, chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/proposals.rs, chain/epoch_manager/src/reward_calculator.rs, chain/epoch_manager/src/test_utils.rs, chain/epoch_manager/src/types.rs, core/primitives/benches/serialization.rs, core/primitives/src/block.rs, core/primitives/src/test_utils.rs, near/src/runtime.rs, near/tests/stake_nodes.rs, near/tests/sync_nodes.rs
Previously we incorrectly computed inflation at every block whereas it should be only updated once per epoch. However, this PR doesn't fix the calculation entirely as doing so requires exposing the transaction fees from runtime.
=> Fix inflation calculation

Cargo.lock, chain/client/src/client.rs, near/Cargo.toml
Testnet is slow due to block approval collection. Disable it for now to make testnet faster and the problem should have been fixed in staging.
=> Disable block approval for now

chain/client/src/client.rs
Currently when we produce a block we don't filter transaction based on validity period which could cause invalid blocks to be produced.
=> Filter transactions based on validity period

Cargo.lock, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, test-utils/testlib/Cargo.toml, test-utils/testlib/src/user/rpc_user.rs
Currently we can only query block by index. This PR allows one to query block by its hash through rpc.
=> Query block by hash through rpc

chain/chain/src/test_utils.rs, chain/chunks/src/lib.rs, chain/client/tests/catching_up.rs
- Tests now skip the first block (because by the time the nodes launch the timeout for the first block is already expired), address it by expecting the first block to be the second block
- Changing the expected prev_block for transactions to be the previous of the last known block (which in the catchup tests always known to all the nodes)
- Adding a new mode for one of the `catchup` tests that exposes a bug Kourpin is presently fixing. The test in that mode is currently ignored.
=> Fixing catchup tests

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, near/src/runtime.rs, runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs
Not sure where to test the rent. Ideally we should have the total coinbase test with 0% inflation to verify we don't burn or lose tokens anywhere. There is still situation when the refund arrives on the non-existing account, then these tokens are considered burned.
=> Provide total rent paid in ApplyResult

chain/client/src/client.rs, pytest/lib/cluster.py, pytest/lib/retry.py, pytest/lib/serializer.py, pytest/lib/transaction.py, pytest/requirements.txt, pytest/tests/sanity/block_production.py, pytest/tests/sanity/transactions.py
Infrastructure to run python tests, and two sanity tests.
- Python infrastructure to build local tests, including starting a cluster, sending RPC requests, and binary serializer
- Two early tests: one makes sure four nodes collectively can create 50 blocks without diverging, another is a sanity test a single payment transaction works.
Discovered two issues:
- Announce account was not property broadcasting itself (hot-fixed in #1318 #1323)
- Transaction routing is (likely) never triggered #1327
=> Python tests

Cargo.lock, chain/chain/Cargo.toml, chain/client/Cargo.toml, chain/jsonrpc/Cargo.toml, chain/network/Cargo.toml, core/crypto/Cargo.toml, core/primitives/Cargo.toml, core/store/Cargo.toml, near/Cargo.toml, runtime/runtime/Cargo.toml, test-utils/loadtester/Cargo.toml, test-utils/state-viewer/Cargo.toml, test-utils/testlib/Cargo.toml
Incorporate borsh fix on the problem https://github.com/nearprotocol/borsh/issues/2 that would crash the testnet.
=> Bump borsh and nearcore version

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/tests/challenges.rs, chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/reward_calculator.rs, chain/epoch_manager/src/test_utils.rs, chain/epoch_manager/src/types.rs, core/primitives/src/block.rs, core/primitives/src/sharding.rs, core/primitives/src/types.rs, core/primitives/src/views.rs, near/src/runtime.rs, near/src/shard_tracker.rs, runtime/near-vm-logic/tests/test_storage_usage.rs, test-utils/state-viewer/src/main.rs
Fixes #1281. Account for storage rent in economics calculations. Economics is now fully implemented except for voting on gas limit, which we do not plan to support before mainnet.
=> Account for storage rent in economics

chain/chain/src/chain.rs, chain/chain/src/error.rs, chain/chain/src/store.rs, chain/chain/tests/challenges.rs, chain/chain/tests/simple_chain.rs, core/store/src/lib.rs
- Fixing an issue that `update_block_index` was not erasing the tail of indexes if the new tip has lower height that the last tip.
- Basic challenge functionality, that reverts the Tip to either the parent of the challenged block, or the challenger block.
- Preventing the chain with an invalid block from becoming canonical.
=> Chain functionality to challenge a block

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/tests/simple_chain.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/client/tests/challenges.rs, chain/client/tests/process_blocks.rs, chain/jsonrpc/tests/rpc_query.rs, chain/network/src/types.rs, core/primitives/benches/serialization.rs, core/primitives/src/block.rs, core/primitives/src/test_utils.rs, core/primitives/src/views.rs, near/tests/sync_nodes.rs
Move invalid tx tests into client cargo.
Move run_catchup and process_tx into `Client` as they are operating in non async mode.
=> Remove block transactions

chain/chain/src/test_utils.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/client/tests/cross_shard_tx.rs
- Adding handlers for block and block header requests to the hackery in the test utils;
- Fixing a bug that causes transactions not being reintroduced to the pool: when a block is unblocked due to an orphaned one part, `on_block_accepted` was not called
=> Fixing cross-shard-tx test

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/client/tests/cross_shard_tx.rs
`catchup_blocks` was removing too many blocks that are stored for the future catchup from the permament storage, which could result in certain blocks never getting caught up, or blocks unblocked too early.
=> Fixing one more issue discovered by `cross_shard_tx`

Cargo.lock, chain/chain/src/chain.rs, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, pytest/tests/stress/stress.py, test-utils/testlib/Cargo.toml, test-utils/testlib/src/user/rpc_user.rs
- Includes Bowen's change from master that allows requesting Block by hash in jsonrpc
- Also fixing bug with invalid proposals
=> Early work on Chaos Monkey

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/src/sync.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/client/tests/challenges.rs, core/primitives/benches/serialization.rs, core/primitives/src/block.rs, core/primitives/src/sharding.rs, core/primitives/src/types.rs, core/primitives/src/views.rs, genesis-tools/genesis-populate/src/lib.rs, near/src/runtime.rs, near/tests/sync_state_nodes.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/runtime/tests/runtime_group_tools.rs, test-utils/state-viewer/src/main.rs, test-utils/testlib/src/node/runtime_node.rs, test-utils/testlib/src/runtime_utils.rs, test-utils/testlib/src/user/runtime_user.rs
=> Mostly StateRoot

core/primitives/src/utils.rs, near/res/testnet.json, scripts/state/migrate-from-0.3.py
`@` separator is not popular enough and hurts UX in the wallet. We can't prefix every account_id with `@` in the wallet if the `@` is allowed within an account ID.
Discussed with @vgrichina, @jakestutzman and @kcole16 and we've decided to remove this separator completely.
=> Remove `@` separator from accounts.

chain/chain/src/chain.rs, chain/client/src/client.rs, chain/client/tests/catching_up.rs, pytest/lib/cluster.py, pytest/lib/utils.py, pytest/tests/sanity/state_sync.py, pytest/tests/sanity/transactions.py, pytest/tests/stress/stress.py
- Chainging the python sanity test to use routing (it passes)
- Changing how the horizon is working
Before this change it was checking heights (H, H+1, H+2), and
then routing to H+2. It is both wrong to check H (the chunk at
H is already produced), and wrong to send to the last height we
checked, because the recepient with a high chance one block
behind us, and will redundantly re-forward the transaction.
Now it looks at (H+1, H+2, H+3), still forwards to H+2.
- The previous change also fixes most of the catchup tests, since
two blocks horizon was not enough under stress. Shifting horizon
one block forward fixed most of them.
Some catchup tests still fail due to #1484
=> Few changes after transaction routing

Cargo.lock, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/network/Cargo.toml, chain/network/src/codec.rs, chain/network/src/lib.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/src/types.rs, chain/network/src/utils.rs, chain/network/tests/routing.rs
It is possible to route back messages now without having explicit route to the author of the original message. Add ping/pong for easy testing networking.
=> Network route back.

Cargo.lock, near/Cargo.toml
Reduce total supply to avoid rewards accumulating too fast.
=> Reduce total supply and adjust parameters

chain/chain/src/chain.rs, chain/chain/src/types.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, core/primitives/benches/serialization.rs, core/primitives/src/block.rs, core/primitives/src/sharding.rs, core/primitives/src/views.rs, genesis-tools/genesis-populate/src/lib.rs
I could not make [the new test case](https://github.com/nearprotocol/nearcore/pull/1524/files#diff-9038756cf0318ed127567e2c3abe5490), which requests a chunk by block height (0) and shard id (0), working:
```
Chunk Missing: ChunkHash(`CiADPKxqY5XoSAQAkLjKohFWj9cK3tBrUVKqaEkCpU4v`)
```
Other than that, the implementation is working fine.
REMINDER: Update [the docs](https://docs.nearprotocol.com/api-documentation/rpc) with the information about the new API.
=> Introduced `chunk` API

Dockerfile.prod, Makefile, scripts/nodelib.py
systemd-coredump needs to be installed in host machine instead of docker. Remove it in docker to minimize image size. Besides these, docker is kind of a special "process" in host machine, a configuration change in host needed to make coredump works. On linux it's:
```
echo '/tmp/core.%t.%e.%p' | sudo tee /proc/sys/kernel/core_pattern
```
Docker use content host's core_pattern as path to store core dump, but store that in the container fs instead of host fs, so the change in nodelib.py is for bring the core dump into host (/tmp)
To test this by making a segment fault, easiest way is adding this to main():
```
let r1 = 0 as *const i32;
unsafe {
println!("r1 is: {}", *r1);
}
```
=> working coredump for docker

Cargo.lock, runtime/near-runtime-fees/Cargo.toml, runtime/near-vm-errors/Cargo.toml, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-logic/src/lib.rs, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner/Cargo.toml, runtime/publish.sh
A workaround for this cargo bug https://github.com/rust-lang/cargo/issues/2524 . We need it for making near-bindgen testing nicer.
=> Cargo bug workaround

scripts/nodelib.py, scripts/start_stakewars.py
Needs to be updated accordingly after https://github.com/nearprotocol/nearcore/pull/1562 is merged.
=> Script to start nodes for stakewars

genesis-tools/keypair-generator/src/main.rs, scripts/nodelib.py, scripts/start_stakewars.py
It is a rather suboptimal way to do it but until we have good cli support, we need something to generate keypairs for stakewars.
=> Add option to generate signer keys to file

Cargo.lock, genesis-tools/genesis-csv-to-json/Cargo.toml, genesis-tools/genesis-csv-to-json/src/serde_with.rs
When we deserialize a list of public keys, we should allow whitespaces since people inadvertently drop in whitespaces.
=> Allow whitespaces in public key representation

chain/network/src/types.rs
Currently, the test is configured just for info, but some messages are above 1024.
```
Enums: 
The size of RoutedMessageBody is 1096
The size of PeerRequest is 1136
The size of NetworkRequests is 1192
The size of NetworkClientMessages is 1192
The size of NetworkClientResponses is 1128
Structs:
The size of RawRoutedMessage is 1168
The size of RoutedMessageNoSignature is 1232
The size of RoutedMessage is 1296
The size of RoutedMessageFrom is 1368
The size of SendMessage is 1304
The size of StateResponseInfo is 1088
```
ref #1313
=> Adding a test to monitor network structure sizes

chain/chain/src/chain.rs, chain/chunks/src/chunk_cache.rs, chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/network/src/peer.rs, near/src/config.rs
1. Properly fixing the case when a node is not a validator and doesn't need to request any chunks.
2. Allow fetching chunks that are outside of the cache horizon, and only use the horizon for unknown chunks.
=> Fixing chunks retrieval for non-validators

Dockerfile
@hoekevin I just pushed this build to `ailisp/nearcore` docker image, can you try if this build works for you? Thanks
=> use x86-64 arch to avoid illegal inst in older cpus

chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/proposals.rs, chain/epoch_manager/src/test_utils.rs, chain/epoch_manager/src/types.rs
Fixes two bugs in epoch manager:
* When we kickout validators, we need to make sure that the union of kickout set for current epoch  and last epoch is not the whole validator set for the current epoch. Otherwise everyone gets kicked out.
* When we calculate expected number of blocks we need to go to `max(epoch_last_block_index, last_epoch_last_block_index + self.config.epoch_length)` instead of just `last_epoch_last_block_index + self.config.epoch_length` to handle the situation where the epoch ends later than expected.
=> Epoch manager fixes

chain/chain/src/error.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/proposals.rs, chain/epoch_manager/src/test_utils.rs, chain/epoch_manager/src/types.rs, genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs, near/src/config.rs, near/src/runtime.rs, near/src/shard_tracker.rs, near/tests/stake_nodes.rs, near/tests/sync_nodes.rs
Add a separate threshold for chunk validator kickout. Also now block producer will wait for chunks to arrive, in addition to block approvals.
=> Add chunk validator kickout threshold

chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/client.rs, chain/client/src/lib.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/types.rs, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, core/primitives/src/views.rs, near/src/runtime.rs, near/tests/rpc_nodes.rs
* Fix a bug in rpc routing where previous we do not route the query if the query at current node is not successful
* Refactor validator query to be its own rpc instead of being part of query rpc
* Add number of missing blocks to validator query result. Fixes #1637
=> Fix some issues in rpc routing

chain/client/src/types.rs, chain/client/tests/chunks_management.rs
Fixes #1705
The problem was that the delay to re-request chunks in the test config was 1/5 of the block production time, and the test might require to request more than 5 times.
=> Fixing `chunks_recovered_from_others` flakiness.

Cargo.lock, chain/chain/Cargo.toml, chain/chain/src/lib.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chunks/src/lib.rs, chain/chunks/src/types.rs, chain/client/src/client.rs, chain/client/src/types.rs, chain/client/tests/challenges.rs, chain/pool/Cargo.toml, chain/pool/src/lib.rs, chain/pool/src/types.rs, core/crypto/src/signature.rs, core/primitives/src/block.rs, core/primitives/src/sharding.rs, near/src/runtime.rs
Reverting the revert https://github.com/nearprotocol/nearcore/commit/bbeed123db9a3fda06943c6d17556a889c8e4901
And reintroducing transactions back into the pool after filtering at chunk production. It removes invalid transactions from the pool during filtering while keeping valid transactions until the chunk is included in the block.
=> RE: client tx limiting

chain/chain/src/chain.rs, chain/chain/src/types.rs
It's possible to have multiple sync_hash with the same state_root,
which would lead to one of them deleting shared data while the other
is still running.
=> Replace state_root with sync_hash in StatePartKey

genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs, genesis-tools/genesis-csv-to-json/src/main.rs, near/src/runtime.rs, scripts/nodelib.py, scripts/start_stakewars.py
Also fix the minor issue that genesis tool requires validator_key.json to exist.
=> Allow genesis tool to specify shards to track

chain/chain/src/chain.rs, chain/chain/src/error.rs, chain/client/src/client_actor.rs, near/src/config.rs
Also adjust the adaptive waiting time for skipped blocks to be at least `max_block_production_delay` to reduce forkfulness.
=> Remove OldBlock error

chain/epoch_manager/src/lib.rs, core/store/src/lib.rs
Allow epoch manager to compare two epoch ids. Because of the guarantees of finality gadget, there cannot be two different epochs that are strictly on two different forks and therefore we can always compare two epoch ids.
=> Compare epoch id

chain/chunks/src/lib.rs, chain/client/src/client.rs, nightly/nightly.txt, pytest/tests/sanity/fork_sync.py, pytest/tests/sanity/one_val.py
Problem: the call to `prepare_chunks` was moved in `produce_blocks` before the check
for sufficient number of approvals. `prepare_chunks` removes the chunks info from the
`shards_mgr`, so if we then didn't have enough approvals or enough chunks and were
delaying the block production, the next time around `prepare_chunks` returned an empty
set
Test Plan: new pytest `one_val.py` that reproduces the issue without this change
=> Fixing an issue that was causing blocks being produced without chunks

chain/chain/src/chain.rs, chain/chain/src/finality.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chain/tests/finality.rs, chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/epoch_manager/src/lib.rs, chain/epoch_manager/tests/finality.rs, near/src/runtime.rs, nightly/nightly.txt, pytest/lib/cluster.py, pytest/lib/utils.py, pytest/tests/sanity/state_sync.py
- Making the Finality Gadget respect weights
- Both `compute_quorums` and `compute_quorums_slow` in the test infra now take stakes
as parameter. Both functions are changed to respect the stakes.
- Also (unrelated to the finality gadget) added LogTracker into python test utilities that
allows to track if a particular substring appears in the logs between two interactions
with the log tracker
- Added check to `state_sync.py` test to check if "State 0" appears in the logs when the
sync height is > 100, and that it doesn't appear when it is < 30, runs with both heights
passed
Test Plan for the Finality Gadget change:
- Added a sanity test `test_finality_weight` with a simple case to test that weights are
actually respected
- `test_fuzzy_safety` now on each iteration with 50% chance uses …
=> Finality Gadget respects weights

.gitlab-ci.yml, scripts/upload_release.sh
Each commit into master and staging (This happens after merge any PR into master/staging), will do a release build and upload to gcloud. Will be used in pytest remote node and app layer integration tests.
=> Release binary to gcloud

Dockerfile
Test docker build, works well. Also updated in https://github.com/nearprotocol/docs/. For stakewar seems no longer have rust instructions there, so not updated.
=> Fix dockerfile after rust-rocksdb

.gitlab-ci.yml, near/src/config.rs
`/runtime/near-vm-runner/tests/res/test_contract_rs.wasm` was load at run time instead of compile time. This breaks our docker and binary release. To see the issue: `docker run nearprotocol/nearcore:staging near testnet`
#1208 
Blocks #1823
=> Fix bundled test_contract_rs

chain/chain/src/test_utils.rs, chain/client/tests/catching_up.rs, chain/client/tests/cross_shard_tx.rs, chain/client/tests/query_client.rs, chain/jsonrpc/tests/rpc_query.rs, core/primitives/src/views.rs, near/src/runtime.rs, near/tests/rpc_nodes.rs, near/tests/stake_nodes.rs, runtime/runtime/src/adapter.rs, runtime/runtime/src/state_viewer.rs, test-utils/loadtester/src/remote_node.rs, test-utils/testlib/src/standard_test_cases.rs, test-utils/testlib/src/user/mod.rs, test-utils/testlib/src/user/rpc_user.rs, test-utils/testlib/src/user/runtime_user.rs
*Resolves #1778*
I have renamed `QueryResponse` to `QueryResponseKind` and added a wrapper `QueryResponse` struct which include `kind` + `block_height`.
I use `serde(flatten)` on the `kind` field to keep the API response backward compatible. From the RPC client point of view, a single `block_height` field has been added [a test case is added to ensure this] (cc @vgrichina):
```
$ http post http://127.0.0.1:3030/ jsonrpc=2.0 id=dontcare method=query 'params:=["account/test.near", ""]'
{
"id": "dontcare",
"jsonrpc": "2.0",
"result": {
"amount": "1000000000000000000000000000",
"block_height": 83,
"code_hash": "11111111111111111111111111111111",
"locked": "50000000000000000000000000",
"storage_paid_at": 0,
"storage_usage": 182
}
}
```
=> Exposed block height at which given query RPC was performed

chain/chunks/Cargo.toml, chain/network/Cargo.toml, core/primitives/Cargo.toml
This is the default in reed-solomon-erasure 4.x: https://github.com/darrenldl/reed-solomon-erasure, but in 3.x to avoid illegal instructions in docker build for pre-haswell cpus (when you build in a >=haswell cpu), this is needed. There's incompatible api changes in reed-solomon-erasure 4.x, but I can also consider upgrade to that if it's needed.
PS: pre-haswell: ix-3xxx laptop, ex-1xxx server.
=> Use pure rust reed-solomon-erasure

.gitignore, chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/tests/fork_choice.rs, chain/client/src/client.rs, chain/client/src/sync.rs, chain/client/src/types.rs, near/src/config.rs, nightly/nightly.txt, pytest/lib/adversary.py, pytest/prepare_adversarial_binary.py, pytest/tests/adversarial/wrong_sync_info.py, pytest/tests/sanity/state_sync.py, pytest/tests/sanity/state_sync2.py
The adversarial node can be found here:
https://github.com/nearprotocol/nearcore/commit/cf7487f1e3b01262ec086ebbde10d4b1c5f026dc
- Made Header sync use weight/second to measure performance of the
header sync, and ban peer if for a prolonged period of time
weight/second is below expected value
- `process_block` now checks epoch before it checks if a block is an
orphan. It is needed to make it impossible to spam with fake blocks
without being penalized (more protections for it coming in future PRs).
- New infrastructure for adversarial testing that allows to corrupt node
and allows manipulating the behavior of the corrupted node.
Test plan:
- New python test (`wrong_sync_info`) that tests the adversary that
lies about their sync status
- Also new test `state_sync2` which is completely …
=> Header sync in presense of adversaries + Adversarial testing infra

scripts/parallel_coverage.py, scripts/testlib.py
Some fails https://gitlab.com/near-protocol/nearcore/-/jobs/386373532 report generated binary is directory, and when i ssh to host, they're indeed directory and owned by root. This happens because docker bind the binary as volume and use root user inside docker. In some rare case when test binary was cleaned (probably due to a maintenance after some task stuck), but pending tests are still going to run in docker, in this case docker detect the volume (file) doesn't exist, and it will create a directory (and since root user was used, the dir is owned by root, similar to what was happen to nearcore docker image), which cause issue in next build.
=> Run test as non root in docker and check binary exist before mount to docker

chain/client/src/sync.rs
The issue of https://github.com/nearprotocol/nearcore/pull/1904 is rewriting value of `download_timeout` in parts. Rewriting `download_timeout` means that timeout happened only with last part which is not desirable behaviour.
This PR fixes the issue + pretty printing SyncState.
=> sync parts timeout fix + colorful info

core/store/src/db.rs
I was misread one of parity kvdb-rocksdb option and steal it here. This fix #1883 , total initial get time decrease from eight minutes to 700ms.
IMPORTANT: as I tested for existing testnet node, must delete ~/.near/data and boot it from other node to get correct rocksdb config effective
=> Correct rust-rocksdb options

runtime/near-vm-logic/src/logic.rs, runtime/near-vm-runner/src/prepare.rs
The root of the problem is an overflow that happens in pwasm-utils
=> Fix u32 overflow during contract preparation

Cargo.lock, chain/client/Cargo.toml
located this happens after new sysinfo::System::new(): https://github.com/GuillaumeGomez/sysinfo/issues/242; before it fixed there it looks okay for us to use previous version.
=> Downgrade sysinfo to avoid too many open files bug

core/primitives/src/block.rs, core/primitives/src/merkle.rs, core/primitives/src/views.rs
Fixes https://github.com/nearprotocol/nearcore/issues/1921
=> challenges_root

chain/chain/src/chain.rs, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/client/src/view_client.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, chain/network/tests/infinite_loop.rs, chain/network/tests/peer_handshake.rs, chain/network/tests/runner/mod.rs, near/src/lib.rs, near/tests/rpc_nodes.rs
Fixes https://github.com/nearprotocol/nearcore/issues/1926
=> Move network requests to ViewClient

chain/network/src/peer_manager.rs
https://github.com/nearprotocol/nearcore/pull/1887 introduced
`expect("Decoder error")` which was incorrect because Decoder error is
not the only error case for FramedRead stream: error could come from the
underlying tcp stream.
The old behavior was to ignore the error, the behavior with this change
is to print the error and stop the stream.
=> Don't crash on "Connection reset by peer"

chain/chain/src/error.rs, chain/client/src/view_client.rs, chain/jsonrpc/tests/rpc_query.rs
When we receive some requests that contain shard id we should first check its validity before using it to index into an array. Fixes #1948
=> Check for invalid shard id

chain/network/tests/churn_attack.rs, chain/network/tests/routing.rs
Use workaround proposed [here](https://github.com/rust-lang/rust/issues/46379#issuecomment-487421236) to avoid dead code warning.
=> Remove dead code warnings from test

runtime/runtime/src/balance_checker.rs
Remove cargo complain about unused variable.
=> Remove warning

Cargo.lock, chain/client/Cargo.toml, chain/client/src/info.rs
As a follow up to this issue: https://github.com/nearprotocol/nearcore/issues/1942 (was fixed by downgrade sysinfo)
It's because of an optional optimization in sysinfo crate and now an option to turn off initial open files is added in https://github.com/GuillaumeGomez/sysinfo/pull/243. To verify it's still good, find near's pid. `lsof -p <pid> | wc -l`. Also note this was only an issue for linux (the optimization was linux only)
=> Upgrade sysinfo as too many open files is fixed

chain/chunks/src/chunk_cache.rs, chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/tests/catching_up.rs, chain/client/tests/chunks_management.rs
Fixes https://github.com/nearprotocol/nearcore/issues/1971.
Also fixes calculation of `encoded_chunks.num_chunks_for_block()`.
=> store partial encoded chunks

chain/jsonrpc/res/rpc_errors_schema.json, core/primitives/src/errors.rs, runtime/near-vm-errors/src/lib.rs, runtime/near-vm-logic/src/dependencies.rs, runtime/near-vm-logic/src/gas_counter.rs, runtime/near-vm-logic/src/lib.rs, runtime/near-vm-logic/src/logic.rs, runtime/near-vm-logic/src/types.rs, runtime/near-vm-logic/tests/helpers.rs, runtime/near-vm-logic/tests/test_miscs.rs, runtime/near-vm-logic/tests/test_registers.rs, runtime/near-vm-runner/src/errors.rs, runtime/near-vm-runner/src/imports.rs, runtime/near-vm-runner/src/runner.rs, runtime/near-vm-runner/tests/test_error_cases.rs, runtime/near-vm-runner/tests/test_invalid_contracts.rs, runtime/near-vm-runner/tests/test_rs_contract.rs, runtime/near-vm-runner/tests/test_ts_contract.rs, runtime/runtime/src/actions.rs, runtime/runtime/src/ext.rs, runtime/runtime/src/lib.rs, runtime/runtime/tests/test_evil_contracts.rs, test-utils/testlib/src/standard_test_cases.rs
- Refactoring around Errors from VMLogic.
- Add safe math and InconsistentStateError into VMLogic.
- Add safety check to Runtime for attached_balance + account.amount.
Ref #1461
=> Safe math vm logic

chain/network/src/peer_manager.rs, chain/network/src/test_utils.rs, chain/network/src/types.rs, chain/network/tests/peer_handshake.rs, chain/network/tests/runner/mod.rs, chain/network/tests/stress_network.rs, core/primitives/src/test_utils.rs
Test that #1954 is properly fixed. In the first commit (without the patch) this test reproduce the error, but right now it shows new error:
```
thread 'stress_test' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', src/libcore/result.rs:1165:5
```
Not sure why this error is happening.
=> Test connection reset by peer

near/tests/stake_nodes.rs
Test `test_validator_kickout` doesn't look flaky anymore.
#1094 can be closed.
=> test_kickout already working

chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_transactions.rs
Do not allow invalid account ids when we process transaction status queries.
=> Check account id inside tx status query

runtime/near-vm-logic/src/logic.rs, runtime/near-vm-logic/tests/test_promises.rs
Staking action should not be deducting from balance before creating receipt.
The overall logic of staking (e.g. deducting, locking and unlocking funds) is done when that Receipt is processed.
=> Fix staking action in near-vm-logic

chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/client/tests/challenges.rs, chain/client/tests/process_blocks.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, near/tests/sync_nodes.rs
This PR changes a couple things in block propagation to make it faster:
* Right now when a node receives a block it first processes it and only after the block is accepted does it get broadcast to other nodes. This slows down the propagation of blocks and therefore chunk production. This PR changes it so that when a block is received it will be rebroadcasted if it passes some basic validation.
* Currently header and approval are bundled together and every time an approval is sent, the message also contains the latest block header, which causes the block header to be unnecessarily broadcast to every peer. This PR removes this bundling and the block header broadcast altogether.
Test Plan
---------
* All existing tests pass.
* Test that when a block doesn't pass basic validation it will not …
=> Broadcast block immediately after receiving it

chain/client/src/client.rs, core/chain-configs/src/client_config.rs, near/src/config.rs, near/src/main.rs, test-utils/loadtester/src/main.rs, test-utils/testlib/src/node/mod.rs
Fixes https://github.com/nearprotocol/nearcore/issues/2094.
=> archive flag for turning off GC

test-utils/state-viewer/src/main.rs
Add back the option of dumping state in json format. Mostly for debugging purposes.
Test plan
--------
Manually test with local node to make sure that state can be dumped correctly.
=> Add json state dump for debugging

runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/verifier.rs
If an invalid state is given to the Runtime as part of a malicious challenge, the Runtime should fail with inconsistent state error instead of a crash or an overflow.
Test plan:
Added a unit test to verify the fix
Fixes: #2123
=> Add storage_paid_at check during `apply_rent`

Cargo.toml, tests/test_overflows.rs
By default Rust has `overflow-checks=off` for release.
This change enables panic on integer overflows with `profile.release`. This is not a nightly feature, because it's not an override.
Test plan:
- Added units test to check for overflow. This is useless because `cargo test --release` doesn't follow `profile.release` but instead some weird mix.
- Added explicit `std::panic::catch_unwind` to near main function. But overflow panic is too powerful to catch with panic catcher, so I reverted this check. But during this check observed the overflow panic, so I confirmed the overflow panics for the main binary.
=> Enable overflow-checks for release

chain/jsonrpc/tests/rpc_transactions.rs
These tests have a confusing behavior where they always explicitly
panic but in case of success they do it after stopping the system
with 0 code so it gets ignored.
Move the panic to the failure branch.
Run the test manually and see no panic in the output
Swap map_ok and map_err branches and see that it fails
=> fix(jsonrpc_client): Fix tests with confusing panic output

Cargo.lock, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/client/tests/catching_up.rs, chain/client/tests/cross_shard_tx.rs, chain/client/tests/query_client.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, core/primitives/src/rpc.rs, core/primitives/src/views.rs, near/tests/stake_nodes.rs, pytest/lib/cluster.py, pytest/tests/sanity/rpc_finality.py
For rpc queries, currently we return the result from the latest block and don't consider any finality. This PR allows ones to specify the finality requirement for the query (nfg, doomslug, none).
Test plan
---------
* Sanity test that different types of finality can be processed.
* pytest `rpc_finality.py` which tests that when blocks cannot be finalized by NFG because not enough validators are online but can be finalized by doomslug, rpc specifying doomslug finality and NFG finality return different (and correct) values.
=> feat(rpc): allow rpc to specify finality in query

chain/client/src/test_utils.rs, chain/client/tests/bug_repros.rs, chain/client/tests/catching_up.rs, chain/client/tests/chunks_management.rs, chain/client/tests/cross_shard_tx.rs, chain/network/tests/runner/mod.rs, core/chain-configs/src/client_config.rs
Fixes https://github.com/nearprotocol/nearcore/issues/2145.
I guess the problem was in very specific way of validators assigning in the test. Nodes try to build State Headers and asked for (previously deleted) chunks from ourselves, then fail because of having no chunks.
This fix turns off GC by adding `archive` flag and passes it to the config.
=> fix(chain): archive flag + test_catchup_receipts_sync_distant_epoch fix

chain/client/src/types.rs, chain/client/src/view_client.rs, chain/client/tests/chunks_management.rs, chain/client/tests/process_blocks.rs, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, chain/jsonrpc/tests/rpc_transactions.rs, core/primitives/src/rpc.rs, near/tests/rpc_nodes.rs, near/tests/run_nodes.rs, near/tests/stake_nodes.rs, near/tests/sync_nodes.rs, near/tests/sync_state_nodes.rs, near/tests/track_shards.rs, pytest/tests/sanity/block_production.py, test-utils/testlib/src/user/rpc_user.rs
Allow rpc to specify block finality when querying blocks. For example, previously we only allow queries like 
```
http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:=[48605]'
```
whereas the new API would allow
```
http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:={"block_id": 48605}'
```
as well as
```
http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:={"finality": "near-final"}'
```
Fixes #2175 
Test plan
---------
* Test that the new API is backward compatible by running old tests with the new API.
* Test that the new API works (sanity test `test_block_query`).
* Test in pytest `block_production.py` that the finality specified in the block rpc works properly.
=> Feat(rpc): add finality to block rpc

chain/chain/src/chain.rs, chain/chain/src/error.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, core/crypto/src/lib.rs, core/crypto/src/signature.rs, core/crypto/src/signer.rs, core/crypto/src/traits.rs, core/primitives/src/block.rs, core/primitives/src/errors.rs, core/primitives/src/validator_signer.rs, core/primitives/src/views.rs, genesis-tools/genesis-populate/src/lib.rs, near/src/runtime.rs, runtime/runtime/src/actions.rs, test-utils/state-viewer/src/main.rs
This implements a simple biasable randomness beacon. The work on the
unbiasable randomness beacon is here:
https://github.com/nearprotocol/nearcore/commits/rnd_integration
The biasable randomness beacon in this commit just uses the VRF created
by the current block proposer, thus it has 1 bit of influence (the block
proposer can choose not to create a block), which is sufficient for the
block producers rotation, but should be used with caution for other use
cases.
Test plan
---------
No new tests added as part of the change.
=> feat: Simple randomness beacon

chain/client/tests/chunks_management.rs, chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/test_utils.rs, chain/epoch_manager/src/types.rs
Currently when we save block info in epoch manager, we actually save it to a `StoreUpdate` as well as a cache, which does not get committed until `record_block_info` returns. However, inside `record_block_info` we might call `finalize_epoch`, which goes through all blocks in the epoch to gather data, which also invalidates everything in the cache if epoch length is larger than the cache size. Unfortunately if that happens `finalize_epoch` will fail and the chain stalls completely. This PR did two things to fix it:
* Do not assume that block info is available in storage after calling `save_block_info`. Instead we pass `last_block_info` to `finalize_epoch`.
* Eliminate the process of going through all blocks in the epoch in `finalize_epoch`, which is hugely inefficient in the first place. …
=> fix(epoch manager): fix incorrect usage of StoreUpdate

.gitignore, pytest/lib/cluster.py
Similar to #1985 but now we changed back to log to stderr
Test Plans
-------------
Run pytest locally, now it's no longer have `AssertionError: node dirs: 0 num_nodes: 4 num_observers: 0` error
=> fix: Fix pytest after log to stderr

chain/client/tests/catching_up.rs, chain/client/tests/cross_shard_tx.rs, nightly/nightly.txt, pytest/lib/cluster.py, pytest/tests/sanity/state_sync.py, pytest/tests/sanity/state_sync_routed.py, pytest/tests/sanity/transactions.py
Many timeout tweaks, and small typos.
`cross_shard_tx_with_validator_rotation` with 150 block time has
extremely long forks (doomslug is disabled), and takes lots of time per
iteration. I split it into two: one with 150ms block time, but only 16
iterations, and one with 400ms block time, but all 64 iterations. Both
locally take ~45 minutes, will see how long it takes on gcloud.
=> fix: Third wave of fixing nightly tests

chain/epoch_manager/src/lib.rs, nightly/nightly.txt, test-utils/testlib/src/node/process_node.rs, test-utils/testlib/src/node/thread_node.rs, tests/test_rejoin.rs, tests/test_simple.rs
Fixing the following issues:
1. `ThreadNode` was not properly setting its state on kill
2. `ThreadNode` doesn't properly free up its port, but instead of
figuring out why, I just replaced it with `ProcessNode` in the tests
that are affected
3. `test_4_20_kill1` wasn't accounting for fees. Disabling fees.
4. In the same test, the same chunk producer was always mapped to the
same block producer, and thus killing the second node was making the
0-th chunk producer (who happens to be attached to the 2nd BP) to not be
able to have their transactions included. Address it by having 17 seats.
Also split the test in two, with one shard and with two shards
5. In multiple places we were using the wrong node to get the access key
Test plan
---------
Locally `test_4_20_kill1` and …
=> fix: Fixing old rust multi-node tests

chain/client/tests/cross_shard_tx.rs, nightly/nightly.txt, pytest/tests/sanity/state_sync2.py, pytest/tests/sanity/state_sync_routed.py
Disabling old tests that fail due to the runtime cache unti they are
fixed;
Changing the `cross_shard_tx_with_validator_rotation` slightly based on
its performance on gcloud.
(increasing the block prod time speeds up test, because it results in
fewer forks, so the 150->200 change is to make more iterations fit.
With 150ms it fits ~6 iterations into one hour)
=> fix: Disabling some tests + small fixes

nightly/nightly.txt, pytest/tests/stress/stress.py
The test was not updated after some config parameters were renamed.
Also because of #2195, tx status of lost transactions times out, so
adding a workaround into the test for now
Disabling the version of stress that messes up with network, because the
nightly runner is currently not configured to support the utility I use
to stop network between processes
Couple other changes:
1. Made `node_restart` worker not restart the node if no blocks were
produced in the meantime. It is needed because with only two nodes after
a long restart doomslug can take a while to recover (it is equivalent to
half the network shutting down and restarting after some delay).
Block production worker will fail the test if the block production
actually stalls
2. For the same reason increased the tolerated delays for …
=> fix: Fixing stress.py

chain/chain/src/chain.rs, chain/chain/src/doomslug.rs, chain/client/src/client_actor.rs, chain/client/src/view_client.rs, chain/jsonrpc/src/lib.rs, chain/network/src/types.rs, nightly/nightly.txt, pytest/tests/adversarial/fork_sync.py, pytest/tests/adversarial/start_from_genesis.py
After Doomslug introduction, it's impossible to create a chain from genesis to overtake the current max block height. `start_from_genesis` test should take it to account.
Also fixes https://github.com/nearprotocol/nearcore/issues/2206.
=> fix(adversary): start_from_genesis test relies on Doomslug

chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/proposals.rs, chain/epoch_manager/src/test_utils.rs, chain/epoch_manager/src/types.rs, core/primitives/src/types.rs
Some fixes, refactoring and comments.
Test plan
---------
Run existing tests
Extra asserts in the code
=> fix(epoch_manager): Some fixes and comments

nightly/nightly.txt, pytest/lib/utils.py, pytest/tests/stress/stress.py
Further investigation of `stress.py` failures in nightly shows that all
the workers appear to work as expected, but frequent restarts cause
block production to be delayed more than the current tolerance.
Locally spradically also more than 50% of transactions get lost if the
node get restarted too frequently.
Increasing both tolerances.
Also making the prints unbuffered, otherwise several workers in the
nightly runs don't flush their outputs.
Finally, fixing a typo in the nightly.txt
Test plan
---------
Locally `stress.py` doesn't fail, so there's no easy way to test whether
the new tolerances would be sufficient.
It also doesn't completely fix all the known issues, there are some
other failures in stress.py that I haven't gotten to yet
=> fix: Increasing tolerance in stress.py, and fixing nightly.txt

Cargo.lock, chain/telemetry/Cargo.toml, scripts/binary-release.sh
scripts for binary release
Test Plan
------------
Download uploaded binary in a few popular linux vm and see if they works
=> Add binary release script

pytest/Pipfile, pytest/Pipfile.lock, pytest/requirements.txt, pytest/tests/stress/hundred_nodes/start_100_nodes.py
Two people run 100 node together is often blocked by firewall rules limit and static ip address limit (The recent fail by @mfornet is this case). Made they do not reserve ip address and use organization global firewall rules would fix this.
Test Plans
--------------
The same setting has been proved to work in create devnet nodes.
=> Improve 100 node test to not reserve static ip and firewall rule

chain/epoch_manager/tests/finality.rs
In one of the recent changes a check was added to the epoch manager that
disallows duplicate proposals on construction. NFG tests do not rely on
the actual proposals, and were using the same name for all of them.
Fixing to use different names.
Test plan
---------
Both `test_fuzzy_safety` and `test_fuzzy_light_client` pass
=> fix: Fixing a minor issue that was causing NFG tests to fail

Cargo.lock, chain/chain/Cargo.toml, chain/chunks/Cargo.toml, chain/client/Cargo.toml, chain/epoch_manager/Cargo.toml, chain/network/Cargo.toml, core/store/Cargo.toml, runtime/near-vm-runner/Cargo.toml, runtime/runtime/Cargo.toml
Update `hits` counter in `cached` to `u64` to avoid overflowing the counter. It will now take more than one million years to overflow the counter given the current estimate, which I think is acceptable.
Test plan
---------
Make sure all existing tests pass.
=> fix: update cached version to avoid overflow

Cargo.toml, chain/client/Cargo.toml, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/client/src/types.rs, chain/client/tests/process_blocks.rs, chain/network/Cargo.toml, chain/network/src/lib.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/recorder.rs, chain/network/src/routing.rs, chain/network/src/types.rs, chain/network/src/utils.rs, near/Cargo.toml
This PR expose extra information about networking via RPC. Using this data you can create a dashboard using [near-node-debug](https://github.com/nearprotocol/near-node-debug). It provides the following information:
- Number of peers
- Network diameter
- Network topology
- Latency between every pair of nodes (heat map with hover for detailed info)
- Bytes transferred between every pair of nodes (heat map with hover for detailed info)
- Messages transferred between every pair of nodes (heat map with hover for detailed info)
- Bytes received by one node separated by type.
- Total message received by one node separated by type.
- Number of peers each node has:
=> feat(network): Network metric recorder

chain/client/src/test_utils.rs, chain/client/src/view_client.rs, chain/network/tests/runner/mod.rs, near/res/testnet_genesis_hash, near/src/config.rs, near/src/lib.rs, near/src/main.rs, test-utils/state-viewer/src/main.rs
Given we never separately update genesis config part of genesis record part, it make sense to only host combined genesis.json on s3 and this is easier to keep genesis.json consistent with other node in devnet, betanet and testnet. Up to date config part of genesis.json (near/res/testnet_genesis_config.json) should be commited at every genesis change happens and as a nice debug helper, but devnet/betanet/testnet node should rely only on hosted s3 for both config and genesis.
Test Plan
------------
Manually test near init, w/o chain-id=testnet/devnet, state-viewer dump_state and near run after change.
=> Remove genesis split

Makefile
[nearup](https://github.com/nearprotocol/nearup) uses `--binary-path` to run near with both binary compiled from ci and binary compiled locally. It's therefore easier for local dev to just `make release`/`make debug` and `nearup`
Test Plan
------------
Run `make release` and `make debug` locally
=> feat(script): add compile necessary binary for nearup

Makefile, scripts/binary-release.sh
vm standalone is useful in near-runtime-ts ci and state-viewer is in automate betanet/testnet state upgrade
Test Plans
-------------
Run manually
=> Upload also vm standalone and state-viewer binary

scripts/binary-release.sh
Fix a stupid typo i did yesterday
Test Plans
-------------
Run script locally. Next time I need to be more careful on script change
=> fix(script): typo in binary-release

chain/chain/src/store.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, core/primitives/src/rpc.rs, core/primitives/src/types.rs, core/primitives/src/utils.rs, core/primitives/src/views.rs, core/store/src/lib.rs, core/store/src/trie/mod.rs, pytest/tests/sanity/rpc_state_changes.py
*Resolves #2129*
I opted to just replace `account_id` input arguments with `account_ids` expecting a list of those. It is technically a breaking change, but since the API is experimental, it should be expected to evolve rapidly.
Documentation request is here: https://github.com/nearprotocol/docs/issues/173
`EXPERIMENTAL_changes` RPC endpoint accepts the following types of requests:
```js
{
"block_id": /* block hash | block height | omit it if you want to use `finality` */,
"finality": /* "latest" | "final" | "near-final" | omit it if you want to se `block_id` */,
"changes_type": /* "account_changes" | "single_access_key_changes" | "all_access_key_changes" | "contract_code_changes" | "data_changes" */,
/* extra fields based on `changes_type` */
}
```
the extra fields based on …
=> feat(chain): Extend `changes` RPC API to allow querying multiple accounts at once

pytest/lib/branches.py, pytest/lib/cluster.py, pytest/tests/sanity/backward_compatible.py, pytest/tests/sanity/state_migration.py, scripts/migrations/5-preserve-height.py
This adds to new python tests:
- Run `beta` branch binary and current branch binaries together as two validating nodes. Ref #1573
- Run `beta` branch binary, dump state, migrate and start current branch from the dumped state.
TODO: add sending transactions and also running for few epochs to catch other issues between version for both tests.
TODO: @ailisp please add:
- we should be calling `state_migration.py` for all changes on CI.
- calling `backward_compatible.py` test as a separate non-blocking step to the CI. 
This way we will always know when we broken something in the PR.
Also if we are publishing binaries for beta/stable -> can you also add it there instead of re-compiling?
=> test: Adding backward compatibility & state migration tests

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/client/src/client_actor.rs, pytest/lib/cluster.py
<s>The reason of turning off checking refmap is to stop supporting legacy version of GC.
All necessary checks will be added after #2084.</s>
Refcount checks is fixed at current version of GC.
Also extends refcount error messages and adds some make ups.
=> fix(GC): refcount map compatibility with current GC

chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/tests/challenges.rs, chain/client/tests/process_blocks.rs, core/primitives/src/block.rs, core/primitives/src/sharding.rs
There is a memory leak in the reed solomon code that we use https://github.com/darrenldl/reed-solomon-erasure/issues/74 which results in our nodes crashing after reaching about 100k blocks. This PR fixes it by occasionally reinstantiating the reed solomon instance and cap its memory usage at 500MB.
Test plan
---------
Make sure existing tests pass.
=> fix: resolve Reed Solomon memory leak by occasionally reinstantiating

chain/client/src/view_client.rs
Don't show to user epoch out of bound error by default. Use debug instead.
Address #2297
=> nit: Avoid warn on epoch out of bound error.

runtime/near-runtime-fees/Cargo.toml, runtime/near-vm-errors/Cargo.toml, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner/Cargo.toml
The current versions of the runtime are outdated and are breaking CI on near-sdk-rs
=> Bump runtime versions to 0.7.0

chain/client/src/sync.rs, chain/network/src/peer_manager.rs, near/src/config.rs
Also:
- make header sync parameters read from config (and some that were already from config but were not used).
- increase default timeout for stalling in header sync to 120s.
- don't report error about failing to send message when peer is not active any more as it's expected that message doesn't go.
Fix #2305
Test Plan
---------
Run nodes on slow network and see that it doesn't get banned.
With lower header sync limit, observe that it doesn't try to re-request from banned peer.
=> fix(sync): Stop requesting headers from banned peer

chain/chain/src/chain.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/client/tests/bug_repros.rs, chain/client/tests/catching_up.rs, chain/client/tests/chunks_management.rs, chain/client/tests/cross_shard_tx.rs, chain/client/tests/process_blocks.rs
When a node is syncing from peers, it might obtain blocks that are garbage collected for a normal node from an archival node. When this happens, the node can rebroadcast the block to its peers. However, since we do not have any check for old blocks that might have been garbage collected, all peers that are not archival node will consider this block "new" and rebroadcast again. Since in `process_block_header`, this causes an infinite loop of rebroadcasting and therefore the network crash. This PR fixes both issues by 1) checking orphan pool in `process_block_headers` and 2) have a check for blocks that are older than one epoch.
Test plan
---------
* Integration test `test_sync_from_achival_node` that tests the scenario mentioned above. Notice that due to a timing issue, it is very hard to …
=> fix: do not rebroadcast very old blocks

pytest/lib/branches.py
branch name isn't escaped and branch name has `/` fails in state-migration
Test Plan
------------
This branch has `/` and should success
=> fix(script): state migration for slash in branch name

chain/jsonrpc/res/rpc_errors_schema.json, chain/jsonrpc/src/lib.rs, core/chain-configs/src/lib.rs, core/primitives/src/errors.rs, core/runtime-configs/src/lib.rs, near/res/testnet_genesis_config.json, pytest/lib/branches.py, runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs, scripts/migrations/7-account-registrar.py
Disabling creation of top-level account IDs shorted than 11 characters, except if created by `registrar`.
- Adding a new error that tells that the account has to be created by `registrar`
- Adding config to do this
- Adding migration script
- Bumping protocol version
- Adding `registrar` account
NEP: https://github.com/nearprotocol/NEPs/pull/45
Fixes #2292
- CI
- State migration test
- Extra tests for account ID creation.
=> feat: Disable creation of short top-level account ids

chain/chunks/src/lib.rs, chain/client/tests/bug_repros.rs, chain/client/tests/process_blocks.rs, chain/jsonrpc/tests/rpc_query.rs, near/src/runtime.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/verifier.rs, runtime/runtime/tests/test_async_calls.rs, scripts/testlib.py
Make tests run again.
Script should be looking at a different directory for test binaries, most likely broke 
during rust-toolchain update.
Test plan
---------
Check that this is not the case anymore: ========= collected 0 test binaries:
=> fix: running tests in CI

core/runtime-configs/src/lib.rs, near/res/testnet_genesis_config.json, runtime/runtime/src/actions.rs, scripts/migrations/7-account-registrar.py
Disables requirement to create top-level accounts with `registrar`.
By setting min allowed length to 0. It will allow testing of app-layer when `registrar` requirements are needed.
- Added unit-test to verify
- CI
=> fix: Disable top-level registrar requirement

near/src/runtime.rs
The test already passes because of https://github.com/nearprotocol/nearcore/pull/2362. Fixes #2367.
Test plan
---------
Make sure that `test_validator_rotation` passes.
=> fix: enable validator rotation test

chain/chain/src/chain.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/test_utils.rs, chain/client/tests/bug_repros.rs, chain/client/tests/catching_up.rs, chain/client/tests/challenges.rs, chain/client/tests/chunks_management.rs, chain/client/tests/cross_shard_tx.rs, chain/client/tests/process_blocks.rs, chain/jsonrpc/src/lib.rs, chain/network/src/peer.rs, chain/network/src/types.rs, near/tests/stake_nodes.rs, near/tests/sync_nodes.rs
Right now we only forward transaction to one chunk producer in 4 blocks. It is possible that 1) the chunk producer for that slot received the transaction after they already produced the chunk due to some network glitch and 2) the chunk producer wasn't able to produce the chunk because the previous block is skipped. To protect agains it, this PR changes it so that we route the transaction to both the chunk producer in 4 blocks and the chunk producers in 8 blocks. Since chunk producer would remove transactions from the mempool that are already in existing chunks, this shouldn't cause any harm other than more traffic in the network. Resolves #2357.
Test plan
---------
`test_tx_forwarding` that tests two forwarding requests are generated when tx routing happens.
=> fix: improve tx routing

chain/client/tests/process_blocks.rs, nightly/nightly.txt
Fixes `test_gc_with_epoch_length`. It failed because now `clear_block_data` clears the data on the previous block if the block is on the canonical chain. Also increases timeout on nightly gc tests. Resolves #2368.
Test plan
---------
Make sure that `test_gc_with_epoch_length` passes.
=> fix: gc test

runtime/runtime/tests/test_async_calls.rs
Increase deposit amount to pay for basic account storage.
The rest are passing because `registrar` top-level names are disabled now.
Fixes: #2370
- unit tests
=> fix: Fix async tests. 

scripts/binary-release.sh, scripts/docker-release.sh
buildkite use HEAD as commit when trigger a manual build on ui. This isn't a problem for most task but is problematic for binary and docker release. This one tag docker image and name binary to HEAD:  https://buildkite.com/nearprotocol/nearcore/builds/596#35b319ac-a0e9-45e5-816a-24263ee11388 
Test Plan
------------
Locally set BUILDKITE_BRANCH, set BUILDKITE_COMMIT to HEAD and echo
=> fix(script): avoid buildkite manual build use HEAD as version

nightly/nightly.txt
`test_gc_not_remove_fork_large` needs more time to execute
=> fix(gc): increased tests timeout

chain/chain/src/chain.rs, chain/client/tests/bug_repros.rs
When we clear block data in gc the way to tell whether there is a fork is wrong. We should look at block refcount instead of whether there are multiple blocks at a height, since there can be a fork with heads on different heights. However, this doesn't fix the deeper issue #2386. Resolves #2366.
Test plan
---------
`test_sync_from_achival_node` passes
=> fix: test_sync_from_achival_node

nightly/nightly.txt
Fix nightly after near->neard. Also a little rename happens in https://github.com/nearprotocol/nightly/commit/8e3640d8dc0aa851529c525d1e83cfb0381992c6
Test Plan
------------
Simulate nightly runner test run pytest locally
=> fix(script): nightly after near->neard

core/primitives/src/trie_key.rs
*Resolves #2408*
I realized that I missed the fact that there is indeed a separator `col::ACCESS_KEY`, so the storage key is, essentially, constructed as `col::ACCESS_KEY + account_id + col::ACCESS_KEY + serialized_public_key`! I missed the fact that it is a constant there, which can be used instead of the magical `2`!
No tests are needed, the magical `2` was the correct const.
=> refactor(core): Fixed potentially dangerous implementation of parse_account_id_from_access_key_key

chain/chain/src/chain.rs, chain/client/tests/process_blocks.rs
Currently in `clear_data`, if there is no blocks between tail and gc_stop_height, we would just run through the entire loop without updating tail, which leads to gc getting stuck. This PR fixes it by updating the tail even when there is no block at some height. Notice that this means that tail height doesn't necessarily imply the existence of a block at that height, but given that we only use it for gc purposes, I think it is fine.
Test plan
---------
`test_gc_tail_update` passes.
=> fix: tail should be updated when there are skips

chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/peer_store.rs, chain/network/src/types.rs, chain/network/tests/churn_attack.rs, chain/network/tests/full_network.rs, chain/network/tests/routing.rs, chain/network/tests/runner/mod.rs
There was an issue on handshake when two nodes tried to
connect to each other, in which they were not removed successfully
from outgoing list, and were unable to make progress.
There was another issue uncovered by the fix of previous issue
that in the scenario when A and B try to connect to each other,
when B drop its outgoing connection to A, it also drops the inbound
connection.
We introduce a test for #2395. This test is still failing and will
be fixed on a future PR. (connect_on_full_network)
Test plan
=========
There are two regression test for fixed issues that verify handshake
is performed properly. (simple_network & peer_handshake) Notice the
latter test already existed, and was important in detecting the
second uncovered issue.
=> fix(network): Fix issue on handshake.

pytest/tests/stress/hundred_nodes/start_100_nodes.py
Do not telemetry in 100 node
Test Plan
-------------
commented create machine part locally, only generate 100 node configs. check they're updated correctly
=> fix(script): Do not telemetry in 100 node

scripts/migrations/5-preserve-height.py
Update the migration script to protocol version 5 to make sure that it works for testnet.
Test plan
---------
Use the same genesis as currently running testnet to spin up a local node. After it produces blocks for a while, stop it and dump its state using the state-viewer in `stable`. Then apply `5-preserve-height.py`, `6-state-stake.py`, and `7-account-registar.py` to obtain the migrated genesis file. Then spin up a node with binary compiled from beta branch and make sure that the node can start and produce blocks.
@ailisp please independently verify that the migration scripts work.
=> fix(script): prepare for testnet update

chain/client/src/client_actor.rs, chain/client/src/info.rs
Currently the sync status is off because we use 0 instead of genesis height as the base.
Test plan
---------
Manually test it with betanet to check that the displayed information makes sense.
=> fix: display correct sync status

pytest/empty-contract-rs/Cargo.toml, pytest/empty-contract-rs/src/lib.rs, pytest/lib/cluster.py, pytest/tests/contracts/deploy_call_smart_contract.py, pytest/tests/sanity/state_sync2.py
https://nightly.neartest.com/run/c1ba86d68438f22d25235ba66e2254439d55e9c4_200406_171929/expensive/expensive_near_sync_state_nodes_sync_state_nodes_multishard/stderr
: fixed in #2401 
https://nightly.neartest.com/run/c1ba86d68438f22d25235ba66e2254439d55e9c4_200406_171929/pytest/pytest_contracts_deploy_call_smart_contract_py/stderr: fixed here
0 stdout and 0 stderr of state_sync2: Possibly fixed using the same trick used the parallel_run_test.py. Also If still no output, added print to ensure it's stdout cached instead of there's really no output
Test Plan
------------
deploy_call_smart_contract passed locally
=> fix(script): nightly test

core/chain-configs/src/genesis_config.rs, neard/src/genesis_validate.rs, neard/src/lib.rs, neard/src/main.rs
Validate genesis to check that various invariants hold before starting the node. Partially addresses #2435.
Test plan
---------
unit tests in `validate_genesis.rs`.
=> fix: validate genesis

Cargo.lock, test-utils/state-viewer/Cargo.toml, test-utils/state-viewer/src/main.rs, test-utils/state-viewer/src/state_dump.rs
Currently state dump can cause inconsistency between validators in genesis and the state records. This PR fixes the issue by enforcing the following rules:
1) Validators in the new genesis after the state dump are validators from the epoch during which state dump happens.
2) For those that stake and change their stake during the last epoch, the change to state is reset. For example, if someone stakes during the last epoch, their stake will be returned back to balance and locked amount becomes 0.
Resolves #2435.
Test plan
--------
* `test_dump_state_preserve_validators` that tests we preserve the validators from last epoch.
* `test_dump_state_return_locked` that tests we return locked balance for nonvalidators.
=> fix(state viewer): fix state dump inconsistency

neard/src/main.rs
Fixes #2429 
Test plan
----
Version is printed at the start of the binary
=> Add log of version and build

chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/peer_store.rs, chain/network/src/test_utils.rs, chain/network/src/types.rs, chain/network/tests/ban_peers.rs, chain/network/tests/runner/mod.rs
Previously if a banned peer tried to connect it was allowed. Fix #2455 
Test plan
=========
Start two nodes, check they connect to each other. Ban one of them.
Wait until they disconnect. After some timeout they shoud remain
disconnected i.e. don't allow incomming connection from banned peers.
After larger timeout (ban_windows) peers should be able to reconnect.
Because first `timeout` might be fuzzy I set large timeout (1 second)
and also test by hand that without the change introduced in the PR
this test fails.
=> fix(network): Don't allow connections from banned peers.

chain/chain/src/chain.rs, neard/src/config.rs, pytest/tests/sanity/state_sync3.py
Currently there is a potential infinite loop in state sync: if the node that is syncing cares about the shard, it will not be able to process sync block immediately, which will likely cause the node to go back into state sync after it is done (unless the sync block is close to header head), and because sync block is already removed at this point, future state syncs will get stuck as well after they are done. This PR fixes the issue by relaxing the criterion of entering block sync to allow block sync even if the head is one epoch behind. This is harmless in most scenarios, as a node would first do state sync anyways, unless it is right in the range of (one epoch, two epochs) behind header head.
Fixes #2374.
Test plan
---------
`state_sync3.py` that tests the scenario described above.
=> fix(sync): fix state sync infinite loop

core/crypto/src/signature.rs
This is useful for tests (reverted the test I did for as Marcelo fixed the issue).
Test plan
---
Updated a test to check that try_from coverts back from to_string().
=> Moved deserialization into try_from for string to Signature

scripts/migrations/9-state-record-data.py
There's trivial error in migration script. It wasn't caught because ci state migration is tested on `neard init` genesis, which doesn't have Data records. Also fix validator section inconsistent issue due to old state viewer bug, it's needed for betanet and testnet upgrade.
Test Plan
------------
Run script again diff with yesterday's manual fix
=> fix(script): migration for betanet and testnet

chain/client/src/client_actor.rs
=> fix: Use run_interval for log_summary

chain/network/src/codec.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/peer_store.rs, chain/network/src/recorder.rs, chain/network/src/routing.rs, chain/network/src/test_utils.rs, chain/network/src/types.rs, chain/network/tests/peer_handshake.rs, chain/network/tests/runner/mod.rs
Currently if peer_id A goes offline and in the same address
a new peer_id B appears, nodes will try to connect to B as if it were
A, receiving a lot of invalid handshakes.
Also check that we don't try to connect to ourself.
This solution introduce some complexity on how PeerStore is handled,
since now we need to know about address associated with each peer id
and updated properly, and at the same time protect against malicious
actors that tries to manipulate this mapping. Fix #2456 
Test plan
=========
It was created a test that replicated the issue, by creating two
nodes A and B, taking down B, changing it identity, and spawning it
again at the same address. A and B are able to connect again, since
A was able to learn the new identity from B.
Also a lot of small test were created to test …
=> fix(network): Remove address when nodes goes off.

chain/client/src/client_actor.rs
This reverts commit 601c8d72811bd12d38a29046a1f53e8844640e0a.
Fixes #2464.
=> Revert "disabling State Sync Clearing optimization (#2484)"

nightly/nightly.txt, pytest/tests/sanity/block_sync.py, pytest/tests/sanity/garbage_collection.py, pytest/tests/sanity/garbage_collection1.py, pytest/tests/sanity/gc_after_sync.py, pytest/tests/sanity/gc_sync_after_sync.py, pytest/tests/sanity/one_val.py, test-utils/testlib/src/node/process_node.rs, tests/test_rejoin.rs
Fix two kinds of failures on nightly:
* Since we now do not calculate total supply at deserialization time, some tests fail because they modify some records but not the total supply.
* `test_4_20_kill1` and `test_4_20_kill1` failed because of the neard binary change.
Test plan
---------
Running tests locally and see that they pass.
=> fix(nightly): fix some nightly tests

chain/chain/src/chain.rs, chain/client/src/lib.rs, chain/client/src/test_utils.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_transactions.rs, chain/network/tests/runner/mod.rs, neard/src/lib.rs
Return if tx status is missing on the node that track this shard. Fixes #2488 
CC @frol `tx` rpc actually is not having proper typed errors. I'm not fixing it here, but it's worth reviewing that.
Test Plan
----
Add a test that for a single node if query missing transaction, it returns error right away instead of Timeout.
=> fix(rpc): Fix returning missing tx error

Cargo.lock, chain/chain/Cargo.toml, chain/chain/src/error.rs, chain/chain/src/store.rs, chain/client/tests/process_blocks.rs
*Resolves #2319*
The missing block is detected based on the availability of the block header. The block headers persist over garbage collection.
=> feat(chain): Make a separate error kind for a missing (not available) block

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/client.rs, chain/client/tests/challenges.rs, chain/client/tests/process_blocks.rs, core/chain-configs/src/lib.rs, neard/res/genesis_config.json, neard/src/runtime.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/verifier.rs, scripts/migrations/10-gas-price-fix.py
There is an off-by-one error that can cause a transaction which is valid when it is included in a chunk later becomes invalid when it is applied due to a change in gas price. This PR also refactors `verify_and_charge_transaction` to take `gas_price` instead of `apply_state` as an argument so that we don't pass a lot of unnecessary arguments around and make it easier to understand what the function requires.
Test plan
---------
* Make sure that `test_gas_price_change`, which reproduces the failure we had, passes.
=> fix: pass correct gas price to runtime

core/primitives/src/state_record.rs, test-utils/state-viewer/src/state_dump.rs
Fix the error of entering `unreachable` when encountering `DELAYED_RECEIPT_INDICES`. @evgenykuzyakov please let me know if it makes sense to ignore delayed receipt indices.
Test plan
---------
`test_dump_state_with_delayed_receipt` that tests dumping state with delayed receipt.
=> fix(state dump): delayed receipts

chain/chain/src/chain.rs, chain/chain/src/types.rs, chain/client/src/client.rs, chain/client/src/view_client.rs, chain/client/tests/process_blocks.rs, neard/src/runtime.rs
Fix several issues regarding transaction and tx status request routing:
* If a transaction is submitted through a nonvalidator, we don't consider the case where it is close to the epoch boundary and might forward to wrong validators.
* When a validator receives a transaction, they check whether they are an "active validator" without considering epoch boundary.
* https://github.com/nearprotocol/nearcore/pull/2494/ broke transaction status request routing. If the transaction has receipts that will be processed in some other shards, the validator will never request the receipt result.
Test plan
---------
`test_tx_forward_around_epoch_boundary` that tests transaction forwarding from nonvalidator works on epoch boundary.
`rpc_query.py` does not fail with transaction timeout.
=> fix: fix several issues around transaction and transaction query routing

chain/epoch_manager/src/lib.rs, chain/epoch_manager/src/types.rs
The current way of counting expected number of chunks for a chunk producer is flawed. While I took into consideration that when a block is not produced, not chunk can be included in that block, I failed to realize that if block at height `h` is not produced, chunks at height `h` can be included in block `h+1`, if it is produced. Therefore, what we really need to count when processing a block is whether chunk producers for height `prev_block_height + 1` produced their chunks. Resolves #2534.
Test plan
---------
`test_expected_chunks_prev_block_not_produced` that tests when a chunk producer failed to produce a chunk due to the block at previous height not being produced, it does not get kicked out.
=> fix: correctly count chunk produced

Cargo.lock, deny.toml, runtime/near-vm-runner/Cargo.toml, runtime/near-vm-runner/src/errors.rs
Due to https://github.com/wasmerio/wasmer/issues/1409 we need to rollback Wasmer to older version. I am replacing some of Wasmer generated error with Unknown to avoid undoing too much code from this PR: https://github.com/nearprotocol/nearcore/pull/2505
After the following PR lands https://github.com/wasmerio/wasmer/pull/1401 we would need to revisit error handling from Wasmer anyway. CC @fckt  
Ran near-evm test. CI passes.
=> fix(runtime): Rollback Wasmer to older version

pytest/tests/sanity/state_sync2.py
`state_sync2.py` was not written correctly. The number of shards specified does not match the number specified in `num_block_producer_seats_per_shard`. Resolves #2548 
Test plan
---------
Make sure `state_sync2.py` works locally.
=> fix(pytest): fix state_sync2.py

pytest/tests/sanity/rpc_state_changes.py
rpc_state_changes.py sometimes fails because on the first block of an epoch there is state change to validator accounts when reward is added. This PR fixes it by using an epoch length that is sufficiently long. Fixes #2541 
Test plan
---------
* `rpc_state_changes.py` passes.
=> fix(pytest): fix rpc_state_changes.py

chain/chain/tests/doomslug.rs, nightly/nightly.txt
Two doomslug-related tests had timeouts slightly lower than needed;
`test_fuzzy_doomslug_liveness_and_safety` had a way to create short
forks by malicious actors, but those forks were violating doomslug
invariants (specifically, blocks that did not have enough endorsements
could be produced), and under certain conditions the test would find a
situation in which one such block is not built on top of a final block.
Removing that logic from the test;
Fixes #2553
=> fix(chain): Fixing several nightly failures

pytest/tests/sanity/block_sync.py
bloc_sync.py failed because on each shard there is only one chunk producer and therefore when the chunk producer cleared data, it has no way to recover the chunks and therefore cannot process synced blocks. Fixes #2543 
Test plan
---------
`block_sync.py` passes locally.
=> fix(pytest): fix block_sync.py

pytest/tests/sanity/skip_epoch.py
The test was relying on a single block producer being able to finalize
an epoch, which is not possible any longer. Fixing it by increasing the
number of block producers to four (with one offline the remaining three
can still finalize the epoch)
Fixes #2546
=> fix: Fixing skip_epoch.py

pytest/tests/sanity/gc_sync_after_sync.py
`gc_sync_after_sync.py` fails because we cannot finalize an epoch without three consecutive blocks, which was not possible under the old configuration. Fixes #2540 
Test plan
---------
`gc_sync_after_sync.py` passes locally.
=> fix(pytest): fix gc_sync_after_sync

chain/network/src/peer_manager.rs, chain/network/src/test_utils.rs, chain/network/src/types.rs, chain/network/tests/churn_attack.rs, chain/network/tests/full_network.rs, chain/network/tests/infinite_loop.rs, chain/network/tests/peer_handshake.rs, chain/network/tests/routing.rs, chain/network/tests/runner/mod.rs, neard/src/config.rs
All network parameters can be manipulated from config file.
Invalid network arguments won't  lead to panic anymore,
but only error message will be displayed.
Fix #2521
=> [refactor]: Move network parameters to config.

chain/client/src/client.rs
active_validator was wrong at the last block in the epoch.
That breaks forwarding because when active_validator is true
it only considers the future epoch, and since that's far ahead
it does not forward at all.
Test plan
---------
transactions.py
=> fix(client): fix active_validator

pytest/tests/sanity/restaked.py
`restaked.py` failed because epoch boundary is now shifted a bit if a validator is offline. Fixes #2542 
Test plan
---------
`restaked.py` passes locally.
=> fix(pytest): fix restaked

pytest/tests/sanity/skip_epoch.py
Locally it was still flaky if ran 100 times. With the extra check for
the seen heights haven't reproduced the failure.
Posting the correct way to fix into the #2546, in case it starts
behaving flaky again
=> fix: Further harnessing skip_epoch.py

chain/network/src/peer_manager.rs, chain/network/src/routing.rs, pytest/tests/sanity/state_sync_routed.py
While choosing neighbor node to send a message that is going
to be routed, if the list of neighbors is two, and they are sorted
by nonce there was a bug that indicated that target node was
disconnected.
Test Plan
=========
In sanity/state_sync_routed.py check that no message is dropped
because a Peer is Disconnected, this should only happen when
peer which was online goes offline (not the case in this test).
Fix #2547
=> fix(network): Compute neighbor properly.

pytest/tests/sanity/gc_sync_after_sync.py
The test fails because when swap happens, there are two nodes not producing blocks and the rest cannot produce blocks due to not having enough stake. I didn't notice it previously because I for some reason think the argument is `swap` instead of `swap_nodes`.
Test plan
---------
`gc_sync_after_sync.py swap_nodes` passes
=> fix(pytest): fix gc_sync_after_sync swap_nodes

chain/chain/src/chain.rs, chain/chain/src/store.rs
Currently, we're not using any data from Genesis Block in State. According to https://github.com/nearprotocol/nearcore/issues/2570, it's not enough to not erase Genesis data from State to keep it useful. So, it's better to remove Genesis data from State at all.
Fixes https://github.com/nearprotocol/nearcore/issues/2570
Plan to test: CI + sanity python tests (gc_after_sync, gc_sync_after_sync, gc_sync_after_sync swap_nodes).
=> fix(GC): removing Genesis Block from State

pytest/tests/sanity/state_sync_routed.py
`sanity/state_sync_routed.py` fails at:
```
assert tracker4.count("Consolidated connection with FullPeerInfo") == 2
```
because there is no enough time for the node to get both active connections.
Fix #2547
=> fix(test): Wait for node to have two connections.

Cargo.lock, Cargo.toml
Pins `actix-rt` version `1.1.1` to fix the memory leak caused by https://github.com/actix/actix-net/issues/129. Resolve #2593.
Test plan
---------
Existing tests pass.
=> fix: resolve actix memory leak

.dockerignore
Currently all docker build has "-modified" in its version (e.g. nearup devnet) it's because some file isn't send to docker daemon.
Test Plan
------------
`make` and `docker run nearcore near --version` should not show modified.
=> Fix(script): docker build should not show version modified

chain/network/src/lib.rs, chain/network/src/metrics.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/peer_store.rs, chain/network/tests/peer_handshake.rs, chain/network/tests/runner/mod.rs, core/metrics/src/lib.rs
If a node receives info about itself from other nodes
it was possible it tries to establish connection with itself.
Fix #2601
=> fix(network): Avoid peers connecting to itself.

tests/test_rejoin.rs
cargo isn't available when run nightly tests in parallel containers.
Test Plan
------------
run test with NIGHT_RUNNER defined, cargo build should be skipped. run test directly cargo build should not be skipped.
=> fix(test): skip when run in nightly runner

test-utils/testlib/src/node/process_node.rs
When run locally, `fn warmup` will compile neard binary. When run in nightly, binary is prebuilt by script. 
Test Plan
------------
```
docker run --rm -u $UID:$UID -w /home/bo/workspace/nearcore2 -e NIGHTLY_RUNNER=1 -e CARGO_MANIFEST_DIR=/home/bo/workspace/nearcore2/test-utils/testlib -v /home/bo/workspace/nearcore2/target/debug/deps/cross_shard_tx-779ceb73f76760d6:/home/bo/workspace/nearcore2/target/debug/deps/cross_shard_tx-779ceb73f76760d6 -v /home/bo/workspace/nearcore2/runtime/near-vm-runner/tests/res/test_contract_rs.wasm:/home/bo/workspace/nearcore2/runtime/near-vm-runner/tests/res/test_contract_rs.wasm -w /home/bo/workspace/nearcore2 -it ubuntu:19.04 /home/bo/workspace/nearcore2/target/debug/deps/cross_shard_tx-779ceb73f76760d6
```
to simulate parallel nightly
=> fix(test): run in nightly container has no cargo

core/primitives/src/sharding.rs
After discussion with @SkidanovAlex, we realize that my previous way of restricting memory usage of a reed solomon instance undercount the memory usage at least 30x. This PR reduces the number of ttl for a reed solomon instance to limit its memory usage to about 60MB.
Test plan
---------
Existing tests pass.
=> fix: restrict reed solomon memory usage

Cargo.lock, runtime/runtime-params-estimator/Cargo.toml, runtime/runtime-params-estimator/src/cases.rs, runtime/runtime-params-estimator/src/ext_costs_generator.rs, runtime/runtime-params-estimator/src/runtime_fees_generator.rs, runtime/runtime-params-estimator/src/stats.rs, runtime/runtime-params-estimator/src/testbed_runners.rs, runtime/runtime-params-estimator/src/wasmer_estimator.rs
Switch to using rational numbers when computing runtime costs,
and avoid attempts to deduce the cost of the compound computations.
Test Plan
------------
Run cost estimators in both time and icount modes.
=> feat(runtime costs): simplify cost computations

core/primitives/src/types.rs
Sometimes we notice the following error from RPC:
```json
{
"jsonrpc": "2.0",
"error": {
"code": -32000,
"message": "Server error",
"data": "u128 is not supported"
},
"id": "dontcare"
}
```
=> fix(primitives): Fixed serialization of balances in ValidatorKickoutReason

pytest/tests/sanity/rpc_state_changes.py
rpc_state_changes.py fails because of the gas provided to function calls becomes insufficient after #2574.
Test plan
---------
Make sure `rpc_state_changes.py` pass locally.
=> fix(nightly): rpc_state_changes

nightly/nightly.txt
In nightly fail now, this two test fails because it needs about 10% to 20% more time when run in parallel nightly:
https://nightly.neartest.com/test/expensive/expensive_near-chain_doomslug_tests__test_fuzzy_doomslug_liveness_and_safety
https://nightly.neartest.com/test/expensive/expensive_near-chain_gc_tests__test_gc_boundaries_large
This two test passed before parallel nightly is deployed (~May 8th), now they timeout but generate no error stdout 10% smaller than before May 8th, so giving it 10%-20% time it should pass. To ensure I give double time.
Test Plan
------------
This two test passed when i submit a modified nightly.txt: NIGHTLY_TXT_URL="https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nightly/output/master_fc193cfe563d21580da1f3673f5fed840887f8ef_20200513_194903/fails.tx …
=> fix(test): increase always timeout tests timeout in parallel nightly

test-utils/testlib/src/node/process_node.rs
Nightly expensive tests use --all-features to build, but some expensive test need a neard build without `--all-features`, if, use same target dir, will cause those expensive tests recompiling after compile the neard
Test Plan
------------
Precompile neard in nightly.py to normal_target dir
=> Fix(script): normal target to avoid flag mess up in nightly

Cargo.lock, Cargo.toml, Makefile, chain/chain/src/store.rs, chain/chain/tests/gc.rs, chain/client/src/client_actor.rs, chain/jsonrpc/src/lib.rs, chain/network/src/types.rs, core/store/Cargo.toml, core/store/src/db.rs, core/store/src/lib.rs, core/store/src/validate.rs, pytest/lib/cluster.py, scripts/binary-release.sh, test-utils/store-validator/Cargo.toml, test-utils/store-validator/src/main.rs
Resolves https://github.com/nearprotocol/nearcore/issues/2649
This PR introduces `store-validator` utility. It may be executed:
- As a separate binary which checks the storage:
- As a part of python tests infrastructure, it executes automatically:
- As an adversarial method `AdvCheckStorageConsistency` anywhere in CI / expensive tests or debugging
=> feat(storage): Storage Consistency Test Infrastructure

chain/chunks/src/lib.rs, chain/client/src/client_actor.rs
`ShardsManager::resend_chunk_requests` returned a `Result` type, but never actually returned any error. We change the return type to `()` to make it clear this call will not fail.
Other miscellaneous changes:
* remove an unnecessary `clone` call in `ShardsManager::get_random_shard_block_producer`
* change `near_chunks::test::test_request_partial_encoded_chunk_from_self` to use a constant instead of a "magic number"
=> fix(near-chunks): remove unnecessary Result

chain/chain/src/chain.rs, chain/chain/src/lightclient.rs, chain/client/src/view_client.rs, core/primitives/src/views.rs, nightly/nightly.txt, pytest/lib/lightclient.py, pytest/tests/sanity/lightclnt.py
* Remove `approvals_next`
* Make the block for which the light client view is crated be pushed
back if the block two heights onward is in a different epoch
Test plan
---------
Restoring the old python test
=> feat: Making light client conformant with the new spec

neard/src/runtime.rs, runtime/runtime/src/lib.rs
As described in #2687, there is a critical vulnerability caused by a situation where accounts are deleted after they unstake but we still try to return 0 stake to the account. This PR submits an easy fix to the issue by not requiring account to exist when the returned stake is no more than 0. Please note that this is not the optimal way to fix it. The better way would be to change epoch manager behavior so that it will only record accounts in `stake_change` if it is needed. In the case of unstaking, it means that a stake change should only be recorded if it is a change from nonzero (validator or fishermen) to zero. However, this PR is enough to quickly patch the issue so that we can spend more time ironing out the proper and better fix. Resolves #2687.
=> fix: delete account after unstake should not cause node to crash

runtime/runtime-standalone/src/lib.rs
ApplyState.epoch_height must be equal to block.epoch_height
=> fix(runtime-standalone): Correct ApplyState.epoch_height

Cargo.lock, runtime/near-vm-runner-standalone/Cargo.toml, runtime/runtime-standalone/Cargo.toml
Bump version of runtime standalone which was not done in #2709.
=> fix: bump version of runtime standalone

Makefile, scripts/binary-release.sh
Fix the binary release fail due to a rename on store-validator to store-validator-bin
Test Plan
---------
cargo build -p store-validator-bin
=> fix(script): binary release rename

chain/client/tests/cross_shard_tx.rs, nightly/nightly.txt, scripts/check_nightly.py
Currently we have a few expensive tests not in nightly.txt, it's also deserve a check to enforce future expensive tests are in nightly.txt. I didn't find a cargo feature to list all tests or a rust parser binding in python and write this check in rust with std::ast is too heavy so it's a simple hacking parser
Test Plan
---------
Run locally, find a few missing nightly tests. Also I've add this test to buildkite, sanity check step, so it will be checked there
=> fix(test): enforce all expensive test is in nightly

codecov.yml
codecov status check is annoying and pollute commit status, we still want a `codecov 88%` badge in readme, but don't want a drop in coverage makes our commit in master branch shows `X`.
Test Plan
---------
enable codecov for this pr, it should always pass even coverage drops.
=> fix(script): disable codecov status check to polute commit status

nightly/nightly.txt, scripts/check_nightly.py
tests::test_all_chunks_accepted_1000_slow takes more than an hour to finish. Original plan is mark it as very_expensive in rust, but it become non trivial to accomodate check_nightly.py to parse it. So instead, a commented expensive test is allowed in nightly.txt, but a missing one is not allowed. 
Test Plan
---------
Sanity check should pass
=> fix(test): allow comment out very expensive test

neard/src/main.rs
When env variable RUST_LOG is assigned but empty there is an annoying message on startup:
```
Ignoring directive ``: invalid filter directive
```
This is always the case if nearup + docker is used.
=> fix: Remove message at start "Ignoring directive"

Cargo.lock
Revert the change to Cargo.lock introduced in #2672. The change caused some unexpected behaviors such as #2761.
Fixes #2761.
Test plan
---------
Test in the branch `node-crash-no-log-repro` that before this commit, the pytest `state_sync4.py` will fail with no indication of node crashing whereas after this commit the stack trace is printed in stderr.
=> revert Cargo.lock change

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/chain/src/store_validator.rs, chain/chain/src/store_validator/validate.rs, chain/client/tests/process_blocks.rs, pytest/lib/cluster.py
- Updating Tail and Chunk Tail inside `reset_heads_post_state_sync`
- Explicit clearing of Chunks in `reset_data_pre_state_sync`
- Not allowing to clear Chunks of Genesis Height
- `block_height_cmp_tail_count` function in validator to check Tail properly (update description of https://github.com/nearprotocol/nearcore/issues/2597)
- Disabling `chunks_state_roots_in_trie` until https://github.com/nearprotocol/nearcore/issues/2623 happens
- Fixing https://github.com/nearprotocol/nearcore/issues/2774
- Minor refactoring
=> feat(Store Validator): Running Store Validator in Nightly + fixes

chain/chain/src/store_validator.rs, chain/chain/src/store_validator/validate.rs, chain/client/src/client_actor.rs
Running Store Validator in Nightly after each `get_status()` takes time and may lead to timeout. The solution is to limit Store Validator in Nightly as it still:
- tries to check as many conditions as possible (not turning Store Validator off at all)
- works well on small tests
- not dependent on size of the Storage to validate
We also need to do https://github.com/nearprotocol/nightly/issues/5 to run full Store Validator at the end anyway.
TEST PLAN
-----------
`state_sync3.py` not failing on adv_check_store() execution
=> feat(Store Validator): Execution limiting in Nightly validation

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/chain/tests/gc.rs, chain/client/src/client.rs, core/chain-configs/src/client_config.rs, neard/src/config.rs
A hot fix that mitigates #2806 by reducing garbage collection step to the absolute minimum. However, even if we just advance tail by 1 height at each step, `clear_data` still takes about 0.5s to execute, which is very suboptimal.
Test plan
----------
Deploy on betanet and observe that garbage collection speeds up from more than 30s to 0.5s at each step.
=> fix: mitigate gc slowness by reducing step size

nightly/nightly.txt
Compare a recent master paralleled run on buildkite with the sequential nightly on nightly instance:
parallel:
https://nightly.neartest.com/s3/master_68d77cbfc2939f28410102f88ec1d5fba6256806_20200605_181035
sequential:
https://nightly.neartest.com/run/master_68d77cbfc2939f28410102f88ec1d5fba6256806_20200605_110602
10 timeouts on parallel, 6 on sequential. 5 of them are overlapped, 1 test is timeout in sequential but didn't in parallel. 
5 test was only timeout in parallel:
- fixed because missing `--exact` wrongly run multiple tests:
```
expensive near-client catching_up tests::test_catchup_random_single_part_sync
expensive near-client cross_shard_tx tests::test_cross_shard_tx
expensive near-client catching_up tests::test_all_chunks_accepted_1000
```
- fix in this PR by adding 20% more …
=> fix(nightly): add timeout to two gc tests

chain/chain/src/store.rs, nightly/nightly.txt, scripts/check_nightly.py
Fixes `test_seal_removal` test + moves test_clear_old_data_too_many_heights to Nightly.
Blocked by https://github.com/nearprotocol/nightly/pull/4.
=> fix(nightly): running lib tests

chain/jsonrpc/src/lib.rs, pytest/tests/sanity/rpc_tx_submission.py
As reported by @marcinbodnar, `EXPERIMENTAL_check_tx` returns `InternalError` when it is invoked. This is caused by a mistake I made when addressing some comment on the original PR (forgot to consider the variant in `send_tx`). 
Test plan
---------
Add test for `EXPERIMENTAL_check_tx` in `rpc_tx_submission.py` and make sure that it returns the expected error.
=> fix(rpc): fix EXPERIMENTAL_check_tx

core/primitives/src/block_header.rs
Due to move of Approvals, a change that came in before wasn't fully merged and is only detected by nightly tests.
Test plan
----
- Nightly test sanity/lightclnt.py passes again
=> Fix merge issue with light client

chain/chain/src/store_validator.rs, chain/chain/src/store_validator/validate.rs, pytest/lib/cluster.py
Fixes https://github.com/nearprotocol/nearcore/issues/2817.
- do not run validators in python tests while the node is syncing
- use Header Head properly
- setting `is_block_height_cmp_tail_prepared` properly
=> fix(store validator): don't run while syncing + minor fixes

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/client/src/client.rs, core/chain-configs/src/client_config.rs, neard/src/config.rs
https://github.com/nearprotocol/nearcore/pull/2807 is insufficient because of two major reasons:
1. It doesn't help in case of having lots of Forks on the Heights within `gc_step_size` because all those Forks expected to be cleared in one GC call.
2. It breaks GC completely if there is any Fork of Height longer than `gc_step_size`. Such Fork will be never cleared and Tail will be never increased.
This PR replaces `gc_step_size` with `gc_blocks_limit` - maximum number of Blocks that may be deleted per one GC call. It handles Fork Block deletions and doesn't stuck in case of long Forks.
=> fix(GC): replace gc_step_size with gc_blocks_limit

pytest/tests/sanity/state_sync2.py
state_sync2.py was failing because the block producer that the node is supposed to sync from gets kicked out a while ago and therefore doesn't track the shard, so naturally it doesn't have the state.
=> fix(nightly): fix state_sync2.py

Cargo.lock, chain/network/src/peer.rs, chain/network/src/peer_manager.rs
Fix #2754
Run each PeerActor on a separate thread so that communication with peers can be done concurrently. 
Ideally we should have a thread pool, but it is too complex in the actix framework. See this relevant discussion on [gitter](https://gitter.im/actix/actix?at=5ed5cd78d137513704346ee4).
`large_message.py` from #2744 was writing to several peers at the same time and it was a blocking operation (at most one connection writing at a time). After running that test on top of this PR it seen that several connections make progress at the same time.
=> feat(network): Spawn each Peer on separate thread.

Cargo.lock, chain/client/src/client_actor.rs, chain/client/src/info.rs, chain/client/src/metrics.rs, chain/network/Cargo.toml, chain/network/src/metrics.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/src/types.rs, core/metrics/src/lib.rs, core/primitives/src/views.rs
Expose useful metrics in a friendly way to have a useful dashboard for on-fire situations.
As part of this effort worked on the dev-ops to deploy the dashboard. https://github.com/nearprotocol/near-ops/pull/53
There is currently a node on betanet running with this changes applied on top of beta branch. 
http://34.94.189.12:3030/status
Check that the [dashboard](http://35.236.63.163:3000/d/node-inspection/node-inspection?orgId=1&refresh=5s) is working properly. 
DISCLAIMER: While the node is syncing some graphs are not being displayed properly (since some information is not recorded). 
Once every node run this code, we are going to be able to select and explore each node individually using the dropdown from the upper left corner. Node will be added automatically as they join to the …
=> feat(metrics): Expose metrics friendly for dashboard

Cargo.lock, chain/chain/Cargo.toml, chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/chain/src/store_validator.rs, chain/chain/src/store_validator/validate.rs, chain/chunks/src/lib.rs, core/primitives/src/utils.rs, core/store/Cargo.toml, core/store/src/db.rs, test-utils/store-validator/src/main.rs
- DBCol is iterable by `strum`
- `save_chunk` and `save_partial_chunk` are safe from incorrect writing
- StoreValidator error usage refactoring, using `thiserror` crate
- sanity tests for StoreValidator errors are added
- `check_discrepancy` and `check_cached` macro for quick validations
- `get_block_shard_id_rev` not panics for invalid keys
- minor updates
=> feat(Store Validator): use thiserror + minor updates

Cargo.lock, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/tests/process_blocks.rs, neard/src/config.rs, nightly/nightly.txt, pytest/lib/cluster.py, pytest/tests/sanity/validator_switch_key.py
There is an issue with account announcement that prevents zero downtime upgrade from working properly. This PR fixes the issue and also adds a test to make sure that the upgrade process described in https://github.com/near/docs/issues/341 works properly.
Test plan
-----------
* pytest `validator_switch_key.py`.
=> fix: fix some issues in zero downtime upgrade

chain/jsonrpc/src/lib.rs, pytest/tests/sanity/rpc_light_client_execution_outcome_proof.py
For consistency with `next_light_client_block`
=> Promote EXPERIMENTAL_light_client_proof to non-experimental

nightly/nightly.txt
Fixes https://github.com/nearprotocol/nearcore/issues/2554. Also fixes `test_catchup_receipts_sync_hold`.
Hotfix for https://github.com/nearprotocol/nightly/issues/7.
Tested on custom Nightly: https://nightly.neartest.com/s3/T2554_e866bea46e47cc118a9ffc5952dca5ac4aecbc55_20200618_102050
=> fix(nightly) increasing timeout for catchup tests

nightly/nightly.txt, pytest/lib/cluster.py, pytest/lib/messages/block.py, pytest/lib/messages/crypto.py, pytest/lib/messages/network.py, pytest/lib/messages/tx.py, pytest/lib/peer.py, pytest/lib/proxy.py, pytest/tests/sanity/block_production.py, pytest/tests/sanity/nodes_proxy.py, pytest/tests/sanity/transactions.py, pytest/tests/spec/network/handshake.py
This change introduces a large percentage of the `PeerMessage` schema ported to python, and a
library that allows wrapping nodes of the cluster in such a way that the messages between
them are intercepted by the test, de-borshified, and passed to a handler that can decide to
drop them, deliver them, or change them on the fly.
=> feat: Infrastructure to intercept network messages in python

chain/network/src/cache.rs, chain/network/src/lib.rs, chain/network/src/routing.rs
Increased route back cache to avoid dropping messages which
are supposed to be routed back. The problem was that when some
nodes are syncing several chunk request are asked, and request
arrive faster than responses, effectively invalidating the cache
most of the  responses are dropped, since the route back hash was
dropped from the cache.
This PR also introduce cache strategy proposed [here](https://github.com/nearprotocol/nearcore/issues/2756#issuecomment-642961782)
Fix #2756 
Test plan
=========
- Reproduced scenario where several routed messages were dropped locally, and tested with new cache and with old cache. The fix was the size increase.
- Unit tests to check the new strategy is working properly.
=> fix: Don't drop messages. RouteBack cache update

chain/jsonrpc/src/lib.rs
Otherwise the current nearlib tests are failing, because they still depend on the `EXPERIMENTAL_light_client_proof`.
The proper migration should be first introducing `light_client_proof` then moving nearlib API to the new RPC endpoint. And once all chains are upgraded to the new endpoint, only then the EXPERIMENTAL endpoint can be deprecated.
- CI
=> fix: Return experimental endpoint for `light_client_proof` RPC

chain/chain/src/store.rs, chain/chain/src/store_validator/validate.rs, chain/client/tests/process_blocks.rs
Garbage collection is slow because we do not persist chunk tail and therefore `clear_chunk_data` iterates from 0 to min_chunk_height every time it is called. Fixes #2806.
=> fix: persist chunk tail

chain/chain/src/store.rs, chain/chunks/src/lib.rs
Remove warning about unused code because some `uses` were only used behind feature flag `expensive_test`. 
Test plan
=======
- `cargo check --all --tests --benches` pass with no warnings.
- `cargo check --all --tests --benches --features expensive_tests` pass with no warnings.
=> refactor: Remove warnings

chain/client/tests/catching_up.rs
Fixes #2866.
According to https://github.com/nearprotocol/nearcore/issues/2866#issuecomment-646727726, it should be enough to increase `block_prod_time`.
The issue of incorrect [PASSED] test marks in Nightly should be resolved separately.
=> fix(catchup tests): increasing block_prod_time

chain/chain/src/test_utils.rs, chain/chain/src/types.rs, core/primitives/src/transaction.rs, core/primitives/src/version.rs, core/primitives/src/views.rs, neard/res/genesis_config.json, neard/tests/rpc_nodes.rs, pytest/tests/sanity/rpc_light_client_execution_outcome_proof.py, pytest/tests/sanity/rpc_state_changes.py, runtime/runtime/src/lib.rs, scripts/migrations/27-add-amount-burnt-to-execution-outcome.py
Because of the variable gas pricing during the execution the `gas_burnt` is not enough anymore to determine the amount of fees that was used for the given transaction execution. We need to expose the `tokens_burnt` which returns the actual amount that was used for the TX/receipt execution fees.
Bumping protocol version, because it changes the spec.
- CI
=> feat(RPC): Add burnt amount to ExecutionOutcome

pytest/tests/sanity/backward_compatible.py
backward compatible was failing because binary not build
Test Plan
---------
backward compatible test should pass. Note, backward_compatible with beta currently still fails, because it's not backward compatible, backward_compatible with master is passing as expected
=> Fix(test): fix path error in backward compatible

scripts/start_unittest.py
Use nonzero gas price in nearlib tests to make behavior the same with nearlib CI.
=> fix(test_nearlib): use nonzero gas price in unittest script

chain/jsonrpc/src/lib.rs, neard/src/config.rs
Fix #2825 
Test Plan
---------
- current config shouldn't panic with this change
- set metrics_addr to another port should host /metrics in another port, /status etc. should still available in current port
=> feat(config): run metrics in different port

pytest/lib/cluster.py, pytest/lib/mocknet.py, pytest/lib/transaction.py, pytest/tests/mocknet/bounce.py, pytest/tests/mocknet/outage.py, pytest/tests/mocknet/sanity.py
Introduces tests which can be setup to run automatically on mocknet. This PR only introduces the tests, the automation will need to be done later as part of our own infrastructure.
The test scenarios include:
* Bounce (take all nodes down, then bring them back up)
* Outage (take < 1/3 nodes down, make sure network continues, then bring nodes back and make sure they sync and the network recovers)
=> feat(pytest): basic tests using mocknet (#2862)

chain/jsonrpc/src/lib.rs, neard/src/config.rs
This reverts commit 10e6dfe1f313260f8ed9765bbc8e0a551ee356e7.
This change inadvertently breaks all the python tests, and half of the expensive
tests.
Both infrastructures need to be running nodes with different metrics
ports.
=> Revert "feat(config): run metrics in different port (#2881)"

chain/network/src/codec.rs, chain/network/src/peer.rs, pytest/tests/sanity/large_messages.py, pytest/tests/sanity/network_drop_package.py
When a peer sends a message with a header indicating that
it is sending a message larger than the limit it is banned.
And the connection is dropped. Otherwise honest node was
keeping a huge cache with all information that is probably
garbage.
Test plan
=========
* Unit tests in codec
* large_message.py sends trash message on this threshold.
If message were one byte larger connection would be dropped
immediatelly. This case is already covered by previous unit tests.
test: Dropping messages
* Tests were message were 5% of messages was randomly being dropped
and check that nodes are able to make progress (produce blocks)
=> fix: Ban peers that try to send very large message

chain/chain/src/metrics.rs, chain/client/src/info.rs, chain/client/src/metrics.rs, chain/network/src/metrics.rs, runtime/runtime/src/metrics.rs
* Add prefix `near`
* Use lowercase for names
* Add meaninful suffix
fixes: #2873
Test Plan
=========
Run localnet. Check metrics names are correct
on http://*:3030/metrics
=> fix: Use prometheus naming conventions for metrics

nightly/nightly.txt
The mocknet tests are given as their own testing group to ensure they are only run in the sequential nightly runner. This is important because multiple tests against the mocknet cannot run at the same time since they cause drastic effects on the network (e.g. shutting down one or more nodes).
Corresponding PR in the nightly runner: https://github.com/nearprotocol/nightly/pull/9
=> testing: add mocknet tests to nightly

chain/chain/src/test_utils.rs, chain/chain/src/types.rs, core/primitives/src/transaction.rs, core/primitives/src/version.rs, core/primitives/src/views.rs, neard/res/genesis_config.json, neard/tests/rpc_nodes.rs, pytest/tests/sanity/rpc_light_client_execution_outcome_proof.py, runtime/runtime/src/lib.rs, scripts/migrations/28-add-executor-id-to-execution-outcome.py, scripts/migrations/28-add-receiver-id-to-execution-outcome.py
Add `receiver_id` to `ExecutionOutcome` so that the bridge can verify cross contract calls easily. Fixes #2902.
=> fix(bridge): add receiver_id to ExecutionOutcome

pytest/tests/sanity/validator_switch.py
validator_switch.py was broken because the stake was below minimum threshold.
=> fix(pytest): fix validator_switch.py

nightly/nightly.txt
Currently pytest after nightly all fail: http://nightly.neartest.com/run/master_8b939a057186449638ac6dada096f286d95faba8_20200629_094402 Because it recompile binary and rename in a way that break the per-compilation used by the other nightly pytests. It's possible to put upgradable test in medium and do cleanup / recompile tests for other nightly tests, but recompile takes additional time.
Test Plan
---------
Test after upgradable should pass. However, this can't be tested on buildkite nightly, because it's parallel
=> Fix(test): test upgradable test as the last pytest

Cargo.lock
Reverting Cargo.lock fixed the issue. Test state_sync_routed_py_manytx_100 was failing with timeout, and after increasing request timeout from 2seconds to 20seconds it passed. Apparently, some of the updated dependencies introduced in #2804 (in [Cargo.lock](https://github.com/nearprotocol/nearcore/pull/2804/files)) significantly degraded performance of our node.
fixes: #2907
Test plan
=========
+ state_sync_routed_py_manytx_100 pass
=> fix: Dependencies updates that lead to timeout

pytest/tests/contracts/deploy_call_smart_contract.py, pytest/tests/contracts/gibberish.py, pytest/tests/sanity/rpc_query.py, scripts/test_nearlib.sh
Some python tests failed after #2883 because now for cross shard transactions we potentially need to have longer timeout.
=> fix(pytest): fix some pytests timeout

tests/test_simple.rs
The tests in `test_simple.rs` were broken because now we have refunds for transfers as well. Changed the criterion for checking balances on each iteration to a better one.
=> fix(test): fix multi-node expensive tests

Cargo.lock, pytest/tests/sanity/backward_compatible.py
Fix #2443 
Test Plan
---------
When protocol version not changed (now it's the case), it run as usual. When it changes (tested by bump protocol version to 30), it will exit early. Once this merged, I'll turn on backward compatible test as "must pass" on buildkite
=> fix(test): enforce backward compatible test when protocol version not changed

Cargo.lock, neard/Cargo.toml, neard/src/config.rs, neard/src/main.rs
Test Plan:
```
sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/c/neard (neard-genesis-config-download) [101]> cargo run --bin neard init --account-id sandi.betanet --chain-id betanet --download-genesis
Compiling neard v1.2.0 (/home/sandi/workspace/near/core/neard)
Finished dev [unoptimized + debuginfo] target(s) in 18.63s
Running `/home/sandi/workspace/near/core/target/debug/neard init --account-id sandi.betanet --chain-id betanet --download-genesis`
Jul 08 16:14:49.366  INFO near: Version: 1.2.0, Build: dc59fe28-modified, Latest Protocol: 29
thread 'main' panicked at 'To download the genesis you have to specify the download path --genesis', neard/src/main.rs:144:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
sandi@sandi-ThinkPad-X1-Carbon-7th …
```
=> Added download option for the genesis in neard

pytest/requirements.txt
Currently we install this dep first (0.1.9), then nightly's dep (0.3.9), then run all nightly tests. As a result, if we install dep here automatically everytime we run nightly, it will override nightly dep version to 0.1.9 and make mocknet tests fails. 
Test Plan
---------
This is already the case we run in nightly (0.3.9), so no extra test needed.
=> fix(nightly): bump dep version to be not conflict with nightly

nightly/nightly.txt, pytest/tests/sanity/state_sync_massive.py
This test timeout is huge since it needs to generate big state
first, which takes ~180seconds, then spawn new node and check it
is able to sync the new state.
The fix was increase the outer timeout limit, such that in case of
timeout, the inner timeout is triggered.
New node have enough time to sync now, so test should pass.
Fixes #2932 
Test Plan
=========
- state_sync_massive should pass.
- It should not fail in nightly with timeout.
=> fix: state_sync_massive failed due to timeout

nightly/nightly.txt, pytest/tests/mocknet/load_testing.py, pytest/tests/mocknet/load_testing_helper.py
Mocknet nodes stall out (stop producing blocks) if new contracts are deploys too quickly. Until this issue is resolved, we will deploy the testing contract at a rate of 5 tps to keep the network stable.
=> Deploy test contract slowly to keep mocknet stable

README.md
buildkite badge has a bad default that without adding branch it shows latest build of all branches (probably comes from a failed PR branch), instead of master branch, which shows fail at this moment while our master is actually pass
Test Plan
---------
badge should show pass
=> Fix(ci): update badge

pytest/lib/mocknet.py, pytest/tests/mocknet/outage.py
* Originally mocknet was 50% non-validating nodes (this configuration was inherited from devnet)
* We want mostly validating nodes since non-validating nodes are less interesting for testing (contribute less to failure modes, e.g. block production)
* We need at least some non-validating nodes to test code paths when the node is not a block producer
* We settled on 4 as a reasonable number.
* The number of nodes in the mocknet needed to be increased to 54 as a result because the current validator "seat" model did not allow 46 genesis validators, but does allow 50. Note this problem will no longer exist when https://github.com/nearprotocol/NEPs/pull/83 is implemented.
* The timeouts on transactions are also increased to be less sensitive to missing blocks due to offline validators (this is …
=> fix(mocknet): Only have up to 4 rpc nodes on mocknet

pytest/empty-contract-rs/Cargo.toml
* Fixes recent nightly failures due to the change of the `borsh` version in `near-sdk-rs`.
=> fix(nightly): bump borsh version to match near-sdk-rs

pytest/tests/sanity/db_migration.py, pytest/tests/sanity/state_migration.py
Test Plan:
```
5 sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/c/pytest (db_migration_sanity)> python3 tests/sanity/db_migration.py
6    Compiling neard v1.2.0 (/home/sandi/workspace/near/core/neard)               
7     Finished dev [unoptimized + debuginfo] target(s) in 28.83s                  
8     Finished dev [unoptimized + debuginfo] target(s) in 0.18s                   
9 Updated 0 paths from the index                                                  
10 Downloading near & state-viewer for beta@Linux                                  
11 INFO:root:The near root is ../target/debug/...                                  
12 INFO:root:The node root is /home/sandi/./near...                                
13 Jul 14 19:14:18.625  INFO near: Version: 1.2.0, Build: 86e4397c, Latest Protocol: 30 …
```
=> Added CI for database migration #2927

chain/client/src/client_actor.rs
``ClientActor`` will try to check if it's time to do block production every time it receives messages from inbox in ``handle`` method. This will ensure that block production still happens during high load.
Context:
There is a bug in Actix library. While there are messages in mailbox, Actix
will prioritize processing messages until mailbox is empty. Execution of any other task
scheduled with run_later will be delayed.
=> Change ClientActor to prioritize block production during high load

pytest/lib/metrics.py, pytest/tests/mocknet/load_testing.py
Originally bps was computed by taking two `near_block_processed` measurements and dividing the difference by the elapsed time. This gave an unreliable result, so we now instead use the metric which exposes the block rate directly.
=> fix(nightly): Measure blocks per second using near_blocks_per_minute metric

Cargo.lock, Cargo.toml, chain/indexer/Cargo.toml, chain/indexer/README.md, chain/indexer/src/lib.rs, chain/indexer/src/streamer/mod.rs, chain/indexer/src/streamer/streamer.rs, core/primitives/src/types.rs, tools/indexer/example/Cargo.toml, tools/indexer/example/src/main.rs
Work in progress on network-indexer and explorer backend.
Corresponding issue  in [near-explorer #236](https://github.com/near/near-explorer/issues/236)
Currently we have:
* `indexer` at `chain/indexer`
* `indexer-explorer`
We have indexer that can run `neard` (though we need to set predefined parameters and learn what args we need to be ready to receive) and streamer that watches for each newly created block, collects chunks related to the block and sends it to channel.
`indexer-explorer` is the usage of the `indexer`.
=> feat: Network indexer

chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_transactions.rs, pytest/tests/sanity/rpc_sync.py
A node should not serve rpc while it is syncing since it would both slow down the node and also gives inconsistent result from other nodes. Fixes https://github.com/nearprotocol/nearcore/issues/2795
Test plan
---------
* python test `rpc_sync.py`.
=> fix(rpc): do not serve rpc while the node is syncing

pytest/empty-contract-rs/Cargo.toml, pytest/empty-contract-rs/src/lib.rs
* `near-sdk-rs` now re-exports its `borsh`, so we do not need a separate dependency for it
=> fix(pytest): Import borsh from near-sdk-rs directly

chain/client/src/client_actor.rs, core/chain-configs/src/client_config.rs, neard/src/config.rs
Cross shard tx tests are broken after https://github.com/nearprotocol/nearcore/pull/2983, likely because the overhead introduced by the change. Now we might spend too much time checking the triggers such that some message processing is delayed. This PR fixes it by checking the triggers less frequently.
=> fix(test): fix cross_shard_tx tests

chain/chain/src/store.rs, chain/client/tests/process_blocks.rs
In `update_tail`, we incorrectly update `chunk_tail` if it is `None`, because even if `chunk_tail` inside `ChainStoreUpdate` is none, it doesn't mean that chunk_tail doesn't exist. Therefore, in `clear_data`, when we loop through some height where there is no block, we end up overwriting `chunk_tail` to be `genesis_height`, thereby causing garbage collection to be extremely slow.
Test plan
---------
`test_gc_chunk_tail` passes.
=> fix(gc): properly update chunk tail

chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/src/client.rs, core/chain-configs/src/client_config.rs, neard/src/config.rs, neard/src/runtime.rs, neard/tests/rpc_nodes.rs, pytest/tests/stress/hundred_nodes/collect_logs.py
We are not using `block_weight` any more, but for some reason we still use it in `prepare_transactions` and therefore limit number of transactions in a chunk to 1000 for no good reason.
=> fix: remove legacy config on block weight

chain/chain/src/error.rs
We currently unconditionally logs an error inside `log_storage_error`, even if there is no error.
=> fix: log transient error only when there is an error

chain/client/src/view_client.rs
When retrieving a chunk from rpc, we also compute its author. However, the computation uses `height_included`, which is not reliable and will give an unexpected error when there is a fork and the chunk is in fact included in a block with higher height. This PR switches to using `get_epoch_id_from_prev_block` to accurately compute epoch id and the chunk producer.
=> fix(rpc): fix chunk producer computation

chain/epoch_manager/src/lib.rs, pytest/tests/sanity/upgradable.py
When we calculate the protocol version at the end of an epoch, we incorrectly calculate the total stake by multiplying each validator's stake with the number of seats they have. Therefore, when each validators have > 1 seat, they will never be able to upgrade. The issue that comes with this is that we cannot upgrade into this fix because upgradability itself was broken. One solution I see is to ask all validators to update their nodes within one epoch and as long as a majority of them do so, the network will not stall.
Test plan
---------
* `test_protocol_version_switch_with_many_seats`
* `upgradable.py`
=> fix(upgradability): properly count stake

runtime/near-vm-logic/src/types.rs
`PromiseResult::NotReady` is not used any more. It comes from the early versions of the protocol.
Link the the related chat:
https://discord.com/channels/490367152054992913/510254340120903684/734814189465501867
=> Mark PromiseResult::NotReady deprecated

pytest/lib/metrics.py, pytest/lib/mocknet.py, pytest/tests/mocknet/load_testing_helper.py
* Support for sharded mocknet (these machine names have the `sharded-` prefix)
* Single function for downloading logs from all nodes (helpful in gathering logs for debugging issues)
* Use a single block hash for all transactions in the load test instead of constantly pinging the status endpoint (this reduces the load on the node which is not related to receiving and processing transactions, which is the core functionality we are benchmarking)
* Ensure `Metrics` can handle the case where `near_block_processing_time` is missing (which occasionally happens for some reason)
=> fix(mocknet): various improvements

chain/chunks/src/lib.rs, chain/chunks/src/test_utils.rs, chain/client/src/client.rs
The signature check for partial encoded chunks looks up the epoch id using the referenced block hash, however if this block is not known by the node then the check will fail, causing the processing of the chunk to return an error. However, the desired behaviour is to signal that a block is missing so that this chunk can be re-tried in the future. This fixes the issue, properly handling the potential error from the signature check and returning `NeedBlock` appropriately.
Note: The majority of the code is for the testing, the fix itself is quite small (see the second commit)
Testing Plan:
* New unit test for this case
=> fix(chunks): process partial encoded chunk properly handles missing blocks

.github/ISSUE_TEMPLATE/bug_report.md, README.md, neard/src/config.rs
DevNet no longer exists and mentions of it have been removed from this repository.
=> refactor: remove deprecated DevNet

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/client/tests/process_blocks.rs
When we do `reset_data_pre_state_sync` before running state sync, we garbage collect everything up to sync block, which includes the prev block of the sync block. However, when we run state sync, we use `prev_hash` of sync block inside `possible_targets` [here](https://github.com/nearprotocol/nearcore/blob/f65d2441d66fa13f7933c23ba833311677ce1e96/chain/client/src/sync.rs#L801). Therefore, we cannot garbage collect `prev_hash` of sync block. Fixes #3042.
Test plan
---------
`test_data_reset_before_state_sync`
=> fix: do not garbage collect prev block of sync block before state sync

chain/chunks/src/lib.rs, chain/client/src/client.rs
Description:
For partial encoded chunks, the signature check includes looking up the chunk producer, based on the epoch ID. In addition it checks whether this chunk producer has been slashed. These checks require the node to know the parent block the chunk header references, and thus fails if it is not present. This change ensures we properly catch and handle such errors since we will be able to process the chunk later when the node eventually learns about the missing block.
Testing plan:
* New unit test for processing a chunk with an unknown parent block
=> fix(chunks): properly handle missing block, previously causing chunk signature check to fail

scripts/docker-release.sh
it's not allowed by docker, replace it with `_`
Test Plan
---------
This pr is also from fork, it should pass
=> fix(script): docker build from a fork has colon in branch name

chain/jsonrpc/src/lib.rs
Resolves #3054.
Test Plan
=======
Manually confirmed that the benchmark works fine and the node does not report incorrect nonce.
=> fix(jsonrpc): Fixed race condition in broadcast_tx_* methods

test-utils/state-viewer/src/main.rs
From debugging the state transition issue there has emerged some useful commands to be put into state viewer:
* `apply` which applies the state transition at a given height and prints the result
* `view_chain`, which views the block, chunks and chunk extra at a given height.
=> feat: add some debug functionalities to state viewer

scripts/docker-release.sh
I made a mistake when doing this, we have to apply it on the branch commit as we are already removing : with _
=> fix(ci): Fixed typo in the release scripts for docker

chain/chain/src/types.rs, core/primitives/src/version.rs, neard/res/genesis_config.json, pytest/tests/sanity/upgradable.py
I made a typo in #3028 and updated gas price to 1B yotcoNEAR instead of 100M yotcoNEAR.
Test plan
---------
`upgradable.py`
=> fix: gas price

chain/network/src/peer_manager.rs, chain/network/src/types.rs
Currently we log some large messages in network when they get dropped and it makes the log very hard to read on the debug level. This PR removes logging the full `RoutedMessage` by implementing `Debug` trait for it.
=> fix(logging): avoid logging large messages

chain/chain/src/chain.rs
A couple substandard issues that caused nodes to get stuck during sync:
* In `reset_data_pre_state_sync`, we garbage collect all data up to sync block, but this makes no sense. Let's say we are just joining the network and the head is at genesis and the head of the network is more than 2 million blocks ahead. At this point, we don't actually have any data other than the headers that are just synced during header sync. However, in `reset_data_pre_state_sync`, we will go through all those 2 million heights, trying to garbage collect the data we just synced. 
* In `check_state_needed`, we always try to find the hashes of the blocks that we need to sync first, even if we do not need them and should sync state instead. This means that if we are at genesis and the network is 2 million blocks …
=> fix(sync): address a couple suboptimalities

pytest/lib/account.py, pytest/tests/mocknet/load_testing_helper.py
Previously, load tests would query the nodes for the account nonce on each transaction. This put an additional burden on the nodes which is likely unrealistic. Here, we introduce an `Account` object to track the nonce locally in the test, and thus not query the nodes. Additionally, the `Account` object tracks the timestamps of when it sends transactions, allowing for detailed measurements of input transactions per second (though we do not yet make use of this feature in this change).
Note: this does not change the result of running the load test (i.e. tps and bps are not effected by this change), so the nonce querying likely had little impact on the node performance. However, I would still like to make this change since `Account` is a useful, reusable object.
=> pytest: refactor mocknet load_testing_helper to track the nonce locally

core/primitives/src/contract.rs, core/store/src/lib.rs, genesis-tools/genesis-populate/src/lib.rs, runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs, runtime/runtime/tests/test_regression.rs, test-utils/testlib/src/node/mod.rs
Don't re-hash a contract code after a read if the `code_hash` is already available in the account ID. The only place to rehash is when `apply_genesis_records` is called.  
Ref: #3094
=> fix (Runtime): Pass code_hash to ContractCode::new when available

chain/client/src/test_utils.rs, chain/client/tests/bug_repros.rs, chain/client/tests/catching_up.rs, chain/client/tests/chunks_management.rs, chain/client/tests/consensus.rs, chain/client/tests/cross_shard_tx.rs, chain/client/tests/process_blocks.rs
The usefulness and flakiness of `cross_shard_tx` depends heavily on the block production time.
This change adds printing block stats every minute, we will print the following:
- ratio of number of blocks to longest chain
- maximum divergence between recently produced blocks
In addition we will fail `cross_shard_tx` test if the ratio is too high or to low, depending on test parameters.
https://github.com/nearprotocol/nearcore/issues/3014
=> test: add extra stats to cross_shard_tx

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/client/tests/process_blocks.rs, neard/src/runtime.rs
Currently when we do not have enough blocks for garbage collection, `get_gc_stop_height` will return a `DBNotFoundErr` and the caller handles the error. This caused an incorrect handling of error in `process_block` and we will reject valid blocks if we do not have enough data for garbage collection, which can happen after a state sync. This PR changes `get_gc_stop_height` to return genesis height when we do not have enough data for garbage collection and therefore we don't need to worry about error handling at call site.
Test plan
---------
* `test_process_block_after_state_sync`
=> fix(chain): do not return error on get_gc_stop_height

pytest/tests/sanity/staking2.py
The flakiness was primarily due to insufficient number of blocks between the epoch switch, and checking for the expected stakes. The epoch was switching at heights equal to 2 modulo 10, and the checks were executed at the same heights. Moreover, the height was retrieved from one node, but the checks were against the other.
Fixing it by extending the epoch by two blocks, and moving the checks two blocks ahead.
Also adding checks before sending the second set of stakes, it covers a situation when the latest stake during the current epoch is higher than the current stake (a situation the test was not previously testing).
Reducing the timeout to 6 minutes from 10 minutes. staking2.py, staking_repro1.py and staking_repro2.py mostly test the same things, so it is still 18 minutes of testing per …
=> fix: Removing flakiness from staking tests

chain/client/tests/process_blocks.rs, core/primitives/src/block.rs
Currently there is a discrepancy between how gas price is computed and how it is verified. This leads to verification failure when the protocol changes between epochs.
Test plan
---------
`test_gas_price_change_no_chunk`
=> fix: correctly verify gas price

chain/chain/src/chain.rs
gc_sync_after_sync_* tests fail for the following reasons:
1) fork_tail is not properly maintained. A node resets fork tail after state sync but we allowed it to go back on epoch change.
2) in #3099 I didn't account for the fact that we can have chunk in storage whose height is higher than the current head.
Fixes #3133.
Test plan
----------
Run each of the gc_sync_after_sync_* tests 30 tests and observe that there is 0 failure.
=> fix(test): gc_sync_after_sync

pytest/tests/stress/stress.py
Store validity checks are executed on each `get_status` and take up to 1.5 seconds, during which they block `Client`.
In stress.py specifically they quickly get to actually taking 1.5 seconds, thus each time the test calls to `get_status`, one of the nodes gets blocked for 1.5s.
Removing ongoing store validity checks from stress.py, and introducing them only once at the end.
Test plan:
----------
stress.py now can actually pass in nayduck:
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/93
The failure is a new issue: #3169
=> fix: Removing store validity tests from stress.py

nightly/tests_for_nayduck.txt, pytest/tests/sanity/state_sync3.py
`state_sync3.py` failed because the head was not far enough behind to trigger state sync in the beginning and caused the test to timeout. Fixes #3165 
Test plan
---------
Run `state_sync3.py` 30 times and observe no failure.
=> fix(test): state_sync3

pytest/tests/sanity/block_production.py
The test relies on being able to query all the nodes between every two blocks produced.
Before 7028068 it was likely but flaky, after it the test fails consistently.
It is due to the fact that store validity checks take ~0.35 seconds per `get_status`.
Disabling the validity checks for this test. It is generally OK, because practically
every other test (e.g. transactions.py) is a superset of this test in terms of coverage,
and would catch any storage inconsistency that this test would now miss.
Fixes #3143
Test plan:
---------
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/97
=> fix: Removing flakiness from block_production.py

chain/client/tests/cross_shard_tx.rs, nightly/tests_for_nayduck.txt
This change fine-tunes the block production times in cross_shard_tx tests to be appropriate for nayduck workers.
The tests still have some level of flakiness (see Test Plan below), I will be debugging if those are real issues, so not closing #3140 yet.
Test plan:
---------
The tests maintain statistics that ensure that they are producing sufficient number of forks. Thus a passing test not only indicates that the block prod is sufficiently high for blockchain to make progress, but is also sufficiently low to test complex situations.
Here are 12 runs of each test. Vanilla `cross_shard_tx` failures are timeouts:
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/103
And 12 reruns of `cross_shard_tx` after increasing the timeout:
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/106
=> fix: Fine tune cross_shard_tx constants for the nayduck runners

chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/info.rs, chain/client/src/sync.rs, chain/client/src/types.rs, nightly/nightly.txt, pytest/lib/cluster.py, pytest/lib/proxy.py, pytest/lib/proxy_instances.py, pytest/tests/stress/stress.py
This change builds on top of Michael's changes to introduce `local_network` mode to stress.py
The nodes only learn about their peer's highest height via Block messages, and thus if a block message is lost and two nodes are exactly one height away from each other, the one behind will never learn it needs to catch up.
If now such a 1-height difference is split across two rouhgly even halves of the block producers, the system will stall.
Fixing it by re-broadcasting `head` if during some reasonable time the network made no progress.
With this change `local_network` mode passes in nayduck.
Test plan:
---------
Before this change stress.py local_network fails consistently due to chain stalling.
After:
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/104
Out of five failures the first one is …
=> fix: Properly handling stalls due to 1-height differences

nightly/tests_for_nayduck.txt, pytest/tests/sanity/skip_epoch.py
Fix skip_epoch.py by setting proper epoch length to avoid the situation where some nodes do not get a seat.
Test plan
---------
Run `skip_epoch.py` 50 times and observe no failure
=> fix(test): skip_epoch

chain/chunks/src/lib.rs
CI is currently failing due to a test not working properly with seals.
The test doesn't trigger any particular bug in seals, but rather the fact that we do not accept a chunk until we have all the seals.
I believe we do want to accept chunks before we receive seals, and in attempt to fix it I discovered that the implementation of seals generally has issues.
Seals are not needed in a signle shard setup, so disabling them for good for now, and opening #3180 to track.
Test plan:
---------
chunks_recovered_from_full_timeout_too_short (that fails in CI before this change) passes.
All tests in the `chunks/lib.rs` pass
=> fix: Disabling seals to unblock CI

chain/client/src/client_actor.rs, chain/client/tests/bug_repros.rs
Currently we drop blocks when they are more than 500 heights from our head. However, this means that if the network stalled for some time and recover, a valid block whose height is more than 500 ahead but whose prev block is our head may be dropped and will cause the node to stall.
Test plan
---------
`test_long_gap_between_blocks`
=> fix(chain): handle long block height gap

chain/chain/src/chain.rs, chain/client/src/client.rs, chain/client/src/sync.rs, nightly/tests_for_nayduck.txt, pytest/tests/sanity/block_sync_archival.py
@nearmisterwhite requested that they be able to sync every block from genesis. Currently archival nodes do not always sync blocks and may use state sync, which will skip the blocks in between. This PR enforces archival node to sync all blocks.
Test plan
----------
Run `block_sync_archival.py` 30 times and observe no failure.
=> fix: enforce block sync for archival nodes

chain/client/tests/catching_up.rs, core/store/src/lib.rs, nightly/tests_for_nayduck.txt, pytest/lib/proxy.py, pytest/lib/proxy_instances.py, pytest/tests/stress/stress.py
1. Removing the limit on 50 transactions per batch. It was needed when we had a bug that hangs if the tx doesn't exist, and is no longer needed;
2. Adding a new mode that drops a percentage of packets (fixes #3105);
3. Disabling the check for not deleting the same object within a transaction, until #3169 is fixed. After (1) above it crashes stress.py 3 out of 4 times, preventing it from getting to the (potential) real issues;
4. Increasing the epoch to 25 blocks, so that in the time it takes to send all the transactions and wait for the balances in the `local_network` mode ((15+20) * 2 = 70 seconds, which is approx 100 blocks) five epochs do not pass, and the transactions results are not garbage collected
5. Enabling `local_network` in default nayduck runs. Also enabling a mode without …
=> test: Various stress.py changes

chain/chunks/src/lib.rs, chain/client/tests/challenges.rs
This calling `account_id_to_shard_id` many times was causing a performance issue in `ShardsManager::distribute_encoded_chunk` because `receipts_recipient_filter` is called inside a loop, and `account_id_to_shard_id` has a non-trivial computation cost since it computes a hash.
This change is part of an ongoing effort to improve the performance of the node under load. This change does not "solve" the current performance issues, but it does give a small improvement.
=> fix(chunks): refactor `receipts_recipient_filter` to avoid excessive calls to `account_id_to_shard_id`

chain/chain/src/store_validator/validate.rs, chain/chunks/src/lib.rs, chain/client/tests/catching_up.rs
We disabled seals in #3182 and it caused some tests to fail:
* test_chunk_grieving tests specifically seals and it is now disabled
* `skip_epoch.py` failed due to an issue in store validator that is revealed when seal is disabled since we don't request chunk parts now.
Test plan
---------
Run `skip_epoch.py` 50 times and observe no failures.
=> fix(test): fix some tests that failed due to disabling seals

nightly/tests_for_nayduck.txt, pytest/tests/stress/stress.py
Reducing the package drop rate to 5%, and overall tuning constants so that most modes are less flaky.
`node_restart packets_drop` still doesn't pass, #3202 is tracking it.
Test plan:
----------
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/138
=> test: Further harnessing stress.py

core/store/src/migrations.rs
@mikhailOK pointed that `fill_col_outcomes_by_hash` and `fill_col_transaction_refcount` are not committing into Store Update. This bug is fixed in https://github.com/nearprotocol/nearcore/pull/2961 however as we decided to postpone Dynamic Resharding, the fix has not been added separately by mistake.
=> fix(store): commit migrations

Cargo.lock, runtime/near-vm-logic/src/config.rs, runtime/near-vm-logic/src/gas_counter.rs, runtime/near-vm-logic/src/lib.rs, runtime/near-vm-logic/src/logic.rs, runtime/near-vm-logic/src/types.rs, runtime/near-vm-logic/tests/test_iterators.rs, runtime/near-vm-logic/tests/vm_logic_builder.rs, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner-standalone/src/main.rs, runtime/near-vm-runner/src/lib.rs, runtime/near-vm-runner/src/runner.rs, runtime/near-vm-runner/src/wasmer_runner.rs, runtime/near-vm-runner/src/wasmtime_runner.rs
Implement profiler for gas consumption. 
Command like
```
cd runtime/near-vm-runner-standalone  &&  cargo run -- --wasm-file /work/near/near-linkdrop/res/linkdrop.wasm --method-name create_account --input '{"new_account_id": "zest.near", "new_public_key": "ed25519:C1BYE6i7bDoqccHuXfGTHXQzJsdhjN7MQ6h3iCRxycCY" }' --profile-gas
```
produces
```
------------------------------
Total gas: 12849996969996
Host gas: 239484430401 [1% total]
Action gas: 12247300236960 [95% total]
Wasm execution: 363212302635 [2% total]
------ Host functions --------
base -> 5295362220 [0% total, 2% host]
contract_compile_base -> 35445963 [0% total, 0% host]
contract_compile_bytes -> 42827632500 [0% total, 17% host]
read_memory_base -> 28708495200 [0% total, 11% host]
read_memory_byte -> 809683929 [0% total, 0% …
```
=> feat: implement gas profiler.

Cargo.lock, runtime/CHANGELOG.md, runtime/near-runtime-fees/Cargo.toml, runtime/near-vm-errors/Cargo.toml, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner/Cargo.toml, runtime/publish.sh, runtime/runtime-params-estimator/Cargo.toml, runtime/runtime-standalone/Cargo.toml, runtime/runtime/Cargo.toml
Bump version of runtime-* to publish
- CI
=> fix: Bump version for gas profiler change that broke near-sdk-rs tests

chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/tests/cache_edges.rs, nightly/nightly.txt, pytest/tests/stress/saturate_routing_table.py
When a node receives a batch of edges process them all first, and update routing table in the end only once.
Add test that checks PeerManagerActor is not blocked for long time.
Test plan
=======
saturate_routing_table.py should pass
=> fix: Batch edges on routing table sync

chain/client/src/client.rs, chain/client/tests/cross_shard_tx.rs
After disabling seals, the minimum block time that `cross_shard_tx` can tolerate dropped drastically, to 80ms.
We recently introduced a check at the end of the test that makes sure that the block prod time is not too high, so that `cross_shard_tx` actually ends up producing lots of forks. That check was failing recently.
With 80ms block time the test passes very consistently.
Fixes #3140
Test plan:
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/154
=> fix: Final touch to (almost) remove flakiness from cross_shard_tx

chain/chain/src/lib.rs, chain/client/src/lib.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, core/primitives/src/rpc.rs
Bridge currently uses `validator` rpc for retrieving validator information. However, the validator info returned there is not ordered in the block producer order, which caused incompatibility with `next_bps` returned by light client. This PR adds a separate endpoint `EXPERIMENTAL_validators_ordered` just for that purpose.
Test plan
---------
`test_validators_ordered`
=> fix(rpc): add validators_ordered endpoint for bridge

pytest/tests/sanity/controlled_edge_nonce.py
Currently we use as an heuristic edge nonce increase of at most
1000. This test detects that a node doesn't accept higher increases,
i.e. nonce should be > 1000.
Fixes #3166 
Test plan
========
controlled_edge_nonce.py should pass
=> Fix(controlled_edge_nonce) Increase nonce above 1000

chain/network/src/codec.rs, chain/network/src/peer.rs, chain/network/src/types.rs, core/primitives/src/version.rs, neard/res/genesis_config.json, pytest/tests/sanity/backward_compatible.py, pytest/tests/spec/network/handshake.py
This will allow nodes that are compatible with each other to communicate disregarding who initiated the conversation.
This changes needs to be deployed in two step. This PR introduce HandshakeV2 and add ability to nodes to understand and process this types of messages. Later in PR #3157 it is started to use HandshakeV2 as default handshake.
Test plan
=========
Pass upgradability test
=> fix: Use both version and oldest_supported version

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/client/tests/catching_up.rs, chain/client/tests/cross_shard_tx.rs, chain/client/tests/query_client.rs, chain/indexer/src/streamer/streamer.rs, chain/jsonrpc/client/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, chain/jsonrpc/tests/rpc_transactions.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, core/primitives/src/rpc.rs, core/primitives/src/types.rs, neard/tests/rpc_nodes.rs, neard/tests/stake_nodes.rs, test-utils/testlib/src/user/rpc_user.rs
This is based on #2990.
This is necessary for RosettaRPC implementation (#2738) and potentially useful for NEAR Indexer.
Testing Plan
============
Added minimal RPC tests.
=> feat(client): Extended query to be able to refer to the genesis and the earliest [oldest] available blocks

Cargo.lock, runtime/CHANGELOG.md, runtime/near-runtime-fees/Cargo.toml, runtime/near-vm-errors/Cargo.toml, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner/Cargo.toml, runtime/runtime-params-estimator/Cargo.toml, runtime/runtime-standalone/Cargo.toml, runtime/runtime/Cargo.toml
- Same as `1.2.0`, but since it contained incompatible change, we had to bump major version.
- CI
=> fix: Bump runtime crates version to 2.0.0

chain/jsonrpc/src/lib.rs
*Resolves #3231.*
The limit has been changed from 2MB to 10MB, and it is now configurable via `config.json`. This limit affects the size of the transaction, and it was hit when users deploy big contracts; with this change, we should enable deployment of contracts of up to ~6.5MB.
=> feat(jsonrpc): Added configuration to the RPC payload size limit

.gitignore, pytest/lib/data.py, pytest/lib/mocknet.py, pytest/requirements.txt, pytest/tests/mocknet/load_testing.py, pytest/tests/mocknet/load_testing_helper.py
Previously blocks per second (bps) and transactions per second (tps) were computed based on metrics exposed by the node. However, these metrics may not always be an accurate measure (e.g. transactions will be double-counted in the case of a fork of the chain, and the bps metrics is an instantaneous snapshot rather than an average over a particular period of interest). Here, we change things so that bps and tps are measured based on the actual blockchain that is created by querying an archival node.
The `reset_data` function is also added to the mocknet library since it is useful when comparing different versions of the node or different configurations of the node (each run can start from a clean state to avoid possible interactions with existing state).
=> fix(mocknet): use the chain itself to measure bps and tps

Cargo.lock, Cargo.toml, nightly/nightly.txt, test-utils/testlib/src/node/process_node.rs, tests/test_rejoin.rs
Fixes #3141
Test was failing because it tried to query nodes before they were ready.
The fix is to properly wait until the node starts.
Also increase timeouts for tests that run nodes this way.
Test plan
---------
test_4_20_kill1
=> fix(test): fix test_4_20_kill1

Cargo.lock, chain/chain/src/chain.rs, chain/chain/src/types.rs, chain/chunks/src/lib.rs
Currently we already group receipts in `PartialEncodedChunk` by destination shard id and when we process them, we flatten receipts from all shard again and do the same grouping operation, which doesn't make much sense. This PR removes such redundancy.
Test plan
---------
* Nightly tests
* Test it on testnet.
=> fix: remove unnecessary computation in chunk receipt processing

Cargo.lock, chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/chain/tests/sync_chain.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, core/store/src/db.rs, core/store/src/lib.rs
Address several issues related to syncing:
* `sync_head` is not really useful and caused issues because it can go backward during header sync. Therefore we decide to remove it.
* `get_locator` assumed that genesis height is 0.
* We removed the check for block height when we receive a block. This caused us to waste time processing blocks that are too far in the future only to reject them as orphans.
Test plan
----------
* Nightly tests http://nayduck.eastus.cloudapp.azure.com:3000/run#/run/241
=> fix: remove sync head

nightly/tests_for_nayduck.txt, test-utils/testlib/src/user/mod.rs, test-utils/testlib/src/user/rpc_user.rs, test-utils/testlib/src/user/runtime_user.rs, tests/test_tps_regression.rs
There were mutliple issues with the test:
1. It was comparing the number of txs sent to the amount of gas used. I
assume it was written when the latter was equal to the number of txs?
2. It was using a bucketing technique to compare a sliding window of
TPS, but the bucketing code had several issues (e.g. it was not
normalizing the last bucket, making it dominate the sum, and also was
not ensuring that the number of buckets for the submitted and observed
txs was the same). Given that the bucketing is not really needed in the
test, I just removed it.
3. It was expecting all the blocks on all heights to be available, while
in reality some blocks can be skipped.
4. Once the two above are addressed, the number of observed TXs was
consistently around 1/2 of the number of submitted. That was due …
=> fix: (almost) Fix test_highload

chain/client/src/client_actor.rs, chain/client/src/info.rs
Address several issues related to log summary:
* Do no show validator info when the node is still syncing. Fixes #3167.
* Today we use `unwrap_or_return` in `log_summary`, which, if triggered, will stop `log_summary` from being run again.
* We do not use `gas_limit` in `InfoHelper` and therefore I removed it.
Test plan
---------
Run a node to connect to testnet to see that its log output is intended.
=> fix: address issues related to log summary

nightly/tests_for_nayduck.txt
The test takes between 8-10 minutes, so with the 600 seconds timeout is
hitting timeouts
Test plan
---------
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/265
=> fix: increase timeout for `test_gc_star_large`

chain/chain/src/chain.rs, chain/chain/src/store_validator.rs, core/primitives/src/version.rs, core/store/src/migrations.rs, neard/src/lib.rs
Today when we receive state parts, we borsh serialize them and then write the result to storage. The serialization here is unnecessary and wastes time.
Test plan
---------
Connect a node to testnet and observe that the time spent on `set_state_finalize` reduces by 0.3s after this change.
=> fix: avoid unnecessary serialization of state parts

chain/chain/src/chain.rs, chain/client/tests/process_blocks.rs
As mentioned in #3277, there is an inconsistency in gas price usage during state sync finalization, which can cause the state to diverge if gas price changes between sync block and its prev block.
Fixes #3277.
Test plan
---------
`test_catchup_gas_price_change`.
=> fix(chain): use correct gas price during state sync finalization

CODEOWNERS, Cargo.lock, Cargo.toml, chain/rosetta-rpc/CHANGELOG.md, chain/rosetta-rpc/Cargo.toml, chain/rosetta-rpc/README.md, chain/rosetta-rpc/rosetta.cfg, chain/rosetta-rpc/src/adapters.rs, chain/rosetta-rpc/src/config.rs, chain/rosetta-rpc/src/consts.rs, chain/rosetta-rpc/src/errors.rs, chain/rosetta-rpc/src/lib.rs, chain/rosetta-rpc/src/models.rs, chain/rosetta-rpc/src/utils.rs, core/primitives/src/types.rs, core/primitives/src/views.rs, core/runtime-configs/src/lib.rs, deny.toml, neard/Cargo.toml, neard/src/config.rs, neard/src/lib.rs, runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/verifier.rs
Fixed the tests by keeping Rosetta RPC server disabled by default (so TCP ports do not collide on concurrent tests execution). Will need to run nightly tests before merging
Nayduck is fixed: http://nayduck.eastus.cloudapp.azure.com:3000/#/run/293
=> feat(rosettarpc): Data API implementation (revamped)

runtime/near-runtime-utils/Cargo.toml, runtime/near-runtime-utils/README.md
Missing README for a crate to publish
Going to publish runtime crates at `2.2.0`.
- publish with dry-run
=> fix: Add NEAR Runtime utils README to be able to publish

pytest/lib/cluster.py, pytest/lib/proxy.py, pytest/tests/sanity/proxy_restart.py
On proxy restart wait for the previous instance to get closed before starting a new one
fixes #3134 
Test plan
=======
sanity/proxy_restart.py pass consistently
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/285
=> fix(proxy_restart): Consistent way to restart nodes with proxy

chain/network/src/codec.rs, chain/network/src/peer.rs, chain/network/src/types.rs, core/primitives/src/version.rs, pytest/lib/branches.py, pytest/lib/messages/network.py, pytest/lib/peer.py, pytest/lib/utils.py, pytest/tests/sanity/backward_compatible.py, pytest/tests/sanity/db_migration.py, pytest/tests/sanity/upgradable.py, pytest/tests/spec/network/future_handshake.py, pytest/tests/spec/network/handshake.py
This change is only backward compatible with branch latest_supported_version, 
**We must merge and deploy that branch first.**
Fixes #3136 
Test plan
=========
1. Check latest_supported_version_2 branch is backward compatible with
latest_supported_version branch.
Run `backward.py` with `main(near_root, "latest_supported_version", "latest_supported_version_2")` and check it passes.
2. `handshake.py` pass
=> fix: Use handshake version 2

neard/src/config.rs, neard/src/main.rs
Fixes #3286.
Test plan
---------
Test locally that when `chain-id` is `mainnet` and we pass an account id to neard, validator key is indeed generated.
=> fix: generate validator key when chain-id is mainnet

chain/chain/src/chain.rs
During catch up we may run state sync for the first epoch and when we finalize it, it requires applying the chunk of the prev block of the sync block, which is the chunk of genesis, and to apply the chunk, we need to know the previous gas price, which, if we try to get directly, will fail because there is no prev block.
=> fix(test): fix skip_epoch.py

chain/client/src/lib.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/client/tests/query_client.rs
Fixes #3305.
Test plan
--------
`test_execution_outcome_for_chunk`.
=> feat: allow querying execution outcomes for a chunk from ViewClient

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/chain/src/store_validator.rs, chain/chain/src/store_validator/validate.rs, core/primitives/src/version.rs, core/store/src/db.rs, core/store/src/db/migration_utils.rs, core/store/src/lib.rs, core/store/src/migrations.rs, core/store/src/migrations/v6_to_v7.rs, core/store/src/migrations/v8_to_v9.rs, neard/src/lib.rs
Fix inconsistencies between code that writes to storage and gc.
ColTransactions:
one value per transaction per chunk in ColChunks
ColReceiptIdToShardId:
one value per receipt per record in ColOutgoingReceipts
Add a store migration that doesn't change the format, but recomputes
these columns.
Fixes #3247, #2930.
Test plan
---------
re-enable chunk_tx_exists in store-validator
=> fix(store): Fix ColTransactions and ColReceiptIdToShardId

pytest/tests/sanity/upgradable.py
`upgradable.py` depends on the protocol version of the latest rc branch. Since the latest rc branch is already on version 35 now, we need to remove the check for implicit account creation.
=> fix: upgradable.py

chain/chain/src/chain.rs, chain/client/src/lib.rs, chain/client/src/types.rs, chain/client/src/view_client.rs, chain/client/tests/process_blocks.rs, chain/client/tests/query_client.rs
In #3309 I misunderstood what @frol wanted and therefore only return the execution outcomes from transactions and receipts included in the chunk. This PR rectifies the error and it now returns all the execution outcomes generated when the chunk is applied, which includes execution outcomes for local and delayed receipts. Fixes #3305 
Test plan
--------
`test_chunk_execution_outcome`
=> fix: chunk execution outcomes

Cargo.lock, chain/indexer/CHANGELOG.md, chain/indexer/Cargo.toml, chain/indexer/src/lib.rs, chain/indexer/src/streamer/mod.rs, chain/indexer/src/streamer/streamer.rs, tools/indexer/example/src/main.rs
As we found out some `AddKey` actions for transactions where signer is receiver (sir) the receipt created as "local" and is not included into `ChunkView`. But we need those receipts for indexing purposes altogether with `ExecutionOutcome` for such receipts. @bowenwang1996 addressed the issue https://github.com/nearprotocol/nearcore/issues/3305 to help us collect `ExecutionOutcomes` for specific block more easily (corresponding PR #3312) 
So in this update:
* `StreamerMessage` changes:
* We add `local_receipts: Vec<near_primitives::views::ReceiptView>` to include local receipts
* Rename `outcomes` field to `receipt_execution_outcomes`
* `receipt_execution_outcomes` field type changed to be `HashMap<CryptoHash, near_primitives::views::ExecutionOutcomeWithIdView>` and includes **only …
=> feat(indexer): Explicitly add local receipts to StreamerMessage

Cargo.lock, chain/client/src/sync.rs
#3241 introduced an issue during block sync: it maintains `last_block_header` as the block header with largest height in the cache and has this logic that checks whether it is sufficiently close to header head and if it is, then the cache is ignored. However, the issue is that the sync loop runs every 10ms and therefore, it is almost always the case that this condition is triggered and the cache is effectively ignored. This PR fixes it by removing the condition.
Test plan
---------
Sync a node to testnet with this change and observe major improvements in syncing speed.
=> fix: address slowness in block sync

chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, nightly/nightly.txt, pytest/tests/sanity/handshake_tie_resolution.py
There existed a situation if two peers A and B initiated the handshake
almost at the same time, the a tie happens, and it is resolved in favor
of the connection initiated by the peer with smaller PeerId.
Let's say A < B. There is a situation in which both started connection
at the same time, and connection initiated from A is resolved first, so
both peers successfully consolidate connection with each other. However
when the second connection is removed, B call Unregister (this is always
called when a PeerActor is stopped) removing A from the set of active
peers incorrectly.
This situation was surfaced after decreasing the retry timeout to the
order of milliseconds, letting such connections happenning almost
simulatenously.
Solution: Add a flag to the Unregister signal, such that a peer is …
=> Fix(network): Resolve handshake ties properly

pytest/lib/branches.py
Resolves #3318 
When running the test on latest master I noticed the following exception:
```
TypeError: expected str, bytes or os.PathLike object, not VersionInfo
```
And, after coercing the `other_branch` param as a `str`, I was able to get a passing test:
```
(venv) nearcore/pytest [master●] » python tests/sanity/upgradable.py
Latest beta release branch is 1.14.0
Compiling neard v1.2.0 (/Users/near/code/nearcore/neard)
Finished dev [unoptimized + debuginfo] target(s) in 38.85s
Finished dev [unoptimized + debuginfo] target(s) in 1.68s
Updated 1 path from the index
Downloading near & state-viewer for 1.14.0@Darwin
curl: (22) The requested URL returned error: 403 Forbidden
Switched to a new branch '1.14.0'
remote: Enumerating objects: 144, done.
remote: Counting objects: 100% (144/144), …
```
=> upgradable.py should be runnable on mac

Cargo.lock, chain/jsonrpc/src/lib.rs, chain/jsonrpc/tests/rpc_query.rs, chain/network/src/types.rs, core/crypto/src/signature.rs, core/primitives/src/transaction.rs, genesis-tools/genesis-csv-to-json/src/serde_with.rs, neard/src/genesis_validate.rs, runtime/runtime-params-estimator/src/cases.rs, runtime/runtime/src/verifier.rs
This allows me to use PublicKey type inside clap-decorated structs to automatically validate the input.
=> refactor(core): Implement FromStr instead of TryFrom<&str> for PublicKey to enable transparent usage of the type on clap

pytest/lib/cluster.py
If user wants to test her change with several nodes, she can change the config['local'] = False and config['preexist'] = True.
All communication is happening with master instance by sending http requests.
When test starts master returns ips of available instances, where nerd binary is build with current user's sha.
When test is finished or killed, logs from remote instances are copied to .neard/testN/remote.log file.
User also should be auth with nayduck to run any tests
=> Adding ability to run stress tests on preexisting instances

chain/client/src/client_actor.rs, chain/client/src/sync.rs
Currently when an archival node syncs old blocks, they will still try to request them from regular nodes and this causes requests to be wasted and also, if the archival peers are close to the end of `highest_height_peers`, it could potentially cause the node to get stuck in syncing.
Fixes #3365 
Test plan
---------
`test_block_sync_archival`
=> fix(sync): archival node should request old blocks from archival nodes

chain/network/src/peer_manager.rs, chain/network/src/test_utils.rs, chain/network/src/types.rs, chain/network/tests/full_network.rs, chain/network/tests/routing.rs, chain/network/tests/runner/mod.rs, neard/src/config.rs
Each archival node will allocate some of its connections slots
for other archival nodes. When it is rebalancing, some connections
are dropped, but it won't drop any connection to other archival
node, if the number of direct archival nodes is lower than some
threshold.
Fixes: #3364
Test plan
=========
archival_node @ chain/network/tests/routing.rs should pass
This test connects to archival nodes to each other, and perform several
rounds of connection from other nodes forcing a rebalancing, and check
that connection between archival node is not dropped.
=> fix(network): Persist links between archival nodes

chain/indexer/README.md
Setting huge "block_fetch_horizon" did not really work, and since #3168 it is not necessary.
=> doc(indexer): removed an outdated block_fetch_horizon tweak from the README

chain/network/src/peer.rs, core/primitives/src/version.rs
When connection is inbound from node with version 34
handshake failed because node with version 39 wasn't
using correct version to communicate.
Test plan
=========
Backward compatible test passes.
Tested on local network with both versions, previosly nodes
compiled with debug mode were panicing, because HandshakeFailure
was passed to recieve_client message. This behavior is fixed.
=> fix(network): Use version from other peer

pytest/lib/proxy.py
`start_proxy` starts a process that proxifies the node in the
background, and immediatelly returns control to the main process.
If the main process then kills the node, it sets `local_stopped` to 1.
If `start_proxy` hasn't gotten to `check_finish` yet, `check_finish`
will observe `local_stopped` set to 1, and stop the server.
`start_proxy` will then proceed to calling `server.serve_forever`, which
will crash.
I'm fixing it by making `start_proxy` actually wait until it gets to
`serve_forever` before returning control
=> fix: Fixing proxy_restart

chain/rosetta-rpc/src/lib.rs, chain/rosetta-rpc/src/models.rs
Given the public key, it is trivial to populate the expected signature type, so we do it now.
=> feat(rosetta-rpc): Populate signature type in the /construction/payloads response

chain/network/src/peer.rs
When #3302 started the protocol version was 37 but when it is merged, the protocol version got bumped to 39 and therefore this line https://github.com/nearprotocol/nearcore/blob/6efb708f138ee3858b7ed3c4613c055282a26371/chain/network/src/peer.rs#L292 is inconsistent with the new protocol version introduced in #3302. Currently it only works because node before this change always send `HandShakeV2`, which the new node is able to deserialize. Otherwise a node running current master would not be able to connect to a node on protocol version 38 (current testnet).
=> fix: handshake versioning

pytest/tests/sanity/rpc_query.py
The test compares results from two queries, and it clears
block height and hash.
account.locked also needs to be cleared in case we're at an epoch
boundary
Test plan
---------
run many times
=> fix(test): fix rpc_query.py

chain/jsonrpc/src/lib.rs, chain/jsonrpc/src/metrics.rs, core/metrics/src/lib.rs
fix: include method as label in rpc request total metric
Expose the RPC request method as a prometheus label so we can get a better sense of how RPC nodes are used.
Test plan
---------
* Spun up `neard` locally, hit `status` and `health` RPC methods, checked `/metrics`
```
http_rpc_requests_total{method="health"} 1
http_rpc_requests_total{method="status"} 1
```
* Will see these on `testnet` and `betanet` deploys
FYI @chefsale @mhalambek
=> fix(rpc): include method as label in rpc request total metric

pytest/tests/adversarial/start_from_genesis.py
Disable observer node.
Fixes #3422
Test plan
---------
run many times
=> fix(test): start_from_genesis.py

pytest/lib/cluster.py
If remote test is triggered from NayDuck and there are not enough available nodes, kill the test with exit code 13, which will postpone NayDuck test for several minutes. Will retry test to get available nodes again.
=> Postpone remote test if not enough nodes found

Cargo.lock, chain/rosetta-rpc/CHANGELOG.md, chain/rosetta-rpc/Cargo.toml, chain/rosetta-rpc/src/adapters/mod.rs, chain/rosetta-rpc/src/adapters/snapshots/near_rosetta_rpc__adapters__tests__nfvalidator1_receipt_processing_transaction.snap, chain/rosetta-rpc/src/adapters/snapshots/near_rosetta_rpc__adapters__tests__nfvalidator2_action_receipt_gas_reward_transaction.snap, chain/rosetta-rpc/src/adapters/snapshots/near_rosetta_rpc__adapters__tests__validators_update_transaction.snap, chain/rosetta-rpc/src/models.rs, chain/rosetta-rpc/src/utils.rs
*Resolves #3435*
NOTE: The order of transactions in Rosetta /block response is arbitrary. If that is critical, we need to address it separately recovering the order of events processing inside nearcore (validator accounts are updated first, then transactions are translated into receipts, then local receipts are executed, then delayed receipts are executed, then new incoming receipts are executed, then delayed receipts indices are computed)
=> fix(rosetta-rpc): fixed duplicates by transaction identifier in /block Data API

Cargo.lock, chain/chain/src/store_validator.rs
When store-validator times out, it was still validating
the first value in each column, which is wrong if it skipped
values in previous columns.
Fixes #3420, #3424
Test plan
---------
one_val.py many times
=> fix(store-validator): fix wrong failures on timeout

Cargo.lock, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, core/store/src/trie/shard_tries.rs, neard/src/runtime.rs
Currently view client and client share the same cache inside trie. This causes problem when there is some expensive request coming in from view client (state part request for example), which will cause lock contention and can potentially block the client actor. This PR creates separate cache for view client. Notice that while the cache can contain stale data that have been deleted, view client is tolerant to such transient inconsistencies so there should not be an issue.
Test plan
---------
nayduck run http://nayduck.eastus.cloudapp.azure.com:3000/#/run/539
=> fix(trie): separate caches for view client and client

runtime/runtime-params-estimator/estimate.sh
Based on @evgenykuzyakov and my experiment, cargo will use all features in runtime-params-estimator/Cargo.toml since it's in that dir, this cause rocksdb single thread features enabled, and cause genesis-populate stuck.
Test Plan
------------
`./estimate.sh` works locally. no "Disabled all background threads in rocksdb" is printed in genesis-populate
=> fix(script): estimate.sh in other crate dir cause genesis-populate built with wrong feat

Cargo.lock, core/chain-configs/Cargo.toml, core/chain-configs/src/genesis_config.rs, core/store/src/db.rs, core/store/src/lib.rs, core/store/src/trie/shard_tries.rs, core/store/src/trie/update.rs, neard/src/runtime.rs, runtime/runtime/src/lib.rs
- When the node starts for the first time, save the hash of genesis in
storage, and assert on every restart that same genesis is used.
- Save the genesis state roots on first start, and don't rebuild the
trie on every restart.
Fixes #3151
Fixes #3063
Test plan
---------
existing tests
=> fix(genesis): Don't write genesis records on restart

core/runtime-configs/src/lib.rs, genesis-tools/genesis-populate/src/lib.rs, neard/src/runtime.rs, runtime/runtime-params-estimator/src/testbed.rs, runtime/runtime-standalone/src/lib.rs, runtime/runtime/src/lib.rs, runtime/runtime/tests/runtime_group_tools/mod.rs, runtime/runtime/tests/test_regression.rs, test-utils/testlib/src/node/runtime_node.rs, test-utils/testlib/src/runtime_utils.rs, test-utils/testlib/src/user/runtime_user.rs
Move `RuntimeConfig` from `Runtime` initialization to `ApplyState` object.
This makes `Runtime` completely stateless and allows to execute transitions based on different configs.
It allows to upgrade `RuntimeConfig` with the new fees based on the protocol version for the current block.
This change should be NOOP and doesn't change the protocol. 
NEP: https://github.com/nearprotocol/NEPs/issues/120
Issue: #3158
=> feat: Refactor Config out of Runtime

chain/jsonrpc/src/lib.rs, chain/jsonrpc/src/metrics.rs, core/metrics/src/lib.rs
This adds per method processing time tracking
so which should make monitoring easier.
=> Add labels to rpc processing time historgram.

core/store/src/migrations.rs
Currently in 14 -> 15 database migration we didn't take into account postponed receipts and therefore the migration can fail.
Test plan
---------
Test on testnet data that previously failed the migration.
=> fix(storage): fix 14->15 migration

ATTRIBUTIONS.md, Cargo.lock, core/crypto/src/signature.rs, runtime/near-evm-runner/Cargo.toml, runtime/near-evm-runner/src/near_ext.rs
As a first step in #3506, upgrade OpenEthereum from [pre-2.6.0](https://github.com/openethereum/openethereum/commit/eed630a002bbebed3a3097127f2483213ff52079) (Jun 2019) to [2.6.2](https://github.com/openethereum/openethereum/releases/tag/v2.6.2) (Aug 2019).
OpenEthereum 2.6.2 is the last release that nearcore can currently pull in without build errors. Further upgrades will require code changes in near-evm-runner. (I'm working on those.)
The upstream diff from what we currently pull in compared to 2.6.2: https://github.com/openethereum/openethereum/compare/eed630a...v2.6.2
=> Upgrade to OpenEthereum 2.6.2

Cargo.lock, runtime/near-evm-runner/Cargo.toml, runtime/near-evm-runner/src/interpreter.rs, runtime/near-evm-runner/src/lib.rs, runtime/near-evm-runner/src/near_ext.rs
As the next step in #3506, and following up from #3542, upgrade OpenEthereum from [2.6.2](https://github.com/openethereum/openethereum/releases/tag/v2.6.2) (Aug 2019) to [2.6.8](https://github.com/openethereum/openethereum/releases/tag/v2.6.8) (Dec 2019), the last release in the 2.6.x series.
This brings us up to par on the [Istanbul](https://eth.wiki/en/roadmap/istanbul) hard fork, which incorporated many EIPs, changing gas metering and adding a new precompile as well as two new opcodes:
- [EIP-152: Add BLAKE2 compression function `F` precompile](https://eips.ethereum.org/EIPS/eip-152)
- [EIP-1108: Reduce alt_bn128 precompile gas costs](https://eips.ethereum.org/EIPS/eip-1108)
- [EIP-1344: ChainID opcode](https://eips.ethereum.org/EIPS/eip-1344) (includes a new opcode: `CHAINID`)
- …
=> Upgrade to OpenEthereum 2.6.8 (Istanbul support)

core/store/src/migrations.rs
Since the prev state of the tail block isn't available, trying to unwrap on accessing delayed receipts will fail. Fixes #3536.
Test plan
---------
* Run the change against the failed db and verify and it can successfully migrate.
=> fix(storage): fix 14 -> 15 migration

neard/src/main.rs
Added no-ansi flag to disable coloring in neard and special chars:
`
sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/nearcore (master)> ./target/debug/near --no-ansi run
`
`                                                                                                                                                                                                                                                                   sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/nearcore (master)> ./target/debug/near run
`
=> Added --no-ansi flag to disable coloring and ansi chars in logging

runtime/near-evm-runner/src/builtins.rs, runtime/near-evm-runner/src/evm_state.rs, runtime/near-evm-runner/src/lib.rs, runtime/near-evm-runner/src/near_ext.rs, runtime/near-evm-runner/src/types.rs, runtime/near-evm-runner/src/utils.rs, runtime/near-evm-runner/tests/standard_ops.rs, runtime/near-vm-errors/src/lib.rs, test-utils/testlib/src/standard_test_cases.rs
- BREAKING: Added `FunctionCallArgs` structure and changed function call args to require this input. It adds `4` bytes for the size of RLP encoded input before the input. Makes function_call args a standard borsh structure
- BREAKING: Updated `ViewCallArgs` to be standard borsh structure. Same `4` bytes in front of the input
- Fix: Updated gas accounting for view calls, meta calls, and fixed alias function call when counting gas.
- Added a bunch of TODO.  
- Refactor: Created enum for `Method` to be explicit about `method_name` and parse it only once.
- Refactor: Updated storage to avoid some key copies
- Refactored some duplicated code for converting interpreter call result
- Refactor: Removed some cloning from input 
- standard unit test is still failing, probably because of the invalid …
=> feat(evm): EVM standard borsh args + refactoring

chain/chain/src/store_validator/validate.rs
Fix storage check that caused epoch_switches.py to fail. Fixes #3443
=> fix(test): fix epoch_switches.py

core/store/src/trie/shard_tries.rs, core/store/src/trie/trie_storage.rs
After we split caches in trie into client caches and view client caches, we didn't clear view client caches before state sync.
Test plan
---------
test_data_reset_before_state_sync
=> fix: clear trie view caches before state sync

chain/jsonrpc/src/metrics.rs, core/metrics/src/lib.rs
Instaead of default use exponential histogram buckets.
Renaming of existing rpc metrics to all start with near_rpc.
=> fix(Increase historgram levels up to 30)

core/store/src/db.rs
Rocksdb block size cache gets allocated per column. Currently it's 47*180 mb = 8.5gb.
By decreasing rocksdb block cache size to 32mb, we will decrease total cache size to 1.5gb.
In the future total cache size can be decreased by fine tuning cache sizes per column.
=> Change per column rocksdb block cache size from 180mb to 32mb

chain/chain/src/chain.rs, chain/chain/src/error.rs, chain/client/tests/process_blocks.rs, core/primitives/src/block.rs, core/primitives/src/block_header.rs
Make header validation match chunk mask against chunks_included for V1
headers.
Make block validation match chunk mask in header against computed mask
from block body. Don't check chunks_included anymore, as it's checked
in header validation.
Also refactor chunks_included logic in Block::genesis as it was
unnecessarily complex and did not match the logic for non-genesis
blocks anyway.
Fixes #3586
Test plan
---------
Unit test
=> fix(chain): validate chunk mask

core/primitives/src/version.rs
The macro was broken and checked if the feature protocol version was not less than the current protocol version.
Fixing the macro.
Discovered by @ailisp 
Test plan:
- CI
=> fix: fix nightly version check

neard/src/main.rs
Currently if the directory doesn't contain git version information (for example downloaded as a zip), then neard will fail to compile. This PR fixes the issue by adding a fallback.
Test plan
---------
Download code as zip and verify that it can now compile
=> fix: add fallback for git version

chain/client/tests/process_blocks.rs
The test messes with the block at height 4, and fails if that height
gets skipped. Change it to the first block at height >=4.
Fixes #3634
Test plan
---------
run locally
=> fix(test): test_ban_peer_for_invalid_block_header

core/primitives/src/version.rs, neard/res/genesis_config.json, runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs
Fix `storage_usage` subtraction to be correct. Previously it included one extra byte for type of `Option<AccessKey>` instead of `AccessKey`.
- CI
- new unit tests
=> fix: Fix delete_key storage_usage off by one error

neard/src/main.rs
Added the protocol version to to  version command for detecting protocol version changes in betanet based on two binaries for triggering a hard-fork on betanet.
```
sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/nearcore (protocol-flag)> ./target/debug/neard --version
NEAR Protocol Node 1.2.0 (build 522ccf21) (protocol 41)
```
=> feat(version): include the protocol version in the version command

.github/workflows/mac_binary.yml
The old actoin we used for pulling aws-cli tool isn't maintained anymore and the API which it was using got broken.
=> fix(build): fix failing action for mac osx build

neard/src/migrations.rs
This was a one-off fix done a while ago but somehow wasn't merged into master. Some partners ran into the same issue so it makes sense to merge this to master. The issue is that the migration can fail due to
```
thread 'main' panicked at 'unexpected error during migration, IO Error: Not all bytes read
Cause: Unknown', neard/src/migrations.rs:102:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and I realized that the logic there is not actually needed since we only care about the canonical chain when migrating past data.
=> fix: fix 12 -> 13 migration

Cargo.lock, runtime/CHANGELOG.md, runtime/near-evm-runner/Cargo.toml, runtime/near-runtime-fees/Cargo.toml, runtime/near-runtime-utils/Cargo.toml, runtime/near-vm-errors/Cargo.toml, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner/Cargo.toml, runtime/runtime-params-estimator/Cargo.toml, runtime/runtime-standalone/Cargo.toml, runtime/runtime/Cargo.toml
Bumping version of near runtime crates to `2.3.0`, so direct dependency on master can be used as a crates.io patch from `near-sdk-rs` for CI against `nearcore:master`
- Tested `near-sdk-rs` `v2.0.0` still compatible.
- Patched `near-sdk-rs` branch for tag `v2.0.0` with this branch.
- Executed `cargo update` to upgrade local versions in `Cargo.lock`
- Verified it compiles and tests pass
=> fix(runtime): Bump runtime and VM version to `2.3.0`

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/tests/process_blocks.rs
Fix the following issues:
* Reject blocks older than tail right away. Resolves #3691.
* Avoid broadcasting blocks when they are accepted. Resolves #3690.
Test plan
---------
* `test_not_broadcast_block_on_accept`
* Nayduck
=> fix(chain): reject old blocks right away

chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/tests/challenges.rs, core/primitives/src/utils.rs
This PR fixes an issue where the node is doing redundant (and expensive) validation work. This overhead is especially an issue when chunk forwarding is enabled.
Fixes #3683
Testing plan:
* Existing tests
=> fix(chunks): Validate partial encoded chunk header signatures exactly once

chain/chain/src/chain.rs, chain/chain/src/lib.rs, chain/chain/src/missing_chunks.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/tests/challenges.rs, chain/client/tests/process_blocks.rs, core/primitives/src/sharding.rs
Previously the logic was to try applying all blocks which were missing chunks each time we added a new chunk, even if there were still more chunks missing. With this change we now keep track of what chunks each block is missing and only apply the block again after we have all the missing chunks.
Fixes #3684 
Testing plan:
* new tests for the new data structure
* existing unit tests
=> fix(chunks): Do not apply a block until we have all its missing chunks

chain/chunks/src/chunk_cache.rs, chain/chunks/src/lib.rs, chain/client/src/client.rs, chain/network/src/codec.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/types.rs, core/primitives/src/utils.rs
This PR attempts to improve performance by limiting the amount of cloning done in the logic for processing partial encoded chunks. In the process I found there were a couple places in the networking layer where there was excess cloning as well, and fixed there too.
Fixes #3700 
Testing plan:
* No logic is changed, so we rely on existing testing infrastructure
=> fix(chunks & network): Remove some unnecessary cloning

neard/src/config.rs
We started hitting the limit of the genesis size on testnet. Increasing it.
=> fix(download-genesis): increase the maximum size of the genesis size

chain/client/tests/process_blocks.rs, core/store/src/trie/shard_tries.rs, core/store/src/trie/trie_storage.rs
Revert invalidating view client cache on gc/data reset to avoid
lock contention.
Fixes #3712.
This reverts commit 9428c7dd149e0998e5e693c8c253e490919f293c.
=> Revert "fix: clear trie view caches before state sync (#3593)"

CODEOWNERS
To not bother @evgenykuzyakov with all EVM reviews.
=> change codeowners for EVM runtime

Cargo.lock, Cargo.toml
[syn](https://crates.io/crates/syn) [1.0.58](https://crates.io/crates/syn/1.0.58), released yesterday (January 5), breaks our build despite it ostensibly being a semver-compatible update:
To reproduce the problem, remove your top-level `Cargo.lock` and attempt to rebuild nearcore from scratch.
See https://github.com/nushell/nushell/issues/2867 and https://github.com/nushell/nushell/pull/2868 for another project who already ran into this same trouble.
This pull request pins syn to 1.0.57 for now. The pin can be removed once upstream fixes their broken release management process.
=> Pin the syn dependency to avoid breaking change

utils/near-performance-metrics/src/actix_enabled.rs, utils/near-performance-metrics/src/stats_enabled.rs
Some of the logs produced by near-performance-metrics should be warnings instead of infos
=> Change prints inside near-performance-metrics to be warnings

.github/workflows/mac_binary.yml
we are currently building only the normal release, this is needed for nearup to operate on osx for betanet.
=> feat(mac): add osx nightly builds to the github action

utils/near-performance-metrics/src/stats_enabled.rs
I'll remove the number printed in print_performance_stats function to make stats less confusing.
=> make stats about futures less confusing

runtime/near-vm-runner/src/imports.rs, runtime/near-vm-runner/src/wasmer_runner.rs, runtime/near-vm-runner/src/wasmtime_runner.rs
Modifies `wrapped_import` macro to add an ability to introduce new host methods.
This change doesn't modify the protocol.
- CI
- https://github.com/near/nearcore/pull/3827 for an example of adding a new import
=> feat: Add ability to import methods guarded by protocol feature

Cargo.lock, runtime/near-vm-runner/Cargo.toml, runtime/near-vm-runner/src/cache.rs
Reverts near/nearcore#3855
What do we gain by compressing contracts in cache? It definitely slows down the runtime which decreases the function call TPS. What the cost effects of doing it?
There was no migration done from cache Key1 to Key2, so if a node runs a current protocol, then all contracts becomes uncompiled at once.
=> Revert "Compress compiled contracts."

core/store/src/trie/mod.rs, core/store/src/trie/state_parts.rs, core/store/src/trie/trie_storage.rs, core/store/src/trie/trie_tests.rs
Make creating a state part not use TrieCache to reduce
lock contention in view client.
Also remove Send+Sync from TrieStorage since it's not shared between
threads.
Relevant issue: #3742
Test plan
---------
existing tests
=> fix(trie): Don't use cache for obtain_state_part

CONTRIBUTING.md
* point to rustup docs  rather than to the long-obsolete docs for
Rust 1.2.
* document dependencies on native libraries. At the moment, only
libclang is required.
=> doc: update dev env section

chain/network/src/peer_manager.rs
We should fix peer_manager not to schedule multiple computations of routing table at the same time.
=> change peer_manager not to recompute routing multiple times

core/primitives/src/utils.rs, pytest/tests/sanity/backward_compatible.py, runtime/runtime/src/actions.rs, runtime/runtime/src/ext.rs, runtime/runtime/src/state_viewer.rs
#3821 introduces a bug in data id calculation as it directly passes in the current block hash instead of passing the prev block hash first and then upgrade to current block hash. This causes nodes with that commit to produce different receipts and therefore different state after they apply a block. The reason why we didn't catch it in CI is that backward_compatible.py does not have a function call that uses promise.
Test plan
----------
`backward_compatible.py` fails after the fix to the test on master but passes after the change in this PR.
=> fix(runtime): fix receipt id change

utils/near-performance-metrics/src/stats_enabled.rs
There was a crash in log function it would happen rarely because of a race condition when 'performance-stats' feature was enabled.
=> fix crash in performance stats while logging

Cargo.lock, chain/indexer/CHANGELOG.md, chain/indexer/Cargo.toml, chain/indexer/src/lib.rs, tools/indexer/example/src/main.rs
* Update Indexer Framework to version 0.8.0
* Corresponding changes to Indexer Example to be up to date
All the changes made because of breaking change in actix runtime, we cannot attach processes to runtime while runtime isn't started. That's why runtime needs to be created on the Indexer side like shown in Indexer Example.
=> refactor (indexer) Update Indexer Framework and Indexer example according to changes on actix side

chain/client/tests/process_blocks.rs
If the height is skipped, use the correct signer.
Fixes #3898
Test plan
---------
test now passes if height is skipped
=> fix(test): flaky test_not_ban_peer_for_invalid_block

.buildkite/pipeline.yml
After a recent #3869, we can further improve the sanity of all the dependencies to avoid multiple versions (not only it can increase the binary size and compilation time, but it might also bring some security issues).
=> chore(ci): Deny duplicate dependencies for all the features on CI sanity check

tools/delay_detector/src/lib.rs
In runtime we often want to cache delay < 50ms, make it configurable so delays from other module still filtered at 50ms.
Test Plan
---------
Build with delay_detector it still works. use delay detector with shorter delay works
=> tool(delay_detector): add configurable min delay

chain/rosetta-rpc/src/lib.rs
It is similar to #3911 (fix for JSON RPC), but now it is for Rosetta RPC
=> fix(rosetta-rpc): fixed CORS to be permissive by default

utils/near-performance-metrics/src/actix_enabled.rs, utils/near-performance-metrics/src/stats_enabled.rs
We print every minute performance stats for all threads. It will be useful to print this information split by enum type.
=> Improve print_stats method in near-performance-metrics.

Cargo.lock, neard/Cargo.toml, utils/near-performance-metrics/Cargo.toml
We will use near-rust-allocator-proxy from crates.io instead of from url.
Closes #3889
=> start using near-rust-alloctor-proxy 0.2.7 from crates.io

core/store/src/trie/iterator.rs, core/store/src/trie/mod.rs
TrieIterator::seek comment:
/// Position the iterator on the first element with key => `key`.
Fix a bug where it could incorrectly position the iterator at a
a subtree of keys with a prefix < `key`.
The bug never triggers: `seek` is currently used in the following places
1. TrieUpdateIterator with key prefix. It works correctly, because if
the trie has keys with the prefix, the bug does not trigger, and if
it doesn't, TrieUpdateIterator's internal logic will stop it.
2. TrieUpdateIterator with prefix and range. Used only in tests.
3. TrieViewer view_state. Works correctly because of similar logic to
TrieUpdateIterator.
4. get_trie_nodes_for_part. Works because key for `seek` always ends in
a trie node.
Test plan
---------
new test
manually check all calls to `seek` to make sure this …
=> fix(trie): fix iterator seek

core/chain-configs/src/genesis_config.rs
The links to NEAR's chain IDs over at https://github.com/ethereum-lists/chains were broken.
=> fix: chain ID links

chain/network/src/peer_manager.rs
Reverts near/nearcore#3961, as canary is broken and can;'t find peers anymore. Not sure 100 percent that this is the cause, but most liekly.
=> Revert "refactor: remove roundabout way to connect to socket"

chain/network/src/peer_manager.rs
Seems like this Resolver stuff is just ... unnecessary? It sounds like
it does DNS resolution (with its notoriously sync-only APO), but this
isn't needed in this case. addr is a `SocketAddr`, ie, a resolved IP.
Note the 1 second timeout: it's the same value that was used by actix:
https://github.com/actix/actix/blob/v0.11.0-beta.1/src/actors/resolver.rs#L382
This is a second attempt at https://github.com/near/nearcore/pull/3961, which was reverted in https://github.com/near/nearcore/pull/3964. I've looked at the code more closely, and noticed that atix hard-codded a one-second timeout here.
This is def a problem in theory -- if the peer just drops packets (instead of actively refusing the connection), the whole peer manager get's stuck in the `.wait(ctx);` call for several minutes. Not …
=> refactor: remove roundabout way to connect to socket

Cargo.lock, chain/jsonrpc/Cargo.toml, chain/jsonrpc/src/lib.rs
Closes #3951 
Doesn't affect #3938 because that particular method (`query`) is being refactored right now in #3944 
As for the `query` timeout can appear there because of network routing but in my PR which refactors `query` method we totally removed routing (decision made by @bowenwang1996 and @frol) so it seems like timeout from jsonrpc side wouldn't be possible.
=> feat(jsonrpc): Add warn log to jsronrpc methods where time out can happen

runtime/near-vm-logic/src/gas_counter.rs, runtime/near-vm-logic/src/lib.rs, runtime/near-vm-logic/tests/helpers.rs, runtime/near-vm-runner/src/lib.rs, runtime/runtime-params-estimator/src/stats.rs, runtime/runtime-params-estimator/src/testbed_runners.rs, runtime/runtime/src/lib.rs
Practically, this gets rid of `#[cfg]` here and there.
In general, it's a good rule of thumb to protect access to global and
thread local data with accessor functions. That way, the clients don't
need to deal with RefCells and Mutexes themselves.
=> refactor: simplify access to COSTS_CONTER thread local

Cargo.lock, chain/indexer/CHANGELOG.md, chain/indexer/Cargo.toml, chain/indexer/src/lib.rs, tools/indexer/example/src/configs.rs, tools/indexer/example/src/main.rs
During the creation of a tutorial about an indexer we've noticed that the signature of `neard::init_configs` is quite big and hard to use, especially from indexer perspective, so we want to introduce a way of simplifying things.
`InitConfigArgs` from indexer example was taken as a base, so now we have the same struct exposed from NEAR Indexer Framework along with wrapper-function `indexer_init_configs`. It takes `dir` arg and new structure with the same arguments as `neard::init_configs` function. Calls the original one to initialize configs, but now is a bit easier to use from user's point of view.
I am open for suggestions to make it even better, this is a blocker for publishing of the first indexer tutorial to the docs.
=> feat(indexer): Simplify usage of init_configs from indexer perspective

Cargo.toml
I made wasmer1 as default and this doc, but revert to wasmer0 default when applied code reviews, however forget to update this comment.
Test Plan
---------
Tested locally with debug prints to see build neard with wasmer_default, wasmer1_default and none of them when build trigger correct vm.
=> fix(doc): clarify wasmer 0.x is default when build with no feature

runtime/near-vm-runner/src/runner.rs, runtime/near-vm-runner/src/wasmer1_runner.rs, runtime/near-vm-runner/src/wasmer_runner.rs, runtime/near-vm-runner/src/wasmtime_runner.rs
I've brietly tried to add a command object here, so that the API looks like this:
```rust
VmRunConfig::new(code, hash, context, ...)
.vm(VmKind::Wasmtime)
.profile(profile_data)
.run()
```
but it wasn't a clear cut improvement.
=> refactor: reduce duplication in the vm running code

utils/near-performance-metrics-macros/src/lib.rs
Once we enabled rust flags for denying warnings, macosx build broke due to this panic.
=> fix(build): macos not building due {:?} warning

.buildkite/pipeline.yml
* `--all` is deprecated in favor of `--workspace`
* `--all-targets` is even better than `--tests` and `--benches`
=> refactor: cleanup sanity checks CI step

Cargo.lock, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner-standalone/src/main.rs, runtime/near-vm-runner-standalone/src/tracing_timings.rs, runtime/near-vm-runner/Cargo.toml, runtime/near-vm-runner/src/wasmer_runner.rs
(builds on top of #3973)
`tracing` is a generic instrumentation framework. It allows manually
instrumented code to signal point-in-time events and nested spans.
Separately, a consumer for those spans and events can be defined.
In this particular case, we use `tracing` to measure time of various
phases of contract execution, with the output ending up like this (read
it bottom up):
398.15ms compile_module
398.19ms compile_module_cached_wasmer_impl
140.19µs run_wasmer/call
407.21ms run_wasmer
The output's format can certainly be improved, but the beauty of
`tracing` is that it can be done separately from instrumentation.
`tracing` is a bit over-engineered to my personal taste, but other than
that it is a well-maintained crate with a large ecosystem buy-in, and is
a solid bet.
The following …
=> feat: add `tracing` infrastructure to contract runtime

chain/chain/src/test_utils.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs, chain/client/tests/cross_shard_tx.rs
There were several issues, of which one is an actual bug.
The bug was my regression in the latest rewrite of the block sync: if
the current head is not on the canonical header chain, the block sync
would continuously try to fetch a block that build on top of the current
head, which is not what needs to be fetched. This is the main fix in
this change (changes in sync.rs)
The smaller issues fixed:
a) With the recent changes the node became faster, and 80ms was no longer
adequate for the acceptable forkfulness. Changed to 70ms. With 70 the
forkfulness sometimes was below 2.4, but reducing the timeout below 70
was sometimes resulting in nodes not being able to keep up, so I had to
decrease the min forkfulness to 2.3.
b) There was a bug that was querying the balance at the very start of
the …
=> fix: Fixing an error in cross_shard_tx

Cargo.toml, core/primitives-core/src/profile.rs, core/primitives/Cargo.toml, core/primitives/src/runtime/apply_state.rs, neard/Cargo.toml, neard/src/runtime.rs, runtime/near-evm-runner/Cargo.toml, runtime/near-evm-runner/src/runner.rs, runtime/near-vm-logic/src/gas_counter.rs, runtime/near-vm-logic/src/logic.rs, runtime/near-vm-logic/tests/vm_logic_builder.rs, runtime/near-vm-runner-standalone/src/main.rs, runtime/near-vm-runner/Cargo.toml, runtime/near-vm-runner/benches/bench.rs, runtime/near-vm-runner/src/runner.rs, runtime/near-vm-runner/src/wasmer1_runner.rs, runtime/near-vm-runner/src/wasmer_runner.rs, runtime/near-vm-runner/src/wasmtime_runner.rs, runtime/runtime-params-estimator/Cargo.toml, runtime/runtime-params-estimator/src/testbed.rs, runtime/runtime-params-estimator/src/vm_estimator.rs, runtime/runtime/Cargo.toml, runtime/runtime/src/actions.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer.rs, runtime/runtime/tests/runtime_group_tools/mod.rs, test-utils/testlib/Cargo.toml, test-utils/testlib/src/user/runtime_user.rs
The goal here is to make sure that only the leaf crates (primitives-core
and vm-logic) and the topmost crate (params-estimator) know about this
feature.
Before this PR, every intermediary crate would have to know about this
feature as well.
To fix this, we encapsulate all conditional compilation logic inside
ProfileData type, while making sure it compiles to no-op unless the
feature is enabled.
=> refactor: significantly reduce costs_conting blast radius

runtime/near-vm-errors/src/lib.rs, runtime/near-vm-runner-standalone/src/main.rs, runtime/near-vm-runner/benches/bench.rs, runtime/near-vm-runner/src/runner.rs, runtime/near-vm-runner/src/wasmer1_runner.rs, runtime/near-vm-runner/src/wasmer_runner.rs, runtime/near-vm-runner/src/wasmtime_runner.rs, runtime/near-vm-runner/tests/test_error_cases.rs, runtime/near-vm-runner/tests/test_invalid_contracts.rs, runtime/near-vm-runner/tests/test_rs_contract.rs, runtime/near-vm-runner/tests/test_ts_contract.rs, runtime/near-vm-runner/tests/test_utils/mod.rs, runtime/runtime-params-estimator/src/vm_estimator.rs, runtime/runtime/src/actions.rs
runtime actually stores method name as `String`, so we have a static
proof that utf8 validation already happened.
Wasm import/export tables are specked to use utf8, so we don't need to
worry about supporting non-utf8 even in theory.
=> refactor: typify MethodUTF8Error out of existence

CODEOWNERS
While @EgorKulikov and @Longarithm are onboarding we need to find a way to speed up PR review process for the runtime. I am adding @bowenwang1996 to review only the runtime changes that are not affecting the protocol or fundamental design of the runtime, which are mostly refactoring changes. All other changes will still need to be approved by @evgenykuzyakov . 
CC @matklad
=> Add Bowen to the runtime codeowners

Cargo.lock, chain/network/Cargo.toml, chain/network/src/codec.rs
As @matklad pointed, there is no point in importing both `size` and `bytesize` packages.
=> replace size package with bytesize

runtime/near-vm-runner/src/wasmer1_runner.rs
My understanding is that we'll be using `wasmer1`  going forward, so it makes sense to add those tracing calls!
=> refactor: improve visibility into wasmer1 performance

neard/src/main.rs, runtime/near-vm-runner/src/runner.rs, test-utils/logger/src/lib.rs
Tracing spans are a pairs of start/stop events, and can be used to
monitor how well the code is performing in production and, if it is
slow, which specific part is slow. To get this magic power, we need two
things:
* actually use `span!` macros from tracing (we already do in contract
runtime, this PR adds one more span right at the entry point, now that
we have a single entry point)
* ask tracing to please print this valuable info, as it is disabled by
default.
=> feat: enable "how long did this thing run?" logging

runtime/near-vm-runner/src/lib.rs, runtime/near-vm-runner/src/runner.rs, runtime/near-vm-runner/src/tests.rs, runtime/near-vm-runner/src/tests/error_cases.rs, runtime/near-vm-runner/src/tests/invalid_contracts.rs, runtime/near-vm-runner/src/tests/rs_contract.rs, runtime/near-vm-runner/src/tests/ts_contract.rs
By moving from many integration integration test crates to a single (nested) unit-tests module, we:
* improve test compilation performance by cutting down on linking time
significantly
* improve test run-time by increasing parallelism (20s -> 12s, when
`test_out_of_memory` outlier is removed)
* improve organization by making more things private and making it
easier to share code between various tests.
See this post for an in-depth explanation:
https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html
When adding a new integration test file, consider an option of putting
it into `src` dir instead.
=> refactor: improve test compilation speed and organization

Cargo.lock, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner-standalone/src/main.rs, runtime/near-vm-runner-standalone/src/script.rs, runtime/near-vm-runner/src/cache.rs, runtime/near-vm-runner/src/lib.rs, runtime/near-vm-runner/src/tests.rs, runtime/near-vm-runner/src/tests/error_cases.rs
We now can run several contracts in a row which allows us to, eg,
observe caching effects:
374.26ms compile_module
374.29ms compile_module_cached_wasmer_impl
123.06µs run_wasmer/call
383.05ms run_wasmer
52.46µs run_wasmer/call
8.45ms run_wasmer
57.97µs run_wasmer/call
8.47ms run_wasmer
128.15µs run_wasmer/call
8.59ms run_wasmer
This includes #3974 just to get nice numbers, but can be landed separately. 
At the moment, the `Script` has only programmatic interface -- the best way to create your custom test scenario is to write a `#[test]`. We *can* add some kind of interpreter here, so that the script can be read as text, but I feel that just using Rust would be more productive.
=> feat: allow more sophisticated vm benchmarks 

runtime/near-vm-runner-standalone/src/script.rs, runtime/near-vm-runner/src/lib.rs, runtime/near-vm-runner/src/runner.rs, runtime/near-vm-runner/src/tests.rs, runtime/near-vm-runner/src/tests/rs_contract.rs, runtime/near-vm-runner/src/tests/ts_contract.rs
After a series of previous refactors, we can finally consolidate all
entry points. We still need two functions: `run` is a public API, and it
picks the appropriate VM automatically. `run_vm` is an internal API
which allows us to check that all supported VMs work.
=> refactor: reduce code duplication

runtime/near-vm-runner/src/cache.rs, runtime/near-vm-runner/src/wasmer_runner.rs
As that's where we spend the bulk of our time
=> feat: time wasmer deserialization costs

pytest/tests/sanity/staking2.py
60 second state sync timeout is too high for tests with short epochs.
Set it to two seconds, and increase epoch length from 12 to 18.
Fixes #4037
Test plan
---------
staking2.py
before: 19/30 failures in last 30 nightly
state_sync_timeout: 2/60 fail
state_sync_timeout + increase epoch length: 60/60 pass
=> fix(test): staking2.py false failures

pytest/tests/sanity/transactions.py
In merged PR #3944 I've dropped routing for the `Query` handler in ViewClient (@frol and @bowenwang1996 discussed it and approved this change).
After that test `pytest/tests/sanity/transactions.py` started failing. @frol and I investigated it and found out that the fails related to the attempts to test transactions between shards, all the test relies on the querying jsonrpc `query` method to get accounts from different shards and check their balances, but since routing is not present there anymore it's impossible to do it.
In this PR I've made the smallest change introducing only one shard and all the accounts on that shard so the test is not failing anymore, but I'm not sure if it not brakes the main idea of the test.
@bowenwang1996 @SkidanovAlex could you assist in refactoring this test …
=> refactor(pytest): Update sanity/transactions.py test to pass according to dropped routing in handle_query ViewClient method

pytest/tests/sanity/transactions.py
Use get_epoch_block_approvers_ordered instead of get_epoch_block_producers_ordered.
Make some changes to the test: query the observer node, disable storage
checking and set a low state sync timeout.
Fixes #4133
Test plan
---------
nayduck
=> fix(test): transactions.py with nightly_protocol

Cargo.lock, chain/network/Cargo.toml, chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/src/types.rs
Reverts near/nearcore#4111
Reverting change, that could break exchange of routing tables.
In 4111, we switches, how we add edges to PeerManager. We will now send only some edges to PeerManager in one request, not the whole graph. 
Inside `try_save_edges`, we run code, which tries to prune edges that are unreachable. We may remove some valid edges, because we didn't get full graph yet.
@bowenwang1996
=> Revert "Validate each edge only once"

core/primitives-core/src/profile.rs
The simulator was failing due to default calling `new_disabled` and then debug crashed when dividing by zero. Now debug prints a helpful statement when `costs_counting` is not enabled.
=> fix(primitives-core): ProfileData default uses feature and add tests

runtime/near-vm-runner/src/cache.rs, runtime/near-vm-runner/src/wasmer1_runner.rs, runtime/near-vm-runner/src/wasmer_runner.rs
- add a couple of spans that turned out to be potentially significant
during #4030 investigation, notably dropping of the instance
- refactor code to make sure that preloading code path also has the same
spans.
See [1] for how to read the timing info from spans
[1]: https://github.com/near/nearcore/tree/ad3de8f3a597b6cc5c01871a4709973828de3b9f/runtime/near-vm-runner#profiling
=> feature: more runtime performance visibility into runtime

core/primitives/src/network.rs
We've been running Borsh Serializer every time we compute cache for PeerId.
=> Optimize hash function for PeerId

runtime/near-vm-runner/src/preload.rs, runtime/near-vm-runner/src/tests/contract_preload.rs, runtime/near-vm-runner/src/wasmer1_runner.rs, runtime/near-vm-runner/src/wasmer_runner.rs
feat: infrastructure for reusing memory and store between contracts
To prepare for optimized pipelined execution of contracts we need to be able to share reusable parts of state.
This is a preparation PR allowing to share certain parts of the VM state between runs. By default, memory state is turned 
off, as we need to ensure that no memory data of one contract execution can be seen in another execution.
Once https://github.com/near/nearcore/pull/4128 will be merged, we could test performance impact of different
sharing practises.
Test plan
---------
cargo test
more specifically tests::contract_preload::test_run_preloaded which tests the behavior of the preloader.
=> feat: infrastructure for reusing memory and store between contracts

Cargo.lock, chain/network/Cargo.toml, chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/src/types.rs, chain/network/tests/cache_edges.rs
This is a corrected version of #4145 which I reverted.
I added a check, to make sure we don't prune edges while they are requests to edge versifier in progress.
=> Verify edges only once in a correct way

neard/src/lib.rs
We want to know when given thread reaches peak memory usage. However, the main thread reaches peak memory usage while loading config, then it frees memory. We will reset peak memory usage after `start_with_config`, so we can see report when the main thread reaches peak memory usage.
=> Reset max memory usage after loading config

core/primitives-core/src/profile.rs
As per @matklad suggested that default shouldn't be dependent on feature flag.
=> fix(primitives-core): make default profile disabled

runtime/near-vm-runner/src/cache.rs
Unentered spans count towrads "idle" measure, which is not what we want. We want "busy", and for that the span must be entered.
=> fix: count vm_runner cache operation as busy, not as idle

Dockerfile, Dockerfile.nightly
Docker release was broken due to deletion of the stable.rust-toolchain file in: https://github.com/near/nearcore/commit/08653bad65f4a137190514249e8f4ef6d132556c
=> Fix the broken docker release due to stable toolchain change

runtime/near-test-contracts/test-contract-rs/src/lib.rs
LLVM is able to compute closed form for polynomial sums like
let mut sum = 0i
for i in 0..n {
sum += a_0 + a_1*i + a_2*i*i ... + a_k*i^k;
}
https://godbolt.org/z/4Wx7G8vEx
=> fix: prevent LLVM from optimizing the benchmark to O(1) computation

core/primitives-core/src/config.rs, runtime/near-vm-runner/src/tests/rs_contract.rs
Before this PR, we store costs for `alt_bn128_g1` and costs of certain actions in the same array index, becaues, when adding alt_bn128_g1, we forgot to update the number of costs. The fix is to make this mistake impossible, by including an explicit sentinel node at the end.
Test plan
---------
Add sanity check to existing ext tests that they don't increase action costs.
=> fix: don't misinterprent alt_bn128_g1 costs as action costs

pytest/tests/sanity/skip_epoch.py, pytest/tests/sanity/state_sync.py
Fix python tests failure caused by rpc routing removal and wrong state sync timeout configuration.
Test plan
---------
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1464
=> fix some python tests

chain/jsonrpc/client/src/lib.rs, neard/tests/rpc_nodes.rs
I've refactored transaction related methods on JSON-RPC in this PR #4180
Here I've added tests to check that error messages are the same, so we can ensure that refactor is backward compatible. We need to merge this PR before #4180
=> test(jsonrpc): Cover JSON-RPC transaction related methods with tests for error messages (to watch for backward compatibility after refactor)

chain/client/tests/process_blocks.rs
Fixing tests produce_block_with_approvals_arrived_early and test_ban_peer_for_ill_formed_block.
Both tests fail if the block at height 4 is skipped.
=> Fix flaky tests in process_blocks Resolves #4042

neard/src/runtime/mod.rs
Test Plan
------------
Pure refactoring, *should* be covered by existing tests. I am not entirely sure if this semi-debug infra is exercised during CI, but the change seems to be mechanical enough to probably be correct anyways.
=> refactor: use std::fs convenience functions

neard/src/main.rs
Currently we just check if there is a protocol change in based on the binary neard version, we need to also add a hard-fork on betanet if there is a DB version change, so I added it the the version command.
=> feat(version): include the DB version the neard version command

pytest/tests/sanity/lightclnt.py
The interface has changed, and the missing light client block now
returns {}, not None, adjusting the test
Also, removing checking storage, it makes the test slow, but the test heavily relies on block being produced slower than the checks we run.
Test plan
--------
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1563
=> fix: Fixing lightclnt.py

pytest/tests/sanity/backward_compatible.py
Backward compatible test is broken because it runs a stable node whose version depends on the latest rc release. After the most recent release, the nonce restriction takes effect which breaks the test.
Test plan
---------
CI
=> fix(test): fix backward compatible test

chain/client/src/view_client.rs, neard/tests/rpc_nodes.rs
I've noticed that if I request `validators` method and pass `epoch_id` in params I'm getting `Unknown Epoch` if epoch I request is current one.
I thinks it has to work so this fix makes it possible.
The cause was in the epoch manager. If we request validators with epoch id we try to use `EpochSummary` which deals with "cached" epochs. But we request ongoing epoch which is not cached yet. So on the `view_client` I compare current epoch id with requested one and in case of match I act like it was a request for latest to trigger `EpochInfoAggregator` instead of `EpochSummary`
=> fix(jsonrpc): Validators by epoch_id current epoch is not returning Unknown Epoch anymore

runtime/near-vm-logic/Cargo.toml, runtime/near-vm-runner/Cargo.toml, runtime/runtime-params-estimator/Cargo.toml, runtime/runtime/Cargo.toml
We use this feature in ./runtime/near-vm-runner/src/vm_kind.rs.
So, it should be declared in `vm_runner` Cargo.toml rather than in
`vm_logic`.
This is #4279 submitted against master. 
Not sure how to make sure that similar errors don't happen in the future. The culprit here is that you can have `cfg(feature = "some-typo")`, and you won't see any warnings about this anywhere...
=> fix: wasmer1_default feature actually selects wasmer1

core/primitives-core/Cargo.toml, core/primitives-core/src/profile.rs, runtime/near-vm-logic/Cargo.toml, runtime/near-vm-logic/src/gas_counter.rs, runtime/near-vm-runner-standalone/src/main.rs, runtime/near-vm-runner-standalone/src/script.rs, runtime/near-vm-runner/src/tests.rs, runtime/near-vm-runner/src/tests/contract_preload.rs, runtime/near-vm-runner/src/tests/rs_contract.rs, runtime/near-vm-runner/src/tests/ts_contract.rs, runtime/runtime/src/lib.rs
Having costs breakdown (how much gas was spend for each operation type)
is helpful for both increasing reliability (as we can eyeball if the
costs "make sense") and developer friendliness (as devs can understand
where all the gas is going).
Currently this is hidden behind a feature flag, but I would love to
argue that we should just always enable it.
Performance cost seems to be negligible: we heap-allocate an array once
per apply state, and actual cost increasse are just counter increments,
they should be dwarfed by the host functions themselves.
Correctness-wise, the code is semi-sensitive. It is executed by runtime,
but doesn't affect the results. So it's enough if it doesn't panic.
All of existing tests now exercise costs councting code. An additional unit-test is added to smoke-test …
=> Profile by default

Cargo.lock, Cargo.toml, runtime/near-vm-runner/Cargo.toml
Wasmer 1 uses rayon for parallel execution, which we don't want to use.
We've upstreammed the patch making rayon support optional, but it is not
yet released. So let's use our fork at the moment, which patches the
existing 1.0.2 release we use.
=> fix: disable threading on wasmer 1

runtime/near-vm-runner/src/cache.rs
This PR ports wasmer0 implementation of in-memory cache to wasme1 as
well.
The goal here is to keep the behavior between two wasmers as close as
possible. We absolutely do want to get rid of the in-memory cache, but
it's safer not to do that while also doing a major wasmer upgrade!
See https://github.com/near/nearcore/issues/4076#issuecomment-839762577
for context
Test Plan
----------- 
```
$ cargo test -p near-vm-runner --features wasmer0_vm,wasmer1_vm,no_cache
$ $ cargo test -p near-vm-runner --features wasmer0_vm,wasmer1_vm
```
=> feat: enable in-memory cache for wasmer1

chain/client/tests/process_blocks.rs, runtime/runtime/src/lib.rs
Prevent non-mainnet chains from crashing during protocol upgrade to `RestoreReceiptsAfterFix`: https://github.com/near/nearcore/issues/4321
- Remove unnecessary assertion because it's already checked in `test_restored_receipts_data`
- Test protocol upgrade on testnet in `protocol_feature_restore_receipts_after_fix_tests::test_run_for_testnet`
=> Fix protocol upgrade for non-mainnet chains

chain/client/tests/consensus.rs
Fix `test_consensus_with_epoch_switches by increasing timeout.
Test plan
---------
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1622
=> fix: test_consensus_with_epoch_switches

runtime/near-vm-runner/src/tests/error_cases.rs, runtime/near-vm-runner/src/wasmer_runner.rs, runtime/near-vm-runner/src/wasmtime_runner.rs
Certain contracts could trigger internal error is WASM engines and so
conversion panic on those.
=> fix: better error processing in some corner cases

runtime/near-test-contracts/build.rs
See #4331
Test Plan
---------
This affects only build code for our tests, so just usual release pipeline is enough. 
Note that we currently do build test code into the released binary, this will be dealt with separately.
=> fix: prevent build-time deadlock when building tests in release mode

Dockerfile, Dockerfile.nightly, Makefile
builds to fail:
https://buildkite.com/nearprotocol/nearcore-release/builds/601
Created a build to verify if it works as a quick fix to unblock master failing: https://buildkite.com/nearprotocol/nearcore-release/builds/607
As well remove the mount=type=cache as they get removed eitherways every time once we destroy the container, so there aren't useful at all here.
=> fix broken release due to wrong rust version and resolver conflit, remove the dockerfile caching as it is not used anyway.

chain/network/src/peer.rs
Do not log the entirety of invalid data received on network
Test Plan:
The code compiles
=> fix: use pretty_vec to print invalid data

.buildkite/pipeline.yml
Attempt to solve https://github.com/near/nearcore/issues/4367
Check both stable and nightly `cargo build -p neard`
Checked that it covers previous commit:
```
$ git checkout 377908d18e0d4ed46eab2f0cdabf3f9a648179e3
$ cargo check -p neard --features nightly_protocol,nightly_protocol_features
error: failed to select a version for `near-client`.
... required by package `nearcore v1.2.0 (/home/Aleksandr1/nearcore/nearcore)`
... which is depended on by `neard v1.2.0 (/home/Aleksandr1/nearcore/neard)`
versions that meet the requirements `=0.1.0` are: 0.1.0
the package `nearcore` depends on `near-client`, with features: `nearcore` but `near-client` does not have these features.
```
=> Cover cargo build failures in buildkite/nearcore

chain/client/src/client_actor.rs, core/chain-configs/src/client_config.rs, core/primitives/src/views.rs, nearcore/Cargo.toml, nearcore/src/config.rs, nearcore/src/lib.rs, neard/Cargo.toml, neard/src/cli.rs, test-utils/testlib/src/lib.rs, test-utils/testlib/src/node/process_node.rs, test-utils/testlib/src/node/thread_node.rs, test-utils/testlib/src/run_nodes.rs
1. Add `--disable-rpc` command line switch to `neard run` subcommand.
2. Add `json_rpc` build feature which can be disabled to completely remove RPC endpoint support from the binary.
=> Support disabling RPC endpoint at runtime as well as compile time

test-utils/testlib/src/run_nodes.rs
The change fixes the following compiler warning:
warning: trait objects without an explicit `dyn` are deprecated
--> test-utils/testlib/src/run_nodes.rs:38:53
|
38 |     let nodes: Vec<_> = nodes.into_iter().map(|cfg| Node::new_sharable(cfg)).collect();
|                                                     ^^^^ help: use `dyn`: `<dyn Node>`
|
= note: `#[warn(bare_trait_objects)]` on by default
=> Fix ‘bare_trait_objects’ warning

Cargo.lock, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/jsonrpc/Cargo.toml, chain/jsonrpc/client/Cargo.toml, chain/rosetta-rpc/Cargo.toml, chain/telemetry/Cargo.toml, core/primitives/src/transaction.rs, core/primitives/src/version.rs, core/primitives/src/views.rs, core/store/src/migrations.rs, nearcore/src/lib.rs, runtime/runtime/src/lib.rs
This PR does not introduce any functional change. It adds a metadata field to ExecutionOutcome which is versioned. Add a V1 ExecutionMetadata with is empty. Next PR will add a V2 ExecutionMetadata which add ProfileData into ExecutionOutcome. Add migrations to change exisiting outcome in storage to new format
Test Plan
------------
CI
=> feat(primitive): prepare for adding profile data to execution outcome

core/store/src/trie/mod.rs, core/store/src/trie/shard_tries.rs, core/store/src/trie/state_parts.rs
One step to solve https://github.com/near/NEPs/issues/217
It took a while to understand what exactly `(CryptoHash, Vec<u8>, u32)` stores, so I make a struct which self-describes it.
=> Introduce `TrieRefcountChange` for better readability

runtime/publish.sh
The `--dry-run` flag will allow to run `runtime/publish.sh` script to
test whether all the crates are in a state where they can be published.
Note that at the moment, this check fails due to problems described in
the GitHub Issue.
Issue: https://github.com/near/nearcore/issues/4379
=> Add `--dry-run` option to `runtime/publish.sh` script

Cargo.lock, runtime/near-vm-runner/Cargo.toml
See https://github.com/near/wasmer/commit/aa573888b8ca6832498b4ed16de1486d8037f5ab for the actual fix in wasmer. It is published as https://crates.io/crates/wasmer-runtime-core-near/0.17.3. 
Testing for memory leaks is a bit hard, as we don't already use asan. So I just verified manually that the node leaks without this patch and dosen't leak with this patch. Old test help to make sure that, functionally, the node behaves the same.
=> fix: upgrade wasmer 0.17 to fix memory leak

chain/client/src/client.rs, chain/client/tests/challenges.rs, chain/client/tests/process_blocks.rs, chain/client/tests/sandbox.rs, chain/indexer/src/lib.rs, core/chain-configs/src/client_config.rs, genesis-tools/genesis-populate/src/lib.rs, nearcore/src/config.rs, nearcore/src/lib.rs, nearcore/src/migrations.rs, nearcore/src/runtime/mod.rs, nearcore/tests/economics.rs, neard/src/cli.rs, nightly/tests_for_nayduck.txt, pytest/lib/cluster.py, pytest/tests/sanity/rpc_max_gas_burnt.py, runtime/near-test-contracts/test-contract-rs/src/lib.rs, runtime/runtime/src/state_viewer/mod.rs, test-utils/state-viewer/src/main.rs, test-utils/state-viewer/src/state_dump.rs, test-utils/store-validator/src/main.rs, test-utils/testlib/src/lib.rs, test-utils/testlib/src/runtime_utils.rs, test-utils/testlib/src/user/runtime_user.rs, tools/indexer/example/src/configs.rs, tools/restored-receipts-verifier/src/main.rs
The ‘max_gas_burnt_view’ affects the RPCs only and therefore doesn’t
need to be part of the consensus.  In other words, all nodes could
have this value customised rather than using an agreed upon value
from genesis configuration.
Introduce a ‘max_gas_burnt_view’ field to ClientConfig and
a corresponding flag to ‘init’ and ‘run’ subcommands.  When present,
it will override the limit used by the node ignoring whatever is
stored in genesis configuration.
Fixes: https://github.com/near/nearcore/issues/3080
=> Introduce ‘max_gas_burnt_view’ client config and command line flag

pytest/empty-contract-rs/src/lib.rs
The near-sdk crate has been updated¹ to define global allocator by
default.  It no longer re-exports `wee_alloc` and there is no longer
a need for contracts to set is as the allocator manually.
This fixes the following tests/contracts/deploy_call_smart_contract.py
failure:
error[E0433]: failed to resolve: could not find `wee_alloc` in `near_sdk`
--> src/lib.rs:5:25
|
5 | static ALLOC: near_sdk::wee_alloc::WeeAlloc = near_sdk::wee_alloc::WeeAlloc::INIT;
|                         ^^^^^^^^^ could not find `wee_alloc` in `near_sdk`
¹ https://github.com/near/near-sdk-rs/commit/f69d375fff99f355c4c9b94fb5bd659750b3e31a
Issue: https://github.com/near/nearcore/issues/4432
=> pytest: fix compilation of test contracts after SDK update

.github/stale.yml
Change days until stale to be longer (sorry for the opposite suggestion earlier). Also @chefsale my experience so far is that it seems that we don't actually need the bot to automatically close the issue. What we want is for the bot to ping when an issue becomes stale so that we can do some manual triage. Is it possible to configure the bot that way?
=> chore: modify stale bot configuration

Cargo.lock, neard/Cargo.toml, neard/src/cli.rs
The ‘kill’ command sends SIGTERM signal by default.  Catch it in
addition ta SIGINT when running under Unix-like system.
Issue: https://github.com/near/nearcore/issues/3266
=> cli: unix: catch SIGTERM in addition to SIGINT and terminate gracefully

Cargo.lock, runtime/runtime/Cargo.toml, runtime/runtime/src/lib.rs
tracing::span records how long it took to run a block of code and prints
this into into log.
See
https://github.com/near/nearcore/blob/ff01c544ce2675fadbf0284af52b356a383b27a8/docs/architecture.md#runtimenear-vm-runner
for the info on the tracing infra
Test Plan
----------
Only active with debug logging level enabled, doesn't need additional testing.
=> feat: improve visibility for runtime performance

Cargo.lock, runtime/runtime-params-estimator/Cargo.toml, runtime/runtime-params-estimator/src/vm_estimator.rs
Forgot to do this in #4293: the original motivation here was to force
wasmer1 to compile code in a single thread,  but we've since contributed
a "no rayon" mode upstream and upgraded to that.
In other words, wasmer1 no longer uses threads, so we don't need this.
=> refactor: remove needless rayon pool setup in the estimator

pytest/lib/mocknet.py, pytest/tests/mocknet/load_testing.py, pytest/tests/mocknet/outage.py
The logger is cofigured to include message level so there’s no need to
include INFO in the actual message.  AS it stands, this results in log
lines such as:
[2021-07-09 05:37:33] INFO: INFO: Starting Load test.
Remove the unnecessary ‘INFO’ prefix.  This has been done with a simple:
sed -i 's/INFO: //' pytest/**/*.py
=> Remove unneccesarry ‘INFO’ prefix from log messages

pytest/empty-contract-rs/Cargo.toml, pytest/empty-contract-rs/build.sh, pytest/empty-contract-rs/src/lib.rs, pytest/lib/utils.py, pytest/tests/mocknet/load_testing.py
There’s very little reason to make the empty-contract-rs depend on
near-sdk.  The code is trivial and only uses the log method which
can be easily called directly without the near-sdk wrapper.
This also fixes the issue where the test was not reproducible as the
empty-contract-rs would depend on the near-sdk from the git
repository rather than a released crate.
An obvious question which arises is why not use near-test-contracts
like the rest of pytests.  That would be an ideal endgoal but it
doesn’t interact well with how NayDuck runs mocknet tests.
Specifically, near-test-contracts needs to be built and NayDuck
currently skips build stage when running mocknet tests.  Long term
this could be addressed but for now this change improves the
situation so it’s what we’ve got.
Issue: …
=> pytest: don’t depend on near-sdk in empty-contract-rs

pytest/tests/contracts/deploy_call_smart_contract.py
The deploy_call_smart_contract test has two parts.  First, it deployes
the test contract from near-test-contracts and calls its function.
Second, it builds a new contract, deployes that and calls its function.
The second part however doesn’t really test anything additional compared
to the first.  The only difference is building of the contract but
that’s really beyond scope of nearcore tests.  Furthermore, because the
compiled contract depends on near-sdk repository the test is
non-reproducible.
Remove the second part and only test deploying and calling a single
smart contraact.
Issue: https://github.com/near/nearcore/issues/4480
=> pytest: remove contract building from deploy_call_smart_contract test

Cargo.lock, core/primitives/Cargo.toml, core/primitives/src/runtime/config.rs, nearcore/src/runtime/mod.rs
Protocol version changes may affect the runtime configuration.  To
handle this, the runtime uses a RuntimeConfig::from_protocol_version
method which returns the configuration adjusted for given version.
(Currently storage_amount_per_byte can be lowered by this mechanism).
However, it would be rather wasteful to construct a new adjusted
config object each time so the RuntimeConfig::from_protocol_version
method caches the result so that when it’s called next time for the
same (or newer) version it can return the config immediately.
The issue is, the cache has the form of a global singleton object
which is initialised once and never changed.  This means that calling
from_protocol_version on different config objects will return wrong
adjusted configs.
To fix the issue, introduce …
=> primitives: remove `LOWER_STORAGE_COST_CONFIG` global

pytest/requirements.txt
I suggest to add `cython` because building venv for pytest from scratch always ends up with
```
Running setup.py install for scikit-learn ... error
ERROR: Command errored out with exit status 1:
command: /home/Aleksandr1/nearcore/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cak7r1gr/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cak7r1gr/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z15d8knj/install-record.txt --single-version-externally-managed --compile --install-headers /home/Aleksandr1/nearcore/venv/include/site/python3.8/scikit-learn
cwd: …
```
=> Add cython to pytest requirements

pytest/lib/utils.py
Kinda hacky, but use atexit to cleanup any wasm blobs created by the
compile_rust_contract helper function.
Issue: https://github.com/near/nearcore/issues/4480
=> pytest: cleanup blobs created by compile_rust_contract

runtime/runtime-params-estimator/src/cases.rs
According to `least_squares_method` formulas, `a` stands for constant and `b` stands for multiplier. Other usages of `compute_compile_cost_vm` have correct order.
=> Fix order of regression constants

Makefile, codecov.yml
@Longarithm has asked me if we can build the binaries for `param-estimator` and `genesis-populate` in the current pipeline as currently he is using a Docker image which recompiles them every time and this would save him time.
=> feat(build): Added param-estimator and genesis-populate to the Makefile for nightly and stable releases to store artifacts

integration-tests/tests/tidy.rs
This test used to be run from the root of the repo, but got moved to a
subdir. After that, it stopped checking everything, so let's restore the
old, correct behavior.
closes #4505
Test Plan
--------
Manually check that invalid formatting is detected.
=> fix: tidy test checks everything, and not only one dir

test-utils/state-viewer/Cargo.toml, test-utils/state-viewer/src/state_dump.rs
Tested by running a `betanet` node with `nightly_protocol` and `nightly_protocol_features`.
Fixes #4207
=> Use protocol version of the latest block instead of protocol version of the genesis block when dumping state

nightly/nayduck.py
NayDuck scheduler and backend now live in a single process and
listen on the same port.  The old address for the scheduler will
eventually became unavailable.
Isuse: https://github.com/near/nayduck/issues/6
=> nayduck: update scheduler address in the ‘Requset a run’ script

Makefile
Introduce a default ‘all’ target to the Makefile so that running
‘make’ on its own produces a relaese build which is likely what
user meant.
Issue: https://github.com/near/nearcore/issues/4403
=> Makefile: add a default ‘all’ target

nightly/complete_nayduck_set.txt, nightly/nightly.txt, nightly/tests_for_nayduck.txt, pytest/tests/sandbox/patch_state.py
Make sure that NayDuck builds neard binary with --features sandbox when
running sandbox tests and also make the sandbox test a bit smarter about
locating the executable.
=> pytest: fix sandbox test

nightly/nightly.txt
NayDuck is unaware of a ‘basic’ test category and each time it has
been executed it has failed†.  Remove it from the list of NayDuck
nightly tests
† http://nayduck.eastus.cloudapp.azure.com:3000/#/test_history/67137
=> nayduck: remove ‘basic’ test since it’s not a thing

chain/chain/src/test_utils.rs, chain/network/src/routing.rs, chain/network/src/types.rs, core/primitives/src/block.rs, core/primitives/src/challenge.rs, core/primitives/src/epoch_manager.rs, core/primitives/src/receipt.rs, core/primitives/src/sharding.rs, core/primitives/src/sharding/shard_chunk_header_inner.rs, core/primitives/src/syncing.rs, core/primitives/src/transaction.rs, core/primitives/src/types.rs
Serialize is a big promise, so better not to make it if we don't have
to.
Additionally, structs which are both `derive(Serialize, BorshSerialize)`
are suuuper suspicious and a code smell. bors and JSON (what we use
Serialize for) have very different format compatibility guarantees,
keeping a type backwards compatible with both formats at the same time
is tough.
Historical context: this was added in #1928, but we don't use it anymore.
=> refactor: drop unneeded `derive(Serialize)`

runtime/runtime-params-estimator/emu-cost/README.md
Small fix to remove the unused `protocol_feature_evm` from the README.md or `emu-cost`. In genesis populate, it doesn't even exist.
=> Remove `protocol_feature_evm` mention from emu-cost/README.md

chain/epoch_manager/src/proposals.rs, chain/epoch_manager/src/test_utils.rs, core/chain-configs/src/genesis_config.rs, core/primitives/src/epoch_manager.rs, nearcore/src/shard_tracker.rs
num_shards is managed in multiple places in the codebase, I'm trying to consolidate it a bit before I change num shards to be dynamic. num_shards in EpochConfig does not seem to be used at all, so I'm removing it.
=> remove num_shards from EpochConfig since it is not used

Cargo.lock, runtime/near-vm-runner-standalone/Cargo.toml, runtime/near-vm-runner-standalone/src/main.rs, runtime/runtime-params-estimator/Cargo.toml, runtime/runtime-params-estimator/src/main.rs
We'll want to tweak param estimator CLI shortly, and it's easier to do that with declarative clap3. Note that we already use calp3 for the main `neard` binary, so this change also increases overall consistency of the code base.
Test Plan
-------
Smoke-tested manually using examples from readme.
=> refactor: use clap3 in parameter estimator & standalone runner

pytest/lib/utils.py, pytest/tests/sanity/backward_compatible.py, pytest/tests/sanity/db_migration.py, pytest/tests/sanity/state_migration.py, pytest/tests/sanity/upgradable.py, pytest/tests/stress/hundred_nodes/collect_logs.py, pytest/tests/stress/hundred_nodes/create_prometheus_targets.py, pytest/tests/stress/hundred_nodes/node_rotation.py, pytest/tests/stress/hundred_nodes/start_100_nodes.py, scripts/state/update_res.py
Respect TMPDIR, TEMP and TMP environment variables when creating
a temporary /tmp/near directory.  This helps clean up any artefacts
remaining after a test.
There are other places where the scripts hardcode /tmp as the temporary
directory but for now those are left alone just to keep this change
smaller.
Issue: https://github.com/near/nayduck/issues/9
=> pytest: respect $TEMP variable when creating /tmp/near directory

Cargo.lock, nearcore/Cargo.toml, neard/Cargo.toml, neard/src/main.rs
Currently our master version is 1.2.0 and we do not update it due to using a trunk based release process.
I have looked into some options and the most sensible is this (https://softwareengineering.stackexchange.com/questions/333680/how-to-version-when-using-trunk-based-development).
Use 0.0.0 for master so it doesn't create confusion as we already include the build commit in the versioning.
Before:
```
sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/nearcore (use-trunk) [2]> ./target/release/neard --version
neard 1.2.0 (build 12fd620c) (protocol 46) (db 26)
```
Now:
```
sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/nearcore (use-trunk)> ./target/release/neard --version
neard (version trunk) (build 5ba32a5f-modified) (protocol 46) (db 26)
```
=> cleanup(version): move master version to 0.0.0 instead of 1.2.0

.buildkite/pipeline.yml, nightly/complete_nayduck_set.txt
Add the scripts/check_pytest.py to the ‘sanity checks’ pre-commit
tests to make sure that all pytest tests are enabled in one of the
nightly/*.txt files.
Because at the moment there are nine files which do not meet that
criteria, add them to nightly/complete_nayduck_set.txt with a comment
documenting the state.
Issue: https://github.com/near/nearcore/issues/4552
Fixes: https://github.com/near/nearcore/issues/2736
=> pytest: add a pre-commit check testing if all pytests are enabled

chain/chain/src/chain.rs
The implementation of `get_block_proof` has the following issue that caused it to have O(n) complexity sometimes:
```
root
/ \ 
/     \ 
7       \
/    \       \
5       6    \
/ \    / \       \
0   1   2   3    4
```
In the above example, when we try to prove block 0, the current implementation, when trying to get the sibling of node 7, will do a useless traversal of a full binary tree with 4 leaves, whereas it does not need to recurse when it is known that the position is already outside of the number of leaves we have. More specifically, getting the left child (call to `get_merkle_tree_node`) should almost always be O(1) except when we are close to the right most leaf of the tree. For example
```
/ \ 
/     \
/ \      \       
...   8   9   10  
```
if we have 11 leaves in the above …
=> fix(rpc): fix the implementation of `get_block_proof` for light client

.buildkite/pipeline.yml
The approach of the pre-command hook doesn't work: https://github.com/near/nearcore/pull/4589#issuecomment-888492079
=> feat(build) Added set -eux to all steps of the CI pipeline

nightly/TODO-disabled-4552.txt, nightly/pytest-sanity.txt, nightly/pytest-stress.txt
saturate_routing_table test lives in stress directory not sanity directory.
Issue: https://github.com/near/nearcore/issues/4552
=> nightly: fix saturate_routing_table test description

integration-tests/tests/test_catchup.rs, integration-tests/tests/test_rejoin.rs, integration-tests/tests/test_simple.rs, integration-tests/tests/test_tps_regression.rs
Fix three instances of ‘trait objects without an explicit `dyn` are
deprecated’ warning and one instance of unused mut warning.
=> integration-tests: fix compiler warnings

pytest/lib/bridge.py
I’ve got seriously no idea what the assertion in git_clone_install was
supposed to check.  Tying the test to particular commit isn’t a good
idea in the first place.  Plus at the moment `eth2near/ethashproof`
isn’t even a submodule in rainbow bridge repository anyway.
Whatever the reason for the assert, it causes the tests to fail.
Removing it improves the situation (but letting the tests progress)
though it doesn’t fix it completely.
=> pytest: remove breaking assert in bridge pytests

pytest/tests/bridge/multiple_relays.py, pytest/tests/bridge/same_block.py
This fixes failures such as:
Traceback (most recent call last):
File "tests/bridge/multiple_relays.py", line 8, in <module>
from configured_logger import logger
ModuleNotFoundError: No module named 'configured_logger'
=> pytest: fix import of `configured_logger` in bridge tests

nightly/expensive.txt
The test name in the `expensive` nightly tests must match exactly
the path of the path otherwise it won’t match any known tests.
The `test_gc_after_state_sync` is in `process_blocks` module thus
it requires `process_blocks::test_gc_after_state_sync` to be used.
=> nightly: fix `test_gc_after_state_sync` test

core/primitives-core/src/config.rs
The numeric value of the cost stays exactly the same (3856371 is evenly
divisible by 3).
Looking at the recent measurements in
https://github.com/near/nearcore/pull/4455#issuecomment-874790365
it's clear that the measured cost is 3x lower.
Test Plan:
--------
Just visual inspection that the constant stays the same.
=> refactor: make it clear that regular_op_cost uses the multiplier

Cargo.lock, runtime/near-vm-runner/Cargo.toml
Before this fix, the following fails:
```
$ git diff Cargo.toml
diff --git a/Cargo.toml b/Cargo.toml
index 9b5e2c16..ab7f34f1 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -54,10 +54,11 @@ members = [
wasmer-compiler-singlepass = { git = "https://github.com/near/wasmer", branch = "1.0.2-single-threaded" }
[profile.release]
+codegen-units = 1
overflow-checks = true
[profile.bench]
-lto = true
+# lto = true
codegen-units = 1 # Use only 1 codegen-unit to enable full optimizations.
overflow-checks = true
$ cargo +nightly-2021-03-25 test --release --package near-vm-runner --lib \
-- tests::error_cases::test_guest_panic --exact
```
The is fix on wasmer side:
https://github.com/near/wasmer/commit/1ad551ac734d9f9e3823136b79291a6832aa4324
=> fix: update wasmer 0 to prevent miscompilation on a specific nightly rust version

pytest/lib/bridge.py
Swap if bodies in the `git_clone_install` they way thay should be.
Fixes: b24e7a44323bf36e01bb6ba6deba33bc624cae9f
=> pytest: bridge: fix `git_clone_install` method

scripts/nayduck.py
To reduce complexity of the authentication flow, NayDuck is switching
to a new process for requesting and managing authentication tokens.
This deprecates the old codes used when scheduling a NayDuck run.
Switch `nayduck.py` script to use the new tokens.
Issue: https://github.com/near/nayduck/issues/17
=> scripts: nayduck: switch to new authentication mode

nightly/expensive.txt
The `lib` tests are a bit of a lie.  They are really `expensive` tests
where package and binary name is the same.  `expensive` tests are
specified using
expensive <package> <binary> <test>
syntax while `lib` test use:
lib <package> <test>
syntax with the additional assumption that `<binary>` is the same as
`<package>`.  This means that in both cases expensive tests need to be
built and there’s no real difference between the two test categories.
At the moment NayDuck has a bug where it doesn’t treat the two test
categories the same way.  In particular, expensive tests are not built
when handling `lib` tests.  This results in failures†.
Because there’s no fundamental difference between `expensive` and
`lib` tests, rather than fixing handling of `lib` tests, convert them
to `expensive` …
=> nayduck: fix `lib` tests

nightly/TODO-disabled-4552.txt, nightly/nightly.txt, nightly/pytest-stress.txt, scripts/nayduck.py
When check_pytest.py and check_nightly.py read the test list files
handle commented out include directives (i.e. `#./<path>` lines) so
that the include can be commented out with a TODO and the check
scripts will treat files listed in those files as being mentioned.
Issue: https://github.com/near/nearcore/issues/4362
Issue: https://github.com/near/nearcore/issues/4552
=> nayduck: support reading commented ./<path> include directives

Cargo.lock, runtime/runtime-params-estimator/Cargo.toml, runtime/runtime-params-estimator/README.md, runtime/runtime-params-estimator/src/main.rs
Today, to get precise gas estimations via instruction counts, one needs
to follow a series of manual steps from emu-cost/README.md.
This PR optimizes part of that. It adds `--docker` argument to the
parameter estimator, which takes care of docker and qemu.
With this argument, the estimator on the host machine launches a docker
container, compiles a copy of itself in docker, and runs that copy via
qemu.
There are a couple of manual steps left:
* running neard init
* running genesis-populate
* picking the specific parameter values we use for estimation
Those will be automated in subsequent PR. The desired end goal is that
```console
$ cargo run -- --docker
```
is the *single* command you need to run the whole estimation process.
At that point, all various bash and python scripts will be …
=> feat: one button "run estimator in docker \w qemu" 

scripts/check_nightly.py
Rather than requiring white space between hash sign denoting a comment
line and the test specification, accept lines whether that space is not
there.  While at it also remove support for `lib` test category since
those are no longer a thing.
=> scripts: recognise `#expensive` lines in check_nightly.py script

nightly/TODO-disabled-4552.txt, nightly/nightly.txt, nightly/pytest-adversarial.txt, nightly/pytest-sanity.txt, nightly/pytest-stress.txt
Delete `TODO-disabled-4552.txt` file and move the four tests listed there
to files they belong to.  With that also retire issue #4552 since now all
the tests are tracked in #4618.
Fixes: https://github.com/near/nearcore/issues/4552
=> nightly: move disabled tests to their corresponding files

Cargo.toml
Cargo's smaller profiles, like `test` and `bench`, work in a rather
curious fashion. When you run `cargo test`, `cargo test --release` or
`cargo bench`, the tset/bench profiles apply only to a subset of code
being compiled. Most things are compiled with dev/release profile
instead.
To avoid surprises where things compile differently, it's advisable to
keep bench in sync with release.
cc https://github.com/near/nearcore/pull/4507
=> refactor: keep bench and release profile in sync to avoid surprises

core/account-id/src/lib.rs
Fixes `AccountId::is_sub_account_of()`, subaccount checks are valid one level deep only.
The previous behaviour accepts `a.b.c.test` as a valid subaccount of `c.test`. This fix marks that as invalid and exclusively matches `a.b.c.test` only as a valid subaccount of `b.c.test`.
=> fix(account-id): subaccounts are valid one level deep only

pytest/lib/populate.py
Popen.wait does not check whether the executed command failed or not and
there was nothing in genesis_populate that would test that.  As a result,
the test would ignore any failures in the genesis-populate tool.  Change
the code to use subprocess.check_call instead which raises on failure.
Issue: https://github.com/near/nearcore/issues/4574
=> pytest: verify that `genesis-populate` run succeeded

pytest/lib/cluster.py
If a process has already terminated, there’s no point complaining
that we’ve failed to deliver SIGKILL signal to it.  Just treat it
as successful termination.
This eliminate noisy logs such as:
[2021-08-05 23:31:07] CRITICAL: Kill failed on cleanup!
Traceback (most recent call last):
File "lib/cluster.py", line 365, in cleanup
self.kill()
File "lib/cluster.py", line 341, in kill
os.kill(self.pid.value, signal.SIGKILL)
ProcessLookupError: [Errno 3] No such process
Issue: https://github.com/near/nearcore/issues/4574
=> pytest: don’t complain if trying to kill already dead process

Cargo.lock, integration-tests/Cargo.toml, integration-tests/src/node/runtime_node.rs, integration-tests/src/runtime_utils.rs, test-utils/testlib/Cargo.toml, test-utils/testlib/src/runtime_utils.rs
by moving the 'get_runtime_and_trie_from_genesis' function into the 'integration-tests' crate, which is the only place using this function.
Fixes #4357
`cargo test --package node-runtime`
After: `Finished test [unoptimized] target(s) in 2m 55s`, 587 targets
Before: `Finished test [unoptimized] target(s) in 3m 01s`, 612 targets
=> Break the circular dependency of runtime/runtime on testlib

runtime/near-test-contracts/src/lib.rs
Include the full path of the file that the test tried to read in
panic message.
Issue: https://github.com/near/nearcore/issues/4574
=> tests: make panicks in near-test-contracts more verbose

Cargo.lock, chain/client/Cargo.toml
refactor: remove work-around for cargo features
The `node-runtime` dependency in `client` creates a cyclic dependency:
near_client -> node_runtime -> testlib -> near_client
Looks like we can remove it just now, because the dep is used to
work-around cargo features, and is not otherwise used.
I think this was enabled by the recent work on
https://github.com/near/nearcore/issues/4357
Test Plan
--------
```
cargo check --all-targets && \
cargo check --all-targets --features sandbox && \
cargo check --all-targets -p near-client && \
cargo check --all-targets -p near-client --features sandbox
```
=> refactor: remove work-around for cargo features

neard/src/cli.rs
fixes #4464 
fixes #4569
Test plan: verify the genesis config generated is the same as 1.19.2
``` 
$ nearcore-1 git:(ebc1e0a26) diff /Users/minzhang/.near-1.19.2/test0/genesis.json /Users/minzhang/.near-now/test0/genesis.json
2,4c2,4
<   "protocol_version": 45,
<   "genesis_time": "2021-08-18T15:45:26.235826Z",
<   "chain_id": "test-chain-WLJhS",
---
>   "protocol_version": 47,
>   "genesis_time": "2021-08-18T15:40:31.252129Z",
>   "chain_id": "test-chain-b25OT",
156a157,159
>         "ripemd160_base": 853675086,
>         "ripemd160_block": 680107584,
>         "ecrecover_base": 3365369625000,
205a209
>         "max_transaction_size": 4194304,
242a247
>   "simple_nightshade_shard_config": null,
251c256,257
<           "storage_usage": 0
---
>           "storage_usage": 0,
> …
```
=> fix: change default behavior of neard testnet 

scripts/nayduck.py
There’s no longer need to be a public member of the organisations to
authenticate with NayDuck.  Furthermore, update location of the NayDuck
source code and documentationd and test suits files.
Issue: https://github.com/near/nearcore/issues/2411
=> scripts: update nayduck.py comment documentation

nightly/expensive.txt
The second argument of an expensive test is a test binary name.
Those use snake_case and should be specified as such, e.g. `near_chain`
rather than `near-chain`.  Using dashes works because NayDuck replaces
them with underscores but this behaviour is going away (since it adds
unnecessary complexity) so use proper naming instead.
=> nightly: fix test binary file name in nightly test list

nightly/mocknet.txt
Issue: https://github.com/near/nearcore/issues/4726
=> nightly: disable mocknet tests since Mocknet isn’t currently running

chain/chain/src/chain.rs, chain/chain/src/test_utils.rs, chain/chain/src/types.rs, chain/chain/src/validate.rs, chain/chunks/src/lib.rs, chain/chunks/src/test_utils.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/view_client.rs, genesis-tools/genesis-populate/src/lib.rs, integration-tests/tests/client/challenges.rs, nearcore/src/runtime/mod.rs
Now the signature becomes `account_id_to_shard_id(account_id: &AccountId, epoch_id: &EpochId)` and `num_shards(epoch_id: &EpochId)`
Test Plan: passes all existing tests. 
It is hard to fully test this change before we implement state transitioning for resharding. Before that, all epochs still use the same shard layout, so we can't actually test that `account_id_to_shard_id` and `num_shards` are using the correct shard layout from the current epoch. I will add tests later once we implement state transition.
=> make `account_id_to_shard_id` and `num_shards` to take shard layout from the current epoch

chain/client/src/info.rs, chain/client/src/metrics.rs
…t run mainnet validators, this metric can still be exported by the RPC nodes and can be used in our dashboard. This is a useful indicator of block fullness for loadtests.
=> Add a metric for the average amount of Tgas burned in chunks

pytest/lib/cluster.py, pytest/tests/companion.py, scripts/check_pytests.py
The tests/companion.py script is not used for anything (and as far as
I can tell it was never really used).  Delete it.
=> pytest: remove unnecessary companion.py script

pytest/tests/runtime/fuzz.py
Standard error output of the fuzzing is passed through directly
and standard output generated by the `fuzz.py` test only duplicates
information already present in standard error.  And the data can get
quite big† so it’s a waste to include it in both streams.
Stop capturing output of the `cargo fuzz` command and instead
convert the `fuzz.py` test to simply exec the command setting up
the environment beforehand.
† For example http://nayduck.eastus.cloudapp.azure.com:3000/#/run/2047
Issue: https://github.com/near/nearcore/issues/4550
=> pytest: fuzz: don’t capture output

pytest/tests/runtime/fuzz.py
Enabling parallelism in the fuzz slows down the execution and thus leads
to spurious crashes because of asserts on block production time.  Remove
the --jobs switch.
This reverts commit a0b76201c394cb3f609b5efea374c5ba1bdb0693.
Issue: https://github.com/near/nearcore/issues/4550
=> Revert "pytest: fuzz: enable parallelism (#4755)"

chain/jsonrpc-primitives/src/types/blocks.rs, chain/jsonrpc-primitives/src/types/changes.rs, chain/jsonrpc-primitives/src/types/config.rs, integration-tests/tests/nearcore/rpc_error_structs.rs, integration-tests/tests/nearcore/rpc_nodes.rs
The `BlockReference` enum is duplicated in `near-primitives` and `near-jsonrpc-primitives`. The likely reason for this, was to allow for jsonrpc-specific features [Context: <https://github.com/near/nearcore/pull/3861#discussion_r566134004>], but at this moment, they are, for the purposes that matter, identical. With the one in `near_jsonrpc_primitives` plainly convertible `Into` the one in `near_primitives`.
=> refactor(jsonrpc-primitives): deduplicate BlockReference

chain/jsonrpc-primitives/src/errors.rs
`format!("error: {}", err.to_string())` -> `format!("error: {}", err)`
=> refactor(jsonrpc-primitives): impl Display instead of ToString for RpcError

core/primitives/src/errors.rs
`near-runtime-utils` was removed in favor of `near-account-id`, remove old references to it.
=> chore: remove stale references to near-runtime-utils

runtime/runtime-params-estimator/src/main.rs
And also build test contract, which is used in some metrics computation. Corresponding command was included into README.
We could also consider adding this to each metric separately.
Test plan
---------
- cargo check
- make two separate runs and check difference: https://hackmd.io/glLIGVM7RjKSKSe8p9h6rw
=> feat: pass environment variables to docker

core/store/src/trie/shard_tries.rs, nearcore/src/runtime/mod.rs
This PR makes two changes
- Add a new function `add_new_shards` in ShardTries that adds new shards to it. This function will need to be called for building states for new shards in re-sharding
- Locks `tries` in NightshadeRuntime since now it can be modified through `add_new_shards`
Test Plan:
Existing CI tests
=> Add a RwLock to tries in NightshadeRuntime

integration-tests/tests/standard_cases/main.rs, integration-tests/tests/standard_cases/runtime.rs, test-utils/testlib/src/runtime_utils.rs
Add an integration test that asserts an account alice cannot create
accounts of type x.y.alice but can create accounts of type x.alice.
Fixes https://github.com/near/nearcore/issues/4696
=> Add test for creating invalid subaccount

pytest/requirements.txt
While we’re not using Cython directly, scikit-learn does and
for some reason that dependency is not picked up automatically.
Add Cython back to requirements.txt.
=> pytest: add cython back to requirements

core/store/src/lib.rs, core/store/src/trie/shard_tries.rs, core/store/src/trie/split_state.rs, nearcore/src/runtime/mod.rs
This PR refactors the implementation of ShardTries to make it more comply with the general rust design guideline such as interior mutability. It makes two changes
- remove the Arc of individual fields in ShardTries and Arc the whole ShardTries struct instead
- hide the RwLock inside ShardTries so the callers of ShardTries do not need to worry about locking (interior mutability)
=> refactor ShardTries

.gitattributes
Cargo.lock is one of the more important files in the project, especially
in security-sensitive projects. We need to know which dependencies
change and when, we need to keep an eye on accidental additions of new
dependencies.
It's very easy to accidentally upgrade everything when adding just a
single new dependency, and that's what almost happened in #4395.
I haven't seen other big rust-projects adding Cargo.lock to
.gitattributes.
=> chore: don't hide Cargo.lock from diff

README.md
The link points to the issues from 2020, so it seems that it doesn't
have a place in README?
=> docs: drop obsolete link

runtime/near-test-contracts/build.rs
If CARGO_ENCODED_RUSTFLAGS environment variable is set Cargo uses its
value in preference to RUSTFLAGS variable.  As such, to make sure the
latter takes effect the former needs to be unset.
=> near-test-contracts: make sure RUSTFLAGS env. variable takes effect

chain/jsonrpc-primitives/src/types/status.rs, core/primitives/src/types.rs
`EpochReference` is defined as such:
https://github.com/near/nearcore/blob/06d05bce3fab578a91b210d7354fb17427fcc9d6/core/primitives/src/types.rs#L1001-L1007
And it's serialization, as such:
| % | `EpochReference::BlockId(...)` | `EpochReference::Latest` |
| - | ------------------------------ | ------------------------ |
| expectation | `{"block_id": ...}` | `{"latest": null}`
| reality | `{"block_id": ...}` | `"latest"` |
As you can already see, `serde`'s default method for serializing unit variants is to use a string 
unlike how it uses an object for the rest of the variants.
This PR implements custom serialization for `EpochReference`, specifically for the `Latest` variant. So it serializes to `{"latest": null}`.
> Note: this retains the default deserialization so we have no breaking …
=> fix(near-primitives): `EpochReference` enum can be flattened into a struct

Cargo.lock, runtime/near-vm-runner/Cargo.toml
This includes https://github.com/near/wasmer/commit/c92fcf712212f62cd3c3007454031ebd7ecf81c0 to unconditionally disable the remaining signal-handling related code.
=> Move to Wasmer 2.0.1

runtime/runtime-params-estimator/costs.txt
cc #4639
Test Plan
--------
This file is not a source of truth currently, so the change doesn't
affect anything.
=> fix: use correct (not safely-multiplied) cost in the canonical costs file

core/primitives/src/views.rs
Since #4438, the `metadata` field was introduced on `ExecutionOutcomeView`.
Older nodes _(e.g the ones deployed on `[archival-]rpc.<network>.near.org` as of today)_ do not include that field. This means deserializing that data into the new `ExecutionOutcomeView` fails.
This PR introduces a default value for that field. Specifically, from `ExecutionMetadata::V1`.
=> fix(primitives): backwards compatible ExecutionOutcomeView

chain/client/src/test_utils.rs, integration-tests/tests/client/challenges.rs, integration-tests/tests/client/process_blocks.rs, integration-tests/tests/client/runtimes.rs
Replace TestEnv constructors with a TestEnvBuilder structure instead.
Motivation for this change are twofold.  First of all, with Rust’s
lack of default or keyword arguments constructors of TestEnv would
just continue to multiply with more and more arguments.  Second of
all, with the current design whoever uses TestEnv structure must
adhere to `test{}` AccountId format which may not always be desired.
With this commit also change three instances where
TestEnv::new_with_runtime_and_network_adapter was used by the use of
the builder.  Other places where TestEnv constructors are used are
left for now and will be dealt in another commit.
=> Introduce TestEnvBuilder structure

CODEOWNERS
Better not have a single reviewer, especially for parts of code-base
which are not correctness-critical.
=> chore: add matklad to runtime-tester codeowners

test-utils/runtime-tester/src/run_test.rs
=> runtime-tester: use provided account ids when creating test environment

chain/client/src/sync.rs, chain/client/src/test_utils.rs, chain/client/tests/chunks_management.rs, integration-tests/tests/client/challenges.rs, integration-tests/tests/client/process_blocks.rs
Remove the TestEnv::new constructor in favour of using the builder.
This is exactly what has been already been done with new_with_runtime
and new_with_runtime_and_network_adapter methods.  This commit removes
the last constructor of the TestEnv structure leaving the builder as
the only way to creating TestEnv structures.
=> Remove TestEnv::new constructor in favour of a builder

chain/network/src/ibf.rs
Fixes the following compiler error:
$ cargo build --release
error[E0277]: `[usize; 3]` is not an iterator
--> chain/network/src/ibf.rs:215:20
215 |         for pos in pos_list {
|                    ^^^^^^^^ borrow the array with `&` or call `.iter()` on it to iterate over it
Issue: https://github.com/near/nearcore/issues/3838
=> ibf: fix [usize; 3] not being an iterator compilation error

chain/jsonrpc-primitives/Cargo.toml, chain/network/Cargo.toml
Fix compilation error in `near-jsonrpc-primitives` when building with the `adversarial` feature enabled after https://github.com/near/nearcore/pull/4112
=> fix(jsonrpc-primitives): fix adversarial-related compilation errors

core/primitives/src/runtime/config.rs
Remove deprecated `ActualRuntimeConfig` which has no uses now.
Helper for https://github.com/near/nearcore/issues/4649.
Test plan
---------
Existing tests. Removed tests were migrated to `RuntimeConfigStore`.
=> refactor: remove ActualRuntimeConfig

test-utils/runtime-tester/fuzz/fuzz_targets/runtime_fuzzer.rs
This fixes the following error:
error[E0308]: mismatched types
--> fuzz_targets/runtime_fuzzer.rs:10:12
10 |     if let Err(e) = runtime_stats {
|            ^^^^^^   ------------- this expression has type `ScenarioResult<RuntimeStats, near_client_primitives::types::Error>`
|            |
|            expected struct `ScenarioResult`, found enum `Result`
error[E0599]: no method named `unwrap` found for struct `ScenarioResult` in the current scope
--> fuzz_targets/runtime_fuzzer.rs:14:35
14 |         let stats = runtime_stats.unwrap();
|                                   ^^^^^^ method not found in `ScenarioResult<RuntimeStats, near_client_primitives::types::Error>`
It can be reproduced by running runtime/fuzz.py pytest.
=> runtime-tester: fix runtime_fuzzer test

chain/network/Cargo.toml
Building with `cargo build --all-targets --features adversarial` is failing.
See http://nayduck.near.org/#/build/2184
Reported by @mina86
=> Fix build with NayDuck

integration-tests/tests/nearcore/rpc_nodes.rs, pytest/tests/stress/stress.py
Since https://github.com/near/nearcore/pull/3059 there no longer is any `IsSyncing` server error respnse.
=> chore: remove deprecated IsSyncing variant check

.buildkite/pipeline.yml
This shouldn’t add more than around 30s to the ‘sanity checks’ CI step
(so a bit less than 10% of current run time) which is hardly the
critical step (‘sanity checks’ take less than six minutes while
running tests takes over twenty).
Issue: https://github.com/near/nearcore/issues/4893
=> CI: make sure neard builds with adversarial feature

chain/chain/src/chain.rs, chain/client-primitives/src/types.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/info.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs
We need to split state in SyncJobActor to free up ClientActor to do other things in the meantime (very important for validators)
This still requires full integration test
=> Split state in SyncJobsActor

chain/chain/src/chain.rs, chain/chain/src/store.rs, chain/chain/src/validate.rs, chain/client/src/test_utils.rs, chain/epoch_manager/src/reward_calculator.rs, core/primitives-core/src/config.rs, core/primitives-core/src/serialize.rs, core/primitives/src/epoch_manager.rs, core/primitives/src/errors.rs, core/primitives/src/runtime/config.rs, core/primitives/src/runtime/mod.rs, core/primitives/src/sharding.rs, core/primitives/src/transaction.rs, core/primitives/src/version.rs, core/store/src/db.rs, nearcore/src/migrations.rs, runtime/near-vm-logic/src/context.rs, runtime/near-vm-logic/src/serde_with.rs, runtime/near-vm-runner-standalone/src/main.rs
Mostly wrapping URLs in angle brackets and code fragments in backticks
to make `cargo doc` happy.
=> Fix various minor documentation warnings

chain/chain/src/migrations.rs, chain/chain/src/store.rs, chain/client/src/client.rs, chain/client/src/test_utils.rs, core/store/src/test_utils.rs, integration-tests/tests/client/main.rs, integration-tests/tests/client/process_blocks.rs, integration-tests/tests/client/sharding_upgrade.rs
This PR adds an integration test for sharding upgrade. It also fixes function `check_if_block_is_first_with_chunk_of_version` to make it work when number of shards changes.
The integration test tests logic on the client level (no logic in ClientActor is included) and checks that transactions/receipts are processed correctly during sharding upgrade. It also checks that the final after sharding upgrade is correct. 
This PR is a beginning. I will add more tests in the same file using the framework.
=> Integration test for sharding upgrade

runtime/near-vm-errors/src/lib.rs, runtime/near-vm-runner-standalone/src/main.rs, runtime/near-vm-runner/src/vm_kind.rs
We generally want to move away from marking various internal structures
as Serialize -- it's very easy to introduce breakages that way.
In this case, the only reason why we need serialize is to print outcome
in the standalone runner, but we can just to-string it.
Test Plan
-------------
Pure refactoring, existing tests should suffice.
=> refactor: remove some spurious Serializes

chain/rosetta-rpc/src/adapters/mod.rs, core/chain-configs/src/genesis_config.rs, core/primitives-core/src/config.rs, core/primitives-core/src/runtime/fees.rs, core/primitives/src/runtime/config.rs, core/primitives/src/runtime/config_store.rs, nearcore/src/config.rs, runtime/near-vm-logic/tests/vm_logic_builder.rs, runtime/near-vm-runner-standalone/src/script.rs, runtime/near-vm-runner/src/tests.rs, runtime/near-vm-runner/src/tests/contract_preload.rs, runtime/near-vm-runner/src/tests/rs_contract.rs, runtime/near-vm-runner/src/tests/ts_contract.rs, runtime/runtime-params-estimator/src/costs_to_runtime_config.rs, runtime/runtime-params-estimator/src/function_call.rs, runtime/runtime-params-estimator/src/gas_metering.rs, runtime/runtime-params-estimator/src/testbed.rs, runtime/runtime-params-estimator/src/vm_estimator.rs, runtime/runtime/src/actions.rs, runtime/runtime/src/balance_checker.rs, runtime/runtime/src/lib.rs, runtime/runtime/src/state_viewer/mod.rs, runtime/runtime/src/verifier.rs, runtime/runtime/tests/runtime_group_tools/random_config.rs, tools/storage-usage-delta-calculator/src/main.rs
Having default impls for `RuntimeConfig` and `RuntimeFeesConfig` is confusing, because one may think that it is the actual protocol sub-configs, whereas they are used mostly for testing.
Here I separate cases where we want to take:
- actual protocol config
- some test config
Helps to solve https://github.com/near/nearcore/issues/4649.
Test plan
---------
Existing tests. 
~~Note that `test_data_roundtrip_is_more_expensive` was moved to `config_store` because I don't see a reason for testing test config.~~
Note that `test_data_roundtrip_is_more_expensive` is removed because its logic seems to be incorrect (see comments).
=> refactor: separate default and test runtime configs

Cargo.lock, neard/src/cli.rs
We are trying to embrace tracing spans for logging:
let _span = tracing::debug_span(target: "vm", "frobnicate");
// code for frobnicate
Logically, a span produces two events -- start and stop. At the time of
`stop`, we also know how long the span took to complete, which is
invaluable for accessing systems performance.
Before, we were only logging span closing events, as they contain this
timing data. The two problems there are:
* ordering is a bit counter-intuitive -- you get log output *after* the fact
* if the process aborts without dropping the spans, the events don't get
printed
So here we change the logic to produce two log-lines per span:
* once we enter the span (which contains just the name)
* once we exit the span (which contains the timing information)
Exmample output before: …
=> feat: when logging tracing spans, display both start and end events

chain/chain/src/chain.rs
This is based on syntax-level understanding of the code, so please
tripple-check. It seems that the old code flipped the order of
if-branches: if the feature is not active at runtime, we should be doing
the same thing as if the features is not enabled at compile time.
Fix the issue by not repeating the code twice and leveraging the
feature-checking macro instead.
=> fix: correct feature handling

chain/network/src/cache.rs, chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/tests/cache_edges.rs
We shouldn't be using non monotonous time with chrono::Now()
Closes #5096 
Moving changes out of https://github.com/near/nearcore/pull/5089
=> Replace chrono::now() with Instant::now()

.buildkite/pipeline.yml
This CI job tries to build nearcore without Cargo.lock. That means it
uses the latest crates.io dependencies at the time the build is run.
This isn't a useful property to check for us -- we build a binary, and
we ship Cargo.lock. We only care about specific version set pinned
there. We are not a library, we are an end-application.
Additionally, this check creates more busy work for us. Given the amount
of dependencies we have, it's highly probable that someone would
sometimes publish a broken revision (which would be subsequently yank).
With the current setup, this'll break any PR to nearcore, even those
that don't touch dependencies.
=> chore: don't check latest crates.io releases on CI

neard/src/cli.rs
Currently, the --verbose flag help text doesn't really explain what its argument should be, and the --home-dir flag's help text prints the default twice.
=> nit: improve neard --help text

pytest/tests/sanity/state_sync_routed.py
This deflakes the test, see <http://nayduck.near.org/#/run/2183>.
=> pytest: state_sync_routed: override ‘tracked_shards’ in all nodes

nightly/pytest-sanity.txt
Those tests are consistently failing. Disable them and add to
the tracking Issue.
Issue: https://github.com/near/nearcore/issues/5095
=> nightly: disable currently broken tests

nightly/expensive.txt
From NayDuck’s point of view, an ignored expensive test is a working test
(since it does not fail).  Enable `tests::test_chunk_grieving` which is
in that state and which is tracked by a separate issue.
Issues: https://github.com/near/nearcore/issues/3180
=> nightly: enable ignored tests::test_chunk_grieving

chain/network/src/routing.rs
This impl of `Hash` is inconsistent with our derived Eq, which violates
trait's contract:
https://doc.rust-lang.org/stable/std/hash/trait.Hash.html#hash-and-eq
Seems like we don't actually use this, so let's just remove.
=> refactor: drop dead code

chain/network/src/routing.rs, chain/network/tests/cache_edges.rs
Closes #5135
`RoutingTable::update` method is not removing edges from `Graph` while graph pruning.
We will use `remove_edges` method, which has proper implementation of removing edges.
=> Hotfix removing edges from `Graph` inside `RoutingTable`

pytest/requirements.txt
scipy 1.7.2 causes buildkite to fail, see:
- https://buildkite.com/nearprotocol/nearcore/builds/6093#4a0ce8d7-f8c5-43ff-b0d6-db7343a84076 and
- https://buildkite.com/nearprotocol/nearcore/builds/6094#8a07e3cf-b646-447d-92e3-378846cab4b9
Pin to the last working version.
=> pytest: pin scipy to 1.7.1

chain/chunks/src/lib.rs, chain/chunks/src/test_utils.rs, chain/client/src/client.rs, chain/client/src/client_actor.rs, chain/client/src/sync.rs, chain/client/src/test_utils.rs, chain/client/src/view_client.rs, chain/client/tests/bug_repros.rs, chain/client/tests/catching_up.rs, chain/client/tests/chunks_management.rs, chain/client/tests/consensus.rs, chain/client/tests/cross_shard_tx.rs, chain/client/tests/query_client.rs, chain/jsonrpc/src/lib.rs, chain/network-primitives/src/types.rs, chain/network/src/lib.rs, chain/network/src/peer.rs, chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/src/test_utils.rs, chain/network/src/types.rs, integration-tests/tests/client/challenges.rs, integration-tests/tests/client/chunks_management.rs, integration-tests/tests/client/process_blocks.rs, integration-tests/tests/client/runtimes.rs, integration-tests/tests/network/infinite_loop.rs, integration-tests/tests/network/runner.rs
Closes #5142
We are going to group all messages in `PeerManager` under one enum called `PeerManagerMessageRequest`. `PeerManager` will have one single `Handler<...>` for messages. We will be able to extend this enum with extra paypoad that track sizes of all messages not processed yet, but coming from w given peer, which is needed for (https://github.com/near/nearcore/pull/4927), and make mocking PeerManager easier for test in the future.
=> Refactor PeerManager to group messages under one enum

chain/jsonrpc/jsonrpc-tests/src/lib.rs, chain/jsonrpc/src/lib.rs, chain/network/src/edge_verifier.rs, chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/src/routing_table_actor.rs, chain/network/src/test_utils.rs, chain/network/tests/cache_edges.rs, integration-tests/tests/network/infinite_loop.rs, integration-tests/tests/network/peer_handshake.rs, integration-tests/tests/network/runner.rs, integration-tests/tests/network/stress_network.rs, nearcore/src/lib.rs
We should refactor network code, before https://github.com/near/nearcore/pull/5089
- This refactoring doesn't contain any code changes, only methods/attributes are renamed to better names
- All changes are extracted from #5089, this was done to keep that PR smaller. This will cause merge conflicts, but it's better to extract syntax only changes to make #5089 easier to review.
Here is design doc for changes planned (https://docs.google.com/document/d/1FV3oyMRo52EQAgYroVd6Ws-5-ylkLSTdMOstY-IdL-M/edit?usp=sharing)
=> Refactor network code

chain/network/src/peer_manager.rs, chain/network/src/routing_table_actor.rs
In preparation for moving routing table computation to `RoutingTableActor`, we should move  handling `start_routing_table_syncv2` from `PeerManager` to `RoutingTableActor` first.
Related to https://github.com/near/nearcore/issues/5138
Change extracted from https://github.com/near/nearcore/pull/5089, to make that PR shorter.
=> Move code for starting new routing table sync to RoutingTableActor

runtime/near-vm-logic/tests/test_gas_counter.rs, runtime/near-vm-logic/tests/test_promises.rs
Add vm logic tests targeting gas counting logic specifically. In particular, `test_cant_burn_more_than_max_gas_burnt_gas` I believe passes the current master, but fails with #5121 (which passes all other tests).
=> test: add more cases for gas overflow behavior

utils/near-performance-metrics/src/stats_enabled.rs
We saw a node crash in `stats_enabled.rs`. This PR will prevent those crashes from happening.
```
let peak_memory =
ByteSize::b((max(initial_memory_usage, current_thread_peak_memory_usage() - initial_memory_usage) as u64);
```
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'attempt to subtract with overflow', /var/lib/buildkite-agent/builds/buildkite-i-05f8afe8aa72d3ae8-1/nearprotocol/nearcore-nightly-release/utils/near-performance-metrics/src/stats_enabled.rs:328:21
stack backtrace:
0: rust_begin_unwind
at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
1: core::panicking::panic_fmt
at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
2: core::panicking::panic
at …
```
=> Prevent crash in stats_enabled.rs

chain/jsonrpc/jsonrpc-tests/src/lib.rs, chain/network/src/lib.rs, chain/network/src/peer_manager.rs, chain/network/src/routing_table_actor.rs, chain/network/src/test_utils.rs, integration-tests/tests/network/infinite_loop.rs, integration-tests/tests/network/peer_handshake.rs, integration-tests/tests/network/runner.rs, integration-tests/tests/network/stress_network.rs, nearcore/src/lib.rs
Make `RoutingTableActor` use Context instead of `SyncContext`.
`SyncContext` is meant to be used in situations, where someone wants to start multiple instances of actors, each one separate thread. We only have one instance, and the code wouldn't work with multiple instances, so we are changing `SyncContext` to `Context`, to make reading code less confusion.
Additional changes:
- Add `edge_verifier_pool` to `RoutingTableActor` (for https://github.com/near/nearcore/pull/5089)
- Rename `routing_table_pool` to `routing_table_addr`
Changes are extracted from https://github.com/near/nearcore/pull/5089 to make it easier to review.
=> Make RoutingTableActor use Contex instead of SyncContext.

chain/network/src/peer_manager.rs, chain/network/src/routing.rs, chain/network/src/routing_table_actor.rs
Add new features to routing table actor.
- do edge pruning (not used yet)
- store all edges in `edges_info`
-  `StartRoutingTableSync` (handling first message of protocol_feature_routing_exchange_algorithm)  (not yet used)
-  `RoutingTableUpdate` (updating routing table and maybe pruning edges) (not yet used)
-  `AddVerifiedEdges` - adds verified edges and updates stats (Similar to `AddEdges`, but does more) (not yet used)
This is done to split https://github.com/near/nearcore/pull/5089 into smaller pieces.
This should be reviewed after https://github.com/near/nearcore/pull/5159, as this PR also includes changes in that request.
=> Add new features to RoutingTableActor

chain/jsonrpc/src/lib.rs, chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/routing.rs, chain/network/src/routing/routing_table_actor.rs, chain/network/src/test_utils.rs, chain/network/src/types.rs, chain/network/tests/cache.rs, chain/network/tests/cache_edges.rs, integration-tests/tests/network/runner.rs, pytest/tests/sanity/routing_table_sync.py
In this PR we will creating copy of routing table to another thread.
This is related to https://github.com/near/nearcore/issues/4859
Summary:
- `PeerManager` no longer has copy of `edges_info`, instead it only stores list of edges to peers that it is/was connected to `local_edges_info`
- Removed usage of edges in `PeerManager` that were stored in ` edges_info`
- Computation of `peer_forwarding` is done in `RoutingTableActor`, `PeerManager` gets it from another thread every second / tests now use `RoutingTableActor` instead of `RoutingTable` struct
- moved `pub raw_graph: Graph,`  and a few other data structures  to `RoutingTableActor`
- Removed `adv_get_routing_table_new` from jsonrpc server. Now, routing table is only stored in one place, so this method is no longer needed
- Added …
=> Move routing table exchange to another thread

chain/network/src/routing/routing_table_actor.rs
`tests/sanity/routing_table_sync.py` was failing, indicating that we were not running edge pruning nor routing table recalculation.
Here is a hotfix.
The following code was missing:
```
self.needs_routing_table_recalculation = true;
```
=> Hotfix routing table recalculation

runtime/near-vm-logic/src/gas_counter.rs
Rather than special casing view calls each time prepaid gas is
checked, simply assume that prepaid gas is effectively infinite.  The
max gas burnt limit will still have an effect.
This fixes `sanity/rpc_max_gas_burnt.py` pytest which has been broken
by the recent ‘Simplify gas metering’ commit.  The commit changed
GasLimitExceeded failure into GasExceeded (by changing order in which
error conditions were checked).  This commit changes this back by
effectively disabling the first if branch in `process_gas_limit`
function when performing a view call.
=> runtime: simplify prepaid gas accounting in view calls

chain/network/src/routing/routing_table_actor.rs, chain/network/tests/cache_edges.rs
`tests/sanity/routing_table_sync.py` test wasn't fully fixed.
We were not pruning while `prune == Prune::PruneNow`, because no routing table calculation was done.
This PR fixed the test properly.
The bug was in not having ```prune == Prune::PruneNow ``` check. In this PR we will improve code quality as well, and split `recalculate_routing_table_and_maybe_prune_edges` into to separate methods.
=> Fix `tests/sanity/routing_table_sync.py`test

pytest/tests/sanity/routing_table_sync.py
We saw that nayduck test failed, due to having 2s timeout in `nodes[0].get_status(timeout=30)`
Closes https://github.com/near/nearcore/issues/5188#event-5600015413
=> Fix timeout in routing_table_sync.py

chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/edge_verifier_actor.rs, chain/network/src/routing/routing.rs, chain/network/src/routing/routing_table_actor.rs, chain/network/tests/cache_edges.rs
We are using `clone()` a lot in `Edge`.
I propose we change structure of `Edge` to use
```rust
key: (PeerId, PeerId)
```
instead of
```rust
peer0: PeerId,
peer1: PeerId
```
Resolves #5221
=> We should remove cloning from Edge

chain/network/src/routing/routing_table_actor.rs
We found some unused code
- `pub fn get_edge(&self, peer0: PeerId, peer1: PeerId) -> Option<Edge> {`
- `pub fn convert_simple_edges_to_edges(&self, edges: Vec<SimpleEdge>) -> Vec<Edge> {`
=> Remove unused code

utils/near-performance-metrics/src/actix_enabled.rs, utils/near-performance-metrics/src/framed_write.rs, utils/near-performance-metrics/src/stats_enabled.rs
We should refactor the code to handle time in a safe way.
It's not safe to compute duration using `end - start`. Due to various bugs, this can cause panic as seen in #5172
We have seen a crash related to not handling time correctly https://github.com/near/nearcore/pull/5172
=> Refactor code for handling time in near-performance-metrics

core/store/src/db.rs
We recently found out that our rockdb is not efficient enough.
Therefore we would like to increase cache size of specific columns.
In this PR we will increase cache size for `DBCol::ColState` to 128mb.
We can adjust that cache size later, but we try to be conservative in memory usage. 
Some testing should be done to determine optimize cache sizes. 
Closes https://github.com/near/nearcore/issues/5203
=> Increase cache for RockDB by column

chain/network/Cargo.toml, chain/network/benches/routing_table_actor.rs, chain/network/src/peer/peer_actor.rs, chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/ibf_peer_set.rs, chain/network/src/routing/routing.rs, chain/network/src/routing/routing_table_actor.rs, chain/network/tests/cache_edges.rs
Add bench to measure time it takes to copy routing table.
- We should compare what the performance would be if we were using
` HashSet<(PeerId, PeerId), Edge>` vs ` HashSet<(PeerId, PeerId), Arc<Edge>>`
=> Replace Edge with Arc<Edge> to improve performance

chain/network/benches/graph.rs, chain/network/src/routing/routing.rs, chain/network/src/routing/routing_table_actor.rs, core/primitives/src/network.rs
We've been cloning `Edge` in order to convert it to `Vec<u8>`. That seems wasteful.
- change `impl From<PeerId> for Vec<u8> {` to `impl From<&PeerId> for Vec<u8> {`
=> We shouldn't be cloning PeerId so often

chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/route_back_cache.rs, chain/network/src/routing/routing.rs
We have seen cases where nodes would get stack syncing. (https://github.com/near/nearcore/issues/5112)
It looks like we are trying to request headers from a route to which we don't have a route:
```
Nov 08 08:05:14 public-v1-archive-mainnet-rpc-node-p3x5 sh[1942]: Nov 08 08:05:14.108 DEBUG network: None Drop signed message to Hash(`GC72RjNQpJuKMierihJ4bYaF7WMFQCYfPgadbRyGE3fA`) Reason RouteBackNotFound. Num known peers: 411 Message PartialChunkResponse(ChunkHash(`6Y2YYNUpp62uNQxAvo3a7LxfC4eLMDeXeoZisKHcPANx`), [84])
Nov 08 08:05:14 public-v1-archive-mainnet-rpc-node-p3x5 sh[1942]: Nov 08 08:05:14.131 DEBUG network: None Drop signed message to Hash(`C6Q52jRSJxnfuSn7TuoSbVXcEVM8DtpB2xikFDamzLVT`) Reason RouteBackNotFound. Num known peers: 411 Message …
```
=> Add extra logs to investigate issues

integration-tests/tests/network/routing.rs
Add fix to `routing::ping_jump` test
As seen in `https://buildkite.com/nearprotocol/nearcore/builds/6677#5ccd6608-35c5-474b-9cb9-819a4033eccb`
This happened, because updating routing table is not done in `PeerManager` anymore.
=> Fix routing::ping_jump test

pytest/tests/sanity/routing_table_sync.py
We recently changed internal representation of `Edge` to use `key` attribute instead of `peer0`, `peer1`.
This will fix the test. Maybe we should use different structure for  `Edge`, that's independent from the one used in `jsonrpc`.
=> Fix routing_table_sync after changing  internal representation

chain/network/benches/routing_table_actor.rs, chain/network/src/peer/peer_actor.rs, chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/ibf_peer_set.rs, chain/network/src/routing/routing.rs, chain/network/tests/cache_edges.rs
As @matklad suggested, it's a good idea to replace `Arc<Edge>` with a structure, to make code more readable.
=> Replace Arc<Edge> with a structure

chain/network-primitives/src/types.rs, chain/network/benches/routing_table_actor.rs, chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/routing.rs, core/primitives-core/src/hash.rs, core/primitives/src/network.rs
`build_hash` can be optimized by 50% from 450ns per loop to around 300 ns per loop
=> Optimize build_hash function by 50%

Cargo.lock, chain/network-primitives/Cargo.toml, chain/network/Cargo.toml, core/primitives/src/network.rs
We ran a test, and we found that that we can replace old routing table exchange by 30% if we replace `PeerId` with `Arc<PeerId>`.
Mentioned in https://github.com/near/nearcore/issues/5221
Before
```
running 3 tests
test calculate_distance_10_10  ... bench:      12,261 ns/iter (+/- 329)
test calculate_distance_10_100 ... bench:   1,333,230 ns/iter (+/- 20,893)
test calculate_distance_3_3    ... bench:         732 ns/iter (+/- 16)
```
After
```
test calculate_distance_10_10  ... bench:      11,488 ns/iter (+/- 220)
test calculate_distance_10_100 ... bench:     672,570 ns/iter (+/- 58,342)
test calculate_distance_3_3    ... bench:         616 ns/iter (+/- 5)
```
Before
```
test get_all_edges_bench_old  ... bench:   1,001,797 ns/iter (+/- 383,813)
```
After:
``` …
```
=> Replace PeerId with Arc<PeerId>

chain/client/src/client.rs, chain/network/src/lib.rs, chain/network/src/peer/mod.rs, chain/network/src/peer/peer_actor.rs, chain/network/src/routing/mod.rs
Mark some of near-network crates as private.
Also move 
```
/// The time we wait for the response to a Epoch Sync request before retrying
// TODO #3488 set 30_000
pub const EPOCH_SYNC_REQUEST_TIMEOUT_MS: u64 = 1_000;
/// How frequently a Epoch Sync response can be sent to a particular peer
// TODO #3488 set 60_000
pub const EPOCH_SYNC_PEER_TIMEOUT_MS: u64 = 10;
```
to `ClientActor`.
=> Mark some of near-network crates as private

chain/network/src/routing/routing_table_actor.rs, core/primitives/src/network.rs
Remove `<&PeerId>` to `Vec<u8>` conversion.  In Rust we generally avoid having implicit memory allocations.
It's better to call `try_to_vec` directly.
=> Make <&PeerId> to Vec<u8> conversions explicit

CODEOWNERS
`/chain/jsonrpc` has same owners as `/chain/jsonrpc-primitives`.
same for /chain/client/src/view_client.rs` and `/chain/client-primitives`.
Should we do the same thing for `/chain/network` and `/chain/network-primitives` ?
=> Change code owners for network primitives

Cargo.lock, chain/network/Cargo.toml
Dependencies in `near-network` / `Cargo.toml` are not sorted correctly. Let's fix that.
=> Reorganize dependencies in Cargo.toml for near-network

chain/client/src/client.rs
There are still some places where we should be using `Duration` in `PeerActor`.
=> Replace constants with Duration

chain/network/src/peer_manager/peer_manager_actor.rs, chain/network/src/routing/route_back_cache.rs, chain/network/src/routing/routing.rs, chain/network/src/routing/routing_table_actor.rs
Imports in many `near-network` files are not organized properly.
We usually follow order `std`, external packages, our packages, `crate::`
=> Reorganize imports in near-network

chain/network/src/peer_manager/peer_manager_actor.rs
Due to historical reasons, we have multiple  'impl PeerManagerActor' insider `peer_actor_manager.rs`. Let's move into one to improve code quality.
=> Refactor PeerManager to join multiple 'impl PeerManagerActor' into one

pytest/tests/runtime/fuzz.py
The fuzzing test will run until it finds a failure.  As a result, it
never terminates with success which leads NayDuck to interpret valid
runs as failures due to a timeout.  Change the test so that it kills
the command before NayDuck recognises the timeout.
=> pytest: add timeout to the runtime/fuzz.py test
